### ISSUE TITLE
pip3 install of notebook, jupyter or jupyter-core looking for nonexistent /lib dir

### ISSUE THREAD

**Issue by damienstanton** [jupyter/notebook#1081]
I am using OS X 10.11, Python 3.5.1 installed via brew.

```
$ pip3 install jupyter
Collecting jupyter
  Downloading jupyter-1.0.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): notebook in /usr/local/lib/python3.5/site-packages (from jupyter)
Requirement already satisfied (use --upgrade to upgrade): qtconsole in /usr/local/lib/python3.5/site-packages (from jupyter)
Requirement already satisfied (use --upgrade to upgrade): ipykernel in /usr/local/lib/python3.5/site-packages (from jupyter)
Requirement already satisfied (use --upgrade to upgrade): jupyter-console in /usr/local/lib/python3.5/site-packages (from jupyter)
Requirement already satisfied (use --upgrade to upgrade): ipywidgets in /usr/local/lib/python3.5/site-packages (from jupyter)
Requirement already satisfied (use --upgrade to upgrade): nbconvert in /usr/local/lib/python3.5/site-packages (from jupyter)
Collecting jupyter-core (from notebook->jupyter)
  Downloading jupyter_core-4.0.6-py2.py3-none-any.whl (74kB)
    100% |████████████████████████████████| 77kB 2.5MB/s
Requirement already satisfied (use --upgrade to upgrade): terminado>=0.3.3 in /usr/local/lib/python3.5/site-packages (from notebook->jupyter)
Requirement already satisfied (use --upgrade to upgrade): jupyter-client in /usr/local/lib/python3.5/site-packages (from notebook->jupyter)
Requirement already satisfied (use --upgrade to upgrade): ipython-genutils in /usr/local/lib/python3.5/site-packages (from notebook->jupyter)
Requirement already satisfied (use --upgrade to upgrade): jinja2 in /usr/local/lib/python3.5/site-packages (from notebook->jupyter)
Requirement already satisfied (use --upgrade to upgrade): traitlets in /usr/local/lib/python3.5/site-packages (from notebook->jupyter)
Requirement already satisfied (use --upgrade to upgrade): tornado>=4 in /usr/local/lib/python3.5/site-packages (from notebook->jupyter)
Requirement already satisfied (use --upgrade to upgrade): nbformat in /usr/local/lib/python3.5/site-packages (from notebook->jupyter)
Requirement already satisfied (use --upgrade to upgrade): pygments in /usr/local/lib/python3.5/site-packages (from qtconsole->jupyter)
Collecting ipython>=4.0.0 (from ipykernel->jupyter)
  Downloading ipython-4.1.1-py3-none-any.whl (737kB)
    100% |████████████████████████████████| 737kB 566kB/s
Requirement already satisfied (use --upgrade to upgrade): mistune!=0.6 in /usr/local/lib/python3.5/site-packages (from nbconvert->jupyter)
Requirement already satisfied (use --upgrade to upgrade): ptyprocess in /usr/local/lib/python3.5/site-packages (from terminado>=0.3.3->notebook->jupyter)
Requirement already satisfied (use --upgrade to upgrade): pyzmq>=13 in /usr/local/lib/python3.5/site-packages (from jupyter-client->notebook->jupyter)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /usr/local/lib/python3.5/site-packages (from jinja2->notebook->jupyter)
Requirement already satisfied (use --upgrade to upgrade): decorator in /usr/local/lib/python3.5/site-packages (from traitlets->notebook->jupyter)
Requirement already satisfied (use --upgrade to upgrade): jsonschema!=2.5.0,>=2.0 in /usr/local/lib/python3.5/site-packages (from nbformat->notebook->jupyter)
Requirement already satisfied (use --upgrade to upgrade): setuptools>=18.5 in /usr/local/lib/python3.5/site-packages (from ipython>=4.0.0->ipykernel->jupyter)
Requirement already satisfied (use --upgrade to upgrade): simplegeneric>0.8 in /usr/local/lib/python3.5/site-packages (from ipython>=4.0.0->ipykernel->jupyter)
Requirement already satisfied (use --upgrade to upgrade): pexpect in /usr/local/lib/python3.5/site-packages (from ipython>=4.0.0->ipykernel->jupyter)
Requirement already satisfied (use --upgrade to upgrade): pickleshare in /usr/local/lib/python3.5/site-packages (from ipython>=4.0.0->ipykernel->jupyter)
Requirement already satisfied (use --upgrade to upgrade): gnureadline in /usr/local/lib/python3.5/site-packages (from ipython>=4.0.0->ipykernel->jupyter)
Requirement already satisfied (use --upgrade to upgrade): appnope in /usr/local/lib/python3.5/site-packages (from ipython>=4.0.0->ipykernel->jupyter)
Requirement already satisfied (use --upgrade to upgrade): path.py in /usr/local/lib/python3.5/site-packages (from pickleshare->ipython>=4.0.0->ipykernel->jupyter)
Installing collected packages: jupyter, jupyter-core, ipython
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_set.py", line 731, in install
    **kwargs
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_install.py", line 841, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_install.py", line 1040, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.5/site-packages/pip/wheel.py", line 343, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python3.5/site-packages/pip/wheel.py", line 286, in clobber
    ensure_dir(dest)  # common for the 'include' path
  File "/usr/local/lib/python3.5/site-packages/pip/utils/__init__.py", line 82, in ensure_dir
    os.makedirs(path)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/lib'
```
If I create the dir and `chown` it, I get:
```
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_set.py", line 731, in install
    **kwargs
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_install.py", line 841, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.5/site-packages/pip/req/req_install.py", line 1040, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.5/site-packages/pip/wheel.py", line 375, in move_wheel_files
    clobber(source, dest, False, fixer=fixer, filter=filter)
  File "/usr/local/lib/python3.5/site-packages/pip/wheel.py", line 286, in clobber
    ensure_dir(dest)  # common for the 'include' path
  File "/usr/local/lib/python3.5/site-packages/pip/utils/__init__.py", line 82, in ensure_dir
    os.makedirs(path)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by damienstanton** [comment]
Oops, I had left a .pydistutils.cfg file in place that broke my pip3 installation process.

**Comment by interestinall** [comment]
good on you for putting the solution @damienstanton 👍
