### ISSUE TITLE
kernel error

### ISSUE THREAD

**Issue by haihan** [jupyter/notebook#1171]
I used `conda install jupyter`  to install without a problem. Then I open the jupyter notebook, kernel error appears. I also use `python -m IPython kernelspec install-self ` to reinstall kernel, but it cannot solve the problem
```

Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/notebook/base/handlers.py", line 458, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "//anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "//anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "//anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "//anaconda/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 58, in post
    sm.create_session(path=path, kernel_name=kernel_name))
  File "//anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "//anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "//anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "//anaconda/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 73, in create_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "//anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "//anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "//anaconda/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "//anaconda/lib/python2.7/site-packages/notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "//anaconda/lib/python2.7/site-packages/jupyter_client/multikernelmanager.py", line 109, in start_kernel
    km.start_kernel(**kwargs)
  File "//anaconda/lib/python2.7/site-packages/jupyter_client/manager.py", line 244, in start_kernel
    **kw)
  File "//anaconda/lib/python2.7/site-packages/jupyter_client/manager.py", line 190, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "//anaconda/lib/python2.7/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "//anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "//anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```

**Comment by minrk** [comment]
What do you get from `jupyter kernelspec list`?

**Comment by haihan** [comment]
Hello, this is what I got, thanks!
jupyter kernelspec list
Available kernels:
  julia-0.3    /Users/haihan/Library/Jupyter/kernels/julia-0.3
  python2      /Users/haihan/Library/Jupyter/kernels/python2

**Comment by takluyver** [comment]
Have a look in `/Users/haihan/Library/Jupyter/kernels/python2/kernel.json`. The first value in `argv` should be the path to a Python interpreter. What path has it got?

**Comment by haihan** [comment]
Hello， thanks for your replies. 
the first `argv` is `"/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python", ` thanks  a lot!

**Comment by ronteo** [comment]
I had the same issue resolved it by running 
python2 -m ipykernel install --user

**Comment by chisoo** [comment]
@ronteo I had the same issue and this fixed it. Thanks!

**Comment by ronteo** [comment]
@chisoo You are very welcome. Glad it worked!

**Comment by foarruda** [comment]
@ronteo this fixed my jupyter too. Thanks a lot!!

**Comment by aulon** [comment]
I have the same issue. 

After I check the `argv` path in my `kernel.json` what should I do?

**Comment by quoniammm** [comment]
Thanks

**Comment by saxenaPAWAN** [comment]
For Anaconnda users issue can be fixed by changing python.exe to pythonw.exe

**Comment by superghm** [comment]
> For Anaconnda users issue can be fixed by changing python.exe to pythonw.exe

@saxenaPAWAN worked like a charm! Thank you!
