### ISSUE TITLE
Could not find .egg-info directory 

### ISSUE THREAD

**Issue by jmarcellopereira** [jupyter/notebook#1224]
how to solve?

**Comment by takluyver** [comment]
You'll need to provide a bit more detail than that. What were you trying to do? What was the full error you saw?

**Comment by takluyver** [comment]
I see that you provided a bit more info in a mailing list post, but it's still not really enough to diagnose the problem.

**Comment by jmarcellopereira** [comment]
Hi takluyver
 no previously-included directories found matching 'docs/build'
    warning: no files found matching 'tornado/test/README'
  Could not find .egg-info directory in install record for tornado>=4.0 (from ipykernel->jupyter)
  Running setup.py install for terminado
    
  Could not find .egg-info directory in install record for terminado>=0.3.3; sys_platform != "win32" (from notebook->jupyter)
  Running setup.py install for simplegeneric
    
  Could not find .egg-info directory in install record for simplegeneric>0.8 (from ipython>=4.0.0dev0->ipywidgets->jupyter)
  Running setup.py install for pexpect
    
  Could not find .egg-info directory in install record for pexpect; sys_platform != "win32" (from ipython>=4.0.0dev0->ipywidgets->jupyter)
  Running setup.py install for MarkupSafe
    
    building 'markupsafe._speedups' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -c markupsafe/_speedups.c -o build/temp.linux-x86_64-3.4/markupsafe/_speedups.o
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.4/markupsafe/_speedups.o -o build/lib.linux-x86_64-3.4/markupsafe/_speedups.cpython-34m.so

  Could not find .egg-info directory in install record for MarkupSafe (from jinja2->nbconvert->jupyter)
  Running setup.py install for pyzmq

**Comment by minrk** [comment]
Those warnings may not be critical, but you can try making sure your setuptools and pip are up to date:

    pip install --upgrade setuptools pip

**Comment by axil** [comment]
@minrk Thanks! This solved the issue for me.

**Comment by ShunJianLee** [comment]
@axil @minrk 
may i know why this issues happened? 
pi@raspberrypi:~ $ sudo pip install --upgrade setuptools
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead

**Comment by takluyver** [comment]
I'm guessing you've updated requests to a newer version that doesn't match the version of pip on your system. That was possible in older versions of Debian/Ubuntu, but they fixed it in more recent versions. I guess you'll need to delete the newer copy of requests (probably in `/usr/local/lib/python2.7/dist-packages`), and then upgrade pip with `pip install --upgrade pip`.

It's recommended to use `pip install --user` instead of running pip with sudo.

**Comment by ShunJianLee** [comment]
@takluyver Thanks for your advise. how to identify whether which file & doc are newer copy of request?

**Comment by takluyver** [comment]
You're on a Debian-based system, right? (that includes Ubuntu, Mint, etc.) In that case, the packages the system installs using apt go in `/usr/lib`, and the packages you have installed separately are in `/usr/local/lib`. If there's a copy of requests in `/usr/local/lib`, then you should be able to safely remove it.

**Comment by ShunJianLee** [comment]
Bro @takluyver, i am Jessie-based system now as i shown on below. So i just need to delete whole file or which folders in the /usr/local/lib ? Thanks

PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by takluyver** [comment]
Probably `/usr/local/lib/python2.7/dist-packages/requests`, but it's hard to work these things out remotely.

**Comment by ShunJianLee** [comment]
@takluyver thanks

**Comment by axil** [comment]
You can try `import requests; print(requests.__file__)` to see which `requests` version is currently used (if you havn't already).

**Comment by jtpio** [comment]
Closing since this issue has been open and inactive for several years and there doesn't seem to be really anything to be done here in the notebook repository.

Don't hesitate to open a new issue if needed or if the problem persists, thanks!
