### ISSUE TITLE
 Unhandled error in API request

### ISSUE THREAD

**Issue by ChillarAnand** [jupyter/notebook#1236]
I have created a virtual env and installed jupyter using pip. When i started notebook, it is throwing this error.

```
$ jupyter notebook
[I 18:35:15.988 NotebookApp] Serving notebooks from local directory: /home/anand/projects/python/pycon/analysis
[I 18:35:15.989 NotebookApp] 0 active kernels 
[I 18:35:15.989 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 18:35:15.989 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Created new window in existing browser session.
[E 18:35:41.046 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/home/anand/.virtualenvs/exp/local/lib/python2.7/site-packages/notebook/base/handlers.py", line 436, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/home/anand/.virtualenvs/exp/local/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 56, in post
        model = sm.create_session(path=path, kernel_name=kernel_name)
      File "/home/anand/.virtualenvs/exp/local/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 66, in cr
eate_session
        kernel_name=kernel_name)
      File "/home/anand/.virtualenvs/exp/local/lib/python2.7/site-packages/notebook/services/kernels/kernelmanager.py", line 84, in start_kernel
        **kwargs)
      File "/home/anand/.virtualenvs/exp/local/lib/python2.7/site-packages/jupyter_client/multikernelmanager.py", line 109, in start_kernel
        km.start_kernel(**kwargs)
      File "/home/anand/.virtualenvs/exp/local/lib/python2.7/site-packages/jupyter_client/manager.py", line 239, in start_kernel
        **kw)
      File "/home/anand/.virtualenvs/exp/local/lib/python2.7/site-packages/jupyter_client/manager.py", line 186, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "/home/anand/.virtualenvs/exp/local/lib/python2.7/site-packages/jupyter_client/launcher.py", line 119, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
[E 18:35:41.121 NotebookApp] {
      "Origin": "http://localhost:8888", 
      "Content-Length": "79", 
      "Accept-Language": "en-US,en;q=0.8,ms;q=0.6,te;q=0.4", 
      "Accept-Encoding": "gzip, deflate", 
      "Connection": "keep-alive", 
      "Accept": "application/json, text/javascript, */*; q=0.01", 
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36", 
      "Host": "localhost:8888", 
      "X-Requested-With": "XMLHttpRequest", 
      "Referer": "http://localhost:8888/notebooks/pycon_india.ipynb", 
      "Content-Type": "application/json"
    }
[E 18:35:41.125 NotebookApp] 500 POST /api/sessions (127.0.0.1) 159.31ms referer=http://localhost:8888/notebooks/pycon_india.ipynb

**Comment by minrk** [comment]
What do you get from `jupyter kernelspec list`? My guess is that you have a kernelspec installed for an env that doesn't exist anymore.

**Comment by ChillarAnand** [comment]
@minrk  here is output

```
$ jupyter kernelspec list
Available kernels:
  django_extensions
  python2
```

**Comment by willingc** [comment]
@ChillarAnand Let's see if we can get a bit more detail to help you. Would you please share the output of the following two commands:
```
jupyter kernelspec list --debug
```

and

```
jupyter notebook --debug
```

Thanks.

**Comment by minrk** [comment]
You might also want to upgrade jupyter-client:

    pip install --upgrade jupyter-client

You can try installing the kernelspec for the virtualenv explicitly:

```bash
ipython kernel install --prefix "$VIRTUAL_ENV"
```

**Comment by ChillarAnand** [comment]
I have restarted system and not able to reproduce this. Thanks for the help.

**Comment by henryon** [comment]
I faced the same issues on our system. and followed all the comments. still got exceptions.
Any ideas?
Detail logs###############
[W 03:42:30.634 NotebookApp] Notebook user/hadua/Crawle to Files.ipynb is not trusted
[I 03:42:31.585 NotebookApp] Kernel started: fd8aae45-30bc-4c81-99d1-2d2f3b751745
[E 03:42:31.586 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/notebook/base/handlers.py", line 457, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 62, in post
        kernel_id=kernel_id))
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
        yielded = self.gen.send(value)
      File "/usr/local/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 81, in create_session
        self.save_session(session_id, path=path, kernel_id=kernel_id)
      File "/usr/local/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 121, in save_session
        return self.get_session(session_id=session_id)
      File "/usr/local/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 152, in get_session
        self.cursor.execute(query, list(kwargs.values()))
    "OperationalError: Could not decode to UTF-8 column 'kernel_id' with text '\xf9\x80\x81\xa6\xf8\x90\x80\xb8\xf9\x90\x81\xa1\xfd\x90\x80\xb4\xfc\xb0\x80\xad\xf8\xa0\x80\xb0\xfb\x90\x81\xa3\xf8\xb0\x80\xb4\xfc\x90\x80\xb8\xfe\x90\x80\xad\xf9\x80\x80\xb9\xfb\x90\x80\xb1\xf9\x80\x80\xb2\xf9\xa0\x80\xb2\xf8\xa0\x80\xb3\xfd\x90\x80\xb7\xfd\xb0\x80\xb1\xfd\x90\x80\xb4'"
