### ISSUE TITLE
freebsd juypter notebook setup 

### ISSUE THREAD

**Issue by jungle-boogie** [jupyter/notebook#1307]
Hello,

How exactly can I get juypter running with freeBSD 10.2 for a notebook server?
http://jupyter-notebook.readthedocs.org/en/latest/public_server.html

basic steps are:
0. install python3
1. install pip3
2. install juypter
3. generate the config: `jupyter notebook --generate-config`

installation of all things juypter:
```
% sudo pip3 install -U pip
Collecting pip
  Downloading pip-8.1.1-py2.py3-none-any.whl (1.2MB)
    100% |################################| 1.2MB 188kB/s 
Installing collected packages: pip
  Found existing installation: pip 7.1.2
    Uninstalling pip-7.1.2:
      Successfully uninstalled pip-7.1.2
Successfully installed pip-8.1.1
vagrant@:~ % 
vagrant@:~ % sudo pip3 install -U jupyter
Collecting jupyter
  Downloading jupyter-1.0.0-py2.py3-none-any.whl
Collecting jupyter-console (from jupyter)
  Downloading jupyter_console-4.1.1-py2.py3-none-any.whl
Collecting qtconsole (from jupyter)
  Downloading qtconsole-4.2.1-py2.py3-none-any.whl (104kB)
    100% |################################| 112kB 1.1MB/s 
Collecting ipywidgets (from jupyter)
  Downloading ipywidgets-4.1.1-py2.py3-none-any.whl (117kB)
    100% |################################| 122kB 1.8MB/s 
Collecting notebook (from jupyter)
  Downloading notebook-4.1.0-py2.py3-none-any.whl (5.7MB)
    100% |################################| 5.7MB 100kB/s 
Collecting nbconvert (from jupyter)
  Downloading nbconvert-4.1.0-py2.py3-none-any.whl (281kB)
    100% |################################| 286kB 1.7MB/s 
Collecting ipykernel (from jupyter)
  Downloading ipykernel-4.3.1-py2.py3-none-any.whl (93kB)
    100% |################################| 102kB 2.2MB/s 
Collecting ipython (from jupyter-console->jupyter)
  Downloading ipython-4.1.2-py3-none-any.whl (736kB)
    100% |################################| 737kB 730kB/s 
Collecting jupyter-client (from jupyter-console->jupyter)
  Downloading jupyter_client-4.2.2-py2.py3-none-any.whl (76kB)
    100% |################################| 81kB 1.9MB/s 
Collecting traitlets (from qtconsole->jupyter)
  Downloading traitlets-4.2.1-py2.py3-none-any.whl (67kB)
    100% |################################| 71kB 3.6MB/s 
Collecting jupyter-core (from qtconsole->jupyter)
  Downloading jupyter_core-4.1.0-py2.py3-none-any.whl (76kB)
    100% |################################| 81kB 3.2MB/s 
Collecting pygments (from qtconsole->jupyter)
  Downloading Pygments-2.1.3-py2.py3-none-any.whl (755kB)
    100% |################################| 757kB 738kB/s 
Collecting ipython-genutils (from notebook->jupyter)
  Downloading ipython_genutils-0.1.0-py2.py3-none-any.whl
Collecting terminado>=0.3.3 (from notebook->jupyter)
  Downloading terminado-0.6.tar.gz
Collecting tornado>=4 (from notebook->jupyter)
  Downloading tornado-4.3.tar.gz (450kB)
    100% |################################| 460kB 1.1MB/s 
Collecting jinja2 (from notebook->jupyter)
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
    100% |################################| 266kB 2.3MB/s 
Collecting nbformat (from notebook->jupyter)
  Downloading nbformat-4.0.1-py2.py3-none-any.whl (138kB)
    100% |################################| 143kB 2.8MB/s 
Collecting mistune!=0.6 (from nbconvert->jupyter)
  Downloading mistune-0.7.2-py2.py3-none-any.whl
Collecting pickleshare (from ipython->jupyter-console->jupyter)
  Downloading pickleshare-0.6-py2.py3-none-any.whl
Collecting pexpect (from ipython->jupyter-console->jupyter)
  Downloading pexpect-4.0.1.tar.gz (143kB)
    100% |################################| 153kB 2.7MB/s 
Collecting setuptools>=18.5 (from ipython->jupyter-console->jupyter)
  Downloading setuptools-20.6.7-py2.py3-none-any.whl (508kB)
    100% |################################| 512kB 969kB/s 
Collecting decorator (from ipython->jupyter-console->jupyter)
  Downloading decorator-4.0.9-py2.py3-none-any.whl
Collecting simplegeneric>0.8 (from ipython->jupyter-console->jupyter)
  Downloading simplegeneric-0.8.1.zip
Collecting pyzmq>=13 (from jupyter-client->jupyter-console->jupyter)
  Downloading pyzmq-15.2.0.tar.gz (1.1MB)
    100% |################################| 1.1MB 508kB/s 
Collecting ptyprocess (from terminado>=0.3.3->notebook->jupyter)
  Downloading ptyprocess-0.5.1-py2.py3-none-any.whl
Collecting backports-abc>=0.4 (from tornado>=4->notebook->jupyter)
  Downloading backports_abc-0.4-py2.py3-none-any.whl
Collecting MarkupSafe (from jinja2->notebook->jupyter)
  Downloading MarkupSafe-0.23.tar.gz
Collecting jsonschema!=2.5.0,>=2.0 (from nbformat->notebook->jupyter)
  Downloading jsonschema-2.5.1-py2.py3-none-any.whl
Collecting path.py>=6.2 (from pickleshare->ipython->jupyter-console->jupyter)
  Downloading path.py-8.1.2-py2.py3-none-any.whl
Installing collected packages: path.py, pickleshare, ptyprocess, pexpect, setuptools, decorator, ipython-genutils, traitlets, simplegeneric, ipython, pyzmq, jupyter-core, jupyter-client, backports-abc, tornado, ipykernel, jupyter-console, pygments, qtconsole, terminado, mistune, MarkupSafe, jinja2, jsonschema, nbformat, nbconvert, notebook, ipywidgets, jupyter
  Running setup.py install for pexpect ... done
  Found existing installation: setuptools 18.2
    Uninstalling setuptools-18.2:
      Successfully uninstalled setuptools-18.2
  Running setup.py install for simplegeneric ... done
  Running setup.py install for pyzmq ... done
  Running setup.py install for tornado ... done
  Running setup.py install for terminado ... done
  Running setup.py install for MarkupSafe ... done
Successfully installed MarkupSafe-0.23 backports-abc-0.4 decorator-4.0.9 ipykernel-4.3.1 ipython-4.1.2 ipython-genutils-0.1.0 ipywidgets-4.1.1 jinja2-2.8 jsonschema-2.5.1 jupyter-1.0.0 jupyter-client-4.2.2 jupyter-console-4.1.1 jupyter-core-4.1.0 mistune-0.7.2 nbconvert-4.1.0 nbformat-4.0.1 notebook-4.1.0 path.py-8.1.2 pexpect-4.0.1 pickleshare-0.6 ptyprocess-0.5.1 pygments-2.1.3 pyzmq-15.2.0 qtconsole-4.2.1 setuptools-20.6.7 simplegeneric-0.8.1 terminado-0.6 tornado-4.3 tr
```

launching:
```
% jupyter
usage: jupyter [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
               [--paths] [--json]
               [subcommand]
jupyter: error: one of the arguments --version subcommand --config-dir --data-dir --runtime-dir --paths is required
```

So far so good until we want to config for notebook server usage.

```
% jupyter notebook --generate-config
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/usr/local/lib/python3.4/site-packages/notebook/notebookapp.py", line 63, in <module>
    from .services.sessions.sessionmanager import SessionManager
  File "/usr/local/lib/python3.4/site-packages/notebook/services/sessions/sessionmanager.py", line 7, in <module>
    import sqlite3
  File "/usr/local/lib/python3.4/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.4/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3'
```

installing this doesn't resolve the issue:
https://www.freshports.org/databases/py-sqlite3/

**Comment by takluyver** [comment]
Sounds like Python got built without sqlite. Ipython has fallbacks, but the
notebook server assumes the standard library is all there.

**Comment by jungle-boogie** [comment]
> Sounds like Python got built without sqlite.

Looks like you're right:
```
vagrant@:~ % python3
Python 3.4.4 (default, Mar 19 2016, 01:14:08) 
[GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)] on freebsd10
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.4/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3'
```

know of any method to get around this?

**Comment by takluyver** [comment]
Did you compile Python yourself? If so, ensure the sqlite development
headers are installed before building it.

**Comment by jungle-boogie** [comment]
> Did you compile Python yourself?

No, from freebsd pkg:
http://www.freshports.org/lang/python3/

No mention of sqlite3 as a build or run time dependency.

**Comment by willingc** [comment]
@jungle-boogie This may help you https://forums.freebsd.org/threads/53114/

**Comment by jungle-boogie** [comment]
So I installed that package but still not running. Probably need to install the port and make against python?

http://www.freshports.org/databases/py-sqlite3

**Comment by willingc** [comment]
It appears from the thread above that you would need to:

1. Navigate to /usr/ports/databases/py-sqlite3 directory, then run:
    ``make clean``
2. Then run:
    ``make PYTHON_VERSION=python3.4 install``

Caution: The packages and messages refer to very dated versions of py-sqlite3 and the messages themselves are quite old. I wonder if there may be a better solution out there.

You may wish to try https://docs.python.org/3.5/using/unix.html#on-freebsd-and-openbsd to install Python 3.5.

**Comment by minrk** [comment]
I added the same fallback we use elsewhere in #1310, which means you will be able to get a non-stdlib implementation by doing `pip install pysqlite2`.

On my FreeBSD 10 machine, I was able to get the stdlib sqlite3 for Python 3.4 with:

    sudo pkg install py34-sqlite3

I'm not sure why that's not included by default.

**Comment by jungle-boogie** [comment]
> On my FreeBSD 10 machine, I was able to get the stdlib sqlite3 for Python 3.4 with:

That works!

```
% jupyter notebook --generate-config
Writing default config to: /usr/home/sean/.jupyter/jupyter_notebook_config.py
```

Thanks for the input.

**Comment by willingc** [comment]
@minrk Thanks! @jungle-boogie I'm glad Min had the solution for you :+1:

**Comment by jungle-boogie** [comment]
Would you take a PR for updating the docs, @willingc? Maybe you don't want to get too OS specific, though.

**Comment by willingc** [comment]
I would welcome a PR, @jungle-boogie. Although the team is trying to keep the installation instructions simple and more generic, I think a PR against the [Developer FAQ](https://github.com/jupyter/notebook/blob/master/docs/source/development_faq.rst) would be a good place to put a PR explaining how to get running on FreeBSD10. Likely it will be a more advanced person using FreeBSD, so a FAQ entry would be discoverable via search. Thanks!
