### ISSUE TITLE
Kernel crashes upon creation of a new notebook if cwd contains 'parser.py'

### ISSUE THREAD

**Issue by evanmiltenburg** [jupyter/notebook#1346]
I had a file called 'parser.py' in the same directory as where I started the Jupyter notebook. When I opened a new notebook, it produced a series of errors and unsuccessful restarts of the kernel. Here's the relevant part of the output:

    [I 12:57:56.639 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
    [I 12:57:56.639 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
    [I 12:58:02.151 NotebookApp] Kernel started: a921ebc8-3312-48d0-9d64-c03dd652249a
    Traceback (most recent call last):
      File "/Applications/anaconda/lib/python3.5/site-packages/path.py", line 122, in <module>
        import pkg_resources
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "/Applications/anaconda/lib/python3.5/site-packages/setuptools-20.3-py3.5.egg/pkg_resources/__init__.py", line 71, in <module>
      File "/Users/Emiel/PhD/Repositories/Work/parser.py", line 46
        except StopIteration, e:
                            ^
    SyntaxError: invalid syntax

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Applications/anaconda/lib/python3.5/runpy.py", line 151, in _run_module_as_main
        mod_name, mod_spec, code = _get_module_details(mod_name)
      File "/Applications/anaconda/lib/python3.5/runpy.py", line 118, in _get_module_details
        return _get_module_details(pkg_main_name)
      File "/Applications/anaconda/lib/python3.5/runpy.py", line 104, in _get_module_details
        spec = importlib.util.find_spec(mod_name)
      File "/Applications/anaconda/lib/python3.5/importlib/util.py", line 88, in find_spec
        parent = __import__(parent_name, fromlist=['__path__'])
      File "/Applications/anaconda/lib/python3.5/site-packages/ipykernel/__init__.py", line 2, in <module>
        from .connect import *
      File "/Applications/anaconda/lib/python3.5/site-packages/ipykernel/connect.py", line 13, in <module>
        from IPython.core.profiledir import ProfileDir
      File "/Applications/anaconda/lib/python3.5/site-packages/IPython/__init__.py", line 49, in <module>
        from .terminal.embed import embed
      File "/Applications/anaconda/lib/python3.5/site-packages/IPython/terminal/embed.py", line 16, in <module>
        from IPython.core.interactiveshell import DummyMod
      File "/Applications/anaconda/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 31, in <module>
        from pickleshare import PickleShareDB
      File "/Applications/anaconda/lib/python3.5/site-packages/pickleshare.py", line 41, in <module>
        from path import path as Path
      File "/Applications/anaconda/lib/python3.5/site-packages/path.py", line 126, in <module>
        except pkg_resources.DistributionNotFound:
    NameError: name 'pkg_resources' is not defined
    [I 12:58:05.151 NotebookApp] KernelRestarter: restarting kernel (1/5)
    Traceback (most recent call last):
      File "/Applications/anaconda/lib/python3.5/site-packages/path.py", line 122, in <module>
        import pkg_resources
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
      File "/Applications/anaconda/lib/python3.5/site-packages/setuptools-20.3-py3.5.egg/pkg_resources/__init__.py", line 71, in <module>
      File "/Users/Emiel/PhD/Repositories/Work/parser.py", line 46
        except StopIteration, e:
                            ^
    SyntaxError: invalid syntax

    During handling of the above exception, another exception occurred:

...and so on. A colleague of mine was able to reproduce this error with the same folder containing `parser.py`.

**Comment by takluyver** [comment]
If a local file has the same name as a module that something else is relying on, you can generally expect problems. In this case, however, that import was unnecessary, and if you upgrade setuptools, the issue should disappear.
