### ISSUE TITLE
WindowsError: [Error 5] Access is denied 

### ISSUE THREAD

**Issue by evbettor** [jupyter/notebook#1385]
Jupyter notebook not launching, giving me Access is denied.  First tried as admin, then reinstalled as a user and get the same error.
`
WindowsError: [Error 5] Access is denied
 `

Launching Python can get into that.  Any idea how to fix?  I have checked the environment PATH variables and the Anaconda folders are in.

**Comment by takluyver** [comment]
Is there any traceback with that error? Are both `jupyter.exe` and `jupyter-notebook.exe` present in a folder on %PATH%?

**Comment by evbettor** [comment]
Thanks for the question.  

Yes, jupyter.exe and jupyter-notebook.exe's in the Anaconda2/Scripts folder.

Full error below:
```
Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\jupyter-notebook-script.py", line 5, in <module>
    sys.exit(notebook.notebookapp.main())
  File "C:\Anaconda2\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Anaconda2\lib\site-packages\traitlets\config\application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "C:\Anaconda2\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Anaconda2\lib\site-packages\notebook\notebookapp.py", line 1017, in initialize
    super(NotebookApp, self).initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "C:\Anaconda2\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Anaconda2\lib\site-packages\jupyter_core\application.py", line 243, in initialize
    self.migrate_config()
  File "C:\Anaconda2\lib\site-packages\jupyter_core\application.py", line 169, in migrate_config
    migrate()
  File "C:\Anaconda2\lib\site-packages\jupyter_core\migrate.py", line 240, in migrate
    ensure_dir_exists(env['jupyter_config'])
  File "C:\Anaconda2\lib\site-packages\ipython_genutils\path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "C:\Anaconda2\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "C:\Anaconda2\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 5] Access is denied: 'c:\\Users\\admin'
```

**Comment by takluyver** [comment]
I think it's detecting `C:\Users\admin` as your home directory, but you don't have write permissions there, or possibly it doesn't exist. Have you set any environment variables like `HOME` or `HOMEPATH`?

**Comment by evbettor** [comment]
The `HOME` is set as c:\users\admin, but when i look for that folder it does not exist...Should I set to something else?

Thanks!

**Comment by evbettor** [comment]
Cool, that worked by switching the PATH.  Thanks man! you are cool

**Comment by takluyver** [comment]
No problem. Closing this as a configuration issue - I think it's generally safe to assume that $HOME exists.

**Comment by smnh245** [comment]
try to run as admin

**Comment by takluyver** [comment]
We don't recommend running the notebook server as admin.

**Comment by saketrule** [comment]
I am trying to run jupyter in a virtualenv I made. Can someone help me with my error? Thanks

(jupytertest) Sakets-MacBook-Air:.virtualenvs saket$ cd ..
(jupytertest) Sakets-MacBook-Air:~ saket$ jupyter notebook
[I 10:52:18.095 NotebookApp] Writing notebook server cookie secret to /Users/saket/Library/Jupyter/runtime/notebook_cookie_secret
Traceback (most recent call last):
  File "/Users/saket/.virtualenvs/jupytertest/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/Users/saket/.virtualenvs/jupytertest/lib/python2.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/saket/.virtualenvs/jupytertest/lib/python2.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/Users/saket/.virtualenvs/jupytertest/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/saket/.virtualenvs/jupytertest/lib/python2.7/site-packages/notebook/notebookapp.py", line 1368, in initialize
    self.init_webapp()
  File "/Users/saket/.virtualenvs/jupytertest/lib/python2.7/site-packages/notebook/notebookapp.py", line 1161, in init_webapp
    self.jinja_environment_options
  File "/Users/saket/.virtualenvs/jupytertest/lib/python2.7/site-packages/notebook/notebookapp.py", line 154, in __init__
    base_url, default_url, settings_overrides, jinja_env_options)
  File "/Users/saket/.virtualenvs/jupytertest/lib/python2.7/site-packages/notebook/notebookapp.py", line 245, in init_settings
    cookie_secret=jupyter_app.cookie_secret,
  File "/Users/saket/.virtualenvs/jupytertest/lib/python2.7/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/Users/saket/.virtualenvs/jupytertest/lib/python2.7/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/Users/saket/.virtualenvs/jupytertest/lib/python2.7/site-packages/notebook/notebookapp.py", line 630, in _default_cookie_secret
    self._write_cookie_secret_file(secret)
  File "/Users/saket/.virtualenvs/jupytertest/lib/python2.7/site-packages/notebook/notebookapp.py", line 636, in _write_cookie_secret_file
    with io.open(self.cookie_secret_file, 'wb') as f:
IOError: [Errno 13] Permission denied: '/Users/saket/Library/Jupyter/runtime/notebook_cookie_secret'
(jupytertest) Sakets-MacBook-Air:~ saket$

**Comment by patanupam4** [comment]
I do not have a HOME or HOMEPATH set in the environment variable and I still get the same errors and how do I trace the logs?

**Comment by Hmada96ariqat** [comment]
> try to run as admin

Worked for me, Thanks

**Comment by abhi3700** [comment]
Simply do this:
```console
python -m jupyterlab
```

**Comment by Midhilesh4890** [comment]
Lot of solutions are [here](https://stackoverflow.com/questions/60769214/how-to-solve-winerror-5-access-is-denied-in-anaconda-prompt)

@abhi3700  solution is the easiest one
