### ISSUE TITLE
install_nbextension_python fails during ipywidgets installation

### ISSUE THREAD

**Issue by nastasi-oq** [jupyter/notebook#1401]
This diff for file ``notebook/nbextensions.py`` introduced here:  e1eacf8d25256c6353a8177d23e679944fb12bc0
```
git diff e1eacf8d25256c6353a8177d23e679944fb12bc0^ e1eacf8d25256c6353a8177d23e679944fb12bc0 notebook/nbextensions.py
diff --git a/notebook/nbextensions.py b/notebook/nbextensions.py
index 2b5ac22..4582d39 100644
--- a/notebook/nbextensions.py
+++ b/notebook/nbextensions.py
@@ -701,6 +701,7 @@ class InstallNBExtensionApp(BaseNBExtensionApp):
         install = install_nbextension_python if self.python else install_nbextension
         
         full_dests = install(self.extra_args[0],
+                             destination=self.destination,
                              overwrite=self.overwrite,
                              symlink=self.symlink,
                              user=self.user,
```
 breaks the installation of *ipywidgets* packages probably because the corresponding entry 
```python
def install_nbextension_python(module, overwrite=False, symlink=False,
                        user=False, sys_prefix=False, prefix=None, nbextensions_dir=None, logger=None):
```
is not aligned with this change.

The error retrieved is: 
```python
Traceback (most recent call last):
  File "/home/nastasi/.virtualenvs/ipywidgets/bin/jupyter-nbextension", line 9, in <module>
    load_entry_point('notebook', 'console_scripts', 'jupyter-nbextension')()
  File "/home/nastasi/ipywidgets/jupyter_core/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/nastasi/.virtualenvs/ipywidgets/local/lib/python2.7/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/home/nastasi/ipywidgets/notebook/notebook/nbextensions.py", line 953, in start
    super(NBExtensionApp, self).start()
  File "/home/nastasi/ipywidgets/jupyter_core/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/home/nastasi/ipywidgets/notebook/notebook/nbextensions.py", line 731, in start
    self.install_extensions()
  File "/home/nastasi/ipywidgets/notebook/notebook/nbextensions.py", line 711, in install_extensions
    logger=self.log)
TypeError: install_nbextension_python() got an unexpected keyword argument 'destination'
```

**Comment by takluyver** [comment]
Thanks, do you have a couple of minutes to test #1403, which should fix this?

**Comment by nastasi-oq** [comment]
Too late, I'm on the train now, I will try tomorrow morning (CEST timezone)
Il 28/Apr/2016 18:24, "Thomas Kluyver" <notifications@github.com> ha
scritto:

**Comment by takluyver** [comment]
Tomorrow morning should be fine. :-)
