### ISSUE TITLE
Can't create a new python 3 notebook in python 3 virtualenv (tries to write to /usr/share)

### ISSUE THREAD

**Issue by eco32i** [jupyter/notebook#1457]
Fresh install of Ubuntu 16.04, fresh python 3 virtualenv. 

```
(pydata3) ilya@barmalei:~$ jupyter notebook
/home/ilya/.venv/pydata3/lib/python3.5/site-packages/widgetsnbextension/__init__.py:30: UserWarning: To use the jupyter-js-widgets nbextension, you'll need to update
    the Jupyter notebook to version 4.2 or later.
  the Jupyter notebook to version 4.2 or later.""")
[I 23:14:11.199 NotebookApp] Serving notebooks from local directory: /home/ilya
[I 23:14:11.199 NotebookApp] 0 active kernels 
[I 23:14:11.199 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 23:14:11.199 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
touch: cannot touch '/usr/share/mimeapps.list': Permission denied
Created new window in existing browser session.
[I 23:14:17.831 NotebookApp] Creating new notebook in 
[E 23:14:17.836 NotebookApp] Error while saving file: Untitled.ipynb [Errno 13] Permission denied: '/usr/share/jupyter'
    Traceback (most recent call last):
      File "/home/ilya/.venv/pydata3/lib/python3.5/site-packages/traitlets/traitlets.py", line 501, in get
        value = obj._trait_values[self.name]
    KeyError: 'secret'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ilya/.venv/pydata3/lib/python3.5/site-packages/traitlets/traitlets.py", line 501, in get
        value = obj._trait_values[self.name]
    KeyError: 'secret_file'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ilya/.venv/pydata3/lib/python3.5/site-packages/traitlets/traitlets.py", line 501, in get
        value = obj._trait_values[self.name]
    KeyError: 'data_dir'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ilya/.venv/pydata3/lib/python3.5/site-packages/traitlets/traitlets.py", line 501, in get
        value = obj._trait_values[self.name]
    KeyError: 'data_dir'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ilya/.venv/pydata3/lib/python3.5/site-packages/notebook/services/contents/filemanager.py", line 395, in save
        self.check_and_sign(nb, path)
      File "/home/ilya/.venv/pydata3/lib/python3.5/site-packages/notebook/services/contents/manager.py", line 431, in check_and_sign
        self.notary.sign(nb)
      File "/home/ilya/.venv/pydata3/lib/python3.5/site-packages/nbformat/sign.py", line 245, in sign
        signature = self.compute_signature(nb)
      File "/home/ilya/.venv/pydata3/lib/python3.5/site-packages/nbformat/sign.py", line 195, in compute_signature
        hmac = HMAC(self.secret, digestmod=self.digestmod)
      File "/home/ilya/.venv/pydata3/lib/python3.5/site-packages/traitlets/traitlets.py", line 529, in __get__
        return self.get(obj, cls)
      File "/home/ilya/.venv/pydata3/lib/python3.5/site-packages/traitlets/traitlets.py", line 508, in get
        value = self._validate(obj, dynamic_default())
      File "/home/ilya/.venv/pydata3/lib/python3.5/site-packages/nbformat/sign.py", line 168, in _secret_default
        if os.path.exists(self.secret_file):
      File "/home/ilya/.venv/pydata3/lib/python3.5/site-packages/traitlets/traitlets.py", line 529, in __get__
        return self.get(obj, cls)
      File "/home/ilya/.venv/pydata3/lib/python3.5/site-packages/traitlets/traitlets.py", line 508, in get
        value = self._validate(obj, dynamic_default())
      File "/home/ilya/.venv/pydata3/lib/python3.5/site-packages/nbformat/sign.py", line 159, in _secret_file_default
        if not self.data_dir:
      File "/home/ilya/.venv/pydata3/lib/python3.5/site-packages/traitlets/traitlets.py", line 529, in __get__
        return self.get(obj, cls)
      File "/home/ilya/.venv/pydata3/lib/python3.5/site-packages/traitlets/traitlets.py", line 508, in get
        value = self._validate(obj, dynamic_default())
      File "/home/ilya/.venv/pydata3/lib/python3.5/site-packages/nbformat/sign.py", line 101, in _data_dir_default
        return app.data_dir
      File "/home/ilya/.venv/pydata3/lib/python3.5/site-packages/traitlets/traitlets.py", line 529, in __get__
        return self.get(obj, cls)
      File "/home/ilya/.venv/pydata3/lib/python3.5/site-packages/traitlets/traitlets.py", line 508, in get
        value = self._validate(obj, dynamic_default())
      File "/home/ilya/.venv/pydata3/lib/python3.5/site-packages/jupyter_core/application.py", line 93, in _data_dir_default
        ensure_dir_exists(d, mode=0o700)
      File "/home/ilya/.venv/pydata3/lib/python3.5/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
        os.makedirs(path, mode=mode)
      File "/usr/lib/python3.5/os.py", line 241, in makedirs
        mkdir(name, mode)
    PermissionError: [Errno 13] Permission denied: '/usr/share/jupyter'
[W 23:14:17.838 NotebookApp] Unexpected error while saving file: Untitled.ipynb [Errno 13] Permission denied: '/usr/share/jupyter'
[E 23:14:17.839 NotebookApp] {
      "Accept-Encoding": "gzip, deflate",
      "Host": "localhost:8888",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Content-Length": "19",
      "Accept-Language": "en-US,en;q=0.8,ru;q=0.6,he;q=0.4",
      "Connection": "keep-alive",
      "Origin": "http://localhost:8888",
      "Dnt": "1",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.47 Safari/537.36",
      "Content-Type": "application/json",
      "Referer": "http://localhost:8888/tree",
      "X-Requested-With": "XMLHttpRequest"
    }
[E 23:14:17.839 NotebookApp] 500 POST /api/contents (127.0.0.1) 8.78ms referer=http://localhost:8888/tree
```

So it looks like it tries to write to `/usr/share` and fails. No `.local/share/jupyter` directory is created during install. There is '.venv/share/jupyter`, but it doesn't seem to be seen by notebook for some reason.

**Comment by takluyver** [comment]
Do you have either of the environment variables $JUPYTER_DATA_DIR or $XDG_DATA_HOME set?

**Comment by eco32i** [comment]
$XDG_DATA_HOME was set to `/usr/share`, $JUPYTER_DATA_DIR wasn't set. Setting it to `~/.local/share/jupyter` fixed the issue. Is there a way to make sure it is set during the installation?

**Comment by takluyver** [comment]
XDG_DATA_HOME should be set to somewhere that's user writable - or not set at all, because the default is `~/.local/share`. I'd work out what's setting it to `/usr/share` and fix that.

**Comment by eco32i** [comment]
Yes, this is my fault - I changed XDG_DATA_HOME in `.bashrc` when I was troubleshooting `dmenu-desktop` issues and forgot to remove it. I guees this can be closed now.

Thanks for the help!

**Comment by takluyver** [comment]
No problem - glad it got fixed.
