### ISSUE TITLE
Dead kernel for Python2 after installing itorch and irkernel

### ISSUE THREAD

**Issue by eneskemalergin** [jupyter/notebook#1462]
I am using anaconda2 with itorch and ir kernel. Before installing itorch and ir there was no problem working with ipython. Now I am trying to run python kernel but it throws the following error:
```
[I 15:54:17.322 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel c1ea6e88-9781-4f96-82bf-fd2296b7cb6b restarted
Traceback (most recent call last):
  File "/home/enes/anaconda2/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/enes/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/enes/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/enes/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-122>", line 2, in initialize
  File "/home/enes/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/enes/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 421, in initialize
    self.init_kernel()
  File "/home/enes/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 360, in init_kernel
    user_ns=self.user_ns,
  File "/home/enes/anaconda2/lib/python2.7/site-packages/traitlets/config/configurable.py", line 405, in instance
    inst = cls(*args, **kwargs)
  File "/home/enes/anaconda2/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 46, in __init__
    kernel      = self,
  File "/home/enes/anaconda2/lib/python2.7/site-packages/traitlets/config/configurable.py", line 405, in instance
    inst = cls(*args, **kwargs)
  File "/home/enes/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 463, in __init__
    self.db = PickleShareDB(os.path.join(self.profile_dir.location, 'db'))
  File "/home/enes/anaconda2/lib/python2.7/site-packages/pickleshare.py", line 63, in __init__
    self.root.makedirs_p()
AttributeError: 'path' object has no attribute 'makedirs_p'
```

Here is the kernel list:

```
Available kernels:
  python2    /home/enes/anaconda2/lib/python2.7/site-packages/ipykernel/resources
  itorch     /home/enes/.local/share/jupyter/kernels/itorch
  ir         /home/enes/anaconda2/share/jupyter/kernels/ir
```

How can I solve this problem?

**Comment by takluyver** [comment]
I'm not quite sure what has happened, but I think upgrading pickleshare should fix it:

```
pip install --upgrade pickleshare
```

**Comment by eneskemalergin** [comment]
that's solved my problem. Thanks!
