### ISSUE TITLE
jupyter kernelspec list

### ISSUE THREAD

**Issue by jrounds** [jupyter/notebook#1477]
Installed on Mac via Anaconda.  Jupyter notebook starts but I wanted to use a custom kernel with a virtualenv and not sure where to start with this error:
```
:~ $ jupyter kernelspec list
Traceback (most recent call last):
  File "/Users/roun308/anaconda/bin/jupyter-kernelspec", line 8, in <module>
    main()
  File "/Users/roun308/anaconda/bin/jupyter-kernelspec", line 5, in main
    KernelSpecApp.launch_instance()
  File "/Users/roun308/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/Users/roun308/anaconda/lib/python2.7/site-packages/jupyter_client/kernelspecapp.py", line 269, in start
    return self.subapp.start()
  File "/Users/roun308/anaconda/lib/python2.7/site-packages/jupyter_client/kernelspecapp.py", line 44, in start
    specs = self.kernel_spec_manager.get_all_specs()
  File "/Users/roun308/anaconda/lib/python2.7/site-packages/jupyter_client/kernelspec.py", line 196, in get_all_specs
    } for kname in d}
  File "/Users/roun308/anaconda/lib/python2.7/site-packages/jupyter_client/kernelspec.py", line 196, in <dictcomp>
    } for kname in d}
  File "/Users/roun308/anaconda/lib/python2.7/site-packages/jupyter_client/kernelspec.py", line 164, in _get_kernel_spec_by_name
    return self.kernel_spec_class.from_resource_dir(resource_dir)
  File "/Users/roun308/anaconda/lib/python2.7/site-packages/jupyter_client/kernelspec.py", line 38, in from_resource_dir
    kernel_dict = json.load(f)
  File "/Users/roun308/anaconda/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Users/roun308/anaconda/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Users/roun308/anaconda/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/roun308/anaconda/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by jrounds** [comment]
Had something to do with a kernel in a system folder.
When I started notebooks I got a message about Failed to load kernel spec: 'tensorflow_jupyter_kernel'.

I had used jupyter kernelspec to add that kernel, but it ended up in a system folder and then after that list failed to work.
```
WE29699:kernels roun308$ jupyter kernelspec remove tensorflow_jupyter_kernel
Kernel specs to remove:
  tensorflow_jupyter_kernel	/usr/local/share/jupyter/kernels/tensorflow_jupyter_kernel
Remove 1 kernel specs [y/N]: y
[RemoveKernelSpec] Removed /usr/local/share/jupyter/kernels/tensorflow_jupyter_kernel
WE29699:kernels roun308$ jupyter kernelspec list
Available kernels:
  python2    /Users/roun308/Library/Jupyter/kernels/python2
```

**Comment by takluyver** [comment]
The kernel.json file for it must have been invalid JSON. We should probably catch that - one kernel shouldn't be able to stop `jupyter kernelspec list` from working entirely.

**Comment by jrounds** [comment]
Probably.  It comes back when I install it again, so I will focus on that.  Thanks for your time.
```
WE29699:kernels roun308$ jupyter kernelspec install /Users/roun308/tensorflow/tensorflow_jupyter_kernel 
[InstallKernelSpec] Installed kernelspec tensorflow_jupyter_kernel in /usr/local/share/jupyter/kernels/tensorflow_jupyter_kernel
WE29699:kernels roun308$ jupyter kernelspec list
Traceback (most recent call last):
  File "/Users/roun308/anaconda/bin/jupyter-kernelspec", line 8, in <module>
    main()
  File "/Users/roun308/anaconda/bin/jupyter-kernelspec", line 5, in main
    KernelSpecApp.launch_instance()
  File "/Users/roun308/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/Users/roun308/anaconda/lib/python2.7/site-packages/jupyter_client/kernelspecapp.py", line 269, in start
    return self.subapp.start()
  File "/Users/roun308/anaconda/lib/python2.7/site-packages/jupyter_client/kernelspecapp.py", line 44, in start
    specs = self.kernel_spec_manager.get_all_specs()
  File "/Users/roun308/anaconda/lib/python2.7/site-packages/jupyter_client/kernelspec.py", line 196, in get_all_specs
    } for kname in d}
  File "/Users/roun308/anaconda/lib/python2.7/site-packages/jupyter_client/kernelspec.py", line 196, in <dictcomp>
    } for kname in d}
  File "/Users/roun308/anaconda/lib/python2.7/site-packages/jupyter_client/kernelspec.py", line 164, in _get_kernel_spec_by_name
    return self.kernel_spec_class.from_resource_dir(resource_dir)
  File "/Users/roun308/anaconda/lib/python2.7/site-packages/jupyter_client/kernelspec.py", line 38, in from_resource_dir
    kernel_dict = json.load(f)
  File "/Users/roun308/anaconda/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Users/roun308/anaconda/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Users/roun308/anaconda/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/roun308/anaconda/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded 
```

**Comment by jrounds** [comment]
So...

I think it has something to do with file encoding (maybe line ending encoding sorry), so I:
1) copied python2 kernel folder.  Did a list.  Result: Good List.
2) Opened kernel.json in Mac default text editor changed name.  Saved.  Result: List error.
3) copied python2 kernel folder.  Did a list.  Result: Good List.
4) Opened kernel.json in "TextWrangler" changed name. Saved. Result: Good list.


So, has something to do with saving with default text editor and then change of encoding causing a JSON parse error in the list.  Not sure other than that.  Suspect line endings?  Dunno.

**Comment by takluyver** [comment]
I don't think line endings should matter for JSON. Maybe the editor saved it with some odd text encoding. Whatever the cause, though, it should catch invalid files.

**Comment by Carreau** [comment]
For info, what was your default text editor ? `TextEdit`?

**Comment by JamiesHQ** [comment]
@jrounds : We're doing a little housekeeping on our issue log and noticed this thread from 2016. Were you able to find a solution to your issue? Please let us know! We'll close this issue if you found what you need. thanks!

**Comment by JoelKThomas** [comment]
E 01:55:56.100 NotebookApp] Failed to load kernel spec: 'python2'
    Traceback (most recent call last):
      File "/home/joel/anaconda3/lib/python3.5/site-packages/notebook/services/kernelspecs/handlers.py", line 58, in get
        d = kernelspec_model(self, kernel_name)
      File "/home/joel/anaconda3/lib/python3.5/site-packages/notebook/services/kernelspecs/handlers.py", line 22, in kernelspec_model
        spec = ksm.get_kernel_spec(name)
      File "/home/joel/anaconda3/lib/python3.5/site-packages/nb_conda_kernels/manager.py", line 209, in get_kernel_spec
        super(CondaKernelSpecManager, self).get_kernel_spec(kernel_name)
      File "/home/joel/.local/lib/python3.5/site-packages/jupyter_client/kernelspec.py", line 234, in get_kernel_spec
        resource_dir = self._find_spec_directory(kernel_name.lower())
      File "/home/joel/.local/lib/python3.5/site-packages/jupyter_client/kernelspec.py", line 207, in _find_spec_directory
        files = os.listdir(kernel_dir)
    PermissionError: [Errno 13] Permission denied: '/home/joel/.local/share/jupyter/kernels'

Gettting an Error like this!!! Need Help..Thanks

**Comment by Carreau** [comment]
did you use `sudo` to install ?

What are the results of : 
```
$ ls -al /home/joel/.local/share/jupyter/kernels
$ ls -al /home/joel/.local/share/jupyter/
$ ls -al /home/joel/.local/share/
```
