### ISSUE TITLE
Jupyter Notebook Error After Shutdown

### ISSUE THREAD

**Issue by okids** [jupyter/notebook#1563]
I install jupyter notebook and sucessfully use it at first time. After i shut down my computer, this error happen:

```
>  Traceback (most recent call last):
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\tornado\web.py", line 1443, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\tornado\web.py", line 2800, in wrapper
        return method(self, *args, **kwargs)
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\notebook\tree\handlers.py", line 50, in get
        terminals_available=self.settings['terminals_available'],
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\notebook\base\handlers.py", line 302, in render_template
        template = self.get_template(name)
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\notebook\base\handlers.py", line 298, in get_template
        return self.settings['jinja2_env'].get_template(name)
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\jinja2\environment.py", line 812, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\jinja2\environment.py", line 774, in _load_template
        cache_key = self.loader.get_source(self, name)[1]
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\jinja2\loaders.py", line 175, in get_source
        contents = f.read().decode(self.encoding)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 245706: invalid continuation byte
[E 13:41:52.793 NotebookApp] Uncaught exception in write_error
    Traceback (most recent call last):
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\tornado\web.py", line 1443, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\tornado\web.py", line 2800, in wrapper
        return method(self, *args, **kwargs)
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\notebook\tree\handlers.py", line 50, in get
        terminals_available=self.settings['terminals_available'],
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\notebook\base\handlers.py", line 302, in render_template
        template = self.get_template(name)
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\notebook\base\handlers.py", line 298, in get_template
        return self.settings['jinja2_env'].get_template(name)
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\jinja2\environment.py", line 812, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\jinja2\environment.py", line 774, in _load_template
        cache_key = self.loader.get_source(self, name)[1]
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\jinja2\loaders.py", line 175, in get_source
        contents = f.read().decode(self.encoding)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 245706: invalid continuation byte
>During handling of the above exception, another exception occurred:
 Traceback (most recent call last):
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\notebook\base\handlers.py", line 364, in write_error
        html = self.render_template('%s.html' % status_code, **ns)
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\notebook\base\handlers.py", line 302, in render_template
        template = self.get_template(name)
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\notebook\base\handlers.py", line 298, in get_template
        return self.settings['jinja2_env'].get_template(name)
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\jinja2\environment.py", line 812, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\jinja2\environment.py", line 774, in _load_template
        cache_key = self.loader.get_source(self, name)[1]
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\jinja2\loaders.py", line 187, in get_source
        raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: 500.html
>    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\tornado\web.py", line 974, in send_error
        self.write_error(status_code, **kwargs)
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\notebook\base\handlers.py", line 367, in write_error
        html = self.render_template('error.html', **ns)
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\notebook\base\handlers.py", line 302, in render_template
        template = self.get_template(name)
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\notebook\base\handlers.py", line 298, in get_template
        return self.settings['jinja2_env'].get_template(name)
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\jinja2\environment.py", line 812, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\jinja2\environment.py", line 774, in _load_template
        cache_key = self.loader.get_source(self, name)[1]
      File "c:\users\oki.oki-pc\miniconda3\lib\site-packages\jinja2\loaders.py", line 175, in get_source
        contents = f.read().decode(self.encoding)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf6 in position 237630: invalid start byte
[E 13:41:52.807 NotebookApp] {
      "Accept-Language": "en-US,en;q=0.5",
      "Connection": "keep-alive",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101
 Firefox/45.0",
      "Host": "localhost:8888",
      "Accept-Encoding": "gzip, deflate"
    }
[E 13:41:52.817 NotebookApp] 500 GET /tree (::1) 33.00ms referer=None
```

This is the second time the error occurred. I tried to reinstall the package (entough cannopy package, ipython) and replace with miniconda, the same error occurred after shutdown.

**Comment by Carreau** [comment]
Thanks, we'll have a look.

**Comment by minrk** [comment]
This certainly is strange. From the traceback, it would appear that it's failing to decode a template file (error.html, looks like). However, I just checked and none of our templates have non-ascii content, and none of them are more than 10k bytes, so I don't know where "byte in position 237630" would be coming from.

**Comment by takluyver** [comment]
I've bumped this to backlog as we don't know how to reproduce it, nor what might have gone wrong.

**Comment by ddulic** [comment]
I have the same problem. I had it on one of my files but didn't know why, so I just ignored it. But now it also happens to another file. The only significant change to that file was adding various unicode characters, such as `✓`
## output from journalctl sicne I have it running as a service
```
[E 14:50:18.772 NotebookApp] Unhandled error in API request
May 18 14:50:18 ghost jupyter[1515]:     Traceback (most recent call last):
May 18 14:50:18 ghost jupyter[1515]:       File "/home/ddulic/.local/lib/python2.7/site-packages/notebook/base/handlers.py", line 516, in wrapper
May 18 14:50:18 ghost jupyter[1515]:         result = yield gen.maybe_future(method(self, *args, **kwargs))
May 18 14:50:18 ghost jupyter[1515]:       File "/home/ddulic/.local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
May 18 14:50:18 ghost jupyter[1515]:         value = future.result()
May 18 14:50:18 ghost jupyter[1515]:       File "/home/ddulic/.local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
May 18 14:50:18 ghost jupyter[1515]:         raise_exc_info(self._exc_info)
May 18 14:50:18 ghost jupyter[1515]:       File "/home/ddulic/.local/lib/python2.7/site-packages/tornado/gen.py", line 307, in wrapper
May 18 14:50:18 ghost jupyter[1515]:         yielded = next(result)
May 18 14:50:18 ghost jupyter[1515]:       File "/home/ddulic/.local/lib/python2.7/site-packages/notebook/services/contents/handlers.py", line 124, in get
May 18 14:50:18 ghost jupyter[1515]:         path=path, type=type, format=format, content=content,
May 18 14:50:18 ghost jupyter[1515]:       File "/home/ddulic/.local/lib/python2.7/site-packages/ipymd/core/contents_manager.py", line 100, in get
May 18 14:50:18 ghost jupyter[1515]:         model = self._notebook_model(path, content=content)
May 18 14:50:18 ghost jupyter[1515]:       File "/home/ddulic/.local/lib/python2.7/site-packages/notebook/services/contents/filemanager.py", line 344, in _notebook_model
May 18 14:50:18 ghost jupyter[1515]:         self.mark_trusted_cells(nb, path)
May 18 14:50:18 ghost jupyter[1515]:       File "/home/ddulic/.local/lib/python2.7/site-packages/notebook/services/contents/manager.py", line 456, in mark_trusted_cells
May 18 14:50:18 ghost jupyter[1515]:         trusted = self.notary.check_signature(nb)
May 18 14:50:18 ghost jupyter[1515]:       File "/home/ddulic/.local/lib/python2.7/site-packages/nbformat/sign.py", line 436, in check_signature
May 18 14:50:18 ghost jupyter[1515]:         signature = self.compute_signature(nb)
May 18 14:50:18 ghost jupyter[1515]:       File "/home/ddulic/.local/lib/python2.7/site-packages/nbformat/sign.py", line 415, in compute_signature
May 18 14:50:18 ghost jupyter[1515]:         for b in yield_everything(nb):
May 18 14:50:18 ghost jupyter[1515]:       File "/home/ddulic/.local/lib/python2.7/site-packages/nbformat/sign.py", line 270, in yield_everything
May 18 14:50:18 ghost jupyter[1515]:         for b in yield_everything(value):
May 18 14:50:18 ghost jupyter[1515]:       File "/home/ddulic/.local/lib/python2.7/site-packages/nbformat/sign.py", line 274, in yield_everything
May 18 14:50:18 ghost jupyter[1515]:         for b in yield_everything(element):
May 18 14:50:18 ghost jupyter[1515]:       File "/home/ddulic/.local/lib/python2.7/site-packages/nbformat/sign.py", line 270, in yield_everything
May 18 14:50:18 ghost jupyter[1515]:         for b in yield_everything(value):
May 18 14:50:18 ghost jupyter[1515]:       File "/home/ddulic/.local/lib/python2.7/site-packages/nbformat/sign.py", line 279, in yield_everything
May 18 14:50:18 ghost jupyter[1515]:         yield unicode_type(obj).encode('utf8')
May 18 14:50:18 ghost jupyter[1515]:     UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 163: ordinal not in range(128)
May 18 14:50:18 ghost jupyter[1515]: [E 14:50:18.779 NotebookApp] {
May 18 14:50:18 ghost jupyter[1515]:       "Content-Length": "0",
May 18 14:50:18 ghost jupyter[1515]:       "Accept-Language": "en-US,en;q=0.8,de;q=0.6",
May 18 14:50:18 ghost jupyter[1515]:       "Accept-Encoding": "gzip, deflate, sdch, br",
May 18 14:50:18 ghost jupyter[1515]:       "X-Xsrftoken": "2|ed3ca901|f6bb520ca90712127e3d969dd3caeb40|1494850961",
May 18 14:50:18 ghost jupyter[1515]:       "Host": "beta.damir.tech",
May 18 14:50:18 ghost jupyter[1515]:       "Accept": "application/json, text/javascript, */*; q=0.01",
May 18 14:50:18 ghost jupyter[1515]:       "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36",
May 18 14:50:18 ghost jupyter[1515]:       "Dnt": "1",
May 18 14:50:18 ghost jupyter[1515]:       "Connection": "upgrade",
May 18 14:50:18 ghost jupyter[1515]:       "X-Requested-With": "XMLHttpRequest",
May 18 14:50:18 ghost jupyter[1515]:       "Referer": "https://beta.damir.tech/files/notebooks/Sync/Ghost/Website/ghost.md",
May 18 14:50:18 ghost jupyter[1515]:       "Cookie": "ajs_group_id=null; ajs_user_id=%226wah3d76itgi7gyspxkt4m1fta%22; ajs_anonymous_id=%2200000000000000000000000000%22; express:sess=eyJ0b2tlbiI6IjE5ZGI1OWRkMGVlOGJjMDYwYTY5NDdiOWJkNGQ0Yjcw
May 18 14:50:18 ghost jupyter[1515]:     }

```

**Comment by sankalpdayal** [comment]
I have the same problem. I was running a simulation and laptop abruptly shutdown. Now I am unable to load the notebook. It says Unreadable Notebook:  UnicodeDecodeError. 55409, 55410, 'invalid start byte'

**Comment by jtpio** [comment]
Closing due to inactivity.

Feel free to open a new issue in https://github.com/jupyter-server/jupyter_server if it still relevant, thanks!
