### ISSUE TITLE
Wont Delete, or Edit Names or Files

### ISSUE THREAD

**Issue by valleyrock** [jupyter/notebook#1618]
This is the error I get 

```
[W 22:23:10.709 NotebookApp] Unrecognized JSON config file version, assuming ver
sion 1
[W 22:23:10.714 NotebookApp] Unrecognized JSON config file version, assuming ver
sion 1
[I 22:23:12.283 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
[I 22:23:12.385 NotebookApp] The port 8888 is already in use, trying another por
t.
[W 22:23:12.390 NotebookApp] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "C:\Users\win7\Anaconda3\lib\site-packages\notebook\notebookapp.py",
line 1046, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "C:\Users\win7\Anaconda3\lib\importlib__init__.py", line 126, in imp
ort_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
        ImportError: No module named 'jupyterlab'

[I 22:23:12.540 NotebookApp] Serving notebooks from local directory: C:\Users\wi
n7\Desktop
[I 22:23:12.540 NotebookApp] 0 active kernels
[I 22:23:12.540 NotebookApp] The Jupyter Notebook is running at: http://localhos
t:8889/
[I 22:23:12.541 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip confirmation).
```

**Comment by Carreau** [comment]
Hi there, sorry for the delayed response. 
If you are on master and/or have tried jupyterlab, you might need to nuke your config as jupyterlab was an extension. So you likely have a config value that try to load jupyterlab. 

Let see if we can prevent errors to happend if you have a broken extension on the serverside.

**Comment by takluyver** [comment]
It looks like we already catch errors loading server extensions; that traceback is being logged to show what went wrong, but it shouldn't affect anything else. If you're still having other problems, please file a new issue describing those in more detail.
