### ISSUE TITLE
Windows test failures

### ISSUE THREAD

**Issue by takluyver** [jupyter/notebook#1626]
I got a Jenkins job working to test the notebook on Windows. These tests fail:

```
======================================================================
ERROR: test suite for <class 'notebook.services.contents.tests.test_contents_api.APITest'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\site-packages\nose\suite.py", line 229, in run
    self.tearDown()
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\site-packages\nose\suite.py", line 352, in tearDown
    self.teardownContext(ancestor)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\site-packages\nose\suite.py", line 368, in teardownContext
    try_run(context, names)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\site-packages\nose\util.py", line 471, in try_run
    return func()
  File "C:\jenkins\workspace\notebook-windows\_pyversion\3.5\label\windows\notebook\tests\launchnotebook.py", line 132, in teardown_class
    cls.data_dir.cleanup()
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\tempfile.py", line 812, in cleanup
    _shutil.rmtree(self.name)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\shutil.py", line 488, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\shutil.py", line 383, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\shutil.py", line 381, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\tmp43di4yc1\\nbsignatures.db'
-------------------- >> begin captured logging << --------------------
NotebookApp: INFO: Shutting down kernels
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test suite for <class 'notebook.services.contents.tests.test_contents_api.GenericFileCheckpointsAPITest'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\site-packages\nose\suite.py", line 229, in run
    self.tearDown()
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\site-packages\nose\suite.py", line 352, in tearDown
    self.teardownContext(ancestor)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\site-packages\nose\suite.py", line 368, in teardownContext
    try_run(context, names)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\site-packages\nose\util.py", line 471, in try_run
    return func()
  File "C:\jenkins\workspace\notebook-windows\_pyversion\3.5\label\windows\notebook\tests\launchnotebook.py", line 132, in teardown_class
    cls.data_dir.cleanup()
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\tempfile.py", line 812, in cleanup
    _shutil.rmtree(self.name)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\shutil.py", line 488, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\shutil.py", line 383, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\shutil.py", line 381, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\tmpj1mgmsr9\\nbsignatures.db'
-------------------- >> begin captured logging << --------------------
NotebookApp: INFO: Shutting down kernels
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_list_formats (notebook.services.nbconvert.tests.test_nbconvert_api.APITest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\jenkins\workspace\notebook-windows\_pyversion\3.5\label\windows\notebook\services\nbconvert\tests\test_nbconvert_api.py", line 27, in test_list_formats
    formats = self.nbconvert_api.list_formats().json()
  File "C:\jenkins\workspace\notebook-windows\_pyversion\3.5\label\windows\notebook\services\nbconvert\tests\test_nbconvert_api.py", line 20, in list_formats
    return self._req('GET', '')
  File "C:\jenkins\workspace\notebook-windows\_pyversion\3.5\label\windows\notebook\services\nbconvert\tests\test_nbconvert_api.py", line 16, in _req
    response.raise_for_status()
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\site-packages\requests\models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:12341/a%40b/api/nbconvert
-------------------- >> begin captured logging << --------------------
NotebookApp: INFO: Shutting down kernels
NotebookApp: INFO: Serving notebooks from local directory: C:\Users\ADMINI~1\AppData\Local\Temp\2\tmp7mcnjx5k
NotebookApp: INFO: 0 active kernels 
NotebookApp: INFO: The Jupyter Notebook is running at: http://localhost:12341/a%40b/
NotebookApp: INFO: Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
requests.packages.urllib3.connectionpool: DEBUG: "GET /a%40b/api/contents HTTP/1.1" 200 214
requests.packages.urllib3.connectionpool: INFO: Starting new HTTP connection (1): localhost
NotebookApp: WARNING: Could not import nbconvert: No module named 'nbconvert'
NotebookApp: ERROR: {
  "Connection": "keep-alive",
  "Accept-Encoding": "gzip, deflate",
  "Host": "localhost:12341",
  "User-Agent": "python-requests/2.10.0",
  "Accept": "*/*"
}
NotebookApp: ERROR: 500 GET /a%40b/api/nbconvert (::1) 2.00ms referer=None
requests.packages.urllib3.connectionpool: DEBUG: "GET /a%40b/api/nbconvert HTTP/1.1" 500 86
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: Failure: ImportError (No module named 'terminado')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\imp.py", line 244, in load_module
    return load_package(name, filename)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\jenkins\workspace\notebook-windows\_pyversion\3.5\label\windows\notebook\terminal\__init__.py", line 3, in <module>
    import terminado
ImportError: No module named 'terminado'
-------------------- >> begin captured logging << --------------------
NotebookApp: INFO: Shutting down kernels
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: notebook.tests.test_notebookapp.test_nb_dir_with_slash
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\9829\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\jenkins\workspace\notebook-windows\_pyversion\3.5\label\windows\notebook\tests\test_notebookapp.py", line 70, in test_nb_dir_with_slash
    nt.assert_false(app.notebook_dir.endswith("/"))
AssertionError: True is not false
```

**Comment by Carreau** [comment]
Make me think, I never asked @gnestor, which is/are the OS you use in general ?

**Comment by gnestor** [comment]
@Carreau I'm OS X...

**Comment by jtpio** [comment]
Closing this issue since the last comment is from 2016.

For reference `jupyter-server` is tested on Windows: https://github.com/jupyter-server/jupyter_server/blob/8c2987fef9da26c3ef12f6be8a6ad53444446578/.github/workflows/python-tests.yml#L50

![image](https://github.com/jupyter/notebook/assets/591645/a81cf1ba-7121-49f6-a385-1acb59c22aa7)
