### ISSUE TITLE
Jupyter notebook problem with tornado 4.4.1

### ISSUE THREAD

**Issue by npadus** [jupyter/notebook#1636]
(C:\Users\lafamilia\Anaconda3) C:\Users\lafamilia>jupyter notebook
[W 09:43:06.701 NotebookApp] Unrecognized JSON config file version, assuming version 1
[I 09:43:08.589 NotebookApp] [nb_conda_kernels] enabled, 1 kernels found
Traceback (most recent call last):
  File "C:\Users\lafamilia\Anaconda3\Scripts\jupyter-notebook-script.py", line 5, in <module>
    sys.exit(notebook.notebookapp.main())
  File "C:\Users\lafamilia\Anaconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\lafamilia\Anaconda3\lib\site-packages\traitlets\config\application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "C:\Users\lafamilia\Anaconda3\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\lafamilia\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1071, in initialize
    self.init_webapp()
  File "C:\Users\lafamilia\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 892, in init_webapp
    self.jinja_environment_options
  File "C:\Users\lafamilia\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 133, in __init__
    handlers = self.init_handlers(settings)
  File "C:\Users\lafamilia\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 230, in init_handlers
    handlers.extend(load_handlers('services.kernels.handlers'))
  File "C:\Users\lafamilia\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 114, in load_handlers
    mod = __import__(name, fromlist=['default_handlers'])
  File "C:\Users\lafamilia\Anaconda3\lib\site-packages\notebook\services\kernels\handlers.py", line 20, in <module>
    from ...base.zmqhandlers import AuthenticatedZMQStreamHandler, deserialize_binary_message
  File "C:\Users\lafamilia\Anaconda3\lib\site-packages\notebook\base\zmqhandlers.py", line 20, in <module>
    from tornado.websocket import WebSocketHandler
  File "C:\Users\lafamilia\Anaconda3\lib\site-packages\tornado\websocket.py", line 37, in <module>
    from tornado import simple_httpclient
  File "C:\Users\lafamilia\Anaconda3\lib\site-packages\tornado\simple_httpclient.py", line 13, in <module>
    from tornado.tcpclient import TCPClient
ValueError: source code string cannot contain null bytes

Solution: Downgrade to tornado 4.3

**Comment by Carreau** [comment]
Hi, I don't achieve to reproduce that (on Mac OS) , does it still do it on 4.4 ? Do you have any particular config ?

I'm sure it might be a tornado issues, as 4.4 was released recently.

**Comment by npadus** [comment]
I have anacondas defaults, im downgrade tornado 4.4.1. to tornado 4.3 this its solution

**Comment by takluyver** [comment]
I just tested upgrading tornado to 4.4.1 with conda on Windows, and couldn't reproduce it. If there is something to be fixed (and not just random file corruption), it's probably something for the conda packagers to deal with.

**Comment by npadus** [comment]
Maybe jupyter notebook doesnt support  tornado 4.4.x. Only  tornado 4.3 down

**Comment by takluyver** [comment]
It's not a question of what we support. The error message indicates that a file in your tornado installation is corrupt - either something went wrong on your computer, or someone made a mistake in packaging tornado. Jupyter can't do anything about that.

**Comment by npadus** [comment]
Thank you, You're right

Closed
