### ISSUE TITLE
Test failures on Jenkins Windows build

### ISSUE THREAD

**Issue by takluyver** [jupyter/notebook#1702]
```

======================================================================
ERROR: Failure: ImportError (No module named 'terminado')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\28634\lib\site-packages\nose\failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\28634\lib\site-packages\nose\loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\28634\lib\site-packages\nose\importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\28634\lib\site-packages\nose\importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\28634\lib\imp.py", line 244, in load_module
    return load_package(name, filename)
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\28634\lib\imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\jenkins\workspace\notebook-windows\_pyversion\3.5\label\windows\notebook\terminal\__init__.py", line 3, in <module>
    import terminado
ImportError: No module named 'terminado'
-------------------- >> begin captured logging << --------------------
NotebookApp: INFO: Shutting down kernels
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: Should copy select files from source to destination
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\jenkins\workspace\notebook-windows\_pyversion\3.5\label\windows\notebook\bundler\tests\test_bundler_tools.py", line 122, in test_copy_filelist
    self.assertTrue(os.path.isfile(os.path.join(self.tmp, 'resources/subdir/test_file.txt')))
AssertionError: False is not true
-------------------- >> begin captured logging << --------------------
NotebookApp: INFO: Shutting down kernels
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: Should expand to single file in the resources/ subfolder.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\jenkins\workspace\notebook-windows\_pyversion\3.5\label\windows\notebook\bundler\tests\test_bundler_tools.py", line 88, in test_glob_dir
    tools.expand_references(HERE, ['resources/empty.ipynb']))
AssertionError: 'resources/empty.ipynb' not found in {'resources\\empty.ipynb'}

======================================================================
FAIL: Should expand to test_file.txt deep under this test/ directory.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\jenkins\workspace\notebook-windows\_pyversion\3.5\label\windows\notebook\bundler\tests\test_bundler_tools.py", line 104, in test_glob_splatsplat_in_middle
    self.assertIn('resources/subdir/test_file.txt', globs, globs)
AssertionError: 'resources/subdir/test_file.txt' not found in set() : set()

======================================================================
FAIL: Should expand to test_file.txt under any path.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\jenkins\workspace\notebook-windows\_pyversion\3.5\label\windows\notebook\bundler\tests\test_bundler_tools.py", line 115, in test_glob_splatsplat_leading
    self.assertIn('resources/subdir/test_file.txt', globs, globs)
AssertionError: 'resources/subdir/test_file.txt' not found in set() : set()

======================================================================
FAIL: Should expand to all descendants of this test/ directory.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\jenkins\workspace\notebook-windows\_pyversion\3.5\label\windows\notebook\bundler\tests\test_bundler_tools.py", line 109, in test_glob_splatsplat_trailing
    self.assertIn('resources/empty.ipynb', globs, globs)
AssertionError: 'resources/empty.ipynb' not found in set() : set()

======================================================================
FAIL: Should expand to all files in the resources/ subfolder.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\jenkins\workspace\notebook-windows\_pyversion\3.5\label\windows\notebook\bundler\tests\test_bundler_tools.py", line 93, in test_glob_subdir
    tools.expand_references(HERE, ['resources/']))
AssertionError: 'resources/empty.ipynb' not found in set()

======================================================================
FAIL: notebook.tests.test_notebookapp.test_nb_dir_with_slash
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\AppData\Local\Temp\2\28634\lib\site-packages\nose\case.py", line 198, in runTest
    self.test(*self.arg)
  File "C:\jenkins\workspace\notebook-windows\_pyversion\3.5\label\windows\notebook\tests\test_notebookapp.py", line 70, in test_nb_dir_with_slash
    nt.assert_false(app.notebook_dir.endswith("/"))
AssertionError: True is not false
```

**Comment by takluyver** [comment]
Some of these relate to #1695, which doesn't seem to have fixed things entirely on Windows, others are to do with path separators, and it should just live with the import of tornado.

Pinging @parente for the bundler tests.

**Comment by parente** [comment]
Some of the bundler failures look like legitimate failures in the bundler utility code on Windows. I'll grab a windows machine sometime soon and work on fixing it. I was on the fence about whether that utility code should go into notebook or not and the solution may be to just pull that bit out. (/cc @nitind)

@takluyver does the jenkins windows job build PRs or master after merge?

**Comment by takluyver** [comment]
The existing job builds master - we can set up jobs which you give a PR number and it tests that; we have some of those for IPython.

Do you want an account on our Jenkins server so you can configure and run jobs?

**Comment by takluyver** [comment]
Reopening as there are still some errors; I don't think any of these are to do with bundler, though.

**Comment by parente** [comment]
I was a bit pressed for time so I tackled just the bundler related errors in the PR. If I get a chance I'll have a look at the others.

**Comment by minrk** [comment]
We've got tests passing on Appveyor now, so I think we can close.
