### ISSUE TITLE
Jupyter show Python[root] instead of Python 2.7

### ISSUE THREAD

**Issue by dbl001** [jupyter/notebook#1717]
1. Any idea why Jupyter shows Python[Root] instead of 'Python 2.7'?
2. How do I update Julia to version 0.5?  I built Julia from source and it runs from the shell.
![screen shot 2016-08-26 at 9 34 09 am](https://cloud.githubusercontent.com/assets/3105499/18020122/9f109e24-6b94-11e6-857f-6be59c60b6e6.png)

OS X 10.11.6
Anaconda2-4.1.1-MacOSX-x86_64
David-Laxers-MacBook-Pro:~ davidlaxer$ conda --version
conda 4.1.11
David-Laxers-MacBook-Pro:~ davidlaxer$ python --version
Python 2.7.12 :: Anaconda 4.1.1 (x86_64)
![screen shot 2016-08-26 at 12 16 42 pm](https://cloud.githubusercontent.com/assets/3105499/18019997/d693b17a-6b93-11e6-8406-1f5703892965.png)

**Comment by Carreau** [comment]
> Any idea why Jupyter shows Python[Root] instead of 'Python 2.7'?

That's an anaconda thing, it show the environment of python kernel. It does automatically list environment, and the default environment append to me named `[root]`.

@damianavila , @bollwyvl  can you report things up the continuum chain the `[root]` is confusing a lot of users, we had a bootcamp monday/tuesday that thought `[root]` was the user running the kernel.

Can we just change the display_name to be more explicit ? like `Python {version} [{env} environment]`
Maybe there is already an issue on conda/conda ?

> How do I update Julia to version 0.5? I built Julia from source and it runs from the shell. 

That's a question for the Julia people, in particular the [IJulia repository](https://github.com/JuliaLang/IJulia.jl) I guess.

**Comment by dbl001** [comment]
Jupyterlab displays ‘No kernel’ … but Python is really running.

**Comment by Carreau** [comment]
> Jupyterlab displays ‘No kernel’ … but Python is really running.

JupyterLab is alpha version, it's likely a bug in JupyterLab,

**Comment by dbl001** [comment]
I 17:43:13.136 NotebookApp] Kernel started: e940ab35-80b4-4f06-938f-05cff3a2d61c
INFO: Precompiling module ZMQ...
INFO: Precompiling module Nettle...
[W 17:43:24.414 NotebookApp] Timeout waiting for kernel_info reply from e940ab35-80b4-4f06-938f-05cff3a2d61c
Starting kernel event loops.
[E 17:43:29.861 NotebookApp] Uncaught exception GET /api/kernels/e940ab35-80b4-4f06-938f-05cff3a2d61c/channels?session_id=AB70E3A4A70D48B39B67B749446DBF61 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels/e940ab35-80b4-4f06-938f-05cff3a2d61c/channels?session_id=AB70E3A4A70D48B39B67B749446DBF61', version='HTTP/1.1', remote_ip='::1', headers={'Origin': 'http://localhost:8888', 'Upgrade': 'websocket', 'Sec-Websocket-Extensions': 'x-webkit-deflate-frame', 'Sec-Websocket-Version': '13', 'Connection': 'Upgrade', 'Sec-Websocket-Key': 'eeztMBqcVc0lsBJ5FZXMEg==', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.7 (KHTML, like Gecko) Version/9.1.2 Safari/601.7.7', 'Host': 'localhost:8888', 'Cookie': 'csrftoken=mA6yl7Xrl6EG3dMhZcOugzLNL8Xw5HRV; jobs-showAll=true; stages-showAll=true; undefined-table-hidden=false', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'})
    Traceback (most recent call last):
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/web.py", line 1401, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
        self.on_recv(lambda msg: callback(self, msg), copy=copy)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/notebook/services/kernels/handlers.py", line 296, in _on_zmq_reply
        msg = self.session.deserialize(fed_msg_list)
      File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/jupyter_client/session.py", line 859, in deserialize
        raise ValueError("Invalid Signature: %r" % signature)
    ValueError: Invalid Signature: 'stderr'

**Comment by damianavila** [comment]
>@damianavila , @bollwyvl can you report things up the continuum chain the [root] is confusing a lot of users, we had a bootcamp monday/tuesday that thought [root] was the user running the kernel.
>Can we just change the display_name to be more explicit ? like Python {version} [{env} environment]
Maybe there is already an issue on conda/conda ?

@Carreau last version of nb_conda_kernels shows `Python [default]` and Python [conda root] and `Python [conda: name_of_env]`. That should make things less confusing...
