### ISSUE TITLE
Permission denied when enabling widgetsnbextension

### ISSUE THREAD

**Issue by quang-ha** [jupyter/notebook#1731]
Ubuntu 16.04, I have just done a fresh installation of `jupyter` using

```
sudo_ pip3 install jupyter
```
Then I run:
```
jupyter nbextension enable --py --sys-prefix widgetsnbextension
```

But I got this error:
```
Enabling notebook extension jupyter-js-widgets/extension...
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 961, in start
    super(NBExtensionApp, self).start()
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 869, in start
    self.toggle_nbextension_python(self.extra_args[0])
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 845, in toggle_nbextension_python
    logger=self.log)
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 459, in enable_nbextension_python
    logger=logger)
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 380, in _set_nbextension_state_python
    for nbext in nbexts]
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 380, in <listcomp>
    for nbext in nbexts]
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 345, in _set_nbextension_state
    cm.update(section, {"load_extensions": {require: state}})
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/manager.py", line 87, in update
    self.set(section_name, data)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/manager.py", line 74, in set
    f = io.open(filename, 'w', encoding='utf-8')
PermissionError: [Errno 13] Permission denied: '/usr/etc/jupyter/nbconfig/notebook.json'
```
I didn't need `sudo` to enable the widgets before...

**Comment by minrk** [comment]
Whether you need sudo depends on your permissions for the target directory. In this case, `sys-prefix` is `/usr` because presumably you are using the system Python. Given that, ou almost certainly **do not** want to use `--sys-prefix` in this case. Try removing the argument.

**Comment by quang-ha** [comment]
Ah thanks!
