### ISSUE TITLE
npm run build:js doesn't work

### ISSUE THREAD

**Issue by YogeshTayal** [jupyter/notebook#1787]
I just took the Jupyter Notebook raw code, made a small change in HTML/Javascript and tried re-building it. It threw the below error:

> jupyter-notebook-deps@4.0.0 build:js C:\Users\ytayal\Downloads\notebook-master
> webpack

[BABEL] Note: The code generator has deoptimised the styling of "C:/Users/ytayal/Downloads/notebook-master/notebook/static/notebook/js/notebook.js" as it exceed
s the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "C:/Users/ytayal/Downloads/notebook-master/notebook/static/notebook/js/notebook.js" as it exceed
s the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "C:/Users/ytayal/Downloads/notebook-master/notebook/static/components/codemirror/keymap/vim.js"
as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "C:/Users/ytayal/Downloads/notebook-master/notebook/static/notebook/js/notebook.js" as it exceed
s the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "C:/Users/ytayal/Downloads/notebook-master/notebook/static/notebook/js/notebook.js" as it exceed
s the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "C:/Users/ytayal/Downloads/notebook-master/notebook/static/components/codemirror/keymap/vim.js"
as it exceeds the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "C:/Users/ytayal/Downloads/notebook-master/notebook/static/notebook/js/notebook.js" as it exceed
s the max of "100KB".
[BABEL] Note: The code generator has deoptimised the styling of "C:/Users/ytayal/Downloads/notebook-master/notebook/static/notebook/js/notebook.js" as it exceed
s the max of "100KB".
Hash: 20ef13068667f78e4b1b14871d254beabe618e35bda7458d0a8a4ba74f8a38164a8759aef63aaa5159962c21e7373ebd9d9b1668c9f77b57782a95dd3ec0800e4d8745615867
Version: webpack 1.13.2
Child
    Hash: 20ef13068667f78e4b1b
    Version: webpack 1.13.2
    Time: 69907ms
          Asset     Size  Chunks             Chunk Names
    main.min.js  4.27 MB       0  [emitted]  main
        + 174 hidden modules
Child
    Hash: 14871d254beabe618e35
    Version: webpack 1.13.2
    Time: 66942ms
            Asset     Size  Chunks             Chunk Names
      main.min.js  19.9 kB       0  [emitted]  main
    1.main.min.js  5.25 MB       1  [emitted]
        + 182 hidden modules
Child
    Hash: bda7458d0a8a4ba74f8a
    Version: webpack 1.13.2
    Time: 72501ms
            Asset     Size  Chunks             Chunk Names
      main.min.js   147 kB       0  [emitted]  main
    1.main.min.js  4.77 MB       1  [emitted]
        + 191 hidden modules

    WARNING in ./~/xterm/addons/attach/index.html
    Module parse failed: C:\Users\ytayal\Downloads\notebook-master\node_modules\xterm\addons\attach\index.html Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (1:0)
        at Parser.pp$4.raise (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:2221:15)
        at Parser.pp.unexpected (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:603:10)
        at Parser.pp$3.parseExprAtom (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1822:12)
        at Parser.pp$3.parseExprSubscripts (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1715:21)
        at Parser.pp$3.parseMaybeUnary (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1692:19)
        at Parser.pp$3.parseExprOps (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1637:21)
        at Parser.pp$3.parseMaybeConditional (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1620:21)
        at Parser.pp$3.parseMaybeAssign (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1597:21)
        at Parser.pp$3.parseExpression (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1573:21)
        at Parser.pp$1.parseStatement (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:727:47)
        at Parser.pp$1.parseTopLevel (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:638:25)
        at Parser.parse (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:516:17)
        at Object.parse (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:3098:39)
        at Parser.parse (C:\Users\ytayal\Downloads\notebook-master\node_modules\webpack\lib\Parser.js:902:15)
        at DependenciesBlock.<anonymous> (C:\Users\ytayal\Downloads\notebook-master\node_modules\webpack\lib\NormalModule.js:104:16)
        at DependenciesBlock.onModuleBuild (C:\Users\ytayal\Downloads\notebook-master\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
        at nextLoader (C:\Users\ytayal\Downloads\notebook-master\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
        at C:\Users\ytayal\Downloads\notebook-master\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
        at Storage.finished (C:\Users\ytayal\Downloads\notebook-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
        at C:\Users\ytayal\Downloads\notebook-master\node_modules\graceful-fs\graceful-fs.js:78:16
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
     @ ./~/xterm/addons ^\.\/.*$

    WARNING in ./~/xterm/addons/linkify/index.html
    Module parse failed: C:\Users\ytayal\Downloads\notebook-master\node_modules\xterm\addons\linkify\index.html Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (1:0)
        at Parser.pp$4.raise (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:2221:15)
        at Parser.pp.unexpected (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:603:10)
        at Parser.pp$3.parseExprAtom (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1822:12)
        at Parser.pp$3.parseExprSubscripts (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1715:21)
        at Parser.pp$3.parseMaybeUnary (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1692:19)
        at Parser.pp$3.parseExprOps (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1637:21)
        at Parser.pp$3.parseMaybeConditional (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1620:21)
        at Parser.pp$3.parseMaybeAssign (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1597:21)
        at Parser.pp$3.parseExpression (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1573:21)
        at Parser.pp$1.parseStatement (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:727:47)
        at Parser.pp$1.parseTopLevel (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:638:25)
        at Parser.parse (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:516:17)
        at Object.parse (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:3098:39)
        at Parser.parse (C:\Users\ytayal\Downloads\notebook-master\node_modules\webpack\lib\Parser.js:902:15)
        at DependenciesBlock.<anonymous> (C:\Users\ytayal\Downloads\notebook-master\node_modules\webpack\lib\NormalModule.js:104:16)
        at DependenciesBlock.onModuleBuild (C:\Users\ytayal\Downloads\notebook-master\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
        at nextLoader (C:\Users\ytayal\Downloads\notebook-master\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
        at C:\Users\ytayal\Downloads\notebook-master\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
        at Storage.finished (C:\Users\ytayal\Downloads\notebook-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
        at C:\Users\ytayal\Downloads\notebook-master\node_modules\graceful-fs\graceful-fs.js:78:16
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
     @ ./~/xterm/addons ^\.\/.*$
Child
    Hash: 38164a8759aef63aaa51
    Version: webpack 1.13.2
    Time: 66942ms
            Asset     Size  Chunks             Chunk Names
      main.min.js  31.2 kB       0  [emitted]  main
    1.main.min.js  4.45 MB       1  [emitted]
        + 176 hidden modules
Child
    Hash: 59962c21e7373ebd9d9b
    Version: webpack 1.13.2
    Time: 62955ms
            Asset     Size  Chunks             Chunk Names
      main.min.js  36.5 kB       0  [emitted]  main
    1.main.min.js  4.47 MB       1  [emitted]
        + 178 hidden modules
Child
    Hash: 1668c9f77b57782a95dd
    Version: webpack 1.13.2
    Time: 47771ms
          Asset     Size  Chunks             Chunk Names
    contents.js  1.62 MB       0  [emitted]  main
        + 111 hidden modules
Child
    Hash: 3ec0800e4d8745615867
    Version: webpack 1.13.2
    Time: 66802ms
       Asset     Size  Chunks             Chunk Names
    index.js  6.22 MB       0  [emitted]  main
        + 212 hidden modules

    WARNING in ./~/xterm/addons/attach/index.html
    Module parse failed: C:\Users\ytayal\Downloads\notebook-master\node_modules\xterm\addons\attach\index.html Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (1:0)
        at Parser.pp$4.raise (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:2221:15)
        at Parser.pp.unexpected (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:603:10)
        at Parser.pp$3.parseExprAtom (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1822:12)
        at Parser.pp$3.parseExprSubscripts (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1715:21)
        at Parser.pp$3.parseMaybeUnary (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1692:19)
        at Parser.pp$3.parseExprOps (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1637:21)
        at Parser.pp$3.parseMaybeConditional (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1620:21)
        at Parser.pp$3.parseMaybeAssign (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1597:21)
        at Parser.pp$3.parseExpression (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1573:21)
        at Parser.pp$1.parseStatement (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:727:47)
        at Parser.pp$1.parseTopLevel (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:638:25)
        at Parser.parse (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:516:17)
        at Object.parse (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:3098:39)
        at Parser.parse (C:\Users\ytayal\Downloads\notebook-master\node_modules\webpack\lib\Parser.js:902:15)
        at DependenciesBlock.<anonymous> (C:\Users\ytayal\Downloads\notebook-master\node_modules\webpack\lib\NormalModule.js:104:16)
        at DependenciesBlock.onModuleBuild (C:\Users\ytayal\Downloads\notebook-master\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
        at nextLoader (C:\Users\ytayal\Downloads\notebook-master\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
        at C:\Users\ytayal\Downloads\notebook-master\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
        at Storage.finished (C:\Users\ytayal\Downloads\notebook-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
        at C:\Users\ytayal\Downloads\notebook-master\node_modules\graceful-fs\graceful-fs.js:78:16
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
     @ ./~/xterm/addons ^\.\/.*$

    WARNING in ./~/xterm/addons/linkify/index.html
    Module parse failed: C:\Users\ytayal\Downloads\notebook-master\node_modules\xterm\addons\linkify\index.html Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.
    SyntaxError: Unexpected token (1:0)
        at Parser.pp$4.raise (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:2221:15)
        at Parser.pp.unexpected (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:603:10)
        at Parser.pp$3.parseExprAtom (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1822:12)
        at Parser.pp$3.parseExprSubscripts (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1715:21)
        at Parser.pp$3.parseMaybeUnary (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1692:19)
        at Parser.pp$3.parseExprOps (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1637:21)
        at Parser.pp$3.parseMaybeConditional (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1620:21)
        at Parser.pp$3.parseMaybeAssign (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1597:21)
        at Parser.pp$3.parseExpression (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:1573:21)
        at Parser.pp$1.parseStatement (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:727:47)
        at Parser.pp$1.parseTopLevel (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:638:25)
        at Parser.parse (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:516:17)
        at Object.parse (C:\Users\ytayal\Downloads\notebook-master\node_modules\acorn\dist\acorn.js:3098:39)
        at Parser.parse (C:\Users\ytayal\Downloads\notebook-master\node_modules\webpack\lib\Parser.js:902:15)
        at DependenciesBlock.<anonymous> (C:\Users\ytayal\Downloads\notebook-master\node_modules\webpack\lib\NormalModule.js:104:16)
        at DependenciesBlock.onModuleBuild (C:\Users\ytayal\Downloads\notebook-master\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
        at nextLoader (C:\Users\ytayal\Downloads\notebook-master\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
        at C:\Users\ytayal\Downloads\notebook-master\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
        at Storage.finished (C:\Users\ytayal\Downloads\notebook-master\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
        at C:\Users\ytayal\Downloads\notebook-master\node_modules\graceful-fs\graceful-fs.js:78:16
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
     @ ./~/xterm/addons ^\.\/.*$

**Comment by gnestor** [comment]
@YogeshTayal These are just webpack warnings. From the logs you provided, it looks like it in fact did build without any errors.

**Comment by YogeshTayal** [comment]
@gnestor it threw syntax error and module parse failed exception. Also, my changes didn't reflect after running that command. Anyway, I found the fix. python setup.py js css (as mentioned in CONTRIBUTING.rst) didn't work. python setup.js build worked for me.

**Comment by gnestor** [comment]
@YogeshTayal Ok, I think I remember encountering something like this after doing a `git clean` and reinstalling one time. My guidelines:

* When first installing from source: `pip install -e . --user`
* When switching between branches: `npm run build` (or `npm run build:watch` if actively developing)
* When switching between master and the 4.x branch (which are significantly different, 4.x doesn't use webpack to bundle JS): `git clean -xfdi` and then reinstall using `pip install -e . --user`

**Comment by gnestor** [comment]
@YogeshTayal Lastly, successful webpack builds still result in the following (which looks identical to your log output):

```
Hash: e9d8866eac4d174b1f87
[1] Version: webpack 1.13.2
[1] Time: 38196ms
[1]         Asset     Size  Chunks             Chunk Names
[1]   main.min.js  19.9 kB       0  [emitted]  main
[1] 1.main.min.js  4.73 MB       1  [emitted]  
[1]     + 184 hidden modules
[1] Hash: ef2d14083e953c410c61
[1] Version: webpack 1.13.2
[1] Time: 39773ms
[1]         Asset     Size  Chunks             Chunk Names
[1]   main.min.js  31.2 kB       0  [emitted]  main
[1] 1.main.min.js  4.17 MB       1  [emitted]  
[1]     + 178 hidden modules
[1] Hash: d8b79a33d7918338f1b5
[1] Version: webpack 1.13.2
[1] Time: 39881ms
[1]       Asset     Size  Chunks             Chunk Names
[1] main.min.js  3.99 MB       0  [emitted]  main
[1]     + 176 hidden modules
[1] Hash: 4c983b6bcce2583cdb93
[1] Version: webpack 1.13.2
[1] Time: 41865ms
[1]         Asset     Size  Chunks             Chunk Names
[1]   main.min.js   148 kB       0  [emitted]  main
[1] 1.main.min.js  4.49 MB       1  [emitted]  
[1]     + 193 hidden modules
[1] 
[1] WARNING in ./~/xterm/addons/linkify/index.html
[1] Module parse failed: /Users/grant/Sites/jupyter/notebook/node_modules/xterm/addons/linkify/index.html Unexpected token (1:0)
[1] You may need an appropriate loader to handle this file type.
[1] SyntaxError: Unexpected token (1:0)
[1]     at Parser.pp$4.raise (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
[1]     at Parser.pp.unexpected (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
[1]     at Parser.pp$3.parseExprAtom (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
[1]     at Parser.pp$3.parseExprSubscripts (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
[1]     at Parser.pp$3.parseMaybeUnary (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
[1]     at Parser.pp$3.parseExprOps (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
[1]     at Parser.pp$3.parseMaybeConditional (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
[1]     at Parser.pp$3.parseMaybeAssign (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
[1]     at Parser.pp$3.parseExpression (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:1573:21)
[1]     at Parser.pp$1.parseStatement (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:727:47)
[1]     at Parser.pp$1.parseTopLevel (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
[1]     at Parser.parse (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
[1]     at Object.parse (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
[1]     at Parser.parse (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/lib/Parser.js:902:15)
[1]     at DependenciesBlock.<anonymous> (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/lib/NormalModule.js:104:16)
[1]     at DependenciesBlock.onModuleBuild (/Users/grant/Sites/jupyter/notebook/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
[1]     at nextLoader (/Users/grant/Sites/jupyter/notebook/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
[1]     at /Users/grant/Sites/jupyter/notebook/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
[1]     at Storage.finished (/Users/grant/Sites/jupyter/notebook/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
[1]     at /Users/grant/Sites/jupyter/notebook/node_modules/graceful-fs/graceful-fs.js:78:16
[1]     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
[1]  @ ./~/xterm/addons ^\.\/.*$
[1] 
[1] WARNING in ./~/xterm/addons/attach/index.html
[1] Module parse failed: /Users/grant/Sites/jupyter/notebook/node_modules/xterm/addons/attach/index.html Unexpected token (1:0)
[1] You may need an appropriate loader to handle this file type.
[1] SyntaxError: Unexpected token (1:0)
[1]     at Parser.pp$4.raise (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
[1]     at Parser.pp.unexpected (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
[1]     at Parser.pp$3.parseExprAtom (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
[1]     at Parser.pp$3.parseExprSubscripts (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
[1]     at Parser.pp$3.parseMaybeUnary (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
[1]     at Parser.pp$3.parseExprOps (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
[1]     at Parser.pp$3.parseMaybeConditional (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
[1]     at Parser.pp$3.parseMaybeAssign (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
[1]     at Parser.pp$3.parseExpression (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:1573:21)
[1]     at Parser.pp$1.parseStatement (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:727:47)
[1]     at Parser.pp$1.parseTopLevel (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:638:25)
[1]     at Parser.parse (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:516:17)
[1]     at Object.parse (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/node_modules/acorn/dist/acorn.js:3098:39)
[1]     at Parser.parse (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/lib/Parser.js:902:15)
[1]     at DependenciesBlock.<anonymous> (/Users/grant/Sites/jupyter/notebook/node_modules/webpack/lib/NormalModule.js:104:16)
[1]     at DependenciesBlock.onModuleBuild (/Users/grant/Sites/jupyter/notebook/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
[1]     at nextLoader (/Users/grant/Sites/jupyter/notebook/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
[1]     at /Users/grant/Sites/jupyter/notebook/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
[1]     at Storage.finished (/Users/grant/Sites/jupyter/notebook/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
[1]     at /Users/grant/Sites/jupyter/notebook/node_modules/graceful-fs/graceful-fs.js:78:16
[1]     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)
[1]  @ ./~/xterm/addons ^\.\/.*$
```

These are webpack warnings (not errors, errors are fatal) about 2 files that webpack is trying to bundle but doesn't know how to (because they're HTML). We should definitely resolve whatever is the cause of these warnings...I'll look into it now.
