### ISSUE TITLE
fedora 25,  unable to run 'jupyter notebook --debug'

### ISSUE THREAD

**Issue by yssource** [jupyter/notebook#1998]
```
[I 23:26:33.729 NotebookApp] KernelRestarter: restarting kernel (3/5)
[D 23:26:33.730 NotebookApp] Starting kernel: ['/usr/bin/python3', '-m', 'ipykernel', '-f', '/run/user/1000/jupyter/kernel-ce847757-0e3e-419c-9f99-bc45dd22c1a9.json']
[D 23:26:33.735 NotebookApp] Connecting to: tcp://127.0.0.1:36215
Traceback (most recent call last):
  File "/usr/lib64/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.5/site-packages/ipykernel/__main__.py", line 2, in <module>
    from ipykernel import kernelapp as app
  File "/usr/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 100, in <module>
    ConnectionFileMixin):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
[W 23:26:34.929 NotebookApp] Timeout waiting for kernel_info reply from ce847757-0e3e-419c-9f99-bc45dd22c1a9
[D 23:26:34.930 NotebookApp] Opening websocket /api/kernels/ce847757-0e3e-419c-9f99-bc45dd22c1a9/channels
[D 23:26:34.930 NotebookApp] Connecting to: tcp://127.0.0.1:54911
[D 23:26:34.930 NotebookApp] Connecting to: tcp://127.0.0.1:48377
[D 23:26:34.930 NotebookApp] Connecting to: tcp://127.0.0.1:41191
[I 23:26:36.735 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel ce847757-0e3e-419c-9f99-bc45dd22c1a9 restarted
[D 23:26:36.736 NotebookApp] Starting kernel: ['/usr/bin/python3', '-m', 'ipykernel', '-f', '/run/user/1000/jupyter/kernel-ce847757-0e3e-419c-9f99-bc45dd22c1a9.json']
[D 23:26:36.740 NotebookApp] Connecting to: tcp://127.0.0.1:36215
Traceback (most recent call last):
  File "/usr/lib64/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.5/site-packages/ipykernel/__main__.py", line 2, in <module>
    from ipykernel import kernelapp as app
  File "/usr/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 100, in <module>
    ConnectionFileMixin):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
[W 23:26:39.743 NotebookApp] KernelRestarter: restart failed
[W 23:26:39.743 NotebookApp] Kernel ce847757-0e3e-419c-9f99-bc45dd22c1a9 died, removing from map.
ERROR:root:kernel ce847757-0e3e-419c-9f99-bc45dd22c1a9 restarted failed!
[D 23:26:39.793 NotebookApp] Websocket closed ce847757-0e3e-419c-9f99-bc45dd22c1a9:716BCD9899A34EE08B581CAAA7222809
[W 23:26:39.832 NotebookApp] Kernel deleted before session
[W 23:26:39.832 NotebookApp] 410 DELETE /api/sessions/752a12ed-8cb3-4eb5-a02d-ac596c62eb86 (::1) 1.65ms referer=http://localhost:8888/notebooks/Untitled.ipynb
[D 23:28:24.652 NotebookApp] 200 GET /api/contents/Untitled.ipynb?content=0&_=1482247583796 (::1) 1.05ms
[I 23:28:24.682 NotebookApp] Saving file at /Untitled.ipynb
[D 23:28:24.682 NotebookApp] Saving /tmp/n/Untitled.ipynb
[D 23:28:24.795 NotebookApp] 200 PUT /api/contents/Untitled.ipynb (::1) 113.98ms
```

**Comment by takluyver** [comment]
I think that error means it's finding an older version of IPython installed somewhere (maybe from dnf?). Try uninstalling all IPython and Jupyter related stuff you can find, and then installing again.

**Comment by yssource** [comment]
@takluyver Thanks. It works for me.
