### ISSUE TITLE
Failed to run command | API request failed

### ISSUE THREAD

**Issue by ShrinathGupta** [jupyter/notebook#2021]
hi everyone,
I am getting following error when i am trying to start kernel for javascript.

```
**Failed to run command:
   [u'/usr/local/lib/python2.7/dist-packages', u'eclair:org.eclairjs.nashorn.JavascriptInterpreter', u'eclair', u'--nosparkcontext', u'--profile', u'/run/user/1002/jupyter/kernel-8db32e1c-a195-4198-8ce5-a5cd7adaecd9.json']
       PATH='/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin'
       with kwargs:
   {'cwd': u'/home/stack/.local/share/jupyter/kernels/eclair', 'stdin': -1, 'preexec_fn': <function <lambda> at 0x7f441d4a0aa0>, 'stderr': None, 'stdout': None}**

```

but its' working fine when i'm creating kernel for python.
 
when i use it in code to instantiate *sparkcontext* object it's throwing following error.

```
**API request failed: Unexpected token < in JSON at position 0
Failed to start Jupyter session { event: undefined,
 xhr: 
  { UNSENT: 0,
    OPENED: 1,
    HEADERS_RECEIVED: 2,
    LOADING: 3,
    DONE: 4,
    readyState: 4,
    onreadystatechange: null,
    responseText: '<!DOCTYPE html>\n<html>\n  <head>\n    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>\n    <title>Chronograf</title>\n  <link rel="shortcut icon" href="/favicon.ico"><link href="/style.css" rel="stylesheet"></head>\n  <body>\n    <div id=\'react-root\'></div>\n  <script type="text/javascript" src="/manifest.feab17100a1ee5216fe1.js"></script><script type="text/javascript" src="/vendor.a58fbf90d1707f1cd128.js"></script><script type="text/javascript" src="/app.213b96b6faf8023f24b8.js"></script></body>\n</html\n',
    responseXML: '',
    status: 200,
    statusText: null,
    withCredentials: false,
    open: [Function],
    setDisableHeaderCheck: [Function],
    setRequestHeader: [Function],
    getResponseHeader: [Function],
    getAllResponseHeaders: [Function],
    getRequestHeader: [Function],
    send: [Function],
    handleError: [Function],
    abort: [Function],
    addEventListener: [Function],
    removeEventListener: [Function],
    dispatchEvent: [Function],
    onload: [Function],
    onabort: [Function],
    onerror: [Function],
    ontimeout: [Function] },
 ajaxSettings: 
  { method: 'POST',
    dataType: 'json',
    data: '{"kernel":{"name":"eclair"},"notebook":{"path":"Simple Text"}}',
    contentType: 'application/json',
    cache: false },
 throwError: 'Unexpected token < in JSON at position 0' }
(node:28633) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): ReferenceError: err is not defined**
```

**Comment by minrk** [comment]
The executable in your `kernel.json` is `u'/usr/local/lib/python2.7/dist-packages'`, which is a directory, not a valid executable. What is the command you expect to run to launch this kernel?

**Comment by ShrinathGupta** [comment]
@minrk I'm using jupyter notebook command and on it's URL under new drop down i'm choosing my kernel name and it's getting failed to start kenrnel.
Error: 

**

```
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/notebook/base/handlers.py", line 503, in wrapper
>     result = yield gen.maybe_future(method(self, *args, **kwargs))
>   File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1015, in run
>     value = future.result()
>   File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
>     raise_exc_info(self._exc_info)
>   File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1021, in run
>     yielded = self.gen.throw(*exc_info)
>   File "/usr/local/lib/python2.7/dist-packages/notebook/services/sessions/handlers.py", line 75, in post
>     type=mtype))
>   File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1015, in run
>     value = future.result()
>   File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
>     raise_exc_info(self._exc_info)
>   File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1021, in run
>     yielded = self.gen.throw(*exc_info)
>   File "/usr/local/lib/python2.7/dist-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
>     kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
>   File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1015, in run
>     value = future.result()
>   File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
>     raise_exc_info(self._exc_info)
>   File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1021, in run
>     yielded = self.gen.throw(*exc_info)
>   File "/usr/local/lib/python2.7/dist-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
>     self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
>   File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1015, in run
>     value = future.result()
>   File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
>     raise_exc_info(self._exc_info)
>   File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 285, in wrapper
>     yielded = next(result)
>   File "/usr/local/lib/python2.7/dist-packages/notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
>     super(MappingKernelManager, self).start_kernel(**kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
>     km.start_kernel(**kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/jupyter_client/manager.py", line 243, in start_kernel
>     **kw)
>   File "/usr/local/lib/python2.7/dist-packages/jupyter_client/manager.py", line 189, in _launch_kernel
>     return launch_kernel(kernel_cmd, **kw)
>   File "/usr/local/lib/python2.7/dist-packages/jupyter_client/launcher.py", line 123, in launch_kernel
>     proc = Popen(cmd, **kwargs)
>   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
>     errread, errwrite)
>   File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
```

**
but if i'm not running jupyter notebook and try to run it using node js it throws different error.
Please see below mention nodejs snippet.
```
var eclairjs = require('eclairjs');
var spark = new eclairjs();
var sc = new spark.SparkContext("local[*]", "Simple Text");

var data = sc.parallelize([1,2,3,4,5,6,7,8,9,0]);

data.collect().then(function(val) {
  console.log("Success:", val);

  sc.stop().then(process.exit);
}).catch(function(err) {
  console.log("Error:", err);
  sc.stop().then(process.exit);
});

```
Error:

> API request failed: Unexpected token < in JSON at position 0
> Failed to start Jupyter session { event: undefined,
>  xhr: 
>   { UNSENT: 0,
>     OPENED: 1,
>     HEADERS_RECEIVED: 2,
>     LOADING: 3,
>     DONE: 4,
>     readyState: 4,
>     onreadystatechange: null,
>     responseText: '<!DOCTYPE html>\n<html>\n  <head>\n    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>\n    <title>Chronograf</title>\n  <link rel="shortcut icon" href="/favicon.ico"><link href="/style.css" rel="stylesheet"></head>\n  <body>\n    <div id=\'react-root\'></div>\n  <script type="text/javascript" src="/manifest.feab17100a1ee5216fe1.js"></script><script type="text/javascript" src="/vendor.a58fbf90d1707f1cd128.js"></script><script type="text/javascript" src="/app.213b96b6faf8023f24b8.js"></script></body>\n</html\n',
>     responseXML: '',
>     status: 200,
>     statusTe...

**Comment by minrk** [comment]
How did you install this js kernel? The command to run that it has installed is not valid, so I'm guessing the kernel's installation is the source of the problem.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
