### ISSUE TITLE
Jupyter notebook and jupyter console won't start on win 10

### ISSUE THREAD

**Issue by thekuroro** [jupyter/notebook#2062]
Hello guys i tried many time to install and reinstall anaconda but I all way end with the same problem, went I try to launch jupytrer notebook or jupyter console it crash and give me the message below, does anyone knows how to solve it ?

Thank's

Traceback (most recent call last):
  File "C:\Dev\Anaconda3\Scripts\jupyter-console-script.py", line 4, in <module>
    app.main()
  File "C:\Dev\Anaconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Dev\Anaconda3\lib\site-packages\traitlets\config\application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-116>", line 2, in initialize
  File "C:\Dev\Anaconda3\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Dev\Anaconda3\lib\site-packages\jupyter_console\app.py", line 134, in initialize
    super(ZMQTerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-115>", line 2, in initialize
  File "C:\Dev\Anaconda3\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Dev\Anaconda3\lib\site-packages\jupyter_core\application.py", line 243, in initialize
    self.migrate_config()
  File "C:\Dev\Anaconda3\lib\site-packages\jupyter_core\application.py", line 169, in migrate_config
    migrate()
  File "C:\Dev\Anaconda3\lib\site-packages\jupyter_core\migrate.py", line 240, in migrate
    ensure_dir_exists(env['jupyter_config'])
  File "C:\Dev\Anaconda3\lib\site-packages\ipython_genutils\path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "C:\Dev\Anaconda3\lib\os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Dev\Anaconda3\lib\os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Dev\Anaconda3\lib\os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Dev\Anaconda3\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte: 'C:\\Dev\\Anaconda3\\Sc
ripts\\"C:'

**Comment by takluyver** [comment]
What do you get from:

```python
from jupyter_core.paths import jupyter_config_dir
jupyter_config_dir()
```

**Comment by RobbeSneyders** [comment]
I had the same problem.
[This answer on stackoverflow](http://stackoverflow.com/a/41521017/4098821) solved it for me.

**Comment by phseidl** [comment]
creating a new environment solved the issue for me:
```
conda create --name py35 python=3.5
```

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
