### ISSUE TITLE
Error output when running tests

### ISSUE THREAD

**Issue by gnestor** [jupyter/notebook#2101]
I'm seeing the following when running the Python tests:

```
grant:notebook grant$ nosetests
....Error loading server extension jupyterlab
Traceback (most recent call last):
  File "/Users/grant/Sites/jupyter/notebook/notebook/notebookapp.py", line 1120, in init_server_extensions
    func(self)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labapp.py", line 184, in load_jupyter_server_extension
    extensions = get_extensions(lab_config)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labapp.py", line 137, in get_extensions
    folder = find_labextension(name)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 464, in find_labextension
    for exts in _labextension_dirs():
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 1066, in _labextension_dirs
    pjoin(SYSTEM_JUPYTER_PATH[0], 'labextensions')
IndexError: list index out of range
......Error loading server extension jupyterlab
Traceback (most recent call last):
  File "/Users/grant/Sites/jupyter/notebook/notebook/notebookapp.py", line 1120, in init_server_extensions
    func(self)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labapp.py", line 184, in load_jupyter_server_extension
    extensions = get_extensions(lab_config)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labapp.py", line 137, in get_extensions
    folder = find_labextension(name)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 464, in find_labextension
    for exts in _labextension_dirs():
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 1066, in _labextension_dirs
    pjoin(SYSTEM_JUPYTER_PATH[0], 'labextensions')
IndexError: list index out of range
...Error loading server extension jupyterlab
Traceback (most recent call last):
  File "/Users/grant/Sites/jupyter/notebook/notebook/notebookapp.py", line 1120, in init_server_extensions
    func(self)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labapp.py", line 184, in load_jupyter_server_extension
    extensions = get_extensions(lab_config)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labapp.py", line 137, in get_extensions
    folder = find_labextension(name)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 464, in find_labextension
    for exts in _labextension_dirs():
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 1066, in _labextension_dirs
    pjoin(SYSTEM_JUPYTER_PATH[0], 'labextensions')
IndexError: list index out of range
................................./Users/grant/Sites/jupyter/nbformat/nbformat/validator.py:233: UserWarning: No schema for validating v2 notebooks
  warnings.warn("No schema for validating v%s notebooks" % version, UserWarning)
.Error loading server extension jupyterlab
Traceback (most recent call last):
  File "/Users/grant/Sites/jupyter/notebook/notebook/notebookapp.py", line 1120, in init_server_extensions
    func(self)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labapp.py", line 184, in load_jupyter_server_extension
    extensions = get_extensions(lab_config)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labapp.py", line 137, in get_extensions
    folder = find_labextension(name)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 464, in find_labextension
    for exts in _labextension_dirs():
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 1066, in _labextension_dirs
    pjoin(SYSTEM_JUPYTER_PATH[0], 'labextensions')
IndexError: list index out of range
.......................................................................Error loading server extension jupyterlab
Traceback (most recent call last):
  File "/Users/grant/Sites/jupyter/notebook/notebook/notebookapp.py", line 1120, in init_server_extensions
    func(self)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labapp.py", line 184, in load_jupyter_server_extension
    extensions = get_extensions(lab_config)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labapp.py", line 137, in get_extensions
    folder = find_labextension(name)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 464, in find_labextension
    for exts in _labextension_dirs():
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 1066, in _labextension_dirs
    pjoin(SYSTEM_JUPYTER_PATH[0], 'labextensions')
IndexError: list index out of range
..Failed to import the site module
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 182, in _get_module_lock
KeyError: '_sitebuiltins'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/grant/anaconda/lib/python3.5/site.py", line 74, in <module>
    import _sitebuiltins
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 165, in __enter__
  File "<frozen importlib._bootstrap>", line 183, in _get_module_lock
KeyboardInterrupt
..Error loading server extension jupyterlab
Traceback (most recent call last):
  File "/Users/grant/Sites/jupyter/notebook/notebook/notebookapp.py", line 1120, in init_server_extensions
    func(self)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labapp.py", line 184, in load_jupyter_server_extension
    extensions = get_extensions(lab_config)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labapp.py", line 137, in get_extensions
    folder = find_labextension(name)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 464, in find_labextension
    for exts in _labextension_dirs():
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 1066, in _labextension_dirs
    pjoin(SYSTEM_JUPYTER_PATH[0], 'labextensions')
IndexError: list index out of range
.......Error loading server extension jupyterlab
Traceback (most recent call last):
  File "/Users/grant/Sites/jupyter/notebook/notebook/notebookapp.py", line 1120, in init_server_extensions
    func(self)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labapp.py", line 184, in load_jupyter_server_extension
    extensions = get_extensions(lab_config)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labapp.py", line 137, in get_extensions
    folder = find_labextension(name)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 464, in find_labextension
    for exts in _labextension_dirs():
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 1066, in _labextension_dirs
    pjoin(SYSTEM_JUPYTER_PATH[0], 'labextensions')
IndexError: list index out of range
..........Error loading server extension jupyterlab
Traceback (most recent call last):
  File "/Users/grant/Sites/jupyter/notebook/notebook/notebookapp.py", line 1120, in init_server_extensions
    func(self)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labapp.py", line 184, in load_jupyter_server_extension
    extensions = get_extensions(lab_config)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labapp.py", line 137, in get_extensions
    folder = find_labextension(name)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 464, in find_labextension
    for exts in _labextension_dirs():
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 1066, in _labextension_dirs
    pjoin(SYSTEM_JUPYTER_PATH[0], 'labextensions')
IndexError: list index out of range
...........Error loading server extension jupyterlab
Traceback (most recent call last):
  File "/Users/grant/Sites/jupyter/notebook/notebook/notebookapp.py", line 1120, in init_server_extensions
    func(self)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labapp.py", line 184, in load_jupyter_server_extension
    extensions = get_extensions(lab_config)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labapp.py", line 137, in get_extensions
    folder = find_labextension(name)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 464, in find_labextension
    for exts in _labextension_dirs():
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 1066, in _labextension_dirs
    pjoin(SYSTEM_JUPYTER_PATH[0], 'labextensions')
IndexError: list index out of range
.Error loading server extension jupyterlab
Traceback (most recent call last):
  File "/Users/grant/Sites/jupyter/notebook/notebook/notebookapp.py", line 1120, in init_server_extensions
    func(self)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labapp.py", line 184, in load_jupyter_server_extension
    extensions = get_extensions(lab_config)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labapp.py", line 137, in get_extensions
    folder = find_labextension(name)
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 464, in find_labextension
    for exts in _labextension_dirs():
  File "/Users/grant/Sites/jupyter/jupyterlab/jupyterlab/labextensions.py", line 1066, in _labextension_dirs
    pjoin(SYSTEM_JUPYTER_PATH[0], 'labextensions')
IndexError: list index out of range
...................................................................S
----------------------------------------------------------------------
Ran 219 tests in 32.620s

OK (SKIP=1)
```

**Comment by gnestor** [comment]
The following is my output when I run the js tests (it hangs indefinitely on the mockextension group): 

```
grant:notebook grant$ python -m notebook.jstest

Test group: base
Running tests with notebook directory '/var/folders/wg/yhdj316j4hs2_z5s0_5_k0tc0000gp/T/tmpi2pzidgu'
Test file: /Users/grant/Sites/jupyter/notebook/notebook/tests/base/highlight.js 
Timeout for http://localhost:8889/a@b/
Is the notebook server running?
FAIL Wait timeout occured (10000ms)
#    type: uncaughtError
#    file: /Users/grant/Sites/jupyter/notebook/notebook/tests/base/highlight.js
#    error: Wait timeout occured (10000ms)

#    stack: not provided

Captured console.log:
    loaded custom.js
FAIL Couldn't find popup with url containing ''
#    type: uncaughtError
#    file: /Users/grant/Sites/jupyter/notebook/notebook/tests/base/highlight.js:137
#    error: Couldn't find popup with url containing ''
#           findByURL@phantomjs://platform/pagestack.js:137:89
#           find@phantomjs://platform/pagestack.js:89:35
#           _step@phantomjs://platform/casper.js:2527:41
#           runStep@phantomjs://platform/casper.js:1615:31
#           checkStep@phantomjs://platform/casper.js:406:28
#    stack: not provided
Test file: /Users/grant/Sites/jupyter/notebook/notebook/tests/base/keyboard.js  
Timeout for http://localhost:8889/a@b/
Is the notebook server running?
FAIL Wait timeout occured (10000ms)
#    type: uncaughtError
#    file: /Users/grant/Sites/jupyter/notebook/notebook/tests/base/keyboard.js
#    error: Wait timeout occured (10000ms)

#    stack: not provided

Captured console.log:
    loaded custom.js
FAIL Couldn't find popup with url containing ''
#    type: uncaughtError
#    file: /Users/grant/Sites/jupyter/notebook/notebook/tests/base/keyboard.js:137
#    error: Couldn't find popup with url containing ''
#           findByURL@phantomjs://platform/pagestack.js:137:89
#           find@phantomjs://platform/pagestack.js:89:35
#           _step@phantomjs://platform/casper.js:2527:41
#           runStep@phantomjs://platform/casper.js:1615:31
#           checkStep@phantomjs://platform/casper.js:406:28
#    stack: not provided
Test file: /Users/grant/Sites/jupyter/notebook/notebook/tests/base/misc.js      
Timeout for http://localhost:8889/a@b/
Is the notebook server running?
FAIL Wait timeout occured (10000ms)
#    type: uncaughtError
#    file: /Users/grant/Sites/jupyter/notebook/notebook/tests/base/misc.js
#    error: Wait timeout occured (10000ms)

#    stack: not provided

Captured console.log:
    loaded custom.js
FAIL Couldn't find popup with url containing ''
#    type: uncaughtError
#    file: /Users/grant/Sites/jupyter/notebook/notebook/tests/base/misc.js:137
#    error: Couldn't find popup with url containing ''
#           findByURL@phantomjs://platform/pagestack.js:137:89
#           find@phantomjs://platform/pagestack.js:89:35
#           _step@phantomjs://platform/casper.js:2527:41
#           runStep@phantomjs://platform/casper.js:1615:31
#           checkStep@phantomjs://platform/casper.js:406:28
#    stack: not provided
Test file: /Users/grant/Sites/jupyter/notebook/notebook/tests/base/security.js  
Timeout for http://localhost:8889/a@b/
Is the notebook server running?
FAIL Wait timeout occured (10000ms)
#    type: uncaughtError
#    file: /Users/grant/Sites/jupyter/notebook/notebook/tests/base/security.js
#    error: Wait timeout occured (10000ms)

#    stack: not provided

Captured console.log:
    loaded custom.js
FAIL Couldn't find popup with url containing ''
#    type: uncaughtError
#    file: /Users/grant/Sites/jupyter/notebook/notebook/tests/base/security.js:137
#    error: Couldn't find popup with url containing ''
#           findByURL@phantomjs://platform/pagestack.js:137:89
#           find@phantomjs://platform/pagestack.js:89:35
#           _step@phantomjs://platform/casper.js:2527:41
#           runStep@phantomjs://platform/casper.js:1615:31
#           checkStep@phantomjs://platform/casper.js:406:28
#    stack: not provided
Test file: /Users/grant/Sites/jupyter/notebook/notebook/tests/base/utils.js     
Timeout for http://localhost:8889/a@b/
Is the notebook server running?
FAIL Wait timeout occured (10000ms)
#    type: uncaughtError
#    file: /Users/grant/Sites/jupyter/notebook/notebook/tests/base/utils.js
#    error: Wait timeout occured (10000ms)

#    stack: not provided

Captured console.log:
    loaded custom.js
FAIL Couldn't find popup with url containing ''
#    type: uncaughtError
#    file: /Users/grant/Sites/jupyter/notebook/notebook/tests/base/utils.js:137
#    error: Couldn't find popup with url containing ''
#           findByURL@phantomjs://platform/pagestack.js:137:89
#           find@phantomjs://platform/pagestack.js:89:35
#           _step@phantomjs://platform/casper.js:2527:41
#           runStep@phantomjs://platform/casper.js:1615:31
#           checkStep@phantomjs://platform/casper.js:406:28
#    stack: not provided
FAIL 9 tests executed in 51.984s, 0 passed, 9 failed, 0 dubious, 0 skipped.     

Details for the 9 failed tests:

In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/highlight.js
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/highlight.js
    uncaughtError: Wait timeout occured (10000ms)
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/highlight.js:137
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/highlight.js
    uncaughtError: Couldn't find popup with url containing ''
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/keyboard.js
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/highlight.js
    uncaughtError: Wait timeout occured (10000ms)
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/keyboard.js:137
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/keyboard.js
    uncaughtError: Couldn't find popup with url containing ''
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/misc.js
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/keyboard.js
    uncaughtError: Wait timeout occured (10000ms)
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/misc.js:137
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/misc.js
    uncaughtError: Couldn't find popup with url containing ''
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/security.js
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/misc.js
    uncaughtError: Wait timeout occured (10000ms)
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/security.js:137
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/security.js
    uncaughtError: Couldn't find popup with url containing ''
In /Users/grant/Sites/jupyter/notebook/notebook/tests/base/utils.js
  Untitled suite in /Users/grant/Sites/jupyter/notebook/notebook/tests/base/security.js
    uncaughtError: Wait timeout occured (10000ms)

Test group: mockextension
Running tests with notebook directory '/var/folders/wg/yhdj316j4hs2_z5s0_5_k0tc0000gp/T/tmpys4z4hwb'
Test file: /Users/grant/Sites/jupyter/notebook/notebook/tests/mockextension/index.js
```

**Comment by blink1073** [comment]
Hmm, we're importing `SYSTEM_JUPYTER_PATH` [here](https://github.com/jupyterlab/jupyterlab/blob/d14174875712c9ad24bea31be0d54a31daa18b27/jupyterlab/labextensions.py#L19), looks like we need to check if it is empty.

**Comment by takluyver** [comment]
For the former, check that your `jupyter_core` is up to date. I don't think that there should be any case where SYSTEM_JUPYTER_PATH is an empty list (unless conda packaging changes it?)

**Comment by blink1073** [comment]
(Thomas' answer makes more sense).

**Comment by blink1073** [comment]
nbextensions are using the same pattern: https://github.com/jupyter/notebook/blob/2eb7bf19530252247dc9b112016080733b150352/notebook/nbextensions.py#L1013

**Comment by blink1073** [comment]
The second issue looks like a symptom of the first.

**Comment by gnestor** [comment]
Thanks, guys! 

I tried `pip install --upgrade jupyter-core` but no luck.

I ran a `conda list` and I have a couple jupyter-cores:

``
jupyter-core              4.2.1                     <pip>
jupyter-core              4.2.0                     <pip>
jupyter-react             0.1.3                     <pip>
jupyter_client            4.2.2                    py35_0  
jupyter_console           4.1.1                    py35_0  
jupyter_contrib_core      0.3.0                    py35_0    conda-forge
jupyter_core              4.1.0                    py35_0  
```

**Comment by takluyver** [comment]
That's a bit disturbing that there are two different versions. Try uninstalling with both pip and conda, and then installing it again with just one.

**Comment by takluyver** [comment]
Correction, three versions. Even worse.

**Comment by gnestor** [comment]
Ok, I'm upgraded:

```
jupyter-core              4.2.1                     <pip>
```

I should mention that I've installed all extensions using `--sys-prefix` and cleared out any extension config in nbconfig and labconfig in my user directory.

**Comment by blink1073** [comment]
What is the output of `python -c "from jupyter_core.paths import SYSTEM_JUPYTER_PATH; print(SYSTEM_JUPYTER_PATH)"`?

**Comment by gnestor** [comment]
`['/usr/local/share/jupyter', '/usr/share/jupyter']`

**Comment by blink1073** [comment]
And you're still seeing the same error as in the original comment?

**Comment by gnestor** [comment]
Ya 😕

**Comment by blink1073** [comment]
I just ran the tests against Notebook and JupyterLab master locally and I'm not seeing this.  What is the output of `which nosetests` vs `which python`?

**Comment by gnestor** [comment]
Thanks for your help here, @blink1073!

```
grant:notebook grant$ which nosetests
/Users/grant/anaconda/bin/nosetests
grant:notebook grant$ which python
/Users/grant/anaconda/bin/python
```

**Comment by blink1073** [comment]
That looks like what I have...

**Comment by blink1073** [comment]
Are you able to launch `jupyter notebook` and `jupyter lab` successfully?

**Comment by gnestor** [comment]
Ya 👍

**Comment by gnestor** [comment]
BTW, Travis runs all the tests that I would run locally, correct? So as long as Travis builds are passing, then we should be ok?

**Comment by blink1073** [comment]
Yeah, but push and pray is no way to work :wink:.  Just as a sanity check, can you manually rename the JupyterLab folder so it isn't picked up and run it again?

**Comment by gnestor** [comment]
I'm seeing a different error now:

```
grant:notebook grant$ nosetests
....Error loading server extension jupyterlab
Traceback (most recent call last):
  File "/Users/grant/Sites/jupyter/notebook/notebook/notebookapp.py", line 1257, in init_server_extensions
    mod = importlib.import_module(modulename)
  File "/Users/grant/anaconda/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'jupyterlab'
```

**Comment by blink1073** [comment]
Okay, how about moving the JLab folder back and disabling the JLab server extension?

**Comment by gnestor** [comment]
That fixes it. Does this output look like the tests are passing or not?

```
grant:notebook grant$ nosetests
..................................................................................................................................................Failed to import the site module
Traceback (most recent call last):
  File "/Users/grant/anaconda/lib/python3.5/site.py", line 72, in <module>
    import os
  File "/Users/grant/anaconda/lib/python3.5/os.py", line 57, in <module>
    import posixpath as path
  File "/Users/grant/anaconda/lib/python3.5/posixpath.py", line 16, in <module>
    import genericpath
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 744, in get_code
  File "<frozen importlib._bootstrap_external>", line 828, in path_stats
  File "<frozen importlib._bootstrap_external>", line 75, in _path_stat
KeyboardInterrupt
....................................................................................................S
----------------------------------------------------------------------
Ran 247 tests in 34.434s

OK (SKIP=1)
```

**Comment by blink1073** [comment]
That looks good.  The only other thing I can think of is that using `importlib` to import JupyterLab is not working on your machine.  https://github.com/jupyter/notebook/blob/2eb7bf19530252247dc9b112016080733b150352/notebook/notebookapp.py#L1239

**Comment by takluyver** [comment]
If you move the `jupyterlab` folder that it's importing, but leave it configured in `nbserver_extensions`, then `ImportError: No module named 'jupyterlab'` is expected (it shouldn't stop the notebook server from working, though).

The original IndexError is strange.

**Comment by blink1073** [comment]
What is the output of `python -c "import importlib;print(importlib.import_module('jupyterlab').__path__)"`?

**Comment by gnestor** [comment]
`['/Users/grant/Sites/jupyter/jupyterlab/jupyterlab']`

**Comment by blink1073** [comment]
Whelp, color me stumped.

**Comment by minrk** [comment]
I think it's the mock environment setup for the tests. It empties SYSTEM_JUPYTER_PATH, which is probably shouldn't.

It should also be preventing any extensions from being loaded, which I'll work on shortly.

**Comment by minrk** [comment]
#2111 should do it, I think.
