### ISSUE TITLE
Jupyter terminates/exits with a conda error

### ISSUE THREAD

**Issue by drorata** [jupyter/notebook#2110]
Recently, whenever I terminate Jupyter by hitting CTRL-C I get the following error:

```
Traceback (most recent call last):
  File "/Users/username/anaconda3/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/Users/username/anaconda3/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/username/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/username/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 1247, in start
    self.io_loop.start()
  File "/Users/username/anaconda3/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/Users/username/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 862, in start
^C  File "/Users/username/anaconda3/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 122, in poll
    z_events = self._poller.poll(1000*timeout)
  File "/Users/username/anaconda3/lib/python3.5/site-packages/zmq/sugar/poll.py", line 99, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 123, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:2186)
  File "zmq/backend/cython/_poll.pyx", line 116, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:2036)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:2418)
  File "/Users/username/anaconda3/lib/python3.5/site-packages/conda/gateways/signals.py", line 15, in conda_signal_handler
    raise CondaSignalInterrupt(signum)
conda.exceptions.CondaSignalInterrupt: Signal interrupt SIGINT
```

I have no idea how to solve it nor start to debug it. I'll be happy to follow up on this one.

Thanks

**Comment by takluyver** [comment]
Looks like something conda is adding. @damianavila does this look familiar? Is it related to nb_conda_kernels?

**Comment by drorata** [comment]
Could be... I am using conda. In addition, I also have the following file: `~/Library/Jupyter/kernels/python3/kernel.json` with the following content:

```
{
 "language": "python",
 "display_name": "Python 3",
 "argv": [
  "/Users/drorata/anaconda3/bin/python",
  "-m",
  "ipykernel",
  "-f",
  "{connection_file}"
 ]
}
```

**Comment by takluyver** [comment]
That looks normal. The traceback is coming from the notebook application, in any case, not a kernel.

**Comment by drorata** [comment]
What is normal? The kernel definition or the error message? 🙃

**Comment by takluyver** [comment]
Sorry, the kernel definition looks normal. I haven't seen the error before.

**Comment by takluyver** [comment]
I've reported this to conda at conda/conda#4503

**Comment by damianavila** [comment]
@takluyver Have you seen this lately? Looking into https://github.com/conda/conda/issues/4503, it seems @kalefranz has worked out a solution (https://github.com/conda/conda/issues/4503#issuecomment-282458483).

**Comment by takluyver** [comment]
I think this was only reported once, and I don't see it myself (I don't usually use a conda-managed notebook install). But I think we can hope this is fixed on the conda side.
