### ISSUE TITLE
Jupyter:: error: [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by hanboa** [jupyter/notebook#2213]
I was totally fine with running the jupyter process before the server were shutdown by the admin and there was no any update or upgrade and nothing changed.
After getting back the server, I used the following command again to run the Jupyter process by my IP address and port:
jupyter notebook --ip=xxx.xxx.xxx.xxx --port=xxxx

It worked fine at the beginning but it turned out to be the kernel error in [1] (failed to start the kernel due to unknown server error) after I clicked on the web page[3] for coding. In the end, it became network error due to the timeout[2].

Also, I have tried the following:
1. Used localhost or 127.0.0.1
2. Checked the port is not blocked by the firewall

Does anyone have any idea?

[1] error message

```
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/notebook/base/handlers.py", line 458, in wrapper
result = yield gen.maybe_future(method(self, *args, **kwargs))
File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1008, in run
value = future.result()
File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
raise_exc_info(self._exc_info)
File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1014, in run
yielded = self.gen.throw(*exc_info)
File "/usr/local/lib/python2.7/dist-packages/notebook/services/sessions/handlers.py", line 58, in post
sm.create_session(path=path, kernel_name=kernel_name))
File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1008, in run
value = future.result()
File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
raise_exc_info(self._exc_info)
File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1014, in run
yielded = self.gen.throw(*exc_info)
File "/usr/local/lib/python2.7/dist-packages/notebook/services/sessions/sessionmanager.py", line 73, in create_session
self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1008, in run
value = future.result()
File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 232, in result
raise_exc_info(self._exc_info)
File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 282, in wrapper
yielded = next(result)
File "/usr/local/lib/python2.7/dist-packages/notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
super(MappingKernelManager, self).start_kernel(**kwargs)
File "/usr/local/lib/python2.7/dist-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
km.start_kernel(**kwargs)
File "/usr/local/lib/python2.7/dist-packages/jupyter_client/manager.py", line 224, in start_kernel
self.write_connection_file()
File "/usr/local/lib/python2.7/dist-packages/jupyter_client/connect.py", line 406, in write_connection_file
kernel_name=self.kernel_name
File "/usr/local/lib/python2.7/dist-packages/jupyter_client/connect.py", line 98, in write_connection_file
sock.bind((ip, 0))
File "/usr/lib/python2.7/socket.py", line 224, in meth
return getattr(self._sock,name)(*args)
error: [Errno 99] Cannot assign requested address
```

[2] Network Error (tcp_error) due to "operation timed out"
![image](https://cloud.githubusercontent.com/assets/5266945/23203840/38242de8-f91f-11e6-89ce-0040101703f4.png)

[3] View from the webpage
![image](https://cloud.githubusercontent.com/assets/5266945/23204024/e080f728-f91f-11e6-89ec-1624e1d2da17.png)

**Comment by takluyver** [comment]
I don't recall any failures like that, but it might happen if all the sockets on the system were already in use (bind() with port 0 is a way to ask for a random port number). Or maybe there's some security policy that disables the high-numbered ports it uses.

**Comment by hanboa** [comment]
I found the reason by pinging my localhost ending up with no reply.
I realized I need to get the network loopback work! As follows:
sudo ifconfig lo up

Then, it works!

**Comment by takluyver** [comment]
I'm glad you worked it out, but a bit puzzled because I thought loopback was always enabled by default. Is there a kind of system that doesn't have it by default, or had you turned it off for some reason?
