### ISSUE TITLE
Jupyter Notebook Error after installation while running. [WinError 10060]

### ISSUE THREAD

**Issue by manansatra3** [jupyter/notebook#2221]
I am using Windows 10 64 bit. I tried reinstalling Anaconda3 4.3.0.1 many times (Also by disabling firewall and AV program- QuickHeal completely)

When I type "jupyter notebook" in cmd the error shown in the screenshot occurs. Changing port ("jupyter notebook --port=8889" or any other port such as 3000 4000 etc. does not help either.)

ScreenShot of the error:

<img width="960" alt="error" src="https://cloud.githubusercontent.com/assets/21975482/23294123/d5a1ff66-fa8f-11e6-84b1-2fd8ab925f8a.png">

**Comment by takluyver** [comment]
That doesn't look familiar. Can you show the bottom of the traceback it gives?

(Preferably copy and paste errors as text rather than screenshots - it's easier to read and it means people can search based on the error message. You can copy text in the command prompt from the right click menu)

**Comment by manansatra3** [comment]
hey @takluyver here's the error:

C:\Users\MANAN>jupyter notebook
Traceback (most recent call last):
  File "C:\Users\MANAN\Anaconda3\lib\site-packages\tornado\platform\common.py", line 44, in __init__
    self.writer.connect(connect_address)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\MANAN\Anaconda3\Scripts\jupyter-notebook-script.py", line 5, in <module>
    sys.exit(notebook.notebookapp.main())
  File "C:\Users\MANAN\Anaconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\MANAN\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "C:\Users\MANAN\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\MANAN\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1142, in initialize
    self.init_webapp()
  File "C:\Users\MANAN\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 983, in init_webapp
    self.http_server.listen(port, self.ip)
  File "C:\Users\MANAN\Anaconda3\lib\site-packages\tornado\tcpserver.py", line 127, in listen
    self.add_sockets(sockets)
  File "C:\Users\MANAN\Anaconda3\lib\site-packages\tornado\tcpserver.py", line 139, in add_sockets
    self.io_loop = IOLoop.current()
  File "C:\Users\MANAN\Anaconda3\lib\site-packages\tornado\ioloop.py", line 213, in current
    return IOLoop.instance()
  File "C:\Users\MANAN\Anaconda3\lib\site-packages\tornado\ioloop.py", line 161, in instance
    IOLoop._instance = IOLoop()
  File "C:\Users\MANAN\Anaconda3\lib\site-packages\tornado\util.py", line 278, in __new__
    instance.initialize(*args, **init_kwargs)
  File "C:\Users\MANAN\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 139, in initialize
    super(ZMQIOLoop, self).initialize(impl=impl, **kwargs)
  File "C:\Users\MANAN\Anaconda3\lib\site-packages\tornado\ioloop.py", line 705, in initialize
    self._waker = Waker()
  File "C:\Users\MANAN\Anaconda3\lib\site-packages\tornado\platform\common.py", line 48, in __init__
    detail[0] != errno.WSAEADDRINUSE):
TypeError: 'TimeoutError' object is not subscriptable

C:\Users\MANAN>

**Comment by takluyver** [comment]
It sounds a bit similar to #1936, though it's a slightly different error message. Is it possible there's some other security software on the machine, or that you couldn't fully disable the one you mentioned?

**Comment by manansatra3** [comment]
Well it sounds similar to many such queries on stackoverflow as well but none of them are same as this unfortunately.

Yes, I have QuickHeal Antivirus installed in my system on top of the default windows firewall. I disabled both of them completely ( I am sure about this since I have installed many more applications by disabling the AV in similar fashion ).
Also, I installed virtual machine, loaded ubuntu, installed (with AV turned ON) anaconda and tried starting jupyter notebook. Surprisingly, it worked all fine on ubuntu.

**Comment by manansatra3** [comment]
The issue is solved. I instead of disabling my AV, uninstalled it and then it worked for me. After installation and first run of jupyter notebook, I reinstalled my AV and still worked fine. So, my issue is resolved. We can close this issue. Thank-you @takluyver for the help and support provided!

**Comment by shaad1994** [comment]
i have a prblem .. pls someone help me to fix this... when i tried to open jupyter notebook this is happened ..


Microsoft Windows [Version 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Dell>jupyter notebook
Traceback (most recent call last):
  File "C:\Users\Dell\Anaconda2\Scripts\jupyter-notebook-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Dell\Anaconda2\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\Dell\Anaconda2\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "C:\Users\Dell\Anaconda2\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\Dell\Anaconda2\lib\site-packages\notebook\notebookapp.py", line 1296, in initialize
    self.init_webapp()
  File "C:\Users\Dell\Anaconda2\lib\site-packages\notebook\notebookapp.py", line 1120, in init_webapp
    self.http_server.listen(port, self.ip)
  File "C:\Users\Dell\Anaconda2\lib\site-packages\tornado\tcpserver.py", line 143, in listen
    self.add_sockets(sockets)
  File "C:\Users\Dell\Anaconda2\lib\site-packages\tornado\tcpserver.py", line 155, in add_sockets
    self.io_loop = IOLoop.current()
  File "C:\Users\Dell\Anaconda2\lib\site-packages\tornado\ioloop.py", line 214, in current
    return IOLoop.instance()
  File "C:\Users\Dell\Anaconda2\lib\site-packages\tornado\ioloop.py", line 162, in instance
    IOLoop._instance = IOLoop()
  File "C:\Users\Dell\Anaconda2\lib\site-packages\tornado\util.py", line 293, in __new__
    instance.initialize(*args, **init_kwargs)
  File "C:\Users\Dell\Anaconda2\lib\site-packages\zmq\eventloop\ioloop.py", line 139, in initialize
    super(ZMQIOLoop, self).initialize(impl=impl, **kwargs)
  File "C:\Users\Dell\Anaconda2\lib\site-packages\tornado\ioloop.py", line 709, in initialize
    self._waker = Waker()
  File "C:\Users\Dell\Anaconda2\lib\site-packages\tornado\platform\common.py", line 64, in __init__
    self.writer.connect(connect_address)
  File "C:\Users\Dell\Anaconda2\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

C:\Users\Dell>

**Comment by takluyver** [comment]
Don't think I've seen that error before. Do you have any security software on your computer? Some security things seem to interfere with the connections we use.

**Comment by raedbsili1991** [comment]
Hi, 

I am receiving the same error when running Jupyter Notebook, although my firewall is completely deactivated! It was just working fine by yesterday! 
Today, it shows this error!

**Comment by shaad1994** [comment]
how i deactivated windows firewall???
