### ISSUE TITLE
Notebook very slow to open and the lagging

### ISSUE THREAD

**Issue by thHawat** [jupyter/notebook#2261]
Hi, 
I'm on Mac OS X Sierra, and with the last version of Anaconda installed (conda 4.2.13)
When I open a notebook, it takes ages before I can do anything (about 5 minutes)
And then, it lags. 
I've tried several browsers and it doesn't change anything.

My terminal : 

```
[W 21:11:34.024 NotebookApp] Error loading server extension nbpresent
    Traceback (most recent call last):
      File "/Users/Didier/anaconda/lib/python2.7/site-packages/notebook/notebookapp.py", line 1046, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/Didier/anaconda/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/Users/Didier/anaconda/lib/python2.7/site-packages/nbpresent/__init__.py", line 5, in <module>
        from nbconvert.exporters.export import exporter_map
      File "/Users/Didier/anaconda/lib/python2.7/site-packages/nbconvert/__init__.py", line 4, in <module>
        from .exporters import *
      File "/Users/Didier/anaconda/lib/python2.7/site-packages/nbconvert/exporters/__init__.py", line 1, in <module>
        from .export import *
      File "/Users/Didier/anaconda/lib/python2.7/site-packages/nbconvert/exporters/export.py", line 9, in <module>
        import entrypoints
      File "/Users/Didier/anaconda/lib/python2.7/site-packages/entrypoints.py", line 16, in <module>
        from backports import configparser
    ImportError: cannot import name configparser
[I 21:11:34.034 NotebookApp] [nb_conda] enabled
[I 21:11:34.160 NotebookApp] [nb_anacondacloud] enabled
[I 21:11:34.165 NotebookApp] Serving notebooks from local directory: /Users/Didier
[I 21:11:34.165 NotebookApp] 0 active kernels 
[I 21:11:34.165 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 21:11:34.165 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 21:12:50.915 NotebookApp] Kernel started: 376ecfba-d51c-4a7b-b860-61d27180a946
[I 21:16:49.707 NotebookApp] Kernel started: 6d051a31-e6b5-4101-8f60-4c5443ee2351
[W 21:17:39.265 NotebookApp] WebSocket ping timeout after 107237 ms.
[W 21:20:21.463 NotebookApp] Could not import nbconvert: cannot import name configparser
[E 21:20:21.465 NotebookApp] {
      "Accept-Language": "fr-ch", 
      "Accept-Encoding": "gzip, deflate", 
      "Host": "localhost:8888", 
      "Accept": "*/*", 
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/602.3.12 (KHTML, like Gecko) Version/10.0.2 Safari/602.3.12", 
      "Connection": "keep-alive", 
      "X-Requested-With": "XMLHttpRequest", 
      "Referer": "http://localhost:8888/notebooks/Google%20Drive/Private/08.%20Telecom%20Paris%20Tech/Projet/170216-MR-TA-Machine-Learning-VBELN_Level-Copy1.ipynb", 
      "Cookie": "_xsrf=2|0a655c0e|d8da843b8de40c1e1e30de036caff0ea|1488220533; username-localhost-8888=\"2|1:0|10:1488220533|23:username-localhost-8888|44:ODBkOWE3ZTY2MzUxNDZjNjk2MDFhZjlmNTY3YjBhMmY=|5a5a6f93a1a593cb5a8fe5ad169193cbda0ea50aed04fd500cfe21bbe0c58db8\""
    }
[E 21:20:21.465 NotebookApp] 500 GET /api/nbconvert (::1) 33.23ms referer=http://localhost:8888/notebooks/Google%20Drive/Private/08.%20Telecom%20Paris%20Tech/Projet/170216-MR-TA-Machine-Learning-VBELN_Level-Copy1.ipynb
[W 21:21:28.427 NotebookApp] 404 GET /apple-touch-icon-precomposed.png (::1) 28.77ms referer=None
[W 21:21:28.434 NotebookApp] 404 GET /apple-touch-icon.png (::1) 1.31ms referer=None
[W 21:21:28.536 NotebookApp] 404 GET /apple-touch-icon-precomposed.png (::1) 4.02ms referer=None
[W 21:21:28.540 NotebookApp] 404 GET /apple-touch-icon.png (::1) 2.52ms referer=None
[W 21:22:03.425 NotebookApp] WebSocket ping timeout after 102422 ms.
[W 21:22:06.414 NotebookApp] Could not import nbconvert: cannot import name configparser
[E 21:22:06.415 NotebookApp] {
      "Accept-Language": "fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4", 
      "Accept-Encoding": "gzip, deflate, sdch, br", 
      "X-Requested-With": "XMLHttpRequest", 
      "Host": "localhost:8888", 
      "Accept": "*/*", 
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36", 
      "Connection": "keep-alive", 
      "Referer": "http://localhost:8888/notebooks/Google%20Drive/Private/08.%20Telecom%20Paris%20Tech/Projet/170216-MR-TA-Machine-Learning-VBELN_Level.ipynb", 
      "Cookie": "_xsrf=2|fe45146f|b658b2f4f05a8e8f7ea6b9d8d2d937fb|1488104181; username-localhost-8888=\"2|1:0|10:1488221892|23:username-localhost-8888|44:OTU3OWJiYTBmZGVjNDg5ODljNDkzODAyYzEyMDNiMWQ=|2f1775de1d0e98023bf1d5bc3b4520c5a4402b2cb4b24f4725386415fd6764b4\""
    }
[E 21:22:06.415 NotebookApp] 500 GET /api/nbconvert (::1) 5.38ms referer=http://localhost:8888/notebooks/Google%20Drive/Private/08.%20Telecom%20Paris%20Tech/Projet/170216-MR-TA-Machine-Learning-VBELN_Level.ipynb
```

I thank you very warmly in advance for your help

Thufir

**Comment by ezietsman** [comment]
I'm having this issue too.

**Comment by Niwroc** [comment]
I am also on Mac OS X Sierra and having the same issue. It was working fine until this week.

**Comment by ezietsman** [comment]
OK the answer is actually that something in ipython 6 and jedi-completion doesn't work well together. The workaround is to disable the jedi autocompleter.

**Comment by Niwroc** [comment]
Turns out I had a lot of really large print statements in my jupyter notebook cell outputs and that seemed to slow down the kernel considerably. Jupyter has been a lot faster since I have been more careful about managing cell outputs.

**Comment by julienbelan** [comment]
Having it too.

**Comment by louis925** [comment]
Same on Windows 7 with opera.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
