### ISSUE TITLE
Suddenly unable to launch jupyter notebook 

### ISSUE THREAD

**Issue by mayurisrao** [jupyter/notebook#2270]
Hello, 
I have been using jupyter notebook with Canopy. Without having made any changes or updates my jupyter notebook suddenly stopped working one day! While I have the canopy application open I launch jupyter from my command line by running the command `jupyter-notebook`.
This launches the notebook on my browser. However jupyter no longer launches and I get the following error on my command line instead. I use a mac with mountain-lion os. I have tried removing and re-installing jupyter from canopy and with pip, no use.
Help and thanks! 

```
Traceback (most recent call last):
  File "/Users/mayuri/Library/Enthought/Canopy_64bit/User/bin/jupyter-notebook", line 8, in <module>
    from notebook.notebookapp import main
  File "/Users/mayuri/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/Users/mayuri/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/notebook/nbextensions.py", line 27, in <module>
    from ipython_genutils.path import ensure_dir_exists
  File "/Users/mayuri/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/ipython_genutils/path.py", line 13, in <module>
    import random
  File "/Users/mayuri/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/random/__init__.py", line 99, in <module>
    from .mtrand import *
  File "numpy.pxd", line 92, in init mtrand (numpy/random/mtrand/mtrand.c:41017)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/__init__.py", line 46, in <module>
    from numpy.testing import Tester
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/testing/__init__.py", line 13, in <module>
    from .utils import *
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/testing/utils.py", line 15, in <module>
    from tempfile import mkdtemp
  File "/Applications/Canopy.app/appdata/canopy-1.6.1.3253.macosx-x86_64/Canopy.app/Contents/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
ImportError: cannot import name Random
```

**Comment by takluyver** [comment]
Have you made a file called `random.py`? If so, it's finding that instead of the normal Python `random` module.

**Comment by takluyver** [comment]
Closing because I suspect there's nothing we can do here.

**Comment by mayurisrao** [comment]
Hello!
Sorry for the extremely late reply! No, I don't have a random.py file on my computer!

**Comment by takluyver** [comment]
Can you, from the same terminal where launching the notebook fails, run `python -c "import random; print(random)"`? You may have multiple Python installations; if so, try to ensure that the Python you run for this is the same as the one launching the notebook.

**Comment by mayurisrao** [comment]
Hello,
 when I run the command you suggested, I get the same error as when I run Jupyter Notebook. The output is give below.
`python -c "import random; print(random)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mayuri/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy/random/__init__.py", line 99, in <module>
    from .mtrand import *
  File "numpy.pxd", line 92, in init mtrand (numpy/random/mtrand/mtrand.c:41017)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/__init__.py", line 170, in <module>
    from . import add_newdocs
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/core/__init__.py", line 46, in <module>
    from numpy.testing import Tester
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/testing/__init__.py", line 13, in <module>
    from .utils import *
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy/testing/utils.py", line 15, in <module>
    from tempfile import mkdtemp
  File "/Applications/Canopy.app/appdata/canopy-1.6.1.3253.macosx-x86_64/Canopy.app/Contents/lib/python2.7/tempfile.py", line 35, in <module>
    from random import Random as _Random
ImportError: cannot import name Random`

**Comment by takluyver** [comment]
Are you trying to start it from inside the numpy source directory? What do `pwd` and `ls` show you?

**Comment by mayurisrao** [comment]
Could you clarify by what you mean? I usually just launch Jupyter Notebook from my terminal, from any directory. In this case I just tried running it from the home directory. I ran the `python -c "import random; print(random)"` from home directory as well. Was I supposed to run `"import random; print(random)"` from within python?
To see which python is being used, I ran `which python` and this showed `/Users/mayuri/Library/Enthought/Canopy_64bit/User/bin/python`

**Comment by takluyver** [comment]
It appears to be trying to load `numpy.random` as `random`. Have you set the `PYTHONPATH` environment variable, perhaps?

**Comment by mayurisrao** [comment]
This is my `PYTHONPATH`. Should I modify it?
`echo $PYTHONPATH`
`:/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages:/Users/mayuri/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/numpy`

**Comment by takluyver** [comment]
The last bit is the problem. You don't put packages themselves on PYTHONPATH, you put the directories that contain them, i.e. `site-packages`. And most of the time, it's not necessary to set it at all.

**Comment by mayurisrao** [comment]
It worked!! Thank you very much! I am now able launch jupyter-notebook with `PYTHONPATH` set as 
`export PYTHONPATH=$PYTHONPATH:/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages:/Users/mayuri/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/`

Thanks very much!!!

**Comment by takluyver** [comment]
:-)
