### ISSUE TITLE
Trying to start Jupyter notebook

### ISSUE THREAD

**Issue by Jstuff36** [jupyter/notebook#2317]
Hello,
I am trying to start a jupyter notebook, but it keeps failing with the following error.

```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/usr/local/lib/python2.7/site-packages/notebook/notebookapp.py", line 63, in <module>
    from .services.contents.manager import ContentsManager
  File "/usr/local/lib/python2.7/site-packages/notebook/services/contents/manager.py", line 16, in <module>
    from nbformat import sign, validate, ValidationError
  File "/usr/local/lib/python2.7/site-packages/nbformat/sign.py", line 25, in <module>
    from traitlets import (
ImportError: cannot import name default
```

**Comment by takluyver** [comment]
That looks like it's finding an older version of the `traitlets` package. Try uninstalling and reinstalling that using whichever mechanism you used to install the notebook.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!
