### ISSUE TITLE
GH master fails at `js css` rebuild

### ISSUE THREAD

**Issue by michaelaye** [jupyter/notebook#2343]
System:
macOS 10.12.3, python 3.6 using conda, npm/node via homebrew

```bash
> jupyter-notebook-deps@4.0.0 build /Users/klay6683/Dropbox/src/notebook
> python setup.py js css

running js
running jsdeps
bower dependencies up to date
/Users/klay6683/Dropbox/src/notebook/notebook/static/tree/js/main.min.js up to date
/Users/klay6683/Dropbox/src/notebook/notebook/static/auth/js/main.min.js up to date
/Users/klay6683/Dropbox/src/notebook/notebook/static/terminal/js/main.min.js up to date
/Users/klay6683/Dropbox/src/notebook/notebook/static/edit/js/main.min.js up to date
/Users/klay6683/Dropbox/src/notebook/notebook/static/notebook/js/main.min.js up to date
running css
> lessc --source-map --include-path=/Users/klay6683/Dropbox/src/notebook/notebook/static /Users/klay6683/Dropbox/src/notebook/notebook/static/style/ipython.less /Users/klay6683/Dropbox/src/notebook/notebook/static/style/ipython.min.css
module.js:472
    throw err;
    ^

Error: Cannot find module '../lib/less-node/fs'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/klay6683/Dropbox/src/notebook/node_modules/.bin/lessc:4:10)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
Traceback (most recent call last):
  File "setup.py", line 199, in <module>
    main()
  File "setup.py", line 196, in main
    setup(**setup_args)
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/Users/klay6683/Dropbox/src/notebook/setupbase.py", line 440, in run
    ], cwd=repo_root, env=env)
  File "/Users/klay6683/Dropbox/src/notebook/setupbase.py", line 332, in run
    return check_call(cmd, *args, **kwargs)
  File "/Users/klay6683/miniconda3/envs/stable/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['lessc', '--source-map', '--include-path=/Users/klay6683/Dropbox/src/notebook/notebook/static', '/Users/klay6683/Dropbox/src/notebook/notebook/static/style/ipython.less', '/Users/klay6683/Dropbox/src/notebook/notebook/static/style/ipython.min.css']' returned non-zero exit status 1.

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.7.4/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.7.4
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! jupyter-notebook-deps@4.0.0 build: `python setup.py js css`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the jupyter-notebook-deps@4.0.0 build script 'python setup.py js css'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jupyter-notebook-deps package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     python setup.py js css
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jupyter-notebook-deps
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jupyter-notebook-deps
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/klay6683/Dropbox/src/notebook/npm-debug.log
```

**Comment by minrk** [comment]
Try starting fresh:

    git clean -xfd # deletes all untracked files
    python setup.py js css

This worked for me with the same setup you describe.

**Comment by gnestor** [comment]
@michaelaye Let us know if that resolves it for you 👍

**Comment by michaelaye** [comment]
yep, that does it. Sorry for not reading `CONTRIBUTING.rst` properly, but for what it's worth: I'm usually efficient in scraping websites by eye, and the sentence "Don't forget to run npm run build after switching branches" made me ignore the rest of the paragraph, as I wasn't switching branches, but in there's the tip with `git clean -xfd`.
