### ISSUE TITLE
Can't get jupter to start

### ISSUE THREAD

**Issue by Daenerys24** [jupyter/notebook#2344]
```
Traceback (most recent call last):
  File "/usr/bin/jupyter-notebook", line 3, in <module>
    from notebook.notebookapp import main
  File "/usr/lib/python3.6/site-packages/notebook/notebookapp.py", line 61, in <module>
    from .services.kernels.kernelmanager import MappingKernelManager
  File "/usr/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 16, in <module>
    from jupyter_client.multikernelmanager import MultiKernelManager
  File "/usr/lib/python3.6/site-packages/jupyter_client/__init__.py", line 7, in <module>
    from .manager import KernelManager, run_kernel
  File "/usr/lib/python3.6/site-packages/jupyter_client/manager.py", line 32, in <module>
    from .session import Session
  File "/usr/lib/python3.6/site-packages/jupyter_client/session.py", line 61, in <module>
    from jupyter_client.jsonutil import extract_dates, squash_dates, date_default
  File "/usr/lib/python3.6/site-packages/jupyter_client/jsonutil.py", line 11, in <module>
    from dateutil.parser import parse as _dateutil_parse
  File "/usr/lib/python3.6/site-packages/dateutil/parser.py", line 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntax

I tried uninstalling and reinstalling

**Comment by minrk** [comment]
What's `pip list`? Specifically `python-dateutil`?

Also make sure you are using pip >= 9.

**Comment by denisov-vlad** [comment]
I have the same issue:

Python v3.6, python-dateutil (1.5)

**Comment by takluyver** [comment]
Dateutil 1.5 is for Python 2. Update it to a later version.

**Comment by takluyver** [comment]
I'm marking this as no-action because I don't believe it's a bug in our code, but if you're getting python-dateutil 1.5 installed on Python 3, there is probably a problem with dependencies or packaging of something. Do you know what installation and setup steps you did that resulted in that state? If we have a way to reproduce it, we can start to figure out what is at fault for getting you an old version of the package.

**Comment by denisov-vlad** [comment]
I don't know how this happened.

My common python's version is 2.7. So I've installed python3 via brew and then installed jupyter via pip3 and now i see this error.

p.s. I've updated python-dateutil and it's ok now.

**Comment by AlexandruGH** [comment]
Greetings I had the same issue and I solve it like the others specify, by upgrading the python-dateutil:

`sudo -H pip install python-dateutil --upgrade`

**Comment by RachelShalom** [comment]
Thank you! I had the same problem and upgrading dateutil solved the issue

**Comment by f29825604** [comment]
Thank you! I had the same problem and upgrading dateutil solved the issue

**Comment by yushunchang** [comment]
Thank you！Solve it！

**Comment by ismet-dagli** [comment]
> Greetings I had the same issue and I solve it like the others specify, by upgrading the python-dateutil:
> 
> `sudo -H pip install python-dateutil --upgrade`

it upgraded but I take the same error again :/

**Comment by gasparramoa** [comment]
Try to remove python-dateutil first using the command: ``` pip3 uninstall python-dateutil ```
After that install the last version by doing: ``` pip3 install python-dateutil ``` 
Check the version of python-dateutil (2.8.1  at least) using the command: ``` pip3 list ```
It should work now.

**Comment by Shivdutta** [comment]
Thank you! I had the same problem and upgrading dateutil solved the issue

**Comment by Mazata** [comment]
It worked for me too, thanks!
In my case, dateutil had been "retrograded" to 1.5 when I installed heroku 0.1.4 as it is not compatible with newer versions of dateutil. Maybe that information can help someone else

**Comment by leozimshw** [comment]
> Try to remove python-dateutil first using the command: `pip3 uninstall python-dateutil`
> After that install the last version by doing: `pip3 install python-dateutil`
> Check the version of python-dateutil (2.8.1 at least) using the command: `pip3 list`
> It should work now.

when i type pip3 list i cant find de dateutil there but it says that is already installed

**Comment by nmcodazen** [comment]
> It worked for me too, thanks!
> In my case, dateutil had been "retrograded" to 1.5 when I installed heroku 0.1.4 as it is not compatible with newer versions of dateutil. Maybe that information can help someone else

I think I fell in the same boat as you.  Also with heroku, and also this solution worked out.

**Comment by Jay-523** [comment]
> > Greetings I had the same issue and I solve it like the others specify, by upgrading the python-dateutil:
> > `sudo -H pip install python-dateutil --upgrade`
> 
> it upgraded but I take the same error again :/

Had the same issue, it worked :D

**Comment by moseti1** [comment]
I just did `pip3 uninstall python-dateutil` and run `jupyter-lab` and it worked.

**Comment by Erica-Ko** [comment]
Having the same issue:
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/jupyter", line 7, in <module>
    from jupyter_core.command import main
  File "/home/ubuntu/.local/lib/python3.5/site-packages/jupyter_core/__init__.py", line 1, in <module>
    from .version import version_info, __version__
  File "/home/ubuntu/.local/lib/python3.5/site-packages/jupyter_core/version.py", line 21
    _suffix_ = f'.dev{version_info.serial}'
                                          ^
SyntaxError: invalid syntax

Python version: Python 3.6.5 :: Anaconda, Inc.
python-dateutil (2.8.1)

How to solve it? I have spent a lot of time on solving it. Thanks

**Comment by kevin-bates** [comment]
Hi @Erica-Ko - this is actually a different issue and, for now, unrelated to dateutil.  

You have what appears to be a dev version of `jupyter_core` `4.7` - which doesn't support Python 3.5 running within Python 3.5.  Since it looks like you expect to be using Anaconda with python 3.6, perhaps you haven't activated the appropriate conda environment?

The other option would be to stick with 3.5 and downgrade `jupyter_core` to `4.6.3`.

**Comment by Erica-Ko** [comment]
@kevin-bates Thank you for your help : ) That's true that I haven't activated the appropriate conda environment because there is something incorrect in my /.bashrc file. I fixed it and it works.

**Comment by valerie-pietrasz** [comment]
If anyone else runs into this issue: I had this problem as well (also because of a heroku install), but uninstalling and reinstalling python-dateutil didn't work. In my case I needed to uninstall & reinstall jupyter to force dateutil to upgrade.

**Comment by cyrus305** [comment]
> Greetings I had the same issue and I solve it like the others specify, by upgrading the python-dateutil:
> 
> `sudo -H pip install python-dateutil --upgrade`

This solution worked for me. Thanks @moseti1

**Comment by cyrus305** [comment]
> Greetings I had the same issue and I solve it like the others specify, by upgrading the python-dateutil:
> 
> `sudo -H pip install python-dateutil --upgrade`

This solution worked for me. Thanks @AlexandruGH

**Comment by Mars824** [comment]
Stop emailing me!

**Comment by Viyouthan** [comment]
> ```
> Traceback (most recent call last):
>   File "/usr/bin/jupyter-notebook", line 3, in <module>
>     from notebook.notebookapp import main
>   File "/usr/lib/python3.6/site-packages/notebook/notebookapp.py", line 61, in <module>
>     from .services.kernels.kernelmanager import MappingKernelManager
>   File "/usr/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 16, in <module>
>     from jupyter_client.multikernelmanager import MultiKernelManager
>   File "/usr/lib/python3.6/site-packages/jupyter_client/__init__.py", line 7, in <module>
>     from .manager import KernelManager, run_kernel
>   File "/usr/lib/python3.6/site-packages/jupyter_client/manager.py", line 32, in <module>
>     from .session import Session
>   File "/usr/lib/python3.6/site-packages/jupyter_client/session.py", line 61, in <module>
>     from jupyter_client.jsonutil import extract_dates, squash_dates, date_default
>   File "/usr/lib/python3.6/site-packages/jupyter_client/jsonutil.py", line 11, in <module>
>     from dateutil.parser import parse as _dateutil_parse
>   File "/usr/lib/python3.6/site-packages/dateutil/parser.py", line 158
>     l.append("%s=%s" % (attr, `value`))
>                               ^
> SyntaxError: invalid syntax
> 
> I tried uninstalling and reinstalling
> ```

Traceback (most recent call last):
  File "D:\Anaconda3\envs\TF_AnoGAN\Scripts\jupyter-notebook-script.py", line 5, in <module>
    from notebook.notebookapp import main
  File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\notebook\notebookapp.py", line 80, in <module>
    from .services.contents.manager import ContentsManager
  File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\notebook\services\contents\manager.py", line 17, in <module>
    from nbformat import sign, validate as validate_nb, ValidationError
  File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\nbformat\__init__.py", line 11, in <module>
    from . import v1, v2, v3, v4
  File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\nbformat\v4\__init__.py", line 23, in <module>
    from .convert import downgrade, upgrade
  File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\nbformat\v4\convert.py", line 11, in <module>
    from nbformat import v3, validator
  File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\nbformat\validator.py", line 16, in <module>
    from .json_compat import ValidationError, _validator_for_name, get_current_validator
  File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\nbformat\json_compat.py", line 11, in <module>
    import jsonschema
  File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\jsonschema\__init__.py", line 13, in <module>
    from jsonschema._format import FormatChecker
  File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\jsonschema\_format.py", line 411, in <module>
    from webcolors import CSS21_NAMES_TO_HEX
  File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\webcolors\__init__.py", line 12, in <module>
    from ._conversion import (
  File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\webcolors\_conversion.py", line 49
    if hex_value := color_map.get(name.lower()):
                  ^
SyntaxError: invalid syntax
I have the similar problem，how to solve it ?

**Comment by NJB1995** [comment]
> > ```
> > Traceback (most recent call last):
> >   File "/usr/bin/jupyter-notebook", line 3, in <module>
> >     from notebook.notebookapp import main
> >   File "/usr/lib/python3.6/site-packages/notebook/notebookapp.py", line 61, in <module>
> >     from .services.kernels.kernelmanager import MappingKernelManager
> >   File "/usr/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 16, in <module>
> >     from jupyter_client.multikernelmanager import MultiKernelManager
> >   File "/usr/lib/python3.6/site-packages/jupyter_client/__init__.py", line 7, in <module>
> >     from .manager import KernelManager, run_kernel
> >   File "/usr/lib/python3.6/site-packages/jupyter_client/manager.py", line 32, in <module>
> >     from .session import Session
> >   File "/usr/lib/python3.6/site-packages/jupyter_client/session.py", line 61, in <module>
> >     from jupyter_client.jsonutil import extract_dates, squash_dates, date_default
> >   File "/usr/lib/python3.6/site-packages/jupyter_client/jsonutil.py", line 11, in <module>
> >     from dateutil.parser import parse as _dateutil_parse
> >   File "/usr/lib/python3.6/site-packages/dateutil/parser.py", line 158
> >     l.append("%s=%s" % (attr, `value`))
> >                               ^
> > SyntaxError: invalid syntax
> > 
> > I tried uninstalling and reinstalling
> > ```
> 
> Traceback (most recent call last): File "D:\Anaconda3\envs\TF_AnoGAN\Scripts\jupyter-notebook-script.py", line 5, in from notebook.notebookapp import main File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\notebook\notebookapp.py", line 80, in from .services.contents.manager import ContentsManager File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\notebook\services\contents\manager.py", line 17, in from nbformat import sign, validate as validate_nb, ValidationError File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\nbformat__init__.py", line 11, in from . import v1, v2, v3, v4 File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\nbformat\v4__init__.py", line 23, in from .convert import downgrade, upgrade File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\nbformat\v4\convert.py", line 11, in from nbformat import v3, validator File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\nbformat\validator.py", line 16, in from .json_compat import ValidationError, _validator_for_name, get_current_validator File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\nbformat\json_compat.py", line 11, in import jsonschema File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\jsonschema__init__.py", line 13, in from jsonschema._format import FormatChecker File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\jsonschema_format.py", line 411, in from webcolors import CSS21_NAMES_TO_HEX File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\webcolors__init__.py", line 12, in from ._conversion import ( File "D:\Anaconda3\envs\TF_AnoGAN\lib\site-packages\webcolors_conversion.py", line 49 if hex_value := color_map.get(name.lower()): ^ SyntaxError: invalid syntax I have the similar problem，how to solve it ?



Also having this issue!
