### ISSUE TITLE
notebook meets some issues working with tornado 4.5

### ISSUE THREAD

**Issue by timeregained** [jupyter/notebook#2417]
I am using Jupyter notebook 5.0.0 anaconda package in Windows 10 1703 64bit.

When I updated tornado from 4.4.2  to 4.5, I found there is some conflicts with jupyter notebook and caused notebook not working.

The traceback message is as below:

"
Traceback (most recent call last):
  File "D:\Apps\x64\Continuum\Miniconda3\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'log'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Apps\x64\Continuum\Miniconda3\Scripts\jupyter-notebook-script.py", line 5, in <module>
    sys.exit(notebook.notebookapp.main())
  File "D:\Apps\x64\Continuum\Miniconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "D:\Apps\x64\Continuum\Miniconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "D:\Apps\x64\Continuum\Miniconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "D:\Apps\x64\Continuum\Miniconda3\lib\site-packages\notebook\notebookapp.py", line 1290, in initialize
    super(NotebookApp, self).initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "D:\Apps\x64\Continuum\Miniconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "D:\Apps\x64\Continuum\Miniconda3\lib\site-packages\jupyter_core\application.py", line 239, in initialize
    self.parse_command_line(argv)
  File "D:\Apps\x64\Continuum\Miniconda3\lib\site-packages\notebook\notebookapp.py", line 1007, in parse_command_line
    super(NotebookApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "D:\Apps\x64\Continuum\Miniconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "D:\Apps\x64\Continuum\Miniconda3\lib\site-packages\traitlets\config\application.py", line 536, in parse_command_line
    flags=flags, log=self.log)
  File "D:\Apps\x64\Continuum\Miniconda3\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "D:\Apps\x64\Continuum\Miniconda3\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "D:\Apps\x64\Continuum\Miniconda3\lib\site-packages\traitlets\config\application.py", line 226, in _log_default
    _log_formatter = self._log_formatter_cls(fmt=self.log_format, datefmt=self.log_datefmt)
  File "D:\Apps\x64\Continuum\Miniconda3\lib\site-packages\tornado\log.py", line 154, in __init__
    raise RuntimeError("No supported color terminal library")
RuntimeError: No supported color terminal library
"

When I downgrade tornado to 4.4.2 , the notebook came back to be working.

**Comment by takluyver** [comment]
This may be a bug in tornado. Does `import colorama` succeed?

**Comment by timeregained** [comment]
Just tested , import colorama succeed with tornado 4.5. But Jupyter notebook still failed on startup.

**Comment by chdoig** [comment]
This is a known issue in tornado:

https://github.com/tornadoweb/tornado/issues/2015

**Comment by EvanOman** [comment]
I think my Issue # 2015 there is not related to this bug (bad python on my end)

[This issue](https://github.com/tornadoweb/tornado/issues/2013) is however related, fix is in the works

**Comment by bdarnell** [comment]
There's a fix for this in the master branch of https://github.com/tornadoweb/tornado; I'm planning to release it as Tornado 4.5.1 tomorrow.

**Comment by RRosio** [comment]
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed here. Thank you!
