### ISSUE TITLE
No module named shutil_get_terminal_size

### ISSUE THREAD

**Issue by shugert** [jupyter/notebook#2537]
Jupyter Notebook was working fine for the past 10 months without a problem, suddenly today, after I installed Graphlab Create it stopped working. Every time I launch a notebook I get a dead kernel and after it tries to reinitiate 5 times unsuccessfully I get this message:

```
WARNING:root:kernel 533f52df-2352-4b32-98c3-14fa0fcdb44e restarted
Traceback (most recent call last):
  File "/Users/Shugert/anaconda/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/Users/Shugert/anaconda/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/Users/Shugert/anaconda/lib/python2.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/Users/Shugert/anaconda/lib/python2.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/Users/Shugert/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/Users/Shugert/anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/Users/Shugert/anaconda/lib/python2.7/site-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/Users/Shugert/anaconda/lib/python2.7/site-packages/IPython/core/ultratb.py", line 128, in <module>
    from IPython.utils.terminal import get_terminal_size
  File "/Users/Shugert/anaconda/lib/python2.7/site-packages/IPython/utils/terminal.py", line 22, in <module>
    from backports.shutil_get_terminal_size import get_terminal_size as _get_terminal_size
ImportError: No module named shutil_get_terminal_size
```
I am in the middle of final deliveries for my master, so any advice will be really appreciated.

**Comment by takluyver** [comment]
As luck would have it, we've just released IPython 5.4 with a workaround for that issue. So the advice is: upgrade!

The underlying cause is some issue with Python namespace packages, possibly related to `backports.configparser`. We haven't had much luck with finding a proper fix.

**Comment by shugert** [comment]
Thanks @takluyver 

I did upgrade it yesterday but did not solved the issue, and yes it was something related to back ports.configpareser, as matter of fact I was able to fix it with this:

conda config --add channels conda-forge
conda install backports.shutil_get_terminal_size

Thanks!

**Comment by takluyver** [comment]
We may actually have made a release since you upgraded, depending on what time things happened. The latest for Python 2.7 is IPython 5.4.1.

Closing since you've got it working.
