### ISSUE TITLE
centos6.8 Unhandled error in API request

### ISSUE THREAD

**Issue by juntaozhang** [jupyter/notebook#2578]
env:
```
[xipudata@bigdata-cdh03 test]$ cat /etc/redhat-release
CentOS release 6.8 (Final)
[xipudata@bigdata-cdh03 test]$ python -V
Python 2.7.13
[xipudata@bigdata-cdh03 test]$ python -c 'import IPython; print(IPython.sys_info())'
{'commit_hash': u'8b0eef4',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python2.7/site-packages/IPython',
 'ipython_version': '3.2.0',
 'os_name': 'posix',
 'platform': 'Linux-2.6.32-642.3.1.el6.x86_64-x86_64-with-centos-6.8-Final',
 'sys_executable': '/usr/local/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.13 (default, Jun  6 2017, 09:48:51) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]'}
```

```
[xipudata@bigdata-cdh03 test]$ cat hello.ipynb
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": [
    "# -*- coding: UTF-8 -*-\n",
    "def hello(name) :\n",
    "    return \"hello \"+name\n",
    "def hi():\n",
    "    print hello(\"juntao\")\n",
    "hi()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 2",
   "language": "python",
   "name": "python2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
[xipudata@bigdata-cdh03 test]$
```

`ipython notebook --no-browser --port=18888 --ip=0.0.0.0 --debug` when i open `http://bigdata-cdh03.xipudata.com:18888/notebooks/hello.ipynb` in the browser, some error happens:

```
[W 15:36:41.054 NotebookApp] Notebook hello.ipynb is not trusted
[D 15:36:41.058 NotebookApp] 200 GET /api/contents/hello.ipynb?type=notebook&_=1497425774232 (192.168.3.17) 52.79ms
[D 15:36:41.144 NotebookApp] Connecting to: tcp://127.0.0.1:44224
[I 15:36:41.144 NotebookApp] Kernel started: c4d7cd87-85b1-49e7-9805-184ab5babdde
[D 15:36:41.144 NotebookApp] Kernel args: {'cwd': u'/home/xipudata/test'}
[E 15:36:41.145 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/IPython/html/base/handlers.py", line 394, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/usr/local/lib/python2.7/site-packages/IPython/html/services/sessions/handlers.py", line 53, in post
        model = sm.create_session(path=path, kernel_name=kernel_name)
      File "/usr/local/lib/python2.7/site-packages/IPython/html/services/sessions/sessionmanager.py", line 68, in create_session
        kernel_id=kernel_id)
      File "/usr/local/lib/python2.7/site-packages/IPython/html/services/sessions/sessionmanager.py", line 94, in save_session
        return self.get_session(session_id=session_id)
      File "/usr/local/lib/python2.7/site-packages/IPython/html/services/sessions/sessionmanager.py", line 125, in get_session
        self.cursor.execute(query, list(kwargs.values()))
    "OperationalError: Could not decode to UTF-8 column 'kernel_id' with text '\xfd\x80\x81\xa3\xfd\xb0\x81\xa4\xf9\x80\x81\xa3\xfd\xb0\x80\xb8\xfe\x80\x80\xad\xf8\xa0\x80\xb5\xfb\x90\x80\xb1\xfe\x90\x80\xb4\xfd\xb0\x81\xa5\xfe\x90\x80\xad\xfc\x80\x80\xb8\xfb\x90\x80\xb5\xfe\x80\x80\xb1\xf8\x90\x80\xb4\xfd\x90\x81\xa2\xf8\x90\x81\xa2\xf9\x80\x81\xa2\xf9\x90\x81\xa4'"
[E 15:36:41.146 NotebookApp] Uncaught exception POST /api/sessions (192.168.3.17)
    HTTPServerRequest(protocol='http', host='bigdata-cdh03.xipudata.com:18888', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='192.168.3.17', headers={'Origin': 'http://bigdata-cdh03.xipudata.com:18888', 'Content-Length': '73', 'Accept-Language': 'en-US,en;q=0.8,zh;q=0.6', 'Accept-Encoding': 'gzip, deflate', 'Host': 'bigdata-cdh03.xipudata.com:18888', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://bigdata-cdh03.xipudata.com:18888/notebooks/hello.ipynb', 'Cookie': '_ga=GA1.2.534299577.1492671455; _xsrf=2|974ac16c|7a2dbd8b1b63effeaf48e1d7701e3901|1497410688', 'Content-Type': 'application/json'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1415, in _execute
        result = yield result
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 230, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python2.7/site-packages/IPython/html/base/handlers.py", line 412, in wrapper
        self.finish(json.dumps(reply))
      File "/usr/local/lib/python2.7/json/__init__.py", line 244, in dumps
        return _default_encoder.encode(obj)
      File "/usr/local/lib/python2.7/json/encoder.py", line 207, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/usr/local/lib/python2.7/json/encoder.py", line 270, in iterencode
        return _iterencode(o, 0)
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xfd in position 952: invalid start byte
[D 15:36:41.146 NotebookApp] Using contents: services/contents
[D 15:36:41.147 NotebookApp] No template for 500
[D 15:36:41.147 NotebookApp] Using contents: services/contents
[E 15:36:41.150 NotebookApp] {
      "Origin": "http://bigdata-cdh03.xipudata.com:18888",
      "Content-Length": "73",
      "Accept-Language": "en-US,en;q=0.8,zh;q=0.6",
      "Accept-Encoding": "gzip, deflate",
      "Connection": "keep-alive",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36",
      "Host": "bigdata-cdh03.xipudata.com:18888",
      "X-Requested-With": "XMLHttpRequest",
      "Cookie": "_ga=GA1.2.534299577.1492671455; _xsrf=2|974ac16c|7a2dbd8b1b63effeaf48e1d7701e3901|1497410688",
      "Referer": "http://bigdata-cdh03.xipudata.com:18888/notebooks/hello.ipynb",
      "Content-Type": "application/json"
    }
[E 15:36:41.150 NotebookApp] 500 POST /api/sessions (192.168.3.17) 23.71ms referer=http://bigdata-cdh03.xipudata.com:18888/notebooks/hello.ipynb
[D 15:36:41.151 NotebookApp] Serving kernel resource from: /usr/local/lib/python2.7/site-packages/IPython/kernel/resources
[D 15:36:41.151 NotebookApp] 304 GET /kernelspecs/python2/logo-64x64.png (192.168.3.17) 0.77ms
[D 15:36:41.152 NotebookApp] 200 GET /api/contents/hello.ipynb/checkpoints?_=1497425774233 (192.168.3.17) 0.84ms
^C[I 15:38:29.693 NotebookApp] interrupted
Serving notebooks from local directory: /home/xipudata/test
1 active kernels
The IPython Notebook is running at: http://0.0.0.0:18888/
Shutdown this notebook server (y/[n])? Y
[C 15:38:31.483 NotebookApp] Shutdown confirmed
[I 15:38:31.484 NotebookApp] Shutting down kernels
[I 15:38:31.886 NotebookApp] Kernel shutdown: c4d7cd87-85b1-49e7-9805-184ab5babdde
```

and there are some unread files like this:
```
[xipudata@bigdata-cdh03 test]$ ll
total 16
-rw-r--r-- 1 xipudata xipudata 7168 Jun 14 15:38 ??????????????????????????????????????????????????????????????????????????????????????????????????????
-rw-r--r-- 1 xipudata xipudata 4096 Jun 14 15:36 ??????????????????????????????????????????????????????????????????????????????????????????????????????????????????????????
-rw-rw-r-- 1 xipudata xipudata  481 Jun 14 14:04 hello.ipynb
```

**Comment by juntaozhang** [comment]
also in jupyter
```
[xipudata@bigdata-cdh03 test]$ pip list|grep jupyter
jupyter (1.0.0)
jupyter-client (5.0.1)
jupyter-console (5.1.0)
jupyter-core (4.3.0)
```

`[xipudata@bigdata-cdh03 test]$ jupyter notebook --no-browser --port=18888 --ip=0.0.0.0 --debug`

```
[D 15:47:47.023 NotebookApp] Kernel args: {'kernel_name': u'python2', 'cwd': u'/home/xipudata/test'}
[E 15:47:47.023 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/notebook/base/handlers.py", line 516, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 75, in post
        type=mtype))
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 879, in run
        yielded = self.gen.send(value)
      File "/usr/local/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 81, in create_session
        self.save_session(session_id, path=path, name=name, type=type, kernel_id=kernel_id)
      File "/usr/local/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 125, in save_session
        return self.get_session(session_id=session_id)
      File "/usr/local/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 156, in get_session
        self.cursor.execute(query, list(kwargs.values()))
    "OperationalError: Could not decode to UTF-8 column 'kernel_id' with text '\xf8\x90\x81\xa5\xfd\x90\x81\xa5\xfc\xa0\x80\xb4\xfe\x90\x80\xb8\xf8\x90\x80\xad\xf9\x90\x81\xa5\xfb\x90\x80\xb5\xfc\xb0\x80\xb4\xfd\x90\x81\xa3\xfe\x80\x80\xad\xfd\x80\x81\xa1\xfb\x90\x80\xb2\xfd\x90\x80\xb2\xfd\xb0\x80\xb1\xfd\x90\x81\xa3\xfe\x90\x80\xb6\xfd\x80\x80\xb9\xf9\x80\x81\xa1\xf3\xa0\x80\x80\xe7\xbe\x8e\x01'"
[E 15:47:47.024 NotebookApp] Uncaught exception POST /api/sessions (192.168.3.17)
    HTTPServerRequest(protocol='http', host='bigdata-cdh03.xipudata.com:18888', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='192.168.3.17', headers={'Origin': 'http://bigdata-cdh03.xipudata.com:18888', 'Content-Length': '88', 'Accept-Language': 'en-US,en;q=0.8,zh;q=0.6', 'Accept-Encoding': 'gzip, deflate', 'X-Xsrftoken': '2|974ac16c|7a2dbd8b1b63effeaf48e1d7701e3901|1497410688', 'Host': 'bigdata-cdh03.xipudata.com:18888', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://bigdata-cdh03.xipudata.com:18888/notebooks/hello.ipynb', 'Cookie': '_ga=GA1.2.534299577.1492671455; _xsrf=2|974ac16c|7a2dbd8b1b63effeaf48e1d7701e3901|1497410688; username-bigdata-cdh03-xipudata-com-18888="2|1:0|10:1497426466|41:username-bigdata-cdh03-xipudata-com-18888|44:ZTkzYjYwYzMxYWMzNDVhMWJjYmNkZmZkODI4ZDdmYjc=|dd3e94e81a4ffa6259f6c56d7d8e06b7c55075fa55fcc80e5bc0103fcc865d0c"', 'Content-Type': 'application/json'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1415, in _execute
        result = yield result
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 870, in run
        value = future.result()
      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 215, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 876, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/lib/python2.7/site-packages/notebook/base/handlers.py", line 534, in wrapper
        self.finish(json.dumps(reply))
      File "/usr/local/lib/python2.7/json/__init__.py", line 244, in dumps
        return _default_encoder.encode(obj)
      File "/usr/local/lib/python2.7/json/encoder.py", line 207, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/usr/local/lib/python2.7/json/encoder.py", line 270, in iterencode
        return _iterencode(o, 0)
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xf8 in position 1654: invalid start byte
[D 15:47:47.024 NotebookApp] Using contents: services/contents
[D 15:47:47.024 NotebookApp] Using contents: services/contents
[E 15:47:47.025 NotebookApp] {
      "Origin": "http://bigdata-cdh03.xipudata.com:18888",
      "Content-Length": "88",
      "Accept-Language": "en-US,en;q=0.8,zh;q=0.6",
      "Accept-Encoding": "gzip, deflate",
      "X-Xsrftoken": "2|974ac16c|7a2dbd8b1b63effeaf48e1d7701e3901|1497410688",
      "Host": "bigdata-cdh03.xipudata.com:18888",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36",
      "Connection": "keep-alive",
      "X-Requested-With": "XMLHttpRequest",
      "Referer": "http://bigdata-cdh03.xipudata.com:18888/notebooks/hello.ipynb",
      "Cookie": "_ga=GA1.2.534299577.1492671455; _xsrf=2|974ac16c|7a2dbd8b1b63effeaf48e1d7701e3901|1497410688; username-bigdata-cdh03-xipudata-com-18888=\"2|1:0|10:1497426466|41:username-bigdata-cdh03-xipudata-com-18888|44:ZTkzYjYwYzMxYWMzNDVhMWJjYmNkZmZkODI4ZDdmYjc=|dd3e94e81a4ffa6259f6c56d7d8e06b7c55075fa55fcc80e5bc0103fcc865d0c\"",
      "Content-Type": "application/json"
    }
[E 15:47:47.025 NotebookApp] 500 POST /api/sessions (192.168.3.17) 21.11ms referer=http://bigdata-cdh03.xipudata.com:18888/notebooks/hello.ipynb
[D 15:47:47.027 NotebookApp] 200 GET /api/contents/hello.ipynb/checkpoints?_=1497426440648 (192.168.3.17) 1.10ms
[D 15:47:47.597 NotebookApp] activity on eae54289-aee5-43c5-8a42-2517c56994ad: status
^C[I 15:49:16.122 NotebookApp] interrupted
```

**Comment by juntaozhang** [comment]
sorry  it's the problem of _sqlite3.so , and i copy /usr/lib64/python2.6/lib-dynload/_sqlite3.so to python2.7 which is unadvisable.
