### ISSUE TITLE
Jupyter notebook SSL does not allow keyfile with PEM pass phrase

### ISSUE THREAD

**Issue by charlie718y** [jupyter/notebook#2595]
Trying to enable Notebook SSL,

1) Creating a .pem and .key file,
2) To secure the .key file, I put a pass phrase on the .key file.
3) Update notebook config file to point to the certfile and keyfile,
NotebookApp.certfile
NotebookApp.keyfile

An exception is encountered when using browser to access the notebook webserver,

**Enter PEM pass phrase:**
[E 15:24:43.503 NotebookApp] Exception in callback (<socket._socketobject object at 0x7f9bdc28a360>, <function null_wrapper at 0x7f9bdc0bb758>)
    Traceback (most recent call last):
      File "/var/install/lib/python2.7/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/var/install/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/var/install/lib/python2.7/site-packages/tornado/netutil.py", line 276, in accept_handler
        callback(connection, address)
      File "/var/install/lib/python2.7/site-packages/tornado/tcpserver.py", line 264, in _handle_connection
        do_handshake_on_connect=False)
      File "/var/install/lib/python2.7/site-packages/tornado/netutil.py", line 517, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/var/install/lib/python2.7/site-packages/tornado/netutil.py", line 494, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    **IOError: [Errno 22] Invalid argument**

**Comment by gnestor** [comment]
Can you share your update notebook config? 

@minrk Any ideas?

**Comment by charlie718y** [comment]
Hi @gnestor 

It's beeing a while, I no longer have the environment anymore, the issue was due to Tornado not exposing the password parameter in the load_cert_chain API. For more info, refer to, https://github.com/tornadoweb/tornado/issues/2113

In the end I had to stick with passwordless keyfiles. If you guys plan to provide support for password protected keyfiles. Give me a heads up.

Thanks,
Charlie

**Comment by gnestor** [comment]
Thanks for following up @charlie718y! It would be nice to support password-protected keyfiles. We invite you and anyone else to contribute! I'll leave this open and mark as "help wanted".

**Comment by goelakash** [comment]
@gnestor @jtpio 
This issue doesn't seem important. A jupyter server would typically run behind a credential-scoped proxy api/endpoint. The use case for jupyter notebooks is to provide an environment to run a notebook, and not have e2e TLS termination guarantees.
