### ISSUE TITLE
Jupyter on EMR

### ISSUE THREAD

**Issue by iamhasibrahman** [jupyter/notebook#2635]
We just deployed Jupyter with EMR in AWS and running it memory issues whenever we run any job in Jupyter. 

We have pretty large servers  (3 servers, all m4.2xlarge servers) and test data volume is pretty tiny. 

The error messages are shown on ecnlosed images. 

If someone could shed lights, I appreciate a lot. 

---- One error message --- the other two on enclosed file --- 

```17/07/03 04:08:15 WARN YarnAllocator: Container marked as failed: container_1499050738160_0001_01_000011 on host: ip-10-0-24-85.ap-southeast-2.compute.internal. Exit status: 52. Diagnostics: Exception from container-launch.
Container id: container_1499050738160_0001_01_000011
Exit code: 52
Stack trace: ExitCodeException exitCode=52: 
    at org.apache.hadoop.util.Shell.runCommand(Shell.java:582)
    at org.apache.hadoop.util.Shell.run(Shell.java:479)
    at org.apache.hadoop.util.Shell$ShellCommandExecutor.execute(Shell.java:773)
    at org.apache.hadoop.yarn.server.nodemanager.DefaultContainerExecutor.launchContainer(DefaultContainerExecutor.java:212)
    at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:302)
    at org.apache.hadoop.yarn.server.nodemanager.containermanager.launcher.ContainerLaunch.call(ContainerLaunch.java:82)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:748)```

![pasted image at 2017_07_06 09_17 am](https://user-images.githubusercontent.com/17756569/27890599-0a4061b8-6237-11e7-987d-e7c9f5db86a9.png)
![pasted image at 2017_07_06 09_18 am](https://user-images.githubusercontent.com/17756569/27890600-0a908fb2-6237-11e7-88a6-798e0b983b2b.png)

**Comment by iamhasibrahman** [comment]
![pasted image at 2017_07_06 09_17 am](https://user-images.githubusercontent.com/17756569/27890612-2ae1cf88-6237-11e7-9e90-f74a3edec8c5.png)
![pasted image at 2017_07_06 09_18 am](https://user-images.githubusercontent.com/17756569/27890613-2b2164ea-6237-11e7-9c0f-116b0c871c51.png)

**Comment by rolweber** [comment]
Check the memory limits of your containers. See for example https://stackoverflow.com/a/21008262/5629418
