### ISSUE TITLE
Loading changed kernel.json without notebook server restart

### ISSUE THREAD

**Issue by fabboe** [jupyter/notebook#2647]
Hi all,

is it possible to update kernel.json content and use it / refresh the cached definition without restarting the jupyter notebook server?

I update kernel.json, then restart a corresponding kernel but it still picks up the old kernel definition. It only loads the new one after restart jupyer notebook.

Could not find any documentation on when/how to pick up kernel definitions.

Thanks,
Fabian

**Comment by minrk** [comment]
If you shutdown and reopen the individual notebook document, it should get the new definition. It doesn't need to restart the notebook server. Alternately, if you have more than one kernelspec, changing the kernel to another kernelspec and then back should also trigger reloading the spec.

**Comment by kevcampb** [comment]
This doesn't seem to be the case. 

With a kernel config file ~/.ipython/kernels/datascience_local/kernel.json
```
{
  "argv": ["~/.virtualenvs/datascience_local/bin/python", "-m", "IPython.kernel",
  "-f", "{connection_file}"],
  "display_name": "Datascience - local",
  "language": "python"
}
```

In this situation, the python path does not work as jupyter will not resolve ~ to the user homedir. The full path needs specified.

Attempting to use the kernel in a notebook will show kernel error, and the traceback given is as follows

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.5/dist-packages/notebook/services/sessions/handlers.py", line 73, in post
    type=mtype))
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.5/dist-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/local/lib/python3.5/dist-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/local/lib/python3.5/dist-packages/notebook/services/kernels/kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/jupyter_client/manager.py", line 259, in start_kernel
    **kw)
  File "/usr/local/lib/python3.5/dist-packages/jupyter_client/manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/usr/local/lib/python3.5/dist-packages/jupyter_client/launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '~/.virtualenvs/datascience_local/bin/python'
```
Correcting the kernel.json file has no effect. Restarting the user hub, logging out as the user, restarting the kernel, deleting and creating a new notebook, the error persists. Same for changing to a working kernel and then changing back.

Creating a new kernel datascience_local2/kernel.json with the correct python path does work. The new kernel appears in the list, and you can change to that kernel and use it successfully.

Restarting the main jupyterhub process will resolve the issue, and the kernel changes will finally be picked up. That's obviously non-ideal though.

```
kevin.campbell@jupyter-stg:~> /usr/local/bin/jupyter  --version
4.4.0
kevin.campbell@jupyter-stg:~> /usr/local/bin/jupyterhub  --version
0.9.1
kevin.campbell@jupyter-stg:~> /usr/local/bin/jupyter notebook --version
5.6.0
```
