### ISSUE TITLE
Cannot launch jupyter notebook 

### ISSUE THREAD

**Issue by diudiutong** [jupyter/notebook#2649]
When I launch jupyter notebook ,it shows up about 1-2 seconds then quit.
When I launch it in the terminal ,it shows this:
Microsoft Windows [版本 10.0.14393]
(c) 2016 Microsoft Corporation。保留所有权利。

C:\Users\lenovo>jupyter notebook
Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\jupyter-notebook-script.py", line 5, in <module>
    sys.exit(notebook.notebookapp.main())
  File "C:\Anaconda2\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Anaconda2\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "C:\Anaconda2\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Anaconda2\lib\site-packages\notebook\notebookapp.py", line 1296, in initialize
    self.init_webapp()
  File "C:\Anaconda2\lib\site-packages\notebook\notebookapp.py", line 1113, in init_webapp
    self.login_handler_class.validate_security(self, ssl_options=ssl_options)
  File "C:\Anaconda2\lib\site-packages\notebook\auth\login.py", line 214, in validate_security
    if not app.ip:
  File "C:\Anaconda2\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "C:\Anaconda2\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "C:\Anaconda2\lib\site-packages\notebook\notebookapp.py", line 525, in _default_ip
    s = socket.socket()
  File "C:\Anaconda2\lib\socket.py", line 191, in __init__
    _sock = _realsocket(family, type, proto)
socket.error: [Errno 10106]

I use Windows 10.

**Comment by takluyver** [comment]
Error 10106 [is described as](https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx):

> Service provider failed to initialize.

> The requested service provider could not be loaded or initialized. This error is returned if either a service provider's DLL could not be loaded (LoadLibrary failed) or the provider's WSPStartup or NSPStartup function failed.

Do you have some anti-virus or firewall software installed? We have run into problems with various 'security' systems.

**Comment by diudiutong** [comment]
Thanks.I do have installed firewall software,but after I quit it,the notebook is still not working
