### ISSUE TITLE
Notebook launch errors

### ISSUE THREAD

**Issue by Viny123** [jupyter/notebook#2651]
Hi there, I'm new to all this.

When I try to launch Jupyter notebook I get the folowing errors:

```
(C:\Users\Vincent\Anaconda3) C:\Users\Vincent>jupyter notebook
Traceback (most recent call last):
  File "C:\Users\Vincent\Anaconda3\Scripts\jupyter-notebook-script.py", line 5, in <module>
    sys.exit(notebook.notebookapp.main())
  File "C:\Users\Vincent\Anaconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\Vincent\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "C:\Users\Vincent\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\Vincent\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1104, in initialize
    super(NotebookApp, self).initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "C:\Users\Vincent\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\Vincent\Anaconda3\lib\site-packages\jupyter_core\application.py", line 243, in initialize
    self.migrate_config()
  File "C:\Users\Vincent\Anaconda3\lib\site-packages\jupyter_core\application.py", line 162, in migrate_config
    from .migrate import get_ipython_dir, migrate
  File "C:\Users\Vincent\Anaconda3\lib\site-packages\jupyter_core\migrate.py", line 35, in <module>
    from IPython.paths import get_ipython_dir
  File "C:\Users\Vincent\Anaconda3\lib\site-packages\IPython\__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "C:\Users\Vincent\Anaconda3\lib\site-packages\IPython\terminal\embed.py", line 17, in <module>
    from IPython.core.interactiveshell import DummyMod, InteractiveShell
  File "C:\Users\Vincent\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 62, in <module>
    from IPython.utils import io
  File "C:\Users\Vincent\Anaconda3\lib\site-packages\IPython\utils\io.py", line 90, in <module>
    devnull = open(os.devnull, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'nul'
```

I've tried:
reinstalling anaconda several times
reinstalling notebook
restarting pc a few times between reinstalling anaconda and notebook
downgrading notebook
and I probably forgot a few things...

Anyone who can help me?

**Comment by takluyver** [comment]
Is there anything odd about your PC? 'nul' is meant to be a virtual file that always exists, which you can write to to discard data. I don't know how it can be missing.

**Comment by Viny123** [comment]
Not that I am aware of, although.. I had test mode on, but after I turned it off nothing happened.

**Comment by Viny123** [comment]
Spyder doesn't work either, is the problem related to notebook?

Traceback (most recent call last):
File "C:\Users\Vincent\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3011, in main
mainwindow = run_spyder(app, options, args)
File "C:\Users\Vincent\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 2913, in run_spyder
main.setup()
File "C:\Users\Vincent\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 860, in setup
from spyder.plugins.externalconsole import ExternalConsole
File "C:\Users\Vincent\Anaconda3\lib\site-packages\spyder\plugins\externalconsole.py", line 39, in 
from spyder.widgets.externalshell.pythonshell import ExternalPythonShell
File "C:\Users\Vincent\Anaconda3\lib\site-packages\spyder\widgets\externalshell\pythonshell.py", line 34, in 
from spyder.widgets.variableexplorer.namespacebrowser import NamespaceBrowser
File "C:\Users\Vincent\Anaconda3\lib\site-packages\spyder\widgets\variableexplorer\namespacebrowser.py", line 26, in 
import ipykernel.pickleutil
File "C:\Users\Vincent\Anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\Vincent\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Users\Vincent\Anaconda3\lib\site-packages\IPython\__init__.py", line 49, in 
from .terminal.embed import embed
File "C:\Users\Vincent\Anaconda3\lib\site-packages\IPython\terminal\embed.py", line 17, in 
from IPython.core.interactiveshell import DummyMod, InteractiveShell
File "C:\Users\Vincent\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 62, in 
from IPython.utils import io
File "C:\Users\Vincent\Anaconda3\lib\site-packages\IPython\utils\io.py", line 90, in 
devnull = open(os.devnull, 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'nul'

**Comment by takluyver** [comment]
Yup, they're both running into the same problem. 😕

**Comment by Viny123** [comment]
No one who can help me? 😕

**Comment by takluyver** [comment]
Google found these things:

https://github.com/chrippa/livestreamer/issues/674
http://grasswiki.osgeo.org/wiki/WinGRASS_errors#The_startup_fails_with_a_IOerror:_.5BErrno_2.5D_No_such_file_or_directory_:_.27nul.27

All I can say is to try what they suggest!

**Comment by Viny123** [comment]
Thank you @takluyver ! That did help. And of course chrippa and the author of:
 [http://grasswiki.osgeo.org/wiki/WinGRASS_errors#The_startup_fails_with_a_IOerror:_.5BErrno_2.5D_No_such_file_or_directory_:_.27nul.27](url) 
If the author isn't chrippa 😛 

Although, I had my doubts, because of all the errors it showed.

So here's what I did:

> Q: At startup, I get:
>  ```
> nul=open <os.devnull, 'w'>
>  IOerror: [Errno 2] No such file or directory : 'nul'
> ```
> 
> A: Apparently, it's possible for the service implementing the null device ('nul' pseudo-file) to be stopped or to malfunction.
> 
> The status can be checked via the control panel. Start the Device Manager (Control Panel > Hardware and Sound > Device Manager), select View > Show hidden devices, then under Non-Plug and Play Drivers, there should be an entry for "Null".
> 
> The corresponding registry key is:
> `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\Null`
> The Start and Type values should both be 1. `

In my case, I don't have "Non-Plug and play Drivers" option in my Device Manager (and yes, I did reveal the secret hidden files my PC has 🤣) and the "Type" value was already "1".
But.. All I had to do was to change the "Start" value from "4" to "1". After I changed it, I had to reboot my pc for the changes to take effect.

I hope this can help others as well, might they encounter a similair problem😄

**Comment by takluyver** [comment]
Thanks for the follow up, @Viny123 :-)
