### ISSUE TITLE
New ImportError: cannot import name path

### ISSUE THREAD

**Issue by mohamsh** [jupyter/notebook#2693]
I'm trying to run Jupyter on a pyenv. I've followed the steps found in similar issues none of them helped.
However, I still get the following error after uninstalling and installing `path.py`
Can you help?

```
Traceback (most recent call last):
  File "/Users/mohammad/.pyenv/versions/2.7.10/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/mohammad/.pyenv/versions/2.7.10/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/mohammad/.pyenv/versions/2.7.10/envs/vida-webserver/lib/python2.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/Users/mohammad/.pyenv/versions/2.7.10/envs/vida-webserver/lib/python2.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/Users/mohammad/.pyenv/versions/2.7.10/envs/vida-webserver/lib/python2.7/site-packages/ipykernel/connect.py", line 14, in <module>
    from IPython.paths import get_ipython_dir
ImportError: No module named paths
```

**Comment by takluyver** [comment]
It's finding an older version of IPython somewhere. Uninstall any copies of IPython you can find, and install the latest version again.

**Comment by Tapudp** [comment]
I'm trying to deploy my django blog site to pythonanywhere.com and when the whole app is deployed perfectly and the wsgi application is also set properly, in my main project "djangonautic/urls.py", upon writing ``from django.urls import path`` , and when opening the site it says 'ImportError at / ', cannot import name 'path'

for your reference, I know that ``path`` was not there in django 1.11 but I'm using django 2.0 on my local machine as well on the pythonanywhere.com , but the error still persists, I don't even know what other options should I try!!!

**Comment by djruesch** [comment]
I have the same problem.

**Comment by darrahts** [comment]
Yes me too, I installed keras today which installed some other packages and now I have this error. This is on Windows with anaconda 1.9.6. Anaconda was also just upgraded too. The error is appearing in the Ipython console of Spyder.
