### ISSUE TITLE
Unable to launch the Jupyter notebook

### ISSUE THREAD

**Issue by jimmy-walker** [jupyter/notebook#2703]
Hello everyone,
I cannot launch the jupyter notebook.
I searched for some time, but it doesn't fix the problem.
I tried to reinstall the anaconda, but it still doesn't work.
I didn't do anything before, but it suddenly broken.

```
C:\Users\jimmylian>jupyter notebook
[W 16:06:30.931 NotebookApp] Error loading server extension hide_code
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py",
 line 1271, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 126, in im
port_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 948, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'hide_code'
[I 16:06:31.033 NotebookApp] Serving notebooks from local directory: C:\Users\ji
mmylian
[I 16:06:31.033 NotebookApp] 0 active kernels
[I 16:06:31.033 NotebookApp] The Jupyter Notebook is running at: http://localhos
t:8888/?token=76bdbb97349d7fe563fab37b486da2835414955d42d2b939
[I 16:06:31.034 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip confirmation).
[C 16:06:31.039 NotebookApp]
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=76bdbb97349d7fe563fab37b486da2835414955d42d
2b939
[I 16:06:31.040 NotebookApp] Shutting down kernels
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\jupyter-notebook-script.py", line 5, in
 <module>
    sys.exit(notebook.notebookapp.main())
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_core\application.py",
 line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.
py", line 658, in launch_instance
    app.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", lin
e 1417, in start
    self.io_loop.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", lin
e 177, in start
    super(ZMQIOLoop, self).start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\ioloop.py", line 863,
 in start
    event_pairs = self._impl.poll(poll_timeout)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", lin
e 122, in poll
    z_events = self._poller.poll(1000*timeout)
  File "C:\ProgramData\Anaconda3\lib\site-packages\zmq\sugar\poll.py", line 99,
in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 123, in zmq.backend.cython._poll.zmq
_poll (zmq\backend\cython\_poll.c:2186)
  File "zmq/backend/cython/_poll.pyx", line 116, in zmq.backend.cython._poll.zmq
_poll (zmq\backend\cython\_poll.c:2036)
  File "zmq/backend/cython/checkrc.pxd", line 25, in zmq.backend.cython.checkrc.
_check_rc (zmq\backend\cython\_poll.c:2811)
    raise ZMQError(errno)
zmq.error.ZMQError: Unknown error
```

**Comment by takluyver** [comment]
Do you have any security or antivirus software? Sometimes this causes problems for the notebook - try turning it off and see if it makes a difference.

**Comment by jimmy-walker** [comment]
@takluyver Thanks for your reply. I have checked it for my system:windows 7. We are using it in the company under same circumstance. My friends can use it normally. But I cannot.
I also change the jupyter serverextension setting to delete the mode hide_code. But it doesn't change anything.
I tried to use it within my virtual machine system with ubuntu. It can work normally.

**Comment by jimmy-walker** [comment]
I guess it may be related with my vpn provider "astrill". After I used "stealthvpn" service of it, the problem comes.
Maybe it was occupied by the port?
But I check the port 8888 by netstat -ano|findstr "8888",it cannot find anything.

**Comment by takluyver** [comment]
It might be trying to route all network traffic through the VPN, including the notebook server's connections on localhost. Sorry, I don't know enough about VPNs to advise you on that.

**Comment by jimmy-walker** [comment]
It's so kind to you. Thanks for the reply. I will try to solve it later.

**Comment by winner1986** [comment]
@jimmy-walker Have you solved the problem? I am in the same trouble with you

**Comment by jimmy-walker** [comment]
Nope, I failed. I installed vmware with ubuntu to use the ipython notebook.

**Comment by winner1986** [comment]
what a pity

**Comment by jimmy-walker** [comment]
I finally resolve this question via uninstalling the software "astrill".
It appears that this software had occupied the port or resources of juypter notebook.
