### ISSUE TITLE
jupyter nbextension install raise error

### ISSUE THREAD

**Issue by wispyoureyes** [jupyter/notebook#2741]
I'm trying to install the extensions with the following set of commands:
`jupyter nbextension install my_module [--sys-prefix|--user]`
And it raise the following error:
```
$ jupyter nbextension install . [--sys-prefix|--user]

Traceback (most recent call last):
  File "/anaconda/bin/jupyter-nbextension", line 6, in <module>
    sys.exit(notebook.nbextensions.main())
  File "/anaconda/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/anaconda/lib/python3.6/site-packages/notebook/nbextensions.py", line 900, in start
    super(NBExtensionApp, self).start()
  File "/anaconda/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/anaconda/lib/python3.6/site-packages/notebook/nbextensions.py", line 678, in start
    self.install_extensions()
  File "/anaconda/lib/python3.6/site-packages/notebook/nbextensions.py", line 639, in install_extensions
    raise ValueError("Only one nbextension allowed at a time. "

ValueError: Only one nbextension allowed at a time. Call multiple times to install multiple extensions.
```

**Comment by takluyver** [comment]
The bit in square brackets describes options, you're not meant to copy the
whole thing.

On 9 Aug 2017 9:05 a.m., "Greenovia" <notifications@github.com> wrote:

I'm trying to install and the extensions with the following set of commands:
And it raise the following error:

jupyter nbextension install my_module [--sys-prefix|--user]
anderweltdeMacBook-Pro:jupyter_console adminastor$ jupyter nbextension
install . [--sys-prefix|--user]
Traceback (most recent call last):
  File "/anaconda/bin/jupyter-nbextension", line 6, in <module>
    sys.exit(notebook.nbextensions.main())
  File "/anaconda/lib/python3.6/site-packages/jupyter_core/application.py",
line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/anaconda/lib/python3.6/site-packages/traitlets/config/application.py",
line 658, in launch_instance
    app.start()
  File "/anaconda/lib/python3.6/site-packages/notebook/nbextensions.py",
line 900, in start
    super(NBExtensionApp, self).start()
  File "/anaconda/lib/python3.6/site-packages/jupyter_core/application.py",
line 256, in start
    self.subapp.start()
  File "/anaconda/lib/python3.6/site-packages/notebook/nbextensions.py",
line 678, in start
    self.install_extensions()
  File "/anaconda/lib/python3.6/site-packages/notebook/nbextensions.py",
line 639, in install_extensions
    raise ValueError("Only one nbextension allowed at a time. "
ValueError: Only one nbextension allowed at a time. Call multiple
times to install multiple extensions.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/jupyter/notebook/issues/2741>, or mute the thread

**Comment by wispyoureyes** [comment]
Thanks a lot! Trouble you to fix another error raised when I try to enable the extension.
```
$ jupyter nbextension enable my_tarball_bundler

Enabling notebook extension my_tarball_bundler...
      - Validating: problems found:
        - require?  X my_tarball_bundler
```
Seems not able to find the module named 'my_tarball_bundler'

**Comment by takluyver** [comment]
nbextensions are usually javascript files for the frontend. If you're trying to extend the notebook *server*, you'd normally install it using standard Python packaging (pip etc), and enable it with `jupyter serverextension enable`.

**Comment by wispyoureyes** [comment]
The examples in the [doc](https://jupyter-notebook.readthedocs.io) is not complete，is there any complete sever extension example or git repo that I can refer to ?

**Comment by takluyver** [comment]
[jupyter_nbextensions_configurator](https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator) is a server extension to allow configuring nbextensions.

**Comment by wispyoureyes** [comment]
Thank you so much! I've installed my server extension and it runs successfully!
