### ISSUE TITLE
Error updating Jupyter notebook to 5.0

### ISSUE THREAD

**Issue by Manish-rai21bit** [jupyter/notebook#2779]
I am trying to upgrade my jupiter notebook from 4.2.2 to the latest version on my Mac OS. I am not able to upgrade it using "pip install notebook --upgrade".

The error I'm getting is below. Please let me know what is it that I'm missing.-

```
Collecting webencodings (from html5lib>=0.99999999->bleach->nbconvert->notebook)
  Using cached webencodings-0.5.1-py2.py3-none-any.whl
Installing collected packages: setuptools, prompt-toolkit, ipython, ipykernel, mistune, MarkupSafe, jinja2, webencodings, html5lib, bleach, testpath, pandocfilters, jsonschema, nbformat, entrypoints, nbconvert, notebook, ptyprocess
  Found existing installation: setuptools 35.0.1
    Uninstalling setuptools-35.0.1:
Exception:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 303, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/setuptools-35.0.1.dist-info/DESCRIPTION.rst'
```

**Comment by takluyver** [comment]
Try adding the `--user` flag to the pip command to install into your user account.

**Comment by Manish-rai21bit** [comment]
Thanks Takluyver. The solution worked. 
This is the exact command that I used:
 pip install --upgrade --user jupyter

**Comment by takluyver** [comment]
👍
