### ISSUE TITLE
Cannot build docs: NameError: name '_' is not defined

### ISSUE THREAD

**Issue by hroncok** [jupyter/notebook#2798]
I'm trying to package 5.1.0rc2 as an RPM for Fedora Rawhide (to be Fedora 28). Part of the process is to build the documentation.

I have the sdist from PyPI unpacked + 81d0e6146d73a716e8f46b3054dd389ef67779be applied as a patch. I'm running CPython 3.6.2.

The error is:

```
Exception occurred:
  File "/notebook-5.1.0rc2/notebook/services/contents/manager.py", line 69, in ContentsManager
    untitled_notebook = Unicode(_("Untitled"), config=True,
NameError: name '_' is not defined
```

<details>
<summary>full command+stdout+stderr</summary>

```console
# sphinx-build-3 docs/source html
Running Sphinx v1.6.3
making output directory...
DEBUG:: sys.path
================
/usr/bin
/usr/lib64/python36.zip
/usr/lib64/python3.6
/usr/lib64/python3.6/lib-dynload
/usr/lib64/python3.6/site-packages
/usr/lib/python3.6/site-packages
repo_root
=====================
/notebook-5.1.0rc2
DEBUG:: Post insert to sys.path
===============================
/notebook-5.1.0rc2
/notebook-5.1.0rc2/docs/sphinxext
/usr/bin
/usr/lib64/python36.zip
/usr/lib64/python3.6
/usr/lib64/python3.6/lib-dynload
/usr/lib64/python3.6/site-packages
/usr/lib/python3.6/site-packages
Initializing GitHub plugin
loading pickled environment... not yet created
loading intersphinx inventory from https://ipython.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from https://nbconvert.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://nbformat.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://jupyter.readthedocs.io/en/latest/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 32 source files that are out of date
updating environment: 32 added, 0 changed, 0 removed
reading sources... [  3%] changelog
reading sources... [  6%] comms
reading sources... [  9%] config_overview
reading sources... [ 12%] contributing
reading sources... [ 15%] development_faq
reading sources... [ 18%] development_release
reading sources... [ 21%] examples/Notebook/Connecting with the Qt Console
Executing notebook with kernel: python3
reading sources... [ 25%] examples/Notebook/Custom Keyboard Shortcuts
Executing notebook with kernel: python3
reading sources... [ 28%] examples/Notebook/Distributing Jupyter Extensions as Python Packages
reading sources... [ 31%] examples/Notebook/Importing Notebooks
reading sources... [ 34%] examples/Notebook/JavaScript Notebook Extensions
reading sources... [ 37%] examples/Notebook/Notebook Basics
reading sources... [ 40%] examples/Notebook/Running Code
reading sources... [ 43%] examples/Notebook/Typesetting Equations
reading sources... [ 46%] examples/Notebook/What is the Jupyter Notebook
reading sources... [ 50%] examples/Notebook/Working With Markdown Cells
reading sources... [ 53%] examples/Notebook/examples_index
reading sources... [ 56%] examples/Notebook/nbpackage/mynotebook
reading sources... [ 59%] examples/Notebook/nbpackage/nbs/other
reading sources... [ 62%] extending/bundler_extensions
reading sources... [ 65%] extending/contents
/notebook-5.1.0rc2/docs/source/changelog.rst:16: WARNING: Explicit markup ends without a blank line; unexpected unindent.

Exception occurred:
  File "/notebook-5.1.0rc2/notebook/services/contents/manager.py", line 69, in ContentsManager
    untitled_notebook = Unicode(_("Untitled"), config=True,
NameError: name '_' is not defined
The full traceback has been saved in /tmp/sphinx-err-4jf6itch.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
</details>

<details>
<summary>full sphinx-err-4jf6itch.log</summary>

```
# Sphinx version: 1.6.3
# Python version: 3.6.2 (CPython)
# Docutils version: 0.13.1 release
# Jinja2 version: 2.9.6
# Last messages:
#   reading sources... [ 53%] examples/Notebook/examples_index
#   
#   reading sources... [ 56%] examples/Notebook/nbpackage/mynotebook
#   
#   reading sources... [ 59%] examples/Notebook/nbpackage/nbs/other
#   
#   reading sources... [ 62%] extending/bundler_extensions
#   
#   reading sources... [ 65%] extending/contents
#   
# Loaded extensions:
#   alabaster (0.7.9) from /usr/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.6.3) from /usr/lib/python3.6/site-packages/sphinx/ext/autodoc.py
#   sphinx.ext.doctest (1.6.3) from /usr/lib/python3.6/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.intersphinx (1.6.3) from /usr/lib/python3.6/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.autosummary (1.6.3) from /usr/lib/python3.6/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.mathjax (1.6.3) from /usr/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   IPython.sphinxext.ipython_console_highlighting (unknown version) from /usr/lib/python3.6/site-packages/IPython/sphinxext/ipython_console_highlighting.py
#   nbsphinx (0.2.13) from /usr/lib/python3.6/site-packages/nbsphinx.py
#   github (unknown version) from /notebook-5.1.0rc2/docs/sphinxext/github.py
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/sphinx/cmdline.py", line 306, in main
    app.build(opts.force_all, filenames)
  File "/usr/lib/python3.6/site-packages/sphinx/application.py", line 339, in build
    self.builder.build_update()
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 331, in build_update
    'out of date' % len(to_build))
  File "/usr/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 344, in build
    updated_docnames = set(self.env.update(self.config, self.srcdir, self.doctreedir))
  File "/usr/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 583, in update
    self._read_serial(docnames, self.app)
  File "/usr/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 602, in _read_serial
    self.read_doc(docname, app)
  File "/usr/lib/python3.6/site-packages/sphinx/environment/__init__.py", line 723, in read_doc
    pub.publish()
  File "/usr/lib/python3.6/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/lib/python3.6/site-packages/sphinx/io.py", line 74, in read
    self.parse()
  File "/usr/lib/python3.6/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/__init__.py", line 185, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/usr/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2745, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2745, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2745, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 326, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2318, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2330, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2073, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2122, in run_directive
    result = directive_instance.run()
  File "/usr/lib/python3.6/site-packages/sphinx/ext/autosummary/__init__.py", line 230, in run
    items = self.get_items(names)
  File "/usr/lib/python3.6/site-packages/sphinx/ext/autosummary/__init__.py", line 277, in get_items
    real_name, obj, parent, modname = import_by_name(name, prefixes=prefixes)
  File "/usr/lib/python3.6/site-packages/sphinx/ext/autosummary/__init__.py", line 498, in import_by_name
    obj, parent, modname = _import_by_name(prefixed_name)
  File "/usr/lib/python3.6/site-packages/sphinx/ext/autosummary/__init__.py", line 515, in _import_by_name
    __import__(modname)
  File "/notebook-5.1.0rc2/notebook/services/contents/manager.py", line 37, in <module>
    class ContentsManager(LoggingConfigurable):
  File "/notebook-5.1.0rc2/notebook/services/contents/manager.py", line 69, in ContentsManager
    untitled_notebook = Unicode(_("Untitled"), config=True,
NameError: name '_' is not defined

```

</details>

<details>
<summary>pip freeze</summary>

```console
# python3 -m pip freeze
alabaster==0.7.9
asn1crypto==0.22.0
Babel==2.3.4
cffi==1.10.0
chardet==3.0.4
cryptography==2.0.2
decorator==4.0.11
docutils==0.13.1
funcsigs==1.0.2
idna==2.5
imagesize==0.7.1
ipykernel==4.6.0
ipython==6.1.0
ipython-genutils==0.1.0
jedi==0.10.2
Jinja2==2.9.6
jsonschema==2.6.0
jupyter-client==4.4.0
jupyter-core==4.1.0
MarkupSafe==0.23
mistune==0.7.3
mock==2.0.0
nbconvert==5.2.1
nbformat==4.3.0
nbsphinx==0.2.13
nose==1.3.7
nose-warnings-filters==0.1.5
pandocfilters==1.4.1
path.py==5.2
pbr==3.1.1
pexpect==4.2.1
pickleshare==0.7.4
ply==3.9
prompt-toolkit==1.0.14
ptyprocess==0.5.2
pycparser==2.14
pycurl==7.43.0
Pygments==2.2.0
pyOpenSSL==17.1.0
PySocks==1.5.7
pytz==2017.2
pyzmq==16.0.2
requests==2.18.4
simplegeneric==0.8.1
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.6.3
sphinx-rtd-theme==0.2.4
sphinxcontrib-websupport==1.0.1
SQLAlchemy==1.1.13
terminado==0.6
testpath==0.3.1
tornado==4.4.2
traitlets==4.3.2
urllib3==1.22
wcwidth==0.1.7
Whoosh==2.7.4
```
</details>

**Comment by hroncok** [comment]
cc @JCEmmons as this is related to f81fb46ff68323f9652d638a325e9ccc46f62e83

**Comment by hroncok** [comment]
I might have a solution. Testing.

**Comment by takluyver** [comment]
Yup, that's the i18n machinery - `_` is injected into the builtins to look up translations, but evidently it isn't when the docs build imports the notebook.

Thanks for the report, it's embarrassing that we haven't caught that already. I suspect it can be worked around by modifying `conf.py` - if you get that working, please do send us a PR.

**Comment by ixjlyons** [comment]
The fix for this is supposed to have landed in 5.1.0, correct? I'm still getting `NameError: name '_' is not defined` with notebook-5.1.0 from conda-forge. Our build uses [notedown](https://github.com/aaren/notedown), which implements a subclass of `FileContentsManager`.

```
Traceback (most recent call last):
  File "/home/kenny/miniconda3/envs/resonance-dev/bin/notedown", line 7, in <module>
    from notedown.main import app
  File "/home/kenny/miniconda3/envs/resonance-dev/lib/python3.6/site-packages/notedown/__init__.py", line 8, in <module>
    from .contentsmanager import NotedownContentsManager
  File "/home/kenny/miniconda3/envs/resonance-dev/lib/python3.6/site-packages/notedown/contentsmanager.py", line 8, in <module>
    from notebook.services.contents.filemanager import FileContentsManager
  File "/home/kenny/miniconda3/envs/resonance-dev/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 21, in <module>
    from .manager import ContentsManager
  File "/home/kenny/miniconda3/envs/resonance-dev/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 37, in <module>
    class ContentsManager(LoggingConfigurable):
  File "/home/kenny/miniconda3/envs/resonance-dev/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 69, in ContentsManager
    untitled_notebook = Unicode(_("Untitled"), config=True,
NameError: name '_' is not defined
The program exited via sys.exit(). Exit status: notedown failed: 1
```

Any ideas?

**Comment by takluyver** [comment]
The fix that landed was for building our own Sphinx docs. You'll need to ensure that the `_` is installed (which you can do by importing `notebook.transutils`) before importing any code which uses it.

**Comment by ixjlyons** [comment]
I see, thanks!

**Comment by jdemeyer** [comment]
This problem still persists with notebook-5.2.2:
```
Traceback (most recent call last):
  File "/usr/local/src/sage-config/local/bin/notedown", line 11, in <module>
    load_entry_point('notedown==1.5.0', 'console_scripts', 'notedown')()
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/notedown/__init__.py", line 8, in <module>
    from .contentsmanager import NotedownContentsManager
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/notedown/contentsmanager.py", line 8, in <module>
    from notebook.services.contents.filemanager import FileContentsManager
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/notebook/services/contents/filemanager.py", line 21, in <module>
    from .manager import ContentsManager
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/notebook/services/contents/manager.py", line 38, in <module>
    class ContentsManager(LoggingConfigurable):
  File "/usr/local/src/sage-config/local/lib/python2.7/site-packages/notebook/services/contents/manager.py", line 70, in ContentsManager
    untitled_notebook = Unicode(_("Untitled"), config=True,
NameError: name '_' is not defined
```

**Comment by qris** [comment]
Commit daeb0a401bffb6a8b60948b79456c875fd716968 did not change `notebook/services/contents/manager.py` or `__builtins__` at all, so importing notebook.services.contents.manager still leaves the `_` function undefined. Importing `notebook.transutils` first has no effect because it does not modify `__builtins__`.

**Comment by takluyver** [comment]
transutils calls `trans.install()`, which does modify builtins.
