### ISSUE TITLE
python 2.7 jupyter notebook re-generate config file (input/raw_input)

### ISSUE THREAD

**Issue by MarekLew** [jupyter/notebook#281]
### system:
```javascript
{'commit_hash': u'f534027',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/myuser/.virtualenvs/ipython/lib/python2.7/site-packages/IPython',
 'ipython_version': '4.0.0',
 'os_name': 'posix',
 'platform': 'Linux-3.13.0-61-generic-x86_64-with-Ubuntu-14.04-trusty',
 'sys_executable': '/home/myuser/.virtualenvs/ipython/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.6 (default, Jun 22 2015, 17:58:13) \n[GCC 4.8.2]'}
```

jupyter --version
```
4.0.2
```

### command:
jupyter notebook --generate-confi

```sh
/home/myuser/.virtualenvs/ipython/local/lib/python2.7/site-packages/IPython/paths.py:49: UserWarning: Ignoring ~/.config/ipython in favour of ~/.ipython. Remove ~/.config/ipython to get rid of this message
  'get rid of this message').format(cu(xdg_ipdir), cu(ipdir)))
Overwrite /home/myuser/.jupyter/jupyter_notebook_config.py with default config? [y/N]y
Traceback (most recent call last):
  File "/home/myuser/.virtualenvs/ipython/bin/jupyter-notebook", line 6, in <module>
    main()
  File "/home/myuser/.virtualenvs/ipython/local/lib/python2.7/site-packages/jupyter_core/application.py", line 261, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/myuser/.virtualenvs/ipython/local/lib/python2.7/site-packages/traitlets/config/application.py", line 592, in launch_instance
    app.start()
  File "/home/myuser/.virtualenvs/ipython/local/lib/python2.7/site-packages/notebook/notebookapp.py", line 1057, in start
    super(NotebookApp, self).start()
  File "/home/myuser/.virtualenvs/ipython/local/lib/python2.7/site-packages/jupyter_core/application.py", line 254, in start
    self.write_default_config()
  File "/home/myuser/.virtualenvs/ipython/local/lib/python2.7/site-packages/jupyter_core/application.py", line 135, in write_default_config
    answer = ask()
  File "/home/myuser/.virtualenvs/ipython/local/lib/python2.7/site-packages/jupyter_core/application.py", line 131, in ask
    return input(prompt).lower() or 'n'
  File "<string>", line 1, in <module>
NameError: name 'y' is not defined
```
for python 2.7 **input** _equivalent to eval(raw_input(prompt))_.

**Comment by minrk** [comment]
Arg, sorry. Should be fixed by jupyter/jupyter_core#42
