### ISSUE TITLE
WindowsError: [Error 5] Access is denied, while installing jupyter

### ISSUE THREAD

**Issue by ayeshsalah** [jupyter/notebook#2827]
Hello,

I tried installing Jupyter using _pip install jupyter_ on the cmd as an administrator. I get the below error. I am on a 64bit Windows 10 machine. I am using python 2.7. My user profile has the required permissions. I looked at a similar issue, https://github.com/jupyter/notebook/issues/1385 and set the HOME and HOMEPATH. I am still facing the same issue. 

Any ideas how I can install jupyter? I tried using the anaconda way as well, the installer just runs for hours. Does not error out or install, this is why I moved back to the cmd.  

```
C:\windows\system32>pip install jupyter
Collecting jupyter
  Using cached jupyter-1.0.0-py2.py3-none-any.whl
Requirement already satisfied: nbconvert in c:\python27\lib\site-packages (from jupyter)
Collecting notebook (from jupyter)
  Using cached notebook-5.0.0-py2.py3-none-any.whl
Exception:
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\python27\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "c:\python27\lib\site-packages\pip\req\req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "c:\python27\lib\site-packages\pip\download.py", line 821, in unpack_url
    hashes=hashes
  File "c:\python27\lib\site-packages\pip\download.py", line 663, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "c:\python27\lib\site-packages\pip\utils\__init__.py", line 599, in unpack_file
    flatten=not filename.endswith('.whl')
  File "c:\python27\lib\site-packages\pip\utils\__init__.py", line 498, in unzip_file
    ensure_dir(dir)
  File "c:\python27\lib\site-packages\pip\utils\__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "c:\python27\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 5] Access is denied: 'c:\\users\\mo291764\\appdata\\local\\temp\\pip-build-w5gv3b\\notebook\\notebook/static/components/codemirror/mode/nsis'
```

**Comment by ayeshsalah** [comment]
I tried to install jupyter today and it worked without issue.
