### ISSUE TITLE
Comm documentation examples result in error

### ISSUE THREAD

**Issue by rlamorea** [jupyter/notebook#2833]
I am trying to follow the documentation for setting up a Comm as described here:
http://jupyter-notebook.readthedocs.io/en/latest/comms.html

However, there appears to be _something_ missing as I end up getting the following error:

```AttributeError: 'NoneType' object has no attribute 'session'```

The error is triggered when executing:

```c.send(...)```

**Comment by rlamorea** [comment]
I'm fairly certain the `NoneType` object has no attribute `session` is coming from the Comm not having a kernel member.

Here's the stack trace after the `send` call:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
...<snip>...
AttributeError: 'NoneType' object has no attribute 'session'
```

**Comment by takluyver** [comment]
Actually, I think I see the issue. You're trying to use a comm in the `__init__` method of the Kernel subclass. The kernel needs to be fully initialised before using comms, so you need to experiment with comms somewhere else in the code.

**Comment by ubixadmin** [comment]
FWIW: The stack trace was from one part of the experiment where I was trying it in `__init__`.  I also tried it in the class definition (which, I'm guessing, is basically the same thing), and inside the `do_execute` and still got similar errors.

Which, I guess, is my point.  The snippet in the doc doesn't really help if there isn't context for when the Comm can be created and used, especially as there are clearly places where it _can't_ go.

**Comment by takluyver** [comment]
Normally that code would be triggered by the user inside the IPython kernel - e.g. when they instantiate an object that uses a comm. I wasn't really thinking about kernel authors when I wrote it.

**Comment by rlamorea** [comment]
Well, I'll see if I can find a place in the kernel where it works.  Ironically the thing that would seem to be the most obvious place to me as a neophyte just hacking based on the docs is (`on_connect`) -- and that has been deprecated.

**Comment by takluyver** [comment]
I think it should work in the `do_execute()` method, but maybe the IPython kernel is doing something extra and it doesn't automatically work for other Python-based kernels.

Where do you see `on_connect`? I don't see that anywhere in the docs or the code.

**Comment by rlamorea** [comment]
Sorry, typing too fast.  Meant handing the `connect` message (which has since been deprecated).

I will try again inside `do_execute`.  If I recall I got a different error there, but I'll get that posted if it doesn't work.
