### ISSUE TITLE
issue in importing quandl 

### ISSUE THREAD

**Issue by avanishceo** [jupyter/notebook#2874]
import quandl
output:
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-a585eb43abac> in <module>()
----> 1 import quandl
      2 

ModuleNotFoundError: No module named 'quandl'
i am using python jupyter

**Comment by takluyver** [comment]
Are you sure it's installed? Can you import it in Python if you're not using Jupyter? If so, what follows is a saved answer:


It sounds like you're trying an import in two different installations of Python, or two different environments. Check `sys.executable` to see which Python and environment you're running in, and `sys.path` to see where it looks to import modules.

Python packages must be installed separately for each copy of Python you use, and if you are using virtualenvs or conda envs, packages must be installed into each environment where you need them. Either the package is not installed in one, or a different version of the package is installed.

To install packages to a particular Python installation or environment using pip, you can run it like this:

```shell
path/to/python -m pip install ...
# Replace path/to/python with the path of the Python executable (sys.executable)
```

If you are using conda environments, you can install packages from conda like this:

```shell
source activate myenv  # On Windows, just 'activate myenv' (no 'source')
conda install ...
```

[ This is a saved reply because I answer similar questions often - sorry if it doesn't exactly fit your case ]

**Comment by NFA17SCM42J** [comment]
**I am facing the same issue though i have installed the quandl**..........

**Shell Error Message**
RESTART: C:\Users\niles\AppData\Local\Programs\Python\Python36-32\quandl.py 
Traceback (most recent call last):
  File "C:\Users\niles\AppData\Local\Programs\Python\Python36-32\quandl.py", line 1, in <module>
    import quandl
  File "C:\Users\niles\AppData\Local\Programs\Python\Python36-32\quandl.py", line 5, in <module>
    df=quandl.get('SF1/HD_REVENUE_MRQ',authtoken=api_key)
AttributeError: module 'quandl' has no attribute 'get'

**quandl Installation**

C:\Users\niles\AppData\Local\Programs\Python\Python36-32>pip install quandl
Requirement already satisfied: quandl in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages
Requirement already satisfied: numpy>=1.8 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from quandl)
Requirement already satisfied: requests>=2.7.0 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from quandl)
Requirement already satisfied: pyOpenSSL in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from quandl)
Requirement already satisfied: pyasn1 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from quandl)
Requirement already satisfied: pandas>=0.14 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from quandl)
Requirement already satisfied: more-itertools in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from quandl)
Requirement already satisfied: python-dateutil in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from quandl)
Requirement already satisfied: inflection>=0.3.1 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from quandl)
Requirement already satisfied: ndg-httpsclient in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from quandl)
Requirement already satisfied: six in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from quandl)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from requests>=2.7.0->quandl)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from requests>=2.7.0->quandl)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from requests>=2.7.0->quandl)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from requests>=2.7.0->quandl)
Requirement already satisfied: cryptography>=2.1.4 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from pyOpenSSL->quandl)
Requirement already satisfied: pytz>=2011k in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from pandas>=0.14->quandl)
Requirement already satisfied: asn1crypto>=0.21.0 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from cryptography>=2.1.4->pyOpenSSL->quandl)
Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from cryptography>=2.1.4->pyOpenSSL->quandl)
Requirement already satisfied: pycparser in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=2.1.4->pyOpenSSL->quandl)

C:\Users\niles\AppData\Local\Programs\Python\Python36-32>pip3 install quandl
Requirement already satisfied: quandl in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages
Requirement already satisfied: python-dateutil in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from quandl)
Requirement already satisfied: ndg-httpsclient in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from quandl)
Requirement already satisfied: pyasn1 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from quandl)
Requirement already satisfied: pyOpenSSL in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from quandl)
Requirement already satisfied: six in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from quandl)
Requirement already satisfied: requests>=2.7.0 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from quandl)
Requirement already satisfied: more-itertools in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from quandl)
Requirement already satisfied: numpy>=1.8 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from quandl)
Requirement already satisfied: inflection>=0.3.1 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from quandl)
Requirement already satisfied: pandas>=0.14 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from quandl)
Requirement already satisfied: cryptography>=2.1.4 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from pyOpenSSL->quandl)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from requests>=2.7.0->quandl)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from requests>=2.7.0->quandl)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from requests>=2.7.0->quandl)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from requests>=2.7.0->quandl)
Requirement already satisfied: pytz>=2011k in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from pandas>=0.14->quandl)
Requirement already satisfied: cffi>=1.7; platform_python_implementation != "PyPy" in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from cryptography>=2.1.4->pyOpenSSL->quandl)
Requirement already satisfied: asn1crypto>=0.21.0 in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from cryptography>=2.1.4->pyOpenSSL->quandl)
Requirement already satisfied: pycparser in c:\users\niles\appdata\local\programs\python\python36-32\lib\site-packages (from cffi>=1.7; platform_python_implementation != "PyPy"->cryptography>=2.1.4->pyOpenSSL->quandl)

**Comment by ProCoder183** [comment]
Ok so first got to the anaconda prompt type: install -c anaconda quandl, next  conda update jupyter, yes and now the quandl module will be installed  after run Jupiter notebook and in the jupyter script: import quandl it’s important to do it lower case.

**Comment by dexios1** [comment]
I came searching for answers and later realized I was just running the wrong conda environment; I'd installed Conda in another environment. 

Maybe this will help visitor # n.
