### ISSUE TITLE
sqlite database error forces server restart

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/notebook#2915]
I am opening, running, saving and closing a bunch of notebooks (dozens). After doing this for about 20-30 of them, I get an sqlite error making it impossible to save a notebook (have to restart the server).

<img width="781" alt="screen shot 2017-10-09 at 9 46 56 pm" src="https://user-images.githubusercontent.com/27600/31369792-a864dfc8-ad3b-11e7-8bf9-ed7d5672b25b.png">

```python
[E 21:46:52.609 LabApp] Error while saving file: github/altair-viz/altair_notebooks/notebooks/examples/stacked_bar_v.ipynb unable to open database file
    Traceback (most recent call last):
      File "/Users/bgranger/github/jupyter/notebook/notebook/services/contents/filemanager.py", line 444, in save
      File "/Users/bgranger/github/jupyter/notebook/notebook/services/contents/manager.py", line 444, in check_and_sign
      File "/Users/bgranger/anaconda/envs/python34/lib/python3.5/site-packages/nbformat/sign.py", line 447, in sign
      File "/Users/bgranger/anaconda/envs/python34/lib/python3.5/site-packages/nbformat/sign.py", line 209, in store_signature
    sqlite3.OperationalError: unable to open database file
[W 21:46:52.610 LabApp] Unexpected error while saving file: github/altair-viz/altair_notebooks/notebooks/examples/stacked_bar_v.ipynb
```

**Comment by gnestor** [comment]
@minrk Any ideas?

**Comment by minrk** [comment]
Can you include `conda list` and/or `pip list`? What version of nbformat do you have? Can you include more log output, including the last successful safe and the first failed one? Is this a local filesystem or NFS? Do you have more than one notebook server running?

**Comment by ellisonbg** [comment]
* looks like nbformat is 4.3.1. 
* This is a local filesystem (2014 Macbook with SSD)
* I don't think I had more than one notebook server running, but it is possible - that session is gone. I will keep my eye out to see if it shows up again.

Here are the packages:

```
_license                  1.1                      py34_0  
abstract-rendering        0.5.1                np19py34_0  
alabaster                 0.7.3                    py34_0  
alabaster                 0.7.10                    <pip>
alembic                   0.8.8                     <pip>
anaconda                  custom                   py35_0  
ansible                   1.9.4                     <pip>
appdirs                   1.4.3                     <pip>
appnope                   0.1.0                    py35_0  
appscript                 1.0.1                    py34_0  
argcomplete               0.8.9                    py34_0  
argparse                  1.4.0                     <pip>
args                      0.1.0                     <pip>
arrow                     0.8.0                     <pip>
asn1crypto                0.22.0                    <pip>
asn1crypto                0.22.0                   py35_0  
astroid                   1.5.3                     <pip>
astropy                   1.0.3                np19py34_0  
Babel                     2.4.0                     <pip>
babel                     1.3                      py34_0  
backports                 1.0                      py35_0  
backports.shutil_get_terminal_size 1.0.0                    py35_0    conda-forge
bash_kernel               0.4.1                     <pip>
bcolz                     0.9.0                np19py34_0  
beautiful-soup            4.3.2                    py34_0  
beautifulsoup4            4.5.1                     <pip>
binaryornot               0.4.0                     <pip>
binstar                   0.11.0                   py34_0  
bitarray                  0.8.1                    py34_0  
blaze-core                0.8.0                np19py34_0  
bleach                    2.0.0                     <pip>
blz                       0.6.2                np19py34_1  
bokeh                     0.10.0                   py35_0  
bokeh-0.12.3dev4-88       g50b3d45                  <pip>
boto                      2.38.0                   py34_0  
bottleneck                1.0.0                np19py34_0  
Bottleneck                1.2.0                     <pip>
bqplot                    0.6.1                     <pip>
bs4                       0.0.1                     <pip>
certifi                   2016.9.26                py35_0    conda-forge
cffi                      1.10.0                   py35_0  
cffi                      1.10.0                    <pip>
chainer                   1.4.1                     <pip>
chardet                   2.3.0                     <pip>
click                     6.6                       <pip>
clint                     0.5.1                     <pip>
cloudpickle               0.2.1                     <pip>
cloudpickle               0.2.2                    py35_0  
clyent                    0.3.4                    py34_0  
colorama                  0.3.3                    py34_0  
colorama                  0.3.7                     <pip>
CommonMark                0.5.4                     <pip>
configobj                 5.0.6                    py34_0  
cookiecutter              1.4.0                     <pip>
cookies                   2.2.1                     <pip>
cryptography              1.8.1                    py35_0  
cryptography              1.8.1                     <pip>
curl                      7.43.0                        0  
cycler                    0.10.0                    <pip>
cycler                    0.9.0                    py34_0    conda-forge
cython                    0.22.1                   py34_0  
cytoolz                   0.7.3                    py34_0  
dask                      0.15.0                   py35_0  
dask                      0.11.0                    <pip>
datashape                 0.4.5                np19py34_0  
decorator                 4.0.10                    <pip>
decorator                 4.0.11                    <pip>
decorator                 4.0.10                   py35_0    conda-forge
dill                      0.2.6                     <pip>
docutils                  0.12                     py34_0  
docutils                  0.13.1                    <pip>
dynd-python               0.6.5                np19py34_0  
ecdsa                     0.13                      <pip>
empyrical                 0.2.2                     <pip>
entrypoints               0.2.2                     <pip>
entrypoints               0.2.2                    py35_0    conda-forge
fastcache                 1.0.2                    py34_0  
filelock                  2.0.5                     <pip>
flask                     0.10.1                   py35_1  
freetype                  2.5.5                         0  
future                    0.16.0                    <pip>
geopy                     1.11.0                    <pip>
get_terminal_size         1.0.0                    py35_0  
gnureadline               6.3.3                     <pip>
greenlet                  0.4.7                    py34_0  
grin                      1.2.1                     <pip>
h5py                      2.7.0               np113py35_0  
hdf5                      1.8.17                        8    conda-forge
HeapDict                  1.0.0                     <pip>
html5lib                  0.999999999               <pip>
icu                       54.1                          0  
idna                      2.5                       <pip>
idna                      2.5                      py35_0  
imagesize                 0.7.1                     <pip>
inflection                0.3.1                     <pip>
invoke                    0.18.1                   py35_0    conda-forge
ipykernel                 4.3.1                     <pip>
ipykernel                 4.5.1                    py35_0    conda-forge
ipykernel                 4.6.1                     <pip>
ipyleaflet                0.2.0                     <pip>
ipython                   6.1.0                    py35_0    conda-forge
ipython-genutils          0.2.0                     <pip>
ipython-qtconsole         3.2.0                    py34_0  
ipython_genutils          0.1.0                    py35_0  
ipythonblocks             1.7.0                     <pip>
ipywidgets                5.2.2                    py35_2    conda-forge
isort                     4.2.15                    <pip>
itsdangerous              0.24                     py35_0  
jbig                      2.1                           0  
jdcal                     1.0                      py34_0  
jedi                      0.10.0                   py35_0    conda-forge
jedi                      0.10.2                    <pip>
jinja2                    2.8                      py35_1    conda-forge
Jinja2                    2.9.6                     <pip>
jinja2-time               0.2.0                     <pip>
joblib                    0.11                      <pip>
jpeg                      8d                            2    r
jsonschema                2.6.0                     <pip>
jsonschema                2.5.1                    py35_0    conda-forge
jupyter                   1.0.0                    py35_3  
jupyter-client            5.0.1                     <pip>
jupyter-client            4.1.1                     <pip>
jupyter-core              4.3.0                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter-dashboards        0.5.0                     <pip>
jupyter-lightsaber        1.0.5                     <pip>
jupyter-lightsaber-yoda   1.0.5                     <pip>
jupyter-tree-filter       1.4.1                     <pip>
jupyter_client            4.4.0                    py35_0    conda-forge
jupyter_console           5.0.0                    py35_0    conda-forge
jupyter_core              4.2.0                    py35_0    conda-forge
jupyterlab-launcher       0.4.0                     <pip>
Keras                     1.2.2                     <pip>
keras                     2.0.6                    py35_0    conda-forge
launcher                  1.0.0                         3  
lazy-object-proxy         1.3.1                     <pip>
libdynd                   0.6.5                         0  
libgcc                    4.8.5                         1    r
libgfortran               3.0.0                         0    conda-forge
libpng                    1.6.17                        0  
libsodium                 1.0.10                        0    conda-forge
libtiff                   4.0.6                         1  
libxml2                   2.9.2                         1    r
libxslt                   1.1.28                        2  
lightning-python          1.2.1                     <pip>
llvmlite                  0.5.0                    py34_0  
locket                    0.2.0                     <pip>
locket                    0.2.0                    py35_1  
lxml                      3.4.4                    py34_0  
Mako                      1.0.6                     <pip>
markdown2                 2.3.4                     <pip>
markupsafe                0.23                     py35_2  
MarkupSafe                1.0                       <pip>
matplotlib                2.0.0                     <pip>
mccabe                    0.6.1                     <pip>
medium                    0.3.0                     <pip>
mistune                   0.7.3                    py35_1  
mistune                   0.7.4                     <pip>
mkl                       2017.0.3                      0  
mock                      2.0.0                    py35_0    conda-forge
more-itertools            3.0.0                     <pip>
msgpack-python            0.4.8                     <pip>
multipledispatch          0.4.8                     <pip>
multipledispatch          0.4.7                    py34_0  
mypy                      0.470                     <pip>
nbconvert                 5.1.1                     <pip>
nbconvert                 4.2.0                    py35_0    conda-forge
nbdime                    0.2.0.dev0                <pip>
nbformat                  4.3.0                     <pip>
nbformat                  4.1.0                    py35_0    conda-forge
nbsphinx                  0.2.13                    <pip>
ncurses                   5.9                           1    r
ndg-httpsclient           0.4.2                     <pip>
networkx                  1.10                     py35_0  
nlopt                     2.4.2                         1    r
nltk                      3.0.3                np19py34_0  
node-webkit               0.10.1                        0  
nose                      1.3.7                    py35_1  
nose                      1.3.7                     <pip>
notebook                  5.0.0                    py35_0    conda-forge
numba                     0.19.1               np19py34_0  
numexpr                   2.4.3                np19py34_0  
numexpr                   2.5.2                     <pip>
numpy                     1.12.0                    <pip>
numpy                     1.13.1                   py35_0  
numpy                     1.11.0                    <pip>
numpydoc                  0.6.0                     <pip>
odo                       0.3.2                np19py34_0  
openpyxl                  1.8.5                    py34_0  
openssl                   1.0.2j                        0  
packaging                 16.8                     py35_0  
packaging                 16.8                      <pip>
palettable                2.1.1                     <pip>
pamela                    0.2.1                     <pip>
pandas                    0.20.2              np113py35_0  
pandas-datareader         0.3.0.post0               <pip>
pandocfilters             1.4.1                     <pip>
paramiko                  1.16.0                    <pip>
partd                     0.3.8                    py35_0  
path.py                   8.1.2                     <pip>
path.py                   8.2.1                    py35_0  
patsy                     0.4.1                     <pip>
patsy                     0.3.0                np19py34_0  
pbr                       1.10.0                   py35_0    conda-forge
pcre                      8.31                          0  
pep8                      1.6.2                    py34_0  
pexpect                   4.2.0                     <pip>
pexpect                   4.0.1                     <pip>
pexpect                   4.2.1                    py35_0    conda-forge
pickleshare               0.7.4                    py35_0  
pickleshare               0.7.2                     <pip>
pillow                    3.0.0                    py35_0  
pip                       9.0.1                    py35_1  
pkginfo                   1.4.1                     <pip>
plotly                    1.9.10                    <pip>
ply                       3.6                      py34_0  
poyo                      0.4.0                     <pip>
prompt-toolkit            1.0.14                    <pip>
prompt-toolkit            1.0.3                     <pip>
prompt_toolkit            1.0.9                    py35_0    conda-forge
protobuf                  3.2.0                     <pip>
protobuf                  2.6.1                     <pip>
protobuf                  3.0.0                    py35_0    conda-forge
psutil                    5.2.2                    py35_0  
psutil                    4.3.1                     <pip>
ptyprocess                0.5.1                     <pip>
ptyprocess                0.5.1                    py35_0    conda-forge
py                        1.4.34                    <pip>
py                        1.4.27                   py34_0  
pyarrow                   0.7.1                     <pip>
pyasn1                    0.2.3                     <pip>
pyasn1                    0.2.3                    py35_0  
pycosat                   0.6.1                    py34_0  
pycparser                 2.17                      <pip>
pycparser                 2.17                     py35_0  
pycrypto                  2.6.1                     <pip>
pycrypto                  2.6.1                    py34_0  
pycurl                    7.19.5.1                 py34_2  
pyenchant                 1.6.8                     <pip>
pyflakes                  0.9.2                    py34_0  
pyflakes                  1.0.0                     <pip>
pyfolio                   0.7.0                     <pip>
PyGithub                  1.29                      <pip>
Pygments                  2.1.3                     <pip>
pygments                  2.1.3                    py35_1    conda-forge
Pygments                  2.2.0                     <pip>
pylint                    1.7.2                     <pip>
pymc3                     3.0                       <pip>
pymysql                   0.6.6                    py35_0  
pyopenssl                 17.0.0                   py35_0  
pyOpenSSL                 17.0.0                    <pip>
pyparsing                 2.2.0                     <pip>
pyparsing                 2.0.3                    py35_0  
pyqt                      5.6.0                    py35_0  
pytables                  3.2.0                np19py34_0  
pytest                    3.2.2                     <pip>
pytest                    2.7.1                    py34_0  
python                    3.5.2                         3    conda-forge
python-dateutil           2.5.3                     <pip>
python-dateutil           2.6.0                    py35_0    conda-forge
python-editor             1.0.1                     <pip>
python-oauth2             1.0.1                     <pip>
python.app                1.2                      py35_4  
pythonwhat                2.6.0                     <pip>
pythreejs                 0.2.0b2                   <pip>
pytz                      2016.7                    <pip>
pytz                      2016.7                   py35_0    conda-forge
pytz                      2017.2                    <pip>
pyyaml                    3.12                     py35_0  
pyzmq                     15.1.0                    <pip>
pyzmq                     16.0.2                   py35_0    conda-forge
qt                        5.6.0                         0  
qtconsole                 4.2.1                    py35_0    conda-forge
Quandl                    3.1.0                     <pip>
quilt                     2.7.0                     <pip>
r-assertthat              0.1                   r3.2.2_2a    r
r-base                    3.2.2                         0    r
r-base64enc               0.1_3                 r3.2.2_0a    r
r-bh                      1.58.0_1              r3.2.2_0a    r
r-bitops                  1.0_6                 r3.2.2_2a    r
r-boot                    1.3_17                r3.2.2_0a    r
r-bradleyterry2           1.0_6                  r3.2.2_2    r
r-brglm                   0.5_9                  r3.2.2_2    r
r-car                     2.1_0                 r3.2.2_0a    r
r-caret                   6.0_62                r3.2.2_0a    r
r-catools                 1.17.1                r3.2.2_2a    r
r-chron                   2.3_47                r3.2.2_0a    r
r-class                   7.3_14                r3.2.2_0a    r
r-cluster                 2.0.3                 r3.2.2_0a    r
r-codetools               0.2_14                r3.2.2_0a    r
r-colorspace              1.2_6                 r3.2.2_0a    r
r-data.table              1.9.6                 r3.2.2_0a    r
r-dbi                     0.3.1                 r3.2.2_3a    r
r-dichromat               2.0_0                 r3.2.2_3a    r
r-digest                  0.6.8                 r3.2.2_3a    r
r-dplyr                   0.4.3                 r3.2.2_0a    r
r-essentials              1.1                   r3.2.2_1a    r
r-evaluate                0.8                   r3.2.2_0a    r
r-foreach                 1.4.3                 r3.2.2_0a    r
r-foreign                 0.8_66                r3.2.2_0a    r
r-formatr                 1.2.1                 r3.2.2_0a    r
r-ggplot2                 1.0.1                 r3.2.2_0a    r
r-glmnet                  2.0_2                 r3.2.2_0a    r
r-gtable                  0.1.2                 r3.2.2_3a    r
r-gtools                  3.5.0                  r3.2.2_0    r
r-hexbin                  1.27.1                r3.2.2_0a    r
r-highr                   0.5.1                 r3.2.2_0a    r
r-htmltools               0.2.6                 r3.2.2_2a    r
r-htmlwidgets             0.5                   r3.2.2_0a    r
r-httpuv                  1.3.3                 r3.2.2_0a    r
r-irdisplay               0.3                   r3.2.2_0a    r
r-irkernel                0.5                    r3.2.2_2    r
r-iterators               1.0.8                 r3.2.2_0a    r
r-jsonlite                0.9.17                r3.2.2_0a    r
r-kernsmooth              2.23_15               r3.2.2_0a    r
r-knitr                   1.11                  r3.2.2_0a    r
r-labeling                0.3                   r3.2.2_2a    r
r-lattice                 0.20_33               r3.2.2_0a    r
r-lazyeval                0.1.10                r3.2.2_3a    r
r-lme4                    1.1_10                r3.2.2_0a    r
r-magrittr                1.5                   r3.2.2_2a    r
r-maps                    3.0.0_2               r3.2.2_0a    r
r-markdown                0.7.7                 r3.2.2_1a    r
r-mass                    7.3_45                r3.2.2_0a    r
r-matrix                  1.2_2                 r3.2.2_0a    r
r-matrixmodels            0.4_1                 r3.2.2_0a    r
r-mgcv                    1.8_9                 r3.2.2_0a    r
r-mime                    0.4                   r3.2.2_0a    r
r-minqa                   1.2.4                 r3.2.2_1a    r
r-munsell                 0.4.2                 r3.2.2_2a    r
r-nlme                    3.1_122               r3.2.2_0a    r
r-nloptr                  1.0.4                 r3.2.2_2a    r
r-nnet                    7.3_11                r3.2.2_0a    r
r-pbkrtest                0.4_2                 r3.2.2_2a    r
r-plyr                    1.8.3                 r3.2.2_0a    r
r-profilemodel            0.5_9                  r3.2.2_2    r
r-proto                   0.3_10                r3.2.2_2a    r
r-quantmod                0.4_5                 r3.2.2_0a    r
r-quantreg                5.19                  r3.2.2_0a    r
r-r6                      2.1.1                 r3.2.2_0a    r
r-randomforest            4.6_12                r3.2.2_0a    r
r-rbokeh                  0.2.2                 r3.2.2_0a    r
r-rcolorbrewer            1.1_2                 r3.2.2_3a    r
r-rcpp                    0.12.2                r3.2.2_0a    r
r-rcppeigen               0.3.2.5.1             r3.2.2_0a    r
r-recommended             3.2.2                  r3.2.2_0    r
r-repr                    0.3                   r3.2.2_0a    r
r-reshape2                1.4.1                 r3.2.2_2a    r
r-rjsonio                 1.3_0                 r3.2.2_1a    r
r-rmarkdown               0.8.1                 r3.2.2_0a    r
r-rpart                   4.1_10                r3.2.2_0a    r
r-rzmq                    0.7.7                 r3.2.2_2a    r
r-scales                  0.3.0                 r3.2.2_0a    r
r-shiny                   0.12.2                r3.2.2_0a    r
r-sparsem                 1.7                   r3.2.2_0a    r
r-spatial                 7.3_11                r3.2.2_0a    r
r-stringi                 1.0_1                 r3.2.2_0a    r
r-stringr                 1.0.0                 r3.2.2_0a    r
r-survival                2.38_3                r3.2.2_0a    r
r-tidyr                   0.3.1                 r3.2.2_0a    r
r-ttr                     0.23_0                r3.2.2_0a    r
r-uuid                    0.1_2                 r3.2.2_0a    r
r-xtable                  1.8_0                 r3.2.2_0a    r
r-xts                     0.9_7                 r3.2.2_0a    r
r-yaml                    2.1.13                r3.2.2_1a    r
r-zoo                     1.7_12                r3.2.2_1a    r
readline                  6.2                           2  
recommonmark              0.4.0                     <pip>
redis                     2.6.9                         0  
redis-py                  2.10.3                   py34_0  
requests                  2.13.0                    <pip>
requests                  2.8.1                    py35_0  
requests-file             1.4.2                     <pip>
requests-ftp              0.3.1                     <pip>
requests-toolbelt         0.7.1                     <pip>
responses                 0.6.0                     <pip>
rope                      0.9.4                    py34_1  
runipy                    0.1.3                    py34_0  
scikit-image              0.11.3               np19py35_0  
scikit-learn              0.18.2              np113py35_0  
scipy                     0.19.0                    <pip>
scipy                     0.19.1              np113py35_0  
seaborn                   0.6.0                np19py35_0  
seaborn                   0.7.1                     <pip>
setuptools                24.0.2                    <pip>
setuptools                36.5.0                    <pip>
setuptools                32.3.0                   py35_0    conda-forge
simplegeneric             0.8.1                    py35_1  
sip                       4.18                     py35_0    conda-forge
six                       1.10.0                   py35_1    conda-forge
snowballstemmer           1.2.1                     <pip>
snowballstemmer           1.2.0                    py34_0  
sockjs-tornado            1.0.1                    py34_0  
Sphinx                    1.5.5                     <pip>
sphinx                    1.3.1                    py34_0  
sphinx-rtd-theme          0.1.9                     <pip>
sphinx_rtd_theme          0.1.7                    py34_0  
spyder                    2.3.5.2                  py34_0  
spyder-app                2.3.5.2                  py34_0  
SQLAlchemy                1.0.11                    <pip>
sqlalchemy                1.0.5                    py34_0  
sqlite                    3.13.0                        1    conda-forge
statsmodels               0.6.1                np19py34_0  
statsmodels               0.8.0                     <pip>
sympy                     0.7.6                    py34_0  
sympy                     0.7.6.1                   <pip>
tables                    3.4.2                     <pip>
tblib                     1.3.0                     <pip>
tensorflow                1.0.0                     <pip>
tensorflow                0.12.1                   py35_0    conda-forge
terminado                 0.6                      py35_0    conda-forge
testpath                  0.3                       <pip>
theano                    0.8.2                    py35_0    conda-forge
tk                        8.5.19                        1    conda-forge
toolz                     0.8.0                     <pip>
toolz                     0.8.2                    py35_0  
tornado                   4.3                       <pip>
tornado                   4.5.1                     <pip>
tornado                   4.4.2                    py35_0    conda-forge
tqdm                      4.11.2                    <pip>
traitlets                 4.3.1                    py35_0    conda-forge
traitlets                 4.2.1                     <pip>
traitlets                 4.2.2                     <pip>
traitlets                 4.3.2                     <pip>
twine                     1.8.1                     <pip>
typed-ast                 0.6.3                     <pip>
ujson                     1.33                     py34_0  
vega                      0.4.4                    py35_1    conda-forge
wcwidth                   0.1.7                    py35_0    conda-forge
wcwidth                   0.1.7                     <pip>
webencodings              0.5.1                     <pip>
werkzeug                  0.10.4                   py35_0  
wheel                     0.29.0                   py35_0  
whichcraft                0.4.0                     <pip>
widgetsnbextension        1.2.6                    py35_3    conda-forge
wrapt                     1.10.11                   <pip>
xlrd                      1.1.0                     <pip>
xlrd                      0.9.3                    py34_0  
xlsxwriter                0.7.3                    py34_0  
xlwings                   0.3.5                    py34_0  
xlwt                      1.0.0                    py34_0  
xz                        5.2.2                         1  
yaml                      0.1.6                         0  
zeromq                    4.1.5                         0    conda-forge
zict                      0.0.3                     <pip>
zlib                      1.2.8                         3  
```
