### ISSUE TITLE
Weird error starting jupyter notebook / conflict with other Python application

### ISSUE THREAD

**Issue by 0x6d636c61757373** [jupyter/notebook#2926]
Hi!

I just installed jupyter and wanted to run `jupyter notebook` when I got this error message:

```
$ jupyter notebook
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1364, in initialize
    self.init_webapp()
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 1157, in init_webapp
    self.jinja_environment_options
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 154, in __init__
    base_url, default_url, settings_overrides, jinja_env_options)
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 263, in init_settings
    nbextensions_path=jupyter_app.nbextensions_path,
  File "/usr/local/lib/python3.5/dist-packages/notebook/notebookapp.py", line 870, in nbextensions_path
    from IPython.paths import get_ipython_dir
  File "/usr/local/lib/python3.5/dist-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/usr/local/lib/python3.5/dist-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/usr/local/lib/python3.5/dist-packages/IPython/terminal/interactiveshell.py", line 91, in <module>
    class TerminalInteractiveShell(InteractiveShell):
  File "/usr/local/lib/python3.5/dist-packages/IPython/terminal/interactiveshell.py", line 134, in TerminalInteractiveShell
    highlighting: \n %s""" % ', '.join(get_all_styles())
  File "/usr/local/lib/python3.5/dist-packages/pygments/styles/__init__.py", line 79, in get_all_styles
    for name, _ in find_plugin_styles():
  File "/usr/local/lib/python3.5/dist-packages/pygments/plugin.py", line 63, in find_plugin_styles
    yield entrypoint.name, entrypoint.load()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/someuser/.local/lib/python3.5/site-packages/voltron/__init__.py", line 95, in <module>
    setup_env()
  File "/home/someuser/.local/lib/python3.5/site-packages/voltron/__init__.py", line 31, in setup_env
    pkg_plugins=PluginDirectory('plugins', parent=PackageDirectory())
  File "/home/someuser/.local/lib/python3.5/site-packages/scruffy/env.py", line 47, in __init__
    self.add(**kwargs)
  File "/home/someuser/.local/lib/python3.5/site-packages/scruffy/env.py", line 112, in add
    self._children[key].prepare()
  File "/home/someuser/.local/lib/python3.5/site-packages/scruffy/file.py", line 437, in prepare
    self.load()
  File "/home/someuser/.local/lib/python3.5/site-packages/scruffy/file.py", line 443, in load
    self._pm.load_plugins(self.path)
  File "/home/someuser/.local/lib/python3.5/site-packages/scruffy/plugin.py", line 65, in load_plugins
    self.load_plugins(filepath)
  File "/home/someuser/.local/lib/python3.5/site-packages/scruffy/plugin.py", line 61, in load_plugins
    mod = imp.load_module(modname, file, path, descr)
  File "/usr/lib/python3.5/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "/home/someuser/.local/lib/python3.5/site-packages/voltron/plugins/debugger/dbg_gdb.py", line 663, in <module>
    class GDBCommand(DebuggerCommand, gdb.Command):
AttributeError: module 'gdb' has no attribute 'Command'
```

This is very weird... when I `mv` `voltron` out of `/home/someuser/.local/lib/python3.5/site-packages/` it works. voltron is another python application (https://github.com/snare/voltron)
Interestingly the other files and directories cause no problem:

```
$ ls /home/someuser/.local/lib/python3.5/site-packages/
aniso8601                  flask                          itsdangerous-0.24.dist-info  pysigset.py            requests_unixsocket                  voltron                       werkzeug
aniso8601-1.3.0.dist-info  Flask-0.12.2.dist-info         itsdangerous.py              pytz                   requests_unixsocket-0.1.5.dist-info  voltron-0.1.7-py3.5.egg-info  Werkzeug-0.12.2.dist-info
blessed                    flask_restful                  __pycache__                  pytz-2017.2.dist-info  scruffington-0.3.7.dist-info         wcwidth                       yaml
blessed-1.14.2.dist-info   Flask_RESTful-0.3.6.dist-info  pysigset-0.3.2.dist-info     PyYAML-3.12.dist-info  scruffy                              wcwidth-0.1.7.dist-info
```

Thanks!

**Comment by takluyver** [comment]
Thanks, that's a pointer that we're doing something we shouldn't be in IPython. ipython/ipython#10859 ought to fix it.

Packages can provide plugins for the pygments syntax highlighter to offer extra highlighting styles (among other things). It appears voltron provides a pygments style plugin. IPython uses pygments, and for a help string it tries to get a list of the available styles, which causes pygments to load them all. In your case, there's a problem with the style from voltron, so you see an error. But this is also a bad idea generally, because finding and loading plugins can be quite slow.
