### ISSUE TITLE
"Kernel busy" or "no connection to kernel"

### ISSUE THREAD

**Issue by ZaRaSm** [jupyter/notebook#2990]
Hello,
I installed python 3.6 (32 bit) , Anaconda 3 (64 bit) on Win 7 (64 bit ).
I run the Jupiter notebook on anaconda but the only thing that happen is appearing [*] near the code lines and I can see the error "Kernel busy" or "no connection to kernel".

Could you please let me know, how can I fix it ? Thank you

**Comment by takluyver** [comment]
Are there any error messages in the command prompt when you're running Jupyter?

**Comment by ZaRaSm** [comment]
This is my Anaconda Promt when I am running Jupyter.

![anaconda](https://user-images.githubusercontent.com/33186024/32268320-dbb2fa58-beee-11e7-82c9-74b58d8d8158.jpg)

**Comment by takluyver** [comment]
😕 there's nothing obviously wrong there. How about in the browser's Javascript console?

**Comment by ZaRaSm** [comment]
This is the Error that appears in the console ! :(

![anaconda01](https://user-images.githubusercontent.com/33186024/32300093-4568fd94-bf58-11e7-9ec7-f042ec66d266.jpg)

**Comment by takluyver** [comment]
Hmm, that doesn't give many clues either. Do you have some kind of internet security software on your computer? Some kinds of security software have caused problems for the notebook before.

**Comment by ZaRaSm** [comment]
Yes, I have ESET Internet Security. I have tried to run Anaconda while my internet security software is disabled, but I still have problem with it  :( !

**Comment by takluyver** [comment]
Try switching localhost in the URL with 127.0.0.1 - sometimes that gets
round some security block. But I'm running out of ideas to suggest.

**Comment by ZaRaSm** [comment]
I very appreciate for your help. I try it but it doesn't work!

**Comment by nash5** [comment]
Even I had this bug for many days. I tried several methods but neither worked. 

The only solution I found was by resetting the system(I took a backup of most wanted apps) and install the application.

Obviously it works!

**Comment by 392781** [comment]
Wonderful solutions.  Unfortunately buying a new laptop is not an option for me.  Any fixes here?  I cannot connect to kernel either.  Have the exact same symptoms as well.

**Comment by kevin-bates** [comment]
You're probably getting bit by the recent tornado 6 release and the flurry of issues that has caused. Try downgrading tornado (if you find you're using 6).

**Comment by 392781** [comment]
@kevin-bates thanks, downgrading to tornado 5.1.1 fixed it.  Funny to see an update on tornado wrecking havoc ;^)

**Comment by petrwaldauf** [comment]
> @kevin-bates thanks, downgrading to tornado 5.1.1 fixed it. Funny to see an update on tornado wrecking havoc ;^)

Thank you Kevin this fixed it!!!!

**Comment by AnakTeka** [comment]
> You're probably getting bit by the recent tornado 6 release and the flurry of issues that has caused. Try downgrading tornado (if you find you're using 6).

Thank you for the suggestion, I'm having the same problem and downgrading tornado fixed the problem

**Comment by Yaroslav00** [comment]
Thank you a lot for this suggestion

**Comment by LeithanK** [comment]
Thanks @kevin-bates !
`pip install tornado==5.1.1` fixed this.

**Comment by ana1239** [comment]
I still have the same problem, downgrading tornado didn't fix it. Help me please ;(
Do you have any other suggestions? 
![error](https://user-images.githubusercontent.com/48262590/53840566-854ec400-3fab-11e9-870b-b0f4db90cf34.JPG)

**Comment by 392781** [comment]
@ana1239

Any errors happening in terminal?

**Comment by ana1239** [comment]
> @ana1239 Any errors happening in terminal?

everything works fine exept for the kernel

**Comment by mhghodsi** [comment]
> Thanks @kevin-bates !
> `pip install tornado==5.1.1` fixed this.

wow! This solved my problem. Thank you!

**Comment by rsuraparaju** [comment]
> You're probably getting bit by the recent tornado 6 release and the flurry of issues that has caused. Try downgrading tornado (if you find you're using 6).

Thanks Kevin! This worked.

**Comment by deepchatterjeevns** [comment]
> You're probably getting bit by the recent tornado 6 release and the flurry of issues that has caused. Try downgrading tornado (if you find you're using 6).

Thanks, @kevin-bates! It worked.

**Comment by sanjaykumardabli** [comment]
How to download tornado

**Comment by nani-samireddy** [comment]
Kernel does not exist: b41f0b9f-e2dd-4a72-94f1-b1cdfc061c86
after the above solution also int is not working to me
like above errors
and this is the full log
[I 14:12:36.081 NotebookApp] JupyterLab extension loaded from C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab
[I 14:12:36.081 NotebookApp] JupyterLab application directory is C:\ProgramData\Anaconda3\share\jupyter\lab
[I 14:12:36.645 NotebookApp] Serving notebooks from local directory: C:\Users\NANI
[I 14:12:36.653 NotebookApp] The Jupyter Notebook is running at:
[I 14:12:36.653 NotebookApp] http://localhost:8889/?token=19e4cb4a419a4dc8a79f175ad4c6f2d2ba43a722664afc6c
[I 14:12:36.653 NotebookApp]  or http://127.0.0.1:8889/?token=19e4cb4a419a4dc8a79f175ad4c6f2d2ba43a722664afc6c
[I 14:12:36.653 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:12:36.877 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/NANI/AppData/Roaming/jupyter/runtime/nbserver-1092-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/?token=19e4cb4a419a4dc8a79f175ad4c6f2d2ba43a722664afc6c
     or http://127.0.0.1:8889/?token=19e4cb4a419a4dc8a79f175ad4c6f2d2ba43a722664afc6c
[I 14:12:58.999 NotebookApp] Kernel started: b41f0b9f-e2dd-4a72-94f1-b1cdfc061c86
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<C:\ProgramData\Anaconda3\lib\site-packages\decorator.py:decorator-gen-125>", line 2, in initialize
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 562, in initialize
    self.init_kernel()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 447, in init_kernel
    user_ns=self.user_ns,
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 68, in __init__
    kernel      = self,
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 687, in __init__
    self.init_magics()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 593, in init_magics
    super(ZMQInteractiveShell, self).init_magics()
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2250, in init_magics
    m.PylabMagics, m.ScriptMagics,
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\magic.py", line 405, in register
    m = m(shell=self.shell)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\magics\osm.py", line 52, in __init__
    self.execre = re.compile(r'(.*)\.(%s)$' % winext,re.IGNORECASE)
  File "C:\ProgramData\Anaconda3\lib\re.py", line 234, in compile
    return _compile(pattern, flags)
  File "C:\ProgramData\Anaconda3\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\ProgramData\Anaconda3\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 924, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 810, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 501, in _parse
    code = _escape(source, this, state)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 369, in _escape
    raise source.error("incomplete escape %s" % escape, len(escape))
re.error: incomplete escape \U at position 52
[I 14:13:01.966 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<C:\ProgramData\Anaconda3\lib\site-packages\decorator.py:decorator-gen-125>", line 2, in initialize
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 562, in initialize
    self.init_kernel()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 447, in init_kernel
    user_ns=self.user_ns,
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 68, in __init__
    kernel      = self,
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 687, in __init__
    self.init_magics()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 593, in init_magics
    super(ZMQInteractiveShell, self).init_magics()
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2250, in init_magics
    m.PylabMagics, m.ScriptMagics,
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\magic.py", line 405, in register
    m = m(shell=self.shell)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\magics\osm.py", line 52, in __init__
    self.execre = re.compile(r'(.*)\.(%s)$' % winext,re.IGNORECASE)
  File "C:\ProgramData\Anaconda3\lib\re.py", line 234, in compile
    return _compile(pattern, flags)
  File "C:\ProgramData\Anaconda3\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\ProgramData\Anaconda3\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 924, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 810, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 501, in _parse
    code = _escape(source, this, state)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 369, in _escape
    raise source.error("incomplete escape %s" % escape, len(escape))
re.error: incomplete escape \U at position 52
[I 14:13:05.004 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<C:\ProgramData\Anaconda3\lib\site-packages\decorator.py:decorator-gen-125>", line 2, in initialize
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 562, in initialize
    self.init_kernel()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 447, in init_kernel
    user_ns=self.user_ns,
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 68, in __init__
    kernel      = self,
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 687, in __init__
    self.init_magics()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 593, in init_magics
    super(ZMQInteractiveShell, self).init_magics()
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2250, in init_magics
    m.PylabMagics, m.ScriptMagics,
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\magic.py", line 405, in register
    m = m(shell=self.shell)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\magics\osm.py", line 52, in __init__
    self.execre = re.compile(r'(.*)\.(%s)$' % winext,re.IGNORECASE)
  File "C:\ProgramData\Anaconda3\lib\re.py", line 234, in compile
    return _compile(pattern, flags)
  File "C:\ProgramData\Anaconda3\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\ProgramData\Anaconda3\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 924, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 810, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 501, in _parse
    code = _escape(source, this, state)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 369, in _escape
    raise source.error("incomplete escape %s" % escape, len(escape))
re.error: incomplete escape \U at position 52
[I 14:13:08.048 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<C:\ProgramData\Anaconda3\lib\site-packages\decorator.py:decorator-gen-125>", line 2, in initialize
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 562, in initialize
    self.init_kernel()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 447, in init_kernel
    user_ns=self.user_ns,
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 68, in __init__
    kernel      = self,
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 687, in __init__
    self.init_magics()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 593, in init_magics
    super(ZMQInteractiveShell, self).init_magics()
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2250, in init_magics
    m.PylabMagics, m.ScriptMagics,
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\magic.py", line 405, in register
    m = m(shell=self.shell)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\magics\osm.py", line 52, in __init__
    self.execre = re.compile(r'(.*)\.(%s)$' % winext,re.IGNORECASE)
  File "C:\ProgramData\Anaconda3\lib\re.py", line 234, in compile
    return _compile(pattern, flags)
  File "C:\ProgramData\Anaconda3\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\ProgramData\Anaconda3\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 924, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 810, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 501, in _parse
    code = _escape(source, this, state)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 369, in _escape
    raise source.error("incomplete escape %s" % escape, len(escape))
re.error: incomplete escape \U at position 52
[I 14:13:11.089 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<C:\ProgramData\Anaconda3\lib\site-packages\decorator.py:decorator-gen-125>", line 2, in initialize
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 562, in initialize
    self.init_kernel()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 447, in init_kernel
    user_ns=self.user_ns,
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 68, in __init__
    kernel      = self,
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 687, in __init__
    self.init_magics()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 593, in init_magics
    super(ZMQInteractiveShell, self).init_magics()
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2250, in init_magics
    m.PylabMagics, m.ScriptMagics,
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\magic.py", line 405, in register
    m = m(shell=self.shell)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\magics\osm.py", line 52, in __init__
    self.execre = re.compile(r'(.*)\.(%s)$' % winext,re.IGNORECASE)
  File "C:\ProgramData\Anaconda3\lib\re.py", line 234, in compile
    return _compile(pattern, flags)
  File "C:\ProgramData\Anaconda3\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\ProgramData\Anaconda3\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 924, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 810, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 420, in _parse_sub
    not nested and not items))
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 501, in _parse
    code = _escape(source, this, state)
  File "C:\ProgramData\Anaconda3\lib\sre_parse.py", line 369, in _escape
    raise source.error("incomplete escape %s" % escape, len(escape))
re.error: incomplete escape \U at position 52
[W 14:13:14.114 NotebookApp] KernelRestarter: restart failed
[W 14:13:14.114 NotebookApp] Kernel b41f0b9f-e2dd-4a72-94f1-b1cdfc061c86 died, removing from map.
[W 14:13:59.084 NotebookApp] Timeout waiting for kernel_info reply from b41f0b9f-e2dd-4a72-94f1-b1cdfc061c86
[E 14:13:59.084 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: b41f0b9f-e2dd-4a72-94f1-b1cdfc061c86)
[W 14:14:00.142 NotebookApp] 404 GET /api/kernels/b41f0b9f-e2dd-4a72-94f1-b1cdfc061c86/channels?session_id=c0d76dd1f83349d287576e3d1bee99fd (::1): Kernel does not exist: b41f0b9f-e2dd-4a72-94f1-b1cdfc061c86
[W 14:14:00.174 NotebookApp] 404 GET /api/kernels/b41f0b9f-e2dd-4a72-94f1-b1cdfc061c86/channels?session_id=c0d76dd1f83349d287576e3d1bee99fd (::1) 39.98ms referer=None
[W 14:14:02.214 NotebookApp] Replacing stale connection: b41f0b9f-e2dd-4a72-94f1-b1cdfc061c86:c0d76dd1f83349d287576e3d1bee99fd


help me with this

**Comment by kevin-bates** [comment]
Hi @nani-samireddy - this is coming from the ipykernel startup sequence and not an issue for this repository.  However, looking at the [applicable code](https://github.com/ipython/ipython/blob/master/IPython/core/magics/osm.py#L48-L60) it appears to be trying to decipher the value of your `PATHEXT` environment variable and I suggest following the instructions starting with this [comment](https://github.com/ipython/ipython/issues/12002#issuecomment-561751246).

Should there be nothing obvious from examining the value of `PATHEXT`, I suggest opening an issue in the IPython repo duplicating the contents of your comment above.
