### ISSUE TITLE
Jupyter 4 Can't Find My Anaconda Python 3 Repo

### ISSUE THREAD

**Issue by chrisalbon** [jupyter/notebook#300]
I `conda update ipython` and `conda install jupyter` without a problem. Then I opened jupyter with `jupyter notebook` without issue. Then, immediately, I get a kernel error saying it cannot find my Py3 kernel (see trackback below), however my Py3 kernel is my Anaconda root environment (`/Users/chrisralbon/anaconda`) not where it thinks, at `/Users/chrisralbon/anaconda/envs/py3k/bin/python`. I am not sure why it is looking there.

```python
Traceback (most recent call last):
  File "/Users/chrisralbon/anaconda/lib/python3.4/site-packages/notebook/base/handlers.py", line 436, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/Users/chrisralbon/anaconda/lib/python3.4/site-packages/notebook/services/sessions/handlers.py", line 56, in post
    model = sm.create_session(path=path, kernel_name=kernel_name)
  File "/Users/chrisralbon/anaconda/lib/python3.4/site-packages/notebook/services/sessions/sessionmanager.py", line 66, in create_session
    kernel_name=kernel_name)
  File "/Users/chrisralbon/anaconda/lib/python3.4/site-packages/notebook/services/kernels/kernelmanager.py", line 84, in start_kernel
    **kwargs)
  File "/Users/chrisralbon/anaconda/lib/python3.4/site-packages/jupyter_client/multikernelmanager.py", line 109, in start_kernel
    km.start_kernel(**kwargs)
  File "/Users/chrisralbon/anaconda/lib/python3.4/site-packages/jupyter_client/manager.py", line 239, in start_kernel
    **kw)
  File "/Users/chrisralbon/anaconda/lib/python3.4/site-packages/jupyter_client/manager.py", line 186, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/Users/chrisralbon/anaconda/lib/python3.4/site-packages/jupyter_client/launcher.py", line 119, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/Users/chrisralbon/anaconda/lib/python3.4/subprocess.py", line 859, in __init__
    restore_signals, start_new_session)
  File "/Users/chrisralbon/anaconda/lib/python3.4/subprocess.py", line 1457, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/chrisralbon/anaconda/envs/py3k/bin/python'
```

**Comment by Carreau** [comment]
Can you try a `python -m IPython kernelspec install-self` to reinstall the kernelspec ?

**Comment by chrisalbon** [comment]
Sweet, python -m IPython kernelspec install-self totally fixed it. Tests working perfectly now.

**Comment by Carreau** [comment]
Great ! Closing.

**Comment by amysjsj** [comment]
So sweet!  Working perfectly now!  Thanks Carreau:)

**Comment by engyasin** [comment]
Great , I had the same problem and now , Solved !! :) :) :+1:

**Comment by willingc** [comment]
@engyasin :+1:

**Comment by mohamedalsherif** [comment]
Fixed it to me too! Thankx

**Comment by laurentknauss** [comment]
Fixed for me too, thanks Carreau!

**Comment by marwahaha** [comment]
Thank you!

```python -m jupyter kernelspec install-self``` did the trick.

**Comment by Shuyib** [comment]
Hi, i'm also having a similiar error. How do i fix it?
Traceback (most recent call last):
  File "/Users/brendamainye/anaconda/lib/python2.7/site-packages/notebook/base/handlers.py", line 457, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/Users/brendamainye/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/brendamainye/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/Users/brendamainye/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/brendamainye/anaconda/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 62, in post
    kernel_id=kernel_id))
  File "/Users/brendamainye/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/brendamainye/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/Users/brendamainye/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/brendamainye/anaconda/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_name)
  File "/Users/brendamainye/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/brendamainye/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/Users/brendamainye/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1014, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/brendamainye/anaconda/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/Users/brendamainye/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Users/brendamainye/anaconda/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/Users/brendamainye/anaconda/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
    yielded = next(result)
  File "/Users/brendamainye/anaconda/lib/python2.7/site-packages/notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/Users/brendamainye/anaconda/lib/python2.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/Users/brendamainye/anaconda/lib/python2.7/site-packages/jupyter_client/manager.py", line 243, in start_kernel
    **kw)
  File "/Users/brendamainye/anaconda/lib/python2.7/site-packages/jupyter_client/manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/Users/brendamainye/anaconda/lib/python2.7/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/Users/brendamainye/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/brendamainye/anaconda/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by takluyver** [comment]
Use `jupyter kernelspec list` to find out where your kernelspecs are installed. One of them contains an invalid path to a Python interpreter.

**Comment by Shuyib** [comment]
Thanks! I checked it out and reinstalled the ipykernel for python 2 and python3.

**Comment by b0ry** [comment]
I've just started using Jupyter and I'm having the same problem.

I've tried reinstalling the Jupyter kernel:
![image](https://cloud.githubusercontent.com/assets/18270809/15981056/81a52246-2f68-11e6-8751-100f3eefc1c5.png)
Nice. No joy though.

And I've tried reinstalling the Python2 kernel:
![image](https://cloud.githubusercontent.com/assets/18270809/15981105/eccbd7b8-2f68-11e6-840a-52062e4a4061.png)
Still no joy :_(

Am I doing something silly? My code is simply
![image](https://cloud.githubusercontent.com/assets/18270809/15981223/6a4ad7ba-2f6a-11e6-9cda-8e3337a838fe.png)

And here's the path in my Jupyter docs
![image](https://cloud.githubusercontent.com/assets/18270809/15981181/f6e2754e-2f69-11e6-9708-3c3c4ee108ed.png)

**Comment by takluyver** [comment]
The paths in the jupyter dashboard are from the directory where you
launched the notebook server. That's probably not root. Run %pwd to see the
working directory the *kernel* is running in, which should give you a clue.

**Comment by b0ry** [comment]
My current working directory is:
![image](https://cloud.githubusercontent.com/assets/18270809/15984495/421a2114-2fc5-11e6-83d7-09759ac22aca.png)

But even writing
![image](https://cloud.githubusercontent.com/assets/18270809/15984522/0ccd7cc6-2fc6-11e6-894b-892ab12f7e2d.png)
gives the same error.

Are there any more diagnostics the community can think of?

**Comment by takluyver** [comment]
Your file is called `channel_1.dat`, you're using `channel1.dat`.

**Comment by b0ry** [comment]
Quite literally, laughing out loud... I'm such a plonker sometimes.

Thank you takluyver,

**Comment by Rockgecko** [comment]
Also worked for me on Windows VM running Windows 7 Pro- thanks!
