### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0x88 in position 2: invalid start byte

### ISSUE THREAD

**Issue by pinkman61** [jupyter/notebook#3040]
Please tell me how to resolve this. I tried few things but didn't work!

pinkman@pinkman:~$ anaconda-navigator
Traceback (most recent call last):
  File "/home/pinkman/anaconda2/bin/anaconda-navigator", line 11, in <module>
    sys.exit(main())
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 125, in main
    from anaconda_navigator.utils.logs import clean_logs
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/utils/logs.py", line 18, in <module>
    from anaconda_navigator.config import (LOG_FILENAME, LOG_FOLDER,
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/config/__init__.py", line 24, in <module>
    from anaconda_navigator.config.main import CONF
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/config/main.py", line 67, in <module>
    raw_mode=True,
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/config/user.py", line 221, in __init__
    self.load_from_ini()
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/config/user.py", line 275, in load_from_ini
    self.readfp(conf_file)
  File "/home/pinkman/anaconda2/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/home/pinkman/anaconda2/lib/python2.7/ConfigParser.py", line 479, in _read
    line = fp.readline()
  File "/home/pinkman/anaconda2/lib/python2.7/codecs.py", line 690, in readline
    return self.reader.readline(size)
  File "/home/pinkman/anaconda2/lib/python2.7/codecs.py", line 545, in readline
    data = self.read(readsize, firstline=True)
  File "/home/pinkman/anaconda2/lib/python2.7/codecs.py", line 492, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x88 in position 2: invalid start byte

------------------------------------------------------------------------------------------------------------------------------------------

pinkman@pinkman:~$ jupyter kernelspec list
Available kernels:
  python2    /home/pinkman/.local/share/jupyter/kernels/python2

------------------------------------------------------------------------------------------------------------------------------------------

**Comment by takluyver** [comment]
That error is coming from anaconda navigator, there's no Jupyter code involved. Try reporting on https://github.com/ContinuumIO/anaconda-issues/
