### ISSUE TITLE
Mac os High Sierra not running jupyter notebook

### ISSUE THREAD

**Issue by csimek** [jupyter/notebook#3050]
I just updated my mac to OS High Sierra. I tried to run jupyter notebook in the terminal and I received this error: 

ModuleNotFoundError: No module named 'urlparse'

Is anyone else experiencing this issue or are there any suggestions for fixing this?

**Comment by takluyver** [comment]
Try reinstalling Jupyter. If you still see the error, give us some more details, like the traceback that it should be showing you.

**Comment by csimek** [comment]
I attempted a reinstall of anaconda to no avail. Here is the full traceback:

Traceback (most recent call last):
  File "/Users/CSimek2/anaconda/lib/python3.6/site-packages/notebook/nbextensions.py", line 18, in <module>
    from urllib.request import urlretrieve
  File "/Users/CSimek2/anaconda/lib/python3.6/urllib/request.py", line 2585, in <module>
    from _scproxy import _get_proxy_settings, _get_proxies
ImportError: dlopen(/Users/CSimek2/anaconda/lib/python3.6/lib-dynload/_scproxy.cpython-36m-darwin.so, 2): Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /Users/CSimek2/anaconda/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/CSimek2/anaconda3/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/Users/CSimek2/anaconda/lib/python3.6/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/Users/CSimek2/anaconda/lib/python3.6/site-packages/notebook/nbextensions.py", line 20, in <module>
    from urlparse import urlparse
ModuleNotFoundError: No module named 'urlparse'

**Comment by gnestor** [comment]
It looks like you're missing `urlparse` which is a dependency. Can you try `pip install notebook --upgrade --force-reinstall`?

**Comment by takluyver** [comment]
That's not the real issue. It's trying the Python 3 urllib import and falling over on some OS X library (`Symbol not found: __cg_jpeg_resync_to_restart`). Then it catches the ImportError and tries the Python 2 import (`urlparse`), which is not meant to work, because it's Python 3.

The important error is the first one (and isn't exception chaining nice ;-)

**Comment by batbraincmu** [comment]
Any Idea how to fix this?
