### ISSUE TITLE
Error when importing notebook.services.contents.filemanager

### ISSUE THREAD

**Issue by rossant** [jupyter/notebook#3056]
In notebook 5.2.1, the following command raises an error:

```
python -c "from notebook.services.contents.filemanager import FileContentsManager"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/cyrille/miniconda3/envs/cookbook_future/lib/python3.6/site-packages/notebook/services/contents/filemanager.py", line 21, in <module>
    from .manager import ContentsManager
  File "/home/cyrille/miniconda3/envs/cookbook_future/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 38, in <module>
    class ContentsManager(LoggingConfigurable):
  File "/home/cyrille/miniconda3/envs/cookbook_future/lib/python3.6/site-packages/notebook/services/contents/manager.py", line 70, in ContentsManager
    untitled_notebook = Unicode(_("Untitled"), config=True,
NameError: name '_' is not defined

```

There seems to be an extra `_` here:

https://github.com/jupyter/notebook/blob/ba33c33ee24db50ef500700f08f78d0fe6942a22/notebook/services/contents/manager.py#L70

Is that the problem? When removing this `_`, the error goes away.

**Comment by takluyver** [comment]
The `_` is part of the translation machinery. If you import `notebook.transutils` first, it should be defined.

The `_()` translation function is conventionally injected into builtins rather than being passed around, because you want to use it in many places. It's kind of ugly, but it seems to be a normal way to use it.

**Comment by rossant** [comment]
Calling `from notebook import transutils` before `from notebook.services.contents.filemanager import FileContentsManager` fixes the problem. Thanks!

**Comment by rossant** [comment]
For future reference, `from notebook import transutils` should be put inside a `try/except` to deal with earlier versions of notebook.
