### ISSUE TITLE
Start kernel failed: ImportError: No module named 'IPython'

### ISSUE THREAD

**Issue by DSRYhh** [jupyter/notebook#3086]
I'm using jupyter in python virtualenv, python 3.5, Ubuntu 14.04. I install jupyter via:
```
pip3 install jupyter
```
Run `jupyter notebook` can start the notebook, but when run the code in a notebook, the notebook crashed:
```
[I 16:20:42.414 NotebookApp] KernelRestarter: restarting kernel (1/5)
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
ImportError: No module named 'IPython'
```

**Comment by DSRYhh** [comment]
Solution found. See [https://stackoverflow.com/questions/29725915/ipython-iptest-importerror-no-module-named-ipython/47507335#47507335](url). The problem is I use `--system-site-packages` when create the virtualenv.
