### ISSUE TITLE
Unhandled error in API request [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by ziyiyang8** [jupyter/notebook#3093]
I am using the nb2kg server extension and everytime I open a notebook I get

> [E 22:03:07.566 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/notebook/base/handlers.py", line 503, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/lib/python2.7/dist-packages/nb2kg/handlers.py", line 253, in get
        kernel_specs = yield gen.maybe_future(ksm.list_kernel_specs())
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/lib/python2.7/dist-packages/nb2kg/managers.py", line 266, in list_kernel_specs
        response = yield fetch_kg(self.kernelspecs_endpoint, method='GET')
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/lib/python2.7/dist-packages/nb2kg/managers.py", line 34, in fetch_kg
        response = yield client.fetch(url, headers=KG_HEADERS, validate_cert=VALIDATE_KG_CERT, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    gaierror: [Errno -2] Name or service not known

>

**Comment by takluyver** [comment]
It looks like this is coming from nb2kg code - maybe file it there first: https://github.com/jupyter/kernel_gateway_demos/tree/master/nb2kg
