### ISSUE TITLE
Error jupyter notebook on Ubuntu 17.04 cannot find -lpthread and cannot find -lc

### ISSUE THREAD

**Issue by AndreyGFranca** [jupyter/notebook#3096]
Hello everyone, recently I've installed the package Xeus-cling via conda, and after the jupyter notebook doesn't run, and return this error when I type `jupyter notebook`

```
[/home/andrey/Programs/conda/compiler_compat/ld: cannot find -lpthread
/home/andrey/Programs/conda/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/home/andrey/Programs/conda/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/home/andrey/Programs/conda/lib/python3.6/site-packages/notebook/notebookapp.py", line 42, in <module>
    from zmq.eventloop import ioloop
  File "/home/andrey/Programs/conda/lib/python3.6/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/home/andrey/Programs/conda/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/andrey/Programs/conda/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/andrey/Programs/conda/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/andrey/Programs/conda/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/andrey/Programs/conda/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libzmq.so.5.1.2: cannot open shared object file: No such file or directory
](url)
```

I'm using ubuntu, and try to install libzmq `sudo apt-get install libzmq5` but this is already installed.

Thanks

--
Andrey

**Comment by nicolefinnie** [comment]
@AndreyGFranca  Thanks for your post, yes, it did fix my problem too, my original `pyzmq` was `16.0.2` after having uninstalled and cleaned up, the latest version of `pyzmq `17.0.0` works with jupyter.
