### ISSUE TITLE
Kernal Repeatedly Dying C++

### ISSUE THREAD

**Issue by idotamir516** [jupyter/notebook#3112]
Similar to solved issue [](https://github.com/jupyter/notebook/issues/1892) my kernal keeps on dying then even when attempting to restart dies again. However, this only occurs when I try to use cling for c++11 or 14. Python 3 still works excellently. My terminal shows the following:

> [I 02:50:43.033 NotebookApp] Kernel started: cab048db-b518-4f7e-a3a1-1eebea3389de
Traceback (most recent call last):
  File "/Users/idotamir/anaconda3/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/idotamir/cling/share/cling/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/Users/idotamir/cling/share/cling/Jupyter/kernel/clingkernel.py", line 344, in main
    ClingKernelApp.launch_instance()
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/Users/idotamir/cling/share/cling/Jupyter/kernel/clingkernel.py", line 101, in __init__
    whichCling = os.readlink(shutil.which('cling'))
TypeError: readlink: path should be string, bytes or os.PathLike, not NoneType
[I 02:50:46.034 NotebookApp] KernelRestarter: restarting kernel (1/5)
Traceback (most recent call last):
  File "/Users/idotamir/anaconda3/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/idotamir/cling/share/cling/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/Users/idotamir/cling/share/cling/Jupyter/kernel/clingkernel.py", line 344, in main
    ClingKernelApp.launch_instance()
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/Users/idotamir/cling/share/cling/Jupyter/kernel/clingkernel.py", line 101, in __init__
    whichCling = os.readlink(shutil.which('cling'))
TypeError: readlink: path should be string, bytes or os.PathLike, not NoneType
[I 02:50:49.041 NotebookApp] KernelRestarter: restarting kernel (2/5)
Traceback (most recent call last):
  File "/Users/idotamir/anaconda3/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/idotamir/cling/share/cling/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/Users/idotamir/cling/share/cling/Jupyter/kernel/clingkernel.py", line 344, in main
    ClingKernelApp.launch_instance()
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/Users/idotamir/cling/share/cling/Jupyter/kernel/clingkernel.py", line 101, in __init__
    whichCling = os.readlink(shutil.which('cling'))
TypeError: readlink: path should be string, bytes or os.PathLike, not NoneType
[I 02:50:52.049 NotebookApp] KernelRestarter: restarting kernel (3/5)
[W 02:50:53.069 NotebookApp] Timeout waiting for kernel_info reply from cab048db-b518-4f7e-a3a1-1eebea3389de
Traceback (most recent call last):
  File "/Users/idotamir/anaconda3/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/idotamir/cling/share/cling/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/Users/idotamir/cling/share/cling/Jupyter/kernel/clingkernel.py", line 344, in main
    ClingKernelApp.launch_instance()
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/Users/idotamir/cling/share/cling/Jupyter/kernel/clingkernel.py", line 101, in __init__
    whichCling = os.readlink(shutil.which('cling'))
TypeError: readlink: path should be string, bytes or os.PathLike, not NoneType
[I 02:50:55.058 NotebookApp] KernelRestarter: restarting kernel (4/5)
kernel cab048db-b518-4f7e-a3a1-1eebea3389de restarted
Traceback (most recent call last):
  File "/Users/idotamir/anaconda3/bin/jupyter-cling-kernel", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/idotamir/cling/share/cling/Jupyter/kernel/scripts/jupyter-cling-kernel", line 4, in <module>
    main()
  File "/Users/idotamir/cling/share/cling/Jupyter/kernel/clingkernel.py", line 344, in main
    ClingKernelApp.launch_instance()
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/Users/idotamir/anaconda3/lib/python3.6/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/Users/idotamir/cling/share/cling/Jupyter/kernel/clingkernel.py", line 101, in __init__
    whichCling = os.readlink(shutil.which('cling'))
TypeError: readlink: path should be string, bytes or os.PathLike, not NoneType
[W 02:50:58.070 NotebookApp] KernelRestarter: restart failed
[W 02:50:58.071 NotebookApp] Kernel cab048db-b518-4f7e-a3a1-1eebea3389de died, removing from map.
kernel cab048db-b518-4f7e-a3a1-1eebea3389de restarted failed!
[W 02:50:58.087 NotebookApp] Kernel deleted before session

Of course any help would be greatly appreciated

**Comment by takluyver** [comment]
This bit looks like it can't find Cling on your system:

```
File "/Users/idotamir/cling/share/cling/Jupyter/kernel/clingkernel.py", line 101, in init
whichCling = os.readlink(shutil.which('cling'))
TypeError: readlink: path should be string, bytes or os.PathLike, not NoneType
```

**Comment by idotamir516** [comment]
That's what I thought the error was as well so I tried to export the folder that cling was stored in and add it to the path i.e.

> export PATH=cling/bin:$PATH

however, the issue persisted. Should I only export the bin file from the terminal when I am in a specific path?

I do think that I might be looking in the wrong place since cling for c++11 and 14 were downloaded correctly and are options  to use in jupyter notebook so is it possible that the interpreter is just in the wrong file?

**Comment by takluyver** [comment]
I think the paths in PATH need to be absolute, like `/Users/idotamir/.../bin` (fill it in for the correct path on your system).

**Comment by idotamir516** [comment]
I tried using the absolute path

> export PATH=/Users/idotamir/cling/bin:$PATH

however that didn't work as well. I also double checked that cling was installed so in the terminal I typed the command:

> cling --version
and it returned 

> 0.6~dev

All the previous help is much appreciated and if you have any more ideas on how to fix this I am happy to try.

**Comment by idotamir516** [comment]
Ok so just to clarify I opened a Python notebook and checking in the notebook itself those commands (just want to make sure I did it right). If that is indeed what I should have done here are the respective results:

print(os.environ['PATH']):

> /Users/idotamir/anaconda3/bin:/Users/idotamir/.rvm/gems/ruby-2.3.1/bin:/Users/idotamir/.rvm/gems/ruby-2.3.1@global/bin:/Users/idotamir/.rvm/rubies/ruby-2.3.1/bin:/Users/idotamir/.rbenv/shims:/Users/idotamir/.rbenv/bin:/Library/Frameworks/Python.framework/Versions/3.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/idotamir/.rvm/bin

print(shutil.which('cling')):

> None

If this means anything, when I run print(shutil.which('clang')) it actually does find a directory for the compiler so I'm wondering if I downloaded the wrong thing or that it could be because I use C++ anyway for other projects using text editors.

**Comment by takluyver** [comment]
That PATH doesn't show your addition of `/Users/idotamir/cling/bin`, so wherever you changed it, it's not affecting the environment you started the notebook in.

Normally, you'd add that line `export ...` to a file like `.bashrc` (if bash is your shell), then start a new terminal and launch `jupyter notebook` from there.

**Comment by idotamir516** [comment]
I see so what I did now is in the terminal I typed again the export command written above and launched jupyter notebook from there and it is now successful! I was wondering if there is something I can do so I don't have to export it each time however and for it to be permanently part of the path or to somehow show jupyter notebook where to find it?

**Comment by takluyver** [comment]
Yep. You probably have a file in your home directory called `.bashrc` .  Files starting with a dot are hidden, but you can see them with `ls -a`. That file is run each time you start bash. So edit it, and add your command modifying PATH. Then you shouldn't have to type it again.

**Comment by idotamir516** [comment]
Thank you it works flawlessly I have learned so much from this interaction and Jupyter notebook works perfectly :)

**Comment by takluyver** [comment]
Great :-)

**Comment by kishansairam9** [comment]
I added cling to PATH and it works when i use the command cling from the conda env
I also reinstalled xeus-cling two times in new conda env
None of them seemed to work.    
```
(xeus) [kishan@kishan-xps15 ~]$ jupyter lab
[I 05:28:59.662 LabApp] JupyterLab extension loaded from /home/kishan/anaconda3/envs/xeus/lib/python3.6/site-packages/jupyterlab
[I 05:28:59.662 LabApp] JupyterLab application directory is /home/kishan/anaconda3/envs/xeus/share/jupyter/lab
[W 05:28:59.663 LabApp] JupyterLab server extension not enabled, manually loading...
[I 05:28:59.665 LabApp] JupyterLab extension loaded from /home/kishan/anaconda3/envs/xeus/lib/python3.6/site-packages/jupyterlab
[I 05:28:59.666 LabApp] JupyterLab application directory is /home/kishan/anaconda3/envs/xeus/share/jupyter/lab
[I 05:28:59.666 LabApp] Serving notebooks from local directory: /home/kishan
[I 05:28:59.666 LabApp] The Jupyter Notebook is running at:
[I 05:28:59.666 LabApp] http://localhost:8888/?token=982a1fdd4426bd96f6516709963fef7716d7be13cbc92a54
[I 05:28:59.666 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 05:28:59.668 LabApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=982a1fdd4426bd96f6516709963fef7716d7be13cbc92a54
[I 05:28:59.989 LabApp] Accepting one-time-token-authenticated connection from ::1
[17255:17255:1215/052900.007028:ERROR:sandbox_linux.cc(364)] InitializeSandbox() called with multiple threads in process gpu-process.
Opening in existing browser session.
[I 05:29:00.960 LabApp] Node v10.13.0
    
[I 05:29:01.066 LabApp] Build is up to date
[I 05:29:01.473 LabApp] Kernel started: dbe2f0e8-d838-4585-ac81-cf7a625a3aef
[I 05:29:04.474 LabApp] KernelRestarter: restarting kernel (1/5), new random ports
[I 05:29:07.483 LabApp] KernelRestarter: restarting kernel (2/5), new random ports
[I 05:29:10.488 LabApp] KernelRestarter: restarting kernel (3/5), new random ports
[I 05:29:13.496 LabApp] KernelRestarter: restarting kernel (4/5), new random ports
[W 05:29:16.505 LabApp] KernelRestarter: restart failed
[W 05:29:16.505 LabApp] Kernel dbe2f0e8-d838-4585-ac81-cf7a625a3aef died, removing from map.
[W 05:30:01.484 LabApp] Timeout waiting for kernel_info reply from dbe2f0e8-d838-4585-ac81-cf7a625a3aef
[E 05:30:01.486 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: dbe2f0e8-d838-4585-ac81-cf7a625a3aef)
[E 05:30:01.490 LabApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: dbe2f0e8-d838-4585-ac81-cf7a625a3aef)

```
