### ISSUE TITLE
The kernel has died

### ISSUE THREAD

**Issue by nmsdn** [jupyter/notebook#3126]
Hi all

I have a similar problem as [@jslug1000](https://github.com/jupyter/notebook/issues/1892). When opening any jupyter notebook, even one with no code in, I get the 'Dead kernel' message.
I followed @takluyver's suggestion and it didn't work. 

I have uninstalled and reinstalled 'Anaconda' and problems persists.

Terminal window shows the following:

```
[I 17:05:11.026 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 17:05:36.830 NotebookApp] Kernel started: 58ee57d0-4a18-43ed-8e1f-4e77bbe795a1
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-121>", line 2, in initialize
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 46, in __init__
    kernel      = self,
  File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 477, in __init__
    self.init_history()
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 1577, in init_history
    self.history_manager = HistoryManager(shell=self, parent=self)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\history.py", line 548, in __init__
    self.new_session()
  File "<decorator-gen-21>", line 2, in new_session
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\history.py", line 60, in needs_sqlite
    return f(self, *a, **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\history.py", line 574, in new_session
    NULL, "") """, (datetime.datetime.now(),))
sqlite3.DatabaseError: database disk image is malformed
[I 17:05:39.825 NotebookApp] KernelRestarter: restarting kernel (1/5)
Traceback (most recent call last):
```

Please help.

**Comment by takluyver** [comment]
I'm not sure what suggestion you tried before, but try finding and deleting a file like `C:\Users\Username\.ipython\profile_default\history.sqlite` . It looks like that file has got corrupted.

**Comment by nmsdn** [comment]
I have deleted the file and nothing changed. 
The suggestion I followed was uninstalling the following:
- ipykernel
- ipython
- jupyter_client
- jupyter_core
- traitlets
- ipython_genutils
and then install again.

**Comment by takluyver** [comment]
Does it keep recreating that file if you delete it?

**Comment by takluyver** [comment]
(i.e. if you delete it and try to open a notebook again, does the `history.sqlite` file reappear?

**Comment by nmsdn** [comment]
No it doesn't reappear.

**Comment by takluyver** [comment]
That might mean that it's a different file that needs to be deleted. Try searching your computer for `history.sqlite` ?

**Comment by nmsdn** [comment]
Yes, found it and deleted it. Problem Fixed. Thanks a lot!

**Comment by nmsdn** [comment]
@takluyver, If I may ask how to did spot that the file  `history.sqlite` is corrupted?

**Comment by takluyver** [comment]
I could see in the traceback that the error is coming from the history module (`C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\history.py`), and that it's an sqlite database error. [SQLite](http://sqlite.org/) is a lightweight database that we use for storing a record of the commands you enter. 

I've worked on that bit of code, so I'm familiar with where the file is, but if not, I might have tried searching the docs for "history sqlite", which gives me [this page](http://ipython.readthedocs.io/en/stable/interactive/reference.html?highlight=history%20sqlite#search-command-history) among other results.

**Comment by wakristensen** [comment]
I have a similar problem when trying to run jupyter notebook. I get the dead kernel message during startup.

I have tried uninstalling and reinstalling 
- ipykernel
- ipython
- jupyter_client
- jupyter_core
- traitlets
- ipython_genutils

However there seems to be a problem with enum module, as the terminal outputs:
`AttributeError: module 'enum' has no attribute 'IntFlag'`

I am running python 3.6.5 in Conda 4.5.0.
Please help!

**Comment by takluyver** [comment]
Have you got a file called `enum.py` or an `enum` folder where you're trying to start the kernel? It might be shadowing the standard library enum module.

**Comment by takluyver** [comment]
No - the first one is the module it should find, the second is inside a package, and it won't look for the third path (and if it did, it's the same file as the first).

Can you show more of the traceback? I don't think any of our code uses `enum.IntFlag`.

**Comment by deveshbatra** [comment]
Probably too late, but unsetting PYTHONPATH (or any other environment variables for that matter) worked for me.

'unset PYTHONPATH'

**Comment by Bitewulign** [comment]
when I run a code in anaconda jupyter, i got an error
''The kernel has died, and the automatic restart has failed.''
I upgrade all the libraries. However, the error still exists. I couldn't go to the next step. Any help is appreciated!

**Comment by WangMo-Katherine** [comment]
i also face the same error. what i did was to update the mkl library and it worked for me.
the only problem was that it removed my matplotlib and seaborn lib which i had to insall it manually
