### ISSUE TITLE
An error occur after Jupyter Notebook suddenly shut down

### ISSUE THREAD

**Issue by ChuckZhu** [jupyter/notebook#3132]
Traceback (most recent call last):
  File "C:\Users\Chuck\Anaconda2\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Chuck\Anaconda2\lib\site-packages\conda\cli\main.py", line 179,
 in main
    return handle_exception(e)
  File "C:\Users\Chuck\Anaconda2\lib\site-packages\conda\exceptions.py", line 63
4, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Users\Chuck\Anaconda2\lib\site-packages\conda\exceptions.py", line 59
6, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\Users\Chuck\Anaconda2\lib\site-packages\conda\cli\main_info.py", line
 162, in get_info_dict
    from ..connection import user_agent
  File "C:\Users\Chuck\Anaconda2\lib\site-packages\conda\connection.py", line 12
, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "C:\Users\Chuck\Anaconda2\lib\site-packages\requests\__init__.py", line 4
8, in <module>
    import urllib3
  File "C:\Users\Chuck\Anaconda2\lib\site-packages\urllib3\__init__.py", line 8,
 in <module>
    from .connectionpool import (
  File "C:\Users\Chuck\Anaconda2\lib\site-packages\urllib3\connectionpool.py", l
ine 36, in <module>
    from .response import HTTPResponse
ImportError: cannot import name HTTPResponse

**Comment by takluyver** [comment]
This looks like there's a problem with some conda wrapper. You could try reporting it [on conda](https://github.com/conda/conda). If it doesn't cause any problems, it's probably also safe to ignore it.
