### ISSUE TITLE
problem running from terminal

### ISSUE THREAD

**Issue by vahidajalluian** [jupyter/notebook#3141]
when I want to run "jupyter notebook" I get the following error.
what is the problem?

```
Traceback (most recent call last):
  File "/home/vahid/anaconda3/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/home/vahid/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 74, in <module>
    from .services.kernels.kernelmanager import MappingKernelManager
  File "/home/vahid/anaconda3/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 16, in <module>
    from jupyter_client.multikernelmanager import MultiKernelManager
  File "/home/vahid/anaconda3/lib/python3.6/site-packages/jupyter_client/__init__.py", line 7, in <module>
    from .manager import KernelManager, run_kernel
  File "/home/vahid/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 32, in <module>
    from .session import Session
  File "/home/vahid/anaconda3/lib/python3.6/site-packages/jupyter_client/session.py", line 61, in <module>
    from jupyter_client.jsonutil import extract_dates, squash_dates, date_default
  File "/home/vahid/anaconda3/lib/python3.6/site-packages/jupyter_client/jsonutil.py", line 11, in <module>
    from dateutil.parser import parse as _dateutil_parse
  File "/home/vahid/anaconda3/lib/python3.6/site-packages/dateutil/parser.py", line 158
    l.append("%s=%s" % (attr, `value`))
                              ^
SyntaxError: invalid syntax
```

how can I solve it?

**Comment by takluyver** [comment]
It looks like you've got a wrong version of `python-dateutil` installed. Try running `conda update python-dateutil` and see if that fixes anything.

**Comment by vahidajalluian** [comment]
it has been solved. the problem was with wrong version in anaconda. after removing them from anaconda the problem solved

**Comment by takluyver** [comment]
Great. I'll close this now, but it would be good if you could describe exactly what you needed to do - it might help other people with similar problems if they see this.

**Comment by ajeetksingh** [comment]
Hi @vahidajalluian,
Can you please describe what did you exactly needed to do?
Thanks. :)

**Comment by rchann2** [comment]
@ajeetksingh I reinstalled jupyter using pip3 install --upgrade jupyter and it worked.
