### ISSUE TITLE
ImportError: No module named bunch

### ISSUE THREAD

**Issue by govinda-kamath** [jupyter/notebook#3143]
I was trying to run jupyter from the command line, but seem to run into the following error

```
govinda@shannon:/data⟫ jupyter notebook
Traceback (most recent call last):
  File "/home/govinda/anaconda/bin/jupyter-notebook", line 4, in <module>
    from notebook.notebookapp import main
  File "/home/govinda/anaconda/lib/python2.7/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/home/govinda/anaconda/lib/python2.7/site-packages/notebook/nbextensions.py", line 222, in <module>
    from traitlets import Bool, Enum, Unicode
  File "/home/govinda/anaconda/lib/python2.7/site-packages/traitlets/__init__.py", line 1, in <module>
    from .traitlets import *
  File "/home/govinda/anaconda/lib/python2.7/site-packages/traitlets/traitlets.py", line 62, in <module>
    from .utils.bunch import Bunch
ImportError: No module named bunch
```

The strange thing being that `bunch` is actually installed in my system.
```
govinda@shannon:/data⟫ conda install bunch
Fetching package metadata .................
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/govinda/anaconda:
#
bunch                     1.0.1                    py27_0    conda-forge
```

```
govinda@shannon:/data⟫ pip install Bunch
Requirement already satisfied: Bunch in /home/govinda/anaconda/lib/python2.7/site-packages
```

I'd appreciate any help with respect to this. Thanks.

**Comment by takluyver** [comment]
It's looking for the [traitlets.utils.bunch](https://github.com/ipython/traitlets/blob/master/traitlets/utils/bunch.py) module. Your installation appears to be corrupted somehow. Try uninstalling and reinstalling the `traitlets` package. If that doesn't work, it may be necessary to delete Anaconda and install it again.

**Comment by govinda-kamath** [comment]
That did the trick. Thanks a lot!
