### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by steph-jung** [jupyter/notebook#3185]
I get this error when I try to use jupyter notebook..

ubuntu@ip-172-31-17-129:~$ jupyter notebook
[I 23:44:44.737 NotebookApp] Using EnvironmentKernelSpecManager...
[I 23:44:44.737 NotebookApp] Started periodic updates of the kernel list (every 3 minutes).
[W 23:44:44.977 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 23:44:44.983 NotebookApp] Serving notebooks from local directory: /home/ubuntu
[I 23:44:44.983 NotebookApp] 0 active kernels
[I 23:44:44.983 NotebookApp] The Jupyter Notebook is running at:
[I 23:44:44.983 NotebookApp] http://[all ip addresses on your system]:8088/?token=750976ae7414c414f37eee415b89d167b5261036d4ffe4fb
[I 23:44:44.983 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 23:44:44.984 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8088/?token=750976ae7414c414f37eee415b89d167b5261036d4ffe4fb
[I 23:44:44.984 NotebookApp] Starting initial scan of virtual environments...
[E 23:44:44.988 NotebookApp] Exception in callback <functools.partial object at 0x7fb5b5e92368>
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 605, in _run_callback
        ret = callback()
      File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/environment_kernels/core.py", line 151, in _update_env_data
        self._get_env_data(reload=True)
      File "/usr/local/lib/python2.7/dist-packages/environment_kernels/core.py", line 166, in _get_env_data
        env_data.update(supplyer(self))
      File "/usr/local/lib/python2.7/dist-packages/environment_kernels/envs_conda.py", line 22, in get_conda_env_data
        env_paths.extend(_find_conda_env_paths_from_conda(mgr))
      File "/usr/local/lib/python2.7/dist-packages/environment_kernels/envs_conda.py", line 77, in _find_conda_env_paths_from_conda
        stdout=subprocess.PIPE)
      File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory
ubuntu@ip-172-31-17-129:~$ jupyter notebook
[I 23:44:44.737 NotebookApp] Using EnvironmentKernelSpecManager...
[I 23:44:44.737 NotebookApp] Started periodic updates of the kernel list (every 3 minutes).
[W 23:44:44.977 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[I 23:44:44.983 NotebookApp] Serving notebooks from local directory: /home/ubuntu
[I 23:44:44.983 NotebookApp] 0 active kernels
[I 23:44:44.983 NotebookApp] The Jupyter Notebook is running at:
[I 23:44:44.983 NotebookApp] http://[all ip addresses on your system]:8088/?token=750976ae7414c414f37eee415b89d167b5261036d4ffe4fb
[I 23:44:44.983 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 23:44:44.984 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8088/?token=750976ae7414c414f37eee415b89d167b5261036d4ffe4fb
[I 23:44:44.984 NotebookApp] Starting initial scan of virtual environments...
[E 23:44:44.988 NotebookApp] Exception in callback <functools.partial object at 0x7fb5b5e92368>
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 605, in _run_callback
        ret = callback()
      File "/usr/local/lib/python2.7/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/environment_kernels/core.py", line 151, in _update_env_data
        self._get_env_data(reload=True)
      File "/usr/local/lib/python2.7/dist-packages/environment_kernels/core.py", line 166, in _get_env_data
        env_data.update(supplyer(self))
      File "/usr/local/lib/python2.7/dist-packages/environment_kernels/envs_conda.py", line 22, in get_conda_env_data
        env_paths.extend(_find_conda_env_paths_from_conda(mgr))
      File "/usr/local/lib/python2.7/dist-packages/environment_kernels/envs_conda.py", line 77, in _find_conda_env_paths_from_conda
        stdout=subprocess.PIPE)
      File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
        errread, errwrite)
      File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory

**Comment by takluyver** [comment]
It looks like the error is coming from [environment_kernels](https://github.com/Cadair/jupyter_environment_kernels) - try opening an issue there.
