### ISSUE TITLE
Cannot shutdown a ghost notebook server

### ISSUE THREAD

**Issue by phizaz** [jupyter/notebook#3240]
I have closed all "cmd"s on Windows 10 that run notebook server.

I now run `jupyter notebook list` and see there still is one last running notebook.

```
Currently running servers:
http://localhost:8890/ :: C:\...
```

Which is a ghost indeed, there is no more notebook running! I also cannot find it anywhere in "Task Manager". 

Now, I try to kill it anyway with `jupyter notebook stop 8890` and here is the result:

```
Traceback (most recent call last):
  File "c:\users\me\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\me\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\me\Anaconda3\Scripts\jupyter-notebook.EXE\__main__.py", line 9, in <module>
  File "c:\users\me\anaconda3\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\users\me\anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "c:\users\me\anaconda3\lib\site-packages\notebook\notebookapp.py", line 1571, in start
    super(NotebookApp, self).start()
  File "c:\users\me\anaconda3\lib\site-packages\jupyter_core\application.py", line 255, in start
    self.subapp.start()
  File "c:\users\me\anaconda3\lib\site-packages\notebook\notebookapp.py", line 451, in start
    if not self.shutdown_server(server):
  File "c:\users\me\anaconda3\lib\site-packages\notebook\notebookapp.py", line 442, in shutdown_server
    return shutdown_server(server, log=self.log)
  File "c:\users\me\anaconda3\lib\site-packages\notebook\notebookapp.py", line 402, in shutdown_server
    HTTPClient().fetch(req)
  File "c:\users\me\anaconda3\lib\site-packages\tornado\httpclient.py", line 102, in fetch
    self._async_client.fetch, request, **kwargs))
  File "c:\users\me\anaconda3\lib\site-packages\tornado\ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "c:\users\me\anaconda3\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
ConnectionRefusedError: [Errno 10061] Unknown error
Shutting down server on port 8890 ...
```

The ghost persists...

**Comment by takluyver** [comment]
The notebook server writes a file which makes it show up in the list. If it has crashed, or been forcefully terminated, it won't have cleaned the file up. If you restart and run `jupyter notebook list` again,  there's a good chance it will be cleaned up (it is cleaned up if there's no process with the same PID). Or you can remove the file manually - run `jupyter --paths` and look in the 'runtime' directory.

**Comment by Miladiouss** [comment]
This happens to me every time I suspend my laptop. Restarting fixes it, but it is inconvenient.

**Comment by lucainnocenti** [comment]
@takluyver I have the same problem and restarting doesn't seem to help (the notebook is actually running for me, but I can't seem to shut it down, not with `pkill` and not with `jupyter notebook stop XXXX`).

Which of the files in that directory should I remove? This is its content for me:

```
$ ls /run/user/455019/jupyter/
kernel-04b145a6-553c-40bf-8212-a4738c61d2f4.json
kernel-0de242b0-20a1-4207-ac8e-64ec05b5f94d.json
kernel-12430350-2dee-48a3-9e31-88ae323c1999.json
kernel-4faa0ad7-5589-4ce1-aae4-cdca31e565e6.json
kernel-5ae00f81-52b0-4251-b00c-9466d3589b69.json
kernel-81ec273d-d297-474b-89a5-4be968ccf3d7.json
kernel-8c7da320-e5c2-4431-ad00-b4d10b04b146.json
kernel-9045952a-301e-492d-b6e8-4615518a1a25.json
kernel-b2a3094c-3d73-4695-b86c-808bed6b3b7f.json
kernel-e0cc7f2b-afce-49fc-bf4d-9bf3669b962b.json
nbserver-14198.json
nbserver-29073.json
notebook_cookie_secret
```

**Comment by waydegg** [comment]
@lucainnocenti You can delete all of the files as I believe they're just for making loading previous jupyter notebook sessions easier/quicker ([check the docs here](https://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html#runtime-files)). I removed all of the folder's contents and restarted my conda environment I was running my notebooks in, and after doing a `jupyter notebook list` saw no more notebooks running in the background.

**Comment by AndreaVerena** [comment]
> 
> 
> @lucainnocenti You can delete all of the files as I believe they're just for making loading previous jupyter notebook sessions easier/quicker ([check the docs here](https://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html#runtime-files)). I removed all of the folder's contents and restarted my conda environment I was running my notebooks in, and after doing a `jupyter notebook list` saw no more notebooks running in the background.

It works!
