### ISSUE TITLE
Jupyter Notebook is broken after updaing conda environment

### ISSUE THREAD

**Issue by protik77** [jupyter/notebook#3253]
I submitted the same issue in [conda](https://github.com/conda/conda/issues/6774) and was suggested to submit it here. I am copying the same issue I submitted here.

**I'm submitting a bug report**

## Current Behavior
After updating `conda` environment, Jupyter Notebook fails to get python environment. Getting the following error:

```python
(ptk.pmg) C:\Dropbox\Dropbox\Test>jupyter notebook
[I 14:14:04.214 NotebookApp] [nb_conda_kernels] enabled, 5 kernels found
[W 14:14:04.801 NotebookApp] Terminals not available (error was No module named 'terminado')
[I 14:14:04.855 NotebookApp] [nb_anacondacloud] enabled
[I 14:14:04.861 NotebookApp] [nb_conda] enabled
[I 14:14:04.928 NotebookApp] \u2713 nbpresent HTML export ENABLED
[W 14:14:04.928 NotebookApp] \u2717 nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
[I 14:14:05.045 NotebookApp] Serving notebooks from local directory: C:\Dropbox\Dropbox\RnD\Job hunting\citrine\DataProcessor
[I 14:14:05.045 NotebookApp] 0 active kernels
[I 14:14:05.047 NotebookApp] The Jupyter Notebook is running at:
[I 14:14:05.049 NotebookApp] http://localhost:8888/?token=b3d8d0fd92b80c3cfcd575bf1f8bfc338aeecabf86a04d7f
[I 14:14:05.050 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:14:05.053 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=b3d8d0fd92b80c3cfcd575bf1f8bfc338aeecabf86a04d7f
[I 14:14:05.811 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[W 14:14:06.273 NotebookApp] Error loading kernelspec 'conda-env-ase-py'
    Traceback (most recent call last):
      File "C:\protix\Miniconda3\envs\ptk.pmg\lib\site-packages\jupyter_client\kernelspec.py", line 257, in get_all_specs
        spec = self._get_kernel_spec_by_name(kname, resource_dir)
      File "C:\protix\Miniconda3\envs\ptk.pmg\lib\site-packages\jupyter_client\kernelspec.py", line 201, in _get_kernel_spec_by_name
        return self.kernel_spec_class.from_resource_dir(resource_dir)
      File "C:\protix\Miniconda3\envs\ptk.pmg\lib\site-packages\jupyter_client\kernelspec.py", line 46, in from_resource_dir
        with io.open(kernel_file, 'r', encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\protix\\Miniconda3\\envs\\ptk.pmg\\lib\\site-packages\\nb_conda_kernels\\logos\\python\\kernel.json'
[W 14:14:06.276 NotebookApp] Error loading kernelspec 'conda-env-ptk.pmg-py'
    Traceback (most recent call last):
      File "C:\protix\Miniconda3\envs\ptk.pmg\lib\site-packages\jupyter_client\kernelspec.py", line 257, in get_all_specs
        spec = self._get_kernel_spec_by_name(kname, resource_dir)
      File "C:\protix\Miniconda3\envs\ptk.pmg\lib\site-packages\jupyter_client\kernelspec.py", line 201, in _get_kernel_spec_by_name
        return self.kernel_spec_class.from_resource_dir(resource_dir)
      File "C:\protix\Miniconda3\envs\ptk.pmg\lib\site-packages\jupyter_client\kernelspec.py", line 46, in from_resource_dir
        with io.open(kernel_file, 'r', encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\protix\\Miniconda3\\envs\\ptk.pmg\\lib\\site-packages\\nb_conda_kernels\\logos\\python\\kernel.json'
[W 14:14:06.278 NotebookApp] Error loading kernelspec 'conda-env-Miniconda3-py'
    Traceback (most recent call last):
      File "C:\protix\Miniconda3\envs\ptk.pmg\lib\site-packages\jupyter_client\kernelspec.py", line 257, in get_all_specs
        spec = self._get_kernel_spec_by_name(kname, resource_dir)
      File "C:\protix\Miniconda3\envs\ptk.pmg\lib\site-packages\jupyter_client\kernelspec.py", line 201, in _get_kernel_spec_by_name
        return self.kernel_spec_class.from_resource_dir(resource_dir)
      File "C:\protix\Miniconda3\envs\ptk.pmg\lib\site-packages\jupyter_client\kernelspec.py", line 46, in from_resource_dir
        with io.open(kernel_file, 'r', encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\protix\\Miniconda3\\envs\\ptk.pmg\\lib\\site-packages\\nb_conda_kernels\\logos\\python\\kernel.json'
[W 14:14:06.304 NotebookApp] Error loading kernelspec 'python3'
    Traceback (most recent call last):
      File "C:\protix\Miniconda3\envs\ptk.pmg\lib\site-packages\jupyter_client\kernelspec.py", line 257, in get_all_specs
        spec = self._get_kernel_spec_by_name(kname, resource_dir)
      File "C:\protix\Miniconda3\envs\ptk.pmg\lib\site-packages\jupyter_client\kernelspec.py", line 201, in _get_kernel_spec_by_name
        return self.kernel_spec_class.from_resource_dir(resource_dir)
      File "C:\protix\Miniconda3\envs\ptk.pmg\lib\site-packages\jupyter_client\kernelspec.py", line 46, in from_resource_dir
        with io.open(kernel_file, 'r', encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\protix\\Miniconda3\\envs\\ptk.pmg\\lib\\site-packages\\nb_conda_kernels\\logos\\python\\kernel.json'
[W 14:14:06.309 NotebookApp] Error loading kernelspec 'conda-root-py'
    Traceback (most recent call last):
      File "C:\protix\Miniconda3\envs\ptk.pmg\lib\site-packages\jupyter_client\kernelspec.py", line 257, in get_all_specs
        spec = self._get_kernel_spec_by_name(kname, resource_dir)
      File "C:\protix\Miniconda3\envs\ptk.pmg\lib\site-packages\jupyter_client\kernelspec.py", line 201, in _get_kernel_spec_by_name
        return self.kernel_spec_class.from_resource_dir(resource_dir)
      File "C:\protix\Miniconda3\envs\ptk.pmg\lib\site-packages\jupyter_client\kernelspec.py", line 46, in from_resource_dir
        with io.open(kernel_file, 'r', encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\protix\\Miniconda3\\envs\\ptk.pmg\\lib\\site-packages\\nb_conda_kernels\\logos\\python\\kernel.json'
```

### Steps to Reproduce

I activated the environment. Then I did,
```
conda update --all
```

Then conda suggested I update the conda. Which I did using,
```
conda update -n base conda
```
After updating I tried,
```
jupyter notebook
```
And got the errors mentioned above.

## Expected Behavior

It should launch Jupyter Notebook with the environments installed. But the notebook is missing all the environments.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : ptk.pmg
    active env location : C:\protix\Miniconda3\envs\ptk.pmg
            shell level : 1
       user config file : C:\Users\pdas\.condarc
 populated config files : C:\Users\pdas\.condarc
          conda version : 4.4.7
    conda-build version : not installed
         python version : 3.5.4.final.0
       base environment : C:\protix\Miniconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\protix\Miniconda3\pkgs
                          C:\Users\pdas\AppData\Local\conda\conda\pkgs
       envs directories : C:\protix\Miniconda3\envs
                          C:\Users\pdas\AppData\Local\conda\conda\envs
                          C:\Users\pdas\.conda\envs
               platform : win-64
             user-agent : conda/4.4.7 requests/2.18.4 CPython/3.5.4 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\pdas\.condarc <==
ssl_verify: True
channels:
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at C:\protix\Miniconda3\envs\ptk.pmg:
#
_nb_ext_conf              0.4.0                    py35_1    defaults
anaconda-client           1.6.6            py35h690133a_0    defaults
ase                       3.15.0                    <pip>
asn1crypto                0.24.0                   py35_0    defaults
astroid                   1.6.0                    py35_0    defaults
attrs                     17.3.0           py35hdfbe3a1_0    defaults
beautifulsoup4            4.6.0            py35h61fcdcc_1    defaults
bleach                    2.1.2                    py35_0    defaults
bzip2                     1.0.6                haa5b126_2    defaults
ca-certificates           2017.08.26           h94faf87_0    defaults
cachecontrol              0.12.3           py35h3f82863_0    defaults
certifi                   2017.11.5        py35h456c6ae_0    defaults
cffi                      1.11.4           py35hfa6e2cd_0    defaults
chardet                   3.0.4            py35h177e1b7_1    defaults
clangdev                  3.9.1                   cling_4  [cling vc14]  conda-forge
click                     6.7                       <pip>
cling-patches             1                             0    QuantStack
clyent                    1.2.2            py35h3cd9751_1    defaults
colorama                  0.3.9            py35h32a752f_0    defaults
coverage                  4.4.2            py35h1d76e2e_0    defaults
cryptography              2.1.4            py35h8ead9e0_0    defaults
cycler                    0.10.0           py35hcc71164_0    defaults
decorator                 4.2.1                    py35_0    defaults
distlib                   0.2.5            py35h12c42d7_0    defaults
entrypoints               0.2.3            py35hb91ced9_2    defaults
Flask                     0.12.2                    <pip>
freetype                  2.8                  h51f8f2c_1    defaults
git                       2.15.0               heaa8ca2_0    defaults
hdf5                      1.10.1               h98b8871_1    defaults
html5lib                  1.0.1            py35h047fa9f_0    defaults
hypothesis                3.38.5           py35h37a2ca4_0    defaults
icc_rt                    2017.0.4             h97af966_0    defaults
icu                       58.2                 ha66f8fd_1    defaults
idna                      2.6              py35h8dcb9ae_1    defaults
intel-openmp              2018.0.0             hd92c6cd_8    defaults
ipykernel                 4.8.0                    py35_0    defaults
ipython                   6.2.1            py35h4a2ac14_1    defaults
ipython_genutils          0.2.0            py35ha709e79_0    defaults
ipywidgets                7.1.0                    py35_0    defaults
isort                     4.2.15           py35h0bf7b49_0    defaults
itsdangerous              0.24                      <pip>
jedi                      0.11.1                   py35_0    defaults
jinja2                    2.10             py35hdf652bb_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
jsonschema                2.6.0            py35h27d56d3_0    defaults
jupyter                   1.0.0            py35hce9caf1_2    defaults
jupyter_client            5.2.1                    py35_0    defaults
jupyter_console           5.2.0            py35hf76c22e_1    defaults
jupyter_core              4.4.0            py35h629ba7f_0    defaults
jupyterlab                0.31.1                   py35_0    defaults
jupyterlab_launcher       0.10.2                   py35_0    defaults
lazy-object-proxy         1.3.1            py35he996729_0    defaults
libiconv                  1.15                 h1df5818_7    defaults
libpng                    1.6.32               h140d38e_4    defaults
libxml2                   2.9.4                h41ea7b2_6    defaults
llvmdev                   3.9.1                   cling_4  [cling vc14]  conda-forge
lockfile                  0.12.2           py35h667c6d9_0    defaults
lzo                       2.10                 h6df0209_2    defaults
m2w64-binutils            2.25.1                        5    defaults
m2w64-bzip2               1.0.6                         6    defaults
m2w64-crt-git             5.0.0.4636.2595836               2    defaults
m2w64-gcc                 5.3.0                         6    defaults
m2w64-gcc-fortran         5.3.0                         6    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-headers-git         5.0.0.4636.c0ad18a               2    defaults
m2w64-isl                 0.16.1                        2    defaults
m2w64-libiconv            1.14                          6    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
m2w64-mpc                 1.0.3                         3    defaults
m2w64-mpfr                3.1.4                         4    defaults
m2w64-windows-default-manifest 6.4                           3    defaults
m2w64-winpthreads-git     5.0.0.4634.697f757               2    defaults
m2w64-zlib                1.2.8                        10    defaults
make                      3.82                          0    defaults
MarkupSafe                1.0                       <pip>
markupsafe                1.0              py35hc253e08_1    defaults
matplotlib                2.1.1            py35h2062329_0    defaults
mccabe                    0.6.1            py35hcf31250_1    defaults
memory_profiler           0.47             py35hcf15aca_0    defaults
mistune                   0.8.3                    py35_0    defaults
mkl                       2018.0.1             h2108138_4    defaults
monty                     0.9.6                     <pip>
msgpack-python            0.5.1            py35he980bc4_0    defaults
msys2-conda-epoch         20160418                      1    defaults
nb_anacondacloud          1.4.0                    py35_0    defaults
nb_conda                  2.2.0                    py35_0    defaults
nb_conda_kernels          2.1.0                    py35_0    defaults
nbconvert                 5.3.1            py35h98d6c46_0    defaults
nbformat                  4.4.0            py35h908c9d9_0    defaults
nbpresent                 3.0.2                    py35_0    defaults
notebook                  5.3.1                    py35_0    defaults
numexpr                   2.6.4            py35hb78e28a_0    defaults
numpy                     1.14.0           py35h4a99626_0    defaults
numpy                     1.13.0                    <pip>
openssl                   1.0.2n               h74b6da3_0    defaults
packaging                 16.8             py35h5fb721f_1    defaults
palettable                2.1.1                     <pip>
palettable                2.1.1                    py35_0    conda-forge
pandas                    0.22.0           py35h6538335_0    defaults
pandoc                    1.19.2.1             hb2460c7_1    defaults
pandocfilters             1.4.2            py35h978f723_1    defaults
parso                     0.1.1            py35he39c48a_0    defaults
path.py                   10.5             py35h3b5be1d_0    defaults
patsy                     0.5.0                    py35_0    defaults
pickleshare               0.7.4            py35h2f9f535_0    defaults
pip                       9.0.1            py35h691316f_4    defaults
pluggy                    0.6.0            py35h717ee57_0    defaults
progress                  1.3              py35ha84af61_0    defaults
progressbar2              3.34.3           py35hb4d8331_0    defaults
prompt_toolkit            1.0.15           py35h89c7cb4_0    defaults
psutil                    5.4.3            py35hfa6e2cd_0    defaults
py                        1.5.2            py35h4fcc378_0    defaults
pycparser                 2.18             py35h15a15da_1    defaults
PyDispatcher              2.0.5                     <pip>
pygments                  2.2.0            py35h24c0941_0    defaults
pylint                    1.8.1                    py35_0    defaults
pymatgen                  4.5.2                     <pip>
pympler                   0.5              py35h0fea292_0    defaults
pyopenssl                 17.5.0           py35h75c5b16_0    defaults
pyparsing                 2.2.0                     <pip>
pyparsing                 2.2.0            py35hcabcaab_1    defaults
pyqt                      5.6.0            py35hd46907b_5    defaults
pysocks                   1.6.7            py35hb30ac0d_1    defaults
pytables                  3.4.2            py35h9e98cc6_2    defaults
pytest                    3.3.2                    py35_0    defaults
pytest-runner             3.0              py35hfddb3e9_0    defaults
python                    3.5.4               h1357f44_23    defaults
python-dateutil           2.6.1            py35h6b299a3_1    defaults
python-utils              2.2.0                    py35_0    defaults
pytz                      2017.3           py35hb294b1a_0    defaults
pyyaml                    3.12             py35h4bf9689_1    defaults
PyYAML                    3.12                      <pip>
pyzmq                     16.0.3           py35h1861011_0    defaults
qt                        5.6.2           vc14h6f8c307_12  [vc14]  defaults
qtconsole                 4.3.1            py35hc47b0dd_0    defaults
requests                  2.18.4           py35h54a615f_1    defaults
requests                  2.12.3                    <pip>
rise                      4.0.0b1                  py35_1    damianavila82
scikit-learn              0.19.1           py35h2037775_0    defaults
scipy                     1.0.0            py35h75710e8_0    defaults
seaborn                   0.8.1            py35hc73483e_0    defaults
send2trash                1.4.2                    py35_0    defaults
setuptools                38.4.0                   py35_0    defaults
simplegeneric             0.8.1            py35h6406082_0    defaults
sip                       4.18.1           py35h01cbaa7_2    defaults
six                       1.11.0           py35hc1da2df_1    defaults
six                       1.11.0                    <pip>
spglib                    1.9.8.20                  <pip>
sqlite                    3.21.0               h9d3ae62_0    defaults
statsmodels               0.8.0            py35hfa6034c_0    defaults
tabulate                  0.7.7                     <pip>
testpath                  0.3.1            py35h06cf69e_0    defaults
tk                        8.6.7                hcb92d03_3    defaults
tornado                   4.5.3                    py35_0    defaults
traitlets                 4.3.2            py35h09b975b_0    defaults
urllib3                   1.22             py35h8cc84eb_0    defaults
vc                        14                   h0510ff6_3    defaults
vs2015_runtime            14.0.25123                    3    defaults
wcwidth                   0.1.7            py35h6e80d8a_0    defaults
webencodings              0.5.1            py35h5d527fb_1    defaults
Werkzeug                  0.12.2                    <pip>
wheel                     0.30.0           py35h38a90bc_1    defaults
widgetsnbextension        3.1.0                    py35_0    defaults
win_inet_pton             1.0.1            py35hbef1270_1    defaults
win_unicode_console       0.5              py35h56988b5_0    defaults
wincertstore              0.2              py35hfebbdb8_0    defaults
wrapt                     1.10.11          py35h54666f7_0    defaults
yaml                      0.1.7                hc54c509_2    defaults
zlib                      1.2.11               h8395fce_2    defaults
zope                      1.0                      py35_0    defaults
zope.interface            4.4.3            py35h57d3274_0    defaults
```
</p></details>

**Comment by mbkennel** [comment]
I also have this problem after upgrading conda packages.  The following workaround seems to have fixed it (starting from the Anaconda root directory)

``cp ./share/jupyter/kernels/python2/kernel.json lib/python2.7/site-packages/nb_conda_kernels/logos/python/``

**Comment by minrk** [comment]
This will be fixed by jupyter-client 5.2.2 (https://github.com/jupyter/jupyter_client/pull/339). It should also be fixed in nb_conda_kernels by defining `.get_all_specs()`.

**Comment by minrk** [comment]
jupyter-client 5.2.2 is out, fixing this issue. It should be available everywhere but conda-forge mac packages, due to the big Travis mac backlog.

**Comment by jaganmohan** [comment]
I am also getting similar issue with jupyter notebook after installing flask and `conda update`

```
conda info


     active environment : None
       user config file : /home/jazzy/.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : not installed
         python version : 2.7.15.final.0
       base environment : /data/jazzy/miniconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /data/jazzy/miniconda2/pkgs
                          /home/jazzy/.conda/pkgs
       envs directories : /data/jazzy/miniconda2/envs
                          /home/jazzy/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.19.1 CPython/2.7.15 Linux/3.19.0-51-generic ubuntu/14.04 glibc/2.19
                UID:GID : 1010:1010
             netrc file : None
           offline mode : False
```

```
[I 14:02:45.495 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
WARNING:root:kernel 8e593d3c-c364-41ba-8b2d-187c165c52ab restarted
Traceback (most recent call last):
  File "/data/jazzy/miniconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/data/jazzy/miniconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/data/jazzy/miniconda2/lib/python2.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/data/jazzy/miniconda2/lib/python2.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/data/jazzy/miniconda2/lib/python2.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/data/jazzy/miniconda2/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/data/jazzy/miniconda2/lib/python2.7/site-packages/IPython/core/application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "/data/jazzy/miniconda2/lib/python2.7/site-packages/traitlets/__init__.py", line 1, in <module>
    from .traitlets import *
  File "/data/jazzy/miniconda2/lib/python2.7/site-packages/traitlets/traitlets.py", line 43, in <module>
    import contextlib
  File "/data/jazzy/miniconda2/lib/python2.7/contextlib.py", line 4, in <module>
    from functools import wraps
  File "/data/jazzy/Embeddings/synonyms/utils/functools.py", line 5, in <module>
    import matplotlib
  File "/data/jazzy/miniconda2/lib/python2.7/site-packages/matplotlib/__init__.py", line 105, in <module>
    import six
  File "/data/jazzy/miniconda2/lib/python2.7/site-packages/six.py", line 662, in <module>
    iterbytes = functools.partial(itertools.imap, ord)
AttributeError: 'module' object has no attribute 'partial'
```
