### ISSUE TITLE
unable to launch Jupyter 

### ISSUE THREAD

**Issue by daxuyin** [jupyter/notebook#3254]
After upgrade Jupyter to version 5.3.1, I receive the following errors when launching Jupyter, either from command line or within Anaconda Navigator:

Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in 
from notebook.notebookapp import main
File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\__init__.py", line 25, in 
from .nbextensions import install_nbextension
File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\nbextensions.py", line 27, in 
from jupyter_core.utils import ensure_dir_exists
ImportError: cannot import name 'ensure_dir_exists'

Could anyone help?

**Comment by daxuyin** [comment]
Many thanks in advance,

**Comment by takluyver** [comment]
Update the Jupyter_core package as well (`conda update jupyter_core`). There was a dependency that got missed in the packaging. It should be fixed already by a newer version of the package.

**Comment by daxuyin** [comment]
It fixed the problem, thanks a lot.
