### ISSUE TITLE
ImportError: cannot import name 'Environment'

### ISSUE THREAD

**Issue by Shiv751** [jupyter/notebook#3332]
- python- 3.5.2
- win 7 64bit
- Jupyter Notebook installing issue

`Traceback (most recent call last):
  File "c:\users\sem\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sem\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\SEM\AppData\Local\Programs\Python\Python35\Scripts\jupyter-notebook.EXE\__main__.py", line 5, in <module>
  File "c:\users\sem\appdata\local\programs\python\python35\lib\site-packages\notebook\notebookapp.py", line 38, in <module>
    from jinja2 import Environment, FileSystemLoader
ImportError: cannot import name 'Environment'
`

**Comment by takluyver** [comment]
Do you have a file called `jinja2.py`? If so, Python is finding that instead of the real jinja2 package; you'll need to remove/rename it to make it work.

If it's not that, try uninstalling and reinstalling.

**Comment by Shiv751** [comment]
It doesn't working @takluyver 
Getting same error
`Traceback (most recent call last):
  File "c:\users\sem\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sem\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\SEM\AppData\Local\Programs\Python\Python35\Scripts\jupyter-notebook.EXE\__main__.py", line 5, in <module>
  File "c:\users\sem\appdata\local\programs\python\python35\lib\site-packages\notebook\notebookapp.py", line 38, in <module>
    from jinja2 import Environment, FileSystemLoader
ImportError: cannot import name 'Environment'
`

**Comment by takluyver** [comment]
Open a Python shell, do `import jinja2` and then `print(jinja2)` to see what file it's being loaded from. Make sure it's the real [Jinja2](https://pypi.python.org/pypi/Jinja2) package.

**Comment by aprudnik** [comment]
Hello, I have same issue on centos 7.
>>> from jinja2 import Environment, PackageLoader, select_autoescape
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name Environment
>>>
>>> print(jinja2)
<module 'jinja2' from '/usr/lib64/python2.7/site-packages/jinja2'>

If I run python shell with sudo then I am able to import Environment. Looks like some issue with permissions to the packaged. Don't know how it is possible to import jinja2 without sudo and not be able to import Environment.

**Comment by Shuai-Xie** [comment]
For me, the error is:
```
from jinja2 import Environment, FileSystemLoader
ImportError: cannot import name 'Environment'
```

**I solved it by downgrading `jinja2` from 2.9.6 to 2.8.**

**Comment by Dhrumil-Zion** [comment]
> 
> 
> For me, the error is:
> 
> ```
> from jinja2 import Environment, FileSystemLoader
> ImportError: cannot import name 'Environment'
> ```
> 
> **I solved it by downgrading `jinja2` from 2.9.6 to 2.8.**

which command you have used to do this ?

**Comment by Fida1316** [comment]
please help.
File "C:\Users\dell\Anaconda3\envs\uner\lib\site-packages\notebook\notebookapp.py", line 45, in <module>
    from jinja2 import Environment, FileSystemLoader
ImportError: cannot import name 'Environment'

**Comment by ruinabyss** [comment]
> Do you have a file called `jinja2.py`? If so, Python is finding that instead of the real jinja2 package; you'll need to remove/rename it to make it work.
> 
> If it's not that, try uninstalling and reinstalling.

thanks,bro i've benn searched many ways to do ，but you solve it with one word
