### ISSUE TITLE
Running Jupyter for the first time on pycharm : [Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by Younessk** [jupyter/notebook#3371]
Hello,
I am currently facing the error below when running Jupyter on pycharm :
"D:\Python\Python 3.5\python.exe" "D:\Python\PyCharm Community Edition 2017.3.3\helpers\pycharm\pycharm_load_entry_point.py" notebook --no-browser --ip 127.0.0.1:8888 --port 8888 --port-retries=0
[TerminalIPythonApp] WARNING | Subcommand `ipython notebook` is deprecated and will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter notebook` in the future
Traceback (most recent call last):
  File "D:\Python\PyCharm Community Edition 2017.3.3\helpers\pycharm\pycharm_load_entry_point.py", line 12, in <module>
    sys.exit(f())
  File "D:\Python\Python 3.5\lib\site-packages\IPython\__init__.py", line 119, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "D:\Python\Python 3.5\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-110>", line 2, in initialize
  File "D:\Python\Python 3.5\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "D:\Python\Python 3.5\lib\site-packages\IPython\terminal\ipapp.py", line 300, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "D:\Python\Python 3.5\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "D:\Python\Python 3.5\lib\site-packages\IPython\core\application.py", line 446, in initialize
    self.parse_command_line(argv)
  File "D:\Python\Python 3.5\lib\site-packages\IPython\terminal\ipapp.py", line 295, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "D:\Python\Python 3.5\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "D:\Python\Python 3.5\lib\site-packages\traitlets\config\application.py", line 514, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "D:\Python\Python 3.5\lib\site-packages\IPython\core\application.py", line 236, in initialize_subcommand
    return super(BaseIPythonApplication, self).initialize_subcommand(subc, argv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "D:\Python\Python 3.5\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "D:\Python\Python 3.5\lib\site-packages\traitlets\config\application.py", line 452, in initialize_subcommand
    self.subapp.initialize(argv)
  File "<decorator-gen-114>", line 2, in initialize
  File "D:\Python\Python 3.5\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "D:\Python\Python 3.5\lib\site-packages\notebook\notebookapp.py", line 1507, in initialize
    self.init_webapp()
  File "D:\Python\Python 3.5\lib\site-packages\notebook\notebookapp.py", line 1297, in init_webapp
    self.http_server.listen(port, self.ip)
  File "D:\Python\Python 3.5\lib\site-packages\tornado\tcpserver.py", line 142, in listen
    sockets = bind_sockets(port, address=address)
  File "D:\Python\Python 3.5\lib\site-packages\tornado\netutil.py", line 156, in bind_sockets
    0, flags)):
  File "D:\Python\Python 3.5\lib\socket.py", line 733, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

**Comment by takluyver** [comment]
Does it work running it outside Pycharm? The Pycharm interface to Jupyter is completely maintained by the Jetbrains team.

**Comment by Younessk** [comment]
Yes it does ! I have no issues with that

**Comment by takluyver** [comment]
OK, in that case you might want to investigate with Jetbrains support to see if this is something they're familiar with. Update us here if you find any more info!
