### ISSUE TITLE
ImportError: No module named paths

### ISSUE THREAD

**Issue by SimingYan** [jupyter/notebook#3402]
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/simy/.local/lib/python2.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/home/simy/.local/lib/python2.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/simy/.local/lib/python2.7/site-packages/ipykernel/connect.py", line 14, in <module>
    from IPython.paths import get_ipython_dir
ImportError: No module named paths

According to some previous issues. I think this information is useful. My pip version is 9.0.1. My ipython version is 2.4.1 and my jupyter version is 4.4.0.

**Comment by minrk** [comment]
IPython version should be at least 4.0 or 5.0. Try:

```
pip install --upgrade pip
pip install --upgrade ipython
```

**Comment by SimingYan** [comment]
I have done these commands before:
1.Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages
2.Successfully installed decorator-4.2.1 enum34-1.1.6 ipython-5.5.0 pexpect-4.4.0 ptyprocess-0.5.2 six-1.11.0

And I think the problem I need to solve now is that I am not a root user. Because I have installed the ipython 5.5 but what I use is ipython 2.4.1
