### ISSUE TITLE
Kernel error

### ISSUE THREAD

**Issue by Nemo900** [jupyter/notebook#3489]
Hi, 
I have a kernel error using jupyter through anaconda navigator. this is the message i received:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\web.py", line 1512, in _execute
    result = yield result
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\ProgramData\Anaconda2\lib\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\ProgramData\Anaconda2\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\ProgramData\Anaconda2\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\gen.py", line 307, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Anaconda2\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 148, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\jupyter_client\manager.py", line 258, in start_kernel
    **kw)
  File "C:\ProgramData\Anaconda2\lib\site-packages\jupyter_client\manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\ProgramData\Anaconda2\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\ProgramData\Anaconda2\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 267] The directory name is invalid

I tried to put "jupyter kernelspec list" on CMD but all I got is "'jupyter' is not recognized as an internal or external command, operable program or batch file"

**Comment by takluyver** [comment]
> I tried to put "jupyter kernelspec list" on CMD but all I got is...

On Windows, you probably need to start an 'Anaconda prompt' from the start menu. This is still CMD, but it sets some things up so that you can access Python commands.

**Comment by Nemo900** [comment]
@takluyver  Thanks for the reply. I tried to it in anaconda prompt and this is what I got:
![image](https://user-images.githubusercontent.com/38008847/38274025-2af0820a-3796-11e8-87ed-a4e2ad02a88e.png)

How do I continue from here?

**Comment by takluyver** [comment]
The easiest thing is probably just to delete that directory - it should fall back on running the kernel on the same version of Python that runs your notebook server.

If you've got time to investigate, I'd be interested to see what directory it's pointing to that is invalid. Look for a `kernel.json` in that folder.

**Comment by Nemo900** [comment]
I found the kernel.json file. Should I delete it?

**Comment by takluyver** [comment]
I think deleting it will probably fix the issue, but if you'd like to post the contents of that file first, it might provide some hint of what went wrong. That could be useful if other people report the same error.

**Comment by Nemo900** [comment]
![image](https://user-images.githubusercontent.com/38008847/38274854-ae5e2f3c-3798-11e8-8759-fb1aadc2ad4b.png)

**Comment by takluyver** [comment]
Thanks. There's nothing obviously wrong there. I wonder if this is the
wrong track. What's the directory where you're trying to create/open a
notebook? It might be a python 2 Unicode issue.

**Comment by Nemo900** [comment]
The problem was indeed a unicode issue, I had Hebrew in my directory so it didn't read it. 

Thank you so much for all your help!

**Comment by takluyver** [comment]
No problem. If possible, I'd recommend using Python 3 - it's generally better at things like this.
