### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by alaparthishivaji** [jupyter/notebook#3504]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-4a3efc4cbb3c> in <module>()
     10 from io import StringIO
     11 from matplotlib import pyplot as plt
---> 12 from PIL import Image
     13 
     14 # This is needed since the notebook is stored in the object_detection folder.

C:\anaconda\lib\site-packages\PIL\Image.py in <module>()
     56     # Also note that Image.core is not a publicly documented interface,
     57     # and should be considered private and subject to change.
---> 58     from . import _imaging as core
     59     if PILLOW_VERSION != getattr(core, 'PILLOW_VERSION', None):
     60         raise ImportError("The _imaging extension was built for another "

ImportError: DLL load failed: The specified module could not be found.

**Comment by takluyver** [comment]
You probably need to ask Pillow about that. Or possibly the packaging tool that you used to install it.

**Comment by alaparthishivaji** [comment]
File "<ipython-input-1-07fcd7cd3af4>", line 12, in <module>
    from PIL import Image

  File "C:\anaconda\lib\site-packages\PIL\Image.py", line 58, in <module>
    from . import _imaging as core

ImportError: DLL load failed: The specified module could not be found.

**Comment by alaparthishivaji** [comment]
File "<ipython-input-1-07fcd7cd3af4>", line 12, in <module>
    from PIL import Image

  File "C:\anaconda\lib\site-packages\PIL\Image.py", line 58, in <module>
    from . import _imaging as core

ImportError: DLL load failed: The specified module could not be found.

**Comment by aendrs** [comment]
Have you solved it? I´m having the same problem
