### ISSUE TITLE
Unable to launch notebook from terminal in windows

### ISSUE THREAD

**Issue by antcap96** [jupyter/notebook#3512]
when doing the command jupyter notebook i get the errors:

[C 22:07:21.051 NotebookApp] Bad config encountered during initialization:
[C 22:07:21.052 NotebookApp] Could not decode 'C:\\Users\\Ant\xf3nio\\.jupyter' for unicode trait 'config_dir' of a NotebookApp instance.

My user name is António (bad choice, I know), so I'm guessing that is causing a problem.

Is there a way I can solve this error?

Thank you

**Comment by takluyver** [comment]
If you're on Python 2, I'd strongly recommend upgrading to Python 3 - that fixes a lot of these errors. If you're already on Python 3, we can investigate further where that's coming from.

**Comment by antcap96** [comment]
Thanks for the timely response,

I was using python2. But now, I'm struggling to install jupyter on python3, as when I run the command `pip3 install notebook` I get the error


```
Running setup.py install for MarkupSafe ... error
Exception:
Traceback (most recent call last):
  File "c:\users\antónio\appdata\local\programs\python\python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 161: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\antónio\appdata\local\programs\python\python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "c:\users\antónio\appdata\local\programs\python\python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "c:\users\antónio\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "c:\users\antónio\appdata\local\programs\python\python36\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "c:\users\antónio\appdata\local\programs\python\python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "c:\users\antónio\appdata\local\programs\python\python36\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 161: invalid continuation byte
```

Is this still something you can help me with or should I go somewhere else?

**Comment by antcap96** [comment]
After changing the path environment variable so that python3 is before python2 I got it to work.
Thank you so much!
