### ISSUE TITLE
Fresh install of anaconda 64 bit on windows . When trying to open jupyter notebook , it is producing errors . 

### ISSUE THREAD

**Issue by ghost** [jupyter/notebook#3519]
[I 08:36:29.992 NotebookApp] The port 8888 is already in use, trying another port.
[I 08:36:29.992 NotebookApp] The port 8889 is already in use, trying another port.
[I 08:36:29.993 NotebookApp] The port 8890 is already in use, trying another port.
[I 08:36:33.029 NotebookApp] JupyterLab beta preview extension loaded from C:\Users\arora\Anaconda3\lib\site-packages\jupyterlab
[I 08:36:33.029 NotebookApp] JupyterLab application directory is C:\Users\arora\Anaconda3\share\jupyter\lab
[W 08:36:33.033 NotebookApp] Error loading server extension jupyterlab
Traceback (most recent call last):
File "C:\Users\arora\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 321, in __init__
self._run(['node', 'node-version-check.js'], cwd=HERE, quiet=True)
File "C:\Users\arora\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 1165, in _run
proc = Process(cmd, **kwargs)
File "C:\Users\arora\Anaconda3\lib\site-packages\jupyterlab\process.py", line 73, in __init__
self.proc = self._create_process(cwd=cwd, env=env)
File "C:\Users\arora\Anaconda3\lib\site-packages\jupyterlab\process.py", line 131, in _create_process
cmd[0] = which(cmd[0], kwargs.get('env'))
File "C:\Users\arora\Anaconda3\lib\site-packages\jupyterlab\jlpmapp.py", line 59, in which
raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\arora\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1454, in init_server_extensions
func(self)
File "C:\Users\arora\Anaconda3\lib\site-packages\jupyterlab\extension.py", line 111, in load_jupyter_server_extension
info = get_app_info(app_dir)
File "C:\Users\arora\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 244, in get_app_info
handler = _AppHandler(app_dir, logger)
File "C:\Users\arora\Anaconda3\lib\site-packages\jupyterlab\commands.py", line 324, in __init__
raise ValueError(msg)
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
[I 08:36:33.146 NotebookApp] Serving notebooks from local directory: C:\Users\arora
[I 08:36:33.146 NotebookApp] 0 active kernels
[I 08:36:33.146 NotebookApp] The Jupyter Notebook is running at:
[I 08:36:33.147 NotebookApp] http://localhost:8891/?token=bb87020b706de558d987fb40bdd2f7b9a5cdab7a1a32b55e
[I 08:36:33.147 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 08:36:33.151 NotebookApp] 

Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
http://localhost:8891/?token=bb87020b706de558d987fb40bdd2f7b9a5cdab7a1a32b55e
[I 08:36:33.232 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 08:36:37.828 NotebookApp] Creating new notebook in

**Comment by mikofski** [comment]
One of my coworkers is also experiencing this same issue. Apparently [according to this JupyterLab issue 3984](https://github.com/jupyterlab/jupyterlab/issues/3984) it _may_ be due to out of date jupyterlab extension. I am going to recommend to my coworker to try updating as the issue comments suggest.

Also related to this [Jupyter lab google group posting](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/86P4KQSZ0HU). Seems like updating is the recommendation.
