### ISSUE TITLE
Unhandled error in API request

### ISSUE THREAD

**Issue by kfergie** [jupyter/notebook#3538]
Hi,  

Thank you for any help!!! 

I haven't used my jupyter notebook for a while (was working before!), and now tried to get it working with matlab.  Now, and am now having trouble with both matlab *and* python kernels, getting an Unhandled error in API request.  I'm running on ubuntu 16.04, have updated my jupyter client, and have tried running through the localhost.  

jupyter kernelspec list  gives me: 

```
Available kernels:
  matlab     /home/katie/.local/share/jupyter/kernels/matlab
  python2    /home/katie/Software/anaconda2/share/jupyter/kernels/python2
```

My console errors look like this when I try running through python kernel: 

```
[E 16:30:09.663 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/notebook/base/handlers.py", line 516, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
        raise_exc_info(self._exc_info)
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 75, in post
        type=mtype))
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
        raise_exc_info(self._exc_info)
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
        raise_exc_info(self._exc_info)
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1107, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1099, in run
        value = future.result()
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 260, in result
        raise_exc_info(self._exc_info)
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 315, in wrapper
        yielded = next(result)
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/notebook/services/kernels/kernelmanager.py", line 94, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/jupyter_client/manager.py", line 258, in start_kernel
        self.start_restarter()
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/jupyter_client/ioloop/manager.py", line 52, in start_restarter
        self._restarter.start()
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/jupyter_client/ioloop/restarter.py", line 45, in start
        self.poll, 1000*self.time_to_dead, self.loop
    TypeError: __init__() takes exactly 3 arguments (4 given)
[E 16:30:09.664 NotebookApp] {
      "Content-Length": "92", 
      "Accept-Language": "en-US,en;q=0.5", 
      "Accept-Encoding": "gzip, deflate", 
      "X-Xsrftoken": "2|40595423|66227fc61f28454ed8a6eb2f54c16294|1523895785", 
      "X-Requested-With": "XMLHttpRequest", 
      "Host": "localhost:8888", 
      "Accept": "application/json, text/javascript, */*; q=0.01", 
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:59.0) Gecko/20100101 Firefox/59.0", 
      "Connection": "keep-alive", 
      "Referer": "http://localhost:8888/notebooks/Untitled8.ipynb?kernel_name=python2", 
      "Cookie": "_xsrf=2|40595423|66227fc61f28454ed8a6eb2f54c16294|1523895785; username-localhost-8889=\"2|1:0|10:1523906974|23:username-localhost-8889|44:ZTBjYWEyNDNlNjY2NDJmODhjODljZDhhZTY3NjU4N2I=|6679cb45a10b83b4d8ab96358a0fd858acd4721208aa57dc462f1f8ade497414\"; username-localhost-8888=\"2|1:0|10:1523910605|23:username-localhost-8888|44:MDk3ZGY2YjY2NDVmNDhiM2FkZDgwZDQwMjdlM2IxMGE=|8462dfe9e2e4a48fb12dba2a511ffdb55a45c31157aa2d98d867acb89c9b8b96\"", 
      "Content-Type": "application/json"
    }
[E 16:30:09.664 NotebookApp] 500 POST /api/sessions (127.0.0.1) 20.12ms referer=http://localhost:8888/notebooks/Untitled8.ipynb?kernel_name=python2
```

**Comment by takluyver** [comment]
This is the crucial part of the traceback:

```
      File "/home/katie/Software/anaconda2/lib/python2.7/site-packages/jupyter_client/ioloop/restarter.py", line 45, in start
        self.poll, 1000*self.time_to_dead, self.loop
    TypeError: __init__() takes exactly 3 arguments (4 given)
```

It must be loading an old version of jupyter_client, because it points to line 45, and that file in the latest version (5.2.3) only has [44 lines](https://github.com/jupyter/jupyter_client/blob/5.2.3/jupyter_client/ioloop/restarter.py). Try upgrading it again, making sure you're in the root conda environment (deactivate any other conda env). If it still doesn't work, then it's probably easiest to uninstall and reinstall Anaconda.

**Comment by kfergie** [comment]
The uninstall/reinstall of Anaconda worked great! Thanks for your help! :)

**Comment by Carreau** [comment]
> The uninstall/reinstall of Anaconda worked great! Thanks for your help! :)

Great ! Closing. Feel free to ask if reopening is necessary.
