### ISSUE TITLE
[jupyter notebook launch error!] I got select.error: (10038, '')

### ISSUE THREAD

**Issue by cucum13er** [jupyter/notebook#3548]
![jupyter_error](https://user-images.githubusercontent.com/17548194/39031614-e48d6612-449b-11e8-80a2-e75eb6bb0bbc.png)
(CS682) C:\Users\cucum>jupyter notebook
[I 12:06:57.032 NotebookApp] Serving notebooks from local directory: C:\Users\cucum
[I 12:06:57.032 NotebookApp] 0 active kernels
[I 12:06:57.032 NotebookApp] The Jupyter Notebook is running at:
[I 12:06:57.032 NotebookApp] http://localhost:8888/?token=cee6e2ea13dbbf22bf8eedc155135b1ee06969bf8a0c3218
[I 12:06:57.032 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 12:06:57.032 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=cee6e2ea13dbbf22bf8eedc155135b1ee06969bf8a0c3218
[I 12:06:57.766 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 12:06:58.631 NotebookApp] Shutting down 0 kernels
Traceback (most recent call last):
  File "C:\Users\cucum\AppData\Local\conda\conda\envs\CS682\Scripts\jupyter-notebook-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\cucum\AppData\Local\conda\conda\envs\CS682\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\cucum\AppData\Local\conda\conda\envs\CS682\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\cucum\AppData\Local\conda\conda\envs\CS682\lib\site-packages\notebook\notebookapp.py", line 1636, in start
    self.io_loop.start()
  File "C:\Users\cucum\AppData\Local\conda\conda\envs\CS682\lib\site-packages\tornado\ioloop.py", line 863, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "C:\Users\cucum\AppData\Local\conda\conda\envs\CS682\lib\site-packages\tornado\platform\select.py", line 63, in poll
    self.read_fds, self.write_fds, self.error_fds, timeout)
select.error: (10038, '')

When I tried to launch jupyter notebook in terminal, it usually comes this error. Then I will get ERR_CONNECTION_REFUSED by my chrome browser(get a blank page). But not always, if I continuously type this command, there is about 20 percent chance of successfully launching. 
I am using windows 10 and anaconda3. I create the environment CS682 in python2.7.
I have tried to change the tornado package version into 5.0.1, 5.0.0 and 4.5.1. still not work. 

Thank you for your time!

**Comment by takluyver** [comment]
@bdarnell sorry to bother you again, any ideas on this? I found https://github.com/tornadoweb/tornado/issues/1360 , but it looks like that's specifically to do with tornado autoreload, which we don't use (AFAIK). Thanks!

**Comment by bdarnell** [comment]
tornadoweb/tornado#1360 is related to what happens if you close an IOLoop while it's running. Autoreload is one way that could happen (in older versions of Tornado - it hasn't been true since 4.2), but not the only way. 

I don't know anything else about what might cause this. Maybe using PipeIOStream?
