### ISSUE TITLE
Unable to open Jupyter Notebook from Command Prompt (Ubuntu 16.04) 

### ISSUE THREAD

**Issue by harrypotter0** [jupyter/notebook#3565]
Hi,

I'm having issues opening Jupyter Notebook with Command Prompt. I'm on Ubuntu 16.04. When i tried typing jupyter notebook in my command prompt, this appears and notebook does not open anywhere:

Any help would be greatly appreciated, thank you!
### Actual Behavior
Not opening

### Expected Behavior
Should have opened.

### Steps to Reproduce

After installing anaconda , just use this `jupyter notebook`

##### Operating System:
Ubuntu 16.04

Here is the error in command prompt ::
[I 18:06:07.386 NotebookApp] The port 8888 is already in use, trying another port.
[I 18:06:07.387 NotebookApp] The port 8889 is already in use, trying another port.
[I 18:06:07.387 NotebookApp] The port 8890 is already in use, trying another port.
[I 18:06:07.387 NotebookApp] The port 8891 is already in use, trying another port.
[I 18:06:07.387 NotebookApp] The port 8892 is already in use, trying another port.
[I 18:06:07.388 NotebookApp] The port 8892 is already in use, trying another port.
[I 18:06:07.426 NotebookApp] JupyterLab alpha preview extension loaded from /home/harrypotter0/anaconda2/lib/python2.7/site-packages/jupyterlab
JupyterLab v0.27.0
Known labextensions:
[I 18:06:07.427 NotebookApp] Running the core application with no additional extensions or settings
[I 18:06:07.432 NotebookApp] Serving notebooks from local directory: /home/harrypotter0/Documents/W2VecGOT
[I 18:06:07.432 NotebookApp] 0 active kernels 
[I 18:06:07.432 NotebookApp] The Jupyter Notebook is running at: http://localhost:8958/?token=1558ac68accfad8409287f039e50ff6cf1b1f5878d39ce73
[I 18:06:07.432 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 18:06:07.433 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8958/?token=1558ac68accfad8409287f039e50ff6cf1b1f5878d39ce73
[I 18:06:07.899 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[E 18:06:07.935 NotebookApp] Uncaught exception GET /tree?token=355ef28c2c4b0d560482eadb4ada5e424706aa97f0b49dd1 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8958', method='GET', uri='/tree?token=355ef28c2c4b0d560482eadb4ada5e424706aa97f0b49dd1', version='HTTP/1.1', remote_ip='127.0.0.1', headers={'Accept-Language': 'en-US,en;q=0.9', 'Accept-Encoding': 'gzip, deflate, br', 'Host': 'localhost:8958', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36', 'Connection': 'keep-alive', 'Cookie': '_xsrf=2|2e4fb38e|dd2d1047db9aa117030755b8897e415a|1524657969; username-localhost-8888="2|1:0|10:1524657969|23:username-localhost-8888|44:NjhiMmVkZDRjM2IzNDk5ZDk2MTc2NjIxM2YwNmQ4YzA=|b4cb2c8f7055ab468f84e59e2bd3c2a18b6c79cd37a7e800da2dcca25ed61938"; username-localhost-8889="2|1:0|10:1524658586|23:username-localhost-8889|44:MWRhZjhjNGJhYWE3NDBiYThlZWRkOWE0ZjAyN2QzNGE=|67ac2fb74f815329eddd54ae11ad6c08b203efd840104620f95f09dca82efba9"; username-localhost-8890="2|1:0|10:1524658902|23:username-localhost-8890|44:MjZjZDQ4YjdhZTUxNDE0OTgwMjhiMmEwYmEzZDVkZTc=|9ea250ba6dbea9ebce087bcfb5fe76eaa36f70fad110dff5790c408b1ac6fa95"; username-localhost-8891="2|1:0|10:1524659155|23:username-localhost-8891|44:NmU5ZDEwOWFiNmE5NDZiZmI2ZWI1NDM3NDYxOTk2NTE=|276426ae02ab92ec80b525a7c220d15137dc6b1024cfb33c9a04a0d842ef6834"; username-localhost-8892="2|1:0|10:1524659381|23:username-localhost-8892|44:MzFlMjg1MDIxN2U2NDBhNjk2NzliODk2ZmZhZmZhNDU=|d56ff8ae9da1d7e492253c0f91fc61ba4c9b495b3eba4174c5c8ea9c2330bc7f"; username-localhost-8884="2|1:0|10:1524659531|23:username-localhost-8884|44:N2VmY2EwNTViMThkNDhiNTg0ZWQ2MzE0OWUyZDVjYWM=|3ed099dacc93b454be3a3630c1af2a292cea90f5f36d28009236ec2d6970cbef"; username-localhost-8980="2|1:0|10:1524659542|23:username-localhost-8980|44:ZTkyNTVkMTcyNzQ1NDYwMjlhYmUxNmM3MDU5MjVhMTQ=|8e6a8c185b9ce099a9c9819d6a89e87891db417071f29b31bdaea2f5797fc048"; username-localhost-8865="2|1:0|10:1524659726|23:username-localhost-8865|44:YThjMjY4NjU4YWY5NDk5MmI5YTk1ZTAwZTMxMmMyNmE=|703b4387df59bf47a9e5ced60651bf421a990e058103227b0d9de3632046add3"', 'Upgrade-Insecure-Requests': '1'})
    Traceback (most recent call last):
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 1509, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 2897, in wrapper
        return method(self, *args, **kwargs)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/notebook/tree/handlers.py", line 53, in get
        server_root=self.settings['server_root_dir'],
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/notebook/base/handlers.py", line 347, in render_template
        template = self.get_template(name)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/notebook/base/handlers.py", line 343, in get_template
        return self.settings['jinja2_env'].get_template(name)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/jinja2/environment.py", line 719, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/jinja2/environment.py", line 693, in _load_template
        template = self.loader.load(self, name, globals)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/jinja2/loaders.py", line 127, in load
        code = environment.compile(source, name, filename)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/jinja2/environment.py", line 493, in compile
        self.handle_exception(exc_info, source_hint=source)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/notebook/templates/tree.html", line 8, in template
        data-base-url="{{base_url | urlencode}}"
    TemplateAssertionError: no filter named 'urlencode'
[16453:16472:0425/180607.991377:ERROR:browser_gpu_channel_host_factory.cc(119)] Failed to launch GPU process.
[E 18:06:07.996 NotebookApp] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 1036, in send_error
        self.write_error(status_code, **kwargs)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/notebook/base/handlers.py", line 416, in write_error
        html = self.render_template('error.html', **ns)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/notebook/base/handlers.py", line 348, in render_template
        return template.render(**ns)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/jinja2/environment.py", line 894, in render
        return self.environment.handle_exception(exc_info, True)
      File "/home/harrypotter0/anaconda2/lib/python2.7/site-packages/notebook/templates/page.html", line 107, in template
        data-jupyter-api-token="{{token | urlencode}}"
    TemplateAssertionError: no filter named 'urlencode'
[E 18:06:07.997 NotebookApp] {
      "Accept-Language": "en-US,en;q=0.9", 
      "Accept-Encoding": "gzip, deflate, br", 
      "Host": "localhost:8958", 
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8", 
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36", 
      "Connection": "keep-alive", 
      "Cookie": "_xsrf=2|2e4fb38e|dd2d1047db9aa117030755b8897e415a|1524657969; username-localhost-8888=\"2|1:0|10:1524657969|23:username-localhost-8888|44:NjhiMmVkZDRjM2IzNDk5ZDk2MTc2NjIxM2YwNmQ4YzA=|b4cb2c8f7055ab468f84e59e2bd3c2a18b6c79cd37a7e800da2dcca25ed61938\"; username-localhost-8889=\"2|1:0|10:1524658586|23:username-localhost-8889|44:MWRhZjhjNGJhYWE3NDBiYThlZWRkOWE0ZjAyN2QzNGE=|67ac2fb74f815329eddd54ae11ad6c08b203efd840104620f95f09dca82efba9\"; username-localhost-8890=\"2|1:0|10:1524658902|23:username-localhost-8890|44:MjZjZDQ4YjdhZTUxNDE0OTgwMjhiMmEwYmEzZDVkZTc=|9ea250ba6dbea9ebce087bcfb5fe76eaa36f70fad110dff5790c408b1ac6fa95\"; username-localhost-8891=\"2|1:0|10:1524659155|23:username-localhost-8891|44:NmU5ZDEwOWFiNmE5NDZiZmI2ZWI1NDM3NDYxOTk2NTE=|276426ae02ab92ec80b525a7c220d15137dc6b1024cfb33c9a04a0d842ef6834\"; username-localhost-8892=\"2|1:0|10:1524659381|23:username-localhost-8892|44:MzFlMjg1MDIxN2U2NDBhNjk2NzliODk2ZmZhZmZhNDU=|d56ff8ae9da1d7e492253c0f91fc61ba4c9b495b3eba4174c5c8ea9c2330bc7f\"; username-localhost-8884=\"2|1:0|10:1524659531|23:username-localhost-8884|44:N2VmY2EwNTViMThkNDhiNTg0ZWQ2MzE0OWUyZDVjYWM=|3ed099dacc93b454be3a3630c1af2a292cea90f5f36d28009236ec2d6970cbef\"; username-localhost-8980=\"2|1:0|10:1524659542|23:username-localhost-8980|44:ZTkyNTVkMTcyNzQ1NDYwMjlhYmUxNmM3MDU5MjVhMTQ=|8e6a8c185b9ce099a9c9819d6a89e87891db417071f29b31bdaea2f5797fc048\"; username-localhost-8865=\"2|1:0|10:1524659726|23:username-localhost-8865|44:YThjMjY4NjU4YWY5NDk5MmI5YTk1ZTAwZTMxMmMyNmE=|703b4387df59bf47a9e5ced60651bf421a990e058103227b0d9de3632046add3\"", 
      "Upgrade-Insecure-Requests": "1"
    }
[E 18:06:07.997 NotebookApp] 500 GET /tree?token=355ef28c2c4b0d560482eadb4ada5e424706aa97f0b49dd1 (127.0.0.1) 98.62ms referer=None
Created new window in existing browser session.
^Z
[9]+  Stopped                 jupyter notebook

##### `conda info`

```

     active environment : None
       user config file : /home/harrypotter0/.condarc
 populated config files : 
          conda version : 4.5.1
    conda-build version : 3.0.27
         python version : 2.7.14.final.0
       base environment : /home/harrypotter0/anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/harrypotter0/anaconda2/pkgs
                          /home/harrypotter0/.conda/pkgs
       envs directories : /home/harrypotter0/anaconda2/envs
                          /home/harrypotter0/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.1 requests/2.18.4 CPython/2.7.14 Linux/4.13.0-36-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : /home/harrypotter0/.netrc
           offline mode : False


```

##### `conda list --show-channel-urls`

```
# packages in environment at /home/harrypotter0/anaconda2:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py27h08a7f0c_0    defaults
alabaster                 0.7.10           py27he5a193a_0    defaults
anaconda                  custom           py27h4a00acb_0    defaults
anaconda-client           1.6.5            py27hc8169bf_0    defaults
anaconda-navigator        1.6.9            py27hfbc306d_0    defaults
anaconda-project          0.8.0            py27hd7a9a97_0    defaults
argparse                  1.2.1                     <pip>
asn1crypto                0.22.0           py27h94ebe91_1    defaults
astroid                   1.5.3            py27h8f8f47c_0    defaults
astropy                   2.0.2            py27h57072c0_4    defaults
autoflake                 1.1                       <pip>
autopep8                  1.3.4                     <pip>
babel                     2.5.0            py27h20693cd_0    defaults
backports                 1.0              py27h63c9359_1    defaults
backports.functools_lru_cache 1.4              py27he8db605_1    defaults
backports.shutil_get_terminal_size 1.0.0            py27h5bc021e_2    defaults
backports.weakref         1.0rc1                    <pip>
backports_abc             0.5              py27h7b3c97b_0    defaults
beautifulsoup4            4.6.0            py27h3f86ba9_1    defaults
bitarray                  0.8.1            py27h304d4c6_0    defaults
bkcharts                  0.2              py27h241ae91_0    defaults
blaze                     0.11.3           py27h5f341da_0    defaults
bleach                    2.0.0            py27h3a0dcc8_0    defaults
bleach                    1.5.0                     <pip>
blinker                   1.2                       <pip>
bokeh                     0.12.10          py27he46cc6b_0    defaults
boto                      2.48.0           py27h9556ac2_1    defaults
bottleneck                1.2.1            py27h21b16a3_0    defaults
bzip2                     1.0.6                h0376d23_1    defaults
ca-certificates           2018.03.07                    0    defaults
cairo                     1.14.10              haa5651f_5    defaults
cdecimal                  2.3              py27h4e63abe_1    defaults
certifi                   2018.4.16                py27_0    defaults
cffi                      1.10.0           py27hf1aaaf4_1    defaults
chardet                   3.0.4            py27hfa10054_1    defaults
click                     6.7              py27h4225b90_0    defaults
cloudpickle               0.4.0            py27ha64365b_0    defaults
clyent                    1.2.2            py27h7276e6c_1    defaults
colorama                  0.3.9            py27h5cde069_0    defaults
conda                     4.5.1                    py27_0    defaults
conda-build               3.0.27           py27hff9f855_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
conda-verify              2.0.0            py27hf052a9d_0    defaults
configparser              3.5.0            py27h5117587_0    defaults
contextlib2               0.5.5            py27hbf4c468_0    defaults
cryptography              2.0.3            py27hea39389_1    defaults
curl                      7.55.1               hcb0b314_2    defaults
cx-Freeze                 5.1.1                     <pip>
cycler                    0.10.0           py27hc7354d3_0    defaults
cython                    0.26.1           py27hdbcff32_0    defaults
cytoolz                   0.8.2            py27hf14aec9_0    defaults
dask                      0.15.3           py27hb94b45f_0    defaults
dask-core                 0.15.3           py27h53a7ee6_0    defaults
datashape                 0.5.4            py27hf507385_0    defaults
dbus                      1.10.22              h3b5a359_0    defaults
decorator                 4.1.2            py27h1544723_0    defaults
distributed               1.19.1           py27h38c4a05_0    defaults
dj-database-url           0.4.2                     <pip>
django-appconf            1.0.2                     <pip>
django-compressor         2.2                       <pip>
docformatter              0.8                       <pip>
docutils                  0.14             py27hae222c1_0    defaults
entrypoints               0.2.3            py27h502b47d_2    defaults
enum34                    1.1.6            py27h99a27e9_1    defaults
et_xmlfile                1.0.1            py27h75840f5_0    defaults
expat                     2.2.4                hc00ebd1_1    defaults
fake-useragent            0.1.8                     <pip>
fastcache                 1.0.2            py27h4cb8e01_0    defaults
filelock                  2.0.12           py27h38fa839_0    defaults
Flask                     0.9                       <pip>
flask                     0.12.2           py27h6d5c1cd_0    defaults
Flask-Admin               1.0.4                     <pip>
Flask-Bootstrap           2.2.2.post1               <pip>
Flask-Cache               0.10.1                    <pip>
flask-cors                3.0.3            py27h1a8a27f_0    defaults
Flask-FlatPages           0.3                       <pip>
Flask-Gravatar            0.2.4                     <pip>
Flask-Images              2.1.2                     <pip>
Flask-Login               0.1.3                     <pip>
Flask-Mail                0.7.4                     <pip>
Flask-PyMongo             0.2.1                     <pip>
Flask-Restless            0.9.1                     <pip>
Flask-SQLAlchemy          0.16                      <pip>
Flask-Themes              0.1.3                     <pip>
Flask-Uploads             0.1.3                     <pip>
Flask-WTF                 0.8.2                     <pip>
fontconfig                2.12.4               h88586e7_1    defaults
freetype                  2.8                  h52ed37b_0    defaults
funcsigs                  1.0.2            py27h83f16ab_0    defaults
funcsigs                  1.0.2                     <pip>
functools32               3.2.3.2          py27h4ead58f_1    defaults
futures                   3.1.1            py27hdbc8cbb_0    defaults
get_terminal_size         1.0.0                haa9412d_0    defaults
gevent                    1.2.2            py27h475ea6a_0    defaults
gitdb                     0.6.4                     <pip>
GitPython                 0.3.6                     <pip>
glib                      2.53.6               hc861d11_1    defaults
glob2                     0.5              py27hd3b7d1f_1    defaults
gmp                       6.1.2                hb3b607b_0    defaults
gmpy2                     2.0.8            py27hc856308_1    defaults
graphite2                 1.3.10               hc526e54_0    defaults
greenlet                  0.4.12           py27hac09c53_0    defaults
grin                      1.2.1            py27h54abee7_1    defaults
gst-plugins-base          1.12.2               he3457e5_0    defaults
gstreamer                 1.12.2               h4f93127_0    defaults
gunicorn                  19.7.1                    <pip>
h5py                      2.7.0            py27h71d1790_1    defaults
harfbuzz                  1.5.0                h2545bd6_0    defaults
hdf5                      1.10.1               hb0523eb_0    defaults
heapdict                  1.0.0            py27h33770af_0    defaults
html5lib                  0.999999999      py27hdf15f34_0    defaults
html5lib                  0.9999999                 <pip>
icu                       58.2                 h211956c_0    defaults
idna                      2.6              py27h5722d68_1    defaults
imageio                   2.2.0            py27hf108a7f_0    defaults
imagesize                 0.7.1            py27hd17bf80_0    defaults
intel-openmp              2018.0.0             h15fc484_7    defaults
ipaddress                 1.0.18           py27h337fd85_0    defaults
ipykernel                 4.6.1            py27hc93e584_0    defaults
ipython                   5.4.1            py27h36c99b6_1    defaults
ipython_genutils          0.2.0            py27h89fb69b_0    defaults
ipywidgets                7.0.0            py27h4fda95d_0    defaults
isort                     4.2.15           py27hcfa4749_0    defaults
itsdangerous              0.24             py27hb8295c1_1    defaults
jbig                      2.1                  hdba287a_0    defaults
jdcal                     1.3              py27h2cc5433_0    defaults
jedi                      0.10.2           py27h8af4e35_0    defaults
Jinja2                    2.6                       <pip>
jinja2                    2.9.6            py27h82327ae_1    defaults
jpeg                      9b                   habf39ab_1    defaults
jsonschema                2.6.0            py27h7ed5aa4_0    defaults
jupyter                   1.0.0                    py27_4    defaults
jupyter                   1.0.0                     <pip>
jupyter_client            5.2.3                    py27_0    defaults
jupyter_console           5.2.0            py27hc6bee7e_1    defaults
jupyter_core              4.4.0            py27h345911c_0    defaults
jupyterlab                0.27.0           py27h42ebfef_2    defaults
jupyterlab_launcher       0.4.0            py27h0e16d15_0    defaults
lazy-object-proxy         1.3.1            py27h682c727_0    defaults
libedit                   3.1                  heed3624_0    defaults
libffi                    3.2.1                h4deb6c0_3    defaults
libgcc-ng                 7.2.0                h7cc24e2_2    defaults
libgfortran-ng            7.2.0                h9f7466a_2    defaults
libpng                    1.6.32               hda9c8bc_2    defaults
libsodium                 1.0.13               h31c71d8_2    defaults
libssh2                   1.8.0                h8c220ad_2    defaults
libstdcxx-ng              7.2.0                h7a57d05_2    defaults
libtiff                   4.0.8                h90200ff_9    defaults
libtool                   2.4.6                hd50d1a6_0    defaults
libxcb                    1.12                 h84ff03f_3    defaults
libxml2                   2.9.4                h6b072ca_5    defaults
libxslt                   1.1.29               hcf9102b_5    defaults
llvmlite                  0.20.0                   py27_0    defaults
locket                    0.2.0            py27h73929a2_1    defaults
lxml                      4.1.0            py27hb025457_0    defaults
lzo                       2.10                 h1bfc0ba_1    defaults
Markdown                  2.2.1                     <pip>
markupsafe                1.0              py27h97b2822_1    defaults
matplotlib                2.1.0            py27h09aba24_0    defaults
mccabe                    0.6.1            py27h0e7c7be_1    defaults
mistune                   0.7.4            py27h6da7e90_0    defaults
mkl                       2018.0.0             hb491cac_4    defaults
mkl-service               1.1.2            py27hb2d42c5_4    defaults
mock                      2.0.0                     <pip>
mpc                       1.0.3                hf803216_4    defaults
mpfr                      3.1.5                h12ff648_1    defaults
mpl-finance               0.10.0                    <pip>
mpmath                    0.19             py27h4bb41bd_2    defaults
msgpack-python            0.4.8            py27hc2fa789_0    defaults
multipledispatch          0.4.9            py27h9b5f95a_0    defaults
navigator-updater         0.1.0            py27h0f9cd39_0    defaults
nbconvert                 5.3.1            py27he041f76_0    defaults
nbformat                  4.4.0            py27hed7f2b2_0    defaults
ncurses                   6.0                  h06874d7_1    defaults
networkx                  2.0              py27hfc23926_0    defaults
nltk                      3.2.4            py27h41293c3_0    defaults
nose                      1.3.7            py27heec2199_2    defaults
notebook                  5.0.0            py27h3661c2b_2    defaults
numba                     0.35.0             np113py27_10    defaults
numexpr                   2.6.2            py27he5efce1_1    defaults
numpy                     1.14.0                    <pip>
numpy                     1.13.3           py27hbcc08e0_0    defaults
numpydoc                  0.7.0            py27h9647a75_0    defaults
oauthlib                  2.0.6                     <pip>
odo                       0.5.1            py27h9170de3_0    defaults
olefile                   0.44             py27h4bd3e3c_0    defaults
openpyxl                  2.4.8            py27h9f0c937_1    defaults
openssl                   1.0.2o               h20670df_0    defaults
packaging                 16.8             py27h5e07c7c_1    defaults
pandas                    0.20.3           py27h820b67f_2    defaults
pandas-datareader         0.5.0                     <pip>
pandoc                    1.19.2.1             hea2e7c5_1    defaults
pandocfilters             1.4.2            py27h428e1e5_1    defaults
pango                     1.40.11              h8191d47_0    defaults
partd                     0.3.8            py27h4e55004_0    defaults
patchelf                  0.9                  hf79760b_2    defaults
path.py                   10.3.1           py27hc258cac_0    defaults
pathlib2                  2.3.0            py27h6e9d198_0    defaults
patsy                     0.4.1            py27hd1cf8c0_0    defaults
pbr                       3.1.1                     <pip>
pcre                      8.41                 hc71a17e_0    defaults
pep8                      1.7.0            py27h444351c_0    defaults
pexpect                   4.2.1            py27hcf82287_0    defaults
pickleshare               0.7.4            py27h09770e1_0    defaults
PIL                       1.1.7                     <pip>
pillow                    4.2.1            py27h7cd2321_0    defaults
pillowcase                2.0.0                     <pip>
pip                       9.0.3                     <pip>
pip                       9.0.1            py27hbf658b2_3    defaults
pixman                    0.34.0               h83dc358_2    defaults
pkginfo                   1.4.1            py27hee1a9ad_1    defaults
ply                       3.10             py27hd6d9ae5_0    defaults
prompt_toolkit            1.0.15           py27h1b593e1_0    defaults
protobuf                  3.5.1                     <pip>
psutil                    5.4.0            py27h7da3062_0    defaults
ptyprocess                0.5.2            py27h4ccb14c_0    defaults
py                        1.4.34           py27he5894e4_1    defaults
pycairo                   1.13.3           py27hea6d626_0    defaults
pycodestyle               2.3.1            py27h904819d_0    defaults
pycosat                   0.6.3            py27ha4109ae_0    defaults
pycparser                 2.18             py27hefa08c5_1    defaults
pycrypto                  2.6.1            py27h9abbf5c_1    defaults
pycurl                    7.43.0           py27hcf8ebea_3    defaults
pyflakes                  1.6.0            py27h904a57d_0    defaults
pyformat                  0.7                       <pip>
pygments                  2.2.0            py27h4a8b6f5_0    defaults
pylint                    1.7.4            py27h6bc7935_0    defaults
pymongo                   2.5.1                     <pip>
pyodbc                    4.0.17           py27h7f7627d_0    defaults
pyopenssl                 17.2.0           py27h189ff3b_0    defaults
pyparsing                 2.2.0            py27hf1513f8_1    defaults
pyqt                      5.6.0            py27h4b1e83c_5    defaults
pysocks                   1.6.7            py27he2db6d2_1    defaults
pytables                  3.4.2            py27h1f7bffc_2    defaults
pytest                    3.2.1            py27h98000ae_1    defaults
python                    2.7.14              hc2b0042_21    defaults
python-dateutil           2.6.1            py27h4ca5741_1    defaults
python-dateutil           2.7.2                     <pip>
pytz                      2017.2           py27hcac29fa_1    defaults
pywavelets                0.5.2            py27hecda097_0    defaults
PyYAML                    3.10                      <pip>
pyyaml                    3.12             py27h2d70dd7_1    defaults
pyzmq                     16.0.2           py27h297844f_2    defaults
qt                        5.6.2               h974d657_12    defaults
qtawesome                 0.4.4            py27hd7914c3_0    defaults
qtconsole                 4.3.1            py27hc444b0d_0    defaults
qtpy                      1.3.1            py27h63d3751_0    defaults
rcssmin                   1.0.6                     <pip>
readline                  7.0                  hac23ff0_3    defaults
requests                  2.6.0                     <pip>
requests                  2.18.4           py27hc5b0589_1    defaults
requests-file             1.4.3                     <pip>
requests-ftp              0.3.1                     <pip>
requests-oauthlib         0.8.0                     <pip>
rjsmin                    1.0.12                    <pip>
rope                      0.10.5           py27hcb0a616_0    defaults
ruamel_yaml               0.11.14          py27h672d447_2    defaults
scandir                   1.6              py27hf7388dc_0    defaults
scikit-image              0.13.0           py27h06cb35d_1    defaults
scikit-learn              0.19.1           py27h445a80a_0    defaults
scipy                     0.19.1           py27h1edc525_3    defaults
seaborn                   0.8.0            py27h9d2aaa1_0    defaults
selenium                  3.8.0                    py27_0    conda-forge
setuptools                36.5.0           py27h68b189e_0    defaults
setuptools                38.4.0                    <pip>
simplegeneric             0.8.1            py27h19e43cd_0    defaults
singledispatch            3.4.0.3          py27h9bcb476_0    defaults
sip                       4.18.1           py27he9ba0ab_2    defaults
six                       1.11.0           py27h5f960f1_1    defaults
six                       1.11.0                    <pip>
snowballstemmer           1.2.1            py27h44e2768_0    defaults
sortedcollections         0.5.3            py27h135218e_0    defaults
sortedcontainers          1.5.7            py27he59936f_0    defaults
sphinx                    1.6.3            py27hf9b1778_0    defaults
sphinxcontrib             1.0              py27h1512b58_1    defaults
sphinxcontrib-websupport  1.0.1            py27hf906f22_1    defaults
spyder                    3.2.4            py27h04a3490_0    defaults
SQLAlchemy                0.8.0b2                   <pip>
sqlalchemy                1.1.13           py27hb0a01da_0    defaults
sqlite                    3.20.1               h6d8b0f3_1    defaults
ssl_match_hostname        3.5.0.1          py27h4ec10b9_2    defaults
statsmodels               0.8.0            py27hc87d62d_0    defaults
subprocess32              3.2.7            py27h373dbce_0    defaults
sympy                     1.1.1            py27hc28188a_0    defaults
tblib                     1.3.2            py27h51fe5ba_0    defaults
tensorflow                1.2.0                     <pip>
terminado                 0.6              py27h4be8df9_0    defaults
testpath                  0.3.1            py27hc38d2c4_0    defaults
textblob                  0.15.1                    <pip>
tk                        8.6.7                h5979e9b_1    defaults
toolz                     0.8.2            py27hd3b1e7e_0    defaults
tornado                   4.5.2            py27h97b179f_0    defaults
traitlets                 4.3.2            py27hd6ce930_0    defaults
tweepy                    3.5.0                     <pip>
typing                    3.6.2            py27h66f49e2_0    defaults
unicodecsv                0.14.1           py27h5062da9_0    defaults
unify                     0.4                       <pip>
unixodbc                  2.3.4                hc36303a_1    defaults
untokenize                0.1.1                     <pip>
urllib3                   1.22             py27ha55213b_0    defaults
wcwidth                   0.1.7            py27h9e3e1ab_0    defaults
webencodings              0.5.1            py27hff10b21_1    defaults
Werkzeug                  0.8.3                     <pip>
werkzeug                  0.12.2           py27hbf75dff_0    defaults
wheel                     0.29.0           py27h411dd7b_1    defaults
wheel                     0.30.0                    <pip>
whitenoise                3.3.1                     <pip>
widgetsnbextension        3.0.2            py27hcb77dec_1    defaults
wrapt                     1.10.11          py27h04f6869_0    defaults
WTForms                   1.0.3                     <pip>
xlrd                      1.1.0            py27ha77178f_1    defaults
xlsxwriter                1.0.2            py27h12cbc6b_0    defaults
xlwt                      1.3.0            py27h3d85d97_0    defaults
xz                        5.2.3                h2bcbf08_1    defaults
yaml                      0.1.7                h96e3832_1    defaults
zeromq                    4.2.2                hb0b69da_1    defaults
zict                      0.1.3            py27h12c336c_0    defaults
zlib                      1.2.11               hfbfcf68_1    defaults

```

**Comment by takluyver** [comment]
The conda list says you've got notebook 5.0 - try upgrading to a newer version.

**Comment by harrypotter0** [comment]
How to do that ? 
I have tried `sudo pip install --upgrade ipython[all]` but this is not upgrading it .

**Comment by takluyver** [comment]
Try `conda update notebook`

**Comment by harrypotter0** [comment]
Updated with the above command to 5.4.1 but it's still not opening.

**Comment by takluyver** [comment]
Oh, you've somehow got two versions of Jinja2 installed - 2.6 and 2.9.6. The `urlencode` filter was new in 2.7. So you'll need to find and remove the 2.6 version.

**Comment by harrypotter0** [comment]
Thanks for your efforts. After updating the jinja2 using pip I got it working :smiley:

**Comment by harrypotter0** [comment]
Thanks for your efforts. After updating the jinja2 using pip I got it working :smiley:
