### ISSUE TITLE
Failed to start vernal  in MAC

### ISSUE THREAD

**Issue by liceblone** [jupyter/notebook#3568]
KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tornado/ioloop.py", line 288, in current
    return IOLoop._ioloop_for_asyncio[loop]
KeyError: <asyncio.unix_events._UnixSelectorEventLoop object at 0x10444d048>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 171, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ipykernel/kernelapp.py", line 465, in initialize
    self.init_kernel()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ipykernel/kernelapp.py", line 364, in init_kernel
    shell_stream = ZMQStream(self.shell_socket)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zmq/eventloop/zmqstream.py", line 108, in __init__
    self.io_loop = io_loop or IOLoop.instance()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/zmq/eventloop/ioloop.py", line 105, in instance
    loop = ioloop.IOLoop.instance(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tornado/ioloop.py", line 221, in instance
    return IOLoop.current()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tornado/ioloop.py", line 292, in current
    current = AsyncIOMainLoop(make_current=True)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tornado/util.py", line 312, in __new__
    instance.initialize(*args, **init_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tornado/platform/asyncio.py", line 182, in initialize
    super(AsyncIOMainLoop, self).initialize(asyncio.get_event_loop(), **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tornado/platform/asyncio.py", line 53, in initialize
    if loop.is_closed():
AttributeError: '_UnixSelectorEventLoop' object has no attribute 'is_closed'
[W 00:12:24.092 NotebookApp] Timeout waiting for kernel_info reply from 4076a9a3-562c-48a3-836d-8f92ddd13bb3

**Comment by takluyver** [comment]
We had another report of that recently - #3544. You need either a newer version of Python, or an older (<5) version of Tornado.

**Comment by rjurney** [comment]
What is being done about this? Jupyter notebook isn't working for me.

**Comment by takluyver** [comment]
> You need either a newer version of Python, or an older (<5) version of Tornado.

If you're seeing that error and upgrading Python is not an option, you need to remove tornado and `pip install tornado<5`.
