### ISSUE TITLE
Lunching jupyter notebook form cmd i face this problem, how to fix it? 

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [jupyter/notebook#3570]
```
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\jupyter-notebook-script.py", line 3, in <module>
    import notebook.notebookapp
  File "C:\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 72, in <module>
    from .base.handlers import Template404, RedirectWithParams
  File "C:\Anaconda3\lib\site-packages\notebook\base\handlers.py", line 42, in <module>
    sys_info = json.dumps(get_sys_info())
  File "C:\Anaconda3\lib\site-packages\notebook\_sysinfo.py", line 94, in get_sys_info
    return pkg_info(path)
  File "C:\Anaconda3\lib\site-packages\notebook\_sysinfo.py", line 76, in pkg_info
    src, hsh = pkg_commit_hash(pkg_path)
  File "C:\Anaconda3\lib\site-packages\notebook\_sysinfo.py", line 52, in pkg_commit_hash
    cwd=pkg_path, shell=True)
  File "C:\Anaconda3\lib\subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "C:\Anaconda3\lib\subprocess.py", line 990, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by MuhammadAsadJaved** [comment]
Ok Thank you very much @takluyver
