### ISSUE TITLE
Error installing jupyter notebook in ubuntu 14.04 Python version 3.4.3

### ISSUE THREAD

**Issue by md-jamal** [jupyter/notebook#3585]
jamal@jamal:~/Udacity$ pip3 install jupyter notebook
Downloading/unpacking jupyter
  Downloading jupyter-1.0.0-py2.py3-none-any.whl
Downloading/unpacking notebook
  Downloading notebook-5.4.1-py2.py3-none-any.whl (8.0MB): 8.0MB downloaded
Downloading/unpacking ipywidgets (from jupyter)
  Downloading ipywidgets-7.2.1-py2.py3-none-any.whl (106kB): 106kB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2482, in _dep_map
    return self.__dep_map
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2344, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1266, in prepare_files
    req_to_install.extras):
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2291, in requires
    dm = self._dep_map
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2484, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2508, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2573, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'widgetsnbextension ~=3.2.0', 'at', ' ~=3.2.0')

Storing debug log for failure in /home/jamal/.pip/pip.log

**Comment by takluyver** [comment]
Try upgrading pip and setuptools first:

```
pip install --upgrade setuptools pip
```

**Comment by md-jamal** [comment]
Thanks.. Running the command with sudo solved the issue

**Comment by takluyver** [comment]
Using `sudo pip install` is generally not recommended - it's better to do `pip install --user` and install packages for only your user account. But I'm glad you got it working.
