### ISSUE TITLE
kernel dead

### ISSUE THREAD

**Issue by ZhengMengbin** [jupyter/notebook#3596]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\web.py", line 1512, in _execute
    result = yield result
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\ProgramData\Anaconda2\lib\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\ProgramData\Anaconda2\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\ProgramData\Anaconda2\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "C:\ProgramData\Anaconda2\lib\site-packages\tornado\gen.py", line 307, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Anaconda2\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 148, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\jupyter_client\manager.py", line 258, in start_kernel
    **kw)
  File "C:\ProgramData\Anaconda2\lib\site-packages\jupyter_client\manager.py", line 203, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\ProgramData\Anaconda2\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\ProgramData\Anaconda2\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] 

Can somebody help me to fix it?

**Comment by ZhengMengbin** [comment]
I had fixed it, you can see https://blog.csdn.net/qq_21368481/article/details/80211624
