### ISSUE TITLE
jupyter notebook crash

### ISSUE THREAD

**Issue by eloiup** [jupyter/notebook#3602]
Hi!

I ve found many related open/closed issues. 
some fixes worked (temporarily) but the issue always comes back.

I apologize in advance if there are any ideal solutions which i did not encounter

The problem:
Suddenly my notebook just crashes and i am unable to run any new notebooks until i restart jupyter. (cant create new notebooks without an error msg)

The error msg:

> Traceback (most recent call last):
  File "/home/atayne/anaconda2/lib/python2.7/site-packages/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/home/atayne/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/atayne/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/atayne/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/atayne/anaconda2/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 73, in post
    type=mtype))
  File "/home/atayne/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/atayne/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/atayne/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/atayne/anaconda2/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/home/atayne/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/atayne/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/atayne/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/atayne/anaconda2/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/home/atayne/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/atayne/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/atayne/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 307, in wrapper
    yielded = next(result)
  File "/home/atayne/anaconda2/lib/python2.7/site-packages/notebook/services/kernels/kernelmanager.py", line 148, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/home/atayne/anaconda2/lib/python2.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/home/atayne/anaconda2/lib/python2.7/site-packages/jupyter_client/manager.py", line 239, in start_kernel
    self.write_connection_file()
  File "/home/atayne/anaconda2/lib/python2.7/site-packages/jupyter_client/connect.py", line 472, in write_connection_file
    kernel_name=self.kernel_name
  File "/home/atayne/anaconda2/lib/python2.7/site-packages/jupyter_client/connect.py", line 137, in write_connection_file
    with open(fname, 'w') as f:
IOError: [Errno 2] No such file or directory: u'/run/user/1000/jupyter/kernel-c1acdf6f-b9df-4e37-86d5-a9dae2aad4be.json'

using ubuntu

Ty for any help/advice!

ps: 
dir /run/user/1000 exists
sub dir jupyter doesnt.

**Comment by eloiup** [comment]
fixed.

just created the /run/user/1000/jupyter directory
