### ISSUE TITLE
Building the js files results in: Error: Cannot find module 'requirejs'

### ISSUE THREAD

**Issue by jonathanunderwood** [jupyter/notebook#3643]
With version 5.5.0, I observe the following output when running `python3 setup.py js`. It seems that the packages under `notebook/static/components/` aren't being used, somehow.

```
$ python3 setup.py js
running js
running jsdeps
bower dependencies up to date
/home/jgu/Fedora/python-notebook/notebook-5.5.0/notebook/static/notebook/js/mathjaxutils.js /home/jgu/Fedora/python-notebook/notebook-5.5.0/notebook/static/notebook/js/main.min.js
Rebuilding /home/jgu/Fedora/python-notebook/notebook-5.5.0/notebook/static/notebook/js/main.min.js
> node tools/build-main.js notebook
/home/jgu/Fedora/python-notebook/notebook-5.5.0/notebook/static/base/js/namespace.js /home/jgu/Fedora/python-notebook/notebook-5.5.0/notebook/static/terminal/js/main.min.js
/home/jgu/Fedora/python-notebook/notebook-5.5.0/notebook/static/base/js/namespace.js /home/jgu/Fedora/python-notebook/notebook-5.5.0/notebook/static/edit/js/main.min.js
Rebuilding /home/jgu/Fedora/python-notebook/notebook-5.5.0/notebook/static/terminal/js/main.min.js
/home/jgu/Fedora/python-notebook/notebook-5.5.0/notebook/static/base/js/namespace.js /home/jgu/Fedora/python-notebook/notebook-5.5.0/notebook/static/tree/js/main.min.js
Rebuilding /home/jgu/Fedora/python-notebook/notebook-5.5.0/notebook/static/edit/js/main.min.js
> node tools/build-main.js terminal
Rebuilding /home/jgu/Fedora/python-notebook/notebook-5.5.0/notebook/static/tree/js/main.min.js
> node tools/build-main.js edit
> node tools/build-main.js tree
module.js:549
    throw err;
    ^

Error: Cannot find module 'requirejs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jgu/Fedora/python-notebook/notebook-5.5.0/tools/build-main.js:4:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
module.js:549
    throw err;
    ^

Error: Cannot find module 'requirejs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jgu/Fedora/python-notebook/notebook-5.5.0/tools/build-main.js:4:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
/home/jgu/Fedora/python-notebook/notebook-5.5.0/notebook/static/base/js/namespace.js /home/jgu/Fedora/python-notebook/notebook-5.5.0/notebook/static/auth/js/main.min.js
Rebuilding /home/jgu/Fedora/python-notebook/notebook-5.5.0/notebook/static/auth/js/main.min.js
> node tools/build-main.js auth
module.js:549
    throw err;
    ^

Error: Cannot find module 'requirejs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jgu/Fedora/python-notebook/notebook-5.5.0/tools/build-main.js:4:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
module.js:549
    throw err;
    ^

Error: Cannot find module 'requirejs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jgu/Fedora/python-notebook/notebook-5.5.0/tools/build-main.js:4:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
module.js:549
    throw err;
    ^

Error: Cannot find module 'requirejs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jgu/Fedora/python-notebook/notebook-5.5.0/tools/build-main.js:4:11)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
Traceback (most recent call last):
  File "setup.py", line 150, in <module>
    main()
  File "setup.py", line 147, in main
    setup(**setup_args)
  File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/jgu/Fedora/python-notebook/notebook-5.5.0/setupbase.py", line 534, in run
    pool.map(self.build_main, self.apps)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/jgu/Fedora/python-notebook/notebook-5.5.0/setupbase.py", line 527, in build_main
    run(['node', 'tools/build-main.js', name])
  File "/home/jgu/Fedora/python-notebook/notebook-5.5.0/setupbase.py", line 338, in run
    return check_call(cmd, *args, **kwargs)
  File "/usr/lib64/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['node', 'tools/build-main.js', 'notebook']' returned non-zero exit status 1.
```

**Comment by hroncok** [comment]
Note that this has been a problem in Fedora (I've managed to know about but ignore) for a while, not just with 5.5.0.
