### ISSUE TITLE
Unable to start Jupyter Notebook from Terminal.

### ISSUE THREAD

**Issue by ktiwari9** [jupyter/notebook#3695]
Step-1: Checking for Anaconda Version

```
kshitij@kshitij-XPS:~$ conda list anaconda$
/home/kshitij/anaconda2/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.3.0) doesn't match a supported version!
  RequestsDependencyWarning)
# packages in environment at /home/kshitij/anaconda2:
#
# Name                    Version                   Build  Channel
anaconda                  5.2.0                    py27_3
```

Step-2: Running Jupyter Notebook from Terminal

```
kshitij@kshitij-XPS:~$ jupyter notebook
Traceback (most recent call last):
  File "/home/kshitij/anaconda2/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/home/kshitij/anaconda2/lib/python2.7/site-packages/notebook/notebookapp.py", line 45, in <module>
    from zmq.eventloop import ioloop
  File "/usr/lib/python2.7/dist-packages/zmq/__init__.py", line 66, in <module>
    from zmq import backend
  File "/usr/lib/python2.7/dist-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/usr/lib/python2.7/dist-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/usr/lib/python2.7/dist-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/usr/lib/python2.7/dist-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name constants
```
Step-3: Checking Pip Version
```
kshitij@kshitij-XPS:~$ pip -V
/home/kshitij/anaconda2/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.3.0) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/home/kshitij/anaconda2/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 14, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 30, in <module>
    from pip._vendor.retrying import retry
ImportError: No module named retrying
kshitij@kshitij-XPS:~$ 

```

Hack-1: Tried using notebook via PyCharm Edu Edition (also FAILED)

```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 38, in <module>
    from jinja2 import Environment, FileSystemLoader
ImportError: No module named jinja2

Process finished with exit code 1
```

It used to work before but I think after I tried to play with tensorflow installation, some environment variables were changed and things messed up. Could someone please help? Need to use Jupyter Notebooks urgently.

**Comment by takluyver** [comment]
Make sure `pyzmq` is installed in anaconda; it's trying to import it from your system Python installation instead.

**Comment by ktiwari9** [comment]
I had anaconda3 installed for python3 before. I just deleted it. Downloaded a fresh shell file from Anaconda website and ran the file using the `bash Anaconda2-5.2.0-Linux-x86_64.sh` command. So, how do I check if that has pyzmq or not?

**Comment by takluyver** [comment]
If you've done a fresh install, it should have pyzmq. Also check if PYTHONPATH has been set - that can mess things up.

**Comment by ktiwari9** [comment]
In my .bashrc I found these:
```
## Fix the path to find ros dist-packages
export PYTHONPATH=$PYTHONPATH:/usr/lib/python2.7/dist-packages
# added by Anaconda2 installer
export PATH="/home/kshitij/anaconda2/bin:$PATH"
```

Are these what we expect?

**Comment by takluyver** [comment]
The first one (setting PYTHONPATH) is probably breaking stuff for Anaconda, because it puts your system packages ahead of Anaconda in import priority. PYTHONPATH is a crude tool, unfortunately, especially when you have multiple Pythons on your system.

**Comment by takluyver** [comment]
The order won't make any difference. Removing the first one will (probably) fix it for Anaconda, but may break stuff for ROS. Sorry, I can't work out a proper solution for your particular setup.

**Comment by ktiwari9** [comment]
I tried reordering/removing as well, but I still have the exact same problem.

**Comment by Ian-An** [comment]
same issue here on ubuntu 16
