### ISSUE TITLE
Jupyter Notebook 500 Server Error when trying to open file to run

### ISSUE THREAD

**Issue by mkjudge** [jupyter/notebook#3792]
C:\Users\Melissa Judge>jupyter notebook
[I 08:45:45.776 NotebookApp] Loading IPython parallel extension
[I 08:45:45.933 NotebookApp] Serving notebooks from local directory: C:\Users\Melissa Judge
[I 08:45:45.933 NotebookApp] The Jupyter Notebook is running at:
[I 08:45:45.933 NotebookApp] http://localhost:8888/?token=36e23c8aad0bbb0e96c8e17c13f0019858ae8e273de661cb
[I 08:45:45.934 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 08:45:45.937 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=36e23c8aad0bbb0e96c8e17c13f0019858ae8e273de661cb
[I 08:45:46.082 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[E 08:45:58.694 NotebookApp] Uncaught exception GET /notebooks/Documents/MATLAB/Bassett%20Lab/Geodesic%20Distance(Left%20noforloop).ipynb (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/notebooks/Documents/MATLAB/Bassett%20Lab/Geodesic%20Distance(Left%20noforloop).ipynb', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "c:\python27\lib\site-packages\tornado\web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "c:\python27\lib\site-packages\tornado\web.py", line 3006, in wrapper
        return method(self, *args, **kwargs)
      File "c:\python27\lib\site-packages\notebook\notebook\handlers.py", line 59, in get
        get_custom_frontend_exporters=get_custom_frontend_exporters
      File "c:\python27\lib\site-packages\notebook\base\handlers.py", line 463, in render_template
        return template.render(**ns)
      File "c:\python27\lib\site-packages\jinja2\environment.py", line 1008, in render
        return self.environment.handle_exception(exc_info, True)
      File "c:\python27\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "c:\python27\lib\site-packages\notebook\templates\notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "c:\python27\lib\site-packages\notebook\templates\page.html", line 154, in top-level template code
        {% block header %}
      File "c:\python27\lib\site-packages\notebook\templates\notebook.html", line 120, in block "header"
        {% for exporter in get_custom_frontend_exporters() %}
      File "c:\python27\lib\site-packages\notebook\notebook\handlers.py", line 19, in get_custom_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
      File "c:\python27\lib\site-packages\nbconvert\__init__.py", line 4, in <module>
        from .exporters import *
      File "c:\python27\lib\site-packages\nbconvert\exporters\__init__.py", line 3, in <module>
        from .exporter_locator import export_by_name
      File "c:\python27\lib\site-packages\nbconvert\exporters\exporter_locator.py", line 12, in <module>
        from .templateexporter import TemplateExporter
      File "c:\python27\lib\site-packages\nbconvert\exporters\templateexporter.py", line 22, in <module>
        from nbconvert import filters
      File "c:\python27\lib\site-packages\nbconvert\filters\__init__.py", line 3, in <module>
        from .datatypefilter import *
      File "c:\python27\lib\site-packages\nbconvert\filters\datatypefilter.py", line 20, in <module>
        from ..utils.base import NbConvertBase
    ImportError: No module named utils.base
[E 08:45:58.711 NotebookApp] {
      "Accept-Language": "en-US,en;q=0.9",
      "Accept-Encoding": "gzip, deflate, br",
      "Host": "localhost:8888",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36",
      "Connection": "keep-alive",
      "Referer": "http://localhost:8888/tree/Documents/MATLAB/Bassett%20Lab",
      "Cookie": "_xsrf=2|4b289e53|fb7e7555904840593f92a128261577a9|1531335640; username-localhost-8889=\"2|1:0|10:1532350884|23:username-localhost-8889|44:Y2Y4Y2FhNDA3MDUxNDc1YmFmMDdlYTJlODg0NzBmNjM=|88e58e4761674345967ab445748ba31e8004991e48db932e426245eb406a83cd\"; username-localhost-8888=\"2|1:0|10:1532436346|23:username-localhost-8888|44:ZDYyY2JlNzgxYTgwNGIyYmEwNjA3ZjZlNjU2NWJkYjY=|892d07b089a15135eacacbf498e55166a764bc1412f68b265f7793ad5715fafd\"",
      "Upgrade-Insecure-Requests": "1"
    }
[E 08:45:58.714 NotebookApp] 500 GET /notebooks/Documents/MATLAB/Bassett%20Lab/Geodesic%20Distance(Left%20noforloop).ipynb (::1) 158.00ms referer=http://localhost:8888/tree/Documents/MATLAB/Bassett%20Lab

**Comment by Geoyi** [comment]
Never mind, I read through this StackOverflow post, and did `pip install --upgrade --user nbconvert`. It solved the problem.
