### ISSUE TITLE
Cannot Save Existing Notebook 

### ISSUE THREAD

**Issue by kelleyjbrady** [jupyter/notebook#3807]
I am unable to save notebooks that I have previously worked with (although i can open them). The directories in question exist, I have verified this by using `pushd` to access the folder mentioned in the save error below, then listing the files with `ls` (powershell)

Things I have tried that do not fix the issue:
  - Restarting Computer
  - Uninstall Jupyter extensions
  - Uninstall/Reinstall Jupyter
  - Attempt to edit in Jupyterlab (Doest work either)
  - Launch an administrator cmd, then launch Jupyter Notebook

## ls Results

     Directory: \\company\root2\UserDocs\kbrady\My Documents\Git Repos\Study-11-GI2

    Mode                LastWriteTime         Length Name
    ----                -------------         ------ ----
    d-----        7/24/2018  11:01 AM                .ipynb_checkpoints
    d-----        7/20/2018  12:58 PM                bioflash
    d-----        7/20/2018  12:45 PM                histone
    d-----        7/24/2018  10:59 AM                Legacy Data
    d-----        7/20/2018  12:45 PM                output_quantalyzer
    d-----         7/3/2018   2:24 PM                output_quatalyzer
    d-----        7/20/2018  12:46 PM                pdf
    d-----        7/23/2018   4:43 PM                phadia
    d-----        7/20/2018  12:45 PM                quantalyzer
    d-----        7/27/2018  10:51 AM                TSQL
    -a----        7/20/2018  12:45 PM            734 .gitattributes
    -a----        7/20/2018  12:45 PM            977 .gitignore
    -a----        7/27/2018  10:02 AM        1232469 bioflash_prepared.csv
    -a----        7/24/2018  11:17 AM         280727 df2.csv
    -a----        7/25/2018  12:33 PM          47036 drugs.csv
    -a----        7/27/2018  12:33 PM         167766 drugs_merged.csv
    -a----        7/27/2018  12:33 PM         115421 drugs_tall.csv
    -a----        7/23/2018   4:55 PM        6368098 joined.csv
    -a----        7/26/2018   4:08 PM           5798 med_counts.csv
    -a----        7/27/2018   3:24 PM          18027 med_counts.xlsx
    -a----        7/27/2018  10:53 AM          14929 Parse Bioflash Exports.ipynb
    -a----        7/27/2018   3:27 PM          37982 Parse Legacy Data.ipynb
    -a----        7/27/2018  10:53 AM         248491 Parse RD Quantalyzer General.ipynb
    -a----        7/27/2018  10:52 AM           8434 Phadia Parser.ipynb
    -a----        7/27/2018  10:38 AM         261126 prepared_quantalyser.csv
    -a----        7/27/2018  10:48 AM        1645588 prepped_phadia.csv
    -a----        7/27/2018  10:27 AM          74688 quanta_dup.csv
    -a----        7/27/2018  10:02 AM            194 repeated_bioflash.csv

## Start up

    [I 10:45:46.302 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.0
    [I 10:45:46.358 NotebookApp] JupyterLab beta preview extension loaded from 
    C:\tools\Anaconda3\lib\site-packages\jupyterlab
    [I 10:45:46.358 NotebookApp] JupyterLab application directory is 
    C:\tools\Anaconda3\share\jupyter\lab
    [I 10:45:46.967 NotebookApp] Serving notebooks from local directory: U:\UserDocs\kbrady\My Documents
    [I 10:45:46.967 NotebookApp] 0 active kernels
    [I 10:45:46.968 NotebookApp] The Jupyter Notebook is running at:
    [I 10:45:46.968 NotebookApp] http://localhost:8888/?token=37a5f3106fbbcda62817a819f73f9655dca29e8599800bd6
    [I 10:45:46.968 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
    [C 10:45:46.972 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
    http://localhost:8888/token=37a5f3106fbbcda62817a819f73f9655dca29e8599800bd6&token=37a5f316fbbcda62817a819f73f9655dca29e8599800bd6
    [I 10:45:47.331 NotebookApp] Accepting one-time-token-authenticated connection from ::1
    [I 10:46:03.610 NotebookApp] Kernel started: fc5bec84-51f6-471d-afe4-c5de6eb8f78f
    [I 10:46:06.788 NotebookApp] Adapting to protocol v5.1 for kernel fc5bec84-51f6-471d-afe4-c5de6eb8f78f

## Attempt to Save

    Saving file at /Git Repos/Study-11-GI2/Parse Legacy Data.ipynb
    [E 10:46:10.889 NotebookApp] Error while saving file: Git Repos/Study-11-GI2/Parse Legacy Data.ipynb 
    [Errno 2] No such file or directory: 'U:\\UserDocs\\kbrady\\My Documents\\Git Repos\\Study-11-GI2\\.~Parse Legacy Data.ipynb'
        Traceback (most recent call last):
          File "C:\tools\Anaconda3\lib\site-packages\notebook\services\contents\filemanager.py", line 471, in save
            self._save_notebook(os_path, nb)
          File "C:\tools\Anaconda3\lib\site-packages\notebook\services\contents\fileio.py", line 293, in _save_notebook
            with self.atomic_writing(os_path, encoding='utf-8') as f:
          File "C:\tools\Anaconda3\lib\contextlib.py", line 81, in __enter__
            return next(self.gen)
          File "C:\tools\Anaconda3\lib\site-packages\notebook\services\contents\fileio.py", line 213, in atomic_writing
            with atomic_writing(os_path, *args, log=self.log, **kwargs) as f:
          File "C:\tools\Anaconda3\lib\contextlib.py", line 81, in __enter__
            return next(self.gen)
          File "C:\tools\Anaconda3\lib\site-packages\notebook\services\contents\fileio.py", line 103, in atomic_writing
            copy2_safe(path, tmp_path, log=log)
          File "C:\tools\Anaconda3\lib\site-packages\notebook\services\contents\fileio.py", line 51, in copy2_safe
            shutil.copyfile(src, dst)
          File "C:\tools\Anaconda3\lib\shutil.py", line 121, in copyfile
           with open(dst, 'wb') as fdst:
        FileNotFoundError: [Errno 2] No such file or directory: 'U:\\UserDocs\\kbrady\\My Documents\\Git Repos\\Study-11-GI2\\.~Parse Legacy Data.ipynb'
    [W 10:46:10.889 NotebookApp] 500 PUT /api/contents/Git%20Repos/Study-11-GI2/Parse%20Legacy%20Data.ipynb (::1): Unexpected error while saving file: Git Repos/Study-11-GI2/Parse Legacy Data.ipynb [Errno 2] No such file or directory: 'U:\\UserDocs\\kbrady\\My Documents\\Git Repos\\Study-11-GI2\\.~Parse Legacy Data.ipynb'
    [W 10:46:10.889 NotebookApp] Unexpected error while saving file: Git Repos/Study-11-GI2/Parse Legacy Data.ipynb [Errno 2] No such file or directory: 'U:\\UserDocs\\kbrady\\My Documents\\Git Repos\\Study-11-GI2\\.~Parse Legacy Data.ipynb'
    [E 10:46:10.889 NotebookApp] {
          "Host": "localhost:8888",
          "Connection": "keep-alive",
          "Content-Length": "31237",
          "Accept": "application/json, text/javascript, */*; q=0.01",
          "Origin": "http://localhost:8888",
          "X-Requested-With": "XMLHttpRequest",
          "X-Xsrftoken": "2|29e9a3f2|8327dbe28e34d88fff5f4e5a346f4489|1531935385",
          "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36",
          "Content-Type": "application/json",
          "Referer": "http://localhost:8888/notebooks/Git%20Repos/Study-11-GI2/Parse%20Legacy%20Data.ipynb",
          "Accept-Encoding": "gzip, deflate, br",
          "Accept-Language": "en-US,en;q=0.9",
          "Cookie": "_xsrf=2|29e9a3f2|8327dbe28e34d88fff5f4e5a346f4489|1531935385; username-localhost-8889=\"2|1:0|10:1532972448|23:username-localhost-8889|44:ZDNiZTIxZTdhNTEwNDMzNmIzMmQzNTkzNDYxZmJiOTU=|fa60dda004318c294a202dbace94b9f7ed26dd8e64a4ce4f4655cce8123fbc4d\"; username-localhost-8888=\"2|1:0|10:1532972747|23:username-localhost-8888|44:YjVjY2RkZGZkZDg1NGU3ODhlNTQzMzAyYzRkNmE4Zjc=|9b905ba2effd098cc05d7251008d4c7d2d024d0722f9ee378743e20a7434fdef\""
    }
    [E 10:46:10.889 NotebookApp] 500 PUT /api/contents/Git%20Repos/Study-11-GI2/Parse%20Legacy%20Data.ipynb (::1) 619.02ms referer=http://localhost:8888/notebooks/Git%20Repos/Study-11-GI2/Parse%20Legacy%20Data.ipynb

**Comment by kelleyjbrady** [comment]
This has something to do with my network file system, the problem is not unique to jupyter. Thank you to anyone who took a look at this.
