### ISSUE TITLE
Jupyter Conda tab installation failed in EC2 (Deep learning AMI)

### ISSUE THREAD

**Issue by mirocody** [jupyter/notebook#3815]
Hello, 

I got an issue while installing packages through conda. 
Steps to reproduce: 
1. Create notebook. (With configuration mentioned here. https://docs.aws.amazon.com/dlami/latest/devguide/setup-jupyter-configure-server.html)
2. Go to the conda tab. 
3. try and install mysql(or some other package) to the python2 kernel(or other kernel). 
Then it shows:
```
An error occurred while installing packages.
Internal Server Error
```
In the terminal, I got
```
[W 00:36:26.479 NotebookApp] [nb_conda] JSON parse fail:
    Extra data: line 2 column 1 (char 77)
[E 00:36:26.480 NotebookApp] Uncaught exception POST /conda/environments/python3/packages/install (127.0.0.1)
    HTTPServerRequest(protocol='https', host='127.0.0.1:8157', method='POST', uri='/conda/environments/python3/packages/install', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/tornado/web.py", line 1541, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/tornado/web.py", line 2949, in wrapper
        return method(self, *args, **kwargs)
      File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/notebook/base/handlers.py", line 716, in wrapper
        return method(self, *args, **kwargs)
      File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/nb_conda/handlers.py", line 136, in post
        resp = self.env_manager.install_packages(env, packages)
      File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/nb_conda/envmanager.py", line 160, in install_packages
        return self.clean_conda_json(output)
      File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/nb_conda/envmanager.py", line 101, in clean_conda_json
        lines = [line for line in lines if re.match(JSONISH_RE)]
      File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/nb_conda/envmanager.py", line 101, in <listcomp>
        lines = [line for line in lines if re.match(JSONISH_RE)]
    TypeError: match() missing 1 required positional argument: 'string'
[W 00:36:26.482 NotebookApp] Unhandled error
[E 00:36:26.483 NotebookApp] {
      "Host": "127.0.0.1:8157",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|cee34e7f|0513fedcd5194fd65683eb14d150ba0f|1533157020",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate",
      "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
      "Origin": "https://127.0.0.1:8157",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15",
      "Referer": "https://127.0.0.1:8157/tree?",
      "Content-Length": "24",
      "Connection": "keep-alive",
      "Cookie": "username-127-0-0-1-8157=\"2|1:0|10:1533157024|23:username-127-0-0-1-8157|44:NTU0MTA5ZWQzYjI5NDg0MWEwODI1NGQ3OGM2MDIxNDY=|43be7266b8ccfeaf2d5f9403a2c5a21d1a7da08b9e11525d716c6c7ee6596167\"; _xsrf=2|cee34e7f|0513fedcd5194fd65683eb14d150ba0f|1533157020"
    }
[E 00:36:26.483 NotebookApp] 500 POST /conda/environments/python3/packages/install (127.0.0.1) 12146.91ms referer=https://127.0.0.1:8157/tree?
```

However, if I install the package in terminal, through conda or pip, it installs successfully. Anyone have idea on this?

**Comment by mirocody** [comment]
Hi,
Any update on this issue?

**Comment by jasongrout** [comment]
I have no idea. This conda tab and extension is not provided by the notebook project. I'd suggest asking whatever project that provides the conda tab extension.

**Comment by jasongrout** [comment]
Looks like the nb conda project is the right one to ask. I see you already filed an issue there, so I'll close this one.

**Comment by jasongrout** [comment]
Ah, maybe it was somebody else who opened that other issue. That's still the best place to ask.
