### ISSUE TITLE
Fails to start as a service

### ISSUE THREAD

**Issue by yurivict** [jupyter/notebook#3826]
I'm trying to start the Jupyter Notebook server as a service on FreeBSD.
It fails:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook-3.6", line 11, in <module>
    load_entry_point('notebook==5.6.0', 'console_scripts', 'jupyter-notebook')()
  File "/usr/local/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/usr/local/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/notebook/notebookapp.py", line 1600, in initialize
    self.init_configurables()
  File "/usr/local/lib/python3.6/site-packages/notebook/notebookapp.py", line 1293, in init_configurables
    connection_dir=self.runtime_dir,
  File "/usr/local/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/usr/local/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/usr/local/lib/python3.6/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/usr/local/lib/python3.6/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/usr/local/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/.local'
```

How to set the runtime directory? It seems to be confused about it.
How to specify a directory where it can write? (```--notebook-dir=``` isn't it)

**Comment by takluyver** [comment]
It's picking up a path from XDG_RUNTIME_DIR. Unsetting that should work, or you can override it with JUPYTER_RUNTIME_DIR. Docs:

http://jupyter.readthedocs.io/en/latest/projects/jupyter-directories.html#runtime-files

**Comment by yurivict** [comment]
This works, thanks!

Now it starts, but it prints another message:
```
[I 10:42:46.170 NotebookApp] Writing notebook server cookie secret to /var/db/jupyter-notebook-2.7/runtime/notebook_cookie_secret
/usr/local/lib/python2.7/site-packages/IPython/paths.py:69: UserWarning: IPython parent '/' is not a writable location, using a temp directory.
  " using a temp directory.".format(parent))
```

I tried to set the ```IPYTHON``` variable, but this didn't help.

**Comment by yurivict** [comment]
Np, it still fails with the same error:
```
[W 10:57:32.769 NotebookApp] 500 PUT /api/contents/Transformation2D.ipynb (127.0.0.1): Unexpected error while saving file: Transformation2D.ipynb [Errno 13] Permission denied: '/.local'
[W 10:57:32.770 NotebookApp] Unexpected error while saving file: Transformation2D.ipynb [Errno 13] Permission denied: '/.local'
```

**Comment by yurivict** [comment]
Despite ```JUPYTER_PATH```, ```JUPYTER_CONFIG_DIR``` and ```JUPYTER_PATH``` being set to valid paths, it still tries to save the notebook into ```/```.

**Comment by takluyver** [comment]
The initial directory where it shows files and creates new files by default is the CWD where you started it. You can either set the CWD in whatever way your service manager allows, or override it with `--notebook-dir`, or a setting in a config file.

**Comment by yurivict** [comment]
I use ```--notebook-dir``` and set initial directory there, but the problem persists.

**Comment by catkins-miso** [comment]
I had this same problem and resolved it by additionally setting JUPYTER_DATA_DIR=$PYTHONUSERBASE
