### ISSUE TITLE
failed to start the kernel

### ISSUE THREAD

**Issue by MLPythoner** [jupyter/notebook#3854]
I got the following errors when starting jupyter notebook. Please help.
os: windows 7(64bit)
version: anacaond 3 64ibt
-----------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\dell\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'loop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dell\Anaconda3\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "C:\Users\dell\Anaconda3\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\dell\Anaconda3\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\dell\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "C:\Users\dell\Anaconda3\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\dell\Anaconda3\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\dell\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\dell\Anaconda3\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\dell\Anaconda3\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\dell\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\dell\Anaconda3\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\dell\Anaconda3\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\dell\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 148, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\dell\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\dell\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 258, in start_kernel
    self.start_restarter()
  File "C:\Users\dell\Anaconda3\lib\site-packages\jupyter_client\ioloop\manager.py", line 49, in start_restarter
    kernel_manager=self, loop=self.loop,
  File "C:\Users\dell\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "C:\Users\dell\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "C:\Users\dell\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 591, in _validate
    value = self.validate(obj, value)
  File "C:\Users\dell\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 1677, in validate
    self.error(obj, value)
  File "C:\Users\dell\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 1524, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'loop' trait of an IOLoopKernelManager instance must be a ZMQIOLoop, but a value of class 'tornado.platform.asyncio.AsyncIOMainLoop' (i.e. <tornado.platform.asyncio.AsyncIOMainLoop object at 0x0000000005C28FD0>) was specified.

**Comment by huiguo2008** [comment]
I got the exact same problem . looking for one solution for it.
