### ISSUE TITLE
Win7: OSError: access violation when launching jupyter notebook server ONLY with activated virtual environment

### ISSUE THREAD

**Issue by pybokeh** [jupyter/notebook#3855]
Hello, yes unfortunately, my company still uses Windows 7.

Installed latest Anaconda3 installer, created virtual environment, activated it, conda install jupyter, then when I went to launch notebook server via jupyter notebook, I get these errors:

```
Exception in thread Thread-1:

Traceback (most recent call last):

  File "D:\Anaconda3\envs\py32\lib\threading.py", line 916, in _bootstrap_inner

    self.run()

  File "D:\Anaconda3\envs\py32\lib\threading.py", line 864, in run

    self._target(*self._args, **self._kwargs)

  File "D:\Anaconda3\envs\py32\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread

    data = pty.read(4096, blocking=True)

  File "D:\Anaconda3\envs\py32\lib\site-packages\winpty\winpty_wrapper.py", line 74, in read

    ReadFile(self.conout_pipe, data, length, None, None)

OSError: exception: access violation writing 0x00000000

 

Exception in thread Thread-2:

Traceback (most recent call last):

  File "D:\Anaconda3\envs\py32\lib\threading.py", line 916, in _bootstrap_inner

    self.run()

  File "D:\Anaconda3\envs\py32\lib\threading.py", line 864, in run

    self._target(*self._args, **self._kwargs)

  File "D:\Anaconda3\envs\py32\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread

    data = pty.read(4096, blocking=True)

  File "D:\Anaconda3\envs\py32\lib\site-packages\winpty\winpty_wrapper.py", line 74, in read

    ReadFile(self.conout_pipe, data, length, None, None)

OSError: exception: access violation writing 0x00000000

 

Exception in thread Thread-3:

Traceback (most recent call last):

  File "D:\Anaconda3\envs\py32\lib\threading.py", line 916, in _bootstrap_inner

    self.run()

  File "D:\Anaconda3\envs\py32\lib\threading.py", line 864, in run

    self._target(*self._args, **self._kwargs)

  File "D:\Anaconda3\envs\py32\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread

    data = pty.read(4096, blocking=True)

  File "D:\Anaconda3\envs\py32\lib\site-packages\winpty\winpty_wrapper.py", line 74, in read

    ReadFile(self.conout_pipe, data, length, None, None)

OSError: exception: access violation writing 0x00000000

 

Exception in thread Thread-4:

Traceback (most recent call last):

  File "D:\Anaconda3\envs\py32\lib\threading.py", line 916, in _bootstrap_inner

    self.run()

  File "D:\Anaconda3\envs\py32\lib\threading.py", line 864, in run

    self._target(*self._args, **self._kwargs)

  File "D:\Anaconda3\envs\py32\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread

    data = pty.read(4096, blocking=True)

  File "D:\Anaconda3\envs\py32\lib\site-packages\winpty\winpty_wrapper.py", line 74, in read

    ReadFile(self.conout_pipe, data, length, None, None)

OSError: exception: access violation writing 0x00000000

 

Exception in thread Thread-5:

Traceback (most recent call last):

  File "D:\Anaconda3\envs\py32\lib\threading.py", line 916, in _bootstrap_inner

    self.run()

  File "D:\Anaconda3\envs\py32\lib\threading.py", line 864, in run

    self._target(*self._args, **self._kwargs)

  File "D:\Anaconda3\envs\py32\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread

    data = pty.read(4096, blocking=True)

 File "D:\Anaconda3\envs\py32\lib\site-packages\winpty\winpty_wrapper.py", line 74, in read

    ReadFile(self.conout_pipe, data, length, None, None)

OSError: exception: access violation writing 0x00000000

 

Exception in thread Thread-6:

Traceback (most recent call last):

  File "D:\Anaconda3\envs\py32\lib\threading.py", line 916, in _bootstrap_inner

    self.run()

  File "D:\Anaconda3\envs\py32\lib\threading.py", line 864, in run

    self._target(*self._args, **self._kwargs)

  File "D:\Anaconda3\envs\py32\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread

    data = pty.read(4096, blocking=True)

  File "D:\Anaconda3\envs\py32\lib\site-packages\winpty\winpty_wrapper.py", line 74, in read

    ReadFile(self.conout_pipe, data, length, None, None)

OSError: exception: access violation writing 0x00000000

 

Exception in thread Thread-7:

Traceback (most recent call last):

  File "D:\Anaconda3\envs\py32\lib\threading.py", line 916, in _bootstrap_inner

    self.run()

  File "D:\Anaconda3\envs\py32\lib\threading.py", line 864, in run

    self._target(*self._args, **self._kwargs)

  File "D:\Anaconda3\envs\py32\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread

    data = pty.read(4096, blocking=True)

  File "D:\Anaconda3\envs\py32\lib\site-packages\winpty\winpty_wrapper.py", line 74, in read

    ReadFile(self.conout_pipe, data, length, None, None)

OSError: exception: access violation writing 0x00000000

 

Exception in thread Thread-8:

Traceback (most recent call last):

  File "D:\Anaconda3\envs\py32\lib\threading.py", line 916, in _bootstrap_inner

    self.run()

  File "D:\Anaconda3\envs\py32\lib\threading.py", line 864, in run

    self._target(*self._args, **self._kwargs)

  File "D:\Anaconda3\envs\py32\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread

    data = pty.read(4096, blocking=True)

  File "D:\Anaconda3\envs\py32\lib\site-packages\winpty\winpty_wrapper.py", line 74, in read

    ReadFile(self.conout_pipe, data, length, None, None)

OSError: exception: access violation writing 0x00000000

 

Exception in thread Thread-9:

Traceback (most recent call last):

  File "D:\Anaconda3\envs\py32\lib\threading.py", line 916, in _bootstrap_inner

    self.run()

  File "D:\Anaconda3\envs\py32\lib\threading.py", line 864, in run

    self._target(*self._args, **self._kwargs)

  File "D:\Anaconda3\envs\py32\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread

    data = pty.read(4096, blocking=True)

  File "D:\Anaconda3\envs\py32\lib\site-packages\winpty\winpty_wrapper.py", line 74, in read

    ReadFile(self.conout_pipe, data, length, None, None)

OSError: exception: access violation writing 0x00000000

 

Exception in thread Thread-10:

Traceback (most recent call last):

  File "D:\Anaconda3\envs\py32\lib\threading.py", line 916, in _bootstrap_inner

    self.run()

  File "D:\Anaconda3\envs\py32\lib\threading.py", line 864, in run

    self._target(*self._args, **self._kwargs)

  File "D:\Anaconda3\envs\py32\lib\site-packages\winpty\ptyprocess.py", line 331, in _read_in_thread

    data = pty.read(4096, blocking=True)

  File "D:\Anaconda3\envs\py32\lib\site-packages\winpty\winpty_wrapper.py", line 74, in read

    ReadFile(self.conout_pipe, data, length, None, None)

OSError: exception: access violation writing 0x00000000

 

[I 17:19:57.845 NotebookApp] Serving notebooks from local directory: D:\jupyter

[I 17:19:57.846 NotebookApp] 0 active kernels

[I 17:19:57.846 NotebookApp] The Jupyter Notebook is running at:

[I 17:19:57.846 NotebookApp] http://localhost:8888/jupyter/

[I 17:19:57.847 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation)
```

What's strange is if I use system Anaconda (in other words, without environment activated) and launch jupyter notebook, I do not get the OSErrors.  These errors only occur if I launch from an activated virtual environment.

**Comment by pybokeh** [comment]
It may be something wrong with winpty no longer working with Windows 7, I found several issues with similar problem:
https://github.com/spyder-ide/pywinpty/issues/59
https://github.com/spyder-ide/pywinpty/issues/108

**Comment by pybokeh** [comment]
I will close this issue as it is most likely related to winpty library.  I will see if I uninstall and then install via pip will work as a workaround.
