### ISSUE TITLE
Failed to start Kernel 

### ISSUE THREAD

**Issue by Kelvinli5354** [jupyter/notebook#3897]
```Traceback (most recent call last):
  File "C:\Users\Kelfun\Anaconda3\lib\site-packages\tornado\web.py", line 1543, in _execute
    result = yield result
  File "C:\Users\Kelfun\Anaconda3\lib\site-packages\tornado\gen.py", line 1099, in run
    value = future.result()
  File "C:\Users\Kelfun\Anaconda3\lib\site-packages\tornado\gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\Kelfun\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "C:\Users\Kelfun\Anaconda3\lib\site-packages\tornado\gen.py", line 1099, in run
    value = future.result()
  File "C:\Users\Kelfun\Anaconda3\lib\site-packages\tornado\gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\Kelfun\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\Kelfun\Anaconda3\lib\site-packages\tornado\gen.py", line 1099, in run
    value = future.result()
  File "C:\Users\Kelfun\Anaconda3\lib\site-packages\tornado\gen.py", line 1107, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\Kelfun\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\Kelfun\Anaconda3\lib\site-packages\tornado\gen.py", line 1099, in run
    value = future.result()
  File "C:\Users\Kelfun\Anaconda3\lib\site-packages\tornado\gen.py", line 315, in wrapper
    yielded = next(result)
  File "C:\Users\Kelfun\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 148, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\Kelfun\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\Kelfun\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
    **kw)
  File "C:\Users\Kelfun\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Users\Kelfun\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Users\Kelfun\Anaconda3\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Kelfun\Anaconda3\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

I don't have any idea what is happening here. I just reinstalled Anaconda and this error pops up. I checked the kernel.json file and everything looks good.

**Comment by ErfPy** [comment]
I have the same error, @Kelvinli5354 were you able to resolve this issue?

**Comment by calz1** [comment]
Same here :(
