### ISSUE TITLE
Server error:

### ISSUE THREAD

**Issue by a56256324** [jupyter/notebook#3912]
I don't know where the problem is, but when I run jupyter not book, I open the page and get the following prompt
Server error: Traceback (most recent call last): File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1592, in _execute result = yield result File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1133, in run value = future.result() File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result raise self._exception File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 326, in wrapper yielded = next(result) File "/usr/local/lib/python3.5/dist-packages/notebook/services/contents/handlers.py", line 112, in get path=path, type=type, format=format, content=content, File "/usr/local/lib/python3.5/dist-packages/notebook/services/contents/filemanager.py", line 431, in get model = self._dir_model(path, content=content) File "/usr/local/lib/python3.5/dist-packages/notebook/services/contents/filemanager.py", line 337, in _dir_model if self.should_list(name) and not is_file_hidden(os_path, stat_res=st): File "/usr/local/lib/python3.5/dist-packages/notebook/utils.py", line 145, in is_file_hidden_posix stat_res = os.stat(abs_path) NotADirectoryError: [Errno 20] Not a directory: '/home/gaoyang/python' 

And terminal display
[I 21:12:11.174 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[E 21:12:15.543 NotebookApp] Uncaught exception GET /api/contents?type=directory&_=1536844332769 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8889', method='GET', uri='/api/contents?type=directory&_=1536844332769', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python3.5/dist-packages/notebook/services/contents/handlers.py", line 112, in get
        path=path, type=type, format=format, content=content,
      File "/usr/local/lib/python3.5/dist-packages/notebook/services/contents/filemanager.py", line 431, in get
        model = self._dir_model(path, content=content)
      File "/usr/local/lib/python3.5/dist-packages/notebook/services/contents/filemanager.py", line 337, in _dir_model
        if self.should_list(name) and not is_file_hidden(os_path, stat_res=st):
      File "/usr/local/lib/python3.5/dist-packages/notebook/utils.py", line 145, in is_file_hidden_posix
        stat_res = os.stat(abs_path)
    NotADirectoryError: [Errno 20] Not a directory: '/home/gaoyang/python'
[W 21:12:15.547 NotebookApp] Unhandled error
[E 21:12:15.551 NotebookApp] {
      "Host": "localhost:8889",
      "Accept-Encoding": "gzip, deflate",
      "User-Agent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0",
      "Accept-Language": "en-GB,en;q=0.5",
      "Connection": "keep-alive",
      "X-Requested-With": "XMLHttpRequest",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Xsrftoken": "2|0d93f1b8|a477b2855f6f143ecd7f40304c7d5dc5|1536833146",
      "Referer": "http://localhost:8889/tree",
      "Cookie": "_xsrf=2|0d93f1b8|a477b2855f6f143ecd7f40304c7d5dc5|1536833146; username-localhost-8888=\"2|1:0|10:1536843580|23:username-localhost-8888|44:NWEzNThhYzg3YWNhNDNhYmJhODZhNGRmNTIzMzRkMWQ=|ca3619884f5e0812e9cad428fd6f2aa11b38c5c290d9c25df89545192f6ef69d\"; hibext_instdsigdipv2=1; username-localhost-8889=\"2|1:0|10:1536844331|23:username-localhost-8889|44:NjNjZGE0MzRjZGFhNDM3ZThhMTU4NWYyYjcwZTY4Nzk=|c2e9b8e8f1743f7f89dae001649896967949126db93150ee781b5fe335a8707a\"; username-localhost-8890=\"2|1:0|10:1536843915|23:username-localhost-8890|44:MTVlMTkwNDNlNTAzNDczN2JiNTRhMzkzYTU4ZTJlZTE=|10b58a26c3a3d2f8652c477ff5b3b44b32110efea6337492b05aaae96a6b46bc\""
    }
[E 21:12:15.552 NotebookApp] 500 GET /api/contents?type=directory&_=1536844332769 (127.0.0.1) 13.54ms referer=http://localhost:8889/tree
[E 21:12:30.952 NotebookApp] Uncaught exception GET /api/contents?type=directory&_=1536844332772 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8889', method='GET', uri='/api/contents?type=directory&_=1536844332772', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/usr/local/lib/python3.5/dist-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python3.5/dist-packages/notebook/services/contents/handlers.py", line 112, in get
        path=path, type=type, format=format, content=content,
      File "/usr/local/lib/python3.5/dist-packages/notebook/services/contents/filemanager.py", line 431, in get
        model = self._dir_model(path, content=content)
      File "/usr/local/lib/python3.5/dist-packages/notebook/services/contents/filemanager.py", line 337, in _dir_model
        if self.should_list(name) and not is_file_hidden(os_path, stat_res=st):
      File "/usr/local/lib/python3.5/dist-packages/notebook/utils.py", line 145, in is_file_hidden_posix
        stat_res = os.stat(abs_path)
    NotADirectoryError: [Errno 20] Not a directory: '/home/gaoyang/python'

**Comment by kritikamehta15** [comment]
Did you find any workaround? I am having the same issue
