### ISSUE TITLE
Problem running notebook server after upgrade

### ISSUE THREAD

**Issue by hannorein** [jupyter/notebook#394]
I recently upgraded my jupyter installation. I now get an error message whenever I open a notebook. Any hint to what I should be looking for would be appreciated. 

    $ jupyter notebook
    [I 20:09:03.735 NotebookApp] Serving notebooks from local directory: /Users/rein/git/rebound
    [I 20:09:03.735 NotebookApp] 0 active kernels
    [I 20:09:03.735 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
    [I 20:09:03.735 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
    [W 20:09:14.679 NotebookApp] Notebook testCluster.ipynb is not trusted
    [E 20:09:14.824 NotebookApp] Unhandled error in API request
        Traceback (most recent call last):
          File "/Users/rein/git/rebound/venv/lib/python2.7/site-packages/notebook/base/handlers.py", line 436, in wrapper
            result = yield gen.maybe_future(method(self, *args, **kwargs))
          File "/Users/rein/git/rebound/venv/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 56, in post
            model = sm.create_session(path=path, kernel_name=kernel_name)
          File "/Users/rein/git/rebound/venv/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 66, in create_session
            kernel_name=kernel_name)
          File "/Users/rein/git/rebound/venv/lib/python2.7/site-packages/notebook/services/kernels/kernelmanager.py", line 84, in start_kernel
            **kwargs)
          File "/Users/rein/git/rebound/venv/lib/python2.7/site-packages/jupyter_client/multikernelmanager.py", line 109, in start_kernel
            km.start_kernel(**kwargs)
          File "/Users/rein/git/rebound/venv/lib/python2.7/site-packages/jupyter_client/manager.py", line 239, in start_kernel
            **kw)
          File "/Users/rein/git/rebound/venv/lib/python2.7/site-packages/jupyter_client/manager.py", line 186, in _launch_kernel
            return launch_kernel(kernel_cmd, **kw)
          File "/Users/rein/git/rebound/venv/lib/python2.7/site-packages/jupyter_client/launcher.py", line 119, in launch_kernel
            proc = Popen(cmd, **kwargs)
          File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
            errread, errwrite)
          File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
            raise child_exception
        OSError: [Errno 2] No such file or directory
    [E 20:09:14.826 NotebookApp] {
          "Origin": "http://localhost:8888",
          "Content-Length": "79",
          "Accept-Language": "en-us",
          "Accept-Encoding": "gzip, deflate",
          "Connection": "keep-alive",
          "Accept": "application/json, text/javascript, */*; q=0.01",
          "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/600.8.9 (KHTML, like Gecko) Version/8.0.8 Safari/600.8.9",
          "Host": "localhost:8888",
          "Referer": "http://localhost:8888/notebooks/testCluster.ipynb",
          "X-Requested-With": "XMLHttpRequest",
          "Content-Type": "application/json"
        }
    [E 20:09:14.826 NotebookApp] 500 POST /api/sessions (::1) 25.68ms referer=http://localhost:8888/notebooks/testCluster.ipynb

**Comment by Carreau** [comment]
can you try to do a `ipython kernelspec install-self` and retry ?possibly starting the notebook with `--debug` ?

**Comment by Carreau** [comment]
Closing for inactivity.

**Comment by hannorein** [comment]
I couldn't figure out what was going on and after trying for a few hours I simply reinstalled everything from scratch. For that reason I can't provide any more details. Sorry!

**Comment by Carreau** [comment]
> I couldn't figure out what was going on and after trying for a few hours I simply reinstalled everything from scratch. For that reason I can't provide any more details. Sorry!

No problem, I'm just cleaning up a bit the issue list. 
Happy this is working for you.

**Comment by fkraus** [comment]
`ipython kernelspec install-self` helped for me, thanks :-)

**Comment by ronteo** [comment]
I ran 
python2 -m ipykernel install --user

and it worked for me

**Comment by diimdeep** [comment]
trying to fix same problem after upgrading to never jupyter..

**Comment by diimdeep** [comment]
I had clean up python installation and start from scratch.
