### ISSUE TITLE
After installing pydot, jupyter notebook no longer launches

### ISSUE THREAD

**Issue by allahale** [jupyter/notebook#4045]
I installed pydot yesterday using conda install -c anaconda pydot.  Everything seemed fine during that session.  But now I can't launch jupyter notebook or jupyter lab.  Here is the traceback:

Traceback (most recent call last):
  File "/Users/allahale/anaconda3/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/Users/allahale/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 44, in <module>
    from zmq.eventloop import ioloop
  File "/Users/allahale/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 34, in <module>
    from zmq import backend
  File "/Users/allahale/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/Users/allahale/anaconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/Users/allahale/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/Users/allahale/anaconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/Users/allahale/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: dlopen(/Users/allahale/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/constants.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libzmq.5.1.2.dylib
  Referenced from: /Users/allahale/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/constants.cpython-36m-darwin.so
  Reason: image not found

Some more info:
$ conda info

     active environment : None
       user config file : /Users/allahale/.condarc
 populated config files : /Users/allahale/.condarc
          conda version : 4.5.11
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : /Users/allahale/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/allahale/anaconda3/pkgs
                          /Users/allahale/.conda/pkgs
       envs directories : /Users/allahale/anaconda3/envs
                          /Users/allahale/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.4 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False

$ conda list | grep jupyter
jupyter                   1.0.0                    py36_4  
jupyter_client            5.2.3                    py36_0    anaconda
jupyter_console           5.2.0            py36hccf5b1c_1  
jupyter_core              4.4.0            py36h79cf704_0 

What's happening? How do I fix this?

**Comment by allahale** [comment]
```
conda remove zeromq
conda install zeromq
```
Fixed the issue.  Launches fine, now.
