### ISSUE TITLE
 Kernel crashes with ModuleNotFoundError on 'prompt_toolkit.formatted_text'

### ISSUE THREAD

**Issue by katcosgrove** [jupyter/notebook#4050]
With a fresh install of Jupyter in a clean pipenv or virtualenv, a new notebook crashes immediately upon launch with the following in terminal:

[I 13:39:55.748 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/kat/Projects/jupyter_bug/ENV/lib/python3.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/Users/kat/Projects/jupyter_bug/ENV/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/Users/kat/Projects/jupyter_bug/ENV/lib/python3.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/Users/kat/Projects/jupyter_bug/ENV/lib/python3.7/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/Users/kat/Projects/jupyter_bug/ENV/lib/python3.7/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/Users/kat/Projects/jupyter_bug/ENV/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 20, in <module>
    from prompt_toolkit.formatted_text import PygmentsTokens
ModuleNotFoundError: No module named 'prompt_toolkit.formatted_text'
[W 13:39:58.759 NotebookApp] KernelRestarter: restart failed
[W 13:39:58.760 NotebookApp] Kernel d6c405e3-6b72-4be9-93fd-f44aecc78576 died, removing from map.

Originally seen on an Ubuntu 18.04 machine using Python 3.7 and recreated on Mac OS Sierra and High Sierra with 3.7, as well as Ubuntu 16.04 with 2.7 and then 3.6. Four separate machines.

**Comment by bhanuvrat** [comment]
This came up during installation and later resulted in the error mentioned by OP.

```ipython` 7.0.1 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.15 which is incompatible```

**Comment by bhanuvrat** [comment]
seems like it is being fixed here https://github.com/nengo/nengo-dl/commit/f71bcefe8cfdda755c4c9bb26dce9f7333a555eb

**Comment by sirusss** [comment]
As a temporary workaround, this will fix it:
`pip install 'ipykernel<5.0.0'`

**Comment by s3afroze** [comment]
> As a temporary workaround, this will fix it:
> `pip install 'ipykernel<5.0.0'`

Have been trying to fix for hours.
Thank you,

**Comment by Carreau** [comment]
> pip install 'ipykernel<5.0.0'

It seem extremely unlikely this was the problem. IPykernel does not rely on `prompt_toolkit`, and `IPykernel<5` with `IPython>7` will still break jupyter.

For those of you who tried and for who this fixes things with version of IPython is now installed ?

**Comment by s-weigand** [comment]
The `jupyter-console` master also supports `prompt-toolkit>2`, so instead of downgrading `ipython`, upgrading `jupyter-console` should work als well (tested it in a fresh conda env after the `ipython 7.0` release).
So the other temporary workaround (untill the next version of `jupyter-console` is on PyPi), that will fix it is:
`pip install git+https://github.com/jupyter/jupyter_console.git`

**Comment by miker985** [comment]
> pip install 'ipykernel<5.0.0'

This fixed the problem for me such that the Kernel would start and I could use my notebook.

**Comment by gonzales-edwin** [comment]
> As a temporary workaround, this will fix it:
> `pip install 'ipykernel<5.0.0'`

Thank you, this fixed my problem also. I was able to open up notebooks but the cells would not run.

**Comment by jed-frey** [comment]
Using jupyter notebooks, if I just specify ipykernel with 'jupyter' as a requirement I still get this error:

    jupyter-console 5.2.0 has requirement prompt-toolkit<2.0.0,>=1.0.0, but you'll have prompt-toolkit 2.0.5 which is incompatible.

The minimal requirements.txt that gives me working notebook is:

```
ipykernel<5.0.0
notebook
```

pip figures it out from there.

If you add ```ipython```

same error ```ipython 7.0.1 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.15 which is incompatible.```

So you need ```ipython<7.0.0``` as well *if* you have ipython specified.

**Comment by gronki** [comment]
I confirm below works for me at the moment (``ipykernel<5.0.0`` alone was not enough):
```
pip3 install jupyter 'ipykernel<5.0.0' 'ipython<7.0.0'
```

**Comment by KTM-300** [comment]
I have the same error as indicated above.

If I try `pip install 'ipykernel<5.0.0'` command in my command prompt of Windows 10, I get the following error 

> The system cannot find the file specified.

Please can you let this newbie know how to rectify this error?

**Comment by s-weigand** [comment]
since there is a new release of `jupyter_console` the following command should fix the problem if its allready there and if not it shouldn't appear anymore: 
`pip install -U jupyter_console`
@KTM-300 does your system know about pip (does `pip --version` work)?
If not you can add the path of your python installation to the [PATH variable](https://superuser.com/questions/949560/how-do-i-set-system-environment-variables-in-windows-10).

**Comment by KTM-300** [comment]
Thanks for helping.  

Yes, pip --version works.

I managed to get around the problem with the answer from https://stackoverflow.com/questions/52551878/problems-upgrading-ipython-prompt-toolkit-incompatibilities

**Comment by tpanza** [comment]
Confirmed that `pip install -U jupyter_console` fixes this. 

In particular, this problem started happening in my environment with prompt-toolkit-1.0.15. For what it's worth, my environment initially had prompt-toolkit-2.0.5, but then an install of `py2neo` into my environment forced a downgrade of prompt-toolkit to 1.0.15.

So, this may happen if the installation of a new package sneaks in a downgrade of `prompt-toolkit` down to 1.x.

**Comment by echocherish** [comment]
You can try to upgrade jupyter-conslole 's version, then promblems are fixed.

**Comment by tonianev** [comment]
> As a temporary workaround, this will fix it:
> `pip install 'ipykernel<5.0.0'`

Thank you so much!

**Comment by etoatibm** [comment]
Hi 

**pip install -U jupyter_console** 

helped me out.

**Comment by rambail** [comment]
pip install -U jupyter_console

+1

**Comment by diponkor-bala** [comment]
pip install -U jupyter_console is working properly

**Comment by Praveenkumar1996** [comment]
> As a temporary workaround, this will fix it:
> `pip install 'ipykernel<5.0.0'`

Thank you so much, I almost took a day to solve this.

**Comment by remborg** [comment]
> If I try `pip install 'ipykernel<5.0.0'` command in my command prompt of Windows 10, I get the following error
> 
> > The system cannot find the file specified.
> 

I had to replace the single quotes to double quotes to get the command to work:
`pip install "ipykernel<5.0.0"`

**Comment by kevin-bates** [comment]
(From https://github.com/jupyter/notebook/issues/5024#issuecomment-646076083) Rather than _downgrade_ `ipykernel` and `IPython`, especially given the timeframe of those initial suggestions (which may have been correct at the time), I would first try ensuring that you're running the latest versions of each and _upgrade_ if not.

Also, since IPython appears to be [sensitive to the version of prompt_toolkit](https://github.com/ipython/ipython/blob/master/setup.py#L191), I would recommend checking prompt_toolkit's version as well.

If someone finds this "upgrade" approach successful, could you please add a comment?  This will allow future incidents to be forward-moving rather than not.  Thank you.

**Comment by BenjiBong** [comment]
> I confirm below works for me at the moment (`ipykernel<5.0.0` alone was not enough):
> 
> ```
> pip3 install jupyter 'ipykernel<5.0.0' 'ipython<7.0.0'
> ```

Thanks @gronki 

conda install ipykernel'<5.0.0' ipython'<7.0.0' worked for me.
like you, just ipykernel'<5.0.0' wasn't enough.

**Comment by beniroquai** [comment]
@kevin-bates This worked for me indeed:

```pip install prompt_toolkit --force-reinstall```

Thanks!

**Comment by julianschoep** [comment]
pip install ipython==7 prompt-toolkit==2.0.10 jupyter-console==6.0.0
worked for me

**Comment by ShengHow95** [comment]
> `pip install ipython==7 prompt-toolkit==2.0.10 jupyter-console==6.0.0`
> worked for me

This worked for me. Thanks!

**Comment by Mahamatnour** [comment]
> `pip install ipython==7 prompt-toolkit==2.0.10 jupyter-console==6.0.0`
> worked for me

Hey it's worked for me too. it's saved my day. thanks

**Comment by lchapo** [comment]
`conda update jupyter` worked for me

**Comment by stas00** [comment]
And sometimes some rogue module forces the old `prompt_toolkit` version on you, as is the case with `wandb` at the moment: https://github.com/wandb/client/issues/1498

**Comment by Vivian12345** [comment]
> > If I try `pip install 'ipykernel<5.0.0'` command in my command prompt of Windows 10, I get the following error
> > > The system cannot find the file specified.
> 
> I had to replace the single quotes to double quotes to get the command to work:
> `pip install "ipykernel<5.0.0"`

Thanks a lot!
need to double quotes +1

**Comment by Vivian12345** [comment]
> `pip install ipython==7 prompt-toolkit==2.0.10 jupyter-console==6.0.0`
> worked for me

Thank you very much~
It works!

**Comment by ethanjyx** [comment]
> As a temporary workaround, this will fix it: `pip install 'ipykernel<5.0.0'`

This worked for me... thanks!

**Comment by tonyfast** [comment]
This appears to be solved by updating `IPython` or `ipykernel`. Thanks for the discussion y'all. ❤️ [Jupyter Triage Team](https://github.com/orgs/jupyterlab/teams/triage)

**Comment by ainunnawawi** [comment]
pip install ipykernel

**Comment by abaveja313** [comment]
> pip install ipykernel

Worked for me
