### ISSUE TITLE
Trying to generate a self signed SSL certificate

### ISSUE THREAD

**Issue by adu322** [jupyter/notebook#4051]
```
Unrecognized alias: '--certificate=certfile.pem', it will probably have no effect.
Traceback (most recent call last):
  File "/home/username/.anaconda3/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/home/username/.anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/username/.anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/home/username/.anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/username/.anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1629, in initialize
    self.init_webapp()
  File "/home/username/.anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1403, in init_webapp
    max_buffer_size=self.max_buffer_size)
  File "/home/username/.anaconda3/lib/python3.6/site-packages/tornado/util.py", line 312, in __new__
    instance.initialize(*args, **init_kwargs)
  File "/home/username/.anaconda3/lib/python3.6/site-packages/tornado/httpserver.py", line 168, in initialize
    read_chunk_size=chunk_size)
  File "/home/username/.anaconda3/lib/python3.6/site-packages/tornado/tcpserver.py", line 125, in __init__
    raise KeyError('missing key "certfile" in ssl_options')
KeyError: 'missing key "certfile" in ssl_options'
```

generating a cert with openSSL, then running `jupyter notebook --certificate=certfile.pem --keyfile=certfile.pem`

 jupyter --version
4.4.0

conda 4.5.11

**Comment by takluyver** [comment]
The first line is the giveaway there:

```
Unrecognized alias: '--certificate=certfile.pem', it will probably have no effect.
```

Try changing the `--certificate` option to `--certfile`.
