### ISSUE TITLE
Error launching jupyter-notebook in container running python3.7

### ISSUE THREAD

**Issue by sargense** [jupyter/notebook#4069]
Error does not happen until a notebook is opened:

`Could not import runpy module
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 15, in <module>
    import importlib.util
  File "/usr/lib/python3.7/importlib/util.py", line 14, in <module>
    from contextlib import contextmanager
  File "/usr/lib/python3.7/contextlib.py", line 5, in <module>
    from collections import deque
  File "/home/jupyter/notebooks/collections.py", line 1, in <module>
    from .constants import (
ImportError: attempted relative import with no known parent package
`

**Comment by sargense** [comment]
Removed legacy file and updated. Fixed.
