### ISSUE TITLE
Problem w/ Jupyter notebook

### ISSUE THREAD

**Issue by freysim** [jupyter/notebook#4070]
Hi all, 

I am totally new to Jupyter Notebook. 
Currently, I am using the notebook with R and it is working well. 
Now, I tried to use it with Python and I receive the following error.

[I 09:00:52.947 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frey/.local/lib/python3.6/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/home/frey/.local/lib/python3.6/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/frey/.local/lib/python3.6/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/home/frey/.local/lib/python3.6/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/home/frey/.local/lib/python3.6/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/home/frey/.local/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 20, in <module>
    from prompt_toolkit.formatted_text import PygmentsTokens
ModuleNotFoundError: No module named 'prompt_toolkit.formatted_text'
[W 09:00:55.956 NotebookApp] KernelRestarter: restart failed
[W 09:00:55.956 NotebookApp] Kernel 24117cd7-38e5-4978-8bda-d1b84f498051 died, removing from map.

Hopefully, someone can help me.
Regards

**Comment by 1kastner** [comment]
Please re-phrase the title :)

**Comment by takluyver** [comment]
We got into difficulty with the transition to prompt_toolkit version 2; there was a point where IPython required the new version but `jupyter_console` still needed the old version. This should now be solved, so if you're still seeing it, try simply upgrading everything involved.
