### ISSUE TITLE
http://localhost:8888/ is not responding

### ISSUE THREAD

**Issue by 369nio** [jupyter/notebook#4151]
When I launch jupyter notebook from the anaconda navigator or from the command line, then I get this error. Browser pops up this url but it does not respond: http://localhost:8888/tree?token=ce7df169cfe8da7101ad95142193289d2a3b7524db86a998

Error log from Anaconda Navigator:

[I 22:41:24.697 NotebookApp] JupyterLab beta preview extension loaded from C:\ProgramData\Anaconda3\lib\site-packages\jupyterlab
[I 22:41:24.697 NotebookApp] JupyterLab application directory is C:\ProgramData\Anaconda3\share\jupyter\lab
[I 22:41:24.814 NotebookApp] Serving notebooks from local directory: C:\Users\Ikram
[I 22:41:24.814 NotebookApp] 0 active kernels
[I 22:41:24.814 NotebookApp] The Jupyter Notebook is running at:
[I 22:41:24.814 NotebookApp] http://localhost:8888/?token=99d4b11f18f9d4950ffa25e5b8f3a4ed934975fee01da8cd
[I 22:41:24.814 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 22:41:24.876 NotebookApp] 

Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
http://localhost:8888/?token=99d4b11f18f9d4950ffa25e5b8f3a4ed934975fee01da8cd&token=99d4b11f18f9d4950ffa25e5b8f3a4ed934975fee01da8cd
[I 22:41:24.878 NotebookApp] Shutting down 0 kernels
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\Scripts\jupyter-notebook-script.py", line 10, in 
sys.exit(main())
File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
app.start()
File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 1670, in start
self.io_loop.start()
File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 127, in start
self.asyncio_loop.run_forever()
File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 422, in run_forever
self._run_once()
File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 1396, in _run_once
event_list = self._selector.select(timeout)
File "C:\ProgramData\Anaconda3\lib\selectors.py", line 323, in select
r, w, _ = self._select(self._readers, self._writers, [], timeout)
File "C:\ProgramData\Anaconda3\lib\selectors.py", line 314, in _select
r, w, x = select.select(r, w, w, timeout)
OSError: [WinError 10038] An operation was attempted on something that is not a socket

**Comment by YuNicer** [comment]
Same issue for me. what about your solution to this?

**Comment by ShreckYe** [comment]
Same issue but I am using pip. I installed Jupyter with no further modification. The error occurs when I enter "jupyter notebook" in PowerShell.
