### ISSUE TITLE
Jupyter Notebook command fails in Python3.7 OSx

### ISSUE THREAD

**Issue by RaghuMurugesan** [jupyter/notebook#4167]
`jupyter notebook` command is crashing in OSx. I recently upgraded to Python3.7 and I facing this issue after that.

```
$jupyter notebook
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/notebook/nbextensions.py", line 31, in <module>
    from .config_manager import BaseJSONConfigManager
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/notebook/config_manager.py", line 15, in <module>
    from traitlets.config import LoggingConfigurable
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitlets/config/__init__.py", line 6, in <module>
    from .application import *
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/traitlets/config/application.py", line 77, in <module>
    @decorator
TypeError: 'module' object is not callable
```

**Comment by RaghuMurugesan** [comment]
Looks like python kernel didn't like the __init__.py files that I created in directory sub directories from where I started `jupyter notebook`. Delete those __init__.py files fixed the kernel crash issue
