### ISSUE TITLE
ImportError: cannot import name 'ensure_dir_exists'

### ISSUE THREAD

**Issue by keithbriggs** [jupyter/notebook#4168]
I get this after a pip install on an up-to-date Ubuntu system.  What causes this?

~> jupyter notebook
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/usr/local/lib/python3.4/dist-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/usr/local/lib/python3.4/dist-packages/notebook/nbextensions.py", line 27, in <module>
    from jupyter_core.utils import ensure_dir_exists
ImportError: cannot import name 'ensure_dir_exists'

**Comment by takluyver** [comment]
Probably an old version of `jupyter_core`. Try uninstalling and reinstalling that.

**Comment by keithbriggs** [comment]
Thanks, that fixed it.   Why doesn't pip check this dependency and makes sure it's satisfied?

**Comment by takluyver** [comment]
Try the same with `nbconvert`.

The requirement is specified:

https://github.com/jupyter/notebook/blob/2af744075f52f62ab18cf807ec009cb6ad6af2f1/setup.py#L107

It's possible you have an older install (maybe done with `--user`) which is shadowing your new one.

**Comment by keithbriggs** [comment]
This gets a bit further but it now crashes with


> /usr/bin/python: No module named ipykernel_launcher


Keith

________________________________

**Comment by takluyver** [comment]
That's ipykernel. But at this point I'd recommend you just try to wipe out all Python packages you have installed in different places and start again from scratch. It could take a long time to fix them one by one.

**Comment by keithbriggs** [comment]
Thanks for you help - a new ipykernel fixed it!


K

________________________________
