### ISSUE TITLE
Trouble launching Jupyter Notebook: ValueError: certfile "/absolute/path/to/your/certificate/mycert.pem" does not exist

### ISSUE THREAD

**Issue by dafnamargalit** [jupyter/notebook#4172]
Hi,
I have attempted to launch a Jupyter notebook server multiple times but keep receiving the same error. I tried uninstalling and reinstalling it through both anaconda and pip. I can't seem to figure out what is wrong with how I am installing it, and couldn't find anything online regarding the error I am getting. Here is the output from terminal after I run "jupyter notebook":

```
Traceback (most recent call last):
  File "/anaconda3/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/notebook/notebookapp.py", line 1602, in initialize
    self.init_webapp()
  File "/anaconda3/lib/python3.7/site-packages/notebook/notebookapp.py", line 1376, in init_webapp
    xheaders=self.trust_xheaders)
  File "/anaconda3/lib/python3.7/site-packages/tornado/util.py", line 312, in __new__
    instance.initialize(*args, **init_kwargs)
  File "/anaconda3/lib/python3.7/site-packages/tornado/httpserver.py", line 168, in initialize
    read_chunk_size=chunk_size)
  File "/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 129, in __init__
    self.ssl_options['certfile'])
ValueError: certfile "/absolute/path/to/your/certificate/mycert.pem" does not exist
```

**Comment by dafnamargalit** [comment]
Update: I reinstalled node and ran the command "sudo chown -R $(whoami) /usr/local/Cellar" in terminal and the issue was resolved. Don't understand why, but am happy that it worked!

**Comment by imSrbh** [comment]
> Cellar

 What is that?

**Comment by dafnamargalit** [comment]
I believe it's the folder that contains packages installed by Homebrew.
