### ISSUE TITLE
getting kernel error 87 when running jupyter notebook

### ISSUE THREAD

**Issue by abdRazaq** [jupyter/notebook#4237]
I got kernel error 87 while creating new notebook with Python3 as shown below.

---------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\Attapol\Anaconda3\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "C:\Users\Attapol\Anaconda3\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\Attapol\Anaconda3\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\Attapol\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "C:\Users\Attapol\Anaconda3\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\Attapol\Anaconda3\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\Attapol\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\Attapol\Anaconda3\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\Attapol\Anaconda3\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\Attapol\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\Attapol\Anaconda3\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\Attapol\Anaconda3\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\Attapol\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\Attapol\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\Attapol\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
    **kw)
  File "C:\Users\Attapol\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Users\Attapol\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Users\Attapol\Anaconda3\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Attapol\Anaconda3\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
OSError: [WinError 87] The parameter is incorrect

----------------------------------------------------------------------------------------------------
i tried to address the error by many ways, but didn't work.
at last found the cause, it is antivirus blocking a json file like showing below

![image](https://user-images.githubusercontent.com/34486128/49065390-7cce4b00-f250-11e8-871a-efcfe25f88c1.png)

So, simply tell the antivirus to unblock a json file which will be created during runtime by stating ~/*.json.

**Comment by mesla** [comment]
Thanks a lot, I had the same trouble

**Comment by takluyver** [comment]
Thanks for describing what went wrong and how you fixed it.

**Comment by neoraj3-github** [comment]
it's funny but the VM i am running has no antivirus and I get this same error. 

 OSError: [WinError 87] The parameter is incorrect
