### ISSUE TITLE
Cannot start jupyter notebook

### ISSUE THREAD

**Issue by vrastil** [jupyter/notebook#4303]
When I try to start (any) jupyter notebook directly, I get the following error:

     Traceback (most recent call last):
      File "/usr/bin/jupyter-notebook", line 11, in <module>
        sys.exit(main())
      File "/usr/lib/python2.7/site-packages/jupyter_core/application.py",     line 266, in launch_instance
        return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
      File "/usr/lib/python2.7/site-    packages/traitlets/config/application.py", line 658, in launch_instance
        app.start()
      File "/usr/lib/python2.7/site-packages/notebook/notebookapp.py",     line 1784, in start
        self.launch_browser()
      File "/usr/lib/python2.7/site-packages/notebook/notebookapp.py",     line 1742, in launch_browser
        with open(fd, 'w', encoding='utf-8') as fh:
    TypeError: coercing to Unicode: need string or buffer, int found

However, if I only start jupyter on some directory, I can open notebooks through browser just fine.
I installed jupyter through pip (not using anaconda).

jupyter version: 4.4.0
python version: 2.7.15
OS: Fedora 29

**Comment by o-smirnov** [comment]
I confirm the problem. Offending code is here: https://github.com/jupyter/notebook/blob/master/notebook/notebookapp.py#L1749

Clearly it should be passing open_file, not fd to the open() call.

**Comment by o-smirnov** [comment]
Problem was introduced in notebook=5.7.3. Running with 5.7.2 works.

**Comment by takluyver** [comment]
Passing fd was intentional, but I hadn't realised that that was a new feature on Python 3.

**Comment by slel** [comment]
In the end the fix is at #4349 and should be part of
notebook 5.7.5 when it is released.
