### ISSUE TITLE
Jupyter Notebook Ordinal Not Found

### ISSUE THREAD

**Issue by zlashie** [jupyter/notebook#4320]
I am new to Jupyter Notebook and thus trying to resolve the issue by googling it has not worked out for me. I have tried about a dozen different solutions all for which have not solved the problem. So now I have uninstalled all files and tried a fresh install. 

Here is the process;
1. Downloaded Anaconda 2018.12 Python 3.7 64-Bit version.
2. Installed said file.
3. Opened Jupyter Notebook and the file I want to access (A school project submitted by my course responsible) 
4. Run the first line of code.

ERROR: "Python. exe - Ordinal not found
"Ordinal 242 not found in DLL-Library
C:\ProgramData\Anaconda3\Library\bin\mkl_intel_thread.dll"

Any suggestions? I would appreciate it very much if I could get this solved :)

**Comment by zlashie** [comment]
It appears that it dies specifically to the line "import numpy as np" however according to Anaconda Navigator, I do have the library in my environments tab

**Comment by jasongrout** [comment]
This looks like a problem with the Anaconda setup, not Jupyter. I'd suggest asking on the Anaconda support channels.

A short google did turn up this possibly relevant page: https://stackoverflow.com/questions/53026985/the-ordinal-242-could-not-be-located-in-the-dynamic-link-library-anaconda3-libra

**Comment by zlashie** [comment]
> 
> 
> This looks like a problem with the Anaconda setup, not Jupyter. I'd suggest asking on the Anaconda support channels.
> 
> A short google did turn up this possibly relevant page: https://stackoverflow.com/questions/53026985/the-ordinal-242-could-not-be-located-in-the-dynamic-link-library-anaconda3-libra

Hello. I have resolved this issue but a new issue has arised. I installed Python and installed Jupyter Notebook through Python. However, now when I open Jupyter Notebook, I have a "kernel error" with 

"Traceback (most recent call last):
  File "c:\users\ztek\appdata\local\programs\python\python37\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "c:\users\ztek\appdata\local\programs\python\python37\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "c:\users\ztek\appdata\local\programs\python\python37\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\users\ztek\appdata\local\programs\python\python37\lib\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "c:\users\ztek\appdata\local\programs\python\python37\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "c:\users\ztek\appdata\local\programs\python\python37\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\users\ztek\appdata\local\programs\python\python37\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "c:\users\ztek\appdata\local\programs\python\python37\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "c:\users\ztek\appdata\local\programs\python\python37\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\users\ztek\appdata\local\programs\python\python37\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "c:\users\ztek\appdata\local\programs\python\python37\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "c:\users\ztek\appdata\local\programs\python\python37\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "c:\users\ztek\appdata\local\programs\python\python37\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "c:\users\ztek\appdata\local\programs\python\python37\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "c:\users\ztek\appdata\local\programs\python\python37\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
    **kw)
  File "c:\users\ztek\appdata\local\programs\python\python37\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "c:\users\ztek\appdata\local\programs\python\python37\lib\site-packages\jupyter_client\launcher.py", line 138, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "c:\users\ztek\appdata\local\programs\python\python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\users\ztek\appdata\local\programs\python\python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file spec"

**Comment by n59e11** [comment]
If you resolved the issue, please say something about how, because I came here in search for the same problem as you had. It's a bit sad to find the problem and the "empty statement" about having resolved it.
