### ISSUE TITLE
Jupyter tries to import typing.py from the same folder

### ISSUE THREAD

**Issue by jacopofar** [jupyter/notebook#4390]
Hello,
I found a weird behavior of Jupyter notebook: when in the same folder of a notebook there's a file called `typing.py` it is imported every time I run a cell from the notebook, no matter the content.

I'm using `Python 3.7.2` on `macOS 10.14.2` and my Notebook version is `5.7.4`.

Steps to reproduce:

1. create a file `typing.py`in a folder, with arbitrary Python code
2. create a notebook in the same folder, with arbitrary Python code
3. run a cell of the notebook, the other file is imported

If in `typing.py` I raise an exception I get this:

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jacopo/.scientific_jupyter/lib/python3.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/Users/jacopo/.scientific_jupyter/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/Users/jacopo/.scientific_jupyter/lib/python3.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/Users/jacopo/.scientific_jupyter/lib/python3.7/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/Users/jacopo/.scientific_jupyter/lib/python3.7/site-packages/IPython/terminal/embed.py", line 14, in <module>
    from IPython.core.magic import Magics, magics_class, line_magic
  File "/Users/jacopo/.scientific_jupyter/lib/python3.7/site-packages/IPython/core/magic.py", line 22, in <module>
    from IPython.core.inputtransformer2 import ESC_MAGIC, ESC_MAGIC2
  File "/Users/jacopo/.scientific_jupyter/lib/python3.7/site-packages/IPython/core/inputtransformer2.py", line 16, in <module>
    from typing import List, Tuple, Union
  File "/Users/jacopo/Downloads/something/typing.py", line 1, in <module>
    raise ValueError('I am typing.py!')
ValueError: I am typing.py!
```

**Comment by IamViditAgarwal** [comment]
@jacopofar  I tried to reproduce the error , But its not auto importing in my case. Can u please provide some extra information on this issue

**Comment by jacopofar** [comment]
Sure, these are the versions of all the packages installed in that virtual env:

<details>


```
appnope==0.1.0
astroid==2.1.0
backcall==0.1.0
bleach==3.0.2
certifi==2018.11.29
chardet==3.0.4
colorclass==2.2.0
colorlover==0.2.1
cufflinks==0.14.6
cycler==0.10.0
decorator==4.3.0
defusedxml==0.5.0
docopt==0.6.2
dodgy==0.1.9
entrypoints==0.3
fastavro==0.21.16
flake8==3.6.0
flake8-polyfill==1.0.2
footballdata==0.3.1
holidays==0.9.9
html5lib==1.0.1
idna==2.8
ipykernel==5.1.0
ipython==7.2.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
isort==4.3.4
jedi==0.13.2
Jinja2==2.10
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-contrib-core==0.3.3
jupyter-core==4.4.0
jupyter-nbextensions-configurator==0.4.1
jupyterlab==0.35.4
jupyterlab-launcher==0.13.1
jupyterlab-server==0.2.0
kazoo==2.6.0
kiwisolver==1.0.1
lazy-object-proxy==1.3.1
MarkupSafe==1.1.0
matplotlib==3.0.2
mccabe==0.6.1
mistune==0.8.4
mpmath==1.1.0
nbconvert==5.4.0
nbformat==4.4.0
nose==1.3.7
notebook==5.7.4
numpy==1.15.4
packaging==18.0
pandas==0.23.4
pandocfilters==1.4.2
parso==0.3.1
pdfminer.six==20181108
pep8-naming==0.7.0
pexpect==4.6.0
pickleshare==0.7.5
Pillow==5.4.1
pip-upgrader==1.4.6
pipupgrade==1.1.6
plotly==3.5.0
prometheus-client==0.5.0
prompt-toolkit==2.0.7
prospector==1.1.6.2
psycopg2==2.7.6.1
ptyprocess==0.6.0
pycodestyle==2.4.0
pycryptodome==3.7.2
pydocstyle==3.0.0
pyflakes==2.0.0
Pygments==2.3.1
pykafka==2.8.0
pylint==2.2.2
pylint-celery==0.3
pylint-django==2.0.2
pylint-flask==0.5
pylint-plugin-utils==0.4
pyparsing==2.3.0
PyQt5==5.11.2
PyQt5-sip==4.19.12
python-dateutil==2.7.5
python-dotenv==0.10.1
pytz==2018.9
PyYAML==3.13
pyzmq==17.1.2
qtconsole==4.4.3
requests==2.21.0
requirements-detector==0.6
retrying==1.3.3
scikit-learn==0.20.2
scipy==1.2.0
Send2Trash==1.5.0
setoptconf==0.2.0
simplegeneric==0.8.1
sip==4.19.8
six==1.12.0
snowballstemmer==1.2.1
sortedcontainers==2.1.0
SQLAlchemy==1.2.15
sqlalchemy-redshift==0.7.2
sympy==1.3
tabulate==0.8.2
terminado==0.8.1
terminaltables==3.1.0
testpath==0.4.2
torch==1.0.0
torchvision==0.2.1
tornado==5.1.1
traitlets==4.3.2
Unidecode==1.0.23
urllib3==1.24.1
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.4.2
wrapt==1.10.11
xgboost==0.81
```

</details>

I start Jupyter with the `jupyter-notebook` command.

[This](https://asciinema.org/a/XL4cRnEtc1oHHXXgh7yMyukwD) is a recording of said error, I started Jupyter, opened an empty notebook in the same folder of `typing.py` and tried to execute a cell containing `print(2+3)`.

I also checked now the `PYTHONPATH` environment variable in case it had some weird content but it's not set.

**Comment by IamViditAgarwal** [comment]
@jacopofar  I have tried this way also, By creating a virtual environment, installed all the requirements that u have given and created the typing.py file and opened the Jupyter notebook, But still, I am not able to reproduce the error. Everything is working fine..
Can u post the contents of PYTHONPATH?.

**Comment by jacopofar** [comment]
It's empty, the variable is not set at all.

I tried now to display the value at runtime with

```
import os
print(os.environ)
raise ValueError('they are calling me!')
```
but even there it's not set.

**Comment by jacopofar** [comment]
I think this issue can be closed. It's no relevant anymore for me and is just a side effect of the value of PYTHONPATH in some configurations and the fact I had a file with this name.
