### ISSUE TITLE
weird behavior with pypy3

### ISSUE THREAD

**Issue by josecleiton** [jupyter/notebook#4432]
I've installed all using `pypy3 -m pip jupyter --user`, but when i tried to run the `jupyter notebook` command i get following error: 
```
Traceback (most recent call last):
  File "/home/josec/.local/bin/jupyter-notebook", line 6, in <module>
    from notebook.notebookapp import main
  File "/home/josec/.local/lib/pypy3.6/site-packages/notebook/notebookapp.py", line 79, in <module>
    from .base.handlers import Template404, RedirectWithParams
  File "/home/josec/.local/lib/pypy3.6/site-packages/notebook/base/handlers.py", line 32, in <module>
    import prometheus_client
  File "/home/josec/.local/lib/pypy3.6/site-packages/prometheus_client/__init__.py", line 5, in <module>
    from . import gc_collector
  File "/home/josec/.local/lib/pypy3.6/site-packages/prometheus_client/gc_collector.py", line 46, in <module>
    GC_COLLECTOR = GCCollector()
  File "/home/josec/.local/lib/pypy3.6/site-packages/prometheus_client/gc_collector.py", line 17, in __init__
    registry.register(self)
  File "/home/josec/.local/lib/pypy3.6/site-packages/prometheus_client/registry.py", line 24, in register
    names = self._get_names(collector)
  File "/home/josec/.local/lib/pypy3.6/site-packages/prometheus_client/registry.py", line 64, in _get_names
    for metric in desc_func():
  File "/home/josec/.local/lib/pypy3.6/site-packages/prometheus_client/gc_collector.py", line 37, in collect
    for generation, stat in enumerate(gc.get_stats()):
TypeError: 'GcStats' object is not iterable

```

**Comment by chq-matteo** [comment]
Did you manage to solve this issue?
