### ISSUE TITLE
Event loop already running? and restarting not possible (There is no currente ven lop in thread 'Thread-2')

### ISSUE THREAD

**Issue by SumNeuron** [jupyter/notebook#4446]
Just encountered a new error that I have never seen before...
thoughts?
```
[W 10:12:21.055 NotebookApp] Error loading server extension jupyter_nbextensions_configurator
    Traceback (most recent call last):
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1117, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/home/sumner/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'
[I 10:12:21.058 NotebookApp] Serving notebooks from local directory: /home/sumner/<PROJECT>
[I 10:12:21.058 NotebookApp] 0 active kernels 
[I 10:12:21.058 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=962cab80cc31a452782efee2d9082982ffcc97221c4f31df
[I 10:12:21.058 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:12:21.059 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=962cab80cc31a452782efee2d9082982ffcc97221c4f31df
[I 10:12:21.340 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[W 10:12:21.712 NotebookApp] 404 GET /nbextensions/nbextensions_configurator/tree_tab/main.js?v=20190304101220 (127.0.0.1) 11.42ms referer=http://localhost:8888/tree?token=6a24bbeb12a58480ac84231d26c85d3a401a93a9a27c7ba3
[W 10:12:25.656 NotebookApp] 404 GET /nbextensions/nbextensions_configurator/config_menu/main.js?v=20190304101220 (127.0.0.1) 1.45ms referer=http://localhost:8888/notebooks/Twin%20Embedding%20-%20NN.ipynb
[W 10:12:25.660 NotebookApp] 404 GET /nbextensions/collapsibleheadings.js?v=20190304101220 (127.0.0.1) 1.38ms referer=http://localhost:8888/notebooks/Twin%20Embedding%20-%20NN.ipynb
[W 10:12:25.662 NotebookApp] 404 GET /nbextensions/Collapsible.js?v=20190304101220 (127.0.0.1) 1.31ms referer=http://localhost:8888/notebooks/Twin%20Embedding%20-%20NN.ipynb
[W 10:12:25.664 NotebookApp] 404 GET /nbextensions/collapsible_headings.js?v=20190304101220 (127.0.0.1) 1.02ms referer=http://localhost:8888/notebooks/Twin%20Embedding%20-%20NN.ipynb
[W 10:12:25.666 NotebookApp] 404 GET /nbextensions/collapse.js?v=20190304101220 (127.0.0.1) 1.01ms referer=http://localhost:8888/notebooks/Twin%20Embedding%20-%20NN.ipynb
[E 10:12:25.925 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 526, in get
        value = obj._trait_values[self.name]
    KeyError: 'loop'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/notebook/base/handlers.py", line 503, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/notebook/services/sessions/handlers.py", line 75, in post
        type=mtype))
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
        yielded = next(result)
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 244, in start_kernel
        self.start_restarter()
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/jupyter_client/ioloop/manager.py", line 49, in start_restarter
        kernel_manager=self, loop=self.loop,
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 554, in __get__
        return self.get(obj, cls)
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 533, in get
        value = self._validate(obj, dynamic_default())
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 589, in _validate
        value = self.validate(obj, value)
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 1675, in validate
        self.error(obj, value)
      File "/home/sumner/anaconda3/lib/python3.6/site-packages/traitlets/traitlets.py", line 1522, in error
        raise TraitError(e)
    traitlets.traitlets.TraitError: The 'loop' trait of an IOLoopKernelManager instance must be a ZMQIOLoop, but a value of class 'tornado.platform.asyncio.AsyncIOMainLoop' (i.e. <tornado.platform.asyncio.AsyncIOMainLoop object at 0x7f4e8a902ba8>) was specified.
[E 10:12:25.930 NotebookApp] {
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "Referer": "http://localhost:8888/notebooks/Twin%20Embedding%20-%20NN.ipynb",
      "Content-Type": "application/json",
      "X-Xsrftoken": "2|de60568f|adabcd00b487af0d22313dd239c9eea8|1550049426",
      "X-Requested-With": "XMLHttpRequest",
      "Content-Length": "102",
      "Connection": "keep-alive",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1551690741|23:username-localhost-8888|44:YjZmM2I0NDI1OWQzNDBjN2ExNDNiZTJlZjZiMzU3MmM=|0062c9408c0c893aba20658782bd2bda69ed05c6c67f98f08282a5dc395a1faa\"; _xsrf=2|de60568f|adabcd00b487af0d22313dd239c9eea8|1550049426; csrftoken=X1FDZVfIXC9TkvpBqpsfuiRbGfZuBRfuNYQ1B7VLAG5pF9cQMjMLmwBlTub5WKGT"
    }
[E 10:12:25.930 NotebookApp] 500 POST /api/sessions (127.0.0.1) 34.32ms referer=http://localhost:8888/notebooks/Twin%20Embedding%20-%20NN.ipynb
[W 10:12:26.019 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20190304101220 (127.0.0.1) 3.65ms referer=http://localhost:8888/notebooks/Twin%20Embedding%20-%20NN.ipynb
[W 10:12:26.070 NotebookApp] 404 GET /static/components/bootstrap/js/tooltip.js?v=20190304101220 (127.0.0.1) 2.20ms referer=http://localhost:8888/notebooks/Twin%20Embedding%20-%20NN.ipynb
Traceback (most recent call last):
  File "/home/sumner/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/sumner/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sumner/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/sumner/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/sumner/anaconda3/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/home/sumner/anaconda3/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/home/sumner/anaconda3/lib/python3.6/asyncio/base_events.py", line 425, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

then ctrl-c twice:

```
[C 10:17:07.211 NotebookApp] received signal 2, stopping
No answer for 5s: resuming operation...
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/sumner/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/sumner/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sumner/anaconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1084, in _confirm_exit
    ioloop.IOLoop.current().add_callback(self._restore_sigint_handler)
  File "/home/sumner/anaconda3/lib/python3.6/site-packages/zmq/eventloop/ioloop.py", line 116, in current
    loop = ioloop.IOLoop.current(*args, **kwargs)
  File "/home/sumner/anaconda3/lib/python3.6/site-packages/tornado/ioloop.py", line 282, in current
    loop = asyncio.get_event_loop()
  File "/home/sumner/anaconda3/lib/python3.6/asyncio/events.py", line 694, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/home/sumner/anaconda3/lib/python3.6/asyncio/events.py", line 602, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-2'.


```

**Comment by minrk** [comment]
What's `pip list` and/or `conda list`? This looks to me like notebook and/or pyzmq might be out of date

**Comment by jbbqqf** [comment]
Hi! Triaging older issues — I think this can be closed.

This 2019 traceback comes from `jupyter_nbextensions_configurator`, a third-party server extension that is **not part of `jupyter/notebook`** and that is no longer compatible with Notebook v7 (which is JupyterLab-based — see [README's "Maintained versions"](https://github.com/jupyter/notebook#maintained-versions)).

If you're still hitting an event-loop error on a current install, the right venue depends on what you're running:
- `pip install notebook` → v7 → no `nbextensions_configurator` involved; please file fresh with versions and a minimal repro.
- Classic v6 → security-only on the [`6.5.x` branch](https://github.com/jupyter/notebook/tree/6.5.x).
- The configurator project itself: [`jupyter-contrib/jupyter_nbextensions_configurator`](https://github.com/jupyter-contrib/jupyter_nbextensions_configurator).

Suggest closing here.

(Disclosure: I drafted this comment with help from Claude Code while triaging stale issues; the references were verified manually.)
