### ISSUE TITLE
Jupyter notebook not working on fresh install of Anaconda or Miniconda

### ISSUE THREAD

**Issue by hrvojej** [jupyter/notebook#4452]
After fresh install of Anaconda/Miniconda here is error I got.

(base) C:\Users\hrvoje.jerkovic>jupyter notebook
Traceback (most recent call last):
  File "C:\Users\hrvoje.jerkovic\AppData\Local\Continuum\miniconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 10, in <module>
    import sqlite3
  File "C:\Users\hrvoje.jerkovic\AppData\Local\Continuum\miniconda3\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "C:\Users\hrvoje.jerkovic\AppData\Local\Continuum\miniconda3\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\hrvoje.jerkovic\AppData\Local\Continuum\miniconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\Users\hrvoje.jerkovic\AppData\Local\Continuum\miniconda3\lib\site-packages\notebook\notebookapp.py", line 86, in <module>
    from .services.sessions.sessionmanager import SessionManager
  File "C:\Users\hrvoje.jerkovic\AppData\Local\Continuum\miniconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 13, in <module>
    from pysqlite2 import dbapi2 as sqlite3
ModuleNotFoundError: No module named 'pysqlite2'

**Comment by minrk** [comment]
I think that means the Python installation itself is messed up. `sqlite3` is part of Python and needs to work. I'd bring that up with Anaconda folks.

We fallback on `pysqlite2` when the stdlib sqlite3 is broken (you can `pip install pysqlite2`), but this is a symptom of a deeper problem with the install that I probably wouldn't want to work around.
