### ISSUE TITLE
can't open this jupyter notebook

### ISSUE THREAD

**Issue by 66chenbiao** [jupyter/notebook#4489]
(base) C:\Users\ASUS>jupyter notebook
Traceback (most recent call last):
  File "E:\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "E:\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 39, in <module>
    from zmq.eventloop import ioloop
  File "E:\Anaconda3\lib\site-packages\zmq\eventloop\__init__.py", line 3, in <module>
    from zmq.eventloop.ioloop import IOLoop
  File "E:\Anaconda3\lib\site-packages\zmq\eventloop\ioloop.py", line 21, in <module>
    from zmq import (
ImportError: cannot import name 'Poller'

**Comment by minrk** [comment]
this suggests that zmq is not installed properly. Try reinstalling pyzmq:

   conda install pyzmq

or remove and reinstall it.

**Comment by 66chenbiao** [comment]
I uninstalled anaconda directly, which doesn't seem to be compatible with many things.
