### ISSUE TITLE
Sphinx 2.0.0 incompatibilities

### ISSUE THREAD

**Issue by hroncok** [jupyter/notebook#4533]
When i tyr to build the docs with Sphinx 2.0.0b1:

```
+ sphinx-build -D intersphinx_timeout=1 docs/source html
Running Sphinx v2.0.0b1
DEBUG:: sys.path
================
/usr/bin
/usr/lib64/python37.zip
/usr/lib64/python3.7
/usr/lib64/python3.7/lib-dynload
/usr/lib64/python3.7/site-packages
/usr/lib/python3.7/site-packages
repo_root
=====================
/builddir/build/BUILD/notebook-5.7.7
DEBUG:: Post insert to sys.path
===============================
/builddir/build/BUILD/notebook-5.7.7
/builddir/build/BUILD/notebook-5.7.7/docs/sphinxext
/usr/bin
/usr/lib64/python37.zip
/usr/lib64/python3.7
/usr/lib64/python3.7/lib-dynload
/usr/lib64/python3.7/site-packages
/usr/lib/python3.7/site-packages

Exception occurred:
  File "/builddir/build/BUILD/notebook-5.7.7/docs/sphinxext/github.py", line 149, in setup
    app.info('Initializing GitHub plugin')
AttributeError: 'Sphinx' object has no attribute 'info'
The full traceback has been saved in /tmp/sphinx-err-2f2asxjo.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
+ :
+ cat /tmp/sphinx-err-2f2asxjo.log
# Sphinx version: 2.0.0b1
# Python version: 3.7.2 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/sphinx/cmd/build.py", line 283, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/usr/lib/python3.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.7/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.7/site-packages/sphinx/registry.py", line 484, in load_extension
    metadata = mod.setup(app)
  File "/builddir/build/BUILD/notebook-5.7.7/docs/sphinxext/github.py", line 149, in setup
    app.info('Initializing GitHub plugin')
AttributeError: 'Sphinx' object has no attribute 'info'
```

**Comment by hroncok** [comment]
Looks like https://github.com/jupyter/sphinxcontrib_github_alt/pull/2

**Comment by hroncok** [comment]
https://github.com/jupyter/notebook/pull/4534

**Comment by takluyver** [comment]
I've opened #4536 to follow up by removing the bundled copy and using the separately packaged extension, so this kind of thing only needs to be fixed once in the future.
