### ISSUE TITLE
Conda update causes Name or service not known error

### ISSUE THREAD

**Issue by vgensini** [jupyter/notebook#4558]
https://github.com/jupyterlab/jupyterlab/issues/6180

After updating conda yesterday, I now find that my personal jupyter-lab server cannot start due to a socket error below. I have all needed settings in my jupyter_notebook_config.py file (it was working fine for many months prior to yesterday).

jupyter-lab
[I 19:35:40.600 LabApp] [nb_conda_kernels] enabled, 10 kernels found
Traceback (most recent call last):
File "/home/vgensini/Programs/anaconda2/bin/jupyter-lab", line 11, in 
sys.exit(main())
File "/home/vgensini/Programs/anaconda2/lib/python2.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
File "/home/vgensini/Programs/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
app.initialize(argv)
File "", line 2, in initialize
File "/home/vgensini/Programs/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "/home/vgensini/Programs/anaconda2/lib/python2.7/site-packages/notebook/notebookapp.py", line 1628, in initialize
self.init_webapp()
File "/home/vgensini/Programs/anaconda2/lib/python2.7/site-packages/notebook/notebookapp.py", line 1378, in init_webapp
self.jinja_environment_options,
File "/home/vgensini/Programs/anaconda2/lib/python2.7/site-packages/notebook/notebookapp.py", line 159, in init
default_url, settings_overrides, jinja_env_options)
File "/home/vgensini/Programs/anaconda2/lib/python2.7/site-packages/notebook/notebookapp.py", line 252, in init_settings
allow_remote_access=jupyter_app.allow_remote_access,
File "/home/vgensini/Programs/anaconda2/lib/python2.7/site-packages/traitlets/traitlets.py", line 556, in get
return self.get(obj, cls)
File "/home/vgensini/Programs/anaconda2/lib/python2.7/site-packages/traitlets/traitlets.py", line 535, in get
value = self._validate(obj, dynamic_default())
File "/home/vgensini/Programs/anaconda2/lib/python2.7/site-packages/notebook/notebookapp.py", line 867, in _default_allow_remote
for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
socket.gaierror: [Errno -2] Name or service not known

`jupyter notebook --version` 5.7.4

Any ideas what is going on here?

**Comment by jasongrout** [comment]
To be clear, @vgensini also said that `jupyter notebook` didn't work with the same error.

**Comment by jasongrout** [comment]
Googling the error message also seems to give some helpful information: https://www.google.com/search?q=%22socket.gaierror%3A+[Errno+-2]+Name+or+service+not+known%22

**Comment by vgensini** [comment]
Problem solved. In your jupyter_notebook_config.py file:

Change `c.NotebookApp.ip = '*'`

to:

`c.NotebookApp.ip = '0.0.0.0'`
