### ISSUE TITLE
Jupyter Notebook cannot connect to Python3 kernel

### ISSUE THREAD

**Issue by ColbyOstberg** [jupyter/notebook#4572]
Jupyter worked fine, then I ran into an issue with anaconda and uninstalled and reinstalled it, and after that my Jupyter notebooks/labs failed to connect to kernels and gave me the following error message:
Traceback (most recent call last):

  File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
    result = await result
  File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 73, in post
    type=mtype))
  File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 736, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 729, in run
    value = future.result()
  File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/jupyter_client/manager.py", line 259, in start_kernel
    **kw)
  File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/jupyter_client/manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/Users/colbyostberg/anaconda3/lib/python3.7/site-packages/jupyter_client/launcher.py", line 138, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/Users/colbyostberg/anaconda3/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Users/colbyostberg/anaconda3/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/anaconda3/envs/py37/bin/python': '/anaconda3/envs/py37/bin/python'

It is super frustrating and I am hoping to get it resolved ASAP

**Comment by ColbyOstberg** [comment]
I have attempted to completely clean out my system of all anaconda packages multiple times and reinstall it and the problem has yet to cease

**Comment by kevin-bates** [comment]
This is probably pushing my understanding of python envs, but I suspect the kernelspec that is trying to be used is pointing at the deleted python (assuming `/anaconda3/envs/py37/bin/python` was the deleted env).

Try running `jupyter kernelspecs list`.  This will produce a list of kernel/directory pairs.  Unfortunately, the kernel named in this list is not the "display name" used when you select the kernel in Notebook/Lab, but I'm hoping you can narrow things down.

Of the candidate entries, open the `<directory>/kernel.json` file.  In the first entry of the `argv` stanza is the path to the python executable.  I suspect you'll find `/opt/anaconda3/envs/notebook-dev/share/jupyter/kernels/python3` when you probably want the python bin from `/Users/colbyostberg/anaconda3`.

**Comment by ColbyOstberg** [comment]
I appreciate your quick response so much. I went into the .json file and changed the first stanza to /Users/colbyostberg/anaconda3/bin/python3 and we are back up and running. I am assuming this is an issue with this .json file being left over from my previously deleted anaconda. But anyways I appreciate you! Thank you!

**Comment by kevin-bates** [comment]
@ColbyOstberg - could you please close this issue so that its "off the books"?  Thanks.
