### ISSUE TITLE
pysqlite2 error while launching Jupyter notebook

### ISSUE THREAD

**Issue by draj1979** [jupyter/notebook#4577]
Hi,
I downloaded Anaconda and tried to launch Jupyter notebook but it cannot launch giving error as below:
Traceback (most recent call last):
File "D:\Lynda\Anaconda\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 10, in 
import sqlite3
File "D:\Lynda\Anaconda\lib\sqlite3\__init__.py", line 23, in 
from sqlite3.dbapi2 import *
File "D:\Lynda\Anaconda\lib\sqlite3\dbapi2.py", line 27, in 
from _sqlite3 import *
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "D:\Lynda\Anaconda\Scripts\jupyter-notebook-script.py", line 6, in 
from notebook.notebookapp import main
File "D:\Lynda\Anaconda\lib\site-packages\notebook\notebookapp.py", line 86, in 
from .services.sessions.sessionmanager import SessionManager
File "D:\Lynda\Anaconda\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 13, in 
from pysqlite2 import dbapi2 as sqlite3
ModuleNotFoundError: No module named 'pysqlite2'

**Comment by margegaj24** [comment]
Go to D:\Lynda\Anaconda\lib\site-packages\notebook\services\sessions\sessionmanager.py and comment the line: from pysqlite2 import dbapi2 as sqlite3 and then import pysqlite3 as sqlite3. This solution worked for me

**Comment by adriangeerre** [comment]
This worked for me:

https://askubuntu.com/a/1410175
