### ISSUE TITLE
Installed Javascript kernel but getting Kernel Error

### ISSUE THREAD

**Issue by rtaneja1997** [jupyter/notebook#4632]
Whenever I try switching the running Kernel in my Jupyter notebook from Python to Javascript (Node.js), I get the following error: 

`Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/Library/Python/2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Library/Python/2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/Library/Python/2.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/tanejar/Library/Python/2.7/lib/python/site-packages/notebook/services/sessions/handlers.py", line 73, in post
    type=mtype))
  File "/Library/Python/2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Library/Python/2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/Library/Python/2.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/tanejar/Library/Python/2.7/lib/python/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/Library/Python/2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Library/Python/2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/Library/Python/2.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/tanejar/Library/Python/2.7/lib/python/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/Library/Python/2.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/Library/Python/2.7/site-packages/tornado/concurrent.py", line 261, in result
    raise_exc_info(self._exc_info)
  File "/Library/Python/2.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/Users/tanejar/Library/Python/2.7/lib/python/site-packages/notebook/services/kernels/kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/Library/Python/2.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/Library/Python/2.7/site-packages/jupyter_client/manager.py", line 259, in start_kernel
    **kw)
  File "/Library/Python/2.7/site-packages/jupyter_client/manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/Library/Python/2.7/site-packages/jupyter_client/launcher.py", line 138, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`

I'm not sure what's going on. I did jupyter kernelspec list and sure enough I have 2 kernels and their paths, I navigated the path for the python one and the argv first instance is set to usr/bin/python.

**Comment by kevin-bates** [comment]
If I understand your scenario, I suspect this is failing to launch the JS kernel.  There should be an error message prior to this traceback that contains the command string used in the Popen call.  That is most likely the subject of the `Errno 2` as that command is not accessible for whatever reason.

If you don't see the logged error, which should start with a string like `Failed to run command:`, check the kernel.json's `argv` stanza corresponding to the JS kernel and ensure the first entry is accessible or, better yet, fully qualified.
