### ISSUE TITLE
SyntaxError with Python 2

### ISSUE THREAD

**Issue by Elizaveta239** [jupyter/notebook#4644]
Hi! I've installed Python 2.7.15 on Ubuntu and installed latest `jupyter` package.
I'm getting the following error when executing `jupyter notebook`:
```
/home/user/work/jupyter_env/pythons/py27_jupyter/bin/jupyter notebook

Traceback (most recent call last):
  File "/home/user/work/jupyter_env/pythons/py27_jupyter/bin/jupyter-notebook", line 6, in <module>
    from notebook.notebookapp import main
  File "/home/user/work/jupyter_env/pythons/py27_jupyter/lib/python2.7/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/home/user/work/jupyter_env/pythons/py27_jupyter/lib/python2.7/site-packages/notebook/nbextensions.py", line 610, in <module>
    from .extensions import (
  File "/home/user/work/jupyter_env/pythons/py27_jupyter/lib/python2.7/site-packages/notebook/extensions.py", line 8, in <module>
    from tornado.log import LogFormatter
  File "/home/user/.local/lib/python2.7/site-packages/tornado/log.py", line 55
    def _stderr_supports_color() -> bool:
                                 ^
SyntaxError: invalid syntax
```

It looks like the problem is related to tornado 6 and this issue: #4439

**Comment by Elizaveta239** [comment]
Packages list:
```
attrs==19.1.0
backports.shutil-get-terminal-size==1.0.0
bleach==3.1.0
bokeh==1.1.0
configparser==3.7.4
decorator==4.4.0
defusedxml==0.6.0
entrypoints==0.3
enum34==1.1.6
functools32==3.2.3.post2
futures==3.2.0
ipaddress==1.0.22
ipykernel==4.10.0
ipython==5.8.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
Jinja2==2.10.1
jsonschema==3.0.1
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==5.2.0
jupyter-core==4.4.0
MarkupSafe==1.1.1
mistune==0.8.4
nbconvert==5.5.0
nbformat==4.4.0
notebook==5.7.8
numpy==1.16.3
packaging==19.0
pandocfilters==1.4.2
pathlib2==2.3.3
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.0.0
prometheus-client==0.6.0
prompt-toolkit==1.0.16
ptyprocess==0.6.0
Pygments==2.4.1
pyparsing==2.4.0
pyrsistent==0.15.2
python-dateutil==2.8.0
PyYAML==5.1
pyzmq==18.0.1
qtconsole==4.5.1
scandir==1.10.0
Send2Trash==1.5.0
simplegeneric==0.8.1
six==1.12.0
terminado==0.8.2
testpath==0.4.2
tornado==6.0.2
traitlets==4.3.2
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.4.2

```

**Comment by bpartin2009** [comment]
I'm Having the exact same issue.........
What was the resolution to your problem?

**Comment by krishnakakade1999** [comment]
Hey hello geeks you can try latest version of python 3.7 and jupyter  newest version by (sudo get update python/jupyter) and then upgrade to latest version that is going to help you guys that's work for me hope you are going to try .

upgrade your terminal also 
sudo apt-get update

sudo apt-get install python(ver) 
and for jupyter also ok

**Comment by krishnakakade1999** [comment]
i hope this issue is solve let me know

**Comment by theshubhamgoel** [comment]
Still facing the same issue. Attaching the log -

'import sitecustomize' failed; use -v for traceback
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 6, in <module>
    from notebook.notebookapp import main
  File "/usr/local/lib/python3.7/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/usr/local/lib/python3.7/site-packages/notebook/nbextensions.py", line 610, in <module>
    from .extensions import (
  File "/usr/local/lib/python3.7/site-packages/notebook/extensions.py", line 8, in <module>
    from tornado.log import LogFormatter
  File "/usr/local/lib/python3.7/site-packages/tornado/log.py", line 55
    def _stderr_supports_color() -> bool:
                                 ^
SyntaxError: invalid syntax

**Comment by krishnakakade1999** [comment]
@theshubhamgoel  hey You can locate where you install that env for the notebook and delete that and set default bash line that is python 3 itself then install all packages you want then your issue is going to solve and install <b>Anaconda3</b> then let me know i hope this will work for you .

**Comment by doyeen** [comment]
I am on new Jupyter 3.7 which I installed with Anaconda. I was running a particular code and I got this error

  File "<ipython-input-14-a34f8ebcfcf7>", line 22
    dtf = dtf(["Id"]+df+["SalePrice"])
      ^
The arrow is pointing at f and when I removed the f, it still points to t.
What am I to do please?

I'm just begiining to try my hands on this because I've developed interest in Data Sc but i've not been putting it in practice.
