### ISSUE TITLE
Trying to open notebook but been getting this error

### ISSUE THREAD

**Issue by labaran1** [jupyter/notebook#4683]
Traceback (most recent call last):
File "/home/araneae/anaconda3/bin/jupyter-notebook", line 11, in 
sys.exit(main())
File "/home/araneae/anaconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
File "/home/araneae/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 657, in launch_instance
app.initialize(argv)
File "", line 2, in initialize
File "/home/araneae/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "/home/araneae/anaconda3/lib/python3.7/site-packages/notebook/notebookapp.py", line 1628, in initialize
self.init_webapp()
File "/home/araneae/anaconda3/lib/python3.7/site-packages/notebook/notebookapp.py", line 1407, in init_webapp
self.http_server.listen(port, self.ip)
File "/home/araneae/anaconda3/lib/python3.7/site-packages/tornado/tcpserver.py", line 143, in listen
sockets = bind_sockets(port, address=address)
File "/home/araneae/anaconda3/lib/python3.7/site-packages/tornado/netutil.py", line 168, in bind_sockets
sock.bind(sockaddr)
OSError: [Errno 99] Cannot assign requested address

**Comment by limbuu** [comment]
Add this in notebook dockerfile, it works. 
CMD ["jupyter","notebook","--ip='0.0.0.0'","--port=8888","--no-browser","--allow-root"]

**Comment by labaran1** [comment]
okay thanks
