### ISSUE TITLE
Jupyter Notebook Not Showing Up on Browser During Dev Mode

### ISSUE THREAD

**Issue by AbuditRai** [jupyter/notebook#4707]
I am currently trying to access dev mode on Jupyter Notebooks so I can work on fixing some of the accessibility issues. However after  following the https://jupyter-notebook.readthedocs.io/en/stable/contributing.html guide I run the "jupyter notebook" command in the terminal and the act of creating/opening an .ipynb file just results in me not seeing anything on the window, just blank. Even the book besides the file name in the directory page remains gray, not chaing into the open-green logo. I've tried the "Troubleshooting the Installation" steps, but I run into this error at the "npm run build" command:

>npm ERR! Linux 4.15.0-52-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! jupyter-notebook-deps@4.0.0 build: `python setup.py js css`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jupyter-notebook-deps@4.0.0 build script 'python setup.py js css'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the jupyter-notebook-deps package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     python setup.py js css
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs jupyter-notebook-deps
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls jupyter-notebook-deps
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
>npm ERR!     /home/abudit/notebook/npm-debug.log

The npm-debug.log file has this information in it:
>0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle jupyter-notebook-deps@4.0.0~prebuild: jupyter-notebook-deps@4.0.0
6 silly lifecycle jupyter-notebook-deps@4.0.0~prebuild: no script for prebuild, continuing
7 info lifecycle jupyter-notebook-deps@4.0.0~build: jupyter-notebook-deps@4.0.0
8 verbose lifecycle jupyter-notebook-deps@4.0.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle jupyter-notebook-deps@4.0.0~build: PATH: /usr/share/npm/bin/node-gyp-bin:/home/abudit/notebook/node_modules/.bin:/home/abudit/anaconda3/bin:/home/abudit/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle jupyter-notebook-deps@4.0.0~build: CWD: /home/abudit/notebook
11 silly lifecycle jupyter-notebook-deps@4.0.0~build: Args: [ '-c', 'python setup.py js css' ]
12 silly lifecycle jupyter-notebook-deps@4.0.0~build: Returned: code: 1  signal: null
13 info lifecycle jupyter-notebook-deps@4.0.0~build: Failed to exec build script
14 verbose stack Error: jupyter-notebook-deps@4.0.0 build: `python setup.py js css`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid jupyter-notebook-deps@4.0.0
16 verbose cwd /home/abudit/notebook
17 error Linux 4.15.0-52-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error jupyter-notebook-deps@4.0.0 build: `python setup.py js css`
22 error Exit status 1
23 error Failed at the jupyter-notebook-deps@4.0.0 build script 'python setup.py js css'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the jupyter-notebook-deps package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     python setup.py js css
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs jupyter-notebook-deps
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls jupyter-notebook-deps
23 error There is likely additional logging output above.
>24 verbose exit [ 1, true ]
I apologize about the crossing outs. They are supposed to have ~ before them, but I can't figure out how to format this part.

When I uninstall everything again and just download Anaconda-Navigator, I am able to use juptyer notebook once again through that but this does not give me dev mode. Does anyone have any ideas of what could be going wrong? I am on Ubuntu 18.04 if that helps with debugging this issue.

**Comment by AbuditRai** [comment]
I manged to solve this issue by uninstalling everything and updating my npm through instructions found here: https://www.hostinger.com/tutorials/how-to-install-node-ubuntu
