### ISSUE TITLE
python3-pip Error

### ISSUE THREAD

**Issue by YuGlede** [jupyter/notebook#4714]

**Comment by YuGlede** [comment]
I try to use pip3 install some package, but I got the following error, then the process failed
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 6, in <module>
    from pip._internal import main
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 16, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 30, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 6, in <module>
    import compileall
  File "/usr/lib/python3.5/compileall.py", line 20, in <module>
    from concurrent.futures import ProcessPoolExecutor
  File "/usr/lib/python2.7/dist-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/usr/lib/python2.7/dist-packages/concurrent/futures/_base.py", line 357
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax




I have tried many solutions, but none of them can make it, I hope someone can help me.
Thank you!

**Comment by yavalvas** [comment]
It doesn't seem to be related to this repository.

It looks that some libraries are mixed up from Python3.x and Python2.x in your local environment.
You use pip3 which calls dependencies from python2.7.
Then it fails with the invalid syntax of raise clause at the end probably because of:
[pep-3109](https://www.python.org/dev/peps/pep-3109/) changes in Python3.x
