### ISSUE TITLE
socket.gaierror: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by caozhen-alex** [jupyter/notebook#4715]
Hi, I got an issue as the title.
What I did is just to a public notebook server for my docker container conda env.
My workflow is like:
1. Create a config file for notebook by using the following command line: ```jupyter notebook --generate-config```

2. Generate a web certificate with `openssl` by ```openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout mykey.key -out mycert.pem #Bash```. Here 365 means the created certificate valid for 365 days.

3. Prepare a hashed password using the function ```notebook.auth.security.passwd()```. You can directly use *get_hashed_pw.ipynb*

4. Edit the step 1 created config file *jupyter_notebook_config.py* via uncommenting and completing
```
# Set options for certfile, ip, password, and toggle off
# browser auto-opening
c.NotebookApp.certfile = u'/absolute/path/to/your/certificate/mycert.pem'
c.NotebookApp.keyfile = u'/absolute/path/to/your/certificate/mykey.key'
# Set ip to '*' to bind on all interfaces (ips) for the public server
c.NotebookApp.ip = '*'
c.NotebookApp.password = u'sha1:bcd259ccf...<your hashed password here>'
c.NotebookApp.open_browser = False

# It is a good idea to set a known, fixed port for server access
c.NotebookApp.port = 9999
```

**Comment by caozhen-alex** [comment]
The bug reports:

> Traceback (most recent call last):
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'allow_remote_access'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/notebook/notebookapp.py", line 864, in _default_allow_remote
    addr = ipaddress.ip_address(self.ip)
  File "/home/user/miniconda/envs/py36/lib/python3.6/ipaddress.py", line 54, in ip_address
    address)
ValueError: '' does not appear to be an IPv4 or IPv6 address
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/user/miniconda/envs/py36/bin/jupyter-lab", line 10, in <module>
    sys.exit(main())
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "</home/user/miniconda/envs/py36/lib/python3.6/site-packages/decorator.py:decorator-gen-7>", line 2, in initialize
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/notebook/notebookapp.py", line 1630, in initialize
    self.init_webapp()
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/jupyterlab/labapp.py", line 353, in init_webapp
    super().init_webapp(*args, **kwargs)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/notebook/notebookapp.py", line 1378, in init_webapp
    self.jinja_environment_options,
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/notebook/notebookapp.py", line 159, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/notebook/notebookapp.py", line 252, in init_settings
    allow_remote_access=jupyter_app.allow_remote_access,
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/home/user/miniconda/envs/py36/lib/python3.6/site-packages/notebook/notebookapp.py", line 867, in _default_allow_remote
    for info in socket.getaddrinfo(self.ip, self.port, 0, socket.SOCK_STREAM):
  File "/home/user/miniconda/envs/py36/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

**Comment by JindongJiang** [comment]
Please try:
`c.NotebookApp.ip = '0.0.0.0'`

**Comment by caozhen-alex** [comment]
@JindongJiang 
It works. Thx JindongJiang. But what's the trick here between '0.0.0.0' and '*'?

**Comment by JindongJiang** [comment]
NP! Not a trick actually, just a jupyter's update.
