### ISSUE TITLE
Notebook cannot be started. Torando 5.1.1 does not help

### ISSUE THREAD

**Issue by Pierek** [jupyter/notebook#4736]
Hello,

I just want to run notebook.

I followed the normal procedure by installing jupyter using pip, then downgrading tornado to 5.1.1 version and after running notebook I constantly having this error:
~~~~
[I 16:09:55.332 NotebookApp] Adapting to protocol v5.1 for kernel 84970091-2bb3-4d04-8aa9-78c693a0b28e
[I 16:09:55.334 NotebookApp] Restoring connection for 84970091-2bb3-4d04-8aa9-78c693a0b28e:ae5539424f34421da0c1263fc96303ef
[I 16:09:55.352 NotebookApp] Starting buffering for 84970091-2bb3-4d04-8aa9-78c693a0b28e:ae5539424f34421da0c1263fc96303ef
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\tornado\websocket.py", line 874, in wrapper
    yield fut
  File "c:\program files\python37\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\program files\python37\lib\site-packages\tornado\websocket.py", line 876, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
~~~~

Python version is 3.7.3. Tried the same with 3.7.2 - not working

The only thing I can add is that recently I had some issues because of multiple python versions installed on my windows which I removed. After that I couldn't find a way to reinstall it in "Just for me" version (some core.msi was missing in the temp folder and python installer was just failing). Installing python for all users was successful. I don't know if this is linked. Anyways, I cannot find a way to just start notebook on my pc.

Thanks for help

**Comment by lresende** [comment]
I tried this on a new conda environment, installed NB 6.0.0rc1 and then downgraded Tornado to 5.1.1 and could not reproduce the issue. Below is a list of my installed dependencies:

```
pip list
Package           Version  
----------------- ---------
appnope           0.1.0    
attrs             19.1.0   
backcall          0.1.0    
bleach            3.1.0    
certifi           2019.6.16
decorator         4.4.0    
defusedxml        0.6.0    
entrypoints       0.3      
ipykernel         5.1.1    
ipython           7.5.0    
ipython-genutils  0.2.0    
jedi              0.14.0   
Jinja2            2.10.1   
jsonschema        3.0.1    
jupyter-client    5.2.4    
jupyter-core      4.5.0    
MarkupSafe        1.1.1    
mistune           0.8.4    
nbconvert         5.5.0    
nbformat          4.4.0    
notebook          6.0.0rc1 
opencv-python     4.0.0.21 
pandocfilters     1.4.2    
parso             0.5.0    
pexpect           4.7.0    
pickleshare       0.7.5    
pip               19.1.1   
prometheus-client 0.7.1    
prompt-toolkit    2.0.9    
ptyprocess        0.6.0    
Pygments          2.4.2    
pyrsistent        0.15.2   
python-dateutil   2.8.0    
pyzmq             18.0.2   
Send2Trash        1.5.0    
setuptools        41.0.1   
six               1.12.0   
terminado         0.8.2    
testpath          0.4.2    
tornado           5.1.1    
traitlets         4.3.2    
wcwidth           0.1.7    
webencodings      0.5.1    
wheel             0.33.4  
```

What version of the Notebook are you using? If not 6.0.0rc1, could you try with that?

**Comment by Pierek** [comment]
I tried to do what you've asked.
I installed full anaconda python3 dist from here https://www.anaconda.com/distribution/
After installation I ran `jupyter notebook` through the anaconda prompt and created a new nb there and got the same error.
After that I ran anaconda prompt - installed NB 6.0.0rc1 and downgraded tornado to 5.1.1 and still the same.

~~~~
[I 11:35:32.864 NotebookApp] Adapting from protocol version 5.1 (kernel 7bfdb603-4d2b-4745-b116-9222d7a79f8b) to 5.3 (client).
[I 11:35:32.864 NotebookApp] Restoring connection for 7bfdb603-4d2b-4745-b116-9222d7a79f8b:e4099265a5ab43888f90db237904af0f
[I 11:35:32.878 NotebookApp] Starting buffering for 7bfdb603-4d2b-4745-b116-9222d7a79f8b:e4099265a5ab43888f90db237904af0f
Future exception was never retrieved
future: <Future finished exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "c:\users\ppurwin\appdata\local\continuum\anaconda3\lib\site-packages\tornado\websocket.py", line 874, in wrapper
    yield fut
  File "c:\users\ppurwin\appdata\local\continuum\anaconda3\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\ppurwin\appdata\local\continuum\anaconda3\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\users\ppurwin\appdata\local\continuum\anaconda3\lib\site-packages\tornado\websocket.py", line 876, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
~~~~

List of versions:
~~~~
(base) C:\Users\ppurwin>pip list
Package                            Version
---------------------------------- --------
alabaster                          0.7.12
anaconda-client                    1.7.2
anaconda-navigator                 1.9.7
anaconda-project                   0.8.2
asn1crypto                         0.24.0
astroid                            2.2.5
astropy                            3.1.2
atomicwrites                       1.3.0
attrs                              19.1.0
Babel                              2.6.0
backcall                           0.1.0
backports.os                       0.1.1
backports.shutil-get-terminal-size 1.0.0
beautifulsoup4                     4.7.1
bitarray                           0.8.3
bkcharts                           0.2
bleach                             3.1.0
bokeh                              1.0.4
boto                               2.49.0
Bottleneck                         1.2.1
certifi                            2019.3.9
cffi                               1.12.2
chardet                            3.0.4
Click                              7.0
cloudpickle                        0.8.0
clyent                             1.2.2
colorama                           0.4.1
comtypes                           1.1.7
conda                              4.6.11
conda-build                        3.17.8
conda-verify                       3.1.1
contextlib2                        0.5.5
cryptography                       2.6.1
cycler                             0.10.0
Cython                             0.29.6
cytoolz                            0.9.0.1
dask                               1.1.4
decorator                          4.4.0
defusedxml                         0.5.0
distributed                        1.26.0
docutils                           0.14
entrypoints                        0.3
et-xmlfile                         1.0.1
fastcache                          1.0.2
filelock                           3.0.10
Flask                              1.0.2
future                             0.17.1
gevent                             1.4.0
glob2                              0.6
greenlet                           0.4.15
h5py                               2.9.0
heapdict                           1.0.0
html5lib                           1.0.1
idna                               2.8
imageio                            2.5.0
imagesize                          1.1.0
importlib-metadata                 0.0.0
ipykernel                          5.1.0
ipython                            7.4.0
ipython-genutils                   0.2.0
ipywidgets                         7.4.2
isort                              4.3.16
itsdangerous                       1.1.0
jdcal                              1.4
jedi                               0.13.3
Jinja2                             2.10
jsonschema                         3.0.1
jupyter                            1.0.0
jupyter-client                     5.2.4
jupyter-console                    6.0.0
jupyter-core                       4.4.0
jupyterlab                         0.35.4
jupyterlab-server                  0.2.0
keyring                            18.0.0
kiwisolver                         1.0.1
lazy-object-proxy                  1.3.1
libarchive-c                       2.8
llvmlite                           0.28.0
locket                             0.2.0
lxml                               4.3.2
MarkupSafe                         1.1.1
matplotlib                         3.0.3
mccabe                             0.6.1
menuinst                           1.4.16
mistune                            0.8.4
mkl-fft                            1.0.10
mkl-random                         1.0.2
more-itertools                     6.0.0
mpmath                             1.1.0
msgpack                            0.6.1
multipledispatch                   0.6.0
navigator-updater                  0.2.1
nbconvert                          5.4.1
nbformat                           4.4.0
networkx                           2.2
nltk                               3.4
nose                               1.3.7
notebook                           6.0.0rc1
numba                              0.43.1
numexpr                            2.6.9
numpy                              1.16.2
numpydoc                           0.8.0
olefile                            0.46
openpyxl                           2.6.1
packaging                          19.0
pandas                             0.24.2
pandocfilters                      1.4.2
parso                              0.3.4
partd                              0.3.10
path.py                            11.5.0
pathlib2                           2.3.3
patsy                              0.5.1
pep8                               1.7.1
pickleshare                        0.7.5
Pillow                             5.4.1
pip                                19.1.1
pkginfo                            1.5.0.1
pluggy                             0.9.0
ply                                3.11
prometheus-client                  0.6.0
prompt-toolkit                     2.0.9
psutil                             5.6.1
py                                 1.8.0
pycodestyle                        2.5.0
pycosat                            0.6.3
pycparser                          2.19
pycrypto                           2.6.1
pycurl                             7.43.0.2
pyflakes                           2.1.1
Pygments                           2.3.1
pylint                             2.3.1
pyodbc                             4.0.26
pyOpenSSL                          19.0.0
pyparsing                          2.3.1
pyreadline                         2.1
pyrsistent                         0.14.11
PySocks                            1.6.8
pytest                             4.3.1
pytest-arraydiff                   0.3
pytest-astropy                     0.5.0
pytest-doctestplus                 0.3.0
pytest-openfiles                   0.3.2
pytest-remotedata                  0.3.1
python-dateutil                    2.8.0
pytz                               2018.9
PyWavelets                         1.0.2
pywin32                            223
pywinpty                           0.5.5
PyYAML                             5.1
pyzmq                              18.0.0
QtAwesome                          0.5.7
qtconsole                          4.4.3
QtPy                               1.7.0
requests                           2.21.0
rope                               0.12.0
ruamel-yaml                        0.15.46
scikit-image                       0.14.2
scikit-learn                       0.20.3
scipy                              1.2.1
seaborn                            0.9.0
Send2Trash                         1.5.0
setuptools                         40.8.0
simplegeneric                      0.8.1
singledispatch                     3.4.0.3
six                                1.12.0
snowballstemmer                    1.2.1
sortedcollections                  1.1.2
sortedcontainers                   2.1.0
soupsieve                          1.8
Sphinx                             1.8.5
sphinxcontrib-websupport           1.1.0
spyder                             3.3.3
spyder-kernels                     0.4.2
SQLAlchemy                         1.3.1
statsmodels                        0.9.0
sympy                              1.3
tables                             3.5.1
tblib                              1.3.2
terminado                          0.8.1
testpath                           0.4.2
toolz                              0.9.0
tornado                            5.1.1
tqdm                               4.31.1
traitlets                          4.3.2
unicodecsv                         0.14.1
urllib3                            1.24.1
wcwidth                            0.1.7
webencodings                       0.5.1
Werkzeug                           0.14.1
wheel                              0.33.1
widgetsnbextension                 3.4.2
win-inet-pton                      1.1.0
win-unicode-console                0.5
wincertstore                       0.2
wrapt                              1.11.1
xlrd                               1.2.0
XlsxWriter                         1.1.5
xlwings                            0.15.4
xlwt                               1.3.0
zict                               0.1.4
zipp                               0.3.3
~~~~

**Comment by Pierek** [comment]
Tried the same on python 3.6.8 - no success. Is it possible that its linked with some network related stuff on my pc?

**Comment by Pierek** [comment]
I just tried running jupyter in docker :D

I ran
`docker run -p 8888:8888 jupyter/minimal-notebook`

And the same problem :D I wasn't recieving this WebSocketClosedError in the console but the behaivior of the notebook was the same - Connected label in the upper right corner is constatnly blinking as the engine is retrying.

How, how? In Docker? Pls halp

**Comment by Pierek** [comment]
Wow - I have just found, that when I changed the port on my pc to 8889 (`docker run -p 8889:8888 jupyter/minimal-notebook`) it started working. I will try later with normal python on my pc.

**Comment by Pierek** [comment]
Yes! It finally started working by `jupyter notebook --port=8889` (venv on python 3.7.3, with just installed jupyter and all of its dependencies including torando==6.0.3). It seems that I am having some problem with port 8888 on my local machine, will investigate this later.

**Comment by lresende** [comment]
Glad that it worked, feel free to reopen if you find out there is an actual software issue.
