### ISSUE TITLE
remote Notebook server occur kernel error

### ISSUE THREAD

**Issue by coldJune** [jupyter/notebook#4762]

**Comment by coldJune** [comment]
`Traceback (most recent call last):
  File "/usr/local/python3.6.9/lib/python3.6/site-packages/tornado-6.0.3-py3.6-linux-x86_64.egg/tornado/web.py", line 1699, in _execute
    result = await result
  File "/usr/local/python3.6.9/lib/python3.6/site-packages/tornado-6.0.3-py3.6-linux-x86_64.egg/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/usr/local/python3.6.9/lib/python3.6/site-packages/notebook/services/sessions/handlers.py", line 73, in post
    type=mtype))
  File "/usr/local/python3.6.9/lib/python3.6/site-packages/tornado-6.0.3-py3.6-linux-x86_64.egg/tornado/gen.py", line 735, in run
    value = future.result()
  File "/usr/local/python3.6.9/lib/python3.6/site-packages/tornado-6.0.3-py3.6-linux-x86_64.egg/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/usr/local/python3.6.9/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/usr/local/python3.6.9/lib/python3.6/site-packages/tornado-6.0.3-py3.6-linux-x86_64.egg/tornado/gen.py", line 735, in run
    value = future.result()
  File "/usr/local/python3.6.9/lib/python3.6/site-packages/tornado-6.0.3-py3.6-linux-x86_64.egg/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/usr/local/python3.6.9/lib/python3.6/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/usr/local/python3.6.9/lib/python3.6/site-packages/tornado-6.0.3-py3.6-linux-x86_64.egg/tornado/gen.py", line 735, in run
    value = future.result()
  File "/usr/local/python3.6.9/lib/python3.6/site-packages/tornado-6.0.3-py3.6-linux-x86_64.egg/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/usr/local/python3.6.9/lib/python3.6/site-packages/notebook/services/kernels/kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/usr/local/python3.6.9/lib/python3.6/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/usr/local/python3.6.9/lib/python3.6/site-packages/jupyter_client/manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "/usr/local/python3.6.9/lib/python3.6/site-packages/jupyter_client/connect.py", line 472, in write_connection_file
    kernel_name=self.kernel_name
  File "/usr/local/python3.6.9/lib/python3.6/site-packages/jupyter_client/connect.py", line 101, in write_connection_file
    sock.bind((ip, 0))
OSError: [Errno 99] Cannot assign requested address`
this is my config file 
`c.NotebookApp.ip = '0.0.0.0'`
