### ISSUE TITLE
Connection failed when opening downloaded code

### ISSUE THREAD

**Issue by RichardoTiono** [jupyter/notebook#4775]
Hello,
I have encountered error of opening a downloaded code [Interactive deep colorization](https://github.com/junyanz/interactive-deep-colorization) for deep learning program on Jupyter. It always stuck on 'starting kernel please wait' then after waiting I got 'connection failed' error then the notebook closed. I have already tried different downloadable code but the problem persist. But it never happen if I just create a new ipnyb by myself, I even able to run simple code on it. I am using ubuntu 18.04 and opening jupyter on firefox . These are the error that I got

> [E 12:18:15.154 NotebookApp] Could not open static file ''
[W 12:18:15.258 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (127.0.0.1) 50.27ms referer=http://localhost:8888/tree?token=892b25f22d08fdd71b7355d2ed6aef077213b2ab8f48ca0a
[W 12:18:15.279 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (127.0.0.1) 1.62ms referer=http://localhost:8888/tree?token=892b25f22d08fdd71b7355d2ed6aef077213b2ab8f48ca0a
[I 12:18:27.793 NotebookApp] Creating new notebook in 
[W 12:18:28.842 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (127.0.0.1) 1.73ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=python3
[W 12:18:28.910 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (127.0.0.1) 1.98ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=python3
[I 12:18:29.529 NotebookApp] Kernel started: 3c613b86-2bef-435d-981e-e17412d72b8e
[I 12:18:30.040 NotebookApp] Adapting from protocol version 5.1 (kernel 3c613b86-2bef-435d-981e-e17412d72b8e) to 5.3 (client).
[I 12:19:20.863 NotebookApp] Saving file at /Untitled.ipynb
[I 12:19:21.034 NotebookApp] Starting buffering for 3c613b86-2bef-435d-981e-e17412d72b8e:01f087a5249a4799a90a40e022248e80
[I 12:19:26.445 NotebookApp] Kernel shutdown: 3c613b86-2bef-435d-981e-e17412d72b8e
[W 12:19:26.448 NotebookApp] delete /Untitled.ipynb
[W 12:19:27.679 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (127.0.0.1) 1.29ms referer=http://localhost:8888/notebooks/DemoInteractiveColorization.ipynb
[W 12:19:27.717 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (127.0.0.1) 1.14ms referer=http://localhost:8888/notebooks/DemoInteractiveColorization.ipynb
[W 12:19:27.954 NotebookApp] Notebook DemoInteractiveColorization.ipynb is not trusted
[I 12:19:28.381 NotebookApp] Kernel started: 8b51e039-5b10-4687-8afb-2968e2aeb061
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/usr/lib/python3/dist-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/usr/lib/python3/dist-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/usr/lib/python3/dist-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/usr/lib/python3/dist-packages/IPython/core/ultratb.py", line 124, in <module>
    from IPython.utils import path as util_path
  File "/usr/lib/python3/dist-packages/IPython/utils/path.py", line 18, in <module>
    from IPython.utils.process import system
  File "/usr/lib/python3/dist-packages/IPython/utils/process.py", line 19, in <module>
    from ._process_posix import system, getoutput, arg_split, check_pid
  File "/usr/lib/python3/dist-packages/IPython/utils/_process_posix.py", line 24, in <module>
    import pexpect
  File "/usr/lib/python3/dist-packages/pexpect/__init__.py", line 75, in <module>
    from .pty_spawn import spawn, spawnu
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 14, in <module>
    from .spawnbase import SpawnBase
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 224
    def expect(self, pattern, timeout=-1, searchwindowsize=-1, async=False):
                                                                   ^
SyntaxError: invalid syntax
[I 12:19:31.381 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/usr/lib/python3/dist-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/usr/lib/python3/dist-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/usr/lib/python3/dist-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/usr/lib/python3/dist-packages/IPython/core/ultratb.py", line 124, in <module>
    from IPython.utils import path as util_path
  File "/usr/lib/python3/dist-packages/IPython/utils/path.py", line 18, in <module>
    from IPython.utils.process import system
  File "/usr/lib/python3/dist-packages/IPython/utils/process.py", line 19, in <module>
    from ._process_posix import system, getoutput, arg_split, check_pid
  File "/usr/lib/python3/dist-packages/IPython/utils/_process_posix.py", line 24, in <module>
    import pexpect
  File "/usr/lib/python3/dist-packages/pexpect/__init__.py", line 75, in <module>
    from .pty_spawn import spawn, spawnu
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 14, in <module>
    from .spawnbase import SpawnBase
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 224
    def expect(self, pattern, timeout=-1, searchwindowsize=-1, async=False):
                                                                   ^
SyntaxError: invalid syntax
[I 12:19:34.392 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/usr/lib/python3/dist-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/usr/lib/python3/dist-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/usr/lib/python3/dist-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/usr/lib/python3/dist-packages/IPython/core/ultratb.py", line 124, in <module>
    from IPython.utils import path as util_path
  File "/usr/lib/python3/dist-packages/IPython/utils/path.py", line 18, in <module>
    from IPython.utils.process import system
  File "/usr/lib/python3/dist-packages/IPython/utils/process.py", line 19, in <module>
    from ._process_posix import system, getoutput, arg_split, check_pid
  File "/usr/lib/python3/dist-packages/IPython/utils/_process_posix.py", line 24, in <module>
    import pexpect
  File "/usr/lib/python3/dist-packages/pexpect/__init__.py", line 75, in <module>
    from .pty_spawn import spawn, spawnu
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 14, in <module>
    from .spawnbase import SpawnBase
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 224
    def expect(self, pattern, timeout=-1, searchwindowsize=-1, async=False):
                                                                   ^
SyntaxError: invalid syntax
[I 12:19:37.403 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/usr/lib/python3/dist-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/usr/lib/python3/dist-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/usr/lib/python3/dist-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/usr/lib/python3/dist-packages/IPython/core/ultratb.py", line 124, in <module>
    from IPython.utils import path as util_path
  File "/usr/lib/python3/dist-packages/IPython/utils/path.py", line 18, in <module>
    from IPython.utils.process import system
  File "/usr/lib/python3/dist-packages/IPython/utils/process.py", line 19, in <module>
    from ._process_posix import system, getoutput, arg_split, check_pid
  File "/usr/lib/python3/dist-packages/IPython/utils/_process_posix.py", line 24, in <module>
    import pexpect
  File "/usr/lib/python3/dist-packages/pexpect/__init__.py", line 75, in <module>
    from .pty_spawn import spawn, spawnu
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 14, in <module>
    from .spawnbase import SpawnBase
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 224
    def expect(self, pattern, timeout=-1, searchwindowsize=-1, async=False):
                                                                   ^
SyntaxError: invalid syntax
[I 12:19:40.414 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/usr/local/lib/python3.7/dist-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/usr/lib/python3/dist-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/usr/lib/python3/dist-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/usr/lib/python3/dist-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/usr/lib/python3/dist-packages/IPython/core/ultratb.py", line 124, in <module>
    from IPython.utils import path as util_path
  File "/usr/lib/python3/dist-packages/IPython/utils/path.py", line 18, in <module>
    from IPython.utils.process import system
  File "/usr/lib/python3/dist-packages/IPython/utils/process.py", line 19, in <module>
    from ._process_posix import system, getoutput, arg_split, check_pid
  File "/usr/lib/python3/dist-packages/IPython/utils/_process_posix.py", line 24, in <module>
    import pexpect
  File "/usr/lib/python3/dist-packages/pexpect/__init__.py", line 75, in <module>
    from .pty_spawn import spawn, spawnu
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 14, in <module>
    from .spawnbase import SpawnBase
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 224
    def expect(self, pattern, timeout=-1, searchwindowsize=-1, async=False):
                                                                   ^
SyntaxError: invalid syntax
[W 12:19:43.423 NotebookApp] KernelRestarter: restart failed
[W 12:19:43.424 NotebookApp] Kernel 8b51e039-5b10-4687-8afb-2968e2aeb061 died, removing from map.
[W 12:19:49.427 NotebookApp] Replacing stale connection: 8b51e039-5b10-4687-8afb-2968e2aeb061:d13818a2c1bd44578d52b344ffc86fa1
[W 12:20:11.459 NotebookApp] Replacing stale connection: 8b51e039-5b10-4687-8afb-2968e2aeb061:d13818a2c1bd44578d52b344ffc86fa1
[W 12:20:28.520 NotebookApp] Timeout waiting for kernel_info reply from 8b51e039-5b10-4687-8afb-2968e2aeb061
[E 12:20:28.522 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 8b51e039-5b10-4687-8afb-2968e2aeb061)
[W 12:20:28.524 NotebookApp] 404 GET /api/kernels/8b51e039-5b10-4687-8afb-2968e2aeb061/channels?session_id=d13818a2c1bd44578d52b344ffc86fa1 (127.0.0.1): Kernel does not exist: 8b51e039-5b10-4687-8afb-2968e2aeb061
[W 12:20:28.526 NotebookApp] 404 GET /api/kernels/8b51e039-5b10-4687-8afb-2968e2aeb061/channels?session_id=d13818a2c1bd44578d52b344ffc86fa1 (127.0.0.1) 39102.96ms referer=None
[W 12:20:28.526 NotebookApp] 404 GET /api/kernels/8b51e039-5b10-4687-8afb-2968e2aeb061/channels?session_id=d13818a2c1bd44578d52b344ffc86fa1 (127.0.0.1): Kernel does not exist: 8b51e039-5b10-4687-8afb-2968e2aeb061
[W 12:20:28.528 NotebookApp] 404 GET /api/kernels/8b51e039-5b10-4687-8afb-2968e2aeb061/channels?session_id=d13818a2c1bd44578d52b344ffc86fa1 (127.0.0.1) 17071.98ms referer=None

Please help me

**Comment by uililo** [comment]
Experiencing the same issue here

**Comment by Benfeitas** [comment]
This may solve your problem: https://github.com/jupyter/notebook/pull/4772#issuecomment-515794823
