### ISSUE TITLE
Kernel added with ipykernal cannot start due to ImportError: DLL load failed

### ISSUE THREAD

**Issue by djjacqmin** [jupyter/notebook#4784]
- System: Windows 10
- Package Manager: Miniconda3

When I run jupyter notebook, I can create a new notebook and load the base kernel ("Python 3") without any issues. I have another kernel that I installed using ipykernal for another conda environment. When I attempt to load this kernel in jupyter notebook, I get the following error.

I have looked through previous issues. It seems sometimes users have an issue with 'ImportError: DLL load failed' errors, though not with the same package and not with my specific situation (the base environment kernel loads, but not the additional environment installed via ipykernal).

```
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\qa-roils-env\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Miniconda3\envs\qa-roils-env\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\envs\qa-roils-env\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\ProgramData\Miniconda3\envs\qa-roils-env\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\ProgramData\Miniconda3\envs\qa-roils-env\lib\site-packages\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "C:\ProgramData\Miniconda3\envs\qa-roils-env\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\ProgramData\Miniconda3\envs\qa-roils-env\lib\site-packages\jupyter_client\connect.py", line 23, in <module>
    import zmq
  File "C:\ProgramData\Miniconda3\envs\qa-roils-env\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\ProgramData\Miniconda3\envs\qa-roils-env\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\ProgramData\Miniconda3\envs\qa-roils-env\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\ProgramData\Miniconda3\envs\qa-roils-env\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\ProgramData\Miniconda3\envs\qa-roils-env\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\ProgramData\Miniconda3\envs\qa-roils-env\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by bburan** [comment]
I am also experiencing the same issue using a fresh install of Miniconda3 on Windows 7. I installed Miniconda 3 for all users then created a user-specific kernel named `psi-dev-1` and installed it using `python -m ipykernel install --user --name psi-dev-1`. The kernel loads fine, and I can run basic Python statements. However, when I attempt `import numpy`, I get the following traceback:
```

ImportError                               Traceback (most recent call last)
<ipython-input-1-d4cdadb62aa7> in <module>
----> 1 import numpy

~\.conda\envs\psi-dev-1\lib\site-packages\numpy\__init__.py in <module>
    138 
    139     # Allow distributors to run custom init code
--> 140     from . import _distributor_init
    141 
    142     from . import core

~\.conda\envs\psi-dev-1\lib\site-packages\numpy\_distributor_init.py in <module>
     32 
     33 with RTLD_for_MKL():
---> 34     from . import _mklinit
     35 
     36 del RTLD_for_MKL

ImportError: DLL load failed: The specified module could not be found.
```

Note in the paths above, it's using the `psi-dev-1` environment for Numpy. However, when I install numpy into the base conda environment,  it starts working. When I do:

````
import numpy
print(numpy.__file__)
```
I get `'C:\\Users\\bburan\\.conda\\envs\\psi-dev-1\\lib\\site-packages\\numpy\\__init__.py'`.

So, there's something very bizarre about the Windows path issues.

**Comment by parkerwill** [comment]
I have the exact same issue as @djjacqmin .  The base conda environment has the following versions of jupyter specific packages installed:

```
ipykernel                 5.1.0            py36h39e3cac_0
ipython                   7.2.0            py36h39e3cac_0
ipython_genutils          0.2.0            py36h3c5d0ee_0
ipywidgets                7.4.2                    py36_0

jupyter                   1.0.0                    py36_7
jupyter_client            5.2.4                    py36_0
jupyter_console           6.0.0                    py36_0
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1                    py36_0    conda-forge
jupyter_core              4.4.0                    py36_0
jupyter_highlight_selected_word 0.2.0                 py36_1000    conda-forge
jupyter_latex_envs        1.4.4                 py36_1000    conda-forge
jupyter_nbextensions_configurator 0.4.1                    py36_0    conda-forge
jupyterlab                0.35.3                   py36_0
jupyterlab_server         0.2.0                    py36_
```

I then installed a kernel into this environment that points to another conda environment located in the envs directory of the base conda environment which has a different version of python3 and some slightly different package numbers

`ipykernel                 5.1.2            py36h39e3cac_0
ipython                   7.8.0            py36h39e3cac_0
ipython_genutils          0.2.0            py36h3c5d0ee_0
ipywidgets                7.5.1                      py_0

jupyter                   1.0.0                    py36_7
jupyter_client            5.3.1                      py_0
jupyter_console           6.0.0                    py36_0
jupyter_core              4.5.0                      py_0
jupyterlab                1.0.2            py36hf63ae98_0
jupyterlab_server         1.0.0                      py_1`

When I launch jupyter notebook and select the newly installed kernel I get the same error message as @djjacqmin .

**Comment by parkerwill** [comment]
I discovered that when the environment being created in the base conda directory have a version of zeromq that is higher than that of the base environment I got this error.  By updating the version of zeromq in the base conda environment (could also downgrade the one in the virtual environment) that the error didn't occur anymore.

**Comment by obbe79** [comment]
> I discovered that when the environment being created in the base conda directory have a version of zeromq that is higher than that of the base environment I got this error. By updating the version of zeromq in the base conda environment (could also downgrade the one in the virtual environment) that the error didn't occur anymore.

Thank you so much for this info. I had the same problem. Unfortunately my base environment needs administrator privileges to be updated therefore I had to downgrade zeromq in my current env.
