### ISSUE TITLE
Kernel Error: No mapping between account names and security IDs was done

### ISSUE THREAD

**Issue by slivka83** [jupyter/notebook#4890]
Today updated the jupyter notebook to the latest version (6.0.1). And now when I try to open any notebook I get an Kernel Error:
> Traceback (most recent call last):
  File "c:\python\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "c:\python\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "c:\python\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\python\lib\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "c:\python\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "c:\python\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\python\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "c:\python\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "c:\python\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\python\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "c:\python\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "c:\python\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "c:\python\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "c:\python\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "c:\python\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "c:\python\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
    kernel_name=self.kernel_name
  File "c:\python\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "c:\python\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "c:\python\lib\site-packages\jupyter_client\connect.py", line 100, in secure_write
    win32_restrict_file_to_user(fname)
  File "c:\python\lib\site-packages\jupyter_client\connect.py", line 58, in win32_restrict_file_to_user
    admins, _domain, _type = win32security.LookupAccountName("", "Administrators")
pywintypes.error: (1332, 'LookupAccountName', 'No Mapping Between Account Names and Security ID was Done.')

System Win10 x64.

Any ideas?

**Comment by slivka83** [comment]
I downgrade jupyter-client to version 5.3.1 and it worked.

**Comment by Seviks** [comment]
Same problem here. Also when I try new installation with pip. Win10 x64

**Comment by gerMarco2022** [comment]
Same problem here (win10 x64), downgrading the jupyter-client to the 5.3.1 version works like a charm!

**Comment by kevin-bates** [comment]
Yes - downgrading jupyter_client is the correct action at this time.  Here's the PR you want to track into a patch release: https://github.com/jupyter/jupyter_client/pull/478

**Comment by LuizFTelles** [comment]
Same problem here, in a recent-formatted PC with pip (Win10 x64). Downgrading jupyter-client to  5.3.1 also worked for me!

**Comment by MSeal** [comment]
jupyter_client 5.3.3 should have the fix for the issue now, though there was a reported problem with jupyerlab's python terminal after the change.
