### ISSUE TITLE
500: Internal Server Error While Running Jupyter

### ISSUE THREAD

**Issue by djgray101** [jupyter/notebook#4919]
I was working in a Notebook when suddenly everything just froze and my computer up froze and locked up, so I had to do a force restart. I restarted it and tried to run jupyter from the command terminal and received the dreaded 500: Internal Server Error. I am a little concerned about deleting Jupyter and reinstalling because I don't know if the notebooks that I have worked on so far will be completely deleted. So far I have tried the following solutions from previous threads without success: 

1. I tried doing _pip install --upgrade jupyter_
2. _pip install nbconvert==5.4.1_ This didn't work, so I went back to the latest version

I have posted the full terminal error below, but I don't really understand what it all means. If anybody could provide some insight that would be appreciated. 
`[E 17:50:52.602 NotebookApp] Uncaught exception GET /notebooks/Python_Documentation_Practice.ipynb (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/notebooks/Python_Documentation_Practice.ipynb', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "c:\users\djgra\appdata\local\programs\python\python36\lib\site-packages\tornado\web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "c:\users\djgra\appdata\local\programs\python\python36\lib\site-packages\tornado\web.py", line 3174, in wrapper
        return method(self, *args, **kwargs)
      File "c:\users\djgra\appdata\local\programs\python\python36\lib\site-packages\notebook\notebook\handlers.py", line 59, in get
        get_custom_frontend_exporters=get_custom_frontend_exporters
      File "c:\users\djgra\appdata\local\programs\python\python36\lib\site-packages\notebook\base\handlers.py", line 519, in render_template
        return template.render(**ns)
      File "c:\users\djgra\appdata\local\programs\python\python36\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
        return original_render(self, *args, **kwargs)
      File "c:\users\djgra\appdata\local\programs\python\python36\lib\site-packages\jinja2\environment.py", line 1008, in render
        return self.environment.handle_exception(exc_info, True)
      File "c:\users\djgra\appdata\local\programs\python\python36\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "c:\users\djgra\appdata\local\programs\python\python36\lib\site-packages\jinja2\_compat.py", line 37, in reraise
        raise value.with_traceback(tb)
      File "c:\users\djgra\appdata\local\programs\python\python36\lib\site-packages\notebook\templates\notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "c:\users\djgra\appdata\local\programs\python\python36\lib\site-packages\notebook\templates\page.html", line 154, in top-level template code
        {% block header %}
      File "c:\users\djgra\appdata\local\programs\python\python36\lib\site-packages\notebook\templates\notebook.html", line 120, in block "header"
        {% for exporter in get_custom_frontend_exporters() %}
      File "c:\users\djgra\appdata\local\programs\python\python36\lib\site-packages\notebook\notebook\handlers.py", line 24, in get_custom_frontend_exporters
        exporter = get_exporter(name)()
      File "c:\users\djgra\appdata\local\programs\python\python36\lib\site-packages\jupyter_contrib_nbextensions\nbconvert_support\collapsible_headings.py", line 44, in __init__
        collapsible_headings_options = cm.get('notebook').get(
      File "c:\users\djgra\appdata\local\programs\python\python36\lib\site-packages\notebook\services\config\manager.py", line 25, in get
        recursive_update(config, cm.get(section_name))
      File "c:\users\djgra\appdata\local\programs\python\python36\lib\site-packages\notebook\config_manager.py", line 103, in get
        recursive_update(data, json.load(f))
      File "c:\users\djgra\appdata\local\programs\python\python36\lib\json\__init__.py", line 299, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
      File "c:\users\djgra\appdata\local\programs\python\python36\lib\json\__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "c:\users\djgra\appdata\local\programs\python\python36\lib\json\decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "c:\users\djgra\appdata\local\programs\python\python36\lib\json\decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[E 17:50:52.615 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36",
      "Sec-Fetch-Mode": "navigate",
      "Sec-Fetch-User": "?1",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3",
      "Sec-Fetch-Site": "same-origin",
      "Referer": "http://localhost:8888/tree",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|3040379f|29e086d1b5cbe5e15aaaa82dc47af12c|1568731610; username-localhost-8888=\"2|1:0|10:1569714647|23:username-localhost-8888|44:NzYwNGFhMjhkYzgxNDk2NWIxMjg0NzQ5Yzg0ZGRiYmI=|998007b1221d8e947441410220259827337cd5c4fb6946658eee020e4d19da99\""
    }
[E 17:50:52.616 NotebookApp] 500 GET /notebooks/Python_Documentation_Practice.ipynb (::1) 246.87ms referer=http://localhost:8888/tree`

**Comment by djgray101** [comment]
Solution:  From my research, it appears that the _notebook.json_ file somehow had its contents wiped out. When I opened the file I noticed a ton of 0's and replaced them with the following code I got a fix and so far things are okay!

```
{
  "load_extensions": {
    "jupyter-notebook-gist/extension": true,
    "jupyter-js-widgets/extension": true,
    "nbextensions_configurator/config_menu/main": true,
    "contrib_nbextensions_help_item/main": true,
    "equation-numbering/main": true
  }
}
```

**Comment by hemansah** [comment]
Never happened this to me but what happens to me is sometimes jupyter doesn't read its own files and sometimes when I try to open a jupyter notebook from anaconda navigator, It just won't start until I give a restart to my computer.
