### ISSUE TITLE
Kernel is not starting in spyder and jupyter as well

### ISSUE THREAD

**Issue by Dhanesh37** [jupyter/notebook#4932]
Traceback (most recent call last):
File "C:\Users\dhanesh\Anaconda3\lib\site‑packages\spyder\plugins\ipythonconsole.py", line 1554, in create_kernel_manager_and_kernel_client
kernel_manager.start_kernel(stderr=stderr_handle)
File "C:\Users\dhanesh\Anaconda3\lib\site‑packages\jupyter_client\manager.py", line 240, in start_kernel
self.write_connection_file()
File "C:\Users\dhanesh\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 547, in write_connection_file
kernel_name=self.kernel_name
File "C:\Users\dhanesh\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 212, in write_connection_file
with secure_write(fname) as f:
File "C:\Users\dhanesh\Anaconda3\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\Users\dhanesh\Anaconda3\lib\site‑packages\jupyter_client\connect.py", line 102, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\dhanesh\\AppData\\Roaming\\jupyter\\runtime\\kernel�f2e5e375a.json'

**Comment by kevin-bates** [comment]
Hi @Dhanesh37 - this is a duplicate of #4907.  We're hoping to get updated jupyter_core and jupyter_client releases out to address this as soon as possible.  In the meantime, you can follow the work around instructions that @snapo left at the bottom of #4097 or downgrade jupyter_client to 5.3.1.  Sorry for the inconvenience.

cc: @MSeal

**Comment by Dhanesh37** [comment]
Thanks @kevin-bates and @snapo this works fine.
just sharing my observation. I don't know what causes the issue, but in my scenario i am able to use jupyter and spyder perfectly fine untill i create an virtual environment in anaconda for lower python version

**Comment by kevin-bates** [comment]
@Dhanesh37 - could it be the case that when you created the virtual environment, some updated versions of libraries were installed?  There has been some recent churn in this area.  Please try to compare the two environments (working, failing) and pay close attention to the versions of `jupyter_client` and `pywin32` in particular.  I suspect the originally working environment is using `jupyter_client <= 5.3.1` while the problematic env has `jupyter_client == 5.3.3`.

Should we find both envs are using `jupyter_client == 5.3.3` and the only difference is the python version, then that may be a good hint in what has become a "perfect storm" of library updates. :smile:
