### ISSUE TITLE
FileNotFoundError: The command was not found or was not executable: /bin/bash_il.

### ISSUE THREAD

**Issue by why-not** [jupyter/notebook#4934]
I am getting this error when I try to open a terminal in my notebook from a remote web browser. I have set up with a signed certificate, key and a password. I have opened the correct ports. I am able to see the notebook without any issues, and I can run python commands which works without issue. Once I try to start a terminal on my notebook, nothing happens and I get this error on my server. Please help! 

```
[E 21:29:38.909 NotebookApp] Uncaught exception POST /api/terminals (73.252.199.170)
    HTTPServerRequest(protocol='https', host='223.225.169.125:8888', method='POST', uri='/api/terminals', version='HTTP/1.1', remote_ip='223.225.169.125')
    Traceback (most recent call last):
      File "/data/anaconda/envs/py35/lib/python3.5/site-packages/tornado/web.py", line 1541, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/data/anaconda/envs/py35/lib/python3.5/site-packages/tornado/web.py", line 2949, in wrapper
        return method(self, *args, **kwargs)
      File "/data/anaconda/envs/py35/lib/python3.5/site-packages/notebook/terminal/api_handlers.py", line 22, in post
        name, _ = self.terminal_manager.new_named_terminal()
      File "/data/anaconda/envs/py35/lib/python3.5/site-packages/terminado/management.py", line 319, in new_named_terminal
        term = self.new_terminal()
      File "/data/anaconda/envs/py35/lib/python3.5/site-packages/terminado/management.py", line 171, in new_terminal
        pty = PtyProcessUnicode.spawn(argv, env=env, cwd=options.get('cwd', None))
      File "/data/anaconda/envs/py35/lib/python3.5/site-packages/ptyprocess/ptyprocess.py", line 208, in spawn
        'executable: %s.' % command)
    FileNotFoundError: The command was not found or was not executable: /bin/bash_il.
[W 21:29:38.910 NotebookApp] Unhandled error
```

**Comment by why-not** [comment]
Turned out to be a relatively simple fix, I was hung up on the file not fond, but didn't pay attention to the "or was not executable" part. Infact that was the problem. 
```
chmod +x /bin/bash_il 
```
fixed the issue.
