### ISSUE TITLE
cannot import pandas/numpy/matplotlib

### ISSUE THREAD

**Issue by skizlin** [jupyter/notebook#4975]
Getting this when i execute import pandas as pd in jupyter notebook

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-7dd3504c366f> in <module>
----> 1 import pandas as pd

~\AppData\Roaming\Python\Python37\site-packages\pandas\__init__.py in <module>
      9 for dependency in hard_dependencies:
     10     try:
---> 11         __import__(dependency)
     12     except ImportError as e:
     13         missing_dependencies.append("{0}: {1}".format(dependency, str(e)))

~\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py in <module>
    138 
    139     # Allow distributors to run custom init code
--> 140     from . import _distributor_init
    141 
    142     from . import core

~\AppData\Roaming\Python\Python37\site-packages\numpy\_distributor_init.py in <module>
     24                 # NOTE: would it change behavior to load ALL
     25                 # DLLs at this path vs. the name restriction?
---> 26                 WinDLL(os.path.abspath(filename))
     27                 DLL_filenames.append(filename)
     28     if len(DLL_filenames) > 1:

~\Anaconda3\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: [WinError 193] %1 is not a valid Win32 application
```
when i do same on spyder i get following

```
`Traceback (most recent call last):

  File "<ipython-input-2-7dd3504c366f>", line 1, in <module>
    import pandas as pd

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\pandas\__init__.py", line 11, in <module>
    __import__(dependency)

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init

  File "C:\Users\user\AppData\Roaming\Python\Python37\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))

  File "C:\Users\user\Anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)

OSError: [WinError 193] %1 is not a valid Win32 application`
```

Please assist to sort this. I'm just new in all this. Everything was working perfectly until i didn't install and try other python IDE apps and as noob it seems that some of them now f*cked up anaconda. I have tried to uninstall Anaconda, and then also tried to install new version but problem is still here.

OS is Win10

**Comment by skizlin** [comment]
Sorted. What happen is that when I was installing and trying other IDEs i probably installed one which is 32bit version and then all IDEs start using 32bit version of python. So i deleted everything what i found in AppData and ProgramData directories associated with python and reinstall Anaconda
