### ISSUE TITLE
Jupyter lab launch errors

### ISSUE THREAD

**Issue by reaCodes** [jupyter/notebook#4986]
`pip list`: 
```
astroid            2.3.1
attrs              19.3.0
backcall           0.1.0     
bleach             3.1.0     
certifi            2019.9.11 
chardet            3.0.4
colorama           0.4.1
decorator          4.4.0
defusedxml         0.6.0
entrypoints        0.3
idna               2.8
importlib-metadata 0.23
ipykernel          5.1.2
ipython            7.8.0     
ipython-genutils   0.2.0     
isort              4.3.21
jedi               0.15.1    
Jinja2             2.10.3
json5              0.8.5
jsonschema         3.1.1
jupyter-client     5.3.4
jupyter-core       4.6.0
jupyterlab         1.1.4
jupyterlab-server  1.0.6     
lazy-object-proxy  1.4.2     
lxml               4.4.1
MarkupSafe         1.1.1
mccabe             0.6.1
mistune            0.8.4     
more-itertools     7.2.0
MouseInfo          0.1.2
nbconvert          5.6.0     
nbformat           4.4.0
notebook           6.0.1     
numpy              1.17.3+mkl
pandas             0.25.1    
pandocfilters      1.4.2
parso              0.5.1
pickleshare        0.7.5
pip                19.3
prometheus-client  0.7.1
prompt-toolkit     2.0.10
PyAutoGUI          0.9.48
PyGetWindow        0.0.7
Pygments           2.4.2
pylint             2.4.2     
PyMsgBox           1.0.7
pyperclip          1.7.0
PyRect             0.1.4
pyrsistent         0.15.4
PyScreeze          0.1.24
python-dateutil    2.8.0
PyTweening         1.0.3
pytz               2019.3
pywin32            225
pywinpty           0.5.5     
pyzmq              18.1.0
requests           2.22.0
retrying           1.3.3
Send2Trash         1.5.0
setuptools         41.4.0
six                1.12.0
tabulate           0.8.5
terminado          0.8.2
testpath           0.4.2
tornado            6.0.3
traitlets          4.3.3
urllib3            1.25.6
wcwidth            0.1.7
webencodings       0.5.1
wrapt              1.11.2
yapf               0.28.0
zipp               0.6.0
```
--------
`python -v`: 
```
import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'nt' # <class '_frozen_importlib.BuiltinImporter'>
import _thread # previously loaded ('_thread')
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import _weakref # previously loaded ('_weakref')
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import 'winreg' # <class '_frozen_importlib.BuiltinImporter'>
# installing zipimport hook
import 'time' # <class '_frozen_importlib.BuiltinImporter'>
import 'zipimport' # <class '_frozen_importlib.FrozenImporter'>
# installed zipimport hook
# C:\Program Files\Python\lib\encodings\__pycache__\__init__.cpython-38.pyc matches C:\Program Files\Python\lib\encodings\__init__.py
# code object from 'C:\\Program Files\\Python\\lib\\encodings\\__pycache__\\__init__.cpython-38.pyc'
# C:\Program Files\Python\lib\__pycache__\codecs.cpython-38.pyc matches C:\Program Files\Python\lib\codecs.py
# code object from 'C:\\Program Files\\Python\\lib\\__pycache__\\codecs.cpython-38.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <_frozen_importlib_external.SourceFileLoader object at 0x000001ACA0C20A00>
# C:\Program Files\Python\lib\encodings\__pycache__\aliases.cpython-38.pyc matches C:\Program Files\Python\lib\encodings\aliases.py
# code object from 'C:\\Program Files\\Python\\lib\\encodings\\__pycache__\\aliases.cpython-38.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0x000001ACA0CEEFD0>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0x000001ACA0C207F0>
# C:\Program Files\Python\lib\encodings\__pycache__\utf_8.cpython-38.pyc matches C:\Program Files\Python\lib\encodings\utf_8.py
# code object from 'C:\\Program Files\\Python\\lib\\encodings\\__pycache__\\utf_8.cpython-38.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0x000001ACA0C20880>
# C:\Program Files\Python\lib\encodings\__pycache__\gbk.cpython-38.pyc matches C:\Program Files\Python\lib\encodings\gbk.py
# code object from 'C:\\Program Files\\Python\\lib\\encodings\\__pycache__\\gbk.cpython-38.pyc'
import '_codecs_cn' # <class '_frozen_importlib.BuiltinImporter'>
import '_multibytecodec' # <class '_frozen_importlib.BuiltinImporter'>
import 'encodings.gbk' # <_frozen_importlib_external.SourceFileLoader object at 0x000001ACA0D07100>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Program Files\Python\lib\encodings\__pycache__\latin_1.cpython-38.pyc matches C:\Program Files\Python\lib\encodings\latin_1.py
# code object from 'C:\\Program Files\\Python\\lib\\encodings\\__pycache__\\latin_1.cpython-38.pyc'
import 'encodings.latin_1' # <_frozen_importlib_external.SourceFileLoader object at 0x000001ACA0D071C0>
# C:\Program Files\Python\lib\__pycache__\io.cpython-38.pyc matches C:\Program Files\Python\lib\io.py
# code object from 'C:\\Program Files\\Python\\lib\\__pycache__\\io.cpython-38.pyc'
# C:\Program Files\Python\lib\__pycache__\abc.cpython-38.pyc matches C:\Program Files\Python\lib\abc.py
# code object from 'C:\\Program Files\\Python\\lib\\__pycache__\\abc.cpython-38.pyc'
import '_abc' # <class '_frozen_importlib.BuiltinImporter'>
import 'abc' # <_frozen_importlib_external.SourceFileLoader object at 0x000001ACA0D07820>
import 'io' # <_frozen_importlib_external.SourceFileLoader object at 0x000001ACA0D07550>
# C:\Program Files\Python\lib\__pycache__\site.cpython-38.pyc matches C:\Program Files\Python\lib\site.py
# code object from 'C:\\Program Files\\Python\\lib\\__pycache__\\site.cpython-38.pyc'
# C:\Program Files\Python\lib\__pycache__\os.cpython-38.pyc matches C:\Program Files\Python\lib\os.py
# code object from 'C:\\Program Files\\Python\\lib\\__pycache__\\os.cpython-38.pyc'
# C:\Program Files\Python\lib\__pycache__\stat.cpython-38.pyc matches C:\Program Files\Python\lib\stat.py
# code object from 'C:\\Program Files\\Python\\lib\\__pycache__\\stat.cpython-38.pyc'
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <_frozen_importlib_external.SourceFileLoader object at 0x000001ACA0D2F1F0>
# C:\Program Files\Python\lib\__pycache__\ntpath.cpython-38.pyc matches C:\Program Files\Python\lib\ntpath.py      
# code object from 'C:\\Program Files\\Python\\lib\\__pycache__\\ntpath.cpython-38.pyc'
# C:\Program Files\Python\lib\__pycache__\genericpath.cpython-38.pyc matches C:\Program Files\Python\lib\genericpath.py
# code object from 'C:\\Program Files\\Python\\lib\\__pycache__\\genericpath.cpython-38.pyc'
import 'genericpath' # <_frozen_importlib_external.SourceFileLoader object at 0x000001ACA0D2FF40>
import 'ntpath' # <_frozen_importlib_external.SourceFileLoader object at 0x000001ACA0D2F280>
# C:\Program Files\Python\lib\__pycache__\_collections_abc.cpython-38.pyc matches C:\Program Files\Python\lib\_collections_abc.py
# code object from 'C:\\Program Files\\Python\\lib\\__pycache__\\_collections_abc.cpython-38.pyc'
import '_collections_abc' # <_frozen_importlib_external.SourceFileLoader object at 0x000001ACA0D2FD90>
import 'os' # <_frozen_importlib_external.SourceFileLoader object at 0x000001ACA0D138E0>
# C:\Program Files\Python\lib\__pycache__\_sitebuiltins.cpython-38.pyc matches C:\Program Files\Python\lib\_sitebuiltins.py
# code object from 'C:\\Program Files\\Python\\lib\\__pycache__\\_sitebuiltins.cpython-38.pyc'
import '_sitebuiltins' # <_frozen_importlib_external.SourceFileLoader object at 0x000001ACA0D26430>
# C:\Program Files\Python\lib\__pycache__\_bootlocale.cpython-38.pyc matches C:\Program Files\Python\lib\_bootlocale.py
# code object from 'C:\\Program Files\\Python\\lib\\__pycache__\\_bootlocale.cpython-38.pyc'
import '_locale' # <class '_frozen_importlib.BuiltinImporter'>
import '_bootlocale' # <_frozen_importlib_external.SourceFileLoader object at 0x000001ACA0D41AC0>
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x000001ACA0D131F0>
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>
```
--------
Environment: 
Windows 10
Python 3.8.0

----------
When I try to launch Jupyter lab I get the folowing errors: 
```
PS C:\Users\zhong\Documents\VS Code\Code> jupyter-lab.exe
Traceback (most recent call last):
  File "c:\program files\python\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python\Scripts\jupyter-lab.exe\__main__.py", line 7, in <module>
  File "c:\program files\python\lib\site-packages\jupyter_core\application.py", line 268, in launch_instance       
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\program files\python\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance   
    app.initialize(argv)
  File "<c:\program files\python\lib\site-packages\decorator.py:decorator-gen-7>", line 2, in initialize
  File "c:\program files\python\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error 
    return method(app, *args, **kwargs)
  File "c:\program files\python\lib\site-packages\notebook\notebookapp.py", line 1679, in initialize
    self.init_webapp()
  File "c:\program files\python\lib\site-packages\jupyterlab\labapp.py", line 400, in init_webapp
    super().init_webapp(*args, **kwargs)
  File "c:\program files\python\lib\site-packages\notebook\notebookapp.py", line 1442, in init_webapp
    self.http_server.listen(port, self.ip)
  File "c:\program files\python\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "c:\program files\python\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "c:\program files\python\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "c:\program files\python\lib\site-packages\tornado\platform\asyncio.py", line 99, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "c:\program files\python\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
```
---------
Is there anyone who can help me with this problem?

**Comment by kevin-bates** [comment]
Looks like its related to tornado and python 3.8: https://stackoverflow.com/questions/58422817/jupyter-notebook-with-python-3-8

**Comment by reaCodes** [comment]
@kevin-bates Thanks! The method you gave can solve the problem. I expect an official fix for this soon, however.

**Comment by OussemaZaier** [comment]
i have the same problem and i tried to fix without any result 
i tried this also : 
https://stackoverflow.com/questions/58422817/jupyter-notebook-with-python-3-8-notimplementederror

**Comment by kevin-bates** [comment]
@OussemaZaier I suspect the ProactorEventLoop is still in play for you.  You might try building with @minrk's branch referenced in https://github.com/jupyter/notebook/pull/5047 since it matters _where_ the SelectorEventLoop gets established.
