### ISSUE TITLE
Error running stata-kernel in Atom

### ISSUE THREAD

**Issue by rinalynne** [jupyter/notebook#5008]
Hi all. I'm attempting to run Stata in Atom using stata-kernel. It worked after the initial install, but now on my second use I'm receiving this error every time I attempt to run code. 

`[IPKernelApp] ERROR | Exception in message handler: Traceback (most recent call last): File "C:\Users\asus\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell yield gen.maybe_future(handler(stream, idents, msg)) File "C:\Users\asus\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tornado\gen.py", line 735, in run value = future.result() File "C:\Users\asus\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tornado\gen.py", line 209, in wrapper yielded = next(result) File "C:\Users\asus\AppData\Local\Programs\Python\Python37-32\lib\site-packages\ipykernel\kernelbase.py", line 541, in execute_request user_expressions, allow_stdin, File "C:\Users\asus\AppData\Local\Programs\Python\Python37-32\lib\site-packages\stata_kernel\kernel.py", line 125, in do_execute text_to_run, md5, text_to_exclude=text_to_exclude) File "C:\Users\asus\AppData\Local\Programs\Python\Python37-32\lib\site-packages\stata_kernel\stata_session.py", line 274, in do self.kernel.cleanTail("{0}'".format(md5), self.prompt_dot) File "C:\Users\asus\AppData\Local\Programs\Python\Python37-32\lib\site-packages\stata_kernel\kernel.py", line 359, in cleanTail with open(logfile, 'r+', encoding='utf-8') as fh: FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\asus\Google'`

The code I'm trying to run is pretty basic: 
`
version 13
clear all
set more off
capture log close
log using "C:/Users/asus/Google Drive/Projects/EIDD/Data/Analysis/Master Panel Data/Logs/EIDD_regressionresults_masterpanel_04.log", replace`

Initially I thought it was a problem with having spaces in the file path, but I still receive the error even when I just run code attempting to set the working directory to something without spaces.

**Comment by mkgerullis** [comment]
Hello there, I am encountering the same problem. but only when I try to produce graphs using Stata within Atom. @rinalynne , you did not happen to find a solution for this in the meantime?
