### ISSUE TITLE
Jupiter notebook error in windows 64-bit

### ISSUE THREAD

**Issue by mohan488** [jupyter/notebook#5016]
upgraded the python to 38, I tried re-installing pyzmq still same error

C:\Users\Mohan>jupyter notebook
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python38\Scripts\jupyter-notebook.EXE\__main__.py", line 5, in <module>
  File "c:\python38\lib\site-packages\notebook\notebookapp.py", line 47, in <module>
    from zmq.eventloop import ioloop
  File "c:\python38\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "c:\python38\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "c:\python38\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "c:\python38\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "c:\python38\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "c:\python38\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed while importing error: The specified module could not be found.

**Comment by JerryKurata** [comment]
Same issue on a fresh install and 2 years later.  Any ideas?
