### ISSUE TITLE
Unable to run jupyter notebook due to kernel error

### ISSUE THREAD

**Issue by nataliemur26** [jupyter/notebook#5019]
When trying to run code in jupyter notebook I get the following error:

Traceback (most recent call last):
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'loop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\notebook\base\handlers.py", line 516, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 75, in post
    type=mtype))
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 94, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 258, in start_kernel
    self.start_restarter()
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\jupyter_client\ioloop\manager.py", line 49, in start_restarter
    kernel_manager=self, loop=self.loop,
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 591, in _validate
    value = self.validate(obj, value)
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 1677, in validate
    self.error(obj, value)
  File "C:\Users\Natalie\Anaconda3\lib\site-packages\traitlets\traitlets.py", line 1524, in error
    raise TraitError(e)
traitlets.traitlets.TraitError: The 'loop' trait of an IOLoopKernelManager instance must be a ZMQIOLoop, but a value of class 'tornado.platform.asyncio.AsyncIOMainLoop' (i.e. <tornado.platform.asyncio.AsyncIOMainLoop object at 0x000001F277AC1898>) was specified.

**Comment by nataliemur26** [comment]
Please help, still unable to fix the kernel error

**Comment by nataliemur26** [comment]
The following shows up for kernalspeclist:

(base) C:\Users\Natalie>Jupyter kernelspeclist
Traceback (most recent call last):
  File "c:\users\natalie\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\natalie\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Natalie\Anaconda3\Scripts\jupyter.exe\__main__.py", line 7, in <module>
  File "c:\users\natalie\anaconda3\lib\site-packages\jupyter_core\command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "c:\users\natalie\anaconda3\lib\site-packages\jupyter_core\command.py", line 134, in _jupyter_abspath
    'Jupyter command `{}` not found.'.format(jupyter_subcommand)
Exception: Jupyter command `jupyter-kernelspeclist` not found.

**Comment by kevin-bates** [comment]
Try `jupyter kernelspec list`

**Comment by nataliemur26** [comment]
Using `jupyter kernelspec list` gives the following:

(base) C:\Users\Natalie>jupyter kernelspec list
C:\Users\Natalie\Anaconda3\lib\site-packages\jupyter_client\kernelspec.py:150: UserWarning: get_ipython_dir has moved to the IPython.paths module since IPython 4.0.
  dirs.append(os.path.join(get_ipython_dir(), 'kernels'))
Available kernels:
  python3    C:\Users\Natalie\AppData\Roaming\jupyter\kernels\python3
