### ISSUE TITLE
Unable to launch Jupyter after installing Anaconda3-2019.10-Windows-x86_64(1)

### ISSUE THREAD

**Issue by rolysingh** [jupyter/notebook#5020]
Hi,

While launching Jupyter Notebook 6.0.1, I am facing below error -

Traceback (most recent call last):
File "C:\Users\rolsingh.PARTNERS\AppData\Local\Continuum\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 9, in 
import sqlite3
File "C:\Users\rolsingh.PARTNERS\AppData\Local\Continuum\anaconda3\lib\sqlite3\__init__.py", line 23, in 
from sqlite3.dbapi2 import *
File "C:\Users\rolsingh.PARTNERS\AppData\Local\Continuum\anaconda3\lib\sqlite3\dbapi2.py", line 27, in 
from _sqlite3 import *
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\rolsingh.PARTNERS\AppData\Local\Continuum\anaconda3\Scripts\jupyter-notebook-script.py", line 6, in 
from notebook.notebookapp import main
File "C:\Users\rolsingh.PARTNERS\AppData\Local\Continuum\anaconda3\lib\site-packages\notebook\notebookapp.py", line 86, in 
from .services.sessions.sessionmanager import SessionManager
File "C:\Users\rolsingh.PARTNERS\AppData\Local\Continuum\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 12, in 
from pysqlite2 import dbapi2 as sqlite3
ModuleNotFoundError: No module named 'pysqlite2'

Please let me know how can I fix the error. I have tried multiple times and its not working.

**Comment by ismailtokmak** [comment]
Hello,
Mine was below,
Traceback (most recent call last):
File "C:\Users\ismail.tokmak\AppData\Local\Continuum\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 9, in 
import sqlite3
File "C:\Users\ismail.tokmak\AppData\Local\Continuum\anaconda3\lib\sqlite3\__init__.py", line 23, in 
from sqlite3.dbapi2 import *
File "C:\Users\ismail.tokmak\AppData\Local\Continuum\anaconda3\lib\sqlite3\dbapi2.py", line 27, in 
from _sqlite3 import *
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\ismail.tokmak\AppData\Local\Continuum\anaconda3\Scripts\jupyter-notebook-script.py", line 6, in 
from notebook.notebookapp import main
File "C:\Users\ismail.tokmak\AppData\Local\Continuum\anaconda3\lib\site-packages\notebook\notebookapp.py", line 83, in 
from .services.sessions.sessionmanager import SessionManager
File "C:\Users\ismail.tokmak\AppData\Local\Continuum\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 12, in 
from pysqlite2 import dbapi2 as sqlite3
ModuleNotFoundError: No module named 'pysqlite2'

**Comment by YusufMohammedUH** [comment]
I had the same issue too, after installing the same packages as in another environment, but in a different order.

1. `conda install anaconda::numpy anaconda::scipy`
2. `conda install conda-forge::matplotlib anaconda::scikit-learn anaconda::pandas anaconda::seaborn`
3. `conda install anaconda::jupyter`

after the second command  sqlite was downgraded: 
> sqlite                                  3.45.3-h5eee18b_0 --> 3.31.1-h7b6447c_0

This seemed to be the issue. After fixing the sqlite version this issue was resolved, using:

`conda install sqlite=3.45.3`
 
But I have Ubuntu 24.04 and you seem to have a Windows OS, so i don't know if this will help.
 
After reading the how conda resolves dependencies, it seems as if the dependency on specific versions of sqlite are not accounted for by conda.  
Good luck!
