### ISSUE TITLE
JUPYTER NOTEBOOK IS NOT LAUNCHING

### ISSUE THREAD

**Issue by ultradluffy8** [jupyter/notebook#5026]
First Anaconda Navigator was not launching, then I tried it via Anaconda Powershell Prompt, it worked but now **Jupyter Notebook** is not launching it shows this message in a pop up window-

**Traceback (most recent call last):
File "C:\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in 
from notebook.notebookapp import main
File "C:\Users\Harshit\AppData\Roaming\Python\Python37\site-packages\notebook\notebookapp.py", line 47, in 
from zmq.eventloop import ioloop
File "C:\Users\Harshit\AppData\Roaming\Python\Python37\site-packages\zmq\__init__.py", line 47, in 
![Anaconda-Navigator 11_2_2019 12_54_25 PM](https://user-images.githubusercontent.com/48918993/68067677-d6000200-fd70-11e9-88ed-fc4a2313a654.png)
![Anaconda-Navigator 11_2_2019 12_54_25 PM](https://user-images.githubusercontent.com/48918993/68067685-f465fd80-fd70-11e9-9a8a-131fe036b176.png)

from zmq import backend
File "C:\Users\Harshit\AppData\Roaming\Python\Python37\site-packages\zmq\backend\__init__.py", line 40, in 
reraise(*exc_info)
File "C:\Users\Harshit\AppData\Roaming\Python\Python37\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
raise value
File "C:\Users\Harshit\AppData\Roaming\Python\Python37\site-packages\zmq\backend\__init__.py", line 27, in 
_ns = select_backend(first)
File "C:\Users\Harshit\AppData\Roaming\Python\Python37\site-packages\zmq\backend\select.py", line 28, in select_backend
mod = __import__(name, fromlist=public_api)
File "C:\Users\Harshit\AppData\Roaming\Python\Python37\site-packages\zmq\backend\cython\__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants' from 'zmq.backend.cython' (C:\Users\Harshit\AppData\Roaming\Python\Python37\site-packages\zmq\backend\cython\__init__.py)**

I don't know what to do.
Please help me.

**Comment by Kitty1989** [comment]
Same problem. Reinstalled twice.

**Comment by Ing-Mauro-Acuna** [comment]
I am struggling with the same issue. Cannot launch the notebook on the command promt (windows 10) either using the 'jupyter notebook command and raises this error: 'bash: jupyter: coomand not found'

**Comment by Abhisus2112** [comment]
Same for me as well

**Comment by Eyobs-droid** [comment]
try updating pyzmq packages
conda update pyzmq jupyter for updating
or reinstall it
pip uninstall pyzmq
pip install pyzmq
