### ISSUE TITLE
Kernel dead after new installation anaconda - juypter

### ISSUE THREAD

**Issue by snoksnok** [jupyter/notebook#5032]
Hi All, 

I encountered the error below when I tried to launch new Juypter notebook, python 3.7
Have tried the solution suggested in the platform to downgrade tornado>6, but encountered another error about environment.  Tried another solution using mkdir/run/user/$UID/python but not able to run. 
Much grateful if someone could advise. 
 

Traceback (most recent call last):
  File "C:\PythonProg\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "C:\PythonProg\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\PythonProg\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\PythonProg\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\PythonProg\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\PythonProg\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\PythonProg\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\PythonProg\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\PythonProg\lib\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\PythonProg\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\PythonProg\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\PythonProg\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\PythonProg\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\PythonProg\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\PythonProg\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
    **kw)
  File "C:\PythonProg\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\PythonProg\lib\site-packages\jupyter_client\launcher.py", line 138, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\PythonProg\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\PythonProg\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by kevin-bates** [comment]
You might try taking a look at https://github.com/jupyter/notebook/issues/2301#issuecomment-287119893 and the surrounding comments/instructions.

**Comment by Lostigli** [comment]
hello I get this kernel error every time I try to open a jupyter notebook, please help:


Traceback (most recent call last):
  File "B:\apps\anaconda_ai\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "B:\apps\anaconda_ai\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "B:\apps\anaconda_ai\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "B:\apps\anaconda_ai\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "B:\apps\anaconda_ai\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "B:\apps\anaconda_ai\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "B:\apps\anaconda_ai\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "B:\apps\anaconda_ai\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "B:\apps\anaconda_ai\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "B:\apps\anaconda_ai\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "B:\apps\anaconda_ai\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "B:\apps\anaconda_ai\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "B:\apps\anaconda_ai\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "B:\apps\anaconda_ai\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "B:\apps\anaconda_ai\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
    kernel_name=self.kernel_name
  File "B:\apps\anaconda_ai\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "B:\apps\anaconda_ai\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "B:\apps\anaconda_ai\lib\site-packages\jupyter_client\connect.py", line 102, in secure_write
    with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Lorenzo\\AppData\\Roaming\\jupyter\\runtime\\kernel-09691e25-6eff-47cf-aec0-5a30b584a5c6.json'


thanks

**Comment by kevin-bates** [comment]
@Lostigli - your issue is different and probably related to not having the updated `juptyer_client` and `jupyter_core` modules.   Upgrade `jupyter_client` and you should see it at version `5.3.4` with `jupyter_core` at `4.6.1` (i.e., **both** require updates).

**Comment by Lostigli** [comment]
Thanks for the help, I'll try

Il gio 7 nov 2019, 16:38 Kevin Bates <notifications@github.com> ha scritto:

**Comment by Lostigli** [comment]
Hello,
I'm still getting the same kernel error

Il ven 8 nov 2019, 11:26 Lorenzo Stigliano <lollostigli@gmail.com> ha
scritto:

**Comment by kevin-bates** [comment]
hmm - ok.  Can you provide the updated traceback and include a few lines prior to it?

**Comment by Lostigli** [comment]
I updated jupyter-client to 5.3.4 and jupyter-core to 4.6.1.
Still when i try to open a jupyter notebook i get a kernel error.
thanks for the help 


Traceback (most recent call last):
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\Lorenzo\Anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 102, in secure_write
    with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Lorenzo\\AppData\\Roaming\\jupyter\\runtime\\kernel-a1bbd4ca-65eb-4caa-9886-1ed0ac12bbe9.json'

**Comment by kevin-bates** [comment]
You're still using the older versions because `secure_write()` was moved to `jupyter_core` and this is showing it still coming from `jupyter_client`:

> `File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 102, in secure_write
with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:`

**Comment by Lostigli** [comment]
thanks, 
but how do i update it?
i tried installing it with `pip install jupyter-client` and `pip install jupyter-core`. 
thank you again

**Comment by kevin-bates** [comment]
Use `--upgrade`.  I think if you just do `pip install --upgrade jupyter-client` it should update both since jupyter-client has a dependency on jupyterr_core >= 4.6.0.  Just be sure you have 4.6.1 of core, so if you see 4.6.0 after the first upgrade, perform the same command against jupyter-core - which should yield 4.6.1.

**Comment by Lostigli** [comment]
So, I managed to upgrade jupyter-core and jupyter-client successfully.
Unfortunately I still get an error, a different one.

Traceback (most recent call last):
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\tornado\web.py", line
1699, in _execute
    result = await result
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\tornado\gen.py", line
742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File
"C:\Users\Lorenzo\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py",
line 72, in post
    type=mtype))
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\tornado\gen.py", line
735, in run
    value = future.result()
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\tornado\gen.py", line
742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File
"C:\Users\Lorenzo\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py",
line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name,
type, kernel_name)
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\tornado\gen.py", line
735, in run
    value = future.result()
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\tornado\gen.py", line
742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File
"C:\Users\Lorenzo\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py",
line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path,
kernel_name=kernel_name)
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\tornado\gen.py", line
735, in run
    value = future.result()
  File "C:\Users\Lorenzo\Anaconda3\lib\site-packages\tornado\gen.py", line
209, in wrapper
    yielded = next(result)
  File
"C:\Users\Lorenzo\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py",
line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File
"C:\Users\Lorenzo\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py",
line 110, in start_kernel
    km.start_kernel(**kwargs)
  File
"C:\Users\Lorenzo\Anaconda3\lib\site-packages\jupyter_client\manager.py",
line 259, in start_kernel
    **kw)
  File
"C:\Users\Lorenzo\Anaconda3\lib\site-packages\jupyter_client\manager.py",
line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File
"C:\Users\Lorenzo\Anaconda3\lib\site-packages\jupyter_client\launcher.py",
line 138, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Users\Lorenzo\Anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Lorenzo\Anaconda3\lib\subprocess.py", line 1178, in
_execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified


Il ven 8 nov 2019, 21:23 Kevin Bates <notifications@github.com> ha scritto:

**Comment by Lostigli** [comment]
@kevin-bates thanks for all the help, I finally managed to start jupyter notebook successfully.
I run in the anaconda prompt `python -m ipykernel install --user` and then opened the notebook and it worked.
Thanks again,
Lorenzo

**Comment by kevin-bates** [comment]
Since it appears we've com full circle to the OP issue which appears to be resolved by installing the ipykernel in user mode, I'm going to close this specific issue.  Thanks for your updates.
