### ISSUE TITLE
Unable to start kernel after installing new environment

### ISSUE THREAD

**Issue by Redwall13** [jupyter/notebook#5041]
hi all,

I have installed a new environment with Python 3.5 to use Zipline. Followed the instructions as per https://pypi.org/project/zipline-norgatedata/. 

After having installed everything and trying to run the jupyther notebook I got the following error when running a notebook: ImportError: no module named win32api

I have then uninstalled and installed pypiwin32 and since then I am not able to start the kernel as I get following error. 

Any help would be greatly appreciated thanks a lot in advance!

[I 19:08:27.241 NotebookApp] Kernel started: e8cd3b67-642f-4262-816a-20005ecb80e
7
Traceback (most recent call last):
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\runpy.py", line 193, in _run_m
odule_as_main
    "__main__", mod_spec)
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\runpy.py", line 85, in _run_co
de
    exec(code, run_globals)
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\site-packages\ipykernel_launch
er.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\site-packages\ipykernel\__init
__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\site-packages\ipykernel\connec
t.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
ImportError: No module named 'IPython.core'
[I 19:08:30.213 NotebookApp] KernelRestarter: restarting kernel (1/5), new rando
m ports
Traceback (most recent call last):
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\runpy.py", line 193, in _run_m
odule_as_main
    "__main__", mod_spec)
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\runpy.py", line 85, in _run_co
de
    exec(code, run_globals)
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\site-packages\ipykernel_launch
er.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\site-packages\ipykernel\__init
__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\site-packages\ipykernel\connec
t.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
ImportError: No module named 'IPython.core'
[I 19:08:33.214 NotebookApp] KernelRestarter: restarting kernel (2/5), new rando
m ports
Traceback (most recent call last):
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\runpy.py", line 193, in _run_m
odule_as_main
    "__main__", mod_spec)
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\runpy.py", line 85, in _run_co
de
    exec(code, run_globals)
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\site-packages\ipykernel_launch
er.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\site-packages\ipykernel\__init
__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\site-packages\ipykernel\connec
t.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
ImportError: No module named 'IPython.core'
[I 19:08:36.212 NotebookApp] KernelRestarter: restarting kernel (3/5), new rando
m ports
Traceback (most recent call last):
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\runpy.py", line 193, in _run_m
odule_as_main
    "__main__", mod_spec)
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\runpy.py", line 85, in _run_co
de
    exec(code, run_globals)
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\site-packages\ipykernel_launch
er.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\site-packages\ipykernel\__init
__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\site-packages\ipykernel\connec
t.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
ImportError: No module named 'IPython.core'
[I 19:08:39.228 NotebookApp] KernelRestarter: restarting kernel (4/5), new rando
m ports
Traceback (most recent call last):
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\runpy.py", line 193, in _run_m
odule_as_main
    "__main__", mod_spec)
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\runpy.py", line 85, in _run_co
de
    exec(code, run_globals)
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\site-packages\ipykernel_launch
er.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\site-packages\ipykernel\__init
__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\Redwall\Anaconda3\envs\zip35\lib\site-packages\ipykernel\connec
t.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
ImportError: No module named 'IPython.core'
[W 19:08:42.240 NotebookApp] KernelRestarter: restart failed
[W 19:08:42.241 NotebookApp] Kernel e8cd3b67-642f-4262-816a-20005ecb80e7 died, r
emoving from map.
[I 19:08:50.621 NotebookApp] Shutting down on /api/shutdown request.
[I 19:08:50.622 NotebookApp] Shutting down 0 kernels

(zip35) C:\Users\Redwall>jupyter kernelspec list
Available kernels:
  python3    C:\Users\Redwall\Anaconda3\envs\zip35\share\jupyter\kernels\python3

**Comment by rrluque** [comment]
I'm suffering the same problem.
Any clue?
