### ISSUE TITLE
Kernel Error: No mapping between account names and security IDs was done

### ISSUE THREAD

**Issue by wRaq** [jupyter/notebook#5042]
Traceback (most recent call last):
  File "d:\pyt\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "d:\pyt\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "d:\pyt\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "d:\pyt\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "d:\pyt\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "d:\pyt\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "d:\pyt\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "d:\pyt\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "d:\pyt\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "d:\pyt\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "d:\pyt\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "d:\pyt\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "d:\pyt\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "d:\pyt\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "d:\pyt\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
    kernel_name=self.kernel_name
  File "d:\pyt\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "d:\pyt\lib\contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "d:\pyt\lib\site-packages\jupyter_client\connect.py", line 100, in secure_write
    win32_restrict_file_to_user(fname)
  File "d:\pyt\lib\site-packages\jupyter_client\connect.py", line 58, in win32_restrict_file_to_user
    admins, _domain, _type = win32security.LookupAccountName("", "Administrators")
pywintypes.error: (1332, 'LookupAccountName', 'No mapping between account names and security IDs was done.')

Help me, please!

**Comment by wRaq** [comment]
Answer:
https://github.com/jupyter/jupyter_client/pull/478
https://github.com/jupyter/jupyter_client/pull/478/commits/9af6e14bf58fc70ea069b2cb35264d439100f879

**Comment by MrTrick** [comment]
I am getting this same error, when running Jupyter Notebook as a service using `nssm` as per [these instructions](https://www.techcoil.com/blog/how-to-use-nssm-to-setup-jupyter-notebook-as-a-windows-service-running-its-own-python-3-virtual-environment/).

`pywintypes.error: (1332, 'LookupAccountName', 'No mapping between account names and security IDs was done.')`

I'm running the latest component versions, I think:
```
Package            Version
------------------ -------
jupyter            1.0.0
jupyter-client     6.1.2
jupyter-console    6.1.0
jupyter-core       4.6.3
notebook           6.0.3
pywin32            227
pywinpty           0.5.7
...other packages not listed
```

**Comment by asmak9** [comment]
Hello Everyone,

If anyone still having this issue especially when using NSSM software on Windows 10 or Windows Server 2019. I have fixed it by manually applying the fix https://github.com/jupyter/jupyter_client/pull/478. One more important if you still face same issue even after applying the above fix then do follow i.e.

1. Manually verify Lib\site-packages\jupyter_client\connect.py file contains following lines i.e. 

`admins = win32security.CreateWellKnownSid(win32security.WinBuiltinAdministratorsSid)` 
`user, _domain, _type = win32security.LookupAccountName("", win32api.GetUserName())`

2. Manually verify Lib\site-packages\jupyter_core\paths.py file contains following lines i.e. 

`user, _domain, _type = win32security.LookupAccountName("", win32api.GetUserName())`

This will fix the issue.

Thanks & Regards,
Asma Khalid

Website: https://www.asmak9.com/
E-Store Bytezaar: https://www.bytezaar.com/
Q&A Forum: http://forum.asmak9.com/
