### ISSUE TITLE
Error on start, FileNotFoundError

### ISSUE THREAD

**Issue by tomasderner97** [jupyter/notebook#5059]
This is what I see when I start jupyter notebook in a console (Miniconda, python 3.7):

`(base) PS C:\Users\tomas> jupyter notebook
Traceback (most recent call last):
  File "C:\Miniconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\Miniconda3\lib\site-packages\notebook\notebookapp.py", line 83, in <module>
    from .services.contents.manager import ContentsManager
  File "C:\Miniconda3\lib\site-packages\notebook\services\contents\manager.py", line 17, in <module>
    from nbformat import sign, validate as validate_nb, ValidationError
  File "C:\Miniconda3\lib\site-packages\nbformat\__init__.py", line 33, in <module>
    from .validator import validate, ValidationError
  File "C:\Miniconda3\lib\site-packages\nbformat\validator.py", line 12, in <module>
    from jsonschema import ValidationError
  File "C:\Miniconda3\lib\site-packages\jsonschema\__init__.py", line 31, in <module>
    import importlib_metadata
  File "C:\Miniconda3\lib\site-packages\importlib_metadata\__init__.py", line 547, in <module>
    __version__ = version(__name__)
  File "C:\Miniconda3\lib\site-packages\importlib_metadata\__init__.py", line 509, in version
    return distribution(distribution_name).version
  File "C:\Miniconda3\lib\site-packages\importlib_metadata\__init__.py", line 482, in distribution
    return Distribution.from_name(distribution_name)
  File "C:\Miniconda3\lib\site-packages\importlib_metadata\__init__.py", line 183, in from_name
    dist = next(dists, None)
  File "C:\Miniconda3\lib\site-packages\importlib_metadata\__init__.py", line 452, in <genexpr>
    return (item for item in root.iterdir()
  File "C:\Miniconda3\lib\pathlib.py", line 1083, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\tomas\\ '`

Help?

**Comment by takluyver** [comment]
Educated guesswork: you have a space as an entry in the PYTHONPATH environment variable, e.g. maybe it ends with `; `. So packages that are trying to imitate the import system try to build a path with that.
