### ISSUE TITLE
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by simonm3** [jupyter/notebook#5061]
I suddenly get this error and can no longer start jupyter notebook. I can start jupyter console.  I have tried logging out and back in; uninstalled and reinstalled jupyter. Same error. I don't get why it is looking at the folders at the bottom. They are not in my config files. Is there some somewhere else a corrupt file? But where?

Full trace:

$ jupyter notebook
Traceback (most recent call last):
  File "C:\Users\simon\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\Users\simon\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 80, in <module>
    from .services.contents.manager import ContentsManager
  File "C:\Users\simon\Anaconda3\lib\site-packages\notebook\services\contents\manager.py", line 17, in <module>
    from nbformat import sign, validate as validate_nb, ValidationError
  File "C:\Users\simon\Anaconda3\lib\site-packages\nbformat\__init__.py", line 33, in <module>
    from .validator import validate, ValidationError
  File "C:\Users\simon\Anaconda3\lib\site-packages\nbformat\validator.py", line 12, in <module>
    from jsonschema import ValidationError
  File "C:\Users\simon\Anaconda3\lib\site-packages\jsonschema\__init__.py", line 31, in <module>
    import importlib_metadata
  File "C:\Users\simon\Anaconda3\lib\site-packages\importlib_metadata\__init__.py", line 547, in <module>
    __version__ = version(__name__)
  File "C:\Users\simon\Anaconda3\lib\site-packages\importlib_metadata\__init__.py", line 509, in version
    return distribution(distribution_name).version
  File "C:\Users\simon\Anaconda3\lib\site-packages\importlib_metadata\__init__.py", line 482, in distribution
    return Distribution.from_name(distribution_name)
  File "C:\Users\simon\Anaconda3\lib\site-packages\importlib_metadata\__init__.py", line 183, in from_name
    dist = next(dists, None)
  File "C:\Users\simon\Anaconda3\lib\site-packages\importlib_metadata\__init__.py", line 425, in <genexpr>
    for path in map(cls._switch_path, paths)
  File "C:\Users\simon\Anaconda3\lib\site-packages\importlib_metadata\__init__.py", line 449, in _search_path
    if not root.is_dir():
  File "C:\Users\simon\Anaconda3\lib\pathlib.py", line 1351, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "C:\Users\simon\Anaconda3\lib\pathlib.py", line 1161, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\simon\\Documents\\py\\live\\pipemaker\\ c:\\users\\simon\\documents\\py\\live\\renewable'

**Comment by simonm3** [comment]
The issue is something to do with a corrupt pythonpath. The solution was to remove the folder on the last line from the pythonpath and then add it again. Note that it looks correct in windows control panel and was working previously so no idea how it became corrupted.
