### ISSUE TITLE
Error compiling from source code

### ISSUE THREAD

**Issue by maveme** [jupyter/notebook#5062]
I'm trying to run Jupyter from the source code. However, when I ran the `pip3 install -e .` I'm getting the following error: 

`
Rebuilding /notebook/notebook/static/notebook/js/main.min.js
    > node tools/build-main.js notebook
    Rebuilding /notebook/notebook/static/tree/js/main.min.js
    > node tools/build-main.js tree
Failed to build tree Error: Error: ENOENT: no such file or directory, open '/notebook/notebook/static/components/jquery/dist/jquery.min.js'
    In module tree:
        tree/js/main
    
        at Object.openSync (fs.js:440:3)
    
        at /notebook/node_modules/requirejs/bin/r.js:28332:19
        at /notebook/node_modules/requirejs/bin/r.js:3059:39
        at /notebook/node_modules/requirejs/bin/r.js:2999:25
        at Function.prim.nextTick (/notebook/node_modules/requirejs/bin/r.js:28083:9)
        at Object.errback (/notebook/node_modules/requirejs/bin/r.js:2998:26)
        at Object.callback (/notebook/node_modules/requirejs/bin/r.js:2984:23)
        at Object.then (/notebook/node_modules/requirejs/bin/r.js:3038:23)
        at build (/notebook/node_modules/requirejs/bin/r.js:28289:12)
        at runBuild (/notebook/node_modules/requirejs/bin/r.js:30302:17)
        at Object.execCb (/notebook/node_modules/requirejs/bin/r.js:1946:33) {
      originalError: Error: ENOENT: no such file or directory, open '/notebook/notebook/static/components/jquery/dist/jquery.min.js'
          at Object.openSync (fs.js:440:3)
          at Object.readFileSync (fs.js:342:35)
          at Object.readFile (/notebook/node_modules/requirejs/bin/r.js:3658:27)
          at Object.readFileAsync (/notebook/node_modules/requirejs/bin/r.js:3672:32)
          at Function.require._cacheReadAsync (/notebook/node_modules/requirejs/bin/r.js:28102:25)
          at /notebook/node_modules/requirejs/bin/r.js:27671:48
          at /notebook/node_modules/requirejs/bin/r.js:3041:37
          at /notebook/node_modules/requirejs/bin/r.js:2989:25
          at Function.prim.nextTick (/notebook/node_modules/requirejs/bin/r.js:28083:9)
          at Object.callback (/notebook/node_modules/requirejs/bin/r.js:2988:26) {
        errno: -2,
        syscall: 'open',
        code: 'ENOENT',
        path: '/notebook/notebook/static/components/jquery/dist/jquery.min.js',
        fileName: '/notebook/notebook/static/components/jquery/dist/jquery.min.js',
        moduleTree: [ 'tree/js/main' ]
      }
    }
    Rebuilding /notebook/notebook/static/edit/js/main.min.js
    > node tools/build-main.js edit
    Failed to build notebook Error: Error: ENOENT: no such file or directory, open '/notebook/notebook/static/components/jquery/dist/jquery.min.js'
    In module tree:
        notebook/js/main
    
        at Object.openSync (fs.js:440:3)
    
        at /notebook/node_modules/requirejs/bin/r.js:28332:19
        at /notebook/node_modules/requirejs/bin/r.js:3059:39
        at /notebook/node_modules/requirejs/bin/r.js:2999:25
        at Function.prim.nextTick (/notebook/node_modules/requirejs/bin/r.js:28083:9)
        at Object.errback (/notebook/node_modules/requirejs/bin/r.js:2998:26)
        at Object.callback (/notebook/node_modules/requirejs/bin/r.js:2984:23)
        at Object.then (/notebook/node_modules/requirejs/bin/r.js:3038:23)
        at build (/notebook/node_modules/requirejs/bin/r.js:28289:12)
        at runBuild (/notebook/node_modules/requirejs/bin/r.js:30302:17)
        at Object.execCb (/notebook/node_modules/requirejs/bin/r.js:1946:33) {
      originalError: Error: ENOENT: no such file or directory, open '/notebook/notebook/static/components/jquery/dist/jquery.min.js'
          at Object.openSync (fs.js:440:3)
          at Object.readFileSync (fs.js:342:35)
          at Object.readFile (/notebook/node_modules/requirejs/bin/r.js:3658:27)
          at Object.readFileAsync (/notebook/node_modules/requirejs/bin/r.js:3672:32)
          at Function.require._cacheReadAsync (/notebook/node_modules/requirejs/bin/r.js:28102:25)
          at /notebook/node_modules/requirejs/bin/r.js:27671:48
          at /notebook/node_modules/requirejs/bin/r.js:3041:37
          at /notebook/node_modules/requirejs/bin/r.js:2989:25
          at Function.prim.nextTick (/notebook/node_modules/requirejs/bin/r.js:28083:9)
          at Object.callback (/notebook/node_modules/requirejs/bin/r.js:2988:26) {
        errno: -2,
        syscall: 'open',
        code: 'ENOENT',
        path: '/notebook/notebook/static/components/jquery/dist/jquery.min.js',
        fileName: '/notebook/notebook/static/components/jquery/dist/jquery.min.js',
        moduleTree: [ 'notebook/js/main' ]
      }
    }
    rebuilding js and css failed. The following required files are missing: ['notebook/static/notebook/js/main.min.js', 'notebook/static/tree/js/main.min.js', 'notebook/static/edit/js/main.min.js', 'notebook/static/terminal/js/main.min.js', 'notebook/static/auth/js/main.min.js', 'notebook/static/style/ipython.min.css', 'notebook/static/style/style.min.css']
    Rebuilding /notebook/notebook/static/terminal/js/main.min.js
    > node tools/build-main.js terminal
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/notebook/setup.py", line 172, in <module>
        main()
      File "/notebook/setup.py", line 169, in main
        setup(**setup_args)
      File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/notebook/setupbase.py", line 634, in run
        raise e
      File "/notebook/setupbase.py", line 623, in run
        self.distribution.run_command('js')
      File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/notebook/setupbase.py", line 569, in run
        pool.map(self.build_main, self.apps)
      File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
        return self._map_async(func, iterable, mapstar, chunksize).get()
      File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
        raise self._value
      File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
        result = (True, func(*args, **kwds))
      File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
        return list(map(*args))
      File "/notebook/setupbase.py", line 551, in build_main
        run(['node', 'tools/build-main.js', name])
      File "/notebook/setupbase.py", line 338, in run
        return check_call(cmd, *args, **kwargs)
      File "/usr/lib/python3.5/subprocess.py", line 271, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['node', 'tools/build-main.js', 'tree']' returned non-zero exit status 1
    Failed to build edit Error: Error: ENOENT: no such file or directory, open '/notebook/notebook/static/components/jquery/dist/jquery.min.js'
    In module tree:
        edit/js/main
    
        at Object.openSync (fs.js:440:3)
    
        at /notebook/node_modules/requirejs/bin/r.js:28332:19
        at /notebook/node_modules/requirejs/bin/r.js:3059:39
        at /notebook/node_modules/requirejs/bin/r.js:2999:25
        at Function.prim.nextTick (/notebook/node_modules/requirejs/bin/r.js:28083:9)
        at Object.errback (/notebook/node_modules/requirejs/bin/r.js:2998:26)
        at Object.callback (/notebook/node_modules/requirejs/bin/r.js:2984:23)
        at Object.then (/notebook/node_modules/requirejs/bin/r.js:3038:23)
        at build (/notebook/node_modules/requirejs/bin/r.js:28289:12)
        at runBuild (/notebook/node_modules/requirejs/bin/r.js:30302:17)
        at Object.execCb (/notebook/node_modules/requirejs/bin/r.js:1946:33) {
      originalError: Error: ENOENT: no such file or directory, open '/notebook/notebook/static/components/jquery/dist/jquery.min.js'
          at Object.openSync (fs.js:440:3)
          at Object.readFileSync (fs.js:342:35)
          at Object.readFile (/notebook/node_modules/requirejs/bin/r.js:3658:27)
          at Object.readFileAsync (/notebook/node_modules/requirejs/bin/r.js:3672:32)
          at Function.require._cacheReadAsync (/notebook/node_modules/requirejs/bin/r.js:28102:25)
          at /notebook/node_modules/requirejs/bin/r.js:27671:48
          at /notebook/node_modules/requirejs/bin/r.js:3041:37
          at /notebook/node_modules/requirejs/bin/r.js:2989:25
          at Function.prim.nextTick (/notebook/node_modules/requirejs/bin/r.js:28083:9)
          at Object.callback (/notebook/node_modules/requirejs/bin/r.js:2988:26) {
        errno: -2,
        syscall: 'open',
        code: 'ENOENT',
        path: '/notebook/notebook/static/components/jquery/dist/jquery.min.js',
        fileName: '/notebook/notebook/static/components/jquery/dist/jquery.min.js',
        moduleTree: [ 'edit/js/main' ]
      }
    }
    Failed to build terminal Error: Error: ENOENT: no such file or directory, open '/notebook/notebook/static/components/jquery/dist/jquery.min.js'
    In module tree:
        terminal/js/main
    
        at Object.openSync (fs.js:440:3)
    
        at /notebook/node_modules/requirejs/bin/r.js:28332:19
        at /notebook/node_modules/requirejs/bin/r.js:3059:39
        at /notebook/node_modules/requirejs/bin/r.js:2999:25
        at Function.prim.nextTick (/notebook/node_modules/requirejs/bin/r.js:28083:9)
        at Object.errback (/notebook/node_modules/requirejs/bin/r.js:2998:26)
        at Object.callback (/notebook/node_modules/requirejs/bin/r.js:2984:23)
        at Object.then (/notebook/node_modules/requirejs/bin/r.js:3038:23)
        at build (/notebook/node_modules/requirejs/bin/r.js:28289:12)
        at runBuild (/notebook/node_modules/requirejs/bin/r.js:30302:17)
        at Object.execCb (/notebook/node_modules/requirejs/bin/r.js:1946:33) {
      originalError: Error: ENOENT: no such file or directory, open '/notebook/notebook/static/components/jquery/dist/jquery.min.js'
          at Object.openSync (fs.js:440:3)
          at Object.readFileSync (fs.js:342:35)
          at Object.readFile (/notebook/node_modules/requirejs/bin/r.js:3658:27)
          at Object.readFileAsync (/notebook/node_modules/requirejs/bin/r.js:3672:32)
          at Function.require._cacheReadAsync (/notebook/node_modules/requirejs/bin/r.js:28102:25)
          at /notebook/node_modules/requirejs/bin/r.js:27671:48
          at /notebook/node_modules/requirejs/bin/r.js:3041:37
          at /notebook/node_modules/requirejs/bin/r.js:2989:25
          at Function.prim.nextTick (/notebook/node_modules/requirejs/bin/r.js:28083:9)
          at Object.callback (/notebook/node_modules/requirejs/bin/r.js:2988:26) {
        errno: -2,
        syscall: 'open',
        code: 'ENOENT',
        path: '/notebook/notebook/static/components/jquery/dist/jquery.min.js',
        fileName: '/notebook/notebook/static/components/jquery/dist/jquery.min.js',
        moduleTree: [ 'terminal/js/main' ]
      }
    }
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/notebook/setup.py'"'"'; __file__='"'"'/notebook/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
The command '/bin/sh -c pip3 install -e .' returned a non-zero code: 1
`

**Comment by maveme** [comment]
The problem was the path to the JQuery library in `notebook/tools/build-main.js `
