### ISSUE TITLE
jupyter notebook python kernel error

### ISSUE THREAD

**Issue by vvsonara** [jupyter/notebook#5093]
python code not running facing kernel error.
![kernal-error](https://user-images.githubusercontent.com/50987346/69896911-734b5780-136a-11ea-9ac7-f792c80c164f.png)

**Comment by kevin-bates** [comment]
Try upgrading `jupyter_client` to `5.3.4` (e.g., `pip install jupyter_client --upgrade`) which should also upgrade `jupyter_core` to `4.6.1`.

**Comment by misakib2** [comment]
@kevin-bates I have tried your suggestion but still no luck.

**Comment by kevin-bates** [comment]
Ok.  That's not too surprising.  However, the new modules produce a bit more logging, so please provide the full traceback (not a screen shot) since we'll need the details of the exception message.

Also, might the `\Users\MATRIX` filesystem be mounted from a different system?  This can affect permissions as well.

**Comment by blobbysquid** [comment]
I have this same problem, my users file is mounted from a different system so I was wondering what that fix is. My jupiter client is updated to 5.3.4 already

**Comment by kevin-bates** [comment]
@blobbysquid - are the permissions showing `0o0777` in the traceback?  (or `0o0677` since we tolerate owner-execute) If so, you may need to look into mount options that change the way file permissions work.  Having permissions of sensitive files automatically include read-write-execute bits for groups and others is an issue.

Take a look at this https://github.com/jupyter/notebook/issues/5058.  You should be able to point `JUPYTER_RUNTIME_DIR` to a local (and more secure) directory.

**Comment by vvsonara** [comment]
unsolved

**Comment by kevin-bates** [comment]
@vvsonara - I see you closed the issue but commented with 'unsolved' at the same moment.  Was your intention to keep this issue open?

If so, please re-open the issue.  In addition, please provide the new traceback information which should contain a bit more data.  Be sure to use a screen scrape (not a screen snapshot) since the helpful information may not be displayed in the active window.

**Comment by bcerin** [comment]
I had the same issue first I tryed:
`pip install jupyter_client --upgrade --user`
Then i got error:

`FileNotFoundError: [WinError 2] The system cannot find the file specified`
[https://github.com/jupyter/notebook/issues/2301](url)
Then typed:
`python -m ipykernel install --user`

It worked for me.

**Comment by janarthan-j** [comment]
Check your environment variable path!
 In the system variable path add the following lines "C:\Users\\AppData\Roaming\Python\Python37\Scripts"

**Comment by ergenekon94** [comment]
@kevin-bates  thank you so much resolved !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by shahram7** [comment]
i have the same issue. Can anyone help me?

```
Traceback (most recent call last):
  File "C:\Users\Shahram\anaconda3\lib\site-packages\tornado\web.py", line 1703, in _execute
    result = await result
  File "C:\Users\Shahram\anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Shahram\anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 69, in post
    model = yield maybe_future(
  File "C:\Users\Shahram\anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Shahram\anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Shahram\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\Shahram\anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Shahram\anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Shahram\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 100, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "C:\Users\Shahram\anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Shahram\anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "C:\Users\Shahram\anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 185, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\Shahram\anaconda3\lib\site-packages\jupyter_client\manager.py", line 313, in start_kernel
    self.kernel = self._launch_kernel(kernel_cmd, **kw)
  File "C:\Users\Shahram\anaconda3\lib\site-packages\jupyter_client\manager.py", line 220, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Users\Shahram\anaconda3\lib\site-packages\jupyter_client\launcher.py", line 131, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Users\Shahram\anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Shahram\anaconda3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

```

**Comment by Darkerhack** [comment]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/notebook/services/sessions/handlers.py", line 69, in post
    model = yield maybe_future(
  File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/notebook/services/sessions/sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/usr/local/lib/python3.8/site-packages/notebook/services/sessions/sessionmanager.py", line 100, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "/usr/local/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/local/lib/python3.8/site-packages/notebook/services/kernels/kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/jupyter_client/multikernelmanager.py", line 185, in start_kernel
    km.start_kernel(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/jupyter_client/manager.py", line 313, in start_kernel
    self.kernel = self._launch_kernel(kernel_cmd, **kw)
  File "/usr/local/lib/python3.8/site-packages/jupyter_client/manager.py", line 220, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/usr/local/lib/python3.8/site-packages/jupyter_client/launcher.py", line 131, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/opt/python/bin/python3.7'
```

I'm getting this kernel error while running a simple command in jupyter notebook
Kindly suggest solution please

**Comment by shahram7** [comment]
I've installed ipykernel again and it helped me

**Comment by Darkerhack** [comment]
Okay @shahram7, I'll try that for checking whether it'll resolve the issue or not. Thanks

**Comment by Darkerhack** [comment]
Hey, I've tried that and it worked now not getting the previous error!! Thanks a lot @shahram7
