### ISSUE TITLE
Jupyter server fails to start pycharm

### ISSUE THREAD

**Issue by pacoab** [jupyter/notebook#5116]
I have installed PyCharm Professional and I want to run Jupyter notebook in it, but whenever I try to run a cell, a message appears saying Jupyter server stopped with this message error:

Jupyter server process finishedTraceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\untitled\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\ProgramData\Miniconda3\envs\untitled\lib\site-packages\notebook\notebookapp.py", line 49, in <module>
    from zmq.eventloop import ioloop
  File "C:\ProgramData\Miniconda3\envs\untitled\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\ProgramData\Miniconda3\envs\untitled\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\ProgramData\Miniconda3\envs\untitled\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\ProgramData\Miniconda3\envs\untitled\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\ProgramData\Miniconda3\envs\untitled\lib\site-packages\zmq\backend\select.py", line 35, in select_backend
    reraise(ImportError, ImportError("Importing %s failed with %s" % (name, e)), exc_info[2])
  File "C:\ProgramData\Miniconda3\envs\untitled\lib\site-packages\zmq\utils\sixcerpt.py", line 33, in reraise
    raise value.with_traceback(tb)
  File "C:\ProgramData\Miniconda3\envs\untitled\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
ImportError: Importing zmq.backend.cython failed with invalid syntax (__init__.py, line 5)

 I can run jupyter in the command prompt, and even in the pycharm terminal, but when i try to run  in in pycharm, with the 2 "managed jupyter server:autostart" it just doesn´t work

**Comment by violetguos** [comment]
I'm not a regular contributor in this repo, but I encountered other problems when I use Pycharm. You might want to x-post your bug report to Pycharm. In many cases, it's a pycharm bug, not Jupyter's. The fact that yours works in command line makes me feel that.

Also source: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000094190-PyCharm-support-for-Jupyter-Notebooks-is-simply-terrible-even-after-2019-1
