### ISSUE TITLE
jupyter - Failed to start the kernel

### ISSUE THREAD

**Issue by Redmusk888** [jupyter/notebook#5128]
I was trying to Q# when I opened juypter notebook with Anaconda Powershell Prompt.
After i opened juypter notebook , my kernel is dead.

Unhandled error
Traceback (most recent call last):
  File "C:\Users\Raider\AppData\Roaming\Python\Python37\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "C:\Users\Raider\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\Raider\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\Raider\AppData\Roaming\Python\Python37\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "C:\Users\Raider\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\Raider\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\Raider\AppData\Roaming\Python\Python37\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\Raider\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\Raider\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\Raider\AppData\Roaming\Python\Python37\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\Raider\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\Users\Raider\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "C:\Users\Raider\AppData\Roaming\Python\Python37\site-packages\notebook\services\kernels\kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\Raider\AppData\Roaming\Python\Python37\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\Raider\AppData\Roaming\Python\Python37\site-packages\jupyter_client\manager.py", line 259, in start_kernel
    **kw)
  File "C:\Users\Raider\AppData\Roaming\Python\Python37\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Users\Raider\AppData\Roaming\Python\Python37\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系統找不到指定的檔案。

how to fix it

**Comment by kevin-bates** [comment]
The last two comments on https://github.com/jupyter/notebook/issues/5093 may give you what you need.  If that works out, please close this issue - otherwise provide the more recent traceback.  This is usually an issue with the `argv` entry in the kernel definition referencing a command that no longer exists (due to uninstall or move, etc.)
