### ISSUE TITLE
Failed to start kernel\ kernel error \ PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by lolkarthik** [jupyter/notebook#5129]
Hi All,

Please help me out on this :(

I just installed Python 3.7 and Anaconda 2019.10, Python 3.7 x64 bit (OS: Windows 10, 1909)
When I run cmd as administrator jupyter notebook is working fine, but I see a ton of files and folders.. there are so many that this particular page becomes laggy and unresponsive.

The issue is when I open cmd normally it shows kernel error and when I go to this location and give similar permission and new kernel pops up in the folder and its endless giving permission and still showing up kernel error.

What kind of other permission should I provide here? 
**SS from the notebook**
![image](https://user-images.githubusercontent.com/59305398/71541215-81958f00-297b-11ea-99f0-1d1d2052545e.png)

SS of the permission for the kernel and for this respective folder which it contains.
![image](https://user-images.githubusercontent.com/59305398/71541631-287d2980-2982-11ea-82e8-fdf3e23bace0.png)

SS when opened cmd as admin
![image](https://user-images.githubusercontent.com/59305398/71541591-79405280-2981-11ea-82e6-56a9d71963ca.png)

The error which I see :( 

Traceback (most recent call last):
  File "C:\Users\Karthik\Anaconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "C:\Users\Karthik\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Karthik\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\Users\Karthik\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Karthik\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Karthik\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\Karthik\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Karthik\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Karthik\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\Karthik\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Karthik\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\Karthik\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\Karthik\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\Karthik\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "C:\Users\Karthik\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\Users\Karthik\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\Karthik\Anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\Karthik\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 102, in secure_write
    with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
**PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Karthik\\AppData\\Roaming\\jupyter\\runtime\\kernel-6de04b7c-b829-41f1-b0cb-81fde47aa32c.json'**

**Comment by lolkarthik** [comment]
Lol I have uninstalled anaconda and installed anaconda 5.2.0 .. and installed at the location **C:\ rather than  C:\Users\[userfoldername]**

This resolved the issue for me
