### ISSUE TITLE
implementation error

### ISSUE THREAD

**Issue by animedhruv** [jupyter/notebook#5134]
Traceback (most recent call last):
  File "c:\users\dell\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\dell\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Dell\Python\Python38-32\Scripts\jupyter-notebook.EXE\__main__.py", line 7, in <module>
  File "c:\users\dell\python\python38-32\lib\site-packages\jupyter_core\application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\users\dell\python\python38-32\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<c:\users\dell\python\python38-32\lib\site-packages\decorator.py:decorator-gen-7>", line 2, in initialize
  File "c:\users\dell\python\python38-32\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\users\dell\python\python38-32\lib\site-packages\notebook\notebookapp.py", line 1720, in initialize
    self.init_webapp()
  File "c:\users\dell\python\python38-32\lib\site-packages\notebook\notebookapp.py", line 1482, in init_webapp
    self.http_server.listen(port, self.ip)
  File "c:\users\dell\python\python38-32\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "c:\users\dell\python\python38-32\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "c:\users\dell\python\python38-32\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "c:\users\dell\python\python38-32\lib\site-packages\tornado\platform\asyncio.py", line 99, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "c:\users\dell\python\python38-32\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError

Getting this while trying to open jupyter notebook

**Comment by jasongrout** [comment]
This is a python 3.8 compatibility issue. See https://github.com/jupyter/notebook/issues/4613, fixed in https://github.com/jupyter/notebook/pull/5047 and awaiting release.
