### ISSUE TITLE
Jupyter server cannot start

### ISSUE THREAD

**Issue by arilwan** [jupyter/notebook#5150]
I am using Macbook and was running the  Jupyter server fine in the past. For nearly 3 weeks I didn't use it, and now having trouble as it isn't running.

```
$ jupyter notebook
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 6, in <module>
    from notebook.notebookapp import main
  File "/usr/local/lib/python3.7/site-packages/notebook/notebookapp.py", line 62, in <module>
    from tornado import httpserver
  File "/usr/local/lib/python3.7/site-packages/tornado/httpserver.py", line 29, in <module>
    import ssl
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: dlopen(/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so
  Reason: image not found
```

But then I can import `ssl` module from Python interpreter
```
$ python3
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>>
```

Uninstall and re-installing jupyter didn't fix it.
Any idea how to fix this?

**Comment by arilwan** [comment]
For anyone coming across this issue, here's how I resolve it.
First uninstall `openssl`.
_brew uninstall --ignore-dependencies openssl_

The re-install it again
_brew install openssl_

**Comment by big-c-note** [comment]
That did not work for me. I have the same issue

**Comment by Wei-1** [comment]
I got the same issue and that work around doesn't seem to work.
