### ISSUE TITLE
“jupyter notebook stop 8888” calls an error

### ISSUE THREAD

**Issue by jygzyc** [jupyter/notebook#5154]
I want to close my jupyter, but it doesn't work.
`Shutting down server on port 8888 ...
Traceback (most recent call last):
  File "c:\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\python38\Scripts\jupyter-notebook.EXE\__main__.py", line 9, in <module>
  File "c:\python38\lib\site-packages\jupyter_core\application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\python38\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "c:\python38\lib\site-packages\notebook\notebookapp.py", line 1861, in start
    super(NotebookApp, self).start()
  File "c:\python38\lib\site-packages\jupyter_core\application.py", line 257, in start
    self.subapp.start()
  File "c:\python38\lib\site-packages\notebook\notebookapp.py", line 466, in start
    if not self.shutdown_server(server):
  File "c:\python38\lib\site-packages\notebook\notebookapp.py", line 457, in shutdown_server
    return shutdown_server(server, log=self.log)
  File "c:\python38\lib\site-packages\notebook\notebookapp.py", line 417, in shutdown_server
    HTTPClient().fetch(req)
  File "c:\python38\lib\site-packages\tornado\httpclient.py", line 132, in fetch
    response = self._io_loop.run_sync(
  File "c:\python38\lib\site-packages\tornado\ioloop.py", line 532, in run_sync
    return future_cell[0].result()
  File "c:\python38\lib\site-packages\tornado\simple_httpclient.py", line 330, in run
    stream = await self.tcp_client.connect(
  File "c:\python38\lib\site-packages\tornado\tcpclient.py", line 280, in connect
    af, addr, stream = await connector.start(connect_timeout=timeout)
  File "c:\python38\lib\site-packages\tornado\tcpclient.py", line 110, in start
    self.try_connect(iter(self.primary_addrs))
  File "c:\python38\lib\site-packages\tornado\tcpclient.py", line 128, in try_connect
    stream, future = self.connect(af, addr)
  File "c:\python38\lib\site-packages\tornado\tcpclient.py", line 334, in _create_stream
    return stream, stream.connect(addr)
  File "c:\python38\lib\site-packages\tornado\iostream.py", line 1219, in connect
    self._add_io_state(self.io_loop.WRITE)
  File "c:\python38\lib\site-packages\tornado\iostream.py", line 1050, in _add_io_state
    self.io_loop.add_handler(self.fileno(), self._handle_events, self._state)
  File "c:\python38\lib\site-packages\tornado\platform\asyncio.py", line 102, in add_handler
    self.asyncio_loop.add_writer(fd, self._handle_events, fd, IOLoop.WRITE)
  File "c:\python38\lib\asyncio\events.py", line 507, in add_writer
    raise NotImplementedError
NotImplementedError`

How should I handle it?

**Comment by jygzyc** [comment]
Addition:
`C:\python38>jupyter notebook list
Currently running servers:
http://localhost:8888/?token=7a0c69d73eb298239bd7205ef4003f894d0ee0714c7fd0a5 :: C:\Users\user\AppData\Local\Temp\f76eee75-229f-47a2-92a2-a80b30be7947`

**Comment by kevin-bates** [comment]
I believe this is related to https://github.com/jupyter/notebook/pull/5047 and its workaround (until 6.0.3 is released) should apply to the shutdown app as well - although I can't confirm that's the case.

**Comment by jygzyc** [comment]
I had referenced the issue #5047 ,but I still have no idea with it. When I change the Python version to 3.7. It's no problem at all. Emmm...Maybe I should use an 'old' python?

**Comment by kevin-bates** [comment]
You're correct. This issue only occurs on Windows with Python 3.8 so using an older python is another form of workaround.
