### ISSUE TITLE
can't open JNB from terminal

### ISSUE THREAD

**Issue by Jeanjohnsen** [jupyter/notebook#5159]
I am getting this error when typing 'jupyter notebook' in my cmd

C:\Users\geniu\AppData\Local\Programs\Python\Python38-32>jupyter notebook
Traceback (most recent call last):
  File "c:\users\geniu\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\geniu\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\geniu\AppData\Local\Programs\Python\Python38-32\Scripts\jupyter-notebook.EXE\__main__.py", line 7, in <module>
  File "c:\users\geniu\appdata\local\programs\python\python38-32\lib\site-packages\jupyter_core\application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "c:\users\geniu\appdata\local\programs\python\python38-32\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<c:\users\geniu\appdata\local\programs\python\python38-32\lib\site-packages\decorator.py:decorator-gen-7>", line 2, in initialize
  File "c:\users\geniu\appdata\local\programs\python\python38-32\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\users\geniu\appdata\local\programs\python\python38-32\lib\site-packages\notebook\notebookapp.py", line 1720, in initialize
    self.init_webapp()
  File "c:\users\geniu\appdata\local\programs\python\python38-32\lib\site-packages\notebook\notebookapp.py", line 1482, in init_webapp
    self.http_server.listen(port, self.ip)
  File "c:\users\geniu\appdata\local\programs\python\python38-32\lib\site-packages\tornado\tcpserver.py", line 152, in listen
    self.add_sockets(sockets)
  File "c:\users\geniu\appdata\local\programs\python\python38-32\lib\site-packages\tornado\tcpserver.py", line 165, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "c:\users\geniu\appdata\local\programs\python\python38-32\lib\site-packages\tornado\netutil.py", line 279, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "c:\users\geniu\appdata\local\programs\python\python38-32\lib\site-packages\tornado\platform\asyncio.py", line 99, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "c:\users\geniu\appdata\local\programs\python\python38-32\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError

**Comment by kevin-bates** [comment]
This is a duplicate of #4613 and the workaround listed in #5047 should get you going.

**Comment by Ricyteach** [comment]
I left a similar comment elsewhere about this so I hope I'm not piling on, but: 

The trouble with the workaround is if you are often creating virtual environments (which includes a fresh pull down of notebook), the fix has to be implemented every time you create one. 

Speaking for myself: I've simply just had to not use 3.8 at all until 6.0.3 drops and the fix is permanently available. 

Does anyone know when 6.0.3 is coming? I know this is a free and open project and I'm not complaining. Very grateful for all the people working on it! Just wanting to get an idea how much longer it will be.

**Comment by kevin-bates** [comment]
I think we can expect a Notebook 6.0.3 drop in the next day or two.  I believe it was delayed by a conda-forge issue with a required project.

**Comment by Ricyteach** [comment]
What a relief to hear! Thanks!
