### ISSUE TITLE
ModuleNotFoundError: No module named 'notebook.tree'

### ISSUE THREAD

**Issue by nb9ez** [jupyter/notebook#5175]
I've installed Anaconda, but I can't even get Jupyter notebook to run. I've tried running it from Anaconda Navigator, as well as from the command line by typing `jupyter notebook`. The error message I get is below. 

I'm running Windows 10 64 bit, and it's Python 3.7 that's been installed (which works when I type `python` in Anaconda Prompt). 

I've also tried updating in various ways, both with `pip` and with `conda`, both of those with several different flags. 

Any advice?

`(base) C:\Users\Nikhil Bharani>jupyter notebook
Traceback (most recent call last):
  File "c:\users\nikhil bharani\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\nikhil bharani\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Nikhil Bharani\Anaconda3\Scripts\jupyter-notebook.EXE\__main__.py", line 9, in <module>
  File "c:\users\nikhil bharani\anaconda3\lib\site-packages\jupyter_core\application.py", line 268, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\Nikhil Bharani\AppData\Roaming\Python\Python37\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<C:\Users\Nikhil Bharani\AppData\Roaming\Python\Python37\site-packages\decorator.py:decorator-gen-7>", line 2, in initialize
  File "C:\Users\Nikhil Bharani\AppData\Roaming\Python\Python37\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\Nikhil Bharani\AppData\Roaming\Python\Python37\site-packages\notebook\notebookapp.py", line 1679, in initialize
    self.init_webapp()
  File "C:\Users\Nikhil Bharani\AppData\Roaming\Python\Python37\site-packages\notebook\notebookapp.py", line 1408, in init_webapp
    self.jinja_environment_options,
  File "C:\Users\Nikhil Bharani\AppData\Roaming\Python\Python37\site-packages\notebook\notebookapp.py", line 161, in __init__
    handlers = self.init_handlers(settings)
  File "C:\Users\Nikhil Bharani\AppData\Roaming\Python\Python37\site-packages\notebook\notebookapp.py", line 297, in init_handlers
    handlers.extend(load_handlers('notebook.tree.handlers'))
  File "C:\Users\Nikhil Bharani\AppData\Roaming\Python\Python37\site-packages\notebook\notebookapp.py", line 141, in load_handlers
    mod = __import__(name, fromlist=['default_handlers'])
ModuleNotFoundError: No module named 'notebook.tree'`

**Comment by nb9ez** [comment]
@tbrown122387

**Comment by yizhoucc** [comment]
same prob

**Comment by nrmzmh** [comment]
face the same issue, after uninstalling the jupyter & notebook, and installing back, still facing the same error

**Comment by nrmzmh** [comment]
I also have the same problem before and my jupyter notebook version is 6.0.3,

when I trace the folder path 
> C:\Users\**YOUR_NAME**\AppData\Roaming\Python\Python37\site-packages\notebook

there is no folder tree in folder notebook since the last error are
`ModuleNotFoundError: No module named 'notebook.tree'`

![image](https://user-images.githubusercontent.com/36750732/77118779-fe627180-6a6f-11ea-8302-76ae3289124a.png)

So I try to downgrade my jupyter notebook version into 5.7.5 at the command prompt
`pip install jupyter notebook==5.7.5`

and now I'm able to open jupyter notebook

**Comment by madhavparikh99** [comment]
I followed the same steps as @nrmzmh did but still, I am facing the same error of ModuleNotFound: No module named 'notebook.tree'

**Comment by ruyiq** [comment]
> I followed the same steps as @nrmzmh did but still, I am facing the same error of ModuleNotFound: No module named 'notebook.tree'

same here.

**Comment by Arij-Aladel** [comment]
same

**Comment by Markoh2244** [comment]
I had the same error, I was able to fix it. It looks like it had to do something with my python install. Try uninstalling it and make sure you have the installation correct. If you have python 3.8 for example, you should have a folder  38_32 and it should contain a lot of other sub folders. Hope this helps

**Comment by zhipenghan** [comment]
I had the same error and resolved it by uninstall the package -> manually delete the package path below-> install notebook again.
I find the uninstall won't remove the package automatically.

...
  File "_**C:\Users\alias\AppData\Roaming\Python\Python37\site-packages\notebook\**_notebookapp.py", line 138, in load_handlers
    mod = __import__(name, fromlist=['default_handlers'])
ModuleNotFoundError: No module named 'notebook.tree'

**Comment by Zsailer** [comment]
Thank you @nrmzmh for the helpful debugging. Based on that snapshot, it's possible the `6.0.3` release of Jupyter Notebook on Windows might be broken. Do you mind upgrading to Jupyter Notebook `6.2.0` and seeing if that fixes the issue?
