### ISSUE TITLE
Failed to start kernel in jupyter notebook for Julia

### ISSUE THREAD

**Issue by mamuniut09** [jupyter/notebook#5208]
Hello all,

I am facing the below unhandled error and the kernel fails to start. I would appreciate if anybody could help resolve this issue.

**The error message:**

`Traceback (most recent call last):
  File "C:\Users\Mamun\Anaconda3\conda\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "C:\Users\Mamun\Anaconda3\conda\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Mamun\Anaconda3\conda\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\Users\Mamun\Anaconda3\conda\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Mamun\Anaconda3\conda\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Mamun\Anaconda3\conda\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\Mamun\Anaconda3\conda\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Mamun\Anaconda3\conda\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Mamun\Anaconda3\conda\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\Mamun\Anaconda3\conda\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Mamun\Anaconda3\conda\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\Mamun\Anaconda3\conda\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\Mamun\Anaconda3\conda\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\Mamun\Anaconda3\conda\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "C:\Users\Mamun\Anaconda3\conda\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\Users\Mamun\Anaconda3\conda\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\Mamun\Anaconda3\conda\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\Mamun\Anaconda3\conda\lib\site-packages\jupyter_client\connect.py", line 102, in secure_write
    with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Mamun\\AppData\\Roaming\\jupyter\\runtime\\kernel-3c9bc172-8b0f-4224-89c6-22339600824f.json'
`

**Comment by kevin-bates** [comment]
This is a duplicate of #5124.  Now that notebook 6.0.3 is available, please upgrade notebook.  

`pip install notebook --upgrade`

or, for conda envs,

`conda update -c conda-forge notebook`

Once completed, ensure that `jupyter_client` and `jupyter_core` have versions `5.3.4` and `4.6.1`, respectively.

Please re-open this issue if you experience the problem after performing the steps above.

**Comment by kevin-bates** [comment]
I'm sorry, although the steps I gave should be performed, this issue could be related to a mounted filesystem that prevents the ability to write secure files.  As a result, I'm re-opening this issue until @mamuniut09 confirms proper (or improper) behavior.

**Comment by mamuniut09** [comment]
Kevin, thanks a lot for your help. Actually, the error is resolved when I uninstalled the recent windows updates on my pc. Anyways, I appreciate your time.
