### ISSUE TITLE
kernel error in jupytor notebook

### ISSUE THREAD

**Issue by rustyy012** [jupyter/notebook#5229]

**Comment by rustyy012** [comment]
Traceback (most recent call last):
  File "C:\Users\kunal\Anaconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "C:\Users\kunal\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\kunal\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\Users\kunal\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\kunal\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\kunal\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\kunal\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\kunal\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\kunal\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\kunal\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\kunal\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\kunal\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\kunal\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\kunal\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "C:\Users\kunal\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
    sock = self.context.socket(socket_type)
  File "C:\Users\kunal\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    else:
  File "C:\Users\kunal\Anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\kunal\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 102, in secure_write
    sock.bind((ip, 0))
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\kunal\\AppData\\Roaming\\jupyter\\runtime\\kernel-bd80316e-ad9b-4496-b5d9-47b0fb3495b5.json'

**Comment by rustyy012** [comment]
please provide solution for this error .i tried some solutions which are alresdy here but none of them worked.

**Comment by kevin-bates** [comment]
This is appears to be a duplicate of #5124.  I can't tell what solutions you have attempted, but now that notebook 6.0.3 is available, please try upgrading notebook.  

`pip install notebook --upgrade`

or, for conda envs,

`conda update -c conda-forge notebook`

Once completed, ensure that `jupyter_client` and `jupyter_core` have versions `5.3.4` and `4.6.1`, respectively.  If the problem still persists, please provide the updated traceback since it should provide more helpful information.

Thanks.

**Comment by rustyy012** [comment]
i tried pip install notebook ....now the kernel is running ..hopefully it doesnt get more problems in the future...thanks for your help....much appreciated.
