### ISSUE TITLE
jupyter notebook: ImportError: No module named path

### ISSUE THREAD

**Issue by mafcm** [jupyter/notebook#525]
Hi,

I have this error when I launch ``jupyter notebook``
```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/usr/local/lib/python2.7/dist-packages/notebook/notebookapp.py", line 83, in <module>
    from IPython.paths import get_ipython_dir
  File "/usr/local/lib/python2.7/dist-packages/IPython/__init__.py", line 48, in <module>
    from .terminal.embed import embed
  File "/usr/local/lib/python2.7/dist-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.core.interactiveshell import DummyMod
  File "/usr/local/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 31, in <module>
    from pickleshare import PickleShareDB
  File "/usr/local/lib/python2.7/dist-packages/pickleshare.py", line 41, in <module>
    from path import path as Path
ImportError: No module named path
```

How to solve it please ?

**Comment by minrk** [comment]
This should do it:

    pip install path.py
