### ISSUE TITLE
Kernel crash and showing permission denied errno 13 help me out please. 

### ISSUE THREAD

**Issue by kharekartik08** [jupyter/notebook#5251]
```
HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
        result = await result
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
        type=mtype))
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
        yielded = next(result)
      File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
        self.write_connection_file()
      File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
        kernel_name=self.kernel_name
      File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
        with secure_write(fname) as f:
      File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 112, in __enter__
        return next(self.gen)
      File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 102, in secure_write
        with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
    PermissionError: [Errno 13] Permission denied: 'C:\\Users\\KK\\AppData\\Roaming\\jupyter\\runtime\\kernel-00147603-8649-4e6e-b9b3-916390d71bf8.json'
```

I uninstalled anaconda and installed it again but problem still persists.
Please help me out
Windows 10 64bit

**Comment by kevin-bates** [comment]
This is appears to be a duplicate of #5124.  I can't tell what solutions you have attempted, but now that notebook 6.0.3 is available, please try upgrading notebook.  

`pip install notebook --upgrade`

or, for conda envs,

`conda update -c conda-forge notebook`

Once completed, ensure that `jupyter_client` and `jupyter_core` have versions `5.3.4` and `4.6.1`, respectively.  If the problem still persists, please provide the updated traceback since it should provide more helpful information.

Thanks.
