### ISSUE TITLE
Kernel Error

### ISSUE THREAD

**Issue by Stevenvig** [jupyter/notebook#5253]
Anyone know what this error is?

> Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "C:\Anaconda\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Anaconda\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\Anaconda\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Anaconda\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Anaconda\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Anaconda\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Anaconda\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Anaconda\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Anaconda\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Anaconda\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Anaconda\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Anaconda\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Anaconda\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "C:\Anaconda\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\Anaconda\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Anaconda\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Anaconda\lib\site-packages\jupyter_client\connect.py", line 100, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Anaconda\lib\site-packages\jupyter_client\connect.py", line 61, in win32_restrict_file_to_user
    sd = win32security.GetFileSecurity(fname, win32security.DACL_SECURITY_INFORMATION)
pywintypes.error: (50, 'GetFileSecurity', 'The request is not supported.')

>

**Comment by kevin-bates** [comment]
This appears to be a snafu with the pywin32 package. You might try looking at #4980.

Given your traceback, I would try upgrading notebook.  

`pip install notebook --upgrade`

or, for conda envs,

`conda update -c conda-forge notebook`

Once completed, ensure that `jupyter_client` and `jupyter_core` have versions `5.3.4` and `4.6.3`, respectively.  

Once jupyter_core is on 4.6.3, there's another option that can bypass the pywin32 issue by setting `JUPYTER_ALLOW_INSECURE_WRITES=true`, but that should be a last resort and only if security is not paramount.

**Comment by kevin-bates** [comment]
Closing this issue.  We can re-open if this is still a problem and the recommendations were not sufficient.
