### ISSUE TITLE
Kernel Error Trying to Create a Notebook

### ISSUE THREAD

**Issue by MORNIIN** [jupyter/notebook#5277]
I am very new to programming, in fact I know next to nothing. In Udemy I was asked to create a Python 3 Notebook on desktop but there wasn't any folders for that so I created a folder, "Untitled Folder." so I Tried to create a notebook in it but I was getting this Kernel error:

Traceback (most recent call last):
  File "C:\Users\thebe\Anaconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "C:\Users\thebe\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\thebe\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\Users\thebe\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\thebe\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\thebe\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\thebe\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\thebe\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\thebe\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\thebe\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\thebe\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\thebe\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\thebe\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\thebe\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "C:\Users\thebe\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\Users\thebe\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\thebe\Anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\thebe\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 102, in secure_write
    with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\thebe\\AppData\\Roaming\\jupyter\\runtime\\kernel-460d4e50-ae89-492a-a023-6eab3d583fa2.json'

![kernel error 1](https://user-images.githubusercontent.com/62039635/76368651-04ef3b80-6342-11ea-8aa0-dd796cb21023.png)
![kernel error 2](https://user-images.githubusercontent.com/62039635/76368662-0b7db300-6342-11ea-97bb-0e989f4288e3.png)

Thank you very much if you decide to help.

**Comment by kevin-bates** [comment]
Hi @MORNIIN - welcome to the world of programming and, specifically, the Jupyter Community!

You're bumping into a common problem as of late, so "it's not you".  The first step to troubleshooting this issue is to get you up on the latest version of Notebook.  I recommend you stop the notebook server (control-C twice in the command window is the normal approach), then do either of the following to upgrade Notebook (and its dependencies)...

`pip install notebook --upgrade`

or, for conda envs,

`conda update -c conda-forge notebook`

Once completed, you should find that `jupyter_client` and `jupyter_core` have versions >= `5.3.4` and >= `4.6.1`, respectively.  The version check is most easily accomplished using `pip freeze`, then locating the modules in the output. 

Once updated, start your Notebook server instance (e.g., `jupyter notebook`) and try starting a kernel again.  If the problem still persists, please provide the updated traceback information similar to what you provided previously.  The screenshots, for this issue, are not required - although appreciated down the road for other issues.

**Comment by MORNIIN** [comment]
Thank you so much. This fixed the issue. I have to say this all feels like black magic right now but I am excited to see where programming leads for me. I appreciate the help!
