### ISSUE TITLE
Failed to start the kernel, SAS

### ISSUE THREAD

**Issue by bbumi5** [jupyter/notebook#5287]
Hello. I need some help.
I am working on setting jupyter notebook. 
Current Status:
- Windows 10 (64 bit)
- installed SAS 9.4 (64 bit)
- installed Ananconda3 (64 bit)

![12](https://user-images.githubusercontent.com/62242299/76749781-6e4ad080-67c0-11ea-9aab-cb2677405965.PNG)

![11](https://user-images.githubusercontent.com/62242299/76749789-73a81b00-67c0-11ea-95ca-79a9c0d8fea9.PNG)

The problem is, I connected the SAS with jupyter but SAS kernel doesn't work.
Following is log screen that shows up when I click Kernel Error.

![13](https://user-images.githubusercontent.com/62242299/76749804-79056580-67c0-11ea-8f36-cb5c70ad0d67.PNG)

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
    **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\ProgramData\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 138, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by kevin-bates** [comment]
Check the `argv` stanza of the `kernel.json` file located in the `kernel\sas` directory and ensure the program that is to be invoked exists and is accessible.  The traceback is indicating that it can't find the file that launches the kernel process.

**Comment by bbumi5** [comment]
> Check the `argv` stanza of the `kernel.json` file located in the `kernel\sas` directory and ensure the program that is to be invoked exists and is accessible. The traceback is indicating that it can't find the file that launches the kernel process.

Thank you. I checked argv, changed the file location and it worked.
