### ISSUE TITLE
i downloaded jupyter notebook through anaconda but as it started ,it showed kernel error

### ISSUE THREAD

**Issue by pranavagrawal2005** [jupyter/notebook#5290]

**Comment by pranavagrawal2005** [comment]
it showed:
Traceback (most recent call last):
      File "C:\Users\abhishek\Anaconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
        result = await result
      File "C:\Users\abhishek\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\abhishek\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
        type=mtype))
      File "C:\Users\abhishek\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\abhishek\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\abhishek\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session

**Comment by kevin-bates** [comment]
Hi @pranavagrawal2005 - this traceback appears to be incomplete.  I have a suspicion it's going to lead to a permission issue when writing the connection file.  If you haven't done so already, I would recommend upgrading notebook to 6.0.3.

`pip install notebook --upgrade`

or, for conda envs,

`conda update -c conda-forge notebook`

**Comment by pranavagrawal2005** [comment]
sir,i appreciate of your help but i put it in the anaconda prompt...it successfully upgraded.but then i started the jupyter notebook and got this error:
Traceback (most recent call last):
  File "C:\Users\abhishek\Anaconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "C:\Users\abhishek\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\abhishek\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\Users\abhishek\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\abhishek\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\abhishek\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\abhishek\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\abhishek\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\abhishek\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\abhishek\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\abhishek\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\abhishek\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\abhishek\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\abhishek\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "C:\Users\abhishek\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\Users\abhishek\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\abhishek\Anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\abhishek\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 102, in secure_write
    with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\abhishek\\AppData\\Roaming\\jupyter\\runtime\\kernel-9d9161bf-268a-46e4-9875-2fd163566658.json'

**Comment by kevin-bates** [comment]
The traceback implies the upgrade didn't happen.  The `secure_write` method will come from `jupyter_core` once modules are updated.  Did you restart `jupyter notebook` after upgrading?
