### ISSUE TITLE
500 : Internal Server Error ::: Jupyter Notebook 

### ISSUE THREAD

**Issue by connect2robiul** [jupyter/notebook#5293]
```
`[rislam@sms ~]$ jupyter notebook --no-browser --port=2222
[E 14:45:34.467 NotebookApp] [nb_conda_kernels] couldn't call conda:
    [Errno 2] No such file or directory: 'conda'
[I 14:45:34.469 NotebookApp] [nb_conda_kernels] enabled, 0 kernels found
[I 14:45:41.079 NotebookApp] JupyterLab extension loaded from /home/rislam/anaconda/lib/python3.5/site-packages/jupyterlab
[I 14:45:41.079 NotebookApp] JupyterLab application directory is /home/rislam/anaconda/share/jupyter/lab
[I 14:45:44.567 NotebookApp] [nb_anacondacloud] enabled
[I 14:45:44.602 NotebookApp] [nb_conda] enabled
[W 14:45:45.317 NotebookApp] Error loading server extension nbpresent
    Traceback (most recent call last):
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/notebookapp.py", line 1670, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/home/rislam/anaconda/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 665, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "/home/rislam/anaconda/lib/python3.5/site-packages/nbpresent/__init__.py", line 5, in <module>
        from nbconvert.exporters.export import exporter_map
      File "/home/rislam/anaconda/lib/python3.5/site-packages/nbconvert/__init__.py", line 7, in <module>
        from . import postprocessors
      File "/home/rislam/anaconda/lib/python3.5/site-packages/nbconvert/postprocessors/__init__.py", line 5, in <module>
        from .serve import ServePostProcessor
      File "/home/rislam/anaconda/lib/python3.5/site-packages/nbconvert/postprocessors/serve.py", line 19, in <module>
        class ProxyHandler(web.RequestHandler):
      File "/home/rislam/anaconda/lib/python3.5/site-packages/nbconvert/postprocessors/serve.py", line 21, in ProxyHandler
        @web.asynchronous
    AttributeError: module 'tornado.web' has no attribute 'asynchronous'
[I 14:45:45.377 NotebookApp] Serving notebooks from local directory: /home/rislam
[I 14:45:45.378 NotebookApp] The Jupyter Notebook is running at:
[I 14:45:45.378 NotebookApp] http://localhost:2222/?token=1fe8c25833ee10abbba3b8e15476b2c6f6226573029254c8
[I 14:45:45.378 NotebookApp]  or http://127.0.0.1:2222/?token=1fe8c25833ee10abbba3b8e15476b2c6f6226573029254c8
[I 14:45:45.378 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:45:45.394 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/rislam/.local/share/jupyter/runtime/nbserver-433870-open.html
    Or copy and paste one of these URLs:
        http://localhost:2222/?token=1fe8c25833ee10abbba3b8e15476b2c6f6226573029254c8
     or http://127.0.0.1:2222/?token=1fe8c25833ee10abbba3b8e15476b2c6f6226573029254c8
[I 14:47:17.775 NotebookApp] 302 GET / (::1) 1.68ms
[I 14:47:17.807 NotebookApp] 302 GET /tree? (::1) 2.50ms
[I 14:47:37.203 NotebookApp] 302 POST /login?next=%2Ftree%3F (::1) 3.36ms
[E 14:47:37.854 NotebookApp] [nb_conda_kernels] couldn't call conda:
    [Errno 2] No such file or directory: 'conda'
[E 14:47:43.253 NotebookApp] Uncaught exception GET /notebooks/Untitled.ipynb (::1)
    HTTPServerRequest(protocol='http', host='localhost:6969', method='GET', uri='/notebooks/Untitled.ipynb', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/rislam/anaconda/lib/python3.5/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/home/rislam/anaconda/lib/python3.5/asyncio/futures.py", line 363, in __iter__
        return self.result()  # May raise too.
      File "/home/rislam/anaconda/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/home/rislam/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 748, in run
        yielded = self.gen.send(value)
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/notebook/handlers.py", line 101, in get
        get_frontend_exporters=get_frontend_exporters
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/base/handlers.py", line 507, in render_template
        return template.render(**ns)
      File "/home/rislam/anaconda/lib/python3.5/site-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/home/rislam/anaconda/lib/python3.5/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/home/rislam/anaconda/lib/python3.5/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/templates/page.html", line 153, in top-level template code
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/templates/notebook.html", line 114, in block "header"
        {% for exporter in get_frontend_exporters() %}
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/notebook/handlers.py", line 23, in get_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
    ImportError: No module named 'nbconvert.exporters.base'
[E 14:47:43.379 NotebookApp] {
      "Referer": "http://localhost:6969/tree?",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
      "Connection": "keep-alive",
      "Accept-Encoding": "gzip, deflate, br",
      "Cookie": "_xsrf=2|ec2ac7d7|94f2cfe7e02ca9568b811bb7ac648e12|1584383925; username-localhost-7070=\"2|1:0|10:1584384662|23:username-localhost-7070|44:NTczMzE3NTU1OTA1NGZhMTg2YzIwOTM3ZDBhNWQ4N2Y=|a58ae7678fdcb8c9dae06f564c66f32946c9efbe0331a0a81449191cbf0b694c\"; username-localhost-8888=\"2|1:0|10:1584407294|23:username-localhost-8888|44:OTc2ODU4NmRlNWI3NGNhZWFmYzM4ZjVhMjdmMDEwNGY=|fa64414cf32eedd49001bd224695678d4ae264522db8c9ca8c2811dadc107e9f\"; username-localhost-6969=\"2|1:0|10:1584532057|23:username-localhost-6969|44:ZWQzYmE0YzgzZDBjNGZjMjllMjRkMmUzYzZjZmY2NjE=|277bb0be58337b0562e5f9354fab2e056063f50d66c6f887625657128de83249\"",
      "Sec-Fetch-Mode": "navigate",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Sec-Fetch-Dest": "document",
      "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
      "Host": "localhost:6969",
      "Sec-Fetch-User": "?1",
      "Sec-Fetch-Site": "same-origin",
      "Upgrade-Insecure-Requests": "1"
    }
[E 14:47:43.379 NotebookApp] 500 GET /notebooks/Untitled.ipynb (::1) 259.67ms referer=http://localhost:6969/tree?
[E 14:47:46.712 NotebookApp] Uncaught exception GET /notebooks/test.ipynb (::1)
    HTTPServerRequest(protocol='http', host='localhost:6969', method='GET', uri='/notebooks/test.ipynb', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/rislam/anaconda/lib/python3.5/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/home/rislam/anaconda/lib/python3.5/asyncio/futures.py", line 363, in __iter__
        return self.result()  # May raise too.
      File "/home/rislam/anaconda/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/home/rislam/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 748, in run
        yielded = self.gen.send(value)
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/notebook/handlers.py", line 101, in get
        get_frontend_exporters=get_frontend_exporters
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/base/handlers.py", line 507, in render_template
        return template.render(**ns)
      File "/home/rislam/anaconda/lib/python3.5/site-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/home/rislam/anaconda/lib/python3.5/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/home/rislam/anaconda/lib/python3.5/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/templates/page.html", line 153, in top-level template code
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/templates/notebook.html", line 114, in block "header"
        {% for exporter in get_frontend_exporters() %}
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/notebook/handlers.py", line 23, in get_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
    ImportError: No module named 'nbconvert.exporters.base'
[E 14:47:46.715 NotebookApp] {
      "Referer": "http://localhost:6969/tree?",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
      "Connection": "keep-alive",
      "Accept-Encoding": "gzip, deflate, br",
      "Cookie": "_xsrf=2|ec2ac7d7|94f2cfe7e02ca9568b811bb7ac648e12|1584383925; username-localhost-7070=\"2|1:0|10:1584384662|23:username-localhost-7070|44:NTczMzE3NTU1OTA1NGZhMTg2YzIwOTM3ZDBhNWQ4N2Y=|a58ae7678fdcb8c9dae06f564c66f32946c9efbe0331a0a81449191cbf0b694c\"; username-localhost-8888=\"2|1:0|10:1584407294|23:username-localhost-8888|44:OTc2ODU4NmRlNWI3NGNhZWFmYzM4ZjVhMjdmMDEwNGY=|fa64414cf32eedd49001bd224695678d4ae264522db8c9ca8c2811dadc107e9f\"; username-localhost-6969=\"2|1:0|10:1584532057|23:username-localhost-6969|44:ZWQzYmE0YzgzZDBjNGZjMjllMjRkMmUzYzZjZmY2NjE=|277bb0be58337b0562e5f9354fab2e056063f50d66c6f887625657128de83249\"",
      "Sec-Fetch-Mode": "navigate",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Sec-Fetch-Dest": "document",
      "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
      "Host": "localhost:6969",
      "Sec-Fetch-User": "?1",
      "Sec-Fetch-Site": "same-origin",
      "Upgrade-Insecure-Requests": "1"
    }
[E 14:47:46.716 NotebookApp] 500 GET /notebooks/test.ipynb (::1) 9.55ms referer=http://localhost:6969/tree?
[I 14:47:52.941 NotebookApp] Creating new notebook in 
[W 14:47:52.952 NotebookApp] The signatures database cannot be opened; maybe it is corrupted or encrypted. You may need to rerun your notebooks to ensure that they are trusted to run Javascript. The old signatures database has been renamed to /home/rislam/.local/share/jupyter/nbsignatures.db.bak and a new one has been created.
[W 14:47:52.956 NotebookApp] Failed commiting signatures database to disk. You may need to move the database file to a non-networked file system, using config option `NotebookNotary.db_file`. Using in-memory signatures database for the remainder of this session.
[E 14:47:53.032 NotebookApp] Uncaught exception GET /notebooks/Untitled1.ipynb?kernel_name=python3 (::1)
    HTTPServerRequest(protocol='http', host='localhost:6969', method='GET', uri='/notebooks/Untitled1.ipynb?kernel_name=python3', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/rislam/anaconda/lib/python3.5/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/home/rislam/anaconda/lib/python3.5/asyncio/futures.py", line 363, in __iter__
        return self.result()  # May raise too.
      File "/home/rislam/anaconda/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/home/rislam/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 748, in run
        yielded = self.gen.send(value)
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/notebook/handlers.py", line 101, in get
        get_frontend_exporters=get_frontend_exporters
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/base/handlers.py", line 507, in render_template
        return template.render(**ns)
      File "/home/rislam/anaconda/lib/python3.5/site-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/home/rislam/anaconda/lib/python3.5/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/home/rislam/anaconda/lib/python3.5/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/templates/page.html", line 153, in top-level template code
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/templates/notebook.html", line 114, in block "header"
        {% for exporter in get_frontend_exporters() %}
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/notebook/handlers.py", line 23, in get_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
    ImportError: No module named 'nbconvert.exporters.base'
[E 14:47:53.036 NotebookApp] {
      "Referer": "http://localhost:6969/tree?",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
      "Connection": "keep-alive",
      "Accept-Encoding": "gzip, deflate, br",
      "Cookie": "_xsrf=2|ec2ac7d7|94f2cfe7e02ca9568b811bb7ac648e12|1584383925; username-localhost-7070=\"2|1:0|10:1584384662|23:username-localhost-7070|44:NTczMzE3NTU1OTA1NGZhMTg2YzIwOTM3ZDBhNWQ4N2Y=|a58ae7678fdcb8c9dae06f564c66f32946c9efbe0331a0a81449191cbf0b694c\"; username-localhost-8888=\"2|1:0|10:1584407294|23:username-localhost-8888|44:OTc2ODU4NmRlNWI3NGNhZWFmYzM4ZjVhMjdmMDEwNGY=|fa64414cf32eedd49001bd224695678d4ae264522db8c9ca8c2811dadc107e9f\"; username-localhost-6969=\"2|1:0|10:1584532057|23:username-localhost-6969|44:ZWQzYmE0YzgzZDBjNGZjMjllMjRkMmUzYzZjZmY2NjE=|277bb0be58337b0562e5f9354fab2e056063f50d66c6f887625657128de83249\"",
      "Sec-Fetch-Mode": "navigate",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Sec-Fetch-Dest": "document",
      "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
      "Host": "localhost:6969",
      "Sec-Fetch-Site": "same-origin",
      "Upgrade-Insecure-Requests": "1"
    }
[E 14:47:53.037 NotebookApp] 500 GET /notebooks/Untitled1.ipynb?kernel_name=python3 (::1) 10.27ms referer=http://localhost:6969/tree?
[I 14:48:49.392 NotebookApp] 302 GET /tree (::1) 1.84ms
[W 14:48:52.333 NotebookApp] 401 POST /login?next=%2Ftree (::1) 3.83ms referer=http://localhost:6969/login?next=%2Ftree
[I 14:49:25.000 NotebookApp] 302 POST /login?next=%2Ftree (::1) 3.09ms
[E 14:49:25.561 NotebookApp] [nb_conda_kernels] couldn't call conda:
    [Errno 2] No such file or directory: 'conda'
[E 14:49:27.756 NotebookApp] Uncaught exception GET /notebooks/test.ipynb (::1)
    HTTPServerRequest(protocol='http', host='localhost:6969', method='GET', uri='/notebooks/test.ipynb', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/rislam/anaconda/lib/python3.5/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/home/rislam/anaconda/lib/python3.5/asyncio/futures.py", line 363, in __iter__
        return self.result()  # May raise too.
      File "/home/rislam/anaconda/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/home/rislam/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 748, in run
        yielded = self.gen.send(value)
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/notebook/handlers.py", line 101, in get
        get_frontend_exporters=get_frontend_exporters
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/base/handlers.py", line 507, in render_template
        return template.render(**ns)
      File "/home/rislam/anaconda/lib/python3.5/site-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/home/rislam/anaconda/lib/python3.5/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/home/rislam/anaconda/lib/python3.5/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/templates/page.html", line 153, in top-level template code
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/templates/notebook.html", line 114, in block "header"
        {% for exporter in get_frontend_exporters() %}
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/notebook/handlers.py", line 23, in get_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
    ImportError: No module named 'nbconvert.exporters.base'
[E 14:49:27.758 NotebookApp] {
      "Referer": "http://localhost:6969/tree",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "Host": "localhost:6969",
      "Accept-Language": "en-us",
      "Connection": "keep-alive",
      "Accept-Encoding": "gzip, deflate",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15",
      "Cookie": "username-localhost-6969=\"2|1:0|10:1584532164|23:username-localhost-6969|44:Mzg0Yzc5YmUzODNmNDJkNmE4ZDEwYjkxYzZlMGY3MTA=|ee1ac8b8585b4e4e01284e9c248dba311184d0963ace7bc17771aab22886fbd4\"; username-localhost-8888=\"2|1:0|10:1584524755|23:username-localhost-8888|44:NTkwMzJkYjZjNGI1NGNjOGE1OTc3YjNlMDFkMWVlN2U=|7059e21c33852936caa4be59d591a015b2d08afce5eb9d4d3758b5e713515467\"; _xsrf=2|e0550d2c|e0e3732ad8ac3b410e82d5eb63f9f03b|1584116040",
      "Upgrade-Insecure-Requests": "1"
    }
[E 14:49:27.759 NotebookApp] 500 GET /notebooks/test.ipynb (::1) 10.17ms referer=http://localhost:6969/tree
[E 14:53:24.544 NotebookApp] Uncaught exception GET /notebooks/Untitled1.ipynb?kernel_name=python3 (::1)
    HTTPServerRequest(protocol='http', host='localhost:6969', method='GET', uri='/notebooks/Untitled1.ipynb?kernel_name=python3', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/rislam/anaconda/lib/python3.5/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/home/rislam/anaconda/lib/python3.5/asyncio/futures.py", line 363, in __iter__
        return self.result()  # May raise too.
      File "/home/rislam/anaconda/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/home/rislam/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 748, in run
        yielded = self.gen.send(value)
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/notebook/handlers.py", line 101, in get
        get_frontend_exporters=get_frontend_exporters
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/base/handlers.py", line 507, in render_template
        return template.render(**ns)
      File "/home/rislam/anaconda/lib/python3.5/site-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/home/rislam/anaconda/lib/python3.5/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/home/rislam/anaconda/lib/python3.5/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/templates/page.html", line 153, in top-level template code
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/templates/notebook.html", line 114, in block "header"
        {% for exporter in get_frontend_exporters() %}
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/notebook/handlers.py", line 23, in get_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
    ImportError: No module named 'nbconvert.exporters.base'
[E 14:53:24.547 NotebookApp] {
      "Accept-Encoding": "gzip, deflate, br",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36",
      "Connection": "keep-alive",
      "Cache-Control": "max-age=0",
      "Cookie": "_xsrf=2|ec2ac7d7|94f2cfe7e02ca9568b811bb7ac648e12|1584383925; username-localhost-7070=\"2|1:0|10:1584384662|23:username-localhost-7070|44:NTczMzE3NTU1OTA1NGZhMTg2YzIwOTM3ZDBhNWQ4N2Y=|a58ae7678fdcb8c9dae06f564c66f32946c9efbe0331a0a81449191cbf0b694c\"; username-localhost-8888=\"2|1:0|10:1584407294|23:username-localhost-8888|44:OTc2ODU4NmRlNWI3NGNhZWFmYzM4ZjVhMjdmMDEwNGY=|fa64414cf32eedd49001bd224695678d4ae264522db8c9ca8c2811dadc107e9f\"; username-localhost-6969=\"2|1:0|10:1584532057|23:username-localhost-6969|44:ZWQzYmE0YzgzZDBjNGZjMjllMjRkMmUzYzZjZmY2NjE=|277bb0be58337b0562e5f9354fab2e056063f50d66c6f887625657128de83249\"",
      "Sec-Fetch-Mode": "navigate",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Sec-Fetch-Dest": "document",
      "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
      "Host": "localhost:6969",
      "Sec-Fetch-User": "?1",
      "Sec-Fetch-Site": "none",
      "Upgrade-Insecure-Requests": "1"
    }
[E 14:53:24.547 NotebookApp] 500 GET /notebooks/Untitled1.ipynb?kernel_name=python3 (::1) 8.56ms referer=None
[E 14:54:54.789 NotebookApp] Uncaught exception GET /notebooks/Untitled1.ipynb (::1)
    HTTPServerRequest(protocol='http', host='localhost:6969', method='GET', uri='/notebooks/Untitled1.ipynb', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/home/rislam/anaconda/lib/python3.5/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/home/rislam/anaconda/lib/python3.5/asyncio/futures.py", line 363, in __iter__
        return self.result()  # May raise too.
      File "/home/rislam/anaconda/lib/python3.5/asyncio/futures.py", line 274, in result
        raise self._exception
      File "/home/rislam/anaconda/lib/python3.5/site-packages/tornado/gen.py", line 748, in run
        yielded = self.gen.send(value)
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/notebook/handlers.py", line 101, in get
        get_frontend_exporters=get_frontend_exporters
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/base/handlers.py", line 507, in render_template
        return template.render(**ns)
      File "/home/rislam/anaconda/lib/python3.5/site-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/home/rislam/anaconda/lib/python3.5/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/home/rislam/anaconda/lib/python3.5/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/templates/page.html", line 153, in top-level template code
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/templates/notebook.html", line 114, in block "header"
        {% for exporter in get_frontend_exporters() %}
      File "/home/rislam/anaconda/lib/python3.5/site-packages/notebook/notebook/handlers.py", line 23, in get_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
    ImportError: No module named 'nbconvert.exporters.base'
[E 14:54:54.792 NotebookApp] {
      "Referer": "http://localhost:6969/tree",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "Host": "localhost:6969",
      "Accept-Language": "en-us",
      "Connection": "keep-alive",
      "Accept-Encoding": "gzip, deflate",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15",
      "Cookie": "username-localhost-6969=\"2|1:0|10:1584532164|23:username-localhost-6969|44:Mzg0Yzc5YmUzODNmNDJkNmE4ZDEwYjkxYzZlMGY3MTA=|ee1ac8b8585b4e4e01284e9c248dba311184d0963ace7bc17771aab22886fbd4\"; username-localhost-8888=\"2|1:0|10:1584524755|23:username-localhost-8888|44:NTkwMzJkYjZjNGI1NGNjOGE1OTc3YjNlMDFkMWVlN2U=|7059e21c33852936caa4be59d591a015b2d08afce5eb9d4d3758b5e713515467\"; _xsrf=2|e0550d2c|e0e3732ad8ac3b410e82d5eb63f9f03b|1584116040",
      "Upgrade-Insecure-Requests": "1"
    }
[E 14:54:54.792 NotebookApp] 500 GET /notebooks/Untitled1.ipynb (::1) 9.97ms referer=http://localhost:6969/tree
[E 14:55:37.861 NotebookApp] [nb_conda_kernels] couldn't call conda:
    [Errno 2] No such file or directory: 'conda'`
```

**Comment by kevin-bates** [comment]
There are some issues in the output that imply some upgrade and configuration "adjustments" are in order.

These issues...
```
ImportError: No module named 'nbconvert.exporters.base'
```
```
File "/home/rislam/anaconda/lib/python3.5/site-packages/nbconvert/postprocessors/serve.py", line 21, in ProxyHandler
  @web.asynchronous
AttributeError: module 'tornado.web' has no attribute 'asynchronous'
```
imply that your `nbconvert` is out of date and should be updated.  Given its age, I would recommend updating `notebook` as well.

This issue...
```
[E 14:47:37.854 NotebookApp] [nb_conda_kernels] couldn't call conda:
    [Errno 2] No such file or directory: 'conda'
```
indicates a failure to locate your `conda` command - which `nb_conda_kernels` requires so it can discover available kernels.  This may be as simple as adjusting your PATH, but if `conda` isn't found anywhere, then parts of your configuration have been corrupted and you might be better off updating conda.  (Not sure if there's a specific "fix me" command or not, but if 'conda' isn't available, you might need to uninstall/reinstall.)
