### ISSUE TITLE
Kernel not connecting

### ISSUE THREAD

**Issue by staffin-7** [jupyter/notebook#5298]
Iam trying to sort out Connection issue for a while in anaconda. Tried reinstalling anaconda several times and also created new environment. Everything was fine and all of a sudden this started.. 
I installed Ubuntu in virtual box and anaconda in that. It worked fine there, I am experiencing this issue in windows. When I execute jupyter notebook command in command prompt I am getting this:

(base) C:\Users\staff>jupyter-notebook
[I 21:42:56.243 NotebookApp] The port 8888 is already in use, trying another port.
[I 21:42:56.243 NotebookApp] The port 8889 is already in use, trying another port.
[I 21:42:56.259 NotebookApp] The port 8890 is already in use, trying another port.
[I 21:42:56.308 NotebookApp] JupyterLab extension loaded from C:\Users\staff\Anaconda3\lib\site-packages\jupyterlab
[I 21:42:56.308 NotebookApp] JupyterLab application directory is C:\Users\staff\Anaconda3\share\jupyter\lab
[I 21:42:56.308 NotebookApp] Serving notebooks from local directory: C:\Users\staff
[I 21:42:56.308 NotebookApp] The Jupyter Notebook is running at:
[I 21:42:56.308 NotebookApp] http://localhost:8891/?token=3ed8c9e7f8d2507ea67067c3d21adb6b06a7956f629fbc90
[I 21:42:56.308 NotebookApp]  or http://127.0.0.1:8891/?token=3ed8c9e7f8d2507ea67067c3d21adb6b06a7956f629fbc90
[I 21:42:56.308 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 21:42:56.387 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/staff/AppData/Roaming/jupyter/runtime/nbserver-12824-open.html
    Or copy and paste one of these URLs:
        http://localhost:8891/?token=3ed8c9e7f8d2507ea67067c3d21adb6b06a7956f629fbc90
     or http://127.0.0.1:8891/?token=3ed8c9e7f8d2507ea67067c3d21adb6b06a7956f629fbc90
```This is the error shown in anaconda.

[I 21:45:21.326 NotebookApp] The port 8888 is already in use, trying another port.
[I 21:45:21.327 NotebookApp] The port 8889 is already in use, trying another port.
[I 21:45:21.328 NotebookApp] The port 8890 is already in use, trying another port.
[I 21:45:21.388 NotebookApp] JupyterLab extension loaded from C:\Users\staff\Anaconda3\lib\site-packages\jupyterlab
[I 21:45:21.388 NotebookApp] JupyterLab application directory is C:\Users\staff\Anaconda3\share\jupyter\lab
[I 21:45:21.391 NotebookApp] Serving notebooks from local directory: C:\Users\staff
[I 21:45:21.391 NotebookApp] The Jupyter Notebook is running at:
[I 21:45:21.392 NotebookApp] http://localhost:8891/?token=72bae206b616b256d602392ca779f2725f96e7ebdbad62c7
[I 21:45:21.392 NotebookApp] or http://127.0.0.1:8891/?token=72bae206b616b256d602392ca779f2725f96e7ebdbad62c7
[I 21:45:21.392 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 21:45:21.472 NotebookApp] 

To access the notebook, open this file in a browser:
file:///C:/Users/staff/AppData/Roaming/jupyter/runtime/nbserver-8428-open.html
Or copy and paste one of these URLs:
http://localhost:8891/?token=72bae206b616b256d602392ca779f2725f96e7ebdbad62c7
or http://127.0.0.1:8891/?token=72bae206b616b256d602392ca779f2725f96e7ebdbad62c7
[I 21:45:30.301 NotebookApp] Creating new notebook in 
[I 21:45:31.617 NotebookApp] Kernel started: 9cb454bc-8384-4290-95e2-cfe8dedce7b0
Traceback (most recent call last):
File "C:\Users\staff\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\Users\staff\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\staff\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 15, in 
from ipykernel import kernelapp as app
File "C:\Users\staff\Anaconda3\lib\site-packages\ipykernel\__init__.py", line 2, in 
from .connect import *
File "C:\Users\staff\Anaconda3\lib\site-packages\ipykernel\connect.py", line 13, in 
from IPython.core.profiledir import ProfileDir
File "C:\Users\staff\Anaconda3\lib\site-packages\IPython\__init__.py", line 54, in 
from .core.application import Application
File "C:\Users\staff\Anaconda3\lib\site-packages\IPython\core\application.py", line 25, in 
from IPython.core import release, crashhandler
File "C:\Users\staff\Anaconda3\lib\site-packages\IPython\core\crashhandler.py", line 27, in 
from IPython.core import ultratb
File "C:\Users\staff\Anaconda3\lib\site-packages\IPython\core\ultratb.py", line 115, in 
from IPython.core import debugger
File "C:\Users\staff\Anaconda3\lib\site-packages\IPython\core\debugger.py", line 47, in 
from pdb import Pdb as OldPdb
File "C:\Users\staff\Anaconda3\lib\pdb.py", line 76, in 
import code
File "C:\Users\staff\code.py", line 5
from cryptography.hazmat.backends import 
^
SyntaxError: invalid syntax

**Comment by staffin-7** [comment]
Issue resolved. removed code.py from "C:\Users\staff\code.py"
