### ISSUE TITLE
Connection to the Jupyter server could not be established

### ISSUE THREAD

**Issue by acobb83** [jupyter/notebook#5332]
I've tried uninstalling Anaconda and reinstalling, even deprecating versions of Tornado packages. But whenever I load jupyter lab I just get a continuous loop of shell pasted below and the browser saying it can't find a connection.

Server Connection Error: A connection to the Jupyter server could not be established. JupyterLab will continue trying to reconnect. Check your network connection or Jupyter server configuration. 

![image](https://user-images.githubusercontent.com/40008673/78423579-ecf5a800-76b2-11ea-9141-e67d482560f8.png)

(base) C:\Users\usrnme_>jupyter lab
[W 20:21:57.908 LabApp] JupyterLab server extension not enabled, manually loading...
[I 20:21:57.955 LabApp] JupyterLab extension loaded from C:\Users\usrnme_\anaconda3\lib\site-packages\jupyterlab
[I 20:21:57.955 LabApp] JupyterLab application directory is C:\Users\usrnme_\anaconda3\share\jupyter\lab
[I 20:21:58.330 LabApp] Serving notebooks from local directory: C:\Users\usrnme_
[I 20:21:58.330 LabApp] 0 active kernels
[I 20:21:58.330 LabApp] The Jupyter Notebook is running at:
[I 20:21:58.330 LabApp] http://localhost:8888/?token=c46951eac7d35c3b9a5729fe3c251ae012266e64931e5137
[I 20:21:58.330 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 20:21:58.424 LabApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=c46951eac7d35c3b9a5729fe3c251ae012266e64931e5137
[W 20:21:58.455 LabApp] 404 GET /api/kernels/ad8301fd-25b0-4c36-8356-466e929954ab/channels?session_id=0889f61e-cded-486f-934f-6b98a5cc26fa&token=e89f847ab04d63a526a41bd19bd163a5d970caa206d47f79 (::1): Kernel does not exist: ad8301fd-25b0-4c36-8356-466e929954ab
[W 20:21:58.533 LabApp] 404 GET /api/kernels/ad8301fd-25b0-4c36-8356-466e929954ab/channels?session_id=0889f61e-cded-486f-934f-6b98a5cc26fa&token=e89f847ab04d63a526a41bd19bd163a5d970caa206d47f79 (::1) 109.35ms referer=None
[I 20:21:58.986 LabApp] Accepting one-time-token-authenticated connection from ::1
[W 20:21:59.658 LabApp] 404 GET /api/kernels/ad8301fd-25b0-4c36-8356-466e929954ab/channels?session_id=3278b42d-ec7e-4832-8fa1-3d8d7cba8170&token=e89f847ab04d63a526a41bd19bd163a5d970caa206d47f79 (::1): Kernel does not exist: ad8301fd-25b0-4c36-8356-466e929954ab
[W 20:21:59.658 LabApp] 404 GET /api/kernels/ad8301fd-25b0-4c36-8356-466e929954ab/channels?session_id=3278b42d-ec7e-4832-8fa1-3d8d7cba8170&token=e89f847ab04d63a526a41bd19bd163a5d970caa206d47f79 (::1) 0.00ms referer=None
[I 20:21:59.892 LabApp] 301 GET /lab/workspaces/auto-L/?clone (::1) 0.00ms
[W 20:21:59.892 LabApp] 404 GET /metrics?1585992119901 (::1) 0.00ms referer=http://localhost:8888/lab/workspaces/auto-L/?clone
[W 20:22:01.256 LabApp] Could not determine jupyterlab build status without nodejs
[W 20:22:01.272 LabApp] 404 GET /metrics?1585992121064 (::1) 3.99ms referer=http://localhost:8888/lab/workspaces/auto-L?clone
[W 20:22:01.436 LabApp] 404 GET /api/kernels/ad8301fd-25b0-4c36-8356-466e929954ab/channels?session_id=8ca54ec6-e4e0-484d-a9eb-05e81c30e61a&token=e89f847ab04d63a526a41bd19bd163a5d970caa206d47f79 (::1): Kernel does not exist: ad8301fd-25b0-4c36-8356-466e929954ab
[W 20:22:01.438 LabApp] 404 GET /api/kernels/ad8301fd-25b0-4c36-8356-466e929954ab/channels?session_id=8ca54ec6-e4e0-484d-a9eb-05e81c30e61a&token=e89f847ab04d63a526a41bd19bd163a5d970caa206d47f79 (::1) 4.99ms referer=None
[I 20:22:02.562 LabApp] Kernel started: ba44e1b4-0803-48a6-b5d9-3acad8c3cc26
[W 20:22:03.933 LabApp] 404 GET /api/kernels/ad8301fd-25b0-4c36-8356-466e929954ab/channels?session_id=436d7caf-22de-4855-b354-14462b9deb57&token=e89f847ab04d63a526a41bd19bd163a5d970caa206d47f79 (::1): Kernel does not exist: ad8301fd-25b0-4c36-8356-466e929954ab
[W 20:22:03.935 LabApp] 404 GET /api/kernels/ad8301fd-25b0-4c36-8356-466e929954ab/channels?session_id=436d7caf-22de-4855-b354-14462b9deb57&token=e89f847ab04d63a526a41bd19bd163a5d970caa206d47f79 (::1) 3.99ms referer=None
Traceback (most recent call last):
  File "C:\Users\usrnme_\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\usrnme_\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\usrnme_\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\usrnme_\anaconda3\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\Users\usrnme_\AppData\Roaming\Python\Python37\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "C:\Users\usrnme_\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\usrnme_\anaconda3\lib\asyncio\base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
[I 20:22:05.548 LabApp] KernelRestarter: restarting kernel (1/5), new random ports
[W 20:22:06.330 LabApp] 404 GET /metrics?1585992126325 (::1) 2.00ms referer=http://localhost:8888/lab/workspaces/auto-L
Traceback (most recent call last):
  File "C:\Users\usrnme_\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\usrnme_\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\usrnme_\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\usrnme_\anaconda3\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\Users\usrnme_\AppData\Roaming\Python\Python37\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "C:\Users\usrnme_\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\usrnme_\anaconda3\lib\asyncio\base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
[W 20:22:07.674 LabApp] 404 GET /api/kernels/ad8301fd-25b0-4c36-8356-466e929954ab/channels?session_id=92ce3254-fd67-4de9-9179-4175d50d19b8&token=e89f847ab04d63a526a41bd19bd163a5d970caa206d47f79 (::1): Kernel does not exist: ad8301fd-25b0-4c36-8356-466e929954ab
[W 20:22:07.690 LabApp] 404 GET /api/kernels/ad8301fd-25b0-4c36-8356-466e929954ab/channels?session_id=92ce3254-fd67-4de9-9179-4175d50d19b8&token=e89f847ab04d63a526a41bd19bd163a5d970caa206d47f79 (::1) 15.62ms referer=None
[I 20:22:08.564 LabApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "C:\Users\usrnme_\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\usrnme_\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\usrnme_\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\usrnme_\anaconda3\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\Users\usrnme_\AppData\Roaming\Python\Python37\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "C:\Users\usrnme_\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\usrnme_\anaconda3\lib\asyncio\base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
[W 20:22:11.366 LabApp] 404 GET /metrics?1585992131337 (::1) 15.62ms referer=http://localhost:8888/lab/workspaces/auto-L
[I 20:22:11.569 LabApp] KernelRestarter: restarting kernel (3/5), new random ports
[W 20:22:13.303 LabApp] 404 GET /api/kernels/ad8301fd-25b0-4c36-8356-466e929954ab/channels?session_id=996f1aa9-3551-417e-8d85-593cc9fbf064&token=e89f847ab04d63a526a41bd19bd163a5d970caa206d47f79 (::1): Kernel does not exist: ad8301fd-25b0-4c36-8356-466e929954ab
[W 20:22:13.303 LabApp] 404 GET /api/kernels/ad8301fd-25b0-4c36-8356-466e929954ab/channels?session_id=996f1aa9-3551-417e-8d85-593cc9fbf064&token=e89f847ab04d63a526a41bd19bd163a5d970caa206d47f79 (::1) 0.00ms referer=None
Traceback (most recent call last):
  File "C:\Users\usrnme_\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\usrnme_\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\usrnme_\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\usrnme_\anaconda3\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\Users\usrnme_\AppData\Roaming\Python\Python37\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "C:\Users\usrnme_\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\usrnme_\anaconda3\lib\asyncio\base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
[I 20:22:14.580 LabApp] KernelRestarter: restarting kernel (4/5), new random ports
[W 20:22:16.376 LabApp] 404 GET /metrics?1585992136378 (::1) 0.00ms referer=http://localhost:8888/lab/workspaces/auto-L
Traceback (most recent call last):
  File "C:\Users\usrnme_\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\usrnme_\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\usrnme_\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\usrnme_\anaconda3\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\Users\usrnme_\AppData\Roaming\Python\Python37\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "C:\Users\usrnme_\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\usrnme_\anaconda3\lib\asyncio\base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
[I 20:22:20.591 LabApp] KernelRestarter: restarting kernel (1/5), keep random ports
[W 20:22:21.388 LabApp] 404 GET /metrics?1585992141389 (::1) 0.00ms referer=http://localhost:8888/lab/workspaces/auto-L
[W 20:22:21.716 LabApp] 404 GET /api/kernels/ad8301fd-25b0-4c36-8356-466e929954ab/channels?session_id=82eadd1b-2825-4abd-bd68-9ecd50fc0351&token=e89f847ab04d63a526a41bd19bd163a5d970caa206d47f79 (::1): Kernel does not exist: ad8301fd-25b0-4c36-8356-466e929954ab
[W 20:22:21.716 LabApp] 404 GET /api/kernels/ad8301fd-25b0-4c36-8356-466e929954ab/channels?session_id=82eadd1b-2825-4abd-bd68-9ecd50fc0351&token=e89f847ab04d63a526a41bd19bd163a5d970caa206d47f79 (::1) 0.00ms referer=None
Traceback (most recent call last):
  File "C:\Users\usrnme_\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\usrnme_\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\usrnme_\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\usrnme_\anaconda3\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\Users\usrnme_\AppData\Roaming\Python\Python37\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "C:\Users\usrnme_\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\usrnme_\anaconda3\lib\asyncio\base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
[I 20:22:23.591 LabApp] KernelRestarter: restarting kernel (2/5), keep random ports
Traceback (most recent call last):
  File "C:\Users\usrnme_\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\usrnme_\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\usrnme_\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\usrnme_\anaconda3\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\Users\usrnme_\AppData\Roaming\Python\Python37\site-packages\ipykernel\kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "C:\Users\usrnme_\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\usrnme_\anaconda3\lib\asyncio\base_events.py", line 525, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
[W 20:22:26.405 LabApp] 404 GET /metrics?1585992146412 (::1) 0.00ms referer=http://localhost:8888/lab/workspaces/auto-L
[I 20:22:26.593 LabApp] KernelRestarter: restarting kernel (3/5), keep random ports
[W 20:22:31.436 LabApp] 404 GET /metrics?1585992151436 (::1) 0.00ms referer=http://localhost:8888/lab/workspaces/auto-L
[W 20:22:34.333 LabApp] 404 GET /api/kernels/ad8301fd-25b0-4c36-8356-466e929954ab/channels?session_id=4254d7a0-ffca-455e-8d0d-152cc6625b5a&token=e89f847ab04d63a526a41bd19bd163a5d970caa206d47f79 (::1): Kernel does not exist: ad8301fd-25b0-4c36-8356-466e929954ab
[W 20:22:34.333 LabApp] 404 GET /api/kernels/ad8301fd-25b0-4c36-8356-466e929954ab/channels?session_id=4254d7a0-ffca-455e-8d0d-152cc6625b5a&token=e89f847ab04d63a526a41bd19bd163a5d970caa206d47f79 (::1) 0.00ms referer=None
[W 20:22:36.536 LabApp] 404 GET /metrics?1585992156500 (::1) 0.00ms referer=http://localhost:8888/lab/workspaces/auto-L
[W 20:22:41.554 LabApp] 404 GET /metrics?1585992161555 (::1) 0.00ms referer=http://localhost:8888/lab/workspaces/auto-L
[W 20:22:46.569 LabApp] 404 GET /metrics?1585992166570 (::1) 0.00ms referer=http://localhost:8888/lab/workspaces/auto-L
[W 20:22:51.586 LabApp] 404 GET /metrics?1585992171587 (::1) 0.00ms referer=http://localhost:8888/lab/workspaces/auto-L
[W 20:22:53.254 LabApp] 404 GET /api/kernels/ad8301fd-25b0-4c36-8356-466e929954ab/channels?session_id=7cede435-6dd1-4be5-9e8e-983e255bb3e9&token=e89f847ab04d63a526a41bd19bd163a5d970caa206d47f79 (::1): Kernel does not exist: ad8301fd-25b0-4c36-8356-466e929954ab
[W 20:22:53.254 LabApp] 404 GET /api/kernels/ad8301fd-25b0-4c36-8356-466e929954ab/channels?session_id=7cede435-6dd1-4be5-9e8e-983e255bb3e9&token=e89f847ab04d63a526a41bd19bd163a5d970caa206d47f79 (::1) 0.00ms referer=None
[W 20:22:56.610 LabApp] 404 GET /metrics?1585992176611 (::1) 0.00ms referer=http://localhost:8888/lab/workspaces/auto-L
[W 20:23:01.625 LabApp] 404 GET /metrics?1585992181625 (::1) 0.00ms referer=http://localhost:8888/lab/workspaces/auto-L
[W 20:23:06.646 LabApp] 404 GET /metrics?1585992186647 (::1) 0.00ms referer=http://localhost:8888/lab/workspaces/auto-L
[W 20:23:11.662 LabApp] 404 GET /metrics?1585992191664 (::1) 0.00ms referer=http://localhost:8888/lab/workspaces/auto-L
[W 20:23:16.690 LabApp] 404 GET /metrics?1585992196692 (::1) 0.00ms referer=http://localhost:8888/lab/workspaces/auto-L
[W 20:23:21.630 LabApp] 404 GET /api/kernels/ad8301fd-25b0-4c36-8356-466e929954ab/channels?session_id=8667adc9-ba01-4778-9d9c-a487370ea003&token=e89f847ab04d63a526a41bd19bd163a5d970caa206d47f79 (::1): Kernel does not exist: ad8301fd-25b0-4c36-8356-466e929954ab
[W 20:23:21.630 LabApp] 404 GET /api/kernels/ad8301fd-25b0-4c36-8356-466e929954ab/channels?session_id=8667adc9-ba01-4778-9d9c-a487370ea003&token=e89f847ab04d63a526a41bd19bd163a5d970caa206d47f79 (::1) 0.00ms referer=None
[W 20:23:21.708 LabApp] 404 GET /metrics?1585992201709 (::1) 0.00ms referer=http://localhost:8888/lab/workspaces/auto-L
[W 20:23:26.727 LabApp] 404 GET /metrics?1585992206728 (::1) 0.00ms referer=http://localhost:8888/lab/workspaces/auto-L
[W 20:23:31.739 LabApp] 404 GET /metrics?1585992211740 (::1) 0.00ms referer=http://localhost:8888/lab/workspaces/auto-L

**Comment by nitishdhar** [comment]
Hi, Was this issue resolved for you?
