### ISSUE TITLE
Import error causing a "500 internal server error"

### ISSUE THREAD

**Issue by rodlpho** [jupyter/notebook#5346]
Hello,

**NOTE**: At the end of this issue I describe how I fix it, but I don't know if it was the right way.

I'm trying to run a command 

> manage shell_plus --notebook

using django-extensions

So I have a lot of errors trying to run Jupyter notebook inside my pyenv

Analyzing the output error from my Pycharm I had:

```
(.wttd) prog@prog-note:~/wttd$ 
(.wttd) prog@prog-note:~/wttd$ manage shell_plus --notebook
[I 01:03:13.350 NotebookApp] Loading IPython parallel extension
[I 01:03:13.366 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.4.1
[I 01:03:13.476 NotebookApp] [Jupytext Server Extension] Deriving a JupytextContentsManager from LargeFileManager
[I 01:03:13.481 NotebookApp] Serving notebooks from local directory: /home/prog/wttd
[I 01:03:13.482 NotebookApp] The Jupyter Notebook is running at:
[I 01:03:13.482 NotebookApp] http://localhost:8888/?token=af0799ce3ec853ddd3fac591e17ca11fac3590924524999d
[I 01:03:13.482 NotebookApp]  or http://127.0.0.1:8888/?token=af0799ce3ec853ddd3fac591e17ca11fac3590924524999d
[I 01:03:13.482 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 01:03:13.501 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/prog/.local/share/jupyter/runtime/nbserver-10700-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=af0799ce3ec853ddd3fac591e17ca11fac3590924524999d
     or http://127.0.0.1:8888/?token=af0799ce3ec853ddd3fac591e17ca11fac3590924524999d
[W 01:03:16.255 NotebookApp] 404 GET /api/kernels/2bb339a7-7bd1-49d4-b39a-f49e5011081f/channels?session_id=a379cae3e4b84acb8bd398d8b0396b1a (127.0.0.1): Kernel does not exist: 2bb339a7-7bd1-49d4-b39a-f49e5011081f
[W 01:03:16.275 NotebookApp] 404 GET /api/kernels/2bb339a7-7bd1-49d4-b39a-f49e5011081f/channels?session_id=a379cae3e4b84acb8bd398d8b0396b1a (127.0.0.1) 24.62ms referer=None
[I 01:03:18.488 NotebookApp] Creating new notebook in 
[I 01:03:18.489 NotebookApp] Saving Untitled3.ipynb
[E 01:03:18.585 NotebookApp] Uncaught exception GET /notebooks/Untitled3.ipynb?kernel_name=django_extensions (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/notebooks/Untitled3.ipynb?kernel_name=django_extensions', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/prog/wttd/.wttd/lib/python3.9/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/home/prog/wttd/.wttd/lib/python3.9/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/home/prog/wttd/.wttd/lib/python3.9/site-packages/tornado/gen.py", line 1147, in run
        yielded = self.gen.send(value)
      File "/home/prog/wttd/.wttd/lib/python3.9/site-packages/notebook/notebook/handlers.py", line 95, in get
        self.write(self.render_template('notebook.html',
      File "/home/prog/wttd/.wttd/lib/python3.9/site-packages/notebook/base/handlers.py", line 507, in render_template
        return template.render(**ns)
      File "/home/prog/wttd/.wttd/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/home/prog/wttd/.wttd/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/home/prog/wttd/.wttd/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "/home/prog/wttd/.wttd/lib/python3.9/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/home/prog/wttd/.wttd/lib/python3.9/site-packages/notebook/templates/page.html", line 153, in top-level template code
      File "/home/prog/wttd/.wttd/lib/python3.9/site-packages/notebook/templates/notebook.html", line 114, in block "header"
        {% for exporter in get_frontend_exporters() %}
      File "/home/prog/wttd/.wttd/lib/python3.9/site-packages/notebook/notebook/handlers.py", line 23, in get_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
      File "/home/prog/wttd/.wttd/lib/python3.9/site-packages/nbconvert/__init__.py", line 4, in <module>
        from .exporters import *
      File "/home/prog/wttd/.wttd/lib/python3.9/site-packages/nbconvert/exporters/__init__.py", line 3, in <module>
        from .html import HTMLExporter
      File "/home/prog/wttd/.wttd/lib/python3.9/site-packages/nbconvert/exporters/html.py", line 14, in <module>
        from nbconvert.filters.highlight import Highlight2HTML
      File "/home/prog/wttd/.wttd/lib/python3.9/site-packages/nbconvert/filters/__init__.py", line 7, in <module>
        from .strings import *
      File "/home/prog/wttd/.wttd/lib/python3.9/site-packages/nbconvert/filters/strings.py", line 22, in <module>
        from defusedxml import cElementTree as ElementTree
      File "/home/prog/wttd/.wttd/lib/python3.9/site-packages/defusedxml/cElementTree.py", line 10, in <module>
        from xml.etree.cElementTree import TreeBuilder as _TreeBuilder
    ModuleNotFoundError: No module named 'xml.etree.cElementTree'
[E 01:03:18.588 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36",
      "Sec-Fetch-Dest": "document",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "navigate",
      "Referer": "http://localhost:8888/tree",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7",
      "Cookie": "_xsrf=2|7a535793|0a939ec317143663c74dda6ea09fde48|1586280953; username-localhost-8889=\"2|1:0|10:1586305830|23:username-localhost-8889|44:YjA0NjY1N2VkOTI1NGRiOWEyMWZiYzNjM2U5NjY0ZTY=|e272e01ddcf997c5d243b742a0a1814d9135d31cfcdb25ce70254482aab465cd\"; username-localhost-8888=\"2|1:0|10:1586307794|23:username-localhost-8888|44:NWY2MDIyMmVjNzEwNDczNmIzYWRhOGY2OWIzZDEyNmE=|76ac9ce110e4f61a740ea99f6fc24f876423781ad2c144263a3cc7ca44c79c56\""
    }
[E 01:03:18.588 NotebookApp] 500 GET /notebooks/Untitled3.ipynb?kernel_name=django_extensions (127.0.0.1) 76.16ms referer=http://localhost:8888/tree
[W 01:03:25.254 NotebookApp] Replacing stale connection: 2bb339a7-7bd1-49d4-b39a-f49e5011081f:a379cae3e4b84acb8bd398d8b0396b1a


```
I changed 2 files and fixed this. So now I'm able to run inside my env:

> manage shell_plus --notebook

And on the browser, click -> New -> Django Shell Plus --- now I do not have error 500

### **the files that I changed were:**
**cElementTree.py and strings.py**

changing all imports:

>from xml.etree.cElementTree ....

To:
>from xml.etree.ElementTree ....

Removing the "c" before Element.

Please let me know if I can help more, or it was unnecessary :)
Thanks!

**Comment by rodlpho** [comment]
I think the issue is with my environment.

I'm using with Django and Django extensions together with alias "manage", and I will check better this case, maybe I need to reinnstall to get  cElement.
Thanks
