### ISSUE TITLE
Jupyter Notebook Error after Anaconda Reinstall (macOS Catalina)

### ISSUE THREAD

**Issue by sunayhpoole** [jupyter/notebook#5367]
Hi everyone!
I had to reinstall Anaconda a few days ago due to another issue, but when I reinstalled it, I stopped being able to run the jupyter notebook command from my terminal. I've since then uninstalled and reinstalled Anaconda a few times, but the same error appears:

(base) Sunays-Air:~ Sunay$ jupyter-notebook
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/usr/local/lib/python3.7/site-packages/notebook/notebookapp.py", line 62, in <module>
    from tornado import httpserver
  File "/usr/local/lib/python3.7/site-packages/tornado/httpserver.py", line 29, in <module>
    import ssl
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: dlopen(/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/lib-dynload/_ssl.cpython-37m-darwin.so
  Reason: image not found

I'm thinking it has something to do with my PATHs, but I don't know how to fix this or how to even figure out which PATH I need to add. Any help would be much appreciated!

**Comment by kevin-bates** [comment]
Hi @sunayhpoole - it seems like your OpenSSL installation got side-affected somehow.  I have found a few instances of this in other unrelated repos and all seem to point to reinstalling or updating OpenSSL.

Two of the repos are:  https://github.com/oracle/oci-cli (issue 226) and https://github.com/kelaberetiv/TagUI (issue 86)
Here's an SO hit as well: https://stackoverflow.com/questions/44125147/dyld-library-not-loaded-usr-local-opt-openssl-lib-libcrypto-1-0-0-dylib

You might first try updating your tornado package - since that's where this reference is coming from (indirectly).
