### ISSUE TITLE
Jupyter-Kernal Error (Python 3.7)

### ISSUE THREAD

**Issue by DSKaarthick** [jupyter/notebook#5371]
Hi All,

I have installed Python 3.7 through the  "Anaconda3-2020.02-Windows-x86_64" and
when i try to open Jupyter Notebook  i am getting "Kernal Error".

I uninstalled and reinstalled but still its not working and same issue.

![image](https://user-images.githubusercontent.com/63085392/79149729-36e23a80-7de5-11ea-85b0-d60048485e20.png)

Error Message:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\tornado\web.py", line 1703, in _execute
    result = await result
  File "C:\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 158, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 305, in start_kernel
    self.kernel = self._launch_kernel(kernel_cmd, **kw)
  File "C:\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 212, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Anaconda3\lib\site-packages\jupyter_client\launcher.py", line 135, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Anaconda3\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Anaconda3\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by kevin-bates** [comment]
This indicates that the file corresponding to the process that is being launched cannot be found.  I suspect something is amiss with the `argv` stanza of your kernel's `kernel.json` file.

Please run `jupyter kernelspec list` and identify the kernel you're using.  Go to the corresponding directory and verify if the first element of the `argv` array is valid and adjust accordingly.  This is most likely the path to `python` and the value might not be correct for the Windows platform.  If it shows python in the `bin` directory and it isn't in your `bin` directory or has a `.exe` extension update that argument.  On Windows you might find `python` located in the sibling `Scripts` directory.

**Comment by DSKaarthick** [comment]
Thanks a lot!!!  

The kernel.json file , the argv was pointing to some other location where python.exe was not there.
and changed as per your suggestion.

Now its working..

Thanks Kevin!!!

**Comment by kevin-bates** [comment]
This is great news @DSKaarthick - thanks for the update.

Would you mind sharing whether the issue was `bin` vs. `Scripts` or an entirely different directory path was found?  If entirely different, was the actual value from a previous env or something like that?  That is, once you saw the value, things started making sense due to other changes in the configuration?

Just hoping this extra level of detail may help others solve related issues.  Thank you.
