### ISSUE TITLE
Unable to launch Jupyter notebook from Anaconda Navigator

### ISSUE THREAD

**Issue by Ajith8** [jupyter/notebook#5390]
Traceback (most recent call last):
File "C:\Users\Harish\anaconda3\Scripts\jupyter-notebook-script.py", line 6, in 
from notebook.notebookapp import main
File "C:\Users\Harish\anaconda3\lib\site-packages\notebook\notebookapp.py", line 80, in 
from .services.contents.manager import ContentsManager
File "C:\Users\Harish\anaconda3\lib\site-packages\notebook\services\contents\manager.py", line 17, in 
from nbformat import sign, validate as validate_nb, ValidationError
File "C:\Users\Harish\anaconda3\lib\site-packages\nbformat\__init__.py", line 32, in 
from .validator import validate, ValidationError
File "C:\Users\Harish\anaconda3\lib\site-packages\nbformat\validator.py", line 12, in 
from jsonschema import ValidationError
File "C:\Users\Harish\anaconda3\lib\site-packages\jsonschema\__init__.py", line 11, in 
from jsonschema.exceptions import (
File "C:\Users\Harish\anaconda3\lib\site-packages\jsonschema\exceptions.py", line 152, in 
@attr.s(hash=True)
AttributeError: module 'attr' has no attribute 's'

**Comment by Zsailer** [comment]
It looks like you have an outdated version of `jsonscheam` and probably need to upgrade it. Try `pip install -U jsonschema` in your command line. 

Closing for now, but feel free to reopen this issue if it doesn't work. Good luck!

**Comment by Ajith8** [comment]
Hi, 
Tried to install the jsonschema and got the below warning,
Requirement already satisfied, skipping upgrade: zipp>=0.5 in c:\users\harish\anaconda3\lib\site-packages (from importlib-metadata; python_version < "3.8"->jsonschema) (2.2.0)
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

Kindly assist

**Comment by pakinja** [comment]
Hi, I have the same problem, did you can solved it?
