### ISSUE TITLE
kernel dead when opened from anaconda prompt

### ISSUE THREAD

**Issue by andreixxi** [jupyter/notebook#5413]
When I try to open jupyter notebook from anaconda prompt via `jupyter-notebook` i get the following error: 

[E 12:58:36.349 NotebookApp] Uncaught exception POST /api/sessions (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\web.py", line 1699, in _execute
        result = await result
      File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
        type=mtype))
      File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 209, in wrapper
        yielded = next(result)
      File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 158, in start_kernel
        km.start_kernel(**kwargs)
      File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\manager.py", line 301, in start_kernel
        kernel_cmd, kw = self.pre_start_kernel(**kw)
      File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\manager.py", line 248, in pre_start_kernel
        self.write_connection_file()
      File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\connect.py", line 474, in write_connection_file
        kernel_name=self.kernel_name
      File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\connect.py", line 138, in write_connection_file
        with secure_write(fname) as f:
      File "C:\Users\andrei\anaconda3\lib\contextlib.py", line 112, in __enter__
        return next(self.gen)
      File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_core\paths.py", line 424, in secure_write
        win32_restrict_file_to_user(fname)
      File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_core\paths.py", line 359, in win32_restrict_file_to_user
        import win32api
    ImportError: DLL load failed: %1 is not a valid Win32 application.
[W 12:58:36.366 NotebookApp] Unhandled error
[E 12:58:36.369 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "90",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|5c0c98c7|04a5e555036b07695b20058bc49e1031|1585926670",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
      "Content-Type": "application/json",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/notebooks/functii.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|5c0c98c7|04a5e555036b07695b20058bc49e1031|1585926670; username-localhost-8890=\"2|1:0|10:1588232147|23:username-localhost-8890|44:NDFkYmEyNWQwNWU5NDlkNzg0NGZmN2RhYWI3ZGIxYzI=|70519c266efecb292de1c3f3406feb2e7c680ae8546a7b245359bd4f3a82ab8f\"; username-localhost-8889=\"2|1:0|10:1588239712|23:username-localhost-8889|44:MjJmOTMyZWRkYjQxNGZlNGIwNzNiMzYyODM1ZjdmOGQ=|e3e0479c2bbc43b6d544813a3e21f2ef0131180b3183fca186d54189aecd1d39\"; username-localhost-8888=\"2|1:0|10:1588240678|23:username-localhost-8888|44:ZTA3ZDg1OWRlZjQ4NDY3ZGE1MmY2ODEwN2YzNmI1NDk=|6106f24d796044e89eac00541cbc535a6dc28c4b823e736bb3e10f7ca48d0335\""
    }
[E 12:58:36.371 NotebookApp] 500 POST /api/sessions (::1) 72.81ms referer=http://localhost:8888/notebooks/functii.ipynb
[E 13:36:27.341 NotebookApp] Uncaught exception POST /api/sessions (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\web.py", line 1699, in _execute
        result = await result
      File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
        type=mtype))
      File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 209, in wrapper
        yielded = next(result)
      File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 158, in start_kernel
        km.start_kernel(**kwargs)
      File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\manager.py", line 301, in start_kernel
        kernel_cmd, kw = self.pre_start_kernel(**kw)
      File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\manager.py", line 248, in pre_start_kernel
        self.write_connection_file()
      File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\connect.py", line 474, in write_connection_file
        kernel_name=self.kernel_name
      File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\connect.py", line 138, in write_connection_file
        with secure_write(fname) as f:
      File "C:\Users\andrei\anaconda3\lib\contextlib.py", line 112, in __enter__
        return next(self.gen)
      File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_core\paths.py", line 424, in secure_write
        win32_restrict_file_to_user(fname)
      File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_core\paths.py", line 359, in win32_restrict_file_to_user
        import win32api
    ImportError: DLL load failed: %1 is not a valid Win32 application.
[W 13:36:27.351 NotebookApp] Unhandled error
[E 13:36:27.356 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "96",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|5c0c98c7|04a5e555036b07695b20058bc49e1031|1585926670",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36",
      "Content-Type": "application/json",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/notebooks/retele/helper.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|5c0c98c7|04a5e555036b07695b20058bc49e1031|1585926670; username-localhost-8890=\"2|1:0|10:1588232147|23:username-localhost-8890|44:NDFkYmEyNWQwNWU5NDlkNzg0NGZmN2RhYWI3ZGIxYzI=|70519c266efecb292de1c3f3406feb2e7c680ae8546a7b245359bd4f3a82ab8f\"; username-localhost-8889=\"2|1:0|10:1588239712|23:username-localhost-8889|44:MjJmOTMyZWRkYjQxNGZlNGIwNzNiMzYyODM1ZjdmOGQ=|e3e0479c2bbc43b6d544813a3e21f2ef0131180b3183fca186d54189aecd1d39\"; username-localhost-8888=\"2|1:0|10:1588240678|23:username-localhost-8888|44:ZTA3ZDg1OWRlZjQ4NDY3ZGE1MmY2ODEwN2YzNmI1NDk=|6106f24d796044e89eac00541cbc535a6dc28c4b823e736bb3e10f7ca48d0335\""
    }
[E 13:36:27.357 NotebookApp] 500 POST /api/sessions (::1) 430.62ms referer=http://localhost:8888/notebooks/retele/helper.ipynb

**Comment by Zsailer** [comment]
Try calling installing/updating `pywin32` on the command line.

* `conda install pywin32`
* or `conda upgrade pywin32`
* or `pip install pywin32`

If none of these three solutions work, feel free to reopen this issue. Good luck!

**Comment by andreixxi** [comment]
when i open a notebook the kernel is dead. when i click that red panel with 'kernel error' it shows this error: 

Traceback (most recent call last):
  File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 158, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\manager.py", line 301, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\manager.py", line 248, in pre_start_kernel
    self.write_connection_file()
  File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\connect.py", line 474, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\connect.py", line 138, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\andrei\anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_core\paths.py", line 424, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_core\paths.py", line 359, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed: %1 is not a valid Win32 application.
