### ISSUE TITLE
#5390 Unable to launch Jupyter notebook from Anaconda Navigator 

### ISSUE THREAD

**Issue by Ajith8** [jupyter/notebook#5419]
Traceback (most recent call last):
File "C:\Users\Harish\anaconda3\Scripts\jupyter-notebook-script.py", line 6, in 
from notebook.notebookapp import main
File "C:\Users\Harish\anaconda3\lib\site-packages\notebook\notebookapp.py", line 80, in 
from .services.contents.manager import ContentsManager
File "C:\Users\Harish\anaconda3\lib\site-packages\notebook\services\contents\manager.py", line 17, in 
from nbformat import sign, validate as validate_nb, ValidationError
File "C:\Users\Harish\anaconda3\lib\site-packages\nbformat\__init__.py", line 32, in 
from .validator import validate, ValidationError
File "C:\Users\Harish\anaconda3\lib\site-packages\nbformat\validator.py", line 12, in 
from jsonschema import ValidationError
File "C:\Users\Harish\anaconda3\lib\site-packages\jsonschema\__init__.py", line 11, in 
from jsonschema.exceptions import (
File "C:\Users\Harish\anaconda3\lib\site-packages\jsonschema\exceptions.py", line 152, in 
@attr.s(hash=True)
AttributeError: module 'attr' has no attribute 's'

**Comment by Ajith8** [comment]
As per advise on #5390 , tried pip install -U jsonschema but getting below warnings,

Requirement already satisfied, skipping upgrade: zipp>=0.5 in c:\users\harish\anaconda3\lib\site-packages (from importlib-metadata; python_version < "3.8"->jsonschema) (2.2.0)
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

Kindly assist
