### ISSUE TITLE
anaconda jupyter notebook dead kernel

### ISSUE THREAD

**Issue by andreixxi** [jupyter/notebook#5430]
help me pleaseeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
i have the following ERRORS ::::::: 

[I 12:23:13.340 NotebookApp] The port 8888 is already in use, trying another port.
[I 12:23:13.340 NotebookApp] The port 8889 is already in use, trying another port.
[I 12:23:13.366 NotebookApp] Serving notebooks from local directory: C:\Users\andrei
[I 12:23:13.367 NotebookApp] The Jupyter Notebook is running at:
[I 12:23:13.367 NotebookApp] http://localhost:8890/?token=faa28c5f55b0137d5105e713b95798c5ace701e8ec95ab1c
[I 12:23:13.367 NotebookApp] or http://127.0.0.1:8890/?token=faa28c5f55b0137d5105e713b95798c5ace701e8ec95ab1c
[I 12:23:13.367 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 12:23:13.421 NotebookApp] 

To access the notebook, open this file in a browser:
file:///C:/Users/andrei/AppData/Roaming/jupyter/runtime/nbserver-11460-open.html
Or copy and paste one of these URLs:
http://localhost:8890/?token=faa28c5f55b0137d5105e713b95798c5ace701e8ec95ab1c
or http://127.0.0.1:8890/?token=faa28c5f55b0137d5105e713b95798c5ace701e8ec95ab1c
[W 12:23:24.678 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20200508122312 (::1) 17.94ms referer=http://localhost:8890/notebooks/IA/lab2.ipynb
[E 12:23:25.094 NotebookApp] Uncaught exception POST /api/sessions (::1)
HTTPServerRequest(protocol='http', host='localhost:8890', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\web.py", line 1699, in _execute
result = await result
File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 742, in run
yielded = self.gen.throw(*exc_info) # type: ignore
File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
type=mtype))
File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 735, in run
value = future.result()
File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 742, in run
yielded = self.gen.throw(*exc_info) # type: ignore
File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 735, in run
value = future.result()
File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 742, in run
yielded = self.gen.throw(*exc_info) # type: ignore
File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 735, in run
value = future.result()
File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 209, in wrapper
yielded = next(result)
File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
super(MappingKernelManager, self).start_kernel(**kwargs)
File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 158, in start_kernel
km.start_kernel(**kwargs)
File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\manager.py", line 301, in start_kernel
kernel_cmd, kw = self.pre_start_kernel(**kw)
File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\manager.py", line 248, in pre_start_kernel
self.write_connection_file()
File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\connect.py", line 474, in write_connection_file
kernel_name=self.kernel_name
File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\connect.py", line 138, in write_connection_file
with secure_write(fname) as f:
File "C:\Users\andrei\anaconda3\lib\contextlib.py", line 112, in __enter__
return next(self.gen)
File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_core\paths.py", line 435, in secure_write
win32_restrict_file_to_user(fname)
File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_core\paths.py", line 361, in win32_restrict_file_to_user
import win32api
ImportError: DLL load failed: %1 is not a valid Win32 application.
[W 12:23:25.147 NotebookApp] Unhandled error
[E 12:23:25.147 NotebookApp] {
"Host": "localhost:8890",
"Connection": "keep-alive",
"Content-Length": "90",
"Accept": "application/json, text/javascript, */*; q=0.01",
"X-Requested-With": "XMLHttpRequest",
"X-Xsrftoken": "2|508e6c13|0263514cd93bc9e93954a6478cc3f404|1588586705",
"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36",
"Content-Type": "application/json",
"Origin": "http://localhost:8890",
"Sec-Fetch-Site": "same-origin",
"Sec-Fetch-Mode": "cors",
"Sec-Fetch-Dest": "empty",
"Referer": "http://localhost:8890/notebooks/IA/lab2.ipynb",
"Accept-Encoding": "gzip, deflate, br",
"Accept-Language": "en-US,en;q=0.9",
"Cookie": "_xsrf=2|508e6c13|0263514cd93bc9e93954a6478cc3f404|1588586705; username-localhost-8888=\"2|1:0|10:1588928504|23:username-localhost-8888|44:ZDVkNGZhMzdlNzBlNGRlOGE5ZDA5MWViYTUwNmEzYjQ=|6572d8db9d4bb9059a8ec6a881102761eb921981c88a4c4ce1f35f585a7a65aa\"; username-localhost-8889=\"2|1:0|10:1588928540|23:username-localhost-8889|44:MTg4NjQ5M2IxMDU0NDE3NmFkZDYyM2E0YTM3NDBlMGI=|283d144ce2ea677e18bab51f848603c4486ef7fcf84e4e7ff4a63b290021c6fe\"; username-localhost-8890=\"2|1:0|10:1588929795|23:username-localhost-8890|44:NjRlYjQ3ZGEyNzIyNGMwODlkNjNjMjkwN2RmMjFjNGI=|f169a474b438d0f9bf5725c564c0869335cb2273e61f29a68f620626102c90e6\""
}
[E 12:23:25.147 NotebookApp] 500 POST /api/sessions (::1) 101.76ms referer=http://localhost:8890/notebooks/IA/lab2.ipynb

Traceback (most recent call last):
  File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 158, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\manager.py", line 301, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\manager.py", line 248, in pre_start_kernel
    self.write_connection_file()
  File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\connect.py", line 474, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_client\connect.py", line 138, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\andrei\anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_core\paths.py", line 435, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_core\paths.py", line 361, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by kevin-bates** [comment]
Take a look at these query results: https://github.com/jupyter/notebook/issues?q=is%3Aissue+%22DLL+load+failed%22+is%3Aclosed

Start with #5090 and try that.  However, this is essentially the same advice that @Zsailer provided on your other issue #5413.  (Are you not able to re-open that issue?)

One thing you might want to do is first shutdown all your notebook instances before updating software.  The output above implies you have 3 notebook servers running when the traceback was produced.

**Comment by andreixxi** [comment]
> Take a look at these query results: https://github.com/jupyter/notebook/issues?q=is%3Aissue+%22DLL+load+failed%22+is%3Aclosed
> 
> Start with #5090 and try that. However, this is essentially the same advice that @Zsailer provided on your other issue #5413. (Are you not able to re-open that issue?)
> 
> One thing you might want to do is first shutdown all your notebook instances before updating software. The output above implies you have 3 notebook servers running when the traceback was produced.

i've tried with #5090 (conda install pywin32) and what @Zsailer suggested me at #5413 but it did not work. i don't know how to re-open the older issue. i also don't know how to shutdown all notebook instances.. i've also tried to uninstall everything anaconda/python related and reinstall but to no avail ...

**Comment by kevin-bates** [comment]
`jupyter notebook list` should produce a list of currently running servers.  From there, pick out the port numbers (e.g., 8888, 8889, ...) and issue `jupyter notebook stop <port>` for each.

When you're updating your software (checking jupyter_client and pywin32 versions, etc.) be sure you are in the same conda environment as when you launch notebook server.

If your issues still persist, you can avoid _this_ issue by setting environment variable `JUPYTER_ALLOW_INSECURE_WRITES=1` and restarting notebook server.  This will leave your kernel's connection file with permissions that others can see, but if this is an exclusive server or your kernel's security is not a concern, it might prove to be an acceptable workaround.

**Comment by andreixxi** [comment]
Thank you, I managed to stop 2 ports, but i'm having another issue with 2 ports 8888.. when i run `jupyter notebook list` i get the following output: Currently running servers:
http://localhost:8888/?token=390432d11728bd53402509aa9f5f3e04e9091a3249442c77 :: C:\Users\andrei
http://localhost:8888/?token=bf4e99696d82b8d52de3282eb1fc690c4188396aa3ec60e0 :: C:\Users\andrei

and when i try to stop it/them by `jupyter notebook stop 8888` i get the following error: 
Shutting down server on port 8888 ...
Traceback (most recent call last):
  File "C:\Users\andrei\anaconda3\Scripts\jupyter-notebook-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_core\application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\andrei\anaconda3\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\notebookapp.py", line 1910, in start
    super(NotebookApp, self).start()
  File "C:\Users\andrei\anaconda3\lib\site-packages\jupyter_core\application.py", line 259, in start
    self.subapp.start()
  File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\notebookapp.py", line 466, in start
    if not self.shutdown_server(server):
  File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\notebookapp.py", line 457, in shutdown_server
    return shutdown_server(server, log=self.log)
  File "C:\Users\andrei\anaconda3\lib\site-packages\notebook\notebookapp.py", line 417, in shutdown_server
    HTTPClient().fetch(req)
  File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\httpclient.py", line 133, in fetch
    functools.partial(self._async_client.fetch, request, **kwargs)
  File "C:\Users\andrei\AppData\Roaming\Python\Python37\site-packages\tornado\ioloop.py", line 532, in run_sync
    return future_cell[0].result()
tornado.httpclient.HTTPClientError: HTTP 403: Forbidden

How can i set the environment variable `JUPYTER_ALLOW_INSECURE_WRITES=1 ` and restart the server ? thank you. security is not a concern since i only do stuff for uni

**Comment by kevin-bates** [comment]
Several google hits exist demonstrating how to set an environment variable on Windows, here's one: https://support.shotgunsoftware.com/hc/en-us/articles/114094235653-Setting-global-environment-variables-on-Windows

Be sure that after setting the variable, you restart your command window or any applications (like anaconda's launcher perhaps) in which that variable is necessary (i.e., in which you're starting Notebook server).  If in a command window, you should be able to verify its presence running `set` and looking for the variable name=value pair.

**Comment by kevin-bates** [comment]
Closing this issue. We can re-open if your issue still exists after setting the env variable.
