### ISSUE TITLE
Unable to run jupyter on my vm 

### ISSUE THREAD

**Issue by singhmnprt01** [jupyter/notebook#5459]
Failed to write server-info to /home/man/.local/share/jupyter/runtime/nbserver-31350.json: [Errno 28] No space left on device
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/anaconda3_new/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/apps/anaconda3_new/lib/python3.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/apps/anaconda3_new/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/apps/anaconda3_new/lib/python3.7/site-packages/notebook/notebookapp.py", line 1834, in start
    self.write_browser_open_file()
  File "/apps/anaconda3_new/lib/python3.7/site-packages/notebook/notebookapp.py", line 1753, in write_browser_open_file
    self._write_browser_open_file(open_url, f)
OSError: [Errno 28] No space left on device

How to change the the path of server info ?

**Comment by mgedmin** [comment]
You ran out of disk space.  I don't think *anything* will work until you free some space.
