### ISSUE TITLE
Notebook/Python 3.7 kernel conflicting with random.py files

### ISSUE THREAD

**Issue by RuneDominik** [jupyter/notebook#5470]
Edit: Realised, that this is probably an ipykernel issue rather than an issue with the server itself, so I opend a similar issue [here](https://github.com/ipython/ipykernel/issues/512).

When running a notebook with python 3 kernel from a notebook server started in a directory that contains a file `random.py` (file must only exist in the same directory, can be empty), the kernel seemingly tries importing from this file in the process:

```
[I 16:26:31.107 NotebookApp] Kernel started: 2dde5ce2-6742-4523-bbea-1e82edd3f963
Traceback (most recent call last):
File "/home/(...)/.local/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
File "/home/(...)/.local/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
File "/home/(...)/.local/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
File "/home/(...)/.local/anaconda3/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
File "/home/(...)/.local/anaconda3/lib/python3.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
File "/home/(...)/.local/anaconda3/lib/python3.7/site-packages/IPython/__init__.py", line 55, in <module>
    from .core.application import Application
File "/home/(...)/.local/anaconda3/lib/python3.7/site-packages/IPython/core/application.py", line 26, in <module>
    from IPython.core.profiledir import ProfileDir, ProfileDirError
File "/home/(...)/.local/anaconda3/lib/python3.7/site-packages/IPython/core/profiledir.py", line 12, in <module>
    from ..paths import get_ipython_package_dir
File "/home/(...)/.local/anaconda3/lib/python3.7/site-packages/IPython/paths.py", line 5, in <module>
    import tempfile
File "/home/(...)/.local/anaconda3/lib/python3.7/tempfile.py", line 45, in <module>
    from random import Random as _Random
ImportError: cannot import name 'Random' from 'random' (/home/(...)/test/random.py)
```
where (...) is my user. The server tries to restart the kernel till it hits the limit of 5 tries via the `KernelRestarter` always resulting in the error above and the kernel dies after that.

```
[W 16:34:09.714 NotebookApp] KernelRestarter: restart failed
[W 16:34:09.715 NotebookApp] Kernel 2dde5ce2-6742-4523-bbea-1e82edd3f963 died, removing from map.
```

Updating does not seem to resolve the problem. 
Some package-versions that might be interesting (including those pre-update):
```
Python: 3.7.6
ipykernel: 5.1.4 (tried also 5.1.3)
ipython: 7.13.0 (tried also 7.11.1)
jupyter: 1.0.0 
jupyter_client: 6.1.3 (tried also 5.3.4)
jupyter_console: 6.1.0 (tried also 6.0.0)
jupyter_core: 4.6.3 (tried also 4.6.1)
notebook: 6.0.3 (tried also 6.0.2)
```

**Comment by kevin-bates** [comment]
Opening the issue in ipykernel is technically more correct since this is not a notebook issue.  However, the outcome will likely be the same since this is [just the nature of an ipython kernel running local to your files](https://github.com/jupyter/jupyter/issues/125).  Rename your random.py and you'll be good to go (barring any other conflicts).
