### ISSUE TITLE
Name error

### ISSUE THREAD

**Issue by Bhavna25** [jupyter/notebook#5478]
NameError                                 Traceback (most recent call last)
<ipython-input-3-659f434d8a65> in <module>
----> 1 import numpy as np
      2 import matplotlib as plt
      3 import pandas as pd

e:\python\numpy.py in <module>
     19   {
     20    "cell_type": "code",
---> 21    "execution_count": null,
     22    "metadata": {},
     23    "outputs": [],

NameError: name 'null' is not defined

**Comment by martinal** [comment]
I got this same error on a fresh jupyter notebook install:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Cell In [1], line 39
      1 {
      2  "cells": [
      3   {
      4    "cell_type": "code",
      5    "execution_count": 5,
      6    "id": "740ed31b",
      7    "metadata": {},
      8    "outputs": [],
      9    "source": [
     10     "def get(key):\n",
     11     "    return [1,2,3]\n",
     12     "\n",
     13     "def put(key, value):\n",
     14     "    print(f\"{key} = {value}\")"
     15    ]
     16   },
     17   {
     18    "cell_type": "code",
     19    "execution_count": 6,
     20    "id": "95f0e6b4",
     21    "metadata": {},
     22    "outputs": [
     23     {
     24      "name": "stdout",
     25      "output_type": "stream",
     26      "text": [
     27       "ut = [2, 'verden']\n"
     28      ]
     29     }
     30    ],
     31    "source": [
     32     "x = get('hei')\n",
     33     "x[2] = \"verden\"\n",
     34     "put(\"ut\", x[1:])"
     35    ]
     36   },
     37   {
     38    "cell_type": "code",
---> 39    "execution_count": null,
     40    "id": "b7aef514",
     41    "metadata": {},
     42    "outputs": [],
     43    "source": []
     44   }
     45  ],
     46  "metadata": {
     47   "kernelspec": {
     48    "display_name": "Python 3 (ipykernel)",
     49    "language": "python",
     50    "name": "python3"
     51   },
     52   "language_info": {
     53    "codemirror_mode": {
     54     "name": "ipython",
     55     "version": 3
     56    },
     57    "file_extension": ".py",
     58    "mimetype": "text/x-python",
     59    "name": "python",
     60    "nbconvert_exporter": "python",
     61    "pygments_lexer": "ipython3",
     62    "version": "3.9.13"
     63   }
     64  },
     65  "nbformat": 4,
     66  "nbformat_minor": 5
     67 }

NameError: name 'null' is not defined
Traceback (most recent call last):
  File "/home/msa/learning/jupserv/venv/bin/jupyter-run", line 8, in <module>
    sys.exit(RunApp.launch_instance())
  File "/home/msa/learning/jupserv/venv/lib/python3.9/site-packages/jupyter_core/application.py", line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "/home/msa/learning/jupserv/venv/lib/python3.9/site-packages/traitlets/config/application.py", line 978, in launch_instance
    app.start()
  File "/home/msa/learning/jupserv/venv/lib/python3.9/site-packages/jupyter_client/runapp.py", line 110, in start
    raise Exception("jupyter-run error running '%s'" % filename)
Exception: jupyter-run error running 'notebook-job.ipynb'
```

**Comment by martinal** [comment]
```

(venv) ➜  jupserv jupyter --version
Selected Jupyter core packages...
IPython          : 8.5.0
ipykernel        : 6.16.0
ipywidgets       : 8.0.2
jupyter_client   : 7.3.5
jupyter_core     : 4.11.1
jupyter_server   : not installed
jupyterlab       : not installed
nbclient         : 0.6.8
nbconvert        : 7.0.0
nbformat         : 5.6.1
notebook         : 6.4.12
qtconsole        : 5.3.2
traitlets        : 5.4.0
```
