### ISSUE TITLE
Kernel Error

### ISSUE THREAD

**Issue by theja-m** [jupyter/notebook#5490]
I'm getting the following Kernel error .
I have tried so much ways to fix this issue and ended up in uninstalling python and reinstalling python. Even after reinstallation , I'm getting the same error.
Steps Followed -
1. Installed Python 3.8 .
2. Performed pip3 install jupyter on the cmd
3,  Used <jupyter notebook> on the cmd

> Traceback (most recent call last):
  File "c:\users\theja\appdata\local\programs\python\python38\lib\site-packages\tornado\web.py", line 1703, in _execute
    result = await result
  File "c:\users\theja\appdata\local\programs\python\python38\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\theja\appdata\local\programs\python\python38\lib\site-packages\notebook\services\sessions\handlers.py", line 69, in post
    model = yield maybe_future(
  File "c:\users\theja\appdata\local\programs\python\python38\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "c:\users\theja\appdata\local\programs\python\python38\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\theja\appdata\local\programs\python\python38\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "c:\users\theja\appdata\local\programs\python\python38\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "c:\users\theja\appdata\local\programs\python\python38\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\theja\appdata\local\programs\python\python38\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 100, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "c:\users\theja\appdata\local\programs\python\python38\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "c:\users\theja\appdata\local\programs\python\python38\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "c:\users\theja\appdata\local\programs\python\python38\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "c:\users\theja\appdata\local\programs\python\python38\lib\site-packages\jupyter_client\multikernelmanager.py", line 158, in start_kernel
    km.start_kernel(**kwargs)
  File "c:\users\theja\appdata\local\programs\python\python38\lib\site-packages\jupyter_client\manager.py", line 305, in start_kernel
    self.kernel = self._launch_kernel(kernel_cmd, **kw)
  File "c:\users\theja\appdata\local\programs\python\python38\lib\site-packages\jupyter_client\manager.py", line 212, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "c:\users\theja\appdata\local\programs\python\python38\lib\site-packages\jupyter_client\launcher.py", line 135, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "c:\users\theja\appdata\local\programs\python\python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\users\theja\appdata\local\programs\python\python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by kevin-bates** [comment]
I suspect you're running into an issue similar to https://github.com/jupyter/notebook/issues/5415 (the python version is not necessarily germane to this issue).  Please follow the steps in the comment.  I suspect your kernel.json file is pointing to a previous (and now incorrect) launch script.

If that doesn't resolve your issue, please include the contents of that kernel.json file in your response.  Thanks.

**Comment by theja-m** [comment]
I followed the same steps from the issue #5415 ,  now my kernel.json is pointing to the correct launch script.
Thank you very much Kevin.
