### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by sshleifer** [jupyter/notebook#5585]
```bash
jupyter notebook
```
Results in
```
Traceback (most recent call last):
  File "/Users/shleifer/miniconda3/envs/nb/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/Users/shleifer/miniconda3/envs/nb/lib/python3.7/site-packages/notebook/notebookapp.py", line 49, in <module>
    from zmq.eventloop import ioloop
  File "/Users/shleifer/miniconda3/envs/nb/lib/python3.7/site-packages/zmq/__init__.py", line 42, in <module>
    _load_libzmq()
  File "/Users/shleifer/miniconda3/envs/nb/lib/python3.7/site-packages/zmq/__init__.py", line 9, in _load_libzmq
    import sys, ctypes, platform, os
  File "/Users/shleifer/miniconda3/envs/nb/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/Users/shleifer/miniconda3/envs/nb/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /Users/shleifer/miniconda3/envs/nb/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
  Reason: image not found
```

Versions:
```
jupyter==1.0.0
jupyter-client==5.3.4
jupyter-console==6.1.0
jupyter-core==4.6.3
jupyterthemes==0.20.0
notebook==6.0.3
```

**Comment by kevin-bates** [comment]
[Google hits](https://www.google.com/search?q=ImportError%3A+dlopen(%2FUsers%2Fshleifer%2Fminiconda3%2Fenvs%2Fnb%2Flib%2Fpython3.7%2Flib-dynload%2F_ctypes.cpython-37m-darwin.so%2C+2)%3A+Library+not+loaded%3A+%40rpath%2Flibffi.6.dylib+R&oq=ImportError%3A+dlopen(%2FUsers%2Fshleifer%2Fminiconda3%2Fenvs%2Fnb%2Flib%2Fpython3.7%2Flib-dynload%2F_ctypes.cpython-37m-darwin.so%2C+2)%3A+Library+not+loaded%3A+%40rpath%2Flibffi.6.dylib+R&aqs=chrome..69i57j69i58.1270j0j4&sourceid=chrome&ie=UTF-8) are implying this is a conda issue.  This looks like a [fairly successful workaround](https://github.com/conda/conda/issues/9038#issuecomment-627698375) that avoids reinstallation.

As this is not specific to notebook, I'm going to close this issue.  Please post if you find a solution in case others encounter this as well.
