### ISSUE TITLE
Notebook fails to connect to kernel

### ISSUE THREAD

**Issue by drousavy** [jupyter/notebook#5603]
I have been having an issue using Notebook through anaconda. Upon opening the notebook I get the connecting to kernel message which stays up until I receive the failed to connect to kernel message. I have already tried installing a reinstalling anaconda a few times and it does not seem to resolve the issue. Furthermore, anaconda gives me the following error upon starting notebook.

[I 17:25:40.828 NotebookApp] Serving notebooks from local directory: C:\Users\delsa
[I 17:25:40.828 NotebookApp] 0 active kernels
[I 17:25:40.828 NotebookApp] The Jupyter Notebook is running at:
[I 17:25:40.828 NotebookApp] http://localhost:8888/?token=37f53d8369f79b5c86b8062010a79b18b3bb696c9f0ddc17
[I 17:25:40.828 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 17:25:40.874 NotebookApp] 

Copy/paste this URL into your browser when you connect for the first time,
to login with a token:
http://localhost:8888/?token=37f53d8369f79b5c86b8062010a79b18b3bb696c9f0ddc17
[I 17:25:41.067 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[W 17:25:48.585 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20200712172540 (::1) 19.94ms referer=http://localhost:8888/notebooks/CSC503A3Q5.ipynb
[I 17:25:48.766 NotebookApp] Kernel started: 356331ef-3e70-4781-b765-e4e814e672b7
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\delsa\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py", line 16, in 
app.launch_new_instance()
File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
app.start()
File "C:\Users\delsa\AppData\Roaming\Python\Python37\site-packages\ipykernel\kernelapp.py", line 477, in start
ioloop.IOLoop.instance().start()
File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 153, in start
self.asyncio_loop.run_forever()
File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 525, in run_forever
raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
[I 17:25:51.763 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
"__main__", mod_spec)
File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
exec(code, run_globals)
File "C:\Users\delsa\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py", line 16, in 
app.launch_new_instance()
File "C:\ProgramData\Anaconda3\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
app.start()
File "C:\Users\delsa\AppData\Roaming\Python\Python37\site-packages\ipykernel\kernelapp.py", line 477, in start
ioloop.IOLoop.instance().start()
File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 153, in start
self.asyncio_loop.run_forever()
File "C:\ProgramData\Anaconda3\lib\asyncio\base_events.py", line 525, in run_forever
raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running

I have been trying to troubleshoot this for some time now but have run out of ideas and do not have enough expertise to really dig through any of the code. Hopefully, someone is familiar with this issue.

**Comment by kevin-bates** [comment]
Hi @drousavy - could you please provide the output of `jupyter --version` when invoked from the same env in which you started your notebook server?  I have a hunch your ipykernel could use an update.

**Comment by drousavy** [comment]
Hi @kevin-bates here is the output I get for this command.

![jupyterversion_help](https://user-images.githubusercontent.com/55475910/87335522-50367800-c4f5-11ea-8cf5-dd736117288a.png)

**Comment by kevin-bates** [comment]
Thanks @drousavy.  I recommend updating your `notebook` and `ipykernel` versions.  That should update things like `jupyter_core`, `ipython`, etc.  Since this particular issue looks relative to `ipykernel`, you might try that update first, but your `notebook` version is rather old also - so you're probably best off updating both anyway.

**Comment by drousavy** [comment]
Hi @kevin-bates it appears that after updating each one of these things, that my Jupyter notebook has returned to normal operation. Thank you for your assistance.
