### ISSUE TITLE
Jupyter notebook is not connecting 

### ISSUE THREAD

**Issue by shibngri** [jupyter/notebook#5610]
Hi everyone!
I am facing an issue of starting notebook while using jupyter notebook. While pressing the button "connecting to kernel' leads to always "Not Connected". I am using python 2.7 version as the script demands. Kindly help me to fix this. I am attaching herewith the screenshots as well as the messages received in the terminal.
[I 12:27:20.153 NotebookApp] Serving notebooks from local directory: /home/shib/Desktop/Mohoinv/code
[I 12:27:20.153 NotebookApp] The Jupyter Notebook is running at:
[I 12:27:20.154 NotebookApp] http://localhost:8888/?token=ef0e5ac9454a26de39e56943a319519e4eccc3231efc9f8b
[I 12:27:20.154 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 12:27:20.157 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/shib/.local/share/jupyter/runtime/nbserver-4543-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=ef0e5ac9454a26de39e56943a319519e4eccc3231efc9f8b
[E 12:27:22.461 NotebookApp] Could not open static file ''
[W 12:27:22.555 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (127.0.0.1) 12.08ms referer=http://localhost:8888/tree?token=ef0e5ac9454a26de39e56943a319519e4eccc3231efc9f8b
[W 12:27:22.646 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (127.0.0.1) 1.89ms referer=http://localhost:8888/tree?token=ef0e5ac9454a26de39e56943a319519e4eccc3231efc9f8b
[W 12:27:26.452 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (127.0.0.1) 1.42ms referer=http://localhost:8888/notebooks/synthetic-simple.ipynb
[W 12:27:26.574 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (127.0.0.1) 1.67ms referer=http://localhost:8888/notebooks/synthetic-simple.ipynb
[I 12:27:29.217 NotebookApp] Kernel started: a9ec9a9c-efcf-448f-8f0f-733784595fe2
Traceback (most recent call last):
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/IPython/__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/IPython/terminal/embed.py", line 18, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 16, in <module>
    from prompt_toolkit.document import Document
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/prompt_toolkit/application.py", line 3, in <module>
    from .buffer import Buffer, AcceptAction
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/prompt_toolkit/buffer.py", line 7, in <module>
    from .auto_suggest import AutoSuggest
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/prompt_toolkit/auto_suggest.py", line 13, in <module>
    from .filters import to_cli_filter
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/prompt_toolkit/filters/__init__.py", line 33, in <module>
    from .base import *
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/prompt_toolkit/filters/base.py", line 5, in <module>
    from prompt_toolkit.utils import test_callable_args
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/prompt_toolkit/utils.py", line 9, in <module>
    from wcwidth import wcwidth
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/wcwidth/__init__.py", line 12, in <module>
    from .wcwidth import ZERO_WIDTH  # noqa
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/wcwidth/wcwidth.py", line 79, in <module>
    from backports.functools_lru_cache import lru_cache
ImportError: No module named functools_lru_cache
[I 12:27:32.201 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/IPython/__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/IPython/terminal/embed.py", line 18, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/IPython/terminal/interactiveshell.py", line 16, in <module>
    from prompt_toolkit.document import Document
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/prompt_toolkit/interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/prompt_toolkit/application.py", line 3, in <module>
    from .buffer import Buffer, AcceptAction
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/prompt_toolkit/buffer.py", line 7, in <module>
    from .auto_suggest import AutoSuggest
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/prompt_toolkit/auto_suggest.py", line 13, in <module>
    from .filters import to_cli_filter
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/prompt_toolkit/filters/__init__.py", line 33, in <module>
    from .base import *
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/prompt_toolkit/filters/base.py", line 5, in <module>
    from prompt_toolkit.utils import test_callable_args
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/prompt_toolkit/utils.py", line 9, in <module>
    from wcwidth import wcwidth
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/wcwidth/__init__.py", line 12, in <module>
    from .wcwidth import ZERO_WIDTH  # noqa
  File "/home/shib/anaconda3/envs/moho/lib/python2.7/site-packages/wcwidth/wcwidth.py", line 79, in <module>
    from backports.functools_lru_cache import lru_cache
ImportError: No module named functools_lru_cache
![err1](https://user-images.githubusercontent.com/55940334/87516753-86156100-c69b-11ea-9c9c-978dc41d3a2e.JPG)
![err2](https://user-images.githubusercontent.com/55940334/87516769-8c0b4200-c69b-11ea-903e-0c8ed0cfa3f6.JPG)

Your help will be much appreciated.
Thanks in anticipation.
Best,
Shib

**Comment by kevin-bates** [comment]
The various imports worked themselves into a corner navigating import exceptions and hit a module that was not listed as an installation requirement.  Try `pip install backports.functools_lru_cache` within that 2.7 env.  If possible, it might be worthwhile updating the script to Python 3.6+ should other issues arise.

**Comment by shibngri** [comment]
@kevin-bates Your suggestion worked. Much appreciate you help.

**Comment by kevin-bates** [comment]
Glad to hear you're moving forward.  Closing issue.
