### ISSUE TITLE
error of pyngrok

### ISSUE THREAD

**Issue by nobynobita** [jupyter/notebook#5619]
vinay@kali:~/Desktop$ cd HiddenEye

vinay@kali:~/Desktop/HiddenEye$ ls

Config.ini   CONTRIBUTING.md  HiddenEye.py  LICENSE  logo.png  PressKit   requirements.txt  Server        version.txt
_config.yml  Defs             index.html    locale   ngrok     README.md  Screenshot.png    Settings.ini  WebPages

vinay@kali:~/Desktop/HiddenEye$ python3 HiddenEye.py

Traceback (most recent call last):
  File "HiddenEye.py", line 8, in <module>
    import Defs.ActionManager.main_runner as main_runner
  File "/home/vinay/Desktop/HiddenEye/Defs/ActionManager/main_runner.py", line 10, in <module>
    import Defs.ActionManager.simple_informant as simple_informant
  File "/home/vinay/Desktop/HiddenEye/Defs/ActionManager/simple_informant.py", line 11, in <module>
    import Defs.ActionManager.Server.server_runner as server_runner
  File "/home/vinay/Desktop/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 18, in <module>
    os.mkdir("Server/www")
PermissionError: [Errno 13] Permission denied: 'Server/www'

vinay@kali:~/Desktop/HiddenEye$

**Comment by kevin-bates** [comment]
This does not appear to have anything to do with Jupyter Notebook - closing.

**Comment by omaryomario** [comment]
i have the same error
