### ISSUE TITLE
Import of win32api fails (DLL load) when attempting kernel startup

### ISSUE THREAD

**Issue by raj9650sahni** [jupyter/notebook#5624]
@kevin-batesbe i have got the same issue .when i open notebook it works fine but after 
opening a file in notebook .its says 'kernel is starting please wait'
help me
   To access the notebook, open this file in a browser:
        file:///C:/Users/Rajsa/AppData/Roaming/jupyter/runtime/nbserver-4252-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=c762bea6eaeab34eeeafb8f3ad1b13925b42085ebba2c54f
[I 12:31:57.207 NotebookApp] Kernel started: eb614f81-4d5c-43fc-8362-d2d677ecde55
Traceback (most recent call last):
  File "C:\Users\Rajsa\Downloads\New folder\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\Rajsa\Downloads\New folder\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\ipykernel\__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "C:\Users\Rajsa\AppData\Roaming\Python\Python27\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "C:\Users\Rajsa\AppData\Roaming\Python\Python27\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\ipykernel\kernelapp.py", line 415, in initialize
    self.write_connection_file()
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\ipykernel\kernelapp.py", line 193, in write_connection_file
    iopub_port=self.iopub_port, control_port=self.control_port)
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\jupyter_client\connect.py", line 141, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\Rajsa\Downloads\New folder\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\jupyter_core\paths.py", line 435, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\jupyter_core\paths.py", line 361, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed: The specified procedure could not be found.
[I 12:32:00.180 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "C:\Users\Rajsa\Downloads\New folder\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\Rajsa\Downloads\New folder\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\ipykernel\__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "C:\Users\Rajsa\AppData\Roaming\Python\Python27\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "C:\Users\Rajsa\AppData\Roaming\Python\Python27\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\ipykernel\kernelapp.py", line 415, in initialize
    self.write_connection_file()
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\ipykernel\kernelapp.py", line 193, in write_connection_file
    iopub_port=self.iopub_port, control_port=self.control_port)
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\jupyter_client\connect.py", line 141, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\Rajsa\Downloads\New folder\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\jupyter_core\paths.py", line 435, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\jupyter_core\paths.py", line 361, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed: The specified procedure could not be found.
[I 12:32:03.198 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "C:\Users\Rajsa\Downloads\New folder\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\Rajsa\Downloads\New folder\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\ipykernel\__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "C:\Users\Rajsa\AppData\Roaming\Python\Python27\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "C:\Users\Rajsa\AppData\Roaming\Python\Python27\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\ipykernel\kernelapp.py", line 415, in initialize
    self.write_connection_file()
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\ipykernel\kernelapp.py", line 193, in write_connection_file
    iopub_port=self.iopub_port, control_port=self.control_port)
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\jupyter_client\connect.py", line 141, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\Rajsa\Downloads\New folder\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\jupyter_core\paths.py", line 435, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\jupyter_core\paths.py", line 361, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed: The specified procedure could not be found.
[I 12:32:06.249 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "C:\Users\Rajsa\Downloads\New folder\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\Rajsa\Downloads\New folder\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\ipykernel\__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "C:\Users\Rajsa\AppData\Roaming\Python\Python27\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "C:\Users\Rajsa\AppData\Roaming\Python\Python27\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\ipykernel\kernelapp.py", line 415, in initialize
    self.write_connection_file()
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\ipykernel\kernelapp.py", line 193, in write_connection_file
    iopub_port=self.iopub_port, control_port=self.control_port)
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\jupyter_client\connect.py", line 141, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\Rajsa\Downloads\New folder\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\jupyter_core\paths.py", line 435, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\jupyter_core\paths.py", line 361, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed: The specified procedure could not be found.
[I 12:32:09.280 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "C:\Users\Rajsa\Downloads\New folder\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\Rajsa\Downloads\New folder\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\ipykernel\__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "C:\Users\Rajsa\AppData\Roaming\Python\Python27\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-123>", line 2, in initialize
  File "C:\Users\Rajsa\AppData\Roaming\Python\Python27\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\ipykernel\kernelapp.py", line 415, in initialize
    self.write_connection_file()
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\ipykernel\kernelapp.py", line 193, in write_connection_file
    iopub_port=self.iopub_port, control_port=self.control_port)
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\jupyter_client\connect.py", line 141, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\Rajsa\Downloads\New folder\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\jupyter_core\paths.py", line 435, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\Rajsa\Downloads\New folder\lib\site-packages\jupyter_core\paths.py", line 361, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed: The specified procedure could not be found.
[W 12:32:12.296 NotebookApp] KernelRestarter: restart failed
[W 12:32:12.296 NotebookApp] Kernel eb614f81-4d5c-43fc-8362-d2d677ecde55 died, removing from map.

**Comment by kevin-bates** [comment]
Hi @raj9650sahni - I think you're experiencing an issue similar to [this](https://github.com/jupyter/notebook/issues/5235#issuecomment-587545067) and revisiting the installation of `pywin32` is probably warranted.

I had a couple of other observations:
- Your python installation location is a little odd, although should be fine.  Not sure if you want to revisit that as well.
- There are references to python 2.7 - which has past end-of-life - so you might want to update those applications.  They appear related to jupyter packages.
- I took the liberty to update the title of this issue since that appears to be meant for a comment somewhere else.

**Comment by kevin-bates** [comment]
Gone silent - closing.
