### ISSUE TITLE
500 Internal Server Error on Jupyter Notebook! Can someone help to resolve this?

### ISSUE THREAD

**Issue by akki1305** [jupyter/notebook#5635]
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
/opt/anaconda3/bin/jupyter_mac.command ; exit;
(base) Us-MacBook-Air:~ akashrao$ /opt/anaconda3/bin/jupyter_mac.command ; exit;
[I 17:00:22.041 NotebookApp] JupyterLab extension loaded from /opt/anaconda3/lib/python3.7/site-packages/jupyterlab
[I 17:00:22.041 NotebookApp] JupyterLab application directory is /opt/anaconda3/share/jupyter/lab
[I 17:00:22.046 NotebookApp] Serving notebooks from local directory: /Users/akashrao
[I 17:00:22.047 NotebookApp] The Jupyter Notebook is running at:
[I 17:00:22.047 NotebookApp] http://localhost:8888/?token=fbe900018569b512a177100ae54baba7d138cad3f525262f
[I 17:00:22.047 NotebookApp]  or http://127.0.0.1:8888/?token=fbe900018569b512a177100ae54baba7d138cad3f525262f
[I 17:00:22.047 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 17:00:22.053 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/akashrao/Library/Jupyter/runtime/nbserver-1223-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=fbe900018569b512a177100ae54baba7d138cad3f525262f
     or http://127.0.0.1:8888/?token=fbe900018569b512a177100ae54baba7d138cad3f525262f
[I 17:00:28.114 NotebookApp] Creating new notebook in 
[E 17:00:28.352 NotebookApp] Uncaught exception GET /notebooks/Untitled31.ipynb?kernel_name=python3 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/notebooks/Untitled31.ipynb?kernel_name=python3', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/opt/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 748, in run
        yielded = self.gen.send(value)
      File "/opt/anaconda3/lib/python3.7/site-packages/notebook/notebook/handlers.py", line 101, in get
        get_frontend_exporters=get_frontend_exporters
      File "/opt/anaconda3/lib/python3.7/site-packages/notebook/base/handlers.py", line 507, in render_template
        return template.render(**ns)
      File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/opt/anaconda3/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "/opt/anaconda3/lib/python3.7/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/opt/anaconda3/lib/python3.7/site-packages/notebook/templates/page.html", line 153, in top-level template code
      File "/opt/anaconda3/lib/python3.7/site-packages/notebook/templates/notebook.html", line 114, in block "header"
        {% for exporter in get_frontend_exporters() %}
      File "/opt/anaconda3/lib/python3.7/site-packages/notebook/notebook/handlers.py", line 23, in get_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
      File "/opt/anaconda3/lib/python3.7/site-packages/nbconvert/__init__.py", line 4, in <module>
        from .exporters import *
      File "/opt/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/__init__.py", line 3, in <module>
        from .exporter_locator import export_by_name
      File "/opt/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/exporter_locator.py", line 13, in <module>
        from .html import HTMLExporter
      File "/opt/anaconda3/lib/python3.7/site-packages/nbconvert/exporters/html.py", line 13, in <module>
        from nbconvert.filters.markdown_mistune import IPythonRenderer, MarkdownWithMath
      File "/opt/anaconda3/lib/python3.7/site-packages/nbconvert/filters/markdown_mistune.py", line 17, in <module>
        from pygments.lexers import get_lexer_by_name
      File "/opt/anaconda3/lib/python3.7/site-packages/pygments/lexers/__init__.py", line 18, in <module>
        from pygments.lexers._mapping import LEXERS
    ModuleNotFoundError: No module named 'pygments.lexers._mapping'
[E 17:00:28.363 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "navigate",
      "Sec-Fetch-Dest": "document",
      "Referer": "http://localhost:8888/tree",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
      "Cookie": "_xsrf=2|59e56cb2|79e8bc6e369f0a59349fe5e5f7547d10|1595866936; username-localhost-8890=\"2|1:0|10:1595873629|23:username-localhost-8890|44:MTMzMWJlYTYzNzJiNDJiOTk2NzgxOWE3Njk0M2M5YTk=|a8e8dabebb7b7f4ca3ffa0fe3a3458daeda40dcd052905b3ef76b48ba6837215\"; username-localhost-8889=\"2|1:0|10:1595874263|23:username-localhost-8889|44:YzAxOTNmN2U2NTJmNGJjMDhkYTBiOWIzNzFkZTM4NTg=|122dcf94bfc79a6081d14af09970daf98884a92443e196d3f6309a6670039ad4\"; username-localhost-8888=\"2|1:0|10:1595935823|23:username-localhost-8888|44:ZTU3ZTVkZGJhOWFiNGI3YWE2NTYwNDc0OWEyMjAwZjU=|4182af622d2aaa9018d450bfb51409526e059854c01d7ec86b4aab98a86489a2\""
    }
[E 17:00:28.363 NotebookApp] 500 GET /notebooks/Untitled31.ipynb?kernel_name=python3 (::1) 203.57ms referer=http://localhost:8888/tree

**Comment by kevin-bates** [comment]
Hi @akki1305 - there appears to be something amiss with your installation of `pygments` that is used by `nbconvert` when opening a notebook.  Please try `pip install --upgrade pygments` and restart the notebook server to see if that fixes things up.

**Comment by akki1305** [comment]
> Hi @akki1305 - there appears to be something amiss with your installation of `pygments` that is used by `nbconvert` when opening a notebook. Please try `pip install --upgrade pygments` and restart the notebook server to see if that fixes things up.

Dear Mr. Bates,
now i am able to enter the notebook but now it says" A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration."

And in the terminal:

Last login: Tue Jul 28 22:04:44 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
/opt/anaconda3/bin/jupyter_mac.command ; exit;
(base) Us-MacBook-Air:~ akashrao$ /opt/anaconda3/bin/jupyter_mac.command ; exit;
[I 22:05:50.770 NotebookApp] JupyterLab extension loaded from /opt/anaconda3/lib/python3.7/site-packages/jupyterlab
[I 22:05:50.770 NotebookApp] JupyterLab application directory is /opt/anaconda3/share/jupyter/lab
[I 22:05:50.776 NotebookApp] Serving notebooks from local directory: /Users/akashrao
[I 22:05:50.776 NotebookApp] The Jupyter Notebook is running at:
[I 22:05:50.776 NotebookApp] http://localhost:8888/?token=127fb9502465326258110afe6c5aaf88183f372ec9d24f9f
[I 22:05:50.776 NotebookApp]  or http://127.0.0.1:8888/?token=127fb9502465326258110afe6c5aaf88183f372ec9d24f9f
[I 22:05:50.776 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 22:05:50.787 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/akashrao/Library/Jupyter/runtime/nbserver-1759-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=127fb9502465326258110afe6c5aaf88183f372ec9d24f9f
     or http://127.0.0.1:8888/?token=127fb9502465326258110afe6c5aaf88183f372ec9d24f9f
[W 22:05:57.682 NotebookApp] Notebook 01 - Copy (4) (5).ipynb is not trusted
[I 22:06:07.641 NotebookApp] Kernel started: 91db449d-d7bb-4e23-b5d8-401aa6790d76
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/__init__.py", line 55, in <module>
    from .core.application import Application
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
ImportError: cannot import name 'crashhandler' from 'IPython.core' (/opt/anaconda3/lib/python3.7/site-packages/IPython/core/__init__.py)
[I 22:06:10.623 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/__init__.py", line 55, in <module>
    from .core.application import Application
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
ImportError: cannot import name 'crashhandler' from 'IPython.core' (/opt/anaconda3/lib/python3.7/site-packages/IPython/core/__init__.py)
[I 22:06:13.635 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/__init__.py", line 55, in <module>
    from .core.application import Application
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
ImportError: cannot import name 'crashhandler' from 'IPython.core' (/opt/anaconda3/lib/python3.7/site-packages/IPython/core/__init__.py)
[I 22:06:16.645 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/__init__.py", line 55, in <module>
    from .core.application import Application
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
ImportError: cannot import name 'crashhandler' from 'IPython.core' (/opt/anaconda3/lib/python3.7/site-packages/IPython/core/__init__.py)
[I 22:06:19.658 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/__init__.py", line 55, in <module>
    from .core.application import Application
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
ImportError: cannot import name 'crashhandler' from 'IPython.core' (/opt/anaconda3/lib/python3.7/site-packages/IPython/core/__init__.py)
[W 22:06:22.674 NotebookApp] KernelRestarter: restart failed
[W 22:06:22.674 NotebookApp] Kernel 91db449d-d7bb-4e23-b5d8-401aa6790d76 died, removing from map.
[W 22:07:07.903 NotebookApp] Timeout waiting for kernel_info reply from 91db449d-d7bb-4e23-b5d8-401aa6790d76
[E 22:07:07.906 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 91db449d-d7bb-4e23-b5d8-401aa6790d76)
[W 22:07:08.965 NotebookApp] 404 GET /api/kernels/91db449d-d7bb-4e23-b5d8-401aa6790d76/channels?session_id=e61e228ac883490b97300a0fd077426f (::1): Kernel does not exist: 91db449d-d7bb-4e23-b5d8-401aa6790d76
[W 22:07:08.978 NotebookApp] 404 GET /api/kernels/91db449d-d7bb-4e23-b5d8-401aa6790d76/channels?session_id=e61e228ac883490b97300a0fd077426f (::1) 17.36ms referer=None
[W 22:07:11.016 NotebookApp] Replacing stale connection: 91db449d-d7bb-4e23-b5d8-401aa6790d76:e61e228ac883490b97300a0fd077426f
[I 22:07:22.789 NotebookApp] Creating new notebook in 
[I 22:07:23.752 NotebookApp] Kernel started: 1ba50ed1-004c-4aa6-83c9-47456e95e3bc
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/__init__.py", line 55, in <module>
    from .core.application import Application
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
ImportError: cannot import name 'crashhandler' from 'IPython.core' (/opt/anaconda3/lib/python3.7/site-packages/IPython/core/__init__.py)
[I 22:07:26.747 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/__init__.py", line 55, in <module>
    from .core.application import Application
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
ImportError: cannot import name 'crashhandler' from 'IPython.core' (/opt/anaconda3/lib/python3.7/site-packages/IPython/core/__init__.py)
[I 22:07:29.757 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/__init__.py", line 55, in <module>
    from .core.application import Application
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
ImportError: cannot import name 'crashhandler' from 'IPython.core' (/opt/anaconda3/lib/python3.7/site-packages/IPython/core/__init__.py)
[I 22:07:32.767 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/__init__.py", line 55, in <module>
    from .core.application import Application
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
ImportError: cannot import name 'crashhandler' from 'IPython.core' (/opt/anaconda3/lib/python3.7/site-packages/IPython/core/__init__.py)
[I 22:07:35.782 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/opt/anaconda3/lib/python3.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/__init__.py", line 55, in <module>
    from .core.application import Application
  File "/opt/anaconda3/lib/python3.7/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
ImportError: cannot import name 'crashhandler' from 'IPython.core' (/opt/anaconda3/lib/python3.7/site-packages/IPython/core/__init__.py)
[W 22:07:38.794 NotebookApp] KernelRestarter: restart failed
[W 22:07:38.795 NotebookApp] Kernel 1ba50ed1-004c-4aa6-83c9-47456e95e3bc died, removing from map.
[I 22:08:07.774 NotebookApp] Saving file at /01 - Copy (4) (5).ipynb
[W 22:08:07.778 NotebookApp] Notebook 01 - Copy (4) (5).ipynb is not trusted
[W 22:08:24.188 NotebookApp] Timeout waiting for kernel_info reply from 1ba50ed1-004c-4aa6-83c9-47456e95e3bc
[E 22:08:24.190 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: 1ba50ed1-004c-4aa6-83c9-47456e95e3bc)
[W 22:08:25.523 NotebookApp] 404 GET /api/kernels/1ba50ed1-004c-4aa6-83c9-47456e95e3bc/channels?session_id=5094ce97f30a4df1bf4c96986246e02f (127.0.0.1): Kernel does not exist: 1ba50ed1-004c-4aa6-83c9-47456e95e3bc
[W 22:08:25.526 NotebookApp] 404 GET /api/kernels/1ba50ed1-004c-4aa6-83c9-47456e95e3bc/channels?session_id=5094ce97f30a4df1bf4c96986246e02f (127.0.0.1) 6.22ms referer=None
[W 22:08:27.848 NotebookApp] Replacing stale connection: 1ba50ed1-004c-4aa6-83c9-47456e95e3bc:5094ce97f30a4df1bf4c96986246e02f
[I 22:09:23.732 NotebookApp] Saving file at /Untitled32.ipynb
[W 22:11:15.044 NotebookApp] Replacing stale connection: 91db449d-d7bb-4e23-b5d8-401aa6790d76:e61e228ac883490b97300a0fd077426f

**Comment by kevin-bates** [comment]
Looks like a similar issue, but with IPython.  Try `pip install --upgrade ipython`.  However, should similar import-related issues continue to happen, I would recommend building a new python environment or forcing the update of all jupyter-related packages using: `pip install --upgrade --upgrade-strategy eager jupyter`

**Comment by akki1305** [comment]
> pip install --upgrade ipython

pip install --upgrade ipython worked sir now I am able to run the program.

Thank You so very much!!! That was really helpful.
