### ISSUE TITLE
Notebook 6.1.1: ImportError when trying to stop jupyter server

### ISSUE THREAD

**Issue by corivera** [jupyter/notebook#5660]
After installing version 6.1.1 of the **notebook** package, I've started hitting errors when trying to stop the jupyter server. An ImportError is thrown when trying to import "bind_unix_socket", but the error goes away once I downgrade to **notebook** 6.0.3. I'm running on Windows 10 using Python 3.8.3.

I start the notebook with this command: "python -m jupyter notebook --no-browser"

Then I get an error when trying to stop the server with this command: "python -m jupyter notebook stop"

```
Shutting down server on 8888...
Traceback (most recent call last):
  File "c:\users\[user]\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\[user]\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\[user]\AppData\Local\Programs\Python\Python38\Scripts\jupyter-notebook.EXE\__main__.py", line 7, in <module>
  File "C:\Users\[user]\AppData\Roaming\Python\Python38\site-packages\jupyter_core\application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\[user]\AppData\Roaming\Python\Python38\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "C:\Users\[user]\AppData\Roaming\Python\Python38\site-packages\notebook\notebookapp.py", line 2187, in start
    super(NotebookApp, self).start()
  File "C:\Users\[user]\AppData\Roaming\Python\Python38\site-packages\jupyter_core\application.py", line 259, in start
    self.subapp.start()
  File "C:\Users\[user]\AppData\Roaming\Python\Python38\site-packages\notebook\notebookapp.py", line 553, in start
    self._shutdown_or_exit(port, server)
  File "C:\Users\[user]\AppData\Roaming\Python\Python38\site-packages\notebook\notebookapp.py", line 527, in _shutdown_or_exit
    if not self.shutdown_server(server):
  File "C:\Users\[user]\AppData\Roaming\Python\Python38\site-packages\notebook\notebookapp.py", line 523, in shutdown_server
    return shutdown_server(server, log=self.log)
  File "C:\Users\[user]\AppData\Roaming\Python\Python38\site-packages\notebook\notebookapp.py", line 446, in shutdown_server
    from tornado.netutil import bind_unix_socket, Resolver
ImportError: cannot import name 'bind_unix_socket' from 'tornado.netutil' (C:\Users\[user]\AppData\Roaming\Python\Python38\site-packages\tornado\netutil.py)
```

**Comment by kevin-bates** [comment]
Thanks @corivera - this is unfortunate.  I see there's a bug in the shutdown test that was preventing this issue from being exposed on Windows.  In fact, no shutdown was actually taking place via tests.  I'm looking into things now.
