### ISSUE TITLE
Unhandled Kernel Error

### ISSUE THREAD

**Issue by meherlad** [jupyter/notebook#5665]
Hello - I was wondering if someone could help me.
I was previously using Jupyter Lab without any issues but after re-installing miniconda3 (64-bit) on my Windows 10 Laptop I am unable to get the Python 3 kernel working. My error is shown below. Any help would be greatly appreciated.

(base) C:\Users\meher>jupyter lab
[I 23:12:33.662 LabApp] JupyterLab extension loaded from C:\Users\meher\miniconda3\lib\site-packages\jupyterlab
[I 23:12:33.662 LabApp] JupyterLab application directory is C:\Users\meher\miniconda3\share\jupyter\lab
[I 23:12:33.662 LabApp] Serving notebooks from local directory: C:\Users\meher
[I 23:12:33.662 LabApp] Jupyter Notebook 6.1.1 is running at:
[I 23:12:33.662 LabApp] http://localhost:8888/?token=4803c2fc3d85377afab2a668f15fe6ff92aaeea7f6f0c14c
[I 23:12:33.662 LabApp]  or http://127.0.0.1:8888/?token=4803c2fc3d85377afab2a668f15fe6ff92aaeea7f6f0c14c
[I 23:12:33.662 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 23:12:33.705 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/meher/AppData/Roaming/jupyter/runtime/nbserver-16284-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=4803c2fc3d85377afab2a668f15fe6ff92aaeea7f6f0c14c
     or http://127.0.0.1:8888/?token=4803c2fc3d85377afab2a668f15fe6ff92aaeea7f6f0c14c
[I 23:12:36.318 LabApp] Build is up to date
[E 23:12:47.816 LabApp] Failed to run command:
    ['C:\\Users\\meher\\AppData\\Local\\Continuum\\miniconda3\\python.exe', '-m', 'ipykernel_launcher', '-f', 'C:\\Users\\meher\\AppData\\Roaming\\jupyter\\runtime\\kernel-057a935b-a2be-4f16-bb8d-1aa436f88ca5.json']
        PATH='C:\\Users\\meher\\miniconda3;C:\\Users\\meher\\miniconda3\\Library\\mingw-w64\\bin;C:\\Users\\meher\\miniconda3\\Library\\usr\\bin;C:\\Users\\meher\\miniconda3\\Library\\bin;C:\\Users\\meher\\miniconda3\\Scripts;C:\\Users\\meher\\miniconda3\\bin;C:\\Users\\meher\\miniconda3\\condabin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\MATLAB\\R2019a\\bin;C:\\Program Files\\SlikSvn\\bin;C:\\Program Files\\nodejs;C:\\Program Files\\PsychoPy3;C:\\Program Files\\PsychoPy3\\DLLs;C:\\Go\\bin;C:\\Program Files\\Git\\cmd;C:\\Users\\meher\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\meher\\AppData\\Roaming\\npm;C:\\Users\\meher\\go\\bin;C:\\Users\\meher\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\meher\\AppData\\Local\\Microsoft\\WindowsApps;.'
        with kwargs:
    {'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': 'C:\\Users\\meher\\Dropbox\\ALL_Experiments\\Apps\\wm', 'close_fds': False}

[E 23:12:47.817 LabApp] Uncaught exception POST /api/sessions?1596838367771 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions?1596838367771', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\meher\miniconda3\lib\site-packages\tornado\web.py", line 1703, in _execute
        result = await result
      File "C:\Users\meher\miniconda3\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\meher\miniconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 69, in post
        model = yield maybe_future(
      File "C:\Users\meher\miniconda3\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\meher\miniconda3\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\meher\miniconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "C:\Users\meher\miniconda3\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\meher\miniconda3\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\meher\miniconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 100, in start_kernel_for_session
        kernel_id = yield maybe_future(
      File "C:\Users\meher\miniconda3\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\meher\miniconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
        kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
      File "C:\Users\meher\miniconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 186, in start_kernel
        km.start_kernel(**kwargs)
      File "C:\Users\meher\miniconda3\lib\site-packages\jupyter_client\manager.py", line 308, in start_kernel
        self.kernel = self._launch_kernel(kernel_cmd, **kw)
      File "C:\Users\meher\miniconda3\lib\site-packages\jupyter_client\manager.py", line 215, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "C:\Users\meher\miniconda3\lib\site-packages\jupyter_client\launcher.py", line 135, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "C:\Users\meher\miniconda3\lib\subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\Users\meher\miniconda3\lib\subprocess.py", line 1307, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified
[W 23:12:47.822 LabApp] Unhandled error
[E 23:12:47.824 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "154",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
      "X-Xsrftoken": "2|80f83a24|3a855852785b06f493184c562cd33e9d|1596577013",
      "Authorization": "token 4803c2fc3d85377afab2a668f15fe6ff92aaeea7f6f0c14c",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|80f83a24|3a855852785b06f493184c562cd33e9d|1596577013; username-localhost-8889=\"2|1:0|10:1596837989|23:username-localhost-8889|44:NDE2YTJlZDI2NDM1NGM4YjgzMDViODIxZjJlNjU4NGU=|8d1832b0c7b2e891ea5a3a944bdb03636f60f772353fa0325cd29dca6c8f65f9\"; username-localhost-8888=\"2|1:0|10:1596838367|23:username-localhost-8888|44:M2MzYTY3YWI4NWRlNGRjMDk1ZWY5MzQ1ZTNlM2FkMzk=|484f76c2b656e82a67bf80a41119c8622224b6a98dfbf63cf9d0fb02a9d034d5\""
    }
[E 23:12:47.824 LabApp] 500 POST /api/sessions?1596838367771 (::1) 50.13ms referer=http://localhost:8888/lab
[E 23:12:51.633 LabApp] Failed to run command:
    ['C:\\Users\\meher\\AppData\\Local\\Continuum\\miniconda3\\python.exe', '-m', 'ipykernel_launcher', '-f', 'C:\\Users\\meher\\AppData\\Roaming\\jupyter\\runtime\\kernel-1049cbef-2d41-4583-98d4-6ec5893c8b24.json']
        PATH='C:\\Users\\meher\\miniconda3;C:\\Users\\meher\\miniconda3\\Library\\mingw-w64\\bin;C:\\Users\\meher\\miniconda3\\Library\\usr\\bin;C:\\Users\\meher\\miniconda3\\Library\\bin;C:\\Users\\meher\\miniconda3\\Scripts;C:\\Users\\meher\\miniconda3\\bin;C:\\Users\\meher\\miniconda3\\condabin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\MATLAB\\R2019a\\bin;C:\\Program Files\\SlikSvn\\bin;C:\\Program Files\\nodejs;C:\\Program Files\\PsychoPy3;C:\\Program Files\\PsychoPy3\\DLLs;C:\\Go\\bin;C:\\Program Files\\Git\\cmd;C:\\Users\\meher\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\meher\\AppData\\Roaming\\npm;C:\\Users\\meher\\go\\bin;C:\\Users\\meher\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\meher\\AppData\\Local\\Microsoft\\WindowsApps;.'
        with kwargs:
    {'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': 'C:\\Users\\meher\\Dropbox\\ALL_Experiments\\Apps\\wm', 'close_fds': False}

[E 23:12:51.634 LabApp] Uncaught exception POST /api/sessions?1596838371623 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions?1596838371623', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\meher\miniconda3\lib\site-packages\tornado\web.py", line 1703, in _execute
        result = await result
      File "C:\Users\meher\miniconda3\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\meher\miniconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 69, in post
        model = yield maybe_future(
      File "C:\Users\meher\miniconda3\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\meher\miniconda3\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\meher\miniconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "C:\Users\meher\miniconda3\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\meher\miniconda3\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\meher\miniconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 100, in start_kernel_for_session
        kernel_id = yield maybe_future(
      File "C:\Users\meher\miniconda3\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\meher\miniconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
        kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
      File "C:\Users\meher\miniconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 186, in start_kernel
        km.start_kernel(**kwargs)
      File "C:\Users\meher\miniconda3\lib\site-packages\jupyter_client\manager.py", line 308, in start_kernel
        self.kernel = self._launch_kernel(kernel_cmd, **kw)
      File "C:\Users\meher\miniconda3\lib\site-packages\jupyter_client\manager.py", line 215, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "C:\Users\meher\miniconda3\lib\site-packages\jupyter_client\launcher.py", line 135, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "C:\Users\meher\miniconda3\lib\subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\Users\meher\miniconda3\lib\subprocess.py", line 1307, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified
[W 23:12:51.638 LabApp] Unhandled error
[E 23:12:51.639 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "154",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
      "X-Xsrftoken": "2|80f83a24|3a855852785b06f493184c562cd33e9d|1596577013",
      "Authorization": "token 4803c2fc3d85377afab2a668f15fe6ff92aaeea7f6f0c14c",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|80f83a24|3a855852785b06f493184c562cd33e9d|1596577013; username-localhost-8889=\"2|1:0|10:1596837989|23:username-localhost-8889|44:NDE2YTJlZDI2NDM1NGM4YjgzMDViODIxZjJlNjU4NGU=|8d1832b0c7b2e891ea5a3a944bdb03636f60f772353fa0325cd29dca6c8f65f9\"; username-localhost-8888=\"2|1:0|10:1596838368|23:username-localhost-8888|44:YTMzNjI2NmE4MzJkNDgxNDk2NzNlNGZiMGMzNTdjYzI=|96ef58706aac2df127325393b04d5175d88a04cf2b38ffa263cad631508d998f\""
    }
[E 23:12:51.641 LabApp] 500 POST /api/sessions?1596838371623 (::1) 12.45ms referer=http://localhost:8888/lab

**Comment by kevin-bates** [comment]
Hi @meherlad.  Is this `C:\Users\meher\AppData\Local\Continuum\miniconda3\python.exe` still a valid file on your system?

If not, you'll likely need to update the kernel.json file in which the path resides.  This can be accomplished by running `jupyter kernelspec list`, locating the kernel you are attempting to use, then going to that folder to edit kernel.json with the proper path.  You might also have better luck in the future just changing the first entry in `argv` to "python".  This way side-effects won't occur on python changes.

**Comment by meherlad** [comment]
Thank you so much @kevin-bates your second suggestion worked - changing the first entry in `argv` to "python". 

The first gave me this error (see below) but i'm super happy that it's working now!

[E 12:18:44.514 LabApp] 500 POST /api/sessions?1596885524499 (::1) 11.97ms referer=http://localhost:8888/lab
[E 12:18:57.336 LabApp] Failed to run command:
    ['C:\\Users\\meher\\AppData\\Roaming\\jupyter\\kernels\\python3', '-m', 'ipykernel_launcher', '-f', 'C:\\Users\\meher\\AppData\\Roaming\\jupyter\\runtime\\kernel-4db5a64e-45fc-42a3-a0ba-43f481a803e8.json']
        PATH='C:\\Users\\meher\\anaconda3;C:\\Users\\meher\\anaconda3\\Library\\mingw-w64\\bin;C:\\Users\\meher\\anaconda3\\Library\\usr\\bin;C:\\Users\\meher\\anaconda3\\Library\\bin;C:\\Users\\meher\\anaconda3\\Scripts;C:\\Users\\meher\\anaconda3\\bin;C:\\Users\\meher\\anaconda3\\condabin;C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0;C:\\WINDOWS\\System32\\OpenSSH;C:\\Program Files\\MATLAB\\R2019a\\bin;C:\\Program Files\\SlikSvn\\bin;C:\\Program Files\\nodejs;C:\\Go\\bin;C:\\Program Files\\Git\\cmd;C:\\Users\\meher\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\meher\\AppData\\Roaming\\npm;C:\\Users\\meher\\go\\bin;C:\\Users\\meher\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\meher\\AppData\\Local\\Microsoft\\WindowsApps;.'
        with kwargs:
    {'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': 'C:\\Users\\meher\\Dropbox\\ALL_Experiments\\Apps\\wm', 'close_fds': False}

[E 12:18:57.336 LabApp] Uncaught exception POST /api/sessions?1596885537324 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri='/api/sessions?1596885537324', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Users\meher\anaconda3\lib\site-packages\tornado\web.py", line 1703, in _execute
        result = await result
      File "C:\Users\meher\anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\meher\anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 69, in post
        model = yield maybe_future(
      File "C:\Users\meher\anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\meher\anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\meher\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "C:\Users\meher\anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\meher\anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "C:\Users\meher\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 100, in start_kernel_for_session
        kernel_id = yield maybe_future(
      File "C:\Users\meher\anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
        value = future.result()
      File "C:\Users\meher\anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
        yielded = next(result)
      File "C:\Users\meher\anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "C:\Users\meher\anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 186, in start_kernel
        km.start_kernel(**kwargs)
      File "C:\Users\meher\anaconda3\lib\site-packages\jupyter_client\manager.py", line 308, in start_kernel
        self.kernel = self._launch_kernel(kernel_cmd, **kw)
      File "C:\Users\meher\anaconda3\lib\site-packages\jupyter_client\manager.py", line 215, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "C:\Users\meher\anaconda3\lib\site-packages\jupyter_client\launcher.py", line 135, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "C:\Users\meher\anaconda3\lib\subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\Users\meher\anaconda3\lib\subprocess.py", line 1307, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    PermissionError: [WinError 5] Access is denied
[W 12:18:57.339 LabApp] Unhandled error
[E 12:18:57.340 LabApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Content-Length": "137",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36",
      "X-Xsrftoken": "2|80f83a24|3a855852785b06f493184c562cd33e9d|1596577013",
      "Authorization": "token 1c973280a3680a68ec36c5882e24d3092b1ffe9f720398ef",
      "Content-Type": "application/json",
      "Accept": "*/*",
      "Origin": "http://localhost:8888",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Referer": "http://localhost:8888/lab",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|80f83a24|3a855852785b06f493184c562cd33e9d|1596577013; username-localhost-8889=\"2|1:0|10:1596839701|23:username-localhost-8889|44:NTZjMjc1MTdhZWRkNDgxNjlkN2EwNTFkODIzZTY3OTI=|9b354e5b3336f9b4c310c3f126606abc6678e3af6204044dc5e9330dd183ef05\"; username-localhost-8888=\"2|1:0|10:1596885533|23:username-localhost-8888|44:Y2E0ZGU1YWE2M2UzNGEyNmIxN2ZjNjIzZjBkNDc5ZTg=|3c908f5f3026801787480ea424f0973ca0938c744d7eaba90be072db06588323\""
