### ISSUE TITLE
jupyter notebook is not opening

### ISSUE THREAD

**Issue by misbahnaz12** [jupyter/notebook#5668]
when i give command
jupyter notevvok
to anaconda prompt.then it get open in chrome with an empty page.

**Comment by Zsailer** [comment]
@misbahnaz12, would you mind pasting the output of the anaconda prompt here? It's difficult to identify the issue without more information. Thanks!

**Comment by 1209805090** [comment]
(base) C:\Users\12098>jupyter notebook
Traceback (most recent call last):
  File "E:\Software\anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "E:\Software\anaconda3\lib\site-packages\notebook\notebookapp.py", line 66, in <module>
    from tornado import httpserver
  File "E:\Software\anaconda3\lib\site-packages\tornado\httpserver.py", line 29, in <module>
    import ssl
  File "E:\Software\anaconda3\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed while importing _ssl: 找不到指定的程序。
