### ISSUE TITLE
jupyter notebook is not opening

### ISSUE THREAD

**Issue by 1209805090** [jupyter/notebook#5674]
(base) C:\Users\12098>jupyter notebook
Traceback (most recent call last):
  File "E:\Software\anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "E:\Software\anaconda3\lib\site-packages\notebook\notebookapp.py", line 66, in <module>
    from tornado import httpserver
  File "E:\Software\anaconda3\lib\site-packages\tornado\httpserver.py", line 29, in <module>
    import ssl
  File "E:\Software\anaconda3\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed while importing _ssl: 找不到指定的程序。

**Comment by kevin-bates** [comment]
Various hits, including #5609, imply an issue with your conda environment.  I would take the advice provided [here](https://github.com/jupyter/notebook/issues/5609#issuecomment-658364606) to try moving forward.
