### ISSUE TITLE
kernel failure 

### ISSUE THREAD

**Issue by jeffrey3128** [jupyter/notebook#5685]
I have encountered a sudden kernel failure when accessing the Jupyter notebook as usual from anaconda prompt (maybe after some pip install and pip upgrade?), the kernel failed to connect and function properly and shows the below error messages, I did a research on Github and have tried to uninstall and install Anaconda and Python, also did all the upgraded, but the error persists, it is so hopeless, please help~ thanks a lot!!!!!

[I 11:48:06.310 NotebookApp] The port 8888 is already in use, trying another port.
[I 11:48:06.311 NotebookApp] The port 8889 is already in use, trying another port.
[I 11:48:06.316 NotebookApp] Serving notebooks from local directory: C:\Users\jeffrey
[I 11:48:06.317 NotebookApp] Jupyter Notebook 6.1.1 is running at:
[I 11:48:06.317 NotebookApp] http://localhost:8890/?token=49abec84e17b06ce73e67032ba42772131142d2fdb54dc97
[I 11:48:06.317 NotebookApp] or http://127.0.0.1:8890/?token=49abec84e17b06ce73e67032ba42772131142d2fdb54dc97
[I 11:48:06.317 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:48:06.399 NotebookApp] 

To access the notebook, open this file in a browser:
file:///C:/Users/jeffrey/AppData/Roaming/jupyter/runtime/nbserver-4668-open.html
Or copy and paste one of these URLs:
http://localhost:8890/?token=49abec84e17b06ce73e67032ba42772131142d2fdb54dc97
or http://127.0.0.1:8890/?token=49abec84e17b06ce73e67032ba42772131142d2fdb54dc97
[W 11:48:14.370 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20200818114805 (::1) 14.88ms referer=http://localhost:8890/notebooks/Desktop/Untitled.ipynb
[I 11:48:14.702 NotebookApp] Kernel started: a877309e-4e6e-4730-91ea-967f785df875, name: python3
[IPKernelApp] ERROR | Failed to open SQLite history C:\Users\jeffrey\.ipython\profile_default\history.sqlite (file is not a database).
Traceback (most recent call last):
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\IPython\core\history.py", line 87, in catch_corrupt_db
return f(self, *a, **kw)
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\IPython\core\history.py", line 255, in init_db
self.db.execute("""CREATE TABLE IF NOT EXISTS sessions (session integer
sqlite3.DatabaseError: file is not a database

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\jeffrey\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\jeffrey\Anaconda3\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in 
app.launch_new_instance()
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
app.initialize(argv)
File "", line 2, in initialize
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 582, in initialize
self.init_kernel()
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 444, in init_kernel
kernel = kernel_factory(parent=self, session=self.session,
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
inst = cls(*args, **kwargs)
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 64, in __init__
self.shell = self.shell_class.instance(parent=self,
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
inst = cls(*args, **kwargs)
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 661, in __init__
self.init_history()
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 1802, in init_history
self.history_manager = HistoryManager(shell=self, parent=self)
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\IPython\core\history.py", line 536, in __init__
super(HistoryManager, self).__init__(shell=shell, config=config,
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\IPython\core\history.py", line 229, in __init__
self.init_db()
File "", line 2, in init_db
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\IPython\core\history.py", line 113, in catch_corrupt_db
os.rename(self.hist_file, newpath)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\jeffrey\\.ipython\\profile_default\\history.sqlite' -> 'C:\\Users\\jeffrey\\.ipython\\profile_default\\history-corrupt-2020-08-18T11.48.15.817567.sqlite'
[I 11:48:17.696 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
[IPKernelApp] ERROR | Failed to open SQLite history C:\Users\jeffrey\.ipython\profile_default\history.sqlite (file is not a database).
Traceback (most recent call last):
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\IPython\core\history.py", line 87, in catch_corrupt_db
return f(self, *a, **kw)
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\IPython\core\history.py", line 255, in init_db
self.db.execute("""CREATE TABLE IF NOT EXISTS sessions (session integer
sqlite3.DatabaseError: file is not a database

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\jeffrey\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Users\jeffrey\Anaconda3\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in 
app.launch_new_instance()
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
app.initialize(argv)
File "", line 2, in initialize
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
return method(app, *args, **kwargs)
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 582, in initialize
self.init_kernel()
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 444, in init_kernel
kernel = kernel_factory(parent=self, session=self.session,
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
inst = cls(*args, **kwargs)
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 64, in __init__
self.shell = self.shell_class.instance(parent=self,
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
inst = cls(*args, **kwargs)
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 661, in __init__
self.init_history()
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 1802, in init_history
self.history_manager = HistoryManager(shell=self, parent=self)
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\IPython\core\history.py", line 536, in __init__
super(HistoryManager, self).__init__(shell=shell, config=config,
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\IPython\core\history.py", line 229, in __init__
self.init_db()
File "", line 2, in init_db
File "C:\Users\jeffrey\Anaconda3\lib\site-packages\IPython\core\history.py", line 113, in catch_corrupt_db
os.rename(self.hist_file, newpath)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\jeffrey\\.ipython\\profile_default\\history.sqlite' -> 'C:\\Users\\jeffrey\\.ipython\\profile_default\\history-corrupt-2020-08-18T11.48.18.725484.sqlite'
[W 11:55:20.117 NotebookApp] KernelRestarter: restart failed
[W 11:55:20.117 NotebookApp] Kernel 270aa289-c7f3-49d3-babe-9109aa4c409b died, removing from map.

**Comment by kevin-bates** [comment]
This issue is coming out of the IPython package when its attempting to use the history sqlite DB.  Given that you likely have two other Notebook servers running (by virtue of the used ports messages at startup) and the issue regards contention with another process:
> PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\Users\jeffrey\.ipython\profile_default\history.sqlite' -> 'C:\Users\jeffrey\.ipython\profile_default\history-corrupt-2020-08-18T11.48.18.725484.sqlite'

I recommend the following:
1. Stop any Notebook servers that are running.  This can usually be accomplished using `jupyter notebook stop`, but you might need to resort to locating the appropriate python process via task manager and terminating that way.
2. Once all Notebook servers have been shutdown, try the issue again.  Should you still run into issues that appear to be DB related (search for `sqlite` in the console output), stop the Notebook server and see next step.
3. Unless you have affinity to your ipython history, remove the file 'C:\Users\jeffrey\.ipython\profile_default\history.sqlite' and try again.
4. Should the issue still persist, you'll need to open an issue in the [IPython repo](https://github.com/ipython/ipython).
