### ISSUE TITLE
jupyter - Failed to start the kernel

### ISSUE THREAD

**Issue by racine101** [jupyter/notebook#5688]
working in windows 10, I downloaded and install anaconda to use jupyter notebook, When I run jupyter notebook, the notebook launches but the kernel fails to start and I get below error. Please help. Thank you!

--------------------------------------------------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\kultu\AppData\Roaming\Python\Python38\site-packages\tornado\web.py", line 1703, in _execute
    result = await result
  File "C:\Users\kultu\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\kultu\anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 69, in post
    model = yield maybe_future(
  File "C:\Users\kultu\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\kultu\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\kultu\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\kultu\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\kultu\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\kultu\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 100, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "C:\Users\kultu\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\kultu\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\kultu\anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\kultu\AppData\Roaming\Python\Python38\site-packages\jupyter_client\multikernelmanager.py", line 186, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\kultu\AppData\Roaming\Python\Python38\site-packages\jupyter_client\manager.py", line 304, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "C:\Users\kultu\AppData\Roaming\Python\Python38\site-packages\jupyter_client\manager.py", line 251, in pre_start_kernel
    self.write_connection_file()
  File "C:\Users\kultu\AppData\Roaming\Python\Python38\site-packages\jupyter_client\connect.py", line 468, in write_connection_file
    self.connection_file, cfg = write_connection_file(self.connection_file,
  File "C:\Users\kultu\AppData\Roaming\Python\Python38\site-packages\jupyter_client\connect.py", line 138, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\kultu\anaconda3\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "C:\Users\kultu\AppData\Roaming\Python\Python38\site-packages\jupyter_core\paths.py", line 435, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\kultu\AppData\Roaming\Python\Python38\site-packages\jupyter_core\paths.py", line 361, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed while importing win32api: %1 is not a valid Win32 application.

**Comment by kevin-bates** [comment]
Hi @racine101 - This is usually an issue with the installation of `pywin32`.  This https://github.com/jupyter/notebook/issues/4980#issuecomment-600992296 might prove helpful to you.  I would recommend adding `--force-reinstall` or uninstall `pywin32` prior to the install command since you have the package installed.

If that doesn't help, try searching the issues (or internet in general), as this has been reported before.

**Comment by racine101** [comment]
https://stackoverflow.com/questions/19019720/importerror-dll-load-failed-1-is-not-a-valid-win32-application-but-the-dlls

thank you, info on this page helped me resolved the problem.
