### ISSUE TITLE
Exception in callback Error when closing the kernel

### ISSUE THREAD

**Issue by ahmadmustafaanis** [jupyter/notebook#5690]
OS: Ubuntu 18.04 

Latest Jupyter notebook

WHen I close a kernel from command prompt using ctrl+c, it closes the kernel and throws and exception. It was not doing it when I had `tensorflow 2.2`, but i switched to `tensorflow 2.0` and it is giving this jupyter error.

```error
Shutdown this notebook server (y/[n])? y
[C 18:45:49.608 NotebookApp] Shutdown confirmed
[I 18:45:49.610 NotebookApp] Shutting down 1 kernel
[I 18:45:50.313 NotebookApp] Kernel shutdown: b62da79b-ca59-43f3-ba21-a021e6330235
[I 18:45:50.314 NotebookApp] Shutting down 0 terminals
[I 18:45:50.319 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel b62da79b-ca59-43f3-ba21-a021e6330235 restarted
[E 18:45:50.321 NotebookApp] Exception in callback <bound method KernelRestarter.poll of <jupyter_client.ioloop.restarter.IOLoopKernelRestarter object at 0x7fc102298510>>
    Traceback (most recent call last):
      File "/home/ahmad/anaconda3/envs/deep/lib/python3.7/site-packages/tornado/ioloop.py", line 907, in _run
        return self.callback()
      File "/home/ahmad/anaconda3/envs/deep/lib/python3.7/site-packages/jupyter_client/restarter.py", line 113, in poll
        self.kernel_manager.restart_kernel(now=True, newports=newports)
      File "/home/ahmad/anaconda3/envs/deep/lib/python3.7/site-packages/jupyter_client/manager.py", line 442, in restart_kernel
        self.shutdown_kernel(now=now, restart=True)
      File "/home/ahmad/anaconda3/envs/deep/lib/python3.7/site-packages/jupyter_client/manager.py", line 383, in shutdown_kernel
        self._kill_kernel()
      File "/home/ahmad/anaconda3/envs/deep/lib/python3.7/site-packages/jupyter_client/manager.py", line 487, in _kill_kernel
        raise RuntimeError("Cannot kill kernel. No kernel is running!")
    RuntimeError: Cannot kill kernel. No kernel is running!
(deep) ahmad@ahmad-HP-Laptop-15-da1xxx:~$ 
```
How to solve this error. Thanks

**Comment by kevin-bates** [comment]
This appears to be a race condition with shutting down the notebook server and the server's auto-restart logic.  The server terminates the kernel, but 6ms later the periodic callback checks (every 3000ms) to see if a kernel it knows about is no longer responding.  So it goes to restart the kernel, only to find there's no kernel (process) to terminate.

Because this should rarely occur, I'm not sure it's worth addressing and can be safely ignored.  If there's any change to be made here, I'd recommend making `_kill_kernel()` not raise an exception if it finds there's no longer kernel process, similar to what it does [here](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/manager.py#L476-L486), rather than [raise an exception](https://github.com/jupyter/jupyter_client/blob/master/jupyter_client/manager.py#L492).  This would be a change in `jupyter_client` and I can transfer this issue there if you like.

Do you see this often?

**Comment by ahmadmustafaanis** [comment]
After Some Trail and Error, I have seen this does not occur in my `base` env. In my `deep` env, it only occurs when I have imported my `TensorFlow 2.0.0` and made a model with it. If I have only imported, this does not happen, but making a model makes this happen.

But the error is not related to tensorflow, it is related to jupyter.
```error
^C[I 11:47:06.518 NotebookApp] interrupted
Serving notebooks from local directory: /home/ahmad
1 active kernel
Jupyter Notebook 6.1.3 is running at:
http://localhost:8888/?token=b26abbf934f0711974408b8ac962feda49931a7f23ce0613
 or http://127.0.0.1:8888/?token=b26abbf934f0711974408b8ac962feda49931a7f23ce0613
Shutdown this notebook server (y/[n])? y
[C 11:47:07.465 NotebookApp] Shutdown confirmed
[I 11:47:07.466 NotebookApp] Shutting down 1 kernel
[I 11:47:07.969 NotebookApp] Kernel shutdown: 4cec15c3-1949-4732-8ffe-95f2860c9add
[I 11:47:07.970 NotebookApp] Shutting down 0 terminals
[I 11:47:07.973 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel 4cec15c3-1949-4732-8ffe-95f2860c9add restarted
[E 11:47:07.976 NotebookApp] Exception in callback <bound method KernelRestarter.poll of <jupyter_client.ioloop.restarter.IOLoopKernelRestarter object at 0x7f197b765a90>>
    Traceback (most recent call last):
      File "/home/ahmad/anaconda3/envs/deep/lib/python3.7/site-packages/tornado/ioloop.py", line 907, in _run
        return self.callback()
      File "/home/ahmad/anaconda3/envs/deep/lib/python3.7/site-packages/jupyter_client/restarter.py", line 113, in poll
        self.kernel_manager.restart_kernel(now=True, newports=newports)
      File "/home/ahmad/anaconda3/envs/deep/lib/python3.7/site-packages/jupyter_client/manager.py", line 442, in restart_kernel
        self.shutdown_kernel(now=now, restart=True)
      File "/home/ahmad/anaconda3/envs/deep/lib/python3.7/site-packages/jupyter_client/manager.py", line 383, in shutdown_kernel
        self._kill_kernel()
      File "/home/ahmad/anaconda3/envs/deep/lib/python3.7/site-packages/jupyter_client/manager.py", line 487, in _kill_kernel
        raise RuntimeError("Cannot kill kernel. No kernel is running!")
    RuntimeError: Cannot kill kernel. No kernel is running!
(deep) ahmad@ahmad-HP-Laptop-15-da1xxx:~$ 
```

**Comment by kevin-bates** [comment]
> But the error is not related to tensorflow, it is related to jupyter.

Understood and I agree completely.  Apparently, and interestingly, building a tensorflow model has probably introduced something that causes some latency in shutting down the kernel process.   

Since raising an exception stating that the kernel's final shutdown attempt (i.e., SIGKILL vs. SIGTERM) cannot occur because the kernel is no longer running is superfluous, that condition should instead be ignored similar to what occurs when failing to send a signal to the actual process - only to find there is no longer a process (as I pointed out in my previous response).  As a result, I'm going to transfer this issue to [jupyter_client](https://github.com/jupyter/jupyter_client) and address it there.
