### ISSUE TITLE
Error Starting Kernel Invalid response: 500 Internal Server Error Unhandled error

### ISSUE THREAD

**Issue by sushank3100** [jupyter/notebook#5693]
Traceback (most recent call last):
File "C:\Users\susha\AppData\Roaming\Python\Python38\site-packages\tornado\web.py", line 1703, in _execute
result = await result
File "C:\Users\susha\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 742, in run
yielded = self.gen.throw(*exc_info) # type: ignore
File "C:\Users\susha\AppData\Roaming\Python\Python38\site-packages\notebook\services\sessions\handlers.py", line 69, in post
model = yield maybe_future(
File "C:\Users\susha\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 735, in run
value = future.result()
File "C:\Users\susha\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 742, in run
yielded = self.gen.throw(*exc_info) # type: ignore
File "C:\Users\susha\AppData\Roaming\Python\Python38\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
File "C:\Users\susha\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 735, in run
value = future.result()
File "C:\Users\susha\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 742, in run
yielded = self.gen.throw(*exc_info) # type: ignore
File "C:\Users\susha\AppData\Roaming\Python\Python38\site-packages\notebook\services\sessions\sessionmanager.py", line 100, in start_kernel_for_session
kernel_id = yield maybe_future(
File "C:\Users\susha\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 735, in run
value = future.result()
File "C:\Users\susha\AppData\Roaming\Python\Python38\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
File "C:\Users\susha\AppData\Roaming\Python\Python38\site-packages\jupyter_client\multikernelmanager.py", line 186, in start_kernel
km.start_kernel(**kwargs)
File "C:\Users\susha\AppData\Roaming\Python\Python38\site-packages\jupyter_client\manager.py", line 304, in start_kernel
kernel_cmd, kw = self.pre_start_kernel(**kw)
File "C:\Users\susha\AppData\Roaming\Python\Python38\site-packages\jupyter_client\manager.py", line 251, in pre_start_kernel
self.write_connection_file()
File "C:\Users\susha\AppData\Roaming\Python\Python38\site-packages\jupyter_client\connect.py", line 468, in write_connection_file
self.connection_file, cfg = write_connection_file(self.connection_file,
File "C:\Users\susha\AppData\Roaming\Python\Python38\site-packages\jupyter_client\connect.py", line 138, in write_connection_file
with secure_write(fname) as f:
File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 113, in enter
return next(self.gen)
File "C:\Users\susha\AppData\Roaming\Python\Python38\site-packages\jupyter_core\paths.py", line 435, in secure_write
win32_restrict_file_to_user(fname)
File "C:\Users\susha\AppData\Roaming\Python\Python38\site-packages\jupyter_core\paths.py", line 361, in win32_restrict_file_to_user
import win32api
ImportError: DLL load failed while importing win32api: %1 is not a valid Win32 application.

I AM GETTING THIS ERROR EVEN AFTER TRYING  A BUNCH OF SOLUTION ON INTERNET

Name Version Build Channel
jupyter 1.0.0 py38_7
jupyter_client 6.1.6 py_0
jupyter_console 6.1.0 py_0
jupyter_core 4.6.3 py38_0
jupyterlab 2.1.5 py_0
jupyterlab_server 1.2.0 py_0
pywin32 227 py38he774522_1
pywin32-ctypes 0.2.0 py38_1000
pywinpty 0.5.7 py38_0

CAN ANYBODY HELP ME !!!!

**Comment by kevin-bates** [comment]
It's tough to determine what to recommend since you haven't indicated what you've tried.  

This issue (`win32api: %1 is not a valid Win32 application`) appears to be mostly related to running 64bit DLLs on 32bit systems.  I would look at things through that lens in terms of your Anaconda installation, etc.  Also, I see a mixture of paths coming into play.  For instance, `C:\Users\susha\AppData\Roaming\Python\Python38\site-packages` then `C:\ProgramData\Anaconda3\lib` and perhaps its the case that one env is introducing the incompatibility?  Since others appear to have resolved this issue following https://github.com/jupyter/notebook/issues/4909#issuecomment-596876786, I would recommend performing those actions if you haven't already.

Please respond with any findings you have as this appears to be one of the more difficult situations to resolve.

**Comment by sushank3100** [comment]
thanks for the ans  @kevin-bates  but i uninstalled anaconda now i am able to run the jupyter in vs code and its working
