### ISSUE TITLE
Not able to find a module in jupyter

### ISSUE THREAD

**Issue by SourabhKothari99** [jupyter/notebook#5694]
New to jupyter, please help

import my_universal_function as MyFuncs
Traceback (most recent call last):

  File "C:\Users\USER\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-3-323b2829d3c1>", line 1, in <module>
    import my_universal_function as MyFuncs

  File "C:\Users\USER\Desktop\Python\Learning\my_universal_function.py", line 11
    return False
    ^
SyntaxError: invalid syntax

**Comment by SourabhKothari99** [comment]
Noob mistake

the file was not in proper syntax
