### ISSUE TITLE
Tab Completion Not Working

### ISSUE THREAD

**Issue by AnkS4** [jupyter/notebook#5701]
Code Completion/Suggestion is not visible with Tab.

```
The version of the notebook server is: 6.1.1
The server is running on this version of Python:

Python 3.8.5 (default, Jul 27 2020, 08:42:51) 
[GCC 10.1.0]

Current Kernel Information:

Python 3.8.5 (default, Jul 27 2020, 08:42:51) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.17.0 -- An enhanced Interactive Python. Type '?' for help.
```

**Comment by m-j** [comment]
I'm having the same problem. When looked into console got following stacktrace each time I press tab:

```
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "c:\users\mathix\.virtualenvs\protrack-log-analyzer-vdihuccx\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "c:\users\mathix\.virtualenvs\protrack-log-analyzer-vdihuccx\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "c:\users\mathix\.virtualenvs\protrack-log-analyzer-vdihuccx\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "c:\users\mathix\.virtualenvs\protrack-log-analyzer-vdihuccx\lib\site-packages\ipykernel\kernelbase.py", line 583, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "c:\users\mathix\.virtualenvs\protrack-log-analyzer-vdihuccx\lib\site-packages\ipykernel\ipkernel.py", line 360, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "c:\users\mathix\.virtualenvs\protrack-log-analyzer-vdihuccx\lib\site-packages\ipykernel\ipkernel.py", line 385, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "c:\users\mathix\.virtualenvs\protrack-log-analyzer-vdihuccx\lib\site-packages\IPython\core\completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "c:\users\mathix\.virtualenvs\protrack-log-analyzer-vdihuccx\lib\site-packages\IPython\core\completer.py", line 1819, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "c:\users\mathix\.virtualenvs\protrack-log-analyzer-vdihuccx\lib\site-packages\IPython\core\completer.py", line 1876, in _completions
    signature = _make_signature(jm)
  File "c:\users\mathix\.virtualenvs\protrack-log-analyzer-vdihuccx\lib\site-packages\IPython\core\completer.py", line 991, in _make_signature
    return '(%s)'% ', '.join([f for f in (_formatparamchildren(p) for signature in completion.get_signatures()
  File "c:\users\mathix\.virtualenvs\protrack-log-analyzer-vdihuccx\lib\site-packages\IPython\core\completer.py", line 991, in <listcomp>
    return '(%s)'% ', '.join([f for f in (_formatparamchildren(p) for signature in completion.get_signatures()
  File "c:\users\mathix\.virtualenvs\protrack-log-analyzer-vdihuccx\lib\site-packages\IPython\core\completer.py", line 992, in <genexpr>
    for p in signature.defined_names()) if f])
  File "c:\users\mathix\.virtualenvs\protrack-log-analyzer-vdihuccx\lib\site-packages\IPython\core\completer.py", line 969, in _formatparamchildren
    'Expected "param ...", found %r".' % description)
```

**Comment by Zsailer** [comment]
Thanks for pointing us to this issue.

This looks like an issue with IPython and there is already an open issue there: ipython/ipython#12522.

Closing here in favor of that.
