### ISSUE TITLE
Jupyter-notebook failed to launch

### ISSUE THREAD

**Issue by manildayma** [jupyter/notebook#5709]
Anaconda3 was installed without any issue. START menu shortcuts were created but only Anaconda prompt would open. Via prompt, I opened Anaconda Navigator with command "anaconda-navigator" and tried to launch Jupyter and this huge list of errors appear. Please help me resolve this. I've reinstall Anaconda3 about 10 times in 2 days with all possible combinations of settings provided while installation and default settings as well but this doesn't work.
Similar is that case with Jupyter Lab and Spyder.

Traceback (most recent call last):
File "C:\Users\manil\anaconda3\Scripts\jupyter-notebook-script.py", line 6, in 
from notebook.notebookapp import main
File "C:\Users\manil\AppData\Roaming\Python\Python38\site-packages\notebook\notebookapp.py", line 51, in 
from zmq.eventloop import ioloop
File "C:\Users\manil\AppData\Roaming\Python\Python38\site-packages\zmq\_init_.py", line 50, in 
from zmq import backend
File "C:\Users\manil\AppData\Roaming\Python\Python38\site-packages\zmq\backend\_init_.py", line 40, in 
reraise(*exc_info)
File "C:\Users\manil\AppData\Roaming\Python\Python38\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
raise value
File "C:\Users\manil\AppData\Roaming\Python\Python38\site-packages\zmq\backend\_init_.py", line 27, in 
_ns = select_backend(first)
File "C:\Users\manil\AppData\Roaming\Python\Python38\site-packages\zmq\backend\select.py", line 28, in select_backend
mod = _import_(name, fromlist=public_api)
File "C:\Users\manil\AppData\Roaming\Python\Python38\site-packages\zmq\backend\cython\_init_.py", line 6, in 
from . import (constants, error, message, context,
ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython' (most likely due to a circular import) (C:\Users\manil\AppData\Roaming\Python\Python38\site-packages\zmq\backend\cython\_init_.py)

**Comment by kevin-bates** [comment]
Looks like a duplicate of #5689.  Please try resetting `pyzmq`.
