### ISSUE TITLE
Couldn't able to open the jupyter notebook from command prompt. 

### ISSUE THREAD

**Issue by prasanthvattikonda** [jupyter/notebook#5710]
I am able to open the jupyter notebook from the anaconda prompt. But not from the command prompt. can somebody help me how to resolve this. 

C:\Users\Prasanth Vattikonda>jupyter notebook
C:\Users\Prasanth Vattikonda\anaconda3\lib\site-packages\setuptools\distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\Prasanth Vattikonda\anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\Users\Prasanth Vattikonda\anaconda3\lib\site-packages\notebook\notebookapp.py", line 49, in <module>
    from zmq.eventloop import ioloop
  File "C:\Users\Prasanth Vattikonda\anaconda3\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Users\Prasanth Vattikonda\anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\Prasanth Vattikonda\anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\Prasanth Vattikonda\anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\Prasanth Vattikonda\anaconda3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\Prasanth Vattikonda\anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed while importing error: The specified module could not be found.

**Comment by kevin-bates** [comment]
Looks like a variation of #5689.  Please try resetting `pyzmq`.
