### ISSUE TITLE
GettingError While writing Code or anything on Jupyter

### ISSUE THREAD

**Issue by RamMishra1** [jupyter/notebook#5711]
Traceback (most recent call last):
  File "C:\Users\rmish\AppData\Roaming\Python\Python38\site-packages\tornado\web.py", line 1703, in _execute
    result = await result
  File "C:\Users\rmish\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\rmish\AppData\Roaming\Python\Python38\site-packages\notebook\services\sessions\handlers.py", line 69, in post
    model = yield maybe_future(
  File "C:\Users\rmish\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\rmish\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\rmish\AppData\Roaming\Python\Python38\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\rmish\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\rmish\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\rmish\AppData\Roaming\Python\Python38\site-packages\notebook\services\sessions\sessionmanager.py", line 100, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "C:\Users\rmish\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\rmish\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\rmish\AppData\Roaming\Python\Python38\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\rmish\AppData\Roaming\Python\Python38\site-packages\jupyter_client\multikernelmanager.py", line 158, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\rmish\AppData\Roaming\Python\Python38\site-packages\jupyter_client\manager.py", line 301, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "C:\Users\rmish\AppData\Roaming\Python\Python38\site-packages\jupyter_client\manager.py", line 248, in pre_start_kernel
    self.write_connection_file()
  File "C:\Users\rmish\AppData\Roaming\Python\Python38\site-packages\jupyter_client\connect.py", line 468, in write_connection_file
    self.connection_file, cfg = write_connection_file(self.connection_file,
  File "C:\Users\rmish\AppData\Roaming\Python\Python38\site-packages\jupyter_client\connect.py", line 138, in write_connection_file
    with secure_write(fname) as f:
  File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "C:\Users\rmish\AppData\Roaming\Python\Python38\site-packages\jupyter_core\paths.py", line 435, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\rmish\AppData\Roaming\Python\Python38\site-packages\jupyter_core\paths.py", line 361, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed while importing win32api: %1 is not a valid Win32 application.
[
![Jy](https://user-images.githubusercontent.com/70471099/91656971-f3117880-eada-11ea-9006-bad493827aa7.PNG)
](url)

**Comment by kevin-bates** [comment]
Please take a look at this [section of the docs](https://jupyter-notebook.readthedocs.io/en/latest/troubleshooting.html#windows-systems).  If the issue persists, please see [this section](https://jupyter-notebook.readthedocs.io/en/latest/troubleshooting.html#gathering-information).
