### ISSUE TITLE
Err_Connection_Closed Jupyter Notebook on AWS EC2 Instance 

### ISSUE THREAD

**Issue by valverde667** [jupyter/notebook#5723]
I am having trouble launching jupyter in my EC2 instance. When entering https://public-dns:8888/ I keep getting an Err_Connection_Closed message in the browser and error messages in my terminal. Below are the steps. 

### Step 1 ssh into instance 
```
(base) ➜  deep-learning-with-python ssh -i "dl4p.pem" ubuntu@ec2-18-191-6-19.us-east-2.compute.amazonaws.com

=============================================================================
       __|  __|_  )
       _|  (     /   Deep Learning Base AMI (Ubuntu 18.04) Version 27.0
      ___|\___|___|
=============================================================================

Welcome to Ubuntu 18.04.5 LTS (GNU/Linux 5.3.0-1033-aws x86_64v)

Nvidia driver version: 450.51.05
CUDA versions available: cuda-10.0 cuda-10.1 cuda-10.2 
Default CUDA version is 10.0 
Libraries: cuDNN, NCCL, Intel MKL-DNN

AWS Deep Learning AMI Homepage: https://aws.amazon.com/machine-learning/amis/
Developer Guide and Release Notes: https://docs.aws.amazon.com/dlami/latest/devguide/what-is-dlami.html
Support: https://forums.aws.amazon.com/forum.jspa?forumID=263
For a fully managed experience, check out Amazon SageMaker at https://aws.amazon.com/sagemaker
When using INF1 type instances, please update regularly using the instructions at: https://github.com/aws/aws-neuron-sdk/tree/master/release-notes
=============================================================================

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Wed Sep  2 02:18:46 UTC 2020

  System load:  0.0                Processes:              121
  Usage of /:   50.8% of 48.41GB   Users logged in:        0
  Memory usage: 1%                 IP address for eth0:    172.31.29.16
  Swap usage:   0%                 IP address for docker0: 172.17.0.1

 * Kubernetes 1.19 is out! Get it in one command with:

     sudo snap install microk8s --channel=1.19 --classic

   https://microk8s.io/ has docs and details.

24 packages can be updated.
0 updates are security updates.


Last login: Wed Sep  2 02:14:35 2020 from 70.162.45.208

```

### Step 2 execute jupyter notebook 

```
ubuntu@ip-172-31-29-16:~$ jupyter notebook
[I 02:18:53.518 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
[I 02:18:53.523 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[I 02:18:54.103 NotebookApp] [nb_anacondacloud] enabled
[I 02:18:54.107 NotebookApp] [nb_conda] enabled
[I 02:18:54.170 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 02:18:54.171 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
[I 02:18:54.173 NotebookApp] Serving notebooks from local directory: /home/ubuntu
[I 02:18:54.173 NotebookApp] 0 active kernels 
[I 02:18:54.173 NotebookApp] The Jupyter Notebook is running at: https://[all ip addresses on your system]:8888/
[I 02:18:54.173 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```

### Step 3 Return to terminal and find error messages 

```
[E 02:19:18.956 NotebookApp] Exception in callback (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8888)>, <function wrap.<locals>.null_wrapper at 0x7fd836d5d048>)
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 276, in accept_handler
        callback(connection, address)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/tcpserver.py", line 264, in _handle_connection
        do_handshake_on_connect=False)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 517, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 494, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    PermissionError: [Errno 13] Permission denied
[E 02:19:18.961 NotebookApp] Exception in callback (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8888)>, <function wrap.<locals>.null_wrapper at 0x7fd836d5d048>)
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 276, in accept_handler
        callback(connection, address)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/tcpserver.py", line 264, in _handle_connection
        do_handshake_on_connect=False)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 517, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 494, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    PermissionError: [Errno 13] Permission denied
[E 02:19:19.118 NotebookApp] Exception in callback (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8888)>, <function wrap.<locals>.null_wrapper at 0x7fd836d5d048>)
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 276, in accept_handler
        callback(connection, address)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/tcpserver.py", line 264, in _handle_connection
        do_handshake_on_connect=False)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 517, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 494, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    PermissionError: [Errno 13] Permission denied
[E 02:19:19.127 NotebookApp] Exception in callback (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8888)>, <function wrap.<locals>.null_wrapper at 0x7fd836d5d048>)
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 276, in accept_handler
        callback(connection, address)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/tcpserver.py", line 264, in _handle_connection
        do_handshake_on_connect=False)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 517, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 494, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    PermissionError: [Errno 13] Permission denied
[E 02:19:19.612 NotebookApp] Exception in callback (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8888)>, <function wrap.<locals>.null_wrapper at 0x7fd836d5d048>)
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 276, in accept_handler
        callback(connection, address)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/tcpserver.py", line 264, in _handle_connection
        do_handshake_on_connect=False)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 517, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 494, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    PermissionError: [Errno 13] Permission denied
[E 02:19:19.623 NotebookApp] Exception in callback (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8888)>, <function wrap.<locals>.null_wrapper at 0x7fd836d5d048>)
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 276, in accept_handler
        callback(connection, address)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/tcpserver.py", line 264, in _handle_connection
        do_handshake_on_connect=False)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 517, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 494, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    PermissionError: [Errno 13] Permission denied
[E 02:19:19.768 NotebookApp] Exception in callback (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8888)>, <function wrap.<locals>.null_wrapper at 0x7fd836d5d048>)
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 276, in accept_handler
        callback(connection, address)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/tcpserver.py", line 264, in _handle_connection
        do_handshake_on_connect=False)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 517, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 494, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    PermissionError: [Errno 13] Permission denied
[E 02:19:19.779 NotebookApp] Exception in callback (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8888)>, <function wrap.<locals>.null_wrapper at 0x7fd836d5d048>)
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 276, in accept_handler
        callback(connection, address)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/tcpserver.py", line 264, in _handle_connection
        do_handshake_on_connect=False)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 517, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 494, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    PermissionError: [Errno 13] Permission denied
[E 02:19:20.066 NotebookApp] Exception in callback (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8888)>, <function wrap.<locals>.null_wrapper at 0x7fd836d5d048>)
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 276, in accept_handler
        callback(connection, address)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/tcpserver.py", line 264, in _handle_connection
        do_handshake_on_connect=False)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 517, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 494, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    PermissionError: [Errno 13] Permission denied
[E 02:19:20.070 NotebookApp] Exception in callback (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8888)>, <function wrap.<locals>.null_wrapper at 0x7fd836d5d048>)
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 276, in accept_handler
        callback(connection, address)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/tcpserver.py", line 264, in _handle_connection
        do_handshake_on_connect=False)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 517, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 494, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    PermissionError: [Errno 13] Permission denied
[E 02:19:20.226 NotebookApp] Exception in callback (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8888)>, <function wrap.<locals>.null_wrapper at 0x7fd836d5d048>)
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 276, in accept_handler
        callback(connection, address)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/tcpserver.py", line 264, in _handle_connection
        do_handshake_on_connect=False)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 517, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 494, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    PermissionError: [Errno 13] Permission denied
[E 02:19:20.227 NotebookApp] Exception in callback (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8888)>, <function wrap.<locals>.null_wrapper at 0x7fd836d5d048>)
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 276, in accept_handler
        callback(connection, address)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/tcpserver.py", line 264, in _handle_connection
        do_handshake_on_connect=False)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 517, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 494, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    PermissionError: [Errno 13] Permission denied
[E 02:19:25.410 NotebookApp] Exception in callback (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8888)>, <function wrap.<locals>.null_wrapper at 0x7fd836d5d048>)
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 276, in accept_handler
        callback(connection, address)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/tcpserver.py", line 264, in _handle_connection
        do_handshake_on_connect=False)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 517, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 494, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    PermissionError: [Errno 13] Permission denied
[E 02:19:25.411 NotebookApp] Exception in callback (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8888)>, <function wrap.<locals>.null_wrapper at 0x7fd836d5d048>)
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 276, in accept_handler
        callback(connection, address)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/tcpserver.py", line 264, in _handle_connection
        do_handshake_on_connect=False)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 517, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 494, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    PermissionError: [Errno 13] Permission denied
[E 02:19:25.572 NotebookApp] Exception in callback (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8888)>, <function wrap.<locals>.null_wrapper at 0x7fd836d5d048>)
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 276, in accept_handler
        callback(connection, address)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/tcpserver.py", line 264, in _handle_connection
        do_handshake_on_connect=False)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 517, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 494, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    PermissionError: [Errno 13] Permission denied
[E 02:19:25.572 NotebookApp] Exception in callback (<socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 8888)>, <function wrap.<locals>.null_wrapper at 0x7fd836d5d048>)
    Traceback (most recent call last):
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
        handler_func(fd_obj, events)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
        return fn(*args, **kwargs)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 276, in accept_handler
        callback(connection, address)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/tcpserver.py", line 264, in _handle_connection
        do_handshake_on_connect=False)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 517, in ssl_wrap_socket
        context = ssl_options_to_context(ssl_options)
      File "/home/ubuntu/anaconda3/lib/python3.5/site-packages/tornado/netutil.py", line 494, in ssl_options_to_context
        context.load_cert_chain(ssl_options['certfile'], ssl_options.get('keyfile', None))
    PermissionError: [Errno 13] Permission denied
```
### Further Information 
**My system**: 
-macOS Catalina version 10.15.6

**Instance Details** 
-AWS Deep Learning AMI (Ubuntu 18.04) V32.0 (according to the selection but the terminal output says V27)
-Instance type: t2.xlarge
-Security settings: for both inbound and outbound rules I have two rules. One rule has all ports and all protocols. The second rule has only a difference in port range = 8888 

**Jupyter config file**
```
c = get_config()
c.NotebookApp.certfile = u'/home/ubuntu/certs/mycert.pem'
c.NotebookApp.keyfile = u'/home/ubuntu/certs/mycert.key'
c.NotebookApp.ip = '*'
c.NotebookApp.open_browser = False
c.NotebookApp.password = u'passwordstuff'
c.NotebookApp.port = 8888
```

### Previous Attempts
- Tunneling using -L command. No avail 
- Redoing instance multiple times
- Setting different ports 

I am at a complete loss as I have tried everything the Google has to offer. Please help.

**Comment by valverde667** [comment]
I was able to access Jupyter through Safari. Firefox and Chrome do not work. It would be nice to enable it with chrome but not necessary.
