### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/home/user/notebooks' 

### ISSUE THREAD

**Issue by yadav-suraj** [jupyter/notebook#5727]
Server error: Traceback (most recent call last): File "/snap/jupyter/6/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute result = await result File "/snap/jupyter/6/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper yielded = next(result) File "/snap/jupyter/6/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 112, in get path=path, type=type, format=format, content=content, File "/snap/jupyter/6/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 431, in get model = self._dir_model(path, content=content) File "/snap/jupyter/6/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 313, in _dir_model for name in os.listdir(os_dir): PermissionError: [Errno 13] Permission denied: '/home/user/notebooks' 

How do I change permission of this particular folder to comply with jupyter? Only this folder which has all the work is denying access to the jupyter notebook. This error message shows up in browser window of jupyter notebook (localhost). OS: Ubuntu. environment manager: Anaconda. Please help!

**Comment by yadav-suraj** [comment]
So the user and group of the folder was changed to nobody and nogroup as I tried several things on that folder to share it across dual boot system. My bad!

This fixed it: 
`sudo chown -R user:group folder-path
`
replace user and group with your system username and group name. folder-path is path to the folder you can't access
