### ISSUE TITLE
Problem launching Jupyter notebook

### ISSUE THREAD

**Issue by Faur** [jupyter/notebook#5735]
Launching jupyter notebook failed, and I don't understand why.

My setup
* Ubuntu 16.04 LTS
* Python 3.5.6 |Anaconda 4.2.0 (64-bit)

The output of `conda list | grep jupyter` is:

```
jupyter                   1.0.0                    py35_7  
jupyter-client            5.2.3                     <pip>
jupyter-core              4.4.0                     <pip>
jupyter_client            5.3.3                      py_0  
jupyter_console           5.2.0            py35h4044a63_1  
jupyter_core              4.5.0                      py_0  
jupyterlab                2.1.0                      py_0    conda-forge
jupyterlab_server         1.0.0                      py_0  
```

When I typed `jupyter notebook` in the terminal I got:
```
[I 00:02:43.841 NotebookApp] [nb_conda_kernels] enabled, 4 kernels found
Traceback (most recent call last):
  File "/home/toke/anaconda3/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/home/toke/anaconda3/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/toke/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/home/toke/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/toke/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 1602, in initialize
    self.init_webapp()
  File "/home/toke/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 1354, in init_webapp
    self.jinja_environment_options,
  File "/home/toke/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 158, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/home/toke/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 275, in init_settings
    nbextensions_path=jupyter_app.nbextensions_path,
  File "/home/toke/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 1042, in nbextensions_path
    from IPython.paths import get_ipython_dir
  File "/home/toke/anaconda3/lib/python3.5/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/home/toke/anaconda3/lib/python3.5/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/home/toke/anaconda3/lib/python3.5/site-packages/IPython/terminal/interactiveshell.py", line 32, in <module>
    from .debugger import TerminalPdb, Pdb
  File "/home/toke/anaconda3/lib/python3.5/site-packages/IPython/terminal/debugger.py", line 6, in <module>
    from IPython.core.completer import IPCompleter
  File "/home/toke/anaconda3/lib/python3.5/site-packages/IPython/core/completer.py", line 146, in <module>
    import jedi
  File "/home/toke/anaconda3/lib/python3.5/site-packages/jedi/__init__.py", line 41, in <module>
    from jedi.api import Script, Interpreter, set_debug_function, \
  File "/home/toke/anaconda3/lib/python3.5/site-packages/jedi/api/__init__.py", line 15, in <module>
    import parso
  File "/home/toke/anaconda3/lib/python3.5/site-packages/parso/__init__.py", line 41, in <module>
    from parso.parser import ParserSyntaxError
  File "/home/toke/anaconda3/lib/python3.5/site-packages/parso/parser.py", line 113
    node_map: Dict[str, type] = {}
            ^
SyntaxError: invalid syntax

```

**Comment by kevin-bates** [comment]
In briefly looking into this and starting [here](https://github.com/spyder-ide/spyder/issues/13605), this appears to be an issue with `parso` and conda in that conda is installing `parso 0.8` in python 3.5 environments despite the fact that `parso` 0.8 does not support Python 3.5.  A workaround that has been successful appears to be a downgrade of `parso` to `0.7`.

Since this is not related to this repository, I'm closing the issue.
