### ISSUE TITLE
Unable to Navigate to few folders in Jupyter Noteboook

### ISSUE THREAD

**Issue by Abhilash-vaidhya** [jupyter/notebook#5751]
I use MacOSCatalina V10.15.6
 jupyter lab - 1.1.4
 jupyter notebook - 6.0.1

I am not able to navigate to few folders via jupyter lab, but the same is accessible via jupyter notebook.

The following error gets logged in the anaconda terminal when i try to access those folders

```
[I 10:44:05.815 LabApp] The port 8888 is already in use, trying another port.
[I 10:44:05.816 LabApp] The port 8889 is already in use, trying another port.
[I 10:44:05.816 LabApp] The port 8890 is already in use, trying another port.
[I 10:44:05.817 LabApp] The port 8891 is already in use, trying another port.
[I 10:44:05.817 LabApp] The port 8892 is already in use, trying another port.
[I 10:44:05.831 LabApp] JupyterLab extension loaded from /Users/avaidhya/opt/anaconda3/lib/python3.7/site-packages/jupyterlab
[I 10:44:05.831 LabApp] JupyterLab application directory is /Users/avaidhya/opt/anaconda3/share/jupyter/lab
[I 10:44:05.834 LabApp] Serving notebooks from local directory: /Users/avaidhya
[I 10:44:05.834 LabApp] The Jupyter Notebook is running at:
[I 10:44:05.834 LabApp] http://localhost:8796/?token=e223e11a4a2f022a375cf38b02fb7bc98167c1edcf725e38
[I 10:44:05.834 LabApp] or http://127.0.0.1:8796/?token=e223e11a4a2f022a375cf38b02fb7bc98167c1edcf725e38
[I 10:44:05.834 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:44:05.843 LabApp] 

To access the notebook, open this file in a browser:
file:///Users/avaidhya/Library/Jupyter/runtime/nbserver-28907-open.html
Or copy and paste one of these URLs:
http://localhost:8796/?token=e223e11a4a2f022a375cf38b02fb7bc98167c1edcf725e38
or http://127.0.0.1:8796/?token=e223e11a4a2f022a375cf38b02fb7bc98167c1edcf725e38
[W 10:44:08.008 LabApp] Could not determine jupyterlab build status without nodejs
[E 10:44:13.161 LabApp] Uncaught exception GET /api/contents/Documents?content=1&1600060453156 (::1)
HTTPServerRequest(protocol='http', host='localhost:8796', method='GET', uri='/api/contents/Documents?content=1&1600060453156', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
File "/Users/avaidhya/opt/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
result = await result
File "/Users/avaidhya/opt/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
yielded = next(result)
File "/Users/avaidhya/opt/anaconda3/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 112, in get
path=path, type=type, format=format, content=content,
File "/Users/avaidhya/opt/anaconda3/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 431, in get
model = self._dir_model(path, content=content)
File "/Users/avaidhya/opt/anaconda3/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 313, in _dir_model
for name in os.listdir(os_dir):
PermissionError: [Errno 1] Operation not permitted: '/Users/avaidhya/Documents'
[W 10:44:13.170 LabApp] Unhandled error
[E 10:44:13.170 LabApp] {
"Host": "localhost:8796",
"Connection": "keep-alive",
"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.83 Safari/537.36",
"X-Xsrftoken": "2|06c4062e|e19a4880af52ed106d480e60930be491|1599996995",
"Authorization": "token e223e11a4a2f022a375cf38b02fb7bc98167c1edcf725e38",
"Content-Type": "application/json",
"Accept": "*/*",
"Sec-Fetch-Site": "same-origin",
"Sec-Fetch-Mode": "cors",
"Sec-Fetch-Dest": "empty",
"Referer": "http://localhost:8796/lab",
"Accept-Encoding": "gzip, deflate, br",
"Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
"Cookie": "_xsrf=2|06c4062e|e19a4880af52ed106d480e60930be491|1599996995; username-localhost-8890=\"2|1:0|10:1599997114|23:username-localhost-8890|44:ZjM0NDBiMTIxNjQzNGE2MWJjMDBhYTY2ZDUwYjkwYTE=|439bb0cb11ecc954aa382f7b4be18430739f8ed20f4fbc4c4eeac97e9549f668\"; username-localhost-8891=\"2|1:0|10:1600007015|23:username-localhost-8891|44:NjhlZDYzYjBlMjMwNDQxZmE5YzY5ZTcyYWM5NDRiMWI=|2dbc9c260ee8768f56cd99d9978a54fc976f03a6a52e058d629df62057dc96a4\"; username-localhost-8892=\"2|1:0|10:1600055176|23:username-localhost-8892|44:NjdhNTk0OGYyODM2NDRjMWFkOWY4OTQ5MGM0ZTI4ZWY=|085e16f1e4bc9c6048536b2a51b3d5d8d6192b3f37cd7ad8ebfa989600e76dfe\"; username-localhost-8985=\"2|1:0|10:1600055395|23:username-localhost-8985|44:YjNhNGZhZTIyZDQwNDFiYTllMjYxZjI2MDA4NmU1M2E=|71c4a4d9b7746f9ae683707f19570cb0cbca1e9cdcd524ad953f37a75ba27a3b\"; username-localhost-8958=\"2|1:0|10:1600055484|23:username-localhost-8958|44:NjAyMTc3ODE0N2ZjNGFlNDhiOTUwNzdkZGQxNjY0ZjQ=|1535c70d47df09b10d84efd37ce5727932db4d1ebf032d443bff1b12a42cf395\"; username-localhost-8953=\"2|1:0|10:1600055545|23:username-localhost-8953|44:NTgwOGQ1YzgzMGM2NDBmZGEwOTUxMDE3OTg4MmJkMWI=|5cac9c728e145f86cfa1077898678598efa4503acdf4008e10330d4acaff4ddd\"; username-localhost-8807=\"2|1:0|10:1600055717|23:username-localhost-8807|44:MjRlY2RlN2M3YzgwNDNlZmFhYzhlNWI1ZmJkNTU0YTM=|7a25b2e53c238437b52e855737847c42a45b4216753d68d9d469738c73577f28\"; username-localhost-8918=\"2|1:0|10:1600056310|23:username-localhost-8918|44:ZmRkMWY3YTA3OTI5NGJkMzkxNDFiNDAzNzY3MGFjMzg=|6f53a8275440d01bbe516f4416b006cb22aeb92d3dc6f1349d554738cfcfb86c\"; username-localhost-8791=\"2|1:0|10:1600056475|23:username-localhost-8791|44:ZmEzNjNhYWMxYjg2NDdlYTlmOTFiMzA1MWViNjcwZmI=|80aaf53c4fc0759d1054955892d205c0a675576a70dea82b468270140ca8129b\"; username-localhost-8869=\"2|1:0|10:1600056648|23:username-localhost-8869|44:NDE0NjJjOTBkMjA2NDgxNWE0NTc4ZTg1MTIyZDBhNWM=|4dbbbb0030cbda204a7e0645121c36e0a94572a25be1cfa2f10b2ada2ed19727\"; username-localhost-8928=\"2|1:0|10:1600059916|23:username-localhost-8928|44:Nzc2ZTJlOGM3NzdjNGM5OGE0YTJmYWJlMDRmMjg2OGU=|02684cb8c1264d25ca178170ed11e6346d1a40c72b3568db21f9f0886f1266ca\"; username-localhost-8833=\"2|1:0|10:1600060351|23:username-localhost-8833|44:YTMxNmMxZTEzZjRmNGMxOTkyMWFiNDAyZjI3YzgwYTA=|0f0069bceab60bb97b1cfb42e59cc3fd6b021d87f8d120539280b6640e7d49d8\"; username-localhost-8796=\"2|1:0|10:1600060452|23:username-localhost-8796|44:YzJkNjMwYWY5ZGM5NGZkYjgwN2M4MDgyODQ2MjFhZWU=|4beb2a3c1622a326ea069505c834ecfd5e9381a9165d3b6ee4385bd2f6c5b3f4\""
}
[E 10:44:13.170 LabApp] 500 GET /api/contents/Documents?content=1&1600060453156 (::1) 11.15ms referer=http://localhost:8796/lab
```

To Note: The navigation to same folders were working earlier , but erring out all of a sudden.
Any help on this is much appreciated

**Comment by kevin-bates** [comment]
Did you recently update the MacOS to Catalina?  If so, [this](https://stackoverflow.com/questions/58479686/permissionerror-errno-1-operation-not-permitted-after-macos-catalina-update) might help.

I would also recommend terminating the other notebook servers that are likely running based on your _port-in-use_ messages at startup.  I doubt that's coming into play but it can exacerbate troubleshooting.  A combination of `jupyter notebook list` and `jupyter notebook stop` can be used to accomplish that cleanup.

**Comment by Abhilash-vaidhya** [comment]
Unfortunately the given link didn't help.

I have terminated all the jupyter process running on varied ports and launched jupyter lab running on port 8888.The issue is still seen.
```
[I 09:03:02.072 LabApp] JupyterLab extension loaded from /Users/avaidhya/opt/anaconda3/lib/python3.7/site-packages/jupyterlab
[I 09:03:02.072 LabApp] JupyterLab application directory is /Users/avaidhya/opt/anaconda3/share/jupyter/lab
[I 09:03:02.073 LabApp] Serving notebooks from local directory: /Users/avaidhya
[I 09:03:02.074 LabApp] The Jupyter Notebook is running at:
[I 09:03:02.074 LabApp] http://localhost:8888/?token=09cda8fbc3d888a95c1536a5d4a6a78ac971bd6353d4a52b
[I 09:03:02.074 LabApp] or http://127.0.0.1:8888/?token=09cda8fbc3d888a95c1536a5d4a6a78ac971bd6353d4a52b
[I 09:03:02.074 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:03:02.078 LabApp] 

To access the notebook, open this file in a browser:
file:///Users/avaidhya/Library/Jupyter/runtime/nbserver-1954-open.html
Or copy and paste one of these URLs:
http://localhost:8888/?token=09cda8fbc3d888a95c1536a5d4a6a78ac971bd6353d4a52b
or http://127.0.0.1:8888/?token=09cda8fbc3d888a95c1536a5d4a6a78ac971bd6353d4a52b
[W 09:03:05.602 LabApp] Could not determine jupyterlab build status without nodejs
[E 09:03:10.176 LabApp] Uncaught exception GET /api/contents/Documents?content=1&1600140790171 (::1)
HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/contents/Documents?content=1&1600140790171', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
File "/Users/avaidhya/opt/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
result = await result
File "/Users/avaidhya/opt/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
yielded = next(result)
File "/Users/avaidhya/opt/anaconda3/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 112, in get
path=path, type=type, format=format, content=content,
File "/Users/avaidhya/opt/anaconda3/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 431, in get
model = self._dir_model(path, content=content)
File "/Users/avaidhya/opt/anaconda3/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 313, in _dir_model
for name in os.listdir(os_dir):
PermissionError: [Errno 1] Operation not permitted: '/Users/avaidhya/Documents'
[W 09:03:10.187 LabApp] Unhandled error
[E 09:03:10.187 LabApp] {
"Host": "localhost:8888",
"Connection": "keep-alive",
"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36",
"X-Xsrftoken": "2|718e5d8c|9afa9b1a09f7ea83b3d0ea860b5cabe1|1600140784",
"Authorization": "token 09cda8fbc3d888a95c1536a5d4a6a78ac971bd6353d4a52b",
"Content-Type": "application/json",
"Accept": "*/*",
"Sec-Fetch-Site": "same-origin",
"Sec-Fetch-Mode": "cors",
"Sec-Fetch-Dest": "empty",
"Referer": "http://localhost:8888/lab",
"Accept-Encoding": "gzip, deflate, br",
"Accept-Language": "en-GB,en-US;q=0.9,en;q=0.8",
"Cookie": "username-localhost-8892=\"2|1:0|10:1600055176|23:username-localhost-8892|44:NjdhNTk0OGYyODM2NDRjMWFkOWY4OTQ5MGM0ZTI4ZWY=|085e16f1e4bc9c6048536b2a51b3d5d8d6192b3f37cd7ad8ebfa989600e76dfe\"; username-localhost-8985=\"2|1:0|10:1600055395|23:username-localhost-8985|44:YjNhNGZhZTIyZDQwNDFiYTllMjYxZjI2MDA4NmU1M2E=|71c4a4d9b7746f9ae683707f19570cb0cbca1e9cdcd524ad953f37a75ba27a3b\"; username-localhost-8958=\"2|1:0|10:1600055484|23:username-localhost-8958|44:NjAyMTc3ODE0N2ZjNGFlNDhiOTUwNzdkZGQxNjY0ZjQ=|1535c70d47df09b10d84efd37ce5727932db4d1ebf032d443bff1b12a42cf395\"; username-localhost-8953=\"2|1:0|10:1600055545|23:username-localhost-8953|44:NTgwOGQ1YzgzMGM2NDBmZGEwOTUxMDE3OTg4MmJkMWI=|5cac9c728e145f86cfa1077898678598efa4503acdf4008e10330d4acaff4ddd\"; username-localhost-8807=\"2|1:0|10:1600055717|23:username-localhost-8807|44:MjRlY2RlN2M3YzgwNDNlZmFhYzhlNWI1ZmJkNTU0YTM=|7a25b2e53c238437b52e855737847c42a45b4216753d68d9d469738c73577f28\"; username-localhost-8918=\"2|1:0|10:1600056310|23:username-localhost-8918|44:ZmRkMWY3YTA3OTI5NGJkMzkxNDFiNDAzNzY3MGFjMzg=|6f53a8275440d01bbe516f4416b006cb22aeb92d3dc6f1349d554738cfcfb86c\"; username-localhost-8791=\"2|1:0|10:1600056475|23:username-localhost-8791|44:ZmEzNjNhYWMxYjg2NDdlYTlmOTFiMzA1MWViNjcwZmI=|80aaf53c4fc0759d1054955892d205c0a675576a70dea82b468270140ca8129b\"; username-localhost-8869=\"2|1:0|10:1600056648|23:username-localhost-8869|44:NDE0NjJjOTBkMjA2NDgxNWE0NTc4ZTg1MTIyZDBhNWM=|4dbbbb0030cbda204a7e0645121c36e0a94572a25be1cfa2f10b2ada2ed19727\"; username-localhost-8928=\"2|1:0|10:1600059916|23:username-localhost-8928|44:Nzc2ZTJlOGM3NzdjNGM5OGE0YTJmYWJlMDRmMjg2OGU=|02684cb8c1264d25ca178170ed11e6346d1a40c72b3568db21f9f0886f1266ca\"; username-localhost-8833=\"2|1:0|10:1600061125|23:username-localhost-8833|44:NTU1YTAzYmZmZjg2NGVkZTk0ZDIxZDAzMWIzYjM3ZDg=|d9f017ade304d407147297b682a80ee192d2fcc53af361c2d91bcb21a08f2057\"; username-localhost-8937=\"2|1:0|10:1600061138|23:username-localhost-8937|44:MTVhMDVlYjE0ODAyNGY1ZGI2YWNiOGVkM2IzN2NiYzU=|d41670cfb3d83cd486f6f11d6d4fc8cf6b6fc6d7c66921944b8dc355310a603d\"; username-localhost-8796=\"2|1:0|10:1600061170|23:username-localhost-8796|44:Y2E0NjJkNDRhY2EwNDIxMmE0NTdkNjkxMmQ5MDNlZDA=|e479a0d5851c51fa00ee4c41f43b37dccaefd67f7b5de0862e0156ddf6aadc4e\"; username-localhost-8890=\"2|1:0|10:1600061522|23:username-localhost-8890|44:NWVhM2JkNzAyMDY3NDRiN2JlYWVmOTk0Y2MzZWE2MzY=|b4907c86ef29b0004f45950a53f716a9575e40e24c17c907d53bae658379beb1\"; username-localhost-8891=\"2|1:0|10:1600100567|23:username-localhost-8891|44:MDE4ODY2MDQzNTFlNDQ2Y2FmZTNhZTI4ODAyZGRjNWQ=|a3958701c0056075a7bfe1c43a0945f05e3e08b2640d74272b6f9da095c09c11\"; _xsrf=2|718e5d8c|9afa9b1a09f7ea83b3d0ea860b5cabe1|1600140784; username-localhost-8888=\"2|1:0|10:1600140790|23:username-localhost-8888|44:MzVjOGM1NTJmNjBiNDJhYmJkZTYzMTdkZjdlMTM0OWQ=|fffe34d3a84437056c52851246fd334850c3bb073306612259cde452e5bae58b\""
}
[E 09:03:10.187 LabApp] 500 GET /api/contents/Documents?content=1&1600140790171 (::1) 12.93ms referer=http://localhost:8888/lab
```
Point to Note is only in Jupyter Lab the issue is seen whereas in jupyter notebook folder navigation is succesful

**Comment by kevin-bates** [comment]
> Point to Note is only in Jupyter Lab the issue is seen whereas in jupyter notebook folder navigation is successful

> Also only navigation to folders such as Documents,Downloads,Desktop are failing.Rest other folder navigation works fine with jupyter lab as well.It seems to be some sort of permission issue.Not Really sure what config should be done.

Interesting.  I don't have any idea why the frontend would change this particular behavior.  @jasongrout - do you have any ideas here?

I'm unable to reproduce the issue but do see these "system-created" directories on MacOS tend to only be navigable by their owner and not group and others (e.g., `drwx------` vs. `drwxr-xr-x`).  So if you happened to start your notebook server as a different user (which I'm sure is not the case) you'd probably see similar issues, although I would still expect the same behavior within Notebook and Lab frontends.
