### ISSUE TITLE
Exception: Jupyter command `jupyter-notebook` not found.

### ISSUE THREAD

**Issue by dacampos137** [jupyter/notebook#5754]
HI I have this problem and I am trying this tutorial https://lerryws.xyz/posts/PyQGIS-in-Jupyter-Notebook basically I want to Qgis functions in Jupiter  and I wanted using OSgeo4W shell, also I tried to use conda install Qgis but then I have other error 

C:\>run-jupyter.bat
The system cannot find the path specified.
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\OSGeo4W\apps\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\OSGeo4W\apps\Python37\Scripts\jupyter.exe\__main__.py", line 7, in <module>
  File "C:\OSGeo4W\apps\Python37\lib\site-packages\jupyter_core\command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "C:\OSGeo4W\apps\Python37\lib\site-packages\jupyter_core\command.py", line 134, in _jupyter_abspath
    'Jupyter command `{}` not found.'.format(jupyter_subcommand)
Exception: Jupyter command `jupyter-notebook` not found.

**Comment by Rayman174-A** [comment]
Try writing the complete file path and then running it. Also check for the jupyter versions.
