### ISSUE TITLE
running a new cell hangs after running 'warnings.filterwarnings("error")'

### ISSUE THREAD

**Issue by yhidaka** [jupyter/notebook#5757]
After running a cell containing the following lines, running a new cell with any valid/invalid lines of code will result in a hang up, with "[*]" staying forever:

```
import warnings
warnings.filterwarnings("error")
```
with the following error message in the terminal:

```
-----------------------------------------------------------------------------------------------------------------------------------
[I 11:51:53.200 NotebookApp] Serving notebooks from local directory: /home/yhidaka/bug_reports
[I 11:51:53.200 NotebookApp] Jupyter Notebook 6.1.1 is running at:
[I 11:51:53.200 NotebookApp] http://localhost:8084/
[I 11:51:53.200 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 11:51:56.642 NotebookApp] Kernel started: b1d404cb-853f-4844-bc0d-acf09211b861, name: python3
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/home/yhidaka/conda_envs/bug_jupy/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/yhidaka/conda_envs/bug_jupy/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/yhidaka/conda_envs/bug_jupy/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/home/yhidaka/conda_envs/bug_jupy/lib/python3.7/site-packages/ipykernel/kernelbase.py", line 545, in execute_request
    user_expressions, allow_stdin,
  File "/home/yhidaka/conda_envs/bug_jupy/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/home/yhidaka/conda_envs/bug_jupy/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/yhidaka/conda_envs/bug_jupy/lib/python3.7/site-packages/ipykernel/ipkernel.py", line 287, in do_execute
    and should_run_async(code)
  File "/home/yhidaka/conda_envs/bug_jupy/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 2962, in should_run_async
    stacklevel=2,
DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
-----------------------------------------------------------------------------------------------------------------------------------
```

A similar issue was reported at:

 https://stackoverflow.com/questions/63886338/jupyter-tornado-deprecationwarning-should-run-async-will-not-call-transfo/63912887#63912887

The following are the series of commands I issued to create the conda environment that results in this error on 09/16/2020:

```
$ conda create -n bug_jupy python=3.7 jupyter -c https://repo.anaconda.com/pkgs/main --no-default-packages
$ conda activate bug_jupy
(bug_jupy) $ conda list
# packages in environment at /home/yhidaka/conda_envs/bug_jupy:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
argon2-cffi               20.1.0           py37h7b6447c_1    defaults
attrs                     20.1.0                     py_0    defaults
backcall                  0.2.0                      py_0    defaults
bleach                    3.1.5                      py_0    defaults
ca-certificates           2020.7.22                     0    defaults
certifi                   2020.6.20                py37_0    defaults
cffi                      1.14.2           py37he30daa8_0    defaults
dbus                      1.13.16              hb2f20db_0    defaults
decorator                 4.4.2                      py_0    defaults
defusedxml                0.6.0                      py_0    defaults
entrypoints               0.3                      py37_0    defaults
expat                     2.2.9                he6710b0_2    defaults
fontconfig                2.13.0               h9420a91_0    defaults
freetype                  2.10.2               h5ab3b9f_0    defaults
glib                      2.65.0               h3eb4bd4_0    defaults
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb31296c_0    defaults
icu                       58.2                 he6710b0_3    defaults
importlib-metadata        1.7.0                    py37_0    defaults
importlib_metadata        1.7.0                         0    defaults
ipykernel                 5.3.4            py37h5ca1d4c_0    defaults
ipython                   7.18.1           py37h5ca1d4c_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
ipywidgets                7.5.1                      py_0    defaults
jedi                      0.17.2                   py37_0    defaults
jinja2                    2.11.2                     py_0    defaults
jpeg                      9b                   h024ee3a_2    defaults
jsonschema                3.2.0                    py37_1    defaults
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            6.1.6                      py_0    defaults
jupyter_console           6.2.0                      py_0    defaults
jupyter_core              4.6.3                    py37_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libedit                   3.1.20191231         h14c3975_1    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libsodium                 1.0.18               h7b6447c_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libxcb                    1.14                 h7b6447c_0    defaults
libxml2                   2.9.10               he19cac6_1    defaults
markupsafe                1.1.1            py37h14c3975_1    defaults
mistune                   0.8.4           py37h14c3975_1001    defaults
nbconvert                 5.6.1                    py37_1    defaults
nbformat                  5.0.7                      py_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
notebook                  6.1.1                    py37_0    defaults
openssl                   1.1.1g               h7b6447c_0    defaults
packaging                 20.4                       py_0    defaults
pandoc                    2.10.1                        0    defaults
pandocfilters             1.4.2                    py37_1    defaults
parso                     0.7.0                      py_0    defaults
pcre                      8.44                 he6710b0_0    defaults
pexpect                   4.8.0                    py37_1    defaults
pickleshare               0.7.5                 py37_1001    defaults
pip                       20.2.2                   py37_0    defaults
prometheus_client         0.8.0                      py_0    defaults
prompt-toolkit            3.0.7                      py_0    defaults
prompt_toolkit            3.0.7                         0    defaults
ptyprocess                0.6.0                    py37_0    defaults
pycparser                 2.20                       py_2    defaults
pygments                  2.7.0                      py_0    defaults
pyparsing                 2.4.7                      py_0    defaults
pyqt                      5.9.2            py37h05f1152_2    defaults
pyrsistent                0.16.0           py37h7b6447c_0    defaults
python                    3.7.9                h7579374_0    defaults
python-dateutil           2.8.1                      py_0    defaults
pyzmq                     19.0.1           py37he6710b0_1    defaults
qt                        5.9.7                h5867ecd_1    defaults
qtconsole                 4.7.6                      py_0    defaults
qtpy                      1.9.0                      py_0    defaults
readline                  8.0                  h7b6447c_0    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                49.6.0                   py37_0    defaults
sip                       4.19.8           py37hf484d3e_0    defaults
six                       1.15.0                     py_0    defaults
sqlite                    3.33.0               h62c20be_0    defaults
terminado                 0.8.3                    py37_0    defaults
testpath                  0.4.4                      py_0    defaults
tk                        8.6.10               hbc83047_0    defaults
tornado                   6.0.4            py37h7b6447c_1    defaults
traitlets                 4.3.3                    py37_0    defaults
wcwidth                   0.2.5                      py_0    defaults
webencodings              0.5.1                    py37_1    defaults
wheel                     0.35.1                     py_0    defaults
widgetsnbextension        3.5.1                    py37_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
zeromq                    4.3.2                he6710b0_3    defaults
zipp                      3.1.0                      py_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```
My operating system is:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.12 (stretch)
Release:        9.12
Codename:       stretch
$ uname -r
4.9.0-12-amd64
```

Please let me know if any other information is needed.

**Comment by kevin-bates** [comment]
Hi @yhidaka - this is really an issue with the ipykernel and not this repository.  Please refer to this issue regarding its status: https://github.com/ipython/ipykernel/issues/540

**Comment by yhidaka** [comment]
Thank you @kevin-bates for your reply and pointing to the root cause.
