### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmpt8216r4k'

### ISSUE THREAD

**Issue by AmeerHamzaDev** [jupyter/notebook#5793]
Traceback (most recent call last):
  File "C:\Users\Administrator\anaconda3\envs\tensorflow1\lib\site-packages\flask\app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\Administrator\anaconda3\envs\tensorflow1\lib\site-packages\flask\app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\Administrator\anaconda3\envs\tensorflow1\lib\site-packages\flask\app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Administrator\anaconda3\envs\tensorflow1\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Administrator\anaconda3\envs\tensorflow1\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Administrator\anaconda3\envs\tensorflow1\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Administrator\anaconda3\envs\tensorflow1\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Administrator\anaconda3\envs\tensorflow1\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Administrator\anaconda3\envs\tensorflow1\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Administrator\anaconda3\envs\tensorflow1\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Administrator\Desktop\New folder\realtimeCV-master\obj_detect_multi\detector_app.py", line 304, in imgproc
    result = detect_objects(temp.name)
  File "C:\Users\Administrator\Desktop\New folder\realtimeCV-master\obj_detect_multi\detector_app.py", line 266, in detect_objects
    image = Image.open(image_path).convert('RGB')
  File "C:\Users\Administrator\anaconda3\envs\tensorflow1\lib\site-packages\PIL\Image.py", line 2878, in open
    fp = builtins.open(filename, "rb")
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\tmpt8216r4k'

pls see i am trying to run object detection on flask

**Comment by kevin-bates** [comment]
This doesn't appear related to this repository - closing as invalid.  If there's a correlation, please specify and we can reopen should that prove to be the right action.
