### ISSUE TITLE
Can't launch jupyter

### ISSUE THREAD

**Issue by racle257** [jupyter/notebook#5816]
I have created a new env with python==2.7 and install jupyter by 'pip install jupyter'. Then I run notebook by 'jupyter notebook'. But got this, what is wrong?  Please help me with this, it really confused me.
Traceback (most recent call last):
  File "/data01/home/zhuruofei.2457/CommonLib/py_env/py_27/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/data01/home/zhuruofei.2457/CommonLib/py_env/py_27/local/lib/python2.7/site-packages/notebook/notebookapp.py", line 83, in <module>
    from .services.contents.manager import ContentsManager
  File "/data01/home/zhuruofei.2457/CommonLib/py_env/py_27/local/lib/python2.7/site-packages/notebook/services/contents/manager.py", line 17, in <module>
    from nbformat import sign, validate as validate_nb, ValidationError
  File "/data01/home/zhuruofei.2457/CommonLib/py_env/py_27/local/lib/python2.7/site-packages/nbformat/__init__.py", line 33, in <module>
    from .validator import validate, ValidationError
  File "/data01/home/zhuruofei.2457/CommonLib/py_env/py_27/local/lib/python2.7/site-packages/nbformat/validator.py", line 12, in <module>
    from jsonschema import ValidationError
  File "/data01/home/zhuruofei.2457/CommonLib/py_env/py_27/local/lib/python2.7/site-packages/jsonschema/__init__.py", line 21, in <module>
    from jsonschema._types import TypeChecker
  File "/data01/home/zhuruofei.2457/CommonLib/py_env/py_27/local/lib/python2.7/site-packages/jsonschema/_types.py", line 3, in <module>
    from pyrsistent import pmap
  File "/data01/home/zhuruofei.2457/CommonLib/py_env/py_27/local/lib/python2.7/site-packages/pyrsistent/__init__.py", line 3, in <module>
    from pyrsistent._pmap import pmap, m, PMap
  File "/data01/home/zhuruofei.2457/CommonLib/py_env/py_27/local/lib/python2.7/site-packages/pyrsistent/_pmap.py", line 98
    ) from e
         ^
SyntaxError: invalid syntax

**Comment by kevin-bates** [comment]
Hi.  This issue stems from newer versions of [pyrsistent not working on Python 2.7](https://github.com/tobgu/pyrsistent/issues/207).  Since this is a transitive dependency (via [jsonschema](https://github.com/Julian/jsonschema/issues/741)) there isn't a whole lot we can do.

To get around this immediate issue, you should be able to downgrade your pyrsistent package using the equivalent of `pip install pyrsistent==0.16.0`.  However, please keep in mind that Python 2.7 is no longer supported so you might find similar issues elsewhere and could run into pushback beyond these kinds of downgrade steps you're doing here.

I'm going to close this issue as the downgrade of pyrsistent should get you moving forward.
