### ISSUE TITLE
Cant use jupyter-notebook because of 'kernel error'

### ISSUE THREAD

**Issue by AhsabAli2000** [jupyter/notebook#5829]
Hi everyone, I am getting into data science but cant make jupyter notebook work.It is throwing a 'kernel error' in the top right corner of the editor. I am usig Anaconda3 and downloaded it "OFFICIALLY" from the website and typing jupyter-notebook after activating conda in the command line, here is the error thrown in the editor given below
`Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tornado\web.py", line 1703, in _execute
    result = await result
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\notebook\services\sessions\handlers.py", line 69, in post
    model = yield maybe_future(
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\notebook\services\sessions\sessionmanager.py", line 100, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\jupyter_client\multikernelmanager.py", line 185, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\jupyter_client\manager.py", line 309, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\jupyter_client\manager.py", line 256, in pre_start_kernel
    self.write_connection_file()
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\jupyter_client\connect.py", line 468, in write_connection_file
    self.connection_file, cfg = write_connection_file(self.connection_file,
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\jupyter_client\connect.py", line 138, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\user\anaconda3\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\jupyter_core\paths.py", line 435, in secure_write
    win32_restrict_file_to_user(fname)
  File "C:\Users\user\AppData\Roaming\Python\Python38\site-packages\jupyter_core\paths.py", line 361, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed while importing win32api: %1 is not a valid Win32 application.`

**Comment by kevin-bates** [comment]
Please take a look at this [issue in `jupyter_core`](https://github.com/jupyter/jupyter_core/issues/187).  You might also want to check out the [troubleshooting section of the docs relative pywin32](https://jupyter-notebook.readthedocs.io/en/latest/troubleshooting.html#pywin32-issues).

**Comment by AhsabAli2000** [comment]
`pip install -- pywin32==227` did it for me, thank you for mentioning the issue for me.Now I will close theis issue
