### ISSUE TITLE
send2trash does not work in combination with sshfs on macOS

### ISSUE THREAD

**Issue by croth1** [jupyter/notebook#5830]
I guess in the end this is a send2trash problem, but I guess since notebook chooses to use send2trash for the delete request, it fits here as well:

# Steps to reproduce

```
cd /tmp
mkdir mnt
sshfs some_source:/ mnt
jupyter notebook
```

Creating notebooks in a sub folder in the mounted folder `mnt` via the web interface works as expected, but using the delete button fails with: `An error occurred while deleting "mnt/croth1/tmp/Untitled.ipynb".`

# Error
```
[E 10:01:13.361 NotebookApp] Uncaught exception DELETE /api/contents/mnt/croth1/tmp/Untitled.ipynb (::1)
    HTTPServerRequest(protocol='http', host='localhost:8890', method='DELETE', uri='/api/contents/mnt/croth1/tmp/Untitled.ipynb', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/christian/miniconda3/lib/python3.7/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/Users/christian/miniconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
        yielded = next(result)
      File "/Users/christian/miniconda3/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 237, in delete
        yield maybe_future(cm.delete(path))
      File "/Users/christian/miniconda3/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 279, in delete
        self.delete_file(path)
      File "/Users/christian/miniconda3/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 546, in delete_file
        send2trash(os_path)
      File "/Users/christian/miniconda3/lib/python3.7/site-packages/send2trash/plat_osx.py", line 48, in send2trash
        check_op_result(op_result)
      File "/Users/christian/miniconda3/lib/python3.7/site-packages/send2trash/plat_osx.py", line 37, in check_op_result
        raise OSError(msg)
    OSError: Directory not found
```

**Comment by kevin-bates** [comment]
Although I'm not immediately able to get notebook using an sshfs mounted directory, I am able to perform the test in [`_check_trash()`](https://github.com/jupyter/notebook/blob/master/notebook/services/contents/filemanager.py#L515-L524) that would otherwise be prevented on Macs and find that it would indeed return False.  This would lead to the logging of [this warning message](https://github.com/jupyter/notebook/blob/master/notebook/services/contents/filemanager.py#L549-L550) with the notebook remaining.  As a result, I'm wondering if we shouldn't just open up the code in `_check_trash()` for macs as well.
