### ISSUE TITLE
Unable to start Jupyter notebook after conda update

### ISSUE THREAD

**Issue by czymh** [jupyter/notebook#5833]
Hi, I can't start the Jupyter notebook:
```
Traceback (most recent call last):
  File "/home/chenzhao/anaconda3/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/home/chenzhao/anaconda3/lib/python3.8/site-packages/notebook/notebookapp.py", line 51, in <module>
    from zmq.eventloop import ioloop
  File "/home/chenzhao/anaconda3/lib/python3.8/site-packages/zmq/__init__.py", line 50, in <module>
    from zmq import backend
  File "/home/chenzhao/anaconda3/lib/python3.8/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/chenzhao/anaconda3/lib/python3.8/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/chenzhao/anaconda3/lib/python3.8/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/chenzhao/anaconda3/lib/python3.8/site-packages/zmq/backend/select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/chenzhao/anaconda3/lib/python3.8/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /lib64/libpthread.so.0: version `GLIBC_2.12' not found (required by ~anaconda3/lib/python3.8/site-packages/zmq/backend/cython/../../../../../libzmq.so.5)
```
It was working yesterday. I just upgraded it.

**Comment by kevin-bates** [comment]
Although not identical, the target package (zeromq) is same, so I would try reinstalling zeromq as suggested [here](https://github.com/jupyter/notebook/issues/1632#issuecomment-234976803) before opening an issue with the zmq folks.

**Comment by czymh** [comment]
It doesn't work for me. remove / install or install libsodium change nothing!

**Comment by czymh** [comment]
Reinstall anaconda 2020-02(conda 4.9.1) can work!

**Comment by czymh** [comment]
After some tests, I find that this error is because the version of ‘zeromq’ is too high!
Using the ‘conda install zeromq=4.3.1’ can solve.
Thanks for your suggestion!
