### ISSUE TITLE
Cannot export to html.  getting missing style.min.css error

### ISSUE THREAD

**Issue by hilldog1378** [jupyter/notebook#5843]
while trying to export a notebook to html, I get the following errror with nbconvert:
[E 10:40:53.347 LabApp] nbconvert failed: [Errno 2] No such file or directory: 'C:\\Users\\a714683\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\nbconvert\\resources\\style.min.css'
    Traceback (most recent call last):
      File "C:\Users\a714683\AppData\Local\Continuum\anaconda3\lib\site-packages\notebook\nbconvert\handlers.py", line 132, in get
        resources=resource_dict
      File "C:\Users\a714683\AppData\Local\Continuum\anaconda3\lib\site-packages\nbconvert\exporters\html.py", line 95, in from_notebook_node
        })
      File "C:\Users\a714683\AppData\Local\Continuum\anaconda3\lib\site-packages\nbconvert\exporters\templateexporter.py", line 307, in from_notebook_node
        def _raw_mimetypes_default(self):
      File "C:\Users\a714683\AppData\Local\Continuum\anaconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 139, in from_notebook_node
        if 'language' in nb['metadata']:
      File "C:\Users\a714683\AppData\Local\Continuum\anaconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 316, in _preprocess
        # to each preprocessor
      File "C:\Users\a714683\AppData\Local\Continuum\anaconda3\lib\site-packages\nbconvert\preprocessors\base.py", line 47, in __call__
        return self.preprocess(nb, resources)
      File "C:\Users\a714683\AppData\Local\Continuum\anaconda3\lib\site-packages\nbconvert\preprocessors\csshtmlheader.py", line 55, in preprocess
        preprocessors to pass variables into the Jinja engine.
      File "C:\Users\a714683\AppData\Local\Continuum\anaconda3\lib\site-packages\nbconvert\preprocessors\csshtmlheader.py", line 73, in _generate_header
        # Load the user's custom CSS and IPython's default custom CSS.  If they
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\a714683\\AppData\\Local\\Continuum\\anaconda3\\lib\\site-packages\\nbconvert\\resources\\style.min.css'

**Comment by kevin-bates** [comment]
Looks like you're missing a core file within the `nbconvert` package.  Please try to update or uninstall/install nbconvert such that the missing file is restored.  Should the problem persist, get the version of nbconvert you're using, along with other pertinent information (tracebacks are always welcome), and open an issue in the [nbconvert repo](https://github.com/jupyter/nbconvert).  Thank you.
