### ISSUE TITLE
jupyter notebook connecting to kernel issue

### ISSUE THREAD

**Issue by dharani2002** [jupyter/notebook#5850]
E:\python>C:\Users\91850\AppData\Local\Programs\Python\Python38-32\Scripts\jupyter notebook
[W 11:50:45.659 NotebookApp] Terminals not available (error was No module named 'winpty.cywinpty')
[I 11:50:45.659 NotebookApp] Serving notebooks from local directory: E:\python
[I 11:50:45.659 NotebookApp] Jupyter Notebook 6.1.4 is running at:
[I 11:50:45.660 NotebookApp] http://localhost:8888/?token=f767faaea09e67402b9a62906e36127409ee694487f6be78
[I 11:50:45.660 NotebookApp]  or http://127.0.0.1:8888/?token=f767faaea09e67402b9a62906e36127409ee694487f6be78
[I 11:50:45.660 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 11:50:45.693 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/91850/AppData/Roaming/jupyter/runtime/nbserver-21436-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=f767faaea09e67402b9a62906e36127409ee694487f6be78
     or http://127.0.0.1:8888/?token=f767faaea09e67402b9a62906e36127409ee694487f6be78
[I 11:50:54.567 NotebookApp] Kernel started: aff744b0-d7c5-46cb-8c38-c713daa772bc, name: python3
Traceback (most recent call last):
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\IPython\__init__.py", line 55, in <module>
    from .core.application import Application
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\IPython\core\application.py", line 18, in <module>
    import logging
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\logging\__init__.py", line 28, in <module>
    from string import Template
  File "E:\python\string.py", line 1
    Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
           ^
SyntaxError: invalid syntax
[I 11:50:57.549 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\IPython\__init__.py", line 55, in <module>
    from .core.application import Application
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\IPython\core\application.py", line 18, in <module>
    import logging
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\logging\__init__.py", line 28, in <module>
    from string import Template
  File "E:\python\string.py", line 1
    Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
           ^
SyntaxError: invalid syntax
[I 11:51:00.557 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\IPython\__init__.py", line 55, in <module>
    from .core.application import Application
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\IPython\core\application.py", line 18, in <module>
    import logging
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\logging\__init__.py", line 28, in <module>
    from string import Template
  File "E:\python\string.py", line 1
    Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
           ^
SyntaxError: invalid syntax
[I 11:51:03.605 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\IPython\__init__.py", line 55, in <module>
    from .core.application import Application
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\IPython\core\application.py", line 18, in <module>
    import logging
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\logging\__init__.py", line 28, in <module>
    from string import Template
  File "E:\python\string.py", line 1
    Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
           ^
SyntaxError: invalid syntax
[I 11:51:06.613 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\IPython\__init__.py", line 55, in <module>
    from .core.application import Application
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\IPython\core\application.py", line 18, in <module>
    import logging
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\logging\__init__.py", line 28, in <module>
    from string import Template
  File "E:\python\string.py", line 1
    Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
           ^
SyntaxError: invalid syntax
[W 11:51:09.620 NotebookApp] KernelRestarter: restart failed
[W 11:51:09.620 NotebookApp] Kernel aff744b0-d7c5-46cb-8c38-c713daa772bc died, removing from map.
[W 11:51:54.585 NotebookApp] Timeout waiting for kernel_info reply from aff744b0-d7c5-46cb-8c38-c713daa772bc
[E 11:51:54.587 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: aff744b0-d7c5-46cb-8c38-c713daa772bc)
[W 11:51:55.625 NotebookApp] 404 GET /api/kernels/aff744b0-d7c5-46cb-8c38-c713daa772bc/channels?session_id=479de569a81d48fc93dead062d24fd33 (::1): Kernel does not exist: aff744b0-d7c5-46cb-8c38-c713daa772bc
[W 11:51:55.639 NotebookApp] 404 GET /api/kernels/aff744b0-d7c5-46cb-8c38-c713daa772bc/channels?session_id=479de569a81d48fc93dead062d24fd33 (::1) 18.97ms referer=None
[W 11:51:57.653 NotebookApp] Replacing stale connection: aff744b0-d7c5-46cb-8c38-c713daa772bc:479de569a81d48fc93dead062d24fd33
[W 11:56:01.676 NotebookApp] Replacing stale connection: aff744b0-d7c5-46cb-8c38-c713daa772bc:479de569a81d48fc93dead062d24fd33

**Comment by kevin-bates** [comment]
> [I 11:50:45.659 NotebookApp] Serving notebooks from local directory: E:\python
...
>File "c:\users\91850\appdata\local\programs\python\python38-32\lib\logging_init.py", line 28, in
from string import Template
File "E:\python\string.py", line 1
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
^
SyntaxError: invalid syntax

Rename your `E:\python\string.py` file as its interfering with python's import mechanisms.  In general, you should try to avoid using python filenames that match those of built-in or commonly used modules.

**Comment by dharani2002** [comment]
Microsoft Windows [Version 10.0.19041.572]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\91850>e:

E:\>cd E:\cse

E:\cse>C:\Users\91850\AppData\Local\Programs\Python\Python38-32\Scripts\jupyter notebook
[W 12:30:48.744 NotebookApp] Terminals not available (error was No module named 'winpty.cywinpty')
[I 12:30:48.744 NotebookApp] Serving notebooks from local directory: E:\cse
[I 12:30:48.745 NotebookApp] Jupyter Notebook 6.1.4 is running at:
[I 12:30:48.745 NotebookApp] http://localhost:8888/?token=17510a13deff5d948f73743a38500fe1d67a9a250f3b3ddc
[I 12:30:48.745 NotebookApp]  or http://127.0.0.1:8888/?token=17510a13deff5d948f73743a38500fe1d67a9a250f3b3ddc
[I 12:30:48.745 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 12:30:48.775 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/91850/AppData/Roaming/jupyter/runtime/nbserver-17220-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=17510a13deff5d948f73743a38500fe1d67a9a250f3b3ddc
     or http://127.0.0.1:8888/?token=17510a13deff5d948f73743a38500fe1d67a9a250f3b3ddc
[I 12:30:56.205 NotebookApp] Kernel started: d3a34c41-d42b-472a-bba1-4395fc1b4c14, name: python3
Traceback (most recent call last):
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\IPython\__init__.py", line 55, in <module>
    from .core.application import Application
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\IPython\core\application.py", line 18, in <module>
    import logging
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\logging\__init__.py", line 28, in <module>
    from string import Template
  File "E:\cse\string.py", line 1
    Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
           ^
SyntaxError: invalid syntax
[I 12:30:59.197 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\IPython\__init__.py", line 55, in <module>
    from .core.application import Application
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\IPython\core\application.py", line 18, in <module>
    import logging
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\logging\__init__.py", line 28, in <module>
    from string import Template
  File "E:\cse\string.py", line 1
    Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
           ^
SyntaxError: invalid syntax
[I 12:31:02.219 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\IPython\__init__.py", line 55, in <module>
    from .core.application import Application
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\IPython\core\application.py", line 18, in <module>
    import logging
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\logging\__init__.py", line 28, in <module>
    from string import Template
  File "E:\cse\string.py", line 1
    Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
           ^
SyntaxError: invalid syntax
[I 12:31:05.226 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
Traceback (most recent call last):
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\IPython\__init__.py", line 55, in <module>
    from .core.application import Application
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\IPython\core\application.py", line 18, in <module>
    import logging
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\logging\__init__.py", line 28, in <module>
    from string import Template
  File "E:\cse\string.py", line 1
    Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
           ^
SyntaxError: invalid syntax
[I 12:31:08.243 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
Traceback (most recent call last):
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\IPython\__init__.py", line 55, in <module>
    from .core.application import Application
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\site-packages\IPython\core\application.py", line 18, in <module>
    import logging
  File "c:\users\91850\appdata\local\programs\python\python38-32\lib\logging\__init__.py", line 28, in <module>
    from string import Template
  File "E:\cse\string.py", line 1
    Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
           ^
SyntaxError: invalid syntax
[W 12:31:11.252 NotebookApp] KernelRestarter: restart failed
[W 12:31:11.253 NotebookApp] Kernel d3a34c41-d42b-472a-bba1-4395fc1b4c14 died, removing from map.
[W 12:31:56.292 NotebookApp] Timeout waiting for kernel_info reply from d3a34c41-d42b-472a-bba1-4395fc1b4c14
[E 12:31:56.296 NotebookApp] Error opening stream: HTTP 404: Not Found (Kernel does not exist: d3a34c41-d42b-472a-bba1-4395fc1b4c14)
[W 12:31:57.955 NotebookApp] 404 GET /api/kernels/d3a34c41-d42b-472a-bba1-4395fc1b4c14/channels?session_id=2149ae9bc7a0443298de0834202283a6 (::1): Kernel does not exist: d3a34c41-d42b-472a-bba1-4395fc1b4c14
[W 12:31:57.992 NotebookApp] 404 GET /api/kernels/d3a34c41-d42b-472a-bba1-4395fc1b4c14/channels?session_id=2149ae9bc7a0443298de0834202283a6 (::1) 43.02ms referer=None
[W 12:32:00.956 NotebookApp] Replacing stale connection: d3a34c41-d42b-472a-bba1-4395fc1b4c14:2149ae9bc7a0443298de0834202283a6

**Comment by dharani2002** [comment]
i changed the name still i am facing the same problem

**Comment by kevin-bates** [comment]
You need to change the file name, not the directory name.  Change `E:\cse\string.py` to `E:\cse\my_string.py`.
