### ISSUE TITLE
WebSocketClosedError

### ISSUE THREAD

**Issue by EquatorSavage** [jupyter/notebook#5867]
[I 22:36:38.381 NotebookApp] Saving file at /test_bert_base_model.ipynb
[I 22:40:08.158 NotebookApp] Saving file at /test_bert_base_model.ipynb
[I 22:40:26.956 NotebookApp] Starting buffering for 9211572a-340c-4e50-84e0-4f198671bafb:a312a49561244f4e85f9ea5b0ea37927
ERROR:asyncio:Future exception was never retrieved
future: <Future finished exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "/root/.virtualenvs/nlp_torch/lib/python3.6/site-packages/tornado/websocket.py", line 874, in wrapper
    yield fut
  File "/root/.virtualenvs/nlp_torch/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.virtualenvs/nlp_torch/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/root/.virtualenvs/nlp_torch/lib/python3.6/site-packages/tornado/websocket.py", line 876, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError

**Comment by apoluis117** [comment]
a query.
 Could you solve your problem of the 4 lines that causes you problems?
