### ISSUE TITLE
jupyter notebook not opening from command line when installed with pip

### ISSUE THREAD

**Issue by krishna-vasudev** [jupyter/notebook#5915]
**Describe the bug**
notebook not opening when installed with pip

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - win10 [e.g. iOS]
 - google[e.g. chrome, safari]
 - latest[e.g. 22]

**Additional context**
PS C:\Windows\system32> jupyter notebook
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\python39\Scripts\jupyter-notebook.EXE\__main__.py", line 4, in <module>
  File "c:\python39\lib\site-packages\notebook\notebookapp.py", line 49, in <module>
    from zmq.eventloop import ioloop
  File "c:\python39\lib\site-packages\zmq\__init__.py", line 50, in <module>
    _load_libzmq()
  File "c:\python39\lib\site-packages\zmq\__init__.py", line 28, in _load_libzmq
    from . import libzmq
ImportError: DLL load failed while importing libzmq: The specified module could not be found.
please help me solve this error.

**Comment by goxeq** [comment]
https://stackoverflow.com/questions/65604110/can-not-open-jupyter-notebook-getting-error-dll-load-failed-while-importing-l

**Comment by krishna-vasudev** [comment]
Thanks.
