### ISSUE TITLE
Tab completion not working in Jupyter  Fresh linux

### ISSUE THREAD

**Issue by Hex-Tron** [jupyter/notebook#5922]
I installed latest linux mint and installed jupyter-notebook 
but when I use **Tab** its not working anymore
-----

Thanks to _@Edison0019_ , _@bollwyvl_ 
Problem Has Been solved
-----
Please install 
>pip install jedi=0.17.1 

-----
![Version](https://imgur.com/b9xQqT7.png)

This is the log when I press Tab to complete:

```[W 17:35:11.771 NotebookApp] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/jupyter_server/serverapp.py", line 49, in <module>
        assert tornado.version_info >= MIN_TORNADO
    AssertionError
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/notebook/notebookapp.py", line 1670, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/usr/local/lib/python3.8/dist-packages/jupyterlab/__init__.py", line 7, in <module>
        from .labapp import LabApp
      File "/usr/local/lib/python3.8/dist-packages/jupyterlab/labapp.py", line 16, in <module>
        from jupyterlab_server import slugify, WORKSPACE_EXTENSION
      File "/usr/local/lib/python3.8/dist-packages/jupyterlab_server/__init__.py", line 4, in <module>
        from .app import LabServerApp
      File "/usr/local/lib/python3.8/dist-packages/jupyterlab_server/app.py", line 11, in <module>
        from jupyter_server.extension.application import ExtensionApp, ExtensionAppJinjaMixin
      File "/usr/local/lib/python3.8/dist-packages/jupyter_server/extension/application.py", line 20, in <module>
        from jupyter_server.serverapp import ServerApp
      File "/usr/local/lib/python3.8/dist-packages/jupyter_server/serverapp.py", line 51, in <module>
        raise ImportError(
    ImportError: The Jupyter Server requires tornado >=6.1.0
[I 17:35:11.798 NotebookApp] Serving notebooks from local directory: /home/User
[I 17:35:11.798 NotebookApp] The Jupyter Notebook is running at:
[I 17:35:11.798 NotebookApp] http://localhost:8888/?token=678c6018b2216986ac2ee1eb45a5d97da99c443cb1be107d
[I 17:35:11.798 NotebookApp]  or http://127.0.0.1:8888/?token=678c6018b2216986ac2ee1eb45a5d97da99c443cb1be107d
[I 17:35:11.798 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 17:35:11.929 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/User/.local/share/jupyter/runtime/nbserver-5571-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=678c6018b2216986ac2ee1eb45a5d97da99c443cb1be107d
     or http://127.0.0.1:8888/?token=678c6018b2216986ac2ee1eb45a5d97da99c443cb1be107d
[I 17:35:26.633 NotebookApp] Kernel started: 11977e5c-423f-4d39-8ce7-aab975a40d85
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/local/lib/python3.8/dist-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/usr/lib/python3/dist-packages/ipykernel/kernelbase.py", line 583, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "/usr/lib/python3/dist-packages/ipykernel/ipkernel.py", line 354, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "/usr/lib/python3/dist-packages/ipykernel/ipkernel.py", line 379, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/completer.py", line 1818, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/completer.py", line 1861, in _completions
    matched_text, matches, matches_origin, jedi_matches = self._complete(
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/completer.py", line 2029, in _complete
    completions = self._jedi_matches(
  File "/usr/local/lib/python3.8/dist-packages/IPython/core/completer.py", line 1373, in _jedi_matches
    interpreter = jedi.Interpreter(
  File "/usr/local/lib/python3.8/dist-packages/jedi/api/__init__.py", line 725, in __init__
    super().__init__(code, environment=environment,
TypeError: __init__() got an unexpected keyword argument 'column'
```

And this is all Other Detail:

```

$PATH:
	/home/User/.local/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin

sys.path:
	/home/User/.local/bin
	/usr/lib/python38.zip
	/usr/lib/python3.8
	/usr/lib/python3.8/lib-dynload
	/home/User/.local/lib/python3.8/site-packages
	/usr/local/lib/python3.8/dist-packages
	/usr/lib/python3/dist-packages

sys.executable:
	/usr/bin/python

sys.version:
	3.8.5 (default, Jul 28 2020, 12:59:40) 
	[GCC 9.3.0]

platform.platform():
	Linux-5.4.0-58-generic-x86_64-with-glibc2.29

which -a jupyter:
	/home/User/.local/bin/jupyter

pip list:
	Package                Version              Location
	---------------------- -------------------- -------------------------------------------------
	anyio                  2.0.2
	apt-clone              0.2.1
	apturl                 0.5.2
	argon2-cffi            20.1.0
	async-generator        1.10
	attrs                  20.3.0
	Babel                  2.9.0
	backcall               0.2.0
	beautifulsoup4         4.8.2
	bleach                 3.2.1
	blinker                1.4
	Brlapi                 0.7.0
	catfish                1.4.13
	ccsm                   0.9.14.1
	certifi                2019.11.28
	cffi                   1.14.4
	chardet                3.0.4
	Click                  7.0
	colorama               0.4.3
	command-not-found      0.3
	compizconfig-python    0.9.14.1
	configobj              5.0.6
	cryptography           2.8
	cupshelpers            1.0
	cycler                 0.10.0
	dbus-python            1.2.16
	decorator              4.4.2
	defer                  1.0.6
	defusedxml             0.6.0
	distro                 1.4.0
	entrypoints            0.3
	grpcio                 1.16.1
	httplib2               0.14.0
	idna                   2.8
	ifaddr                 0.1.6
	ipykernel              5.4.2                /home/User/.local/lib/python3.8/site-packages
	ipython                7.19.0
	ipython-genutils       0.2.0
	ipywidgets             7.6.2
	jedi                   0.18.0
	Jinja2                 2.11.2
	json5                  0.9.5
	jsonschema             3.2.0
	jupyter-client         6.1.7
	jupyter-core           4.7.0
	jupyter-server         1.1.3
	jupyterlab-pygments    0.1.2
	jupyterlab-server      2.0.0
	keyring                18.0.1
	kiwisolver             1.3.1
	launchpadlib           1.10.13
	lazr.restfulclient     0.14.2
	lazr.uri               1.0.3
	louis                  3.12.0
	Mako                   1.1.0
	MarkupSafe             1.1.0
	matplotlib             3.3.3
	menulibre              2.2.1
	mistune                0.8.4
	mugshot                0.4.2
	nbclassic              0.2.5
	nbclient               0.5.1
	nbconvert              6.0.7
	nbformat               5.0.8
	nest-asyncio           1.4.3
	netifaces              0.10.4
	nose                   1.3.7
	notebook               6.1.6
	numpy                  1.19.4
	oauthlib               3.1.0
	onboard                1.4.1
	packaging              20.3
	pandas                 1.2.0
	pandocfilters          1.4.3
	parso                  0.8.1
	pexpect                4.6.0
	pickleshare            0.7.5
	Pillow                 7.0.0
	pip                    20.3.3
	prometheus-client      0.9.0
	prompt-toolkit         3.0.8
	protobuf               3.6.1
	psutil                 5.5.1
	ptyprocess             0.7.0
	pycairo                1.16.2
	pycparser              2.20
	pycrypto               2.6.1
	pycups                 1.9.73
	pycurl                 7.43.0.2
	Pygments               2.7.3
	PyGObject              3.36.0
	PyICU                  2.4.2
	PyJWT                  1.7.1
	pymacaroons            0.13.0
	PyNaCl                 1.3.0
	pyparsing              2.4.6
	pyparted               3.11.2
	pyrsistent             0.17.3
	python-apt             2.0.0+ubuntu0.20.4.2
	python-dateutil        2.8.1
	python-debian          0.1.36ubuntu1
	python-xapp            2.0.1
	pytz                   2020.5
	pyxdg                  0.26
	PyYAML                 5.3.1
	pyzmq                  20.0.0
	qtconsole              5.0.1
	QtPy                   1.9.0
	reportlab              3.5.34
	requests               2.22.0
	requests-unixsocket    0.2.0
	scipy                  1.5.4
	seaborn                0.11.1
	SecretStorage          2.3.1
	Send2Trash             1.5.0
	setproctitle           1.1.10
	setuptools             45.2.0
	simplejson             3.16.0
	six                    1.14.0
	sniffio                1.2.0
	soupsieve              1.9.5
	systemd-python         234
	terminado              0.9.1
	testpath               0.4.4
	tornado                6.1
	traitlets              5.0.5
	ubuntu-advantage-tools 20.3
	ubuntu-drivers-common  0.0.0
	ufw                    0.36
	urllib3                1.25.8
	wadllib                1.3.3
	wcwidth                0.2.5
	webencodings           0.5.1
	wheel                  0.34.2
	widgetsnbextension     3.5.1
	xkit                   0.0.0
	zeroconf               0.24.4
```

**Comment by enginefuture** [comment]
same problem

**Comment by bollwyvl** [comment]
There is a PR open to address this on IPython:

https://github.com/ipython/ipython/pull/12751

For now, please ensure you have jedi<0.18 installed.

**Comment by Edison0019** [comment]
I have the exact same problem. however everything is working properly on windows

**Comment by bollwyvl** [comment]
Please ensure you have jedi<0.18. there is a PR to pin this for pip,
conda-forge should already have it pinned (though it's possible you could
pull a new version, as we didn't mark the old one broken).

**Comment by Edison0019** [comment]
I was able to figure this out installing specifically jedi==0.17.1

![image](https://user-images.githubusercontent.com/48873079/103577925-acc29080-4ea3-11eb-8077-7ea2e7b03b23.png)

I hope this helps!

**Comment by sambbhavgarg** [comment]
Thanks! It works, @Edison0019 .
