### ISSUE TITLE
Error on pressing Tab for Auto-completion

### ISSUE THREAD

**Issue by sambbhavgarg** [jupyter/notebook#5925]
Has anyone else encountered such an error? Doesn't go away on reinstalling jupyter notebook by - conda install -c conda-forge notebook

> [IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Users\user\miniconda3\envs\sambbhav_work\lib\site-packages\ipykernel\kernelbase.py", line 265, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\user\miniconda3\envs\sambbhav_work\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Users\user\miniconda3\envs\sambbhav_work\lib\site-packages\tornado\gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "C:\Users\user\miniconda3\envs\sambbhav_work\lib\site-packages\contextvars\__init__.py", line 38, in run
    return callable(*args, **kwargs)
  File "C:\Users\user\miniconda3\envs\sambbhav_work\lib\site-packages\ipykernel\kernelbase.py", line 580, in complete_request
    matches = yield gen.maybe_future(self.do_complete(code, cursor_pos))
  File "C:\Users\user\miniconda3\envs\sambbhav_work\lib\site-packages\ipykernel\ipkernel.py", line 356, in do_complete
    return self._experimental_do_complete(code, cursor_pos)
  File "C:\Users\user\miniconda3\envs\sambbhav_work\lib\site-packages\ipykernel\ipkernel.py", line 381, in _experimental_do_complete
    completions = list(_rectify_completions(code, raw_completions))
  File "C:\Users\user\miniconda3\envs\sambbhav_work\lib\site-packages\IPython\core\completer.py", line 484, in rectify_completions
    completions = list(completions)
  File "C:\Users\user\miniconda3\envs\sambbhav_work\lib\site-packages\IPython\core\completer.py", line 1815, in completions
    for c in self._completions(text, offset, _timeout=self.jedi_compute_type_timeout/1000):
  File "C:\Users\user\miniconda3\envs\sambbhav_work\lib\site-packages\IPython\core\completer.py", line 1859, in _completions
    full_text=full_text, cursor_line=cursor_line, cursor_pos=cursor_column)
  File "C:\Users\user\miniconda3\envs\sambbhav_work\lib\site-packages\IPython\core\completer.py", line 2027, in _complete
    cursor_pos, cursor_line, full_text)
  File "C:\Users\user\miniconda3\envs\sambbhav_work\lib\site-packages\IPython\core\completer.py", line 1370, in _jedi_matches
    text[:offset], namespaces, column=cursor_column, line=cursor_line + 1)
  File "C:\Users\user\miniconda3\envs\sambbhav_work\lib\site-packages\jedi\api\__init__.py", line 726, in __init__
    project=Project(Path.cwd()), **kwds)
TypeError: __init__() got an unexpected keyword argument 'column'

**Comment by sambbhavgarg** [comment]
The following gets the job done -
`conda install jedi==0.17.1`
