### ISSUE TITLE
when i try to use multiprocessing igot this bug

### ISSUE THREAD

**Issue by DanJimm** [jupyter/notebook#5951]
**Describe the bug**
i can't use  module multiprocessing on jupyter notebook,but the same code can running sucessful on Pycharm
This is my code:
import multiprocessing
import time

def calculate_one_process(x):
    print('calculate {}'.format(x))
    return sum([i * i for i in range(x+1)])

if __name__ == '__main__':
    nums = [10000000 + x for x in range(20)]
    print('start')
    start_time = time.perf_counter()
    with multiprocessing.Pool(processes=3) as cal_pool:
        cal_pool.map(calculate_one_process, nums)
    end_time = time.perf_counter()
    print('all preocesses takes {}s'.format(end_time - start_time))

I got this error:
AttributeError: Can't get attribute 'cpu_bound' on <module '__main__' (built-in)>
Process SpawnPoolWorker-20:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 110, in worker
    task = get()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\queues.py", line 354, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'cpu_bound' on <module '__main__' (built-in)>

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10 [e.g. iOS] 
 - Browser: 78.0 (64)[e.g. chrome, safari]

**Additional context**

**Comment by kevin-bates** [comment]
Since this appears to reproduce from within a straight `IPython` session, this should be opened in [its repository](https://github.com/ipython/ipython).  Also, it looks like your dunders (`'__'`) got lost in rendering.  Is this what you wanted to show...
```python
import multiprocessing
import time

def calculate_one_process(x):
    print('calculate {}'.format(x))
    return sum([i * i for i in range(x+1)])

if __name__ == '__main__':
    nums = [10000000 + x for x in range(20)]
    print('start')
    start_time = time.perf_counter()
    with multiprocessing.Pool(processes=3) as cal_pool:
        cal_pool.map(calculate_one_process, nums)
    end_time = time.perf_counter()
    print('all preocesses takes {}s'.format(end_time - start_time))
```
