### ISSUE TITLE
SyntaxWarning: "is" with a literal. Did you mean "=="?

### ISSUE THREAD

**Issue by averri** [jupyter/notebook#5955]
**Describe the bug**
Jupyter keeps restarting the kernel.

**To Reproduce**
1. Start Jupyter with `jupyter notebook`

**Expected behavior**
Jupyter should start normally.

**Screenshots**
See logs.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Browser Chrome
 - Python 3.8.0

```
jupyter-client==6.1.11
jupyter-core==4.7.0
jupyter-server==1.2.2
jupyterlab==3.0.5
jupyterlab-server==2.1.2
```
 
**Logs**
```
SyntaxError: invalid syntax
[I 11:28:55.704 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
/usr/lib/python3/dist-packages/traitlets/config/loader.py:795: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(key) is 1:
/usr/lib/python3/dist-packages/traitlets/config/loader.py:804: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if len(key) is 1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/usr/lib/python3/dist-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/usr/lib/python3/dist-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/usr/lib/python3/dist-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/usr/lib/python3/dist-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/usr/lib/python3/dist-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/usr/lib/python3/dist-packages/IPython/core/ultratb.py", line 124, in <module>
    from IPython.utils import path as util_path
  File "/usr/lib/python3/dist-packages/IPython/utils/path.py", line 18, in <module>
    from IPython.utils.process import system
  File "/usr/lib/python3/dist-packages/IPython/utils/process.py", line 19, in <module>
    from ._process_posix import system, getoutput, arg_split, check_pid
  File "/usr/lib/python3/dist-packages/IPython/utils/_process_posix.py", line 24, in <module>
    import pexpect
  File "/usr/lib/python3/dist-packages/pexpect/__init__.py", line 75, in <module>
    from .pty_spawn import spawn, spawnu
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 14, in <module>
    from .spawnbase import SpawnBase
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 224
    def expect(self, pattern, timeout=-1, searchwindowsize=-1, async=False):
```

**Comment by kevin-bates** [comment]
This appears to be a problem with the [traitlets package](https://github.com/ipython/traitlets/issues/604).  Please try upgrading traitlets to its latest version (5.0.5).

```
pip install --upgrade traitlets
```

**Comment by averri** [comment]
Hi @kevin-bates, I did it, but the error persists. It's been 3 hours trying to run Jupyter, that's a bit frustrating.

**Comment by kevin-bates** [comment]
I'm sorry for your frustration.  If the syntax warning is still present, then it doesn't seem that the traitlets update took effect.  This is coming from the kernel process's environment, so if you're trying to run a kernel in an environment other than the one you started your notebook server within, please apply the traitlets update to that environment as well.

A fresh look at the console output, one that spans at least one of the interim restart attempts (e.g., like restart attempt 3), might also prove helpful as it might suggest a different issue that wasn't displayed in the opening description.

**Comment by averri** [comment]
Thanks @kevin-bates. I have created a fresh environment using virtualenv, installed jupyter with `pip install jupiterlab` and it's working fine now.
