### ISSUE TITLE
Kernel error

### ISSUE THREAD

**Issue by 98vish** [jupyter/notebook#6006]
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Roaming\Python\Python38\site-packages\tornado\web.py", line 1704, in _execute
    result = await result
  File "C:\Users\HP\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\hp\anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 69, in post
    model = yield maybe_future(
  File "C:\Users\HP\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Users\HP\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\hp\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\HP\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Users\HP\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\hp\anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 100, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "C:\Users\HP\AppData\Roaming\Python\Python38\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "c:\users\hp\anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "c:\users\hp\anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 186, in start_kernel
    km.start_kernel(**kwargs)
  File "c:\users\hp\anaconda3\lib\site-packages\jupyter_client\manager.py", line 337, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "c:\users\hp\anaconda3\lib\site-packages\jupyter_client\manager.py", line 286, in pre_start_kernel
    self.write_connection_file()
  File "c:\users\hp\anaconda3\lib\site-packages\jupyter_client\connect.py", line 466, in write_connection_file
    self.connection_file, cfg = write_connection_file(self.connection_file,
  File "c:\users\hp\anaconda3\lib\site-packages\jupyter_client\connect.py", line 136, in write_connection_file
    with secure_write(fname) as f:
  File "c:\users\hp\anaconda3\lib\contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "c:\users\hp\anaconda3\lib\site-packages\jupyter_core\paths.py", line 435, in secure_write
    win32_restrict_file_to_user(fname)
  File "c:\users\hp\anaconda3\lib\site-packages\jupyter_core\paths.py", line 361, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed while importing win32api: %1 is not a valid Win32 application.

**Comment by kevin-bates** [comment]
Hi @98vish - this is typically due to a snafu with the `pywin32` installation.  You might try looking at some of the solutions/workarounds posted in https://github.com/jupyter/jupyter_core/issues/187.

**Comment by 98vish** [comment]
I'll try to create a new environment but not work
I'll install ipykernal ,ipython this also not work 
but should I'll do to resolve that issue, please guide and give me solution

**Comment by kevin-bates** [comment]
This is a `pywin32` issue.  Did you try `pip install --upgrade pywin32` within the correct environment?  You might try checking the `pywin32` repo or google for solutions.  I'm sorry, but I don't have access to Windows system where I could dig into this.  

Perhaps you could post the output of `pip freeze` after upgrading `pywin32` and assuming your issue still persists? 
Please make sure you're running that command from the desired python environment.

**Comment by 98vish** [comment]
I'll create a new environment   and try this pip install --upgrade pywin32 but the issue is still the same 
the notebook shows kernel error
