### ISSUE TITLE
Jupyter notebook ipynb not opening 

### ISSUE THREAD

**Issue by sanab123** [jupyter/notebook#6049]
[E 09:56:35.915 NotebookApp] 500 GET /notebooks/Untitled.ipynb (::1) 504.280000ms referer=http://localhost:8888/tree
<img width="1129" alt="Screen Shot 2021-05-03 at 9 58 19 AM" src="https://user-images.githubusercontent.com/29356316/116907224-28d0a900-abf6-11eb-9c7a-132f943b533b.png">

**Comment by myrrc** [comment]
Jupyter version: 4.4.0-2
Debian 10 stable.

I ran into same bug, here's the error stacktrace:

```
[E 22:34:33.185 NotebookApp] Uncaught exception GET /notebooks/Untitled.ipynb (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/notebooks/Untitled.ipynb', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/lib/python3/dist-packages/tornado/web.py", line 3006, in wrapper
        return method(self, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/notebook/notebook/handlers.py", line 59, in get
        get_custom_frontend_exporters=get_custom_frontend_exporters
      File "/usr/lib/python3/dist-packages/notebook/base/handlers.py", line 519, in render_template
        return template.render(**ns)
      File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
        return original_render(self, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
        return self.environment.handle_exception(exc_info, True)
      File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
        raise value.with_traceback(tb)
      File "/usr/lib/python3/dist-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/usr/lib/python3/dist-packages/notebook/templates/page.html", line 153, in top-level template code
        {% block header %}
      File "/usr/lib/python3/dist-packages/notebook/templates/notebook.html", line 120, in block "header"
        {% for exporter in get_custom_frontend_exporters() %}

      File "/usr/lib/python3/dist-packages/notebook/notebook/handlers.py", line 19, in get_custom_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
      File "/usr/lib/python3/dist-packages/nbconvert/__init__.py", line 4, in <module>
        from .exporters import *
      File "/usr/lib/python3/dist-packages/nbconvert/exporters/__init__.py", line 3, in <module>
        from .exporter_locator import export_by_name
      File "/usr/lib/python3/dist-packages/nbconvert/exporters/exporter_locator.py", line
12, in <module>
        from .templateexporter import TemplateExporter
      File "/usr/lib/python3/dist-packages/nbconvert/exporters/templateexporter.py", line
23, in <module>
        from nbconvert import filters
      File "/usr/lib/python3/dist-packages/nbconvert/filters/__init__.py", line 6, in <module>
        from .markdown import *
      File "/usr/lib/python3/dist-packages/nbconvert/filters/markdown.py", line 13, in <module>
        from .markdown_mistune import markdown2html_mistune
      File "/usr/lib/python3/dist-packages/nbconvert/filters/markdown_mistune.py", line 24, in <module>
        class MathBlockGrammar(mistune.BlockGrammar):
    AttributeError: module 'mistune' has no attribute 'BlockGrammar'
[E 22:34:33.189 NotebookApp] {
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept-Encoding": "gzip, deflate",
      "Dnt": "1",
      "Connection": "keep-alive",
      "Referer": "http://localhost:8888/tree",
      "Cookie": "username-localhost-8888=\"2|1:0|10:1620070471|23:username-localhost-8888|44:NjdlZTU1YjVmNjYxNGVkY2FjNDdjYzI2ZTdlZTYwMTI=|0efd8a528a8a5aacc50ebc6b00819f0a6fdadbee2a1dbf221822eb56b5a6bd25\"; _xsrf=2|ea99daeb|d079d991f3a216e33519867fb304e100|1620070217",
      "Upgrade-Insecure-Requests": "1",
      "Sec-Gpc": "1"
    }
```

**Comment by kevin-bates** [comment]
Not sure what evidence there is that this is the same issue as the opening description as it has such little information to go on.

As for this issue (thanks for the traceback), I suspect you might have an incompatible version of `mistune` and `nbconvert` requires [`>=0.8.1, <2`](https://github.com/jupyter/nbconvert/blob/a365a5ca324faf7f6b7d040773936bdb7fb8c15d/setup.py#L215).

**Comment by psychemedia** [comment]
I've started getting a 500 error from a container that installs https://pypi.org/project/ou-tm351-py/ — something in that package (which includes a ton of stuff:-( appears to be breaking the classic notebook server, although JupyterLab still seems to run notebooks correctly.
