### ISSUE TITLE
setuptools::StaticModule not found when starting Jupyter Notebook

### ISSUE THREAD

**Issue by GMTSE** [jupyter/notebook#6056]
**Describe the bug**
Running `jupyter notebook` displays error `ImportError: cannot import name 'StaticModule' from 'setuptools.config' (/home/user/DataScience/lib/python3.8/site-packages/setuptools/config.py)`

I cannot find any information about `jupyter`/`setuptools`/`StaticModule` on the Web... And it is already installed & up-to-date on my machine:
```
$ pip3 install setuptools
Requirement already satisfied: setuptools in /home/user/DataScience/lib/python3.8/site-packages (44.0.0)
```

**To Reproduce**
1. Start jupyter
```
$ jupyter notebook
I 13:50:33.151 NotebookApp] The port 8888 is already in use, trying another port.
[W 13:50:33.156 NotebookApp] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "/home/user/DataScience/lib/python3.8/site-packages/notebook/notebookapp.py", line 2033, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/home/user/DataScience/lib/python3.8/site-packages/jupyterlab/__init__.py", line 7, in <module>
        from .labapp import LabApp
      File "/home/user/DataScience/lib/python3.8/site-packages/jupyterlab/labapp.py", line 15, in <module>
        from jupyterlab_server import slugify, WORKSPACE_EXTENSION
      File "/home/user/DataScience/lib/python3.8/site-packages/jupyterlab_server/__init__.py", line 4, in <module>
        from .app import LabServerApp
      File "/home/user/DataScience/lib/python3.8/site-packages/jupyterlab_server/app.py", line 7, in <module>
        from jupyter_server.extension.application import ExtensionApp, ExtensionAppJinjaMixin
      File "/home/user/DataScience/lib/python3.8/site-packages/jupyter_server/__init__.py", line 15, in <module>
        from ._version import version_info, __version__
      File "/home/user/DataScience/lib/python3.8/site-packages/jupyter_server/_version.py", line 5, in <module>
        from jupyter_packaging import get_version_info
      File "/home/user/DataScience/lib/python3.8/site-packages/jupyter_packaging/__init__.py", line 7, in <module>
        from .setupbase import *
      File "/home/user/DataScience/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 38, in <module>
        from setuptools.config import StaticModule
    ImportError: cannot import name 'StaticModule' from 'setuptools.config' (/home/user/DataScience/lib/python3.8/site-packages/setuptools/config.py)
[I 13:50:33.158 NotebookApp] Serving notebooks from local directory: /home/user/path/src
[I 13:50:33.158 NotebookApp] Jupyter Notebook 6.3.0 is running at:
[I 13:50:33.158 NotebookApp] http://localhost:8889/?token=a83dacee54ab988cb316125732a1015404915f13fe3585ba
[I 13:50:33.158 NotebookApp]  or http://127.0.0.1:8889/?token=a83dacee54ab988cb316125732a1015404915f13fe3585ba
[I 13:50:33.158 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 13:50:33.219 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/user/.local/share/jupyter/runtime/nbserver-1201433-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/?token=a83dacee54ab988cb316125732a1015404915f13fe3585ba
     or http://127.0.0.1:8889/?token=a83dacee54ab988cb316125732a1015404915f13fe3585ba
```
2. Read output

Globally notebook in the browser works but is very slow. When using from EIN (Emacs IPython Notebooks) this error seems to prevent the correct opeining of the file

**Expected behavior**
Jupiter should start without any error

**Screenshots**
--

**Desktop (please complete the following information):**
 - OS: Linux Mint 20
 - Browser Irrelevant (but it is firefox)
 - Version 
```
$ jupyter --version
jupyter core     : 4.7.1
jupyter-notebook : 6.3.0
qtconsole        : 5.1.0
ipython          : 7.23.1
ipykernel        : 5.5.4
jupyter client   : 6.1.13
jupyter lab      : not installed
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5
```

**Comment by kevin-bates** [comment]
```
      File "/home/user/DataScience/lib/python3.8/site-packages/jupyter_packaging/setupbase.py", line 38, in <module>
        from setuptools.config import StaticModule
    ImportError: cannot import name 'StaticModule' from 'setuptools.config' (/home/user/DataScience/lib/python3.8/site-packages/setuptools/config.py)
```

hi @GMTSE -  `jupyter_packaging` requires `setuptools` >= `46.4.0` - which is when `StaticModule` was added.  Could you please ensure you're running the minimally-required version and retry your startup?

**Comment by GMTSE** [comment]
Arg... Thanks... My bad.
Sorry, but unfortunately pip's management of versions is so messy(*), that each time I upgrade my packages, I have hundreds of messages about version conflicts, thus I ended up ignoring them and just hoping this would work... Until now only LSP and Spyder had actual unsolvable conflicts :(

(*) In their defense, I have no idea how they could do better... I'm not sure why apt is much better...
