### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory was incurred after creating new folder and renaming, but folder was created successfully

### ISSUE THREAD

**Issue by biallenchanuow** [jupyter/notebook#6065]
**Environment**
Jupyter Notebook version:  6.0.1
Conda version: 4.8.2
Python version: 3.7.10
Platform: Mac OS version 10.15.3
Browser Version: Google Chrome - Version 90.0.4430.212 (Official Build) (x86_64)

**My Test Steps:**
1.On the main dashboard, click "New" -> "Folder"
2.Selected the created folder, clicked "Rename"
3.Removed the default name "Untitled Folder"
4.Entered the new name "functional test folder" and clicked "Rename"
5.The Rename Failed Error occurred but the folder was created successfully.

**Full error message:**
Rename Failed.

Traceback (most recent call last): 
File "/Users/BIAllenChan/opt/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1699, in_execute result = await result 
File "/Users/BIAllenChan/opt/anaconda3/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper yielded = next(result) 
File "/Users/BIAllenChan/opt/anaconda3/lib/python3.7/site-packages/notebook/services/contents/handlers.py", line 125, in patch model = yield maybe_future(cm.update(model, path)) 
File "/Users/BIAllenChan/opt/anaconda3/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 296, in update self.rename(path, new_path) 
File "/Users/BIAllenChan/opt/anaconda3/lib/python3.7/site-packages/notebook/services/contents/manager.py", line 284, in rename self.rename_file(old_path, new_path) 
File"/Users/BIAllenChan/opt/anaconda3/lib/python3.7/site-packages/notebook/services/contents/filemanager.py", line 565, in rename_file if os.path.exists(new_os_path) and not samefile(old_os_path, new_os_path): 
File "/Users/BIAllenChan/opt/anaconda3/lib/python3.7/genericpath.py", line 100, in samefile s1 = os.stat(f1) FileNotFoundError: [Errno 2] No such file or directory: '/Users/BIAllenChan/Untitled Folder'

**Extra Information**
I have found the same issue but it was caused by another module: exception.py. The suggestion was to update his Conda version (Conda 4.2). However, my Conda version was 4.8.2 but this issue still occurred. Here's the original issue: https://github.com/conda/conda/issues/6758

Unfortunately, I can not replicate the issue so far, but I do appreciate some help to locate the cause of this issue.
Thank you.

Ps: Please find the screenshot of the error message below.
![image](https://user-images.githubusercontent.com/80367048/118486733-4d339600-b75d-11eb-890b-e54114409987.png)

**Comment by kevin-bates** [comment]
This is odd.  This behavior will occur if the rename has already taken place.  The [statement on which this is happening](https://github.com/jupyter/notebook/blob/74da6d1974b64fa019d819e5f0ec39b6392f212d/notebook/services/contents/filemanager.py#L565) is the second clause of:
```python
    if os.path.exists(new_os_path) and not samefile(old_os_path, new_os_path):
```
so, clearly, the new folder already exists (by virtue of a previous rename) and `samefile` throws because the old folder doesn't exist.

Might there have been a double request sent or something?  I see that  _"Chrome is being controlled by automated test software"_.

**Comment by biallenchanuow** [comment]
Hi Kevin, @kevin-bates 
Yes, I was using TestProject to walk through the Jupyter Notebook's interface and record the process to generate the test script. 

Thanks for point out the statement, I think the TestProject agent sent an extra request with "Untitled Folder" as the old_os_path parameter but on the server-side, the path name has already been changed in this case. I think there may be some compatibility issues between TestProject and Jupyter Notebook.
