### ISSUE TITLE
Failed to start the kernel -desperately need help!

### ISSUE THREAD

**Issue by BalazsGitHub** [jupyter/notebook#6117]
Hi,
I try to use Jupyter Notebook in Anaconda and after updating whatever I can and tried all the tips I found still having  Kernel error.
I tried to reinstall Anaconda, made new environment still throws the same err:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\New\lib\site-packages\tornado\web.py", line 1704, in _execute
    result = await result
  File "C:\ProgramData\Anaconda3\envs\New\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\ProgramData\Anaconda3\envs\New\lib\site-packages\notebook\services\sessions\handlers.py", line 69, in post
    model = yield maybe_future(
  File "C:\ProgramData\Anaconda3\envs\New\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\envs\New\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\ProgramData\Anaconda3\envs\New\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 98, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\ProgramData\Anaconda3\envs\New\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\envs\New\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\ProgramData\Anaconda3\envs\New\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 110, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "C:\ProgramData\Anaconda3\envs\New\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\envs\New\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "C:\ProgramData\Anaconda3\envs\New\lib\site-packages\jupyter_client\multikernelmanager.py", line 186, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\ProgramData\Anaconda3\envs\New\lib\site-packages\jupyter_client\manager.py", line 341, in start_kernel
    self.kernel = self._launch_kernel(kernel_cmd, **kw)
  File "C:\ProgramData\Anaconda3\envs\New\lib\site-packages\jupyter_client\manager.py", line 249, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\ProgramData\Anaconda3\envs\New\lib\site-packages\jupyter_client\launcher.py", line 132, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\New\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\ProgramData\Anaconda3\envs\New\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

Can you give me some tips pls?

**Comment by kevin-bates** [comment]
This is usually an indication that the process referenced in the `argv` stanza of the kernel's kernelspec file (`kernel.json`) is referencing a file that is no longer available and may require some adjustment or reinstallation of the kernel.

To determine the `kernel.json` location, run `jupyter kernelspec list`, locate the kernel you're attempting to start, and look in the referenced directory.  There, you should find a `kernel.json` file.  The `argv` entry is the command that jupyter is attempting to issue.  Ensure that the file-based arguments in that entry are valid.

**Comment by BalazsGitHub** [comment]
Thank you for the help!
I found the kernel.json and the path was pointing to a different location where python.exe wasn't existing at all. I changed the path to C:\\ProgramData\\Anaconda3\\python.exe and the Kernel error is gone and Jupyter running smoothly.

**Comment by BalazsGitHub** [comment]
Thank you for the help!
I found the kernel.json and the path was pointing to a different location where python.exe wasn't existing at all. I changed the path to C:\\ProgramData\\Anaconda3\\python.exe and the Kernel error is gone and Jupyter running smoothly.
