### ISSUE TITLE
404 GET /api/kernels/(Kernel does not exist:)

### ISSUE THREAD

**Issue by N-Mashayekhi** [jupyter/notebook#6149]
Hi,
I've been using jupyter notebook for a while and it worked fine, but it suddenly messed up as my laptop restarted automatically. Since then Jupiter can't connect to kernel and when I open it, it doesn't run any code.
This is what I get in terminal after running $ jupyter-3.8 lab:
[I 09:02:54.169 LabApp] JupyterLab extension loaded from /opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jupyterlab
[I 09:02:54.169 LabApp] JupyterLab application directory is /opt/local/Library/Frameworks/Python.framework/Versions/3.8/share/jupyter/lab
[W 09:02:54.171 LabApp] JupyterLab server extension not enabled, manually loading...
[I 09:02:54.172 LabApp] JupyterLab extension loaded from /opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/jupyterlab
[I 09:02:54.172 LabApp] JupyterLab application directory is /opt/local/Library/Frameworks/Python.framework/Versions/3.8/share/jupyter/lab
[I 09:02:54.173 LabApp] Serving notebooks from local directory: /Users/noshinmashayekhi
[I 09:02:54.173 LabApp] The Jupyter Notebook is running at:
[I 09:02:54.174 LabApp] http://localhost:8888/?token=13db5ca439faa7f20cb8d80266f79ae561e9e1659aba54db
[I 09:02:54.174 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:02:54.180 LabApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=13db5ca439faa7f20cb8d80266f79ae561e9e1659aba54db
[W 09:02:54.249 LabApp] 404 GET /api/kernels/3fb0a080-66e5-4fcf-a97f-3b96a93437f5/channels?session_id=5de1bb20-9d34-4b20-8dc3-407d630b3655 (::1): Kernel does not exist: 3fb0a080-66e5-4fcf-a97f-3b96a93437f5
[W 09:02:54.278 LabApp] 404 GET /api/kernels/3fb0a080-66e5-4fcf-a97f-3b96a93437f5/channels?session_id=5de1bb20-9d34-4b20-8dc3-407d630b3655 (::1) 32.07ms referer=None
[I 09:02:54.921 LabApp] Accepting one-time-token-authenticated connection from ::1
[I 09:02:55.373 LabApp] 301 GET /lab/workspaces/auto-y/?clone (::1) 1.05ms
[W 09:02:55.775 LabApp] Could not determine jupyterlab build status without nodejs
[I 09:02:57.561 LabApp] Kernel started: c82c9aaf-66c3-4bdf-a682-37b7c8b31390
[I 09:02:57.574 LabApp] Kernel started: 1c9a94e5-232a-492b-8feb-c0e02c6572cb
[I 09:02:57.590 LabApp] Kernel started: 075b9355-6cf3-4ba6-9f79-0c96fcb13869
[I 09:02:57.605 LabApp] Kernel started: 2da0e170-2589-4313-abd4-c705fd13fe98
[I 09:02:57.619 LabApp] Kernel started: a30b0210-7ab4-4c2f-a3e5-70407dccd909
[I 09:02:57.639 LabApp] Kernel started: 28bb078e-a392-49dd-81d9-5f0cd3a63fc7
[I 09:02:57.669 LabApp] Kernel started: 71fa60e1-2453-47dc-b658-da7766b4a6f0
[I 09:02:57.749 LabApp] Kernel started: b6faea21-4462-439e-b883-abc182758338
[I 09:02:57.793 LabApp] Kernel started: 17babbb7-f18e-4020-ab07-f4e1f8fbefc4
[I 09:02:57.812 LabApp] Kernel started: 9b3ebb67-2473-4877-bcc6-2775d8e64625
[I 09:02:57.837 LabApp] Kernel started: a2dcef58-b1b7-4264-8cca-821e41be5ac1
[I 09:02:57.908 LabApp] Kernel started: 0eaa26fd-64d3-4511-bb12-2284ec58d631
[I 09:02:57.927 LabApp] Kernel started: 3747594c-1bb0-4beb-9cb6-0cdf8ec3cdab
[I 09:02:57.946 LabApp] Kernel started: ad3784f1-ed85-4d86-9d2a-79ae4fb7c89d
/Users/noshinmashayekhi/Library/Python/3.8/lib/python/site-packages/notebook/base/zmqhandlers.py:284: RuntimeWarning: coroutine 'WebSocketHandler.get' was never awaited
  super(AuthenticatedZMQStreamHandler, self).get(*args, **kwargs)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
[W 09:02:59.114 LabApp] Replacing stale connection: c82c9aaf-66c3-4bdf-a682-37b7c8b31390:0acb8ac3-f9e7-45d6-9a16-0e477abe7268
[W 09:02:59.193 LabApp] Replacing stale connection: 1c9a94e5-232a-492b-8feb-c0e02c6572cb:3485575c-7236-49a5-8d4a-838b13cef19d
[W 09:02:59.209 LabApp] Replacing stale connection: 2da0e170-2589-4313-abd4-c705fd13fe98:25be3144-00fd-4868-b767-7dfb04447fa5
[W 09:02:59.232 LabApp] Replacing stale connection: 28bb078e-a392-49dd-81d9-5f0cd3a63fc7:90752f46-534b-4e4b-9dd7-12090e4f2268
[W 09:02:59.240 LabApp] Replacing stale connection: a30b0210-7ab4-4c2f-a3e5-70407dccd909:07bccdea-5c88-4829-aa95-c732fdc2e199
[W 09:02:59.248 LabApp] Replacing stale connection: 075b9355-6cf3-4ba6-9f79-0c96fcb13869:b23f8148-404c-4a45-bdd0-bd6c3ff90389
[W 09:02:59.299 LabApp] Replacing stale connection: 71fa60e1-2453-47dc-b658-da7766b4a6f0:885fbb90-26c2-41eb-b30f-bedf43cc3917
[W 09:02:59.352 LabApp] Replacing stale connection: 9b3ebb67-2473-4877-bcc6-2775d8e64625:101e1113-80ef-4ad2-8a03-885f20c3dc18
[W 09:02:59.354 LabApp] Replacing stale connection: b6faea21-4462-439e-b883-abc182758338:3d937bda-e086-4c85-b533-cf4119a4fe27
[W 09:02:59.364 LabApp] Replacing stale connection: 3747594c-1bb0-4beb-9cb6-0cdf8ec3cdab:ee156d61-f5b6-4e9b-b57a-3b5fa8202450
[W 09:02:59.371 LabApp] Replacing stale connection: ad3784f1-ed85-4d86-9d2a-79ae4fb7c89d:f2725010-06ce-4123-83f3-72f9b78cf487
[W 09:02:59.373 LabApp] Replacing stale connection: ad3784f1-ed85-4d86-9d2a-79ae4fb7c89d:4d2bf80e-9e40-4f90-989c-983790aec987
[W 09:02:59.375 LabApp] Replacing stale connection: ad3784f1-ed85-4d86-9d2a-79ae4fb7c89d:c6416b0f-c820-433d-8f38-fd12d7ed61b4
[W 09:02:59.383 LabApp] Replacing stale connection: 17babbb7-f18e-4020-ab07-f4e1f8fbefc4:f089c5c4-10fa-430f-8c2d-3db526c181c2
[W 09:02:59.398 LabApp] Replacing stale connection: 0eaa26fd-64d3-4511-bb12-2284ec58d631:0a4fc061-ccc8-412e-90ec-1dcaf7df8bbf
[W 09:02:59.451 LabApp] Replacing stale connection: a2dcef58-b1b7-4264-8cca-821e41be5ac1:ac846df7-a27c-4c7d-af3b-3591106b7458
[I 09:03:04.760 LabApp] Creating new notebook in /libmrc/mhd/tests
[W 09:03:05.053 LabApp] Replacing stale connection: ad3784f1-ed85-4d86-9d2a-79ae4fb7c89d:7cdfd98d-3002-4108-82a0-7b989684ecb3
[I 09:03:06.854 LabApp] Kernel started: 2713033e-fa38-48a4-86dd-aad58c047421
[W 09:03:07.432 LabApp] Replacing stale connection: 2713033e-fa38-48a4-86dd-aad58c047421:619ca359-1765-46d6-98c3-a3eb5ed6f31d
[W 09:03:07.434 LabApp] Replacing stale connection: 2713033e-fa38-48a4-86dd-aad58c047421:fbe8fc61-e2f6-4019-a661-b86bad0da6e8
[W 09:03:07.435 LabApp] Replacing stale connection: 2713033e-fa38-48a4-86dd-aad58c047421:99d8a93e-3cb0-465a-b477-57a439c34942
[W 09:03:16.955 LabApp] Replacing stale connection: 2713033e-fa38-48a4-86dd-aad58c047421:5eba6c54-6613-4f52-a0eb-b2ffa4de45d4
[I 09:05:04.906 LabApp] Saving file at /libmrc/mhd/tests/Untitled15.ipynb
[I 09:17:53.344 LabApp] 302 GET /?token=13db5ca439faa7f20cb8d80266f79ae561e9e1659aba54db (::1) 0.84ms
[W 09:17:54.001 LabApp] Could not determine jupyterlab build status without nodejs
[W 09:17:55.631 LabApp] Replacing stale connection: a30b0210-7ab4-4c2f-a3e5-70407dccd909:d8be4c4a-825e-4dfc-88e2-94b7f8fe6e0f
[W 09:17:55.633 LabApp] Replacing stale connection: 1c9a94e5-232a-492b-8feb-c0e02c6572cb:8e807dcd-4396-4fbb-8801-f4a3eab874ee
[W 09:17:55.634 LabApp] Replacing stale connection: c82c9aaf-66c3-4bdf-a682-37b7c8b31390:76be91b4-f54d-4a58-af09-dc838c4d027b
[W 09:17:55.731 LabApp] Replacing stale connection: 71fa60e1-2453-47dc-b658-da7766b4a6f0:3a0b7542-3ccd-4827-bf63-d43bf6dadd8f
[W 09:17:55.734 LabApp] Replacing stale connection: 2da0e170-2589-4313-abd4-c705fd13fe98:66cc9502-1f5f-45f8-ba88-837951403f1c
[W 09:17:55.734 LabApp] Replacing stale connection: a2dcef58-b1b7-4264-8cca-821e41be5ac1:54ce9be4-3ab2-4ed8-a16d-e00cca0e6efc
[W 09:17:55.737 LabApp] Replacing stale connection: 28bb078e-a392-49dd-81d9-5f0cd3a63fc7:d80bfe4a-1b32-4e37-9217-57ca734bfc2a
[W 09:17:55.737 LabApp] Replacing stale connection: b6faea21-4462-439e-b883-abc182758338:3eaa9afc-62b1-4af9-91e6-da0b435f3ad1
[W 09:17:55.738 LabApp] Replacing stale connection: 075b9355-6cf3-4ba6-9f79-0c96fcb13869:32a52854-5b9c-447b-b452-4c38acca44ff

Can anyone help me to fix it? Thanks

**Comment by kevin-bates** [comment]
A couple of observations.

1. You're using an older version of Notebook (and Lab) since the log message indicating that the notebook server has started is not displaying its version information.  This implies a 5.x or older version of Notebook (probably not a big deal, just pointing it out).
2. Assuming your browser session was also on the same restarted laptop, Lab is persisting session information somewhere.  I don't know where that might be kept, but you might want to be sure all kernel sessions are stopped, all browser tabs are closed, then restart your notebook server (application, not machine).
3. This message implies a mismatch of packages and I would recommend upgrading your Notebook package to the current version.  Note that if you also upgrade Lab to >= 3.x, the underlying server becomes jupyter_server rather that notebook (FYI).
```
/Users/noshinmashayekhi/Library/Python/3.8/lib/python/site-packages/notebook/base/zmqhandlers.py:284: RuntimeWarning: coroutine 'WebSocketHandler.get' was never awaited
super(AuthenticatedZMQStreamHandler, self).get(*args, **kwargs)
```

**Comment by f0k** [comment]
Had the same error message, but maybe in a different situation, it said:
```
[W 2025-10-15 14:35:56.054 ServerApp] 404 GET /api/kernels/2293a5d7-cd79-4fae-a23e-108c371c94a5?1760531756051 (127.0.0.1): Kernel does not exist: 2293a5d7-cd79-4fae-a23e-108c371c94a5
[W 2025-10-15 14:35:56.055 ServerApp] wrote error: 'Kernel does not exist: 2293a5d7-cd79-4fae-a23e-108c371c94a5'
    Traceback (most recent call last):
      File "/home/f0k/.venvs/work/lib/python3.12/site-packages/tornado/web.py", line 1848, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/home/f0k/.venvs/work/lib/python3.12/site-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
               ^^^^^^^^^
      File "/home/f0k/.venvs/work/lib/python3.12/site-packages/jupyter_server/services/kernels/handlers.py", line 75, in get
        model = await ensure_async(km.kernel_model(kernel_id))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/f0k/.venvs/work/lib/python3.12/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 513, in kernel_model
        self._check_kernel_id(kernel_id)
      File "/home/f0k/.venvs/work/lib/python3.12/site-packages/jupyter_server/services/kernels/kernelmanager.py", line 544, in _check_kernel_id
        raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)
    tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: 2293a5d7-cd79-4fae-a23e-108c371c94a5)
```
and would not open up a browser. I wonder if it might have tried to restore a previously closed workspace that had an outdated kernel reference. When I opened jupyter lab in a different directory, shut it down again and reopened the one that I wanted, it worked. Leaving this comment here in case anybody else searches for a solution.
