### ISSUE TITLE
How can I use notebook as root user？

### ISSUE THREAD

**Issue by 980202006** [jupyter/notebook#6190]
Hi when I use notebook in a ubuntu system as root user, I got an error:
Traceback (most recent call last):
  File "/root/anaconda3/envs/svs/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
    result = await result
  File "/root/anaconda3/envs/svs/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/root/anaconda3/envs/svs/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 72, in post
    type=mtype))
  File "/root/anaconda3/envs/svs/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/root/anaconda3/envs/svs/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/root/anaconda3/envs/svs/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 98, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/root/anaconda3/envs/svs/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/root/anaconda3/envs/svs/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/root/anaconda3/envs/svs/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 111, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/root/anaconda3/envs/svs/lib/python3.7/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/root/anaconda3/envs/svs/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "/root/anaconda3/envs/svs/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 186, in start_kernel
    km.start_kernel(**kwargs)
  File "/root/anaconda3/envs/svs/lib/python3.7/site-packages/jupyter_client/manager.py", line 341, in start_kernel
    self.kernel = self._launch_kernel(kernel_cmd, **kw)
  File "/root/anaconda3/envs/svs/lib/python3.7/site-packages/jupyter_client/manager.py", line 249, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/root/anaconda3/envs/svs/lib/python3.7/site-packages/jupyter_client/launcher.py", line 132, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/root/anaconda3/envs/svs/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/root/anaconda3/envs/svs/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/build/80754af9/ipykernel_1629986134010/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python': '/tmp/build/80754af9/ipykernel_1629986134010/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python'

**Comment by Kaslanarian** [comment]
So is this problem solved and how?

**Comment by 980202006** [comment]
Not yet.

**Comment by Kaslanarian** [comment]
Fine, I don't want to do this shit anymore.
