### ISSUE TITLE
Jupyter server crashing with this log

### ISSUE THREAD

**Issue by borgdrone7** [jupyter/notebook#6227]
Hi,

I have Jupyter server crashing occasionally with this output:

[I 11:32:08.368 NotebookApp] 302 GET / (X) 0.79ms
[I 11:45:08.327 NotebookApp] 302 GET / (X) 0.71ms
[I 11:45:08.722 NotebookApp] 302 POST /login?next=/tree? (X) 1.69ms
[I 11:45:09.708 NotebookApp] New terminal with automatic name: 1
[E 11:45:09.947 NotebookApp] Uncaught exception GET /terminals/websocket/1 (X)
    HTTPServerRequest(protocol='http', host='X:8888', method='GET', uri='/terminals/websocket/1', version='HTTP/1.1', remote_ip='X')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.9/site-packages/tornado/websocket.py", line 647, in _run_callback
        result = callback(*args, **kwargs)
      File "/usr/local/lib/python3.9/site-packages/notebook/terminal/handlers.py", line 39, in on_message
        super(TermSocket, self).on_message(message)
      File "/usr/local/lib/python3.9/site-packages/terminado/websocket.py", line 86, in on_message
        command = json.loads(message)
      File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 19 (char 18)
Killed
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.

Anyone has idea how to fix it. I replaced IPs with X.
Thanks

**Comment by vivek-lakhataria** [comment]
Hi,
Same issue here whenever i open new python3 notebook

[E 10:31:46.198 NotebookApp] 500 GET /notebooks/Untitled.ipynb?kernel_name=python3 (::1) 19.000000ms referer=http://localhost:8889/tree
[E 10:31:46.411 NotebookApp] Uncaught exception GET /notebooks/Untitled.ipynb?kernel_name=python3 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8889', method='GET', uri='/notebooks/Untitled.ipynb?kernel_name=python3', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "C:\Python39\lib\site-packages\tornado\web.py", line 1592, in _execute
        result = yield result
      File "C:\Python39\lib\site-packages\tornado\gen.py", line 1133, in run
        value = future.result()
      File "C:\Python39\lib\site-packages\tornado\gen.py", line 1147, in run
        yielded = self.gen.send(value)
      File "C:\Python39\lib\site-packages\notebook\book\handlers.py", line 95, in get
        self.write(self.render_template('notebook.html',
      File "C:\Python39\lib\site-packages\notebook\base\handlers.py", line 516, in render_template
        return template.render(**ns)
      File "C:\Python39\lib\site-packages\jinja2\environment.py", line 1304, in render
        self.environment.handle_exception()
      File "C:\Python39\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
        raise rewrite_traceback_stack(source=source)
      File "C:\Python39\lib\site-packages\notebook\templates\notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "C:\Python39\lib\site-packages\notebook\templates\page.html", line 154, in top-level template code
        {% block header %}
      File "C:\Python39\lib\site-packages\notebook\templates\notebook.html", line 115, in block 'header'
        {% for exporter in get_frontend_exporters() %}
      File "C:\Python39\lib\site-packages\notebook\book\handlers.py", line 23, in get_frontend_exporters
        from nbconvert.exporters.base import get_export_names, get_exporter
    ModuleNotFoundError: No module named 'nbconvert.exporters'
[E 10:31:46.423 NotebookApp] {
      "Host": "localhost:8889",
      "Connection": "keep-alive",
      "Cache-Control": "max-age=0",
      "Sec-Ch-Ua": "\"Microsoft Edge\";v=\"95\", \"Chromium\";v=\"95\", \";Not A Brand\";v=\"99\"",
      "Sec-Ch-Ua-Mobile": "?0",
      "Sec-Ch-Ua-Platform": "\"Windows\"",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36 Edg/95.0.1020.44",
19; username-localhost-8892=\"2|1:0|10:1635418932|23:username-localhost-8892|44:NDhjMzNkNDA4MDMwNGExNjkwNzJkYmYyYzlkYjRmYjc=|4a9a0b305c1a8816e3d79e2aa52e45c2a68988f4b246ecd759d5f3567801ba23\"; username-localhost-8891=\"2|1:0|10:1635501884|23:username-localhost-8891|44:YThmZGVjY2U5Y2FjNGM3ZTg3ZThlYTMzOTM2ZjhkMWU=|01f9c67f56115c407c373533e0564ea8951dad209f182058d4828eaeb624332e\"; username-localhost-8889=\"2|1:0|10:1636517138|23:username-localhost-8889|44:Yzc5OGE1NTg4YzgyNGYzMThjMjliOWRhZTM4ZTk5YWQ=|c3608b0156d0403b141eb9e4039f65f2a3b112d368176c176affb8a0796dc952\"; username-localhost-8888=\"2|1:0|10:1636604617|23:username-localhost-8888|44:MzY1NjQyZjY3MDFmNDBmMWExZjdiYTFiZDU1OTY0ZmU=|9aa003997bd9e95bdb5c20daba232f39031209e6ffa8e90e756a424d864bade7\"; username-localhost-8890=\"2|1:0|10:1636693219|23:username-localhost-8890|44:ZDQ1NmE0NTA4OWVjNDdmZWFhNzA1ZDc0NGVlY2YwOWU=|8869a41a3357dd65c1ba10f7d99e1d9f85f26d69c088a18fb356213bb686ff10\""
    }
[E 10:31:46.428 NotebookApp] 500 GET /notebooks/Untitled.ipynb?kernel_name=python3 (::1) 26.000000ms referer=http://localhost:8889/tree
