### ISSUE TITLE
Error upon jupyter-notebook launch

### ISSUE THREAD

**Issue by Sinasta** [jupyter/notebook#6247]
i am facing this error when launching jupyter-notebook on arch linux python 3.9.9:

Exception while loading config file /etc/jupyter/jupyter_notebook_config.json
    Traceback (most recent call last):
      File "/usr/lib/python3.9/site-packages/traitlets/config/application.py", line 738, in _load_config_files
        config = loader.load_config()
      File "/usr/lib/python3.9/site-packages/traitlets/config/loader.py", line 563, in load_config
        dct = self._read_file_as_dict()
      File "/usr/lib/python3.9/site-packages/traitlets/config/loader.py", line 569, in _read_file_as_dict
        return json.load(f)
      File "/usr/lib/python3.9/json/__init__.py", line 293, in load
        return loads(fp.read(),
      File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/bin/jupyter-notebook", line 33, in <module>
    sys.exit(load_entry_point('notebook==6.4.4', 'console_scripts', 'jupyter-notebook')())
  File "/usr/lib/python3.9/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.9/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.initialize(argv)
  File "/usr/lib/python3.9/site-packages/traitlets/config/application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/notebook/notebookapp.py", line 2122, in initialize
    self.init_server_extension_config()
  File "/usr/lib/python3.9/site-packages/notebook/notebookapp.py", line 2006, in init_server_extension_config
    section = manager.get(self.config_file_name)
  File "/usr/lib/python3.9/site-packages/notebook/services/config/manager.py", line 25, in get
    recursive_update(config, cm.get(section_name))
  File "/usr/lib/python3.9/site-packages/notebook/config_manager.py", line 101, in get
    recursive_update(data, json.load(f))
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Sinasta** [comment]
this is the output of jupyter troubleshoot:

$PATH:
	/home/sinasta/.local/bin
	/usr/local/bin
	/usr/bin
	/usr/local/sbin
	/usr/bin/site_perl
	/usr/bin/vendor_perl
	/usr/bin/core_perl

sys.path:
	/usr/bin
	/usr/lib/python310.zip
	/usr/lib/python3.10
	/usr/lib/python3.10/lib-dynload
	/home/sinasta/.local/lib/python3.10/site-packages
	/usr/lib/python3.10/site-packages

sys.executable:
	/usr/bin/python3

sys.version:
	3.10.1 (main, Dec 11 2021, 17:22:55) [GCC 11.1.0]

platform.platform():
	Linux-5.16.0-1-MANJARO-x86_64-with-glibc2.33

which -a jupyter:
	/usr/bin/jupyter

pip list:
	Package               Version
	--------------------- ---------------------------------------------------------------------------------
	apparmor              3.0.3
	appdirs               1.4.4
	argon2-cffi           21.1.0
	async-generator       1.10
	attrs                 21.2.0
	Automat               20.2.0
	Babel                 2.9.1
	backcall              0.2.0
	bcrypt                3.2.0
	beautifulsoup4        4.9.3
	bleach                4.1.0
	Bottleneck            1.3.2
	btrfsutil             5.15.1
	CacheControl          0.12.6
	certifi               2021.10.8
	cffi                  1.15.0
	chardet               4.0.0
	charset-normalizer    2.0.4
	click                 8.0.3
	cloudpickle           2.0.0
	colorama              0.4.4
	constantly            15.1.0
	contextlib2           0.6.0.post1
	cryptography          36.0.0
	cssselect             1.1.0
	cycler                0.10.0
	Cython                0.29.26
	debugpy               1.5.1
	decorator             5.1.0
	defusedxml            0.7.1
	distlib               0.3.3
	distro                1.6.0
	dnspython             2.1.0
	docstring-to-markdown 0.9
	docutils              0.16
	entrypoints           0.3
	fonttools             4.28.4
	GDAL                  3.3.1
	gitdb                 4.0.7
	GitPython             3.1.24
	h2                    4.0.0
	hpack                 4.0.0
	html5lib              1.1
	hyperframe            6.0.1
	hyperlink             21.0.0
	idna                  3.3
	imageio               2.13.3
	img2pdf               0.4.3
	importlib-metadata    4.8.1
	incremental           21.3.0
	ipykernel             6.6.0
	ipython               7.30.1
	ipython_genutils      0.2.0
	ipywidgets            7.6.5
	jedi                  0.18.1
	jedi-language-server  0.34.3
	Jinja2                3.0.3
	joblib                1.1.0
	jsonschema            3.2.0
	jupyter-client        7.1.0
	jupyter-console       6.4.0
	jupyter-core          4.9.1
	jupyterlab-pygments   0.1.2
	Kivy                  2.0.0
	kiwisolver            1.3.2
	lensfun               0.3.95
	LibAppArmor           3.0.3
	libtorrent            1.2.14-build-libtorrent-rasterbar-src-libtorrent-rasterbar-1.2.14-bindings-python
	lit                   13.0.0.dev0
	louis                 3.20.0
	lxml                  4.6.4
	Markdown              3.3.6
	MarkupSafe            2.0.1
	matplotlib            3.5.1
	matplotlib-inline     0.1.3
	menulibre             2.2.3
	mistune               0.8.4
	more-itertools        8.10.0
	mpi4py                3.1.1
	msgpack               1.0.2
	mutagen               1.45.1
	nbclient              0.5.4
	nbconvert             6.1.0
	nbformat              5.1.3
	nest-asyncio          1.5.4
	networkx              2.6.3
	nftables              0.1
	notebook              6.4.4
	npyscreen             4.10.5
	numexpr               2.7.3
	numpy                 1.21.4
	ordered-set           4.0.2
	packaging             20.9
	pacman-mirrors        4.23.1
	pandas                1.3.5
	pandas-datareader     0.10.0
	pandocfilters         1.4.3
	parso                 0.8.2
	pdfarranger           1.8.1
	pep517                0.12.0
	pexpect               4.8.0
	pickleshare           0.7.5
	pikepdf               4.2.0
	Pillow                8.4.0
	pip                   21.3.1
	Pivy                  0.6.6
	pkgconfig             1.5.5
	ply                   3.11
	progress              1.6
	prometheus-client     0.11.0
	prompt-toolkit        3.0.24
	protobuf              3.17.3
	psutil                5.8.0
	ptyprocess            0.7.0
	pwquality             1.4.4
	pyasn1                0.4.8
	pyasn1-modules        0.2.8
	pybind11              2.8.1
	pycairo               1.20.1
	pycparser             2.21
	pycryptodomex         3.10.1
	pycurl                7.44.1
	pydantic              1.8.2
	pygame                2.1.0
	pygls                 0.11.2
	Pygments              2.10.0
	PyGObject             3.42.0
	PyOpenGL              3.1.5
	pyOpenSSL             21.0.0
	pyparsing             2.4.7
	pyproj                3.0.1
	PyQt5                 5.15.6
	PyQt5-sip             12.9.0
	PyQtWebEngine         5.15.5
	pyrsistent            0.18.0
	pyserial              3.5
	PySide2               5.15.2
	PySocks               1.7.1
	python-dateutil       2.8.2
	pytz                  2021.3
	pyxattr               0.7.2
	pyxdg                 0.27
	PyYAML                5.4.1
	pyzmq                 22.2.1
	QtPy                  1.11.2
	requests              2.26.0
	resolvelib            0.5.5
	retrying              1.3.3
	rubber                1.6.0
	scikit-image          0.19.1
	scikit-learn          1.0.1
	scipy                 1.7.3
	scour                 0.38.2
	seaborn               0.11.2
	Send2Trash            1.8.0
	service-identity      21.1.0
	setuptools            57.4.0
	Shapely               1.7.1
	shiboken2             5.15.2
	Shredder              2.10.1.Ludicrous.Lemur
	six                   1.16.0
	smmap                 5.0.0
	sniffio               1.2.0
	soupsieve             2.2.1
	svgwrite              1.4.1
	TBB                   0.2
	team                  1.0
	terminado             0.11.1
	testpath              0.5.0
	threadpoolctl         2.2.0
	toml                  0.10.2
	tomli                 1.2.2
	tornado               6.1
	tqdm                  4.62.3
	traitlets             5.1.0
	Twisted               21.7.0
	typeguard             2.13.2
	typing-extensions     3.10.0.2
	urllib3               1.26.7
	wcwidth               0.2.5
	webencodings          0.5.1
	websockets            10.1
	widgetsnbextension    3.5.1
	youtube-dl            2021.6.6
	yt-dlp                2021.11.10.1
	zipp                  3.6.0
	zope.interface        5.4.0
