### ISSUE TITLE
Can't start jupyter in python3.9.7 conda 4.10.3

### ISSUE THREAD

**Issue by donttal** [jupyter/notebook#6250]
**Describe the bug**
Linux version 4.15.0-144-generic (buildd@lgw01-amd64-031) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #148-Ubuntu SMP Sat May 8 02:33:43 UTC 2021
when I want to run " jupyter notebook --no-browser" 

```python
Traceback` (most recent call last):
  File "/home/user/.local/bin/jupyter-notebook", line 8, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.8/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/traitlets/config/application.py", line 844, in launch_instance
    app.initialize(argv)
  File "/home/user/.local/lib/python3.8/site-packages/traitlets/config/application.py", line 87, in inner
    return method(app, *args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/notebook/notebookapp.py", line 2124, in initialize
    self.init_webapp()
  File "/home/user/.local/lib/python3.8/site-packages/notebook/notebookapp.py", line 1759, in init_webapp
    self.web_app = NotebookWebApplication(
  File "/home/user/.local/lib/python3.8/site-packages/notebook/notebookapp.py", line 179, in __init__
    settings = self.init_settings(
  File "/home/user/.local/lib/python3.8/site-packages/notebook/notebookapp.py", line 302, in init_settings
    nbextensions_path=jupyter_app.nbextensions_path,
  File "/home/user/.local/lib/python3.8/site-packages/notebook/notebookapp.py", line 1329, in nbextensions_path
    from IPython.paths import get_ipython_dir
  File "/home/user/.local/lib/python3.8/site-packages/IPython/__init__.py", line 55, in <module>
    from .core.application import Application
  File "/home/user/.local/lib/python3.8/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/home/user/.local/lib/python3.8/site-packages/IPython/core/crashhandler.py", line 27, in <module>
    from IPython.core import ultratb
  File "/home/user/.local/lib/python3.8/site-packages/IPython/core/ultratb.py", line 116, in <module>
    from IPython.utils import path as util_path
  File "/home/user/.local/lib/python3.8/site-packages/IPython/utils/path.py", line 17, in <module>
    from IPython.utils.process import system
  File "/home/user/.local/lib/python3.8/site-packages/IPython/utils/process.py", line 19, in <module>
    from ._process_posix import system, getoutput, arg_split, check_pid
  File "/home/user/.local/lib/python3.8/site-packages/IPython/utils/_process_posix.py", line 23, in <module>
    import pexpect
  File "/usr/lib/python3/dist-packages/pexpect/__init__.py", line 75, in <module>
    from .pty_spawn import spawn, spawnu
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 14, in <module>
    from .spawnbase import SpawnBase
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 224
    def expect(self, pattern, timeout=-1, searchwindowsize=-1, async=False):
                                                               ^
SyntaxError: invalid syntax
```

**Tried and failed methods**

```sh
$ pip uninstall pexpect
Found existing installation: pexpect 4.2.1
ERROR: Cannot uninstall 'pexpect'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.
$ pip install pexpect
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pexpect in /usr/lib/python3/dist-packages (4.2.1)
```

```sh
$ sudo -H pip uninstall pexpect
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal'
$ python -m pip install --upgrade pip
Requirement already satisfied: pip in /home/user/anaconda3/envs/prompt/lib/python3.9/site-packages (21.2.4)
Collecting pip
  Using cached pip-21.3.1-py3-none-any.whl (1.7 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.4
    Uninstalling pip-21.2.4:
      Successfully uninstalled pip-21.2.4
Successfully installed pip-21.3.1
$ ssudo -H pip uninstall pexpect
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal'
```

**Comment by deviprasad97** [comment]
For me ```pip install --upgrade pexpect``` worked
