### ISSUE TITLE
Connection failed  A connection to the notebook server could not be established. The notebook will continue trying to reconnect. Check your network connection or notebook server configuration.

### ISSUE THREAD

**Issue by AyoolaAbe** [jupyter/notebook#6261]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by kevin-bates** [comment]
You're running an older (pre 6.0?) version of notebook as is evident by the missing version information in this log statement:
```
[I 08:18:55.084 NotebookApp] The Jupyter Notebook is running at:
```
which would explain why the websocket handler was never awaited.  It's also curious to me the mixture of Lab/JupyterServer/Notebook in the logs as well since Lab should be using Jupyter Server completely.  As such, I would suggest also updating `jupyterlab` and `jupyter_server` versions as well.

**Comment by AyoolaAbe** [comment]
Thank you @kevin-bates 
I have updated jupyterlab and server, but the error still comes up.

[W 07:14:53.765 NotebookApp] Error loading server extension jupyterlab
    Traceback (most recent call last):
      File "C:\Users\AYOOLA\anaconda3\lib\site-packages\jupyter_server\prometheus\metrics.py", line 12, in <module>
        from notebook.prometheus.metrics import HTTP_REQUEST_DURATION_SECONDS, TERMINAL_CURRENTLY_RUNNING_TOTAL, KERNEL_CURRENTLY_RUNNING_TOTAL
    ModuleNotFoundError: No module named 'notebook.prometheus'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\AYOOLA\AppData\Roaming\Python\Python39\site-packages\notebook\notebookapp.py", line 1546, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "C:\Users\AYOOLA\anaconda3\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 850, in exec_module
      File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      File "C:\Users\AYOOLA\anaconda3\lib\site-packages\jupyterlab\__init__.py", line 7, in <module>
        from .labapp import LabApp
      File "C:\Users\AYOOLA\anaconda3\lib\site-packages\jupyterlab\labapp.py", line 15, in <module>
        from jupyter_server.serverapp import flags
      File "C:\Users\AYOOLA\anaconda3\lib\site-packages\jupyter_server\serverapp.py", line 74, in <module>
        from .log import log_request
      File "C:\Users\AYOOLA\anaconda3\lib\site-packages\jupyter_server\log.py", line 10, in <module>
        from .prometheus.log_functions import prometheus_log_method
      File "C:\Users\AYOOLA\anaconda3\lib\site-packages\jupyter_server\prometheus\log_functions.py", line 1, in <module>
        from .metrics import HTTP_REQUEST_DURATION_SECONDS
      File "C:\Users\AYOOLA\anaconda3\lib\site-packages\jupyter_server\prometheus\metrics.py", line 18, in <module>
        HTTP_REQUEST_DURATION_SECONDS = Histogram(
      File "C:\Users\AYOOLA\anaconda3\lib\site-packages\prometheus_client\metrics.py", line 522, in __init__
        super(Histogram, self).__init__(
      File "C:\Users\AYOOLA\anaconda3\lib\site-packages\prometheus_client\metrics.py", line 121, in __init__
        registry.register(self)
      File "C:\Users\AYOOLA\anaconda3\lib\site-packages\prometheus_client\registry.py", line 29, in register
        raise ValueError(
    ValueError: Duplicated timeseries in CollectorRegistry: {'http_request_duration_seconds_count', 'http_request_duration_seconds_created', 'http_request_duration_seconds_sum', 'http_request_duration_seconds_bucket', 'http_request_duration_seconds'}
[I 07:14:54.350 NotebookApp] Serving notebooks from local directory: C:\Users\AYOOLA
[I 07:14:54.351 NotebookApp] The Jupyter Notebook is running at:
[I 07:14:54.352 NotebookApp] http://localhost:8888/?token=435f312afedbaa61e6664ac09c7451116db53a5234b42bee
[I 07:14:54.354 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 07:14:54.404 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=435f312afedbaa61e6664ac09c7451116db53a5234b42bee
[I 07:14:54.731 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 07:15:02.390 NotebookApp] Creating new notebook in
[I 07:15:11.053 NotebookApp] Kernel started: 0e628b87-0a33-4f41-b17b-0b60822d3440
C:\Users\AYOOLA\AppData\Roaming\Python\Python39\site-packages\notebook\base\zmqhandlers.py:284: RuntimeWarning: coroutine 'WebSocketHandler.get' was never awaited
  super(AuthenticatedZMQStreamHandler, self).get(*args, **kwargs)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
[W 07:15:17.191 NotebookApp] Replacing stale connection: 0e628b87-0a33-4f41-b17b-0b60822d3440:818f0b23c0e7448b833dabf43f349195
[W 07:15:39.267 NotebookApp] Replacing stale connection: 0e628b87-0a33-4f41-b17b-0b60822d3440:818f0b23c0e7448b833dabf43f349195

**Comment by kevin-bates** [comment]
Thanks for the update @AyoolaAbe.  I'm still a little perplexed why the version information is not appearing in the log output:
```
[I 07:14:54.351 NotebookApp] The Jupyter Notebook is running at:
```
This was added in the 6.1.0 release so this implies the version of the notebook server that _is running_ is prior to 6.1.0 - which would also be consistent with the line number of `notebook\base\zmqhandlers.py:284` missing the await (or yield) call (newer versions have this statement as line 294).

From the same prompt at which you start `jupyter notebook`, could you please run `jupyter troubleshoot` and provide the output?  If you happen to see an older notebook release (prior to 6.1), please upgrade your notebook package (`pip install --upgrade notebook` or `conda update notebook`) then start the notebook server.  It's fairly clear you're still using an older version of notebook, somehow, someway.

**Comment by AyoolaAbe** [comment]
Thanks @kevin-bates its working fine now. thank you for the guidance. it means so much to me
