### ISSUE TITLE
6.4.x test_help_output fails with traitlets 5.2.0: assert "Traceback" not in err

### ISSUE THREAD

**Issue by hroncok** [jupyter/notebook#6424]
**Describe the bug**
Hello. In Fedora, we still have notebook 6.4.x. Recently, traitlets was upgraded to 5.2.0 and suddenly test_help_output fails. Is it OK if we skip the testes?

**To Reproduce**

In this repo, branch 6.4.x.

```
$ python3.10 -m venv __venv__
$ . __venv__/bin/activate
(__venv__) $ pip install .[test]
...
(__venv__) $ pip list | grep traitlets
traitlets                5.2.0
(__venv__) $ pytest notebook/tests/ notebook/bundler/tests/ -k test_help_output
============================= test session starts ==============================
platform linux -- Python 3.10.4, pytest-7.1.2, pluggy-1.0.0
rootdir: .../notebook
plugins: anyio-3.6.1, tornasync-0.6.0.post2, timeout-2.1.0, mock-3.7.0, cov-3.0.0, console-scripts-1.3.1, nbval-0.9.6
collected 158 items / 153 deselected / 5 selected

notebook/tests/test_nbextensions.py F                                    [ 20%]
notebook/tests/test_notebookapp.py .                                     [ 40%]
notebook/tests/test_serverextensions.py F                                [ 60%]
notebook/tests/test_utils.py .                                           [ 80%]
notebook/bundler/tests/test_bundlerextension.py F                        [100%]

=================================== FAILURES ===================================
_______________________________ test_help_output _______________________________

    def test_help_output():
        check_help_all_output('notebook.nbextensions')
>       check_help_all_output('notebook.nbextensions', ['enable'])

notebook/tests/test_nbextensions.py:47: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

pkg = 'notebook.nbextensions', subcommand = ['enable']

    def check_help_all_output(pkg, subcommand=None):
        """test that `python -m PKG --help-all` works"""
        cmd = [sys.executable, "-m", pkg]
        if subcommand:
            cmd.extend(subcommand)
        cmd.append("--help-all")
        out, err, rc = get_output_error_code(cmd)
        assert rc == 0, err
>       assert "Traceback" not in err
E       AssertionError

__venv__/lib64/python3.10/site-packages/traitlets/tests/utils.py:36: AssertionError
_______________________________ test_help_output _______________________________

    def test_help_output():
        check_help_all_output('notebook.serverextensions')
>       check_help_all_output('notebook.serverextensions', ['enable'])

notebook/tests/test_serverextensions.py:26: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

pkg = 'notebook.serverextensions', subcommand = ['enable']

    def check_help_all_output(pkg, subcommand=None):
        """test that `python -m PKG --help-all` works"""
        cmd = [sys.executable, "-m", pkg]
        if subcommand:
            cmd.extend(subcommand)
        cmd.append("--help-all")
        out, err, rc = get_output_error_code(cmd)
        assert rc == 0, err
>       assert "Traceback" not in err
E       AssertionError

__venv__/lib64/python3.10/site-packages/traitlets/tests/utils.py:36: AssertionError
_______________________________ test_help_output _______________________________

    def test_help_output():
        check_help_all_output('notebook.bundler.bundlerextensions')
>       check_help_all_output('notebook.bundler.bundlerextensions', ['enable'])

notebook/bundler/tests/test_bundlerextension.py:23: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

pkg = 'notebook.bundler.bundlerextensions', subcommand = ['enable']

    def check_help_all_output(pkg, subcommand=None):
        """test that `python -m PKG --help-all` works"""
        cmd = [sys.executable, "-m", pkg]
        if subcommand:
            cmd.extend(subcommand)
        cmd.append("--help-all")
        out, err, rc = get_output_error_code(cmd)
        assert rc == 0, err
>       assert "Traceback" not in err
E       AssertionError

__venv__/lib64/python3.10/site-packages/traitlets/tests/utils.py:36: AssertionError
=============================== warnings summary ===============================
notebook/utils.py:15
  .../notebook/notebook/utils.py:15: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    from distutils.version import LooseVersion

notebook/tests/test_notebookapp_integration.py:14
  .../notebook/notebook/tests/test_notebookapp_integration.py:14: PytestUnknownMarkWarning: Unknown pytest.mark.integration_tests - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    pytestmark = pytest.mark.integration_tests

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED notebook/tests/test_nbextensions.py::test_help_output - AssertionError
FAILED notebook/tests/test_serverextensions.py::test_help_output - AssertionE...
FAILED notebook/bundler/tests/test_bundlerextension.py::test_help_output - As...
=========== 3 failed, 2 passed, 153 deselected, 2 warnings in 1.10s ============
```

**Expected behavior**
All tests pass.

**Desktop (please complete the following information):**

- OS: Fedora Linux 35, 36 and 37
- Version 6.4.10, 6.4.11, 6.4.x branch

If I go to installed traitlets and change the assert to `assert "Traceback" not in err, err`, I get:

```
>       assert "Traceback" not in err, err
E       AssertionError: Exception ignored in: <function Application.__del__ at 0x7f83f2678af0>
E       Traceback (most recent call last):
E         File ".../notebook/__venv__/lib64/python3.10/site-packages/traitlets/config/application.py", line 955, in __del__
E         File ".../notebook/__venv__/lib64/python3.10/site-packages/traitlets/config/application.py", line 945, in close_handlers
E         File ".../notebook/__venv__/lib64/python3.10/site-packages/traitlets/traitlets.py", line 683, in __get__
E         File ".../notebook/__venv__/lib64/python3.10/site-packages/traitlets/traitlets.py", line 657, in get
E         File ".../notebook/__venv__/lib64/python3.10/site-packages/traitlets/traitlets.py", line 1428, in _notify_observers
E         File ".../notebook/__venv__/lib64/python3.10/site-packages/traitlets/config/application.py", line 273, in _observe_logging_default
E         File ".../notebook/__venv__/lib64/python3.10/site-packages/traitlets/config/application.py", line 278, in _configure_logging
E         File "/usr/lib64/python3.10/logging/config.py", line 810, in dictConfig
E         File "/usr/lib64/python3.10/logging/config.py", line 547, in configure
E       ValueError: Unable to configure formatter 'console'
```

I am not sure if this isn't a traitlets bug :confused:

**Comment by hroncok** [comment]
Indeed looks like a traitlets thing. Sorry for the noise.
