### ISSUE TITLE
importmap in _html_repr_ fails in local notebooks (does work in collab)

### ISSUE THREAD

**Issue by Strilanc** [jupyter/notebook#6597]
**REPRO STEPS**

From the command line, run `jupyter notebook`, create a new notebook, add a code cell, and put the following into the code cell:

```
class C:
    def _repr_html_(self):
        return """
<html>
<head>
  <script type="importmap">
    {
      "imports": {
        "three": "https://unpkg.com/three@0.138.0/build/three.module.js"
      }
    }
  </script>
</head>
<body>
  <div id="out">loading...</div>
  <script type="module">
    import {Vector2} from "three";
    document.getElementById("out").textContent = "worked!";
  </script>
</body>
</html>
        """

C()
```

Make sure the notebook is trusted, and execute the cell.

**WHAT SHOULD HAPPEN**

The output should say "worked!".

More specifically, the output should be an html widget containing a div with its inner text set to "worked!".

Note that, in google collab, this is in fact the result you get.

**WHAT ACTUALLY HAPPENS**

The output gets stuck at "loading...". Additionally, if you open the browser's javascript console, you will find an error:

```
jquery.min.js:2 Uncaught TypeError: Failed to resolve module specifier "three". Relative references must start with either "/", "./", or "../".
    at b (jquery.min.js:2:1)
    at Pe (jquery.min.js:2:1)
    at S.fn.init.append (jquery.min.js:2:1)
    at OutputArea._safe_append (outputarea.js:458:1)
    at OutputArea.append_execute_result (outputarea.js:497:1)
    at OutputArea.append_output (outputarea.js:325:1)
    at OutputArea.handle_output (outputarea.js:256:1)
    at output (codecell.js:399:1)
    at Kernel._handle_output_message (kernel.js:1199:1)
    at i (jquery.min.js:2:1)
```

**LIKELY CAUSE**

It appears that, whatever mechanism is being used to translate the HTML returned by `_repr_html_` into an output cell widget, it is not correctly translating import maps in a way that results in the javascript within the output cell having access to the declared import maps.

**Comment by RRosio** [comment]
Hi @Strilanc, thank you for submitting this issue. Could you please share which browser you are using? Would it be possible to test if this works for you in JupyterLab using Chrome? If so, Jupyter Notebook 7 should work as well . Thanks again!

**Comment by gabalafou** [comment]
I misspoke during triage today. 

Using JupyterLab version 4.0.0a30 in Brave, I am able to reproduce this issue (with or without shields up). Using the same version in Chrome, I am not able to reproduce; in other words, the code snippet above works in Chrome.

**Comment by Strilanc** [comment]
Here is a recording of me reproducing the bug on the latest version of chrome: https://drive.google.com/file/d/1o24O9W4gXCVHE8CrLGUahX3n7YA2kVn9/view?usp=sharing

Setting up the python environment and starting the server:

![image](https://user-images.githubusercontent.com/79941/198547391-29e668f6-c6bf-4a9d-bae5-144f6faca209.png)

Seeing the bug:

![image](https://user-images.githubusercontent.com/79941/198547446-d0f9692b-f90f-4242-b327-05e2c233c6ce.png)

And the version of chrome (107.0.etc):

![image](https://user-images.githubusercontent.com/79941/198547502-062dae79-eb02-41c8-afd7-0c3a74e38723.png)
