### ISSUE TITLE
Kernel Creation Issue with python 2.7

### ISSUE THREAD

**Issue by ahmadmahmood4040** [jupyter/notebook#6646]
While creating an kernel using the ipykernel command facing the below error. Need your kind and quick support.

(python2) [cdp.juphub@bipcdpe02acdfrp ~]$ python -m ipykernel install --user --name python2 --display-name "Python 2"
Traceback (most recent call last):
  File "/data6/anaconda/anaconda3/envs/python2/lib/python2.7/runpy.py", line 163, in _run_module_as_main
    mod_name, _Error)
  File "/data6/anaconda/anaconda3/envs/python2/lib/python2.7/runpy.py", line 111, in _get_module_details
    __import__(mod_name)  # Do not catch exceptions initializing package
  File "/data6/anaconda/anaconda3/envs/python2/lib/python2.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/data6/anaconda/anaconda3/envs/python2/lib/python2.7/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/data6/anaconda/anaconda3/envs/python2/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/data6/anaconda/anaconda3/envs/python2/lib/python2.7/site-packages/IPython/core/application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "/data6/anaconda/anaconda3/envs/python2/lib/python2.7/site-packages/traitlets/config/__init__.py", line 6, in <module>
    from .application import *
  File "/data6/anaconda/anaconda3/envs/python2/lib/python2.7/site-packages/traitlets/config/application.py", line 17, in <module>
    from decorator import decorator
  File "/data6/anaconda/anaconda3/envs/python2/lib/python2.7/site-packages/decorator.py", line 162
    print('Error in generated code:', file=sys.stderr)
                                          ^
SyntaxError: invalid syntax

**Comment by RRosio** [comment]
Hi @ahmadmahmood4040, thank you for submitting this issue. [Python 2 reached end of life](https://www.python.org/doc/sunset-python-2/) almost three years ago, it is no longer supported. Due to this I will go ahead and close this issue. If you do find places in the documentation that indicate Python 2 support, we would appreciate if you could let us know by opening up another issue! Thank you!
