### ISSUE TITLE
proactoreventloop’ object has no attribute ‘_ssock’ and winerror10013 while trying to open jupyter notebook from anaconda

### ISSUE THREAD

**Issue by Somesh140** [jupyter/notebook#6656]
when i try to open the jupyter notebook through anaconda navigator I am getting following issue:

proactoreventloop’ object has no attribute ‘_ssock’ and winerror10013 

What should I do?

**Comment by RRosio** [comment]
Hi @Somesh140, thank you for submitting this issue! Could you share what version of Jupyter Notebook you are using? Could you try uninstalling Jupyter Notebook and re-installing it?

**Comment by Somesh140** [comment]
@RRosio thanks for the reply.

when i tried `jupyter notebook --version` in command prompt it again gave the same error.

```
C:\Users\vedant>jupyter notebook --version
Traceback (most recent call last):
  File "C:\Users\vedant\anaconda3\Scripts\jupyter-notebook-script.py", line 10,
in <module>
    sys.exit(main())
  File "C:\Users\vedant\anaconda3\lib\site-packages\jupyter_core\application.py"
, line 269, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "C:\Users\vedant\anaconda3\lib\site-packages\traitlets\config\application
.py", line 845, in launch_instance
    app.initialize(argv)
  File "C:\Users\vedant\anaconda3\lib\site-packages\traitlets\config\application
.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "C:\Users\vedant\anaconda3\lib\site-packages\notebook\notebookapp.py", li
ne 2139, in initialize
    self._init_asyncio_patch()
  File "C:\Users\vedant\anaconda3\lib\site-packages\notebook\notebookapp.py", li
ne 2115, in _init_asyncio_patch
    nest_asyncio.apply()
  File "C:\Users\vedant\anaconda3\lib\site-packages\nest_asyncio.py", line 16, i
n apply
    loop = loop or asyncio.get_event_loop()
  File "C:\Users\vedant\anaconda3\lib\site-packages\nest_asyncio.py", line 45, i
n _get_event_loop
    loop = events.get_event_loop_policy().get_event_loop()
  File "C:\Users\vedant\anaconda3\lib\asyncio\events.py", line 639, in get_event
_loop
    self.set_event_loop(self.new_event_loop())
  File "C:\Users\vedant\anaconda3\lib\asyncio\events.py", line 659, in new_event
_loop
    return self._loop_factory()
  File "C:\Users\vedant\anaconda3\lib\asyncio\windows_events.py", line 315, in _
init_
    super()._init_(proactor)
  File "C:\Users\vedant\anaconda3\lib\asyncio\proactor_events.py", line 630, in
_init_
    self._make_self_pipe()
  File "C:\Users\vedant\anaconda3\lib\asyncio\proactor_events.py", line 761, in
_make_self_pipe
    self._ssock, self._csock = socket.socketpair()
  File "C:\Users\vedant\anaconda3\lib\socket.py", line 632, in socketpair
    lsock.listen()
PermissionError: [WinError 10013] An attempt was made to access a socket in a wa
y forbidden by its access permissions
Exception ignored in: <function BaseEventLoop._del_ at 0x00000096A48953A0>
Traceback (most recent call last):
  File "C:\Users\vedant\anaconda3\lib\asyncio\base_events.py", line 688, in __de
l__
  File "C:\Users\vedant\anaconda3\lib\asyncio\proactor_events.py", line 685, in
close
  File "C:\Users\vedant\anaconda3\lib\asyncio\proactor_events.py", line 753, in
_close_self_pipe
AttributeError: 'ProactorEventLoop' object has no attribute '_ssock'
```

But when I  try ```pip install notebook```. it gives the following output

```C:\Users\vedant>pip install notebook
Requirement already satisfied: notebook in c:\users\vedant\anaconda3\lib\site-pa
ckages (6.4.12)
Requirement already satisfied: tornado>=6.1 in c:\users\vedant\anaconda3\lib\sit
e-packages (from notebook) (6.1)
Requirement already satisfied: argon2-cffi in c:\users\vedant\anaconda3\lib\site
-packages (from notebook) (21.3.0)
Requirement already satisfied: ipykernel in c:\users\vedant\anaconda3\lib\site-p
ackages (from notebook) (6.15.2)
Requirement already satisfied: prometheus-client in c:\users\vedant\anaconda3\li
b\site-packages (from notebook) (0.14.1)
Requirement already satisfied: nbformat in c:\users\vedant\anaconda3\lib\site-pa
ckages (from notebook) (5.5.0)
Requirement already satisfied: terminado>=0.8.3 in c:\users\vedant\anaconda3\lib
\site-packages (from notebook) (0.13.1)
Requirement already satisfied: Send2Trash>=1.8.0 in c:\users\vedant\anaconda3\li
b\site-packages (from notebook) (1.8.0)
Requirement already satisfied: nest-asyncio>=1.5 in c:\users\vedant\anaconda3\li
b\site-packages (from notebook) (1.5.5)
Requirement already satisfied: jinja2 in c:\users\vedant\anaconda3\lib\site-pack
ages (from notebook) (2.11.3)
Requirement already satisfied: jupyter-client>=5.3.4 in c:\users\vedant\anaconda
3\lib\site-packages (from notebook) (7.3.4)
Requirement already satisfied: traitlets>=4.2.1 in c:\users\vedant\anaconda3\lib
\site-packages (from notebook) (5.1.1)
Requirement already satisfied: nbconvert>=5 in c:\users\vedant\anaconda3\lib\sit
e-packages (from notebook) (6.4.4)
Requirement already satisfied: ipython-genutils in c:\users\vedant\anaconda3\lib
\site-packages (from notebook) (0.2.0)
Requirement already satisfied: pyzmq>=17 in c:\users\vedant\anaconda3\lib\site-p
ackages (from notebook) (23.2.0)
Requirement already satisfied: jupyter-core>=4.6.1 in c:\users\vedant\anaconda3\
lib\site-packages (from notebook) (4.11.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vedant\anacond
a3\lib\site-packages (from jupyter-client>=5.3.4->notebook) (2.8.2)
Requirement already satisfied: entrypoints in c:\users\vedant\anaconda3\lib\site
-packages (from jupyter-client>=5.3.4->notebook) (0.4)
Requirement already satisfied: pywin32>=1.0 in c:\users\vedant\anaconda3\lib\sit
e-packages (from jupyter-core>=4.6.1->notebook) (302)
Requirement already satisfied: beautifulsoup4 in c:\users\vedant\anaconda3\lib\s
ite-packages (from nbconvert>=5->notebook) (4.11.1)
Requirement already satisfied: bleach in c:\users\vedant\anaconda3\lib\site-pack
ages (from nbconvert>=5->notebook) (4.1.0)
Requirement already satisfied: jupyterlab-pygments in c:\users\vedant\anaconda3\
lib\site-packages (from nbconvert>=5->notebook) (0.1.2)
Requirement already satisfied: pygments>=2.4.1 in c:\users\vedant\anaconda3\lib\
site-packages (from nbconvert>=5->notebook) (2.11.2)
Requirement already satisfied: testpath in c:\users\vedant\anaconda3\lib\site-pa
ckages (from nbconvert>=5->notebook) (0.6.0)
Requirement already satisfied: defusedxml in c:\users\vedant\anaconda3\lib\site-
packages (from nbconvert>=5->notebook) (0.7.1)
Requirement already satisfied: nbclient<0.6.0,>=0.5.0 in c:\users\vedant\anacond
a3\lib\site-packages (from nbconvert>=5->notebook) (0.5.13)
Requirement already satisfied: mistune<2,>=0.8.1 in c:\users\vedant\anaconda3\li
b\site-packages (from nbconvert>=5->notebook) (0.8.4)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\vedant\anaconda3
\lib\site-packages (from nbconvert>=5->notebook) (1.5.0)
Requirement already satisfied: MarkupSafe>=0.23 in c:\users\vedant\anaconda3\lib
\site-packages (from jinja2->notebook) (2.0.1)
Requirement already satisfied: jsonschema>=2.6 in c:\users\vedant\anaconda3\lib\
site-packages (from nbformat->notebook) (4.16.0)
Requirement already satisfied: fastjsonschema in c:\users\vedant\anaconda3\lib\s
ite-packages (from nbformat->notebook) (2.16.2)
Requirement already satisfied: pywinpty>=1.1.0 in c:\users\vedant\anaconda3\lib\
site-packages (from terminado>=0.8.3->notebook) (2.0.2)
Requirement already satisfied: argon2-cffi-bindings in c:\users\vedant\anaconda3
\lib\site-packages (from argon2-cffi->notebook) (21.2.0)
Requirement already satisfied: packaging in c:\users\vedant\anaconda3\lib\site-p
ackages (from ipykernel->notebook) (21.3)
Requirement already satisfied: ipython>=7.23.1 in c:\users\vedant\anaconda3\lib\
site-packages (from ipykernel->notebook) (7.31.1)
Requirement already satisfied: debugpy>=1.0 in c:\users\vedant\anaconda3\lib\sit
e-packages (from ipykernel->notebook) (1.5.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\vedant\anacond
a3\lib\site-packages (from ipykernel->notebook) (0.1.6)
Requirement already satisfied: psutil in c:\users\vedant\anaconda3\lib\site-pack
ages (from ipykernel->notebook) (5.9.0)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in c
:\users\vedant\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->not
ebook) (3.0.20)
Requirement already satisfied: backcall in c:\users\vedant\anaconda3\lib\site-pa
ckages (from ipython>=7.23.1->ipykernel->notebook) (0.2.0)
Requirement already satisfied: setuptools>=18.5 in c:\users\vedant\anaconda3\lib
\site-packages (from ipython>=7.23.1->ipykernel->notebook) (63.4.1)
Requirement already satisfied: decorator in c:\users\vedant\anaconda3\lib\site-p
ackages (from ipython>=7.23.1->ipykernel->notebook) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\vedant\anaconda3\lib\site-
packages (from ipython>=7.23.1->ipykernel->notebook) (0.18.1)
Requirement already satisfied: colorama in c:\users\vedant\anaconda3\lib\site-pa
ckages (from ipython>=7.23.1->ipykernel->notebook) (0.4.5)
Requirement already satisfied: pickleshare in c:\users\vedant\anaconda3\lib\site
-packages (from ipython>=7.23.1->ipykernel->notebook) (0.7.5)
Requirement already satisfied: attrs>=17.4.0 in c:\users\vedant\anaconda3\lib\si
te-packages (from jsonschema>=2.6->nbformat->notebook) (21.4.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in
c:\users\vedant\anaconda3\lib\site-packages (from jsonschema>=2.6->nbformat->not
ebook) (0.18.0)
Requirement already satisfied: six>=1.5 in c:\users\vedant\anaconda3\lib\site-pa
ckages (from python-dateutil>=2.8.2->jupyter-client>=5.3.4->notebook) (1.16.0)
Requirement already satisfied: cffi>=1.0.1 in c:\users\vedant\anaconda3\lib\site
-packages (from argon2-cffi-bindings->argon2-cffi->notebook) (1.15.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\vedant\anaconda3\lib\si
te-packages (from beautifulsoup4->nbconvert>=5->notebook) (2.3.1)
Requirement already satisfied: webencodings in c:\users\vedant\anaconda3\lib\sit
e-packages (from bleach->nbconvert>=5->notebook) (0.5.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\vedant\anaco
nda3\lib\site-packages (from packaging->ipykernel->notebook) (3.0.9)
Requirement already satisfied: pycparser in c:\users\vedant\anaconda3\lib\site-p
ackages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->notebook) (2.21)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in c:\users\vedant\anaconda3\
lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->notebook) (0.8.3
)
Requirement already satisfied: wcwidth in c:\users\vedant\anaconda3\lib\site-pac
kages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.23.1->ipyke
rnel->notebook) (0.2.5)
WARNING: There was an error checking the latest version of pip.```

**Comment by RRosio** [comment]
Hi @Somesh140, thanks for the update. Are you able to successfully uninstall notebook with `pip uninstall notebook`? It's not clear that this is an issue with Notebook yet, so it would be great to try and identify if you only have issues with Jupyter Notebook?

**Comment by Somesh140** [comment]
@RRosio I uninstalled the Antivirus from my system and now I am no more facing this issue.
