### ISSUE TITLE
The code causes the kernel to die due to infinite recursion

### ISSUE THREAD

**Issue by CoolPlayLin** [jupyter/notebook#6687]
**Describe the bug**
A bug in the code caused the kernel to die

**To Reproduce**

- Using the following code can cause kernel death
```
class A:
    def __init__(self, data) -> None:
        self.data = data
    def __bool__(self) -> bool:
        return bool(a)
a = A("Test")
bool(a)
```

**Expected behavior**
- Python reports errors due to infinite recursion
![image](https://user-images.githubusercontent.com/96709586/211723319-a840fcbe-fb65-42e4-adc2-f88da8064d6c.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/96709586/211723794-55a0a1df-eb48-4c88-895a-525f7493a689.png)

**Desktop (please complete the following information):**

- OS: Windows 11 22H2
- Browser: Edge
- Version: 👇👇👇

![image](https://user-images.githubusercontent.com/96709586/211724118-705c21f0-2cc5-4778-9a5a-4a7b7939ee8c.png)

**Comment by CoolPlayLin** [comment]
![image](https://user-images.githubusercontent.com/96709586/211724329-d86fd16e-abbc-4694-bbc7-75a191449f07.png)

**Comment by RRosio** [comment]
Thanks for reporting @CoolPlayLin. A similar issue has previously been reported as well https://github.com/jupyter/notebook/issues/2648.

**Comment by CoolPlayLin** [comment]
You probably didn't get what I mean
@RRosio I'm focusing on kernel bugs

**Comment by CoolPlayLin** [comment]
After running the above code, Python will prompt an error, but Jupyter notebook is the kernel directly dead
@RRosio

**Comment by CoolPlayLin** [comment]
@RRosio

**Comment by RRosio** [comment]
@CoolPlayLin Thank you for clarifying this issue. This issue has been accepted but no one is actively working on it at the moment. If you'd like to look into this issue, we'd welcome a pull request!

**Comment by blairfrandeen** [comment]
I had this same issue. My code that caused it to crash:
```python
class Bug:
    def __post_init__(self): # NOTE: Should be __init__
        self._config = {"bug": True}
    def __getattr__(self, name):
        return self._config[name]

b = Bug()
b.bug
```

Running this code in the Python interpreter gives the following:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in __getattr__
  File "<stdin>", line 5, in __getattr__
  File "<stdin>", line 5, in __getattr__
  [Previous line repeated 996 more times]
RecursionError: maximum recursion depth exceeded
```

Note that the following code, when run in a Jupyter Notebook, generates a recursion error as expected, without killing the kernel.
```python
def inf_rec():
    inf_rec()
inf_rec()
```

**Comment by CoolPlayLin** [comment]
Any update?

**Comment by CoolPlayLin** [comment]
@RRosio Hello, it's been 4 years. Any update on this?

**Comment by krassowski** [comment]
This is a wrong repo to report this issue, as this is about a code run in a kernel, nothing notebook-specific. Depending on which Python kernel you use, you should report issues like that in ipykernel or xeus-python or another repository. There is just no code to be patched on this side.
