### ISSUE TITLE
Jupyter kernel issues

### ISSUE THREAD

**Issue by Anu1305** [jupyter/notebook#6699]
```

Traceback (most recent call last):
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/tornado/web.py", line 1713, in _execute
    # Unset result to avoid circular references
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/tornado/gen.py", line 776, in run
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 72, in post
    type=mtype))
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/tornado/gen.py", line 776, in run
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/tornado/gen.py", line 776, in run
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/tornado/gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/tornado/gen.py", line 234, in wrapper
    yielded = ctx_run(next, result)
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/jupyter_client/utils.py", line 30, in wrapped
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/jupyter_client/utils.py", line 27, in wrapped
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/asyncio/tasks.py", line 223, in __step
    result = coro.send(None)
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 214, in _async_start_kernel
    self._kernels[kernel_id] = km
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/jupyter_client/utils.py", line 30, in wrapped
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/jupyter_client/utils.py", line 27, in wrapped
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/asyncio/tasks.py", line 223, in __step
    result = coro.send(None)
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/jupyter_client/manager.py", line 90, in wrapper
    def __init__(self, *args, **kwargs):
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/jupyter_client/manager.py", line 82, in wrapper
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/jupyter_client/manager.py", line 394, in _async_start_kernel
    self._shutdown_status = _ShutdownStatus.ShutdownRequest
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/jupyter_client/utils.py", line 30, in wrapped
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/jupyter_client/utils.py", line 27, in wrapped
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/nest_asyncio.py", line 90, in run_until_complete
    return f.result()
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/asyncio/futures.py", line 178, in result
    raise self._exception
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/asyncio/tasks.py", line 223, in __step
    result = coro.send(None)
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/jupyter_client/manager.py", line 311, in _async_launch_kernel
    self._control_socket = self._create_connected_socket("control")
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/jupyter_client/provisioning/local_provisioner.py", line 204, in launch_kernel
    return provisioner_info
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/jupyter_client/launcher.py", line 170, in launch_kernel
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/site-packages/jupyter_client/launcher.py", line 158, in launch_kernel
    except Exception as ex:
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/root/anaconda3/envs/TensorPy36/lib/python3.7/subprocess.py", line 1453, in _execute_child
    restore_signals, start_new_session, preexec_fn)
BlockingIOError: [Errno 11] Resource temporarily unavailable
```

**Comment by RRosio** [comment]
Hi @Anu1305, we would need more information about your environment to be able to diagnose what may be happening. Could you provide the output of running `jupyter --version`?

**Comment by PurnaDurga** [comment]
Hi Rosio,

Thanks for the response.
After running jupyter --version, I can see this.
jupyter core     : 4.6.1
jupyter-notebook : 5.2.2
qtconsole        : 4.5.5
ipython          : 7.16.1
ipykernel        : 5.5.6
jupyter client   : 7.1.2
jupyter lab      : 1.1.4
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.4
traitlets        : 4.3.3

**Comment by Anu1305** [comment]
Hi Rosio,

Thanks for the response.
After running jupyter --version, I can see this.
jupyter core : 4.6.1
jupyter-notebook : 5.2.2
qtconsole : 4.5.5
ipython : 7.16.1
ipykernel : 5.5.6
jupyter client : 7.1.2
jupyter lab : 1.1.4
nbconvert : 5.6.1
ipywidgets : 7.5.1
nbformat : 5.0.4
traitlets : 4.3.3

**Comment by RRosio** [comment]
Thank you for providing the additional information @Anu1305. Based on the Notebook version you are using, since it is an older version would it be possible for you to upgrade to Notebook 6.x and check if this error is still coming up?

**Comment by RRosio** [comment]
Hi @Anu1305, just wanted to follow up with you to find out if you are still encountering this issue, and if so is it possible for you to try to upgrade as previously mentioned?

**Comment by RRosio** [comment]
Hi @Anu1305, closing this issue as there have been no recent updates, however please feel welcome to re-open this issue with updates that could help in diagnosing the error!
