### ISSUE TITLE
NotebookApp Error unpacking user from cookie

### ISSUE THREAD

**Issue by ggrrll** [jupyter/notebook#6702]
**Describe the bug**
notebook keeps giving `forbidden` error, when trying to save

(in the title, the error message in console, with many 403 warnings)

**To Reproduce**
just launch notebook from terminal 

**Desktop (please complete the following information):**

- OS: macOS 13.0 
- Browser: brave, safari

some relevant packages from my `pip freeze`
```
42:ipykernel==6.20.2
44:ipython==8.8.0
45:ipython-genutils==0.2.0

55:jupyter==1.0.0
56:jupyter-console==6.4.4
57:jupyter-contrib-core==0.3.3
58:jupyter-contrib-nbextensions==0.5.1
59:jupyter-events==0.6.3
60:jupyter-highlight-selected-word==0.2.0
61:jupyter-latex-envs==1.4.6
62:jupyter-nbextensions-configurator==0.4.1
63:jupyter-server-mathjax==0.2.6
64:jupyter_client==7.4.9
65:jupyter_core==5.1.3
66:jupyter_server==2.1.0
67:jupyter_server_terminals==0.4.4
68:jupyterlab-pygments==0.2.2
69:jupyterlab-widgets==1.1.1
70:jupyterlab_server==2.19.0
```

**Comment by RRosio** [comment]
Hi @ggrrll thank you for submitting this issue. Are you running from a directory where you have the needed permissions? Does this issue come up if you run from a different directory?

**Comment by ggrrll** [comment]
yes, I didn't have problems actually last week (also, I do not have issues with jupyter lab) ... the only thing it changed in the meantime, as far as I can see, it's the installation of *jupyter lab* indeed

**Comment by burnpanck** [comment]
I also started to observe this behaviour, though I do not know what changed in my environment. I am on macOS 13.1, with latest Chrome. I start the jupyter notebook server via the terminal from my home directory as always, which then automatically launches the browser on the jupyter notebook file browser page. I can then successfully open a notebook, but just a few seconds later, it stopps working ("forbidden"). The terminal with the server shows `Error unpacking user from cookie: Extra data: line 1 column 2 (char 1)`. If I refresh the file browser page, it asks me for the token. I can enter the token, which will successfully forward me then to the file browser page. However, after a short time, the same behaviour repeats.

**Comment by ggrrll** [comment]
might be related to #2396

**Comment by ggrrll** [comment]
btw, this issue seems to be affecting also other tool, like `nbdiff`  -- hereby the console error 

```
[E web:1798] Uncaught exception GET /difftool (127.0.0.1)
HTTPServerRequest(protocol='http', host='127.0.0.1:52958', method='GET', uri='/difftool', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tornado/web.py", line 1692, in _execute
    result = await result
  File "/usr/local/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 608, in prepare
    _user = await _user
  File "/usr/local/lib/python3.9/site-packages/jupyter_server/auth/identity.py", line 241, in _get_user
    _cookie_user = self.get_user_cookie(handler)
  File "/usr/local/lib/python3.9/site-packages/jupyter_server/auth/identity.py", line 399, in get_user_cookie
    _user_cookie = handler.get_secure_cookie(
  File "/usr/local/lib/python3.9/site-packages/tornado/web.py", line 773, in get_secure_cookie
    self.require_setting("cookie_secret", "secure cookies")
  File "/usr/local/lib/python3.9/site-packages/tornado/web.py", line 1592, in require_setting
    raise Exception(
Exception: You must define the 'cookie_secret' setting in your application to use secure cookies
[E web:1221] Uncaught exception in write_error
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/tornado/web.py", line 1692, in _execute
    result = await result
  File "/usr/local/lib/python3.9/site-packages/jupyter_server/base/handlers.py", line 608, in prepare
    _user = await _user
  File "/usr/local/lib/python3.9/site-packages/jupyter_server/auth/identity.py", line 241, in _get_user
    _cookie_user = self.get_user_cookie(handler)
  File "/usr/local/lib/python3.9/site-packages/jupyter_server/auth/identity.py", line 399, in get_user_cookie
    _user_cookie = handler.get_secure_cookie(
  File "/usr/local/lib/python3.9/site-packages/tornado/web.py", line 773, in get_secure_cookie
    self.require_setting("cookie_secret", "secure cookies")
  File "/usr/local/lib/python3.9/site-packages/tornado/web.py", line 1592, in require_setting
    raise Exception(
Exception: You must define the 'cookie_secret' setting in your application to use secure cookies

```

**Comment by burnpanck** [comment]
Not sure this is related to #2396. That thread is overflowing with people not having the right user permissions for the folder they are trying to access. Mine are correct. Also, just disabling token verification is definitely *not* a solution. On the other hand, #5492 does seem related. Following their thread, I downgraded my `jupyter_server` package from `2.0.1` to `1.23.5` (i.e. the latest satisfying `jupyter_server<2`). I conclude then that the recent version change did break something.

**Comment by ggrrll** [comment]
yeah...indeed probably related to #1038

**Comment by drscotthawley** [comment]
Are there any suggested workarounds for this at the moment, e.g. downgrade juptyer, or...? 

I would love to be able to edit one of my notebooks right now, but this error is preventing it:
```
[E 15:52:41.105 NotebookApp] Error unpacking user from cookie: Extra data: line 1 column 4 (char 3)
[W 15:52:41.105 NotebookApp] Clearing invalid/expired login cookie username-localhost-8888
```
And then I get a window showing "Connection Failed": 
<img width="938" alt="Screen Shot 2023-02-01 at 4 00 26 PM" src="https://user-images.githubusercontent.com/13925685/216173207-016f4ba7-d43f-4745-843a-32d896a45049.png">



I do have write permission in the directory - it's my laptop. 

Version info:
```bash
$ pip list | grep jupyter
jupyter-book                      0.13.1
jupyter-cache                     0.4.3
jupyter_client                    7.4.9
jupyter-contrib-core              0.4.2
jupyter_core                      5.1.3
jupyter-events                    0.6.3
jupyter-nbextensions-configurator 0.6.1
jupyter_server                    2.1.0
jupyter-server-mathjax            0.2.6
jupyter_server_terminals          0.4.4
jupyter-sphinx                    0.3.2
jupyterlab-pygments               0.2.2
jupyterlab-widgets                1.1.1
sphinx-jupyterbook-latex          0.4.7

$ python --version
Python 3.10.9

$ pip list | grep ^nb
nbclassic                         0.4.8
nbclient                          0.5.13
nbconvert                         6.5.4
nbdev                             2.3.9
nbdime                            3.1.1
nbformat                          5.7.3
```

MacOS 12.3 

This happens for all notebooks I try to open (which I used to be able to open), not just a particular notebook.

**Comment by drscotthawley** [comment]
Update: Found a workaround via [this StackExchange answer]: 

Running
```
pip install --upgrade 'jupyter-server<2.0.0'
```
fixed the problem, without changing anything else. :-)

**Comment by nb-programmer** [comment]
Here is some log output that was resulted from this issue:
```
[E 19:41:41.186 NotebookApp] Error unpacking user from cookie: Extra data: line 1 column 2 (char 1)
[W 19:41:41.186 NotebookApp] Clearing invalid/expired login cookie username-192-168-0-10-8888
```

How to reproduce:
- Latest jupyter-notebook (jupyter-notebook 6.5.3-1 on Arch Linux as of now)
- Have password login instead of token.
> ~/.jupyter/jupyter_notebook_config.json:
```json
{
  "NotebookApp": {
    "password": "argon2:$a<snip>"
  }
}
```
- Proper file read/write/execute permission set. Can create files in the browser.
- Open the :8888 server page, login normally. This works as expected and does not kick me out.
- Create notebook
- Open it
- Above log messages occur as soon as the page loads. If you open an existing/running notebook, same will occur.
- Kernel disconnects, shows Forbidden.
- Refresh, shows login page again. Login again, and it loads the notebook. Instantly kicks out with same error.

Problematic cookie example:
> "username-192-168-0-10-8888" = "2|1:0|10:1678285174|26:username-192-168-0-10-8888|44:ZjgwNDY3OGY1NWE2NDNiYWJhYjE0YzQzZGFmNzk2ZDY=|700d01ee58758b6ce2239f56d06e27bdc0689e083d9abd0ed85dc01d159749bc"
(Not sure if any sensitive data is there in this, tell me please, I'll remove it straight away)

**Comment by xinyi-joffre** [comment]
Is there any workaround that doesn't involve downgrading jupyter-server? Jupyter-server has a vulnerability, and we are getting flagged that we need to upgrade to at least jupyter-server>2.11.2

**Comment by lappemic** [comment]
Downgrading did not solve it for me. I still keep getting:

```bash
[W 2024-02-23 16:01:38.253 ServerApp] wrote error: 'Forbidden'
[W 2024-02-23 16:01:38.254 ServerApp] 403 GET /api/sessions?1708700498223 (127.0.0.1) 2.85ms referer=None
```

is there anyother fix?

**Comment by weinbe58** [comment]
I am also having the same problem. when running jupyter-lab I get a stack trace as well:

```
[W 2024-03-22 10:07:48.569 ServerApp] 403 GET /api/kernels?1711116468549 (@127.0.0.1) 1.40ms referer=None
[W 2024-03-22 10:07:48.569 ServerApp] wrote error: 'Forbidden'
    Traceback (most recent call last):
      File "/Users/pweinberg/Documents/atom_compiler_dev/flair-python/.venv/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/pweinberg/Documents/atom_compiler_dev/flair-python/.venv/lib/python3.11/site-packages/tornado/web.py", line 3289, in wrapper
        url = self.get_login_url()
              ^^^^^^^^^^^^^^^^^^^^
      File "/Users/pweinberg/Documents/atom_compiler_dev/flair-python/.venv/lib/python3.11/site-packages/jupyter_server/base/handlers.py", line 782, in get_login_url
        raise web.HTTPError(403)
    tornado.web.HTTPError: HTTP 403: Forbidden
```
Note sure if this is helpful at all.

**Comment by aimgo** [comment]
This issue persists on Jupyter Notebook 6.4.12. For me, the only 'workaround' (if you can call it that) aside from downgrading is not _creating_ another notebook but copying an existing empty one and editing that.

**Comment by OuYaozhong** [comment]
I also meet this problem. But I found the reason for me.

I am binding the default `8888` port of the remote machine from my local computer by `ssh -NfL 8888:localhost:8888 remote_machine_alias` at first, and then I open the `jupyter lab` in the remote machine, then the problem occur.

If I kill the binding program in my local computer, then reopen the `jupyter lab`, then the error disappears.

But this problem seems only occur when you install the `jupyter-lab` for the first time, since I can not reproduce the problem after I successfully solved it by killing the binding program occupying the port `8888`.

Hint: this problem maybe telling that somebody is occupied the port.

Hope my case can help.
