### ISSUE TITLE
trouble testing notebook 7.0.0rc2 - `jupyter notebook` always gets me a blank page

### ISSUE THREAD

**Issue by parmentelat** [jupyter/notebook#6953]
# Description

not exactly a bug per se: I'm trying to test the latest release candidate, but can't get it to start

now, I have been testing early releases, and developing extensions, and my environment obviously is in shambles, but I can't find out what's wrong

## the symptom

when I run `jupyter notebook`, I end up with a blank page in the browser

the console shows this single error message
```console
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'call')
    at v (bundle.js:1:516)
    at 65733 (5733.bundle.js:1:597)
    at v (bundle.js:1:516)
    at bundle.js:1:13373
    at v.m.<computed> (bundle.js:1:48781)
    at v (bundle.js:1:516)
    at 880.bundle.js:1:398
```

and clicking on the topmost stack frame brings me here

![image](https://github.com/jupyter/notebook/assets/4519227/77ce5469-d6e6-45a9-8e8e-dd4b767d62bd)

## since when

since some time end of last week; I was trying different patches from @jtpio, using wheels from the CI artefacts (before that I was using `pip install git+https:// urls but that was super long..); not quite sure it is the root cause though

## environment

this is in a conda env that has the minimal set of pips installed (jupyterlab + notebook essentially)

```bash
pip freeze | egrep 'jupyte|notebook'
jupyter-events==0.6.3
jupyter-lsp==2.2.0
jupyter_client==8.2.0
jupyter_core==5.3.1
jupyter_server==2.6.0
jupyter_server_terminals==0.4.4
jupyterlab==4.0.2
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.7
jupyterlab_server==2.23.0
notebook==7.0.0rc2
notebook_shim==0.2.3
```

in an attempt to remove configuration errors I have hidden my `~/.jupyter` folder, but I still observe the same behaviour

one odd thing is this:

```bash
jupyter labextension list
JupyterLab v4.0.2
/Users/tparment/miniconda3/envs/jlab4-nb7/share/jupyter/labextensions
        jupyterlab_pygments v0.2.2 enabled  X (python, jupyterlab_pygments)
        jupyter-matplotlib v0.11.3 enabled OK
        @jupyter-notebook/lab-extension v7.0.0-rc.2 enabled OK
        @jupyter-widgets/jupyterlab-manager v5.0.7 enabled  X (python, jupyterlab_widgets)


   The following extensions are outdated:
        jupyterlab_pygments
        @jupyter-widgets/jupyterlab-manager

   Consider running "jupyter labextension update --all" to check for updates.
```

but then when I run it I get

```
jupyter labextension update --all
(Deprecated) Updating extensions with the jupyter labextension update command is now deprecated and will be removed in a future major version of JupyterLab.

Users should manage prebuilt extensions with package managers like pip and conda, and extension authors are encouraged to distribute their extensions as prebuilt packages
```

so I'm kind of getting out of ideas, please advise :)

**Comment by parmentelat** [comment]
as an update on this

I still run into this issue although less systematically

I spend my time trying various combinations of released/pre-released modules/extensions these days
And so I am starting to suspect that I encounter this issue when my browser uses cached code from an earlier session that had a different mix of versions

From now on I will more routinely do hard reloads of the browser (I mean Shift-Command-R) when I run into this kind of symptom
