### ISSUE TITLE
Unable to run jupyter in android 13, kernel dies.

### ISSUE THREAD

**Issue by Fcucgvhhhvjv** [jupyter/notebook#7018]
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository

Hi , i use jupyter notebook in android through termux . In the Android version 13 jupyter notebook no longer works in termux proot ubuntu environment ,it  works fine in Android 12.
Android 13 restricts ifconfig and similar commands in proot ubuntu and termux environment but jupyter notebook and lab works in termux .
The error log in
[W 2023-08-10 11:14:30.893 ServerApp] wrote error: 'Kernel does not exist: a8926e27-883d-45f8-8189-aee028356851'                                            Traceback (most recent call last):                                            File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1786, in _execute                                                                     result = await result                                                     File "/usr/local/lib/python3.10/dist-packages/jupyter_server/services/kernels/handlers.py", line 73, in get                                               model = await ensure_async(km.kernel_model(kernel_id))                    File "/usr/local/lib/python3.10/dist-packages/jupyter_server/services/kernels/kernelmanager.py", line 501, in kernel_model                                self._check_kernel_id(kernel_id)                                          File "/usr/local/lib/python3.10/dist-packages/jupyter_server/services/kernels/kernelmanager.py", line 532, in _check_kernel_id                            raise web.HTTPError(404, "Kernel does not exist: %s" % kernel_id)       tornado.web.HTTPError: HTTP 404: Not Found (Kernel does not exist: a8926e27-883d-45f8-8189-aee028356851)

/resolver/scr.cpp permission denied .
Is there any workaround for this to use in termux proot ubuntu environment.

Thank you

**Comment by Fcucgvhhhvjv** [comment]
@JasonWeill Any help?

**Comment by J-cybse** [comment]
I’d like to implement this. Please assign it to me.
