### ISSUE TITLE
7.0.2: pytest is failing on scanning units

### ISSUE THREAD

**Issue by kloczek** [jupyter/notebook#7024]
<!--
Right now, you're opening an issue to report a bug in Jupyter Notebook.

Please answer the following questions for yourself before submitting an issue
- [x] I checked the documentation and found no answer
- [ x I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository

## Description
I'm packaging your module as an rpm package so I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.

## Reproduce
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix> using 'installer` module
- run pytest with $PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>
- build is performed in env which is *`cut off from access to the public network`* (pytest is executed with `-m "not network"`)

## Expected behavior
pytest should not fail.

## Context
- Operating System and version: Linux x86/64
- Browser and version: N/A
- Jupyter Notebook version: 7.0.2:

Here is pytest output:
<details>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-notebook-7.0.2-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-notebook-7.0.2-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -m 'not network'
ImportError while loading conftest '/home/tkloczko/rpmbuild/BUILD/notebook-7.0.2/tests/conftest.py'.
tests/conftest.py:15: in <module>
    from notebook.app import JupyterNotebookApp
../../BUILDROOT/python-notebook-7.0.2-2.fc35.x86_64/usr/lib/python3.8/site-packages/notebook/app.py:6: in <module>
    from jupyter_client.utils import ensure_async
/usr/lib/python3.8/site-packages/jupyter_client/__init__.py:3: in <module>
    from .asynchronous import AsyncKernelClient
/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/__init__.py:1: in <module>
    from .client import AsyncKernelClient  # noqa
/usr/lib/python3.8/site-packages/jupyter_client/asynchronous/client.py:9: in <module>
    from ..client import KernelClient, reqrep
/usr/lib/python3.8/site-packages/jupyter_client/client.py:20: in <module>
    from .connect import ConnectionFileMixin
/usr/lib/python3.8/site-packages/jupyter_client/connect.py:20: in <module>
    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
/usr/lib/python3.8/site-packages/jupyter_core/paths.py:208: in <module>
    deprecation(
/usr/lib/python3.8/site-packages/jupyter_core/utils/__init__.py:89: in deprecation
    warnings.warn(message, DeprecationWarning, stacklevel=stacklevel + 1)
E   DeprecationWarning: Jupyter is migrating its paths to use standard platformdirs
E   given by the platformdirs library.  To remove this warning and
E   see the appropriate new directories, set the environment variable
E   `JUPYTER_PLATFORM_DIRS=1` and then run `jupyter --paths`.
E   The use of platformdirs will be the default in `jupyter_core` v6
```
</details>

Here is list of installed modules in build env
<details>

```console
Package                       Version
----------------------------- ---------
alabaster                     0.7.13
anyio                         3.7.0
argon2-cffi                   23.1.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
asttokens                     2.2.1
async-generator               1.10
async-lru                     2.0.4
attrs                         23.1.0
Babel                         2.12.1
backcall                      0.2.0
beautifulsoup4                4.12.2
bleach                        6.0.0
build                         0.10.0
certifi                       2023.7.22
cffi                          1.15.1
charset-normalizer            3.2.0
comm                          0.1.4
debugpy                       1.6.7
decorator                     5.1.1
defusedxml                    0.7.1
distro                        1.8.0
docutils                      0.20.1
editables                     0.5
exceptiongroup                1.1.3
executing                     1.2.0
fastjsonschema                2.18.0
fqdn                          1.5.1
gpg                           1.21.0
h11                           0.14.0
hatch-jupyter-builder         0.8.3
hatchling                     1.18.0
html5lib                      1.1
idna                          3.4
imagesize                     1.4.1
importlib-metadata            6.8.0
importlib-resources           6.0.1
iniconfig                     2.0.0
installer                     0.7.0
ipykernel                     6.25.1
ipython                       8.12.0
ipython-genutils              0.2.0
isoduration                   20.11.0
jedi                          0.19.0
Jinja2                        3.1.2
json5                         0.9.14
jsonpointer                   2.4
jsonschema                    4.19.0
jsonschema-specifications     2023.7.1
jupyter_client                8.3.0
jupyter_core                  5.3.1
jupyter-events                0.7.0
jupyter-lsp                   2.2.0
jupyter_server                2.7.2
jupyter_server_terminals      0.4.4
jupyterlab                    4.0.5
jupyterlab-pygments           0.1.2
jupyterlab_server             2.24.0
libcomps                      0.1.19
markdown-it-py                3.0.0
MarkupSafe                    2.1.3
matplotlib-inline             0.1.6
mdit-py-plugins               0.4.0
mdurl                         0.1.2
mistune                       2.0.5
myst-parser                   2.0.0
nbclassic                     0.5.6
nbclient                      0.8.0
nbconvert                     7.7.4
nbformat                      5.9.2
nest-asyncio                  1.5.7
notebook_shim                 0.2.3
outcome                       1.2.0
overrides                     7.4.0
packaging                     23.1
pandocfilters                 1.5.0
parso                         0.8.3
pathspec                      0.11.2
pexpect                       4.8.0
pickleshare                   0.7.5
pkg                           0.0.0
pkgutil_resolve_name          1.3.10
platformdirs                  3.10.0
pluggy                        1.2.0
ply                           3.11
prometheus-client             0.17.1
prompt-toolkit                3.0.38
psutil                        5.9.5
ptyprocess                    0.7.0
pure-eval                     0.2.2
pycparser                     2.21
Pygments                      2.16.0
pyproject_hooks               1.0.0
pytest                        7.4.0
pytest-integration            0.2.3
python-dateutil               2.8.2
python-json-logger            2.0.7
pytz                          2023.2
PyYAML                        6.0.1
pyzmq                         25.1.0
referencing                   0.30.2
requests                      2.31.0
requests-unixsocket           0.3.0
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rpds-py                       0.9.2
selenium                      4.10.0
Send2Trash                    1.8.2
six                           1.16.0
sniffio                       1.3.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.4.1
Sphinx                        7.0.1
sphinx_autodoc_typehints      1.22.0
sphinx-rtd-theme              1.2.2
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2
sphinxcontrib_github_alt      1.2
sphinxcontrib-htmlhelp        2.0.3
sphinxcontrib-jquery          4.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.9
stack-data                    0.6.2
terminado                     0.17.1
testpath                      0.6.0
tinycss2                      1.2.1
tomli                         2.0.1
tornado                       6.3.3
traitlets                     5.9.0
trio                          0.22.0
trio-websocket                0.10.2
trove-classifiers             2023.8.9
typing_extensions             4.7.1
uri-template                  1.2.0
urllib3                       1.26.15
wcwidth                       0.2.6
webcolors                     1.13
webencodings                  0.5.1
websocket-client              1.6.2
wheel                         0.41.1
wsproto                       1.2.0
zipp                          3.16.2
```
</details>

**Comment by andrii-i** [comment]
Hi @kloczek. Could you please post an error you are getting for more context?

**Comment by kloczek** [comment]
Looks like I've accidentally pressed enter before copy whole ticket content.
Sorry.

I cannot repeat now because now build is failing (with 7.02 and 7.0.3)
```console
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting build dependencies for wheel...
* Building wheel...
INFO:hatch_jupyter_builder.utils:Running jupyter-builder
INFO:hatch_jupyter_builder.utils:Building with hatch_jupyter_builder.npm_builder
INFO:hatch_jupyter_builder.utils:With kwargs: {'build_cmd': 'build:prod', 'editable_build_cmd': 'build', 'source_dir': 'packages', 'build_dir': 'notebook/static', 'npm': 'jlpm'}
INFO:hatch_jupyter_builder.utils:Installing build dependencies with npm.  This may take a while...
INFO:hatch_jupyter_builder.utils:> /usr/bin/jlpm install
➤ YN0000: ┌ Project validation
➤ YN0057: │ @jupyter-notebook/app: Resolutions field will be ignored
➤ YN0000: └ Completed
➤ YN0000: ┌ Resolution step
➤ YN0060: │ @jupyter-notebook/app@workspace:app provides webpack (pde4ea) with version 5.88.2, which doesn't satisfy what mini-css-extract-plugin requests
➤ YN0060: │ @jupyter-notebook/app@workspace:app provides webpack (p5ec5f) with version 5.88.2, which doesn't satisfy what style-loader requests
➤ YN0002: │ @jupyter-notebook/application-extension@workspace:packages/application-extension doesn't provide react (p227d4), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyter-notebook/notebook-extension@workspace:packages/notebook-extension doesn't provide react (pd7a13), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyter-notebook/tree-extension@workspace:packages/tree-extension doesn't provide react (pece4f), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyter-notebook/tree@workspace:packages/tree doesn't provide react (pc5d02), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyter-notebook/ui-components@workspace:packages/ui-components doesn't provide webpack (p04231), requested by babel-loader
➤ YN0002: │ @jupyterlab/cell-toolbar-extension@npm:4.0.5 doesn't provide react (paf6c9), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/console-extension@npm:4.0.5 doesn't provide react (pbeef9), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/csvviewer-extension@npm:4.0.5 doesn't provide react (p5959d), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/debugger-extension@npm:4.0.5 doesn't provide react (p76be0), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/documentsearch-extension@npm:4.0.5 doesn't provide react (p58e35), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/extensionmanager-extension@npm:4.0.5 doesn't provide react (p1dad6), requested by @jupyterlab/settingregistry
➤ YN0060: │ @jupyterlab/extensionmanager@npm:4.0.5 provides react (pe8152) with version 18.2.0, which doesn't satisfy what react-paginate requests
➤ YN0002: │ @jupyterlab/filebrowser-extension@npm:4.0.5 doesn't provide react (p90cfd), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/fileeditor-extension@npm:4.0.5 doesn't provide react (pe975e), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/htmlviewer-extension@npm:4.0.5 doesn't provide react (pcb5d3), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/json-extension@npm:4.0.5 doesn't provide @types/react (p804c8), requested by react-json-tree
➤ YN0002: │ @jupyterlab/mainmenu-extension@npm:4.0.5 doesn't provide react (p0b509), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/markdownviewer-extension@npm:4.0.5 doesn't provide react (p696b8), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/metadataform-extension@npm:4.0.5 doesn't provide react (p57981), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/metadataform@npm:4.0.5 doesn't provide @rjsf/utils (p552e8), requested by @rjsf/core
➤ YN0002: │ @jupyterlab/metadataform@npm:4.0.5 doesn't provide @rjsf/utils (pcf1ae), requested by @rjsf/validator-ajv8
➤ YN0002: │ @jupyterlab/services@npm:7.0.5 doesn't provide react (p4d970), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/settingeditor-extension@npm:4.0.5 doesn't provide react (p9efcd), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/terminal-extension@npm:4.0.5 doesn't provide react (p4b53d), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/testutils@npm:4.0.5 doesn't provide typescript (pd72c2), requested by @jupyterlab/testing
➤ YN0002: │ @jupyterlab/toc-extension@npm:6.0.5 doesn't provide react (pbd529), requested by @jupyterlab/settingregistry
➤ YN0002: │ @jupyterlab/translation-extension@npm:4.0.5 doesn't provide react (p8365f), requested by @jupyterlab/settingregistry
➤ YN0002: │ @lerna/legacy-package-management@npm:6.6.2 doesn't provide nx (pfc6c3), requested by @nrwl/devkit
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed in 0s 494ms
➤ YN0000: ┌ Fetch step
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
  File "/usr/lib/python3.8/site-packages/hatchling/build.py", line 56, in build_wheel
    return os.path.basename(next(builder.build(wheel_directory, ['standard'])))
  File "/usr/lib/python3.8/site-packages/hatchling/builders/plugin/interface.py", line 150, in build
    build_hook.initialize(version, build_data)
  File "/usr/lib/python3.8/site-packages/hatch_jupyter_builder/plugin.py", line 87, in initialize
    raise e
  File "/usr/lib/python3.8/site-packages/hatch_jupyter_builder/plugin.py", line 82, in initialize
    build_func(self.target_name, version, **build_kwargs)
  File "/usr/lib/python3.8/site-packages/hatch_jupyter_builder/utils.py", line 113, in npm_builder
    run([*npm_cmd, "install"], cwd=str(abs_path))
  File "/usr/lib/python3.8/site-packages/hatch_jupyter_builder/utils.py", line 229, in run
    return subprocess.check_call(cmd, **kwargs)
  File "/usr/lib64/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/jlpm', 'install']' died with <Signals.SIGSEGV: 11>.

ERROR Backend subprocess exited when trying to invoke build_wheel
```

**Comment by kloczek** [comment]
Command is in first line`
```
+  /usr/bin/python3 -sBm build -w --no-isolation
```
I'm using pep517 based build procedure (it can be used pip as well instead `build`)

**Comment by kloczek** [comment]
I did not tested yet this issue with python +3.9 ans I'm now moving all 1.1k rpm packages to 3.9.x.
