### ISSUE TITLE
Notebook 6.5.5 will not start in Python 3.9/3.10 environment

### ISSUE THREAD

**Issue by pythonic2020** [jupyter/notebook#7054]
## Description

Notebook 6.5.5 will not start in a conda env running Python 3.9 or 3.10.

## Reproduce

Steps to create env and reproduce problem:

1. conda create -n note39 -c conda-forge python=3.9
2. conda activate note39
3. conda config --env --add channels conda-forge
4. conda install notebook=6.5.5 matplotlib pandas

## Failure

(note39) PS C:\Users\me> jupyter notebook

```
Traceback (most recent call last):
  File "C:\Users\me\Miniconda3\envs\note39\lib\site-packages\notebook\traittypes.py", line 235, in _resolve_classes
    klass = self._resolve_string(klass)
  File "C:\Users\me\Miniconda3\envs\note39\lib\site-packages\traitlets\traitlets.py", line 2009, in _resolve_string
    return import_item(string)
  File "C:\Users\me\Miniconda3\envs\note39\lib\site-packages\traitlets\utils\importstring.py", line 30, in import_item
    module = __import__(package, fromlist=[obj])
ModuleNotFoundError: No module named 'jupyter_server.contents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\me\Miniconda3\envs\note39\Scripts\jupyter-notebook-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\me\Miniconda3\envs\note39\lib\site-packages\jupyter_core\application.py", line 285, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
  File "C:\Users\me\Miniconda3\envs\note39\lib\site-packages\traitlets\config\application.py", line 1044, in launch_instance
    app = cls.instance(**kwargs)
  File "C:\Users\me\Miniconda3\envs\note39\lib\site-packages\traitlets\config\configurable.py", line 555, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\me\Miniconda3\envs\note39\lib\site-packages\traitlets\traitlets.py", line 1295, in __new__
    inst.setup_instance(*args, **kwargs)
  File "C:\Users\me\Miniconda3\envs\note39\lib\site-packages\traitlets\traitlets.py", line 1338, in setup_instance
    super(HasTraits, self).setup_instance(*args, **kwargs)
  File "C:\Users\me\Miniconda3\envs\note39\lib\site-packages\traitlets\traitlets.py", line 1314, in setup_instance
    init(self)
  File "C:\Users\me\Miniconda3\envs\note39\lib\site-packages\notebook\traittypes.py", line 226, in instance_init
    self._resolve_classes()
  File "C:\Users\me\Miniconda3\envs\note39\lib\site-packages\notebook\traittypes.py", line 238, in _resolve_classes
    warn(f"{klass} is not importable. Is it installed?", ImportWarning)
TypeError: warn() missing 1 required keyword-only argument: 'stacklevel'
```

## Expected behavior

Notebook starts after typing: `jupyter notebook`

- Operating System and version: Win10 x64, conda version 23.7.4 (python 3.10 in base env)
- Browser and version: Firefox
- Jupyter Notebook version: 6.5.5

**Comment by pythonic2020** [comment]
This issue is covered here:

https://github.com/jupyter/notebook/pull/7051

**Comment by chopeen** [comment]
v6.5.6 fixed the issue for me.

**Comment by pythonic2020** [comment]
Notebook 6.5.6 hasn't been released on conda default or conda-forge repo channels yet...

**Comment by pythonic2020** [comment]
NB 6.5.6 solves the problem. Thank you!
