### ISSUE TITLE
`jupyter-notebook` stack trace  `TypeError: 'ExtendedCompletionFinder' object is not callable`

### ISSUE THREAD

**Issue by thisiswhereitype** [jupyter/notebook#7073]
## Description

Starting jupyter notebook results in a uncaught Python exception.

## Reproduce

`jupyter-notebook --version`

## Context

> Platform: Python 3.10.11 on Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.35

Conda reports:
```
$ conda list | grep notebook
notebook                  7.0.4              pyhd8ed1ab_0    conda-forge
notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
```

```
$ conda list | grep jupyter
jupyter-lsp               2.2.0              pyhd8ed1ab_0    conda-forge
jupyter_client            8.3.1              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.1           py310hff52083_0    conda-forge
jupyter_events            0.7.0              pyhd8ed1ab_2    conda-forge
jupyter_server            2.7.3              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab                4.0.6              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.25.0             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.9              pyhd8ed1ab_0    conda-forge
```

<details><summary>Troubleshoot Output</summary>
<pre>
name: tse
channels:
  - pytorch
  - fastai
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - aiohttp=3.8.5=py310h2372a71_0
  - aiohttp-retry=2.8.3=pyhd8ed1ab_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alsa-lib=1.2.10=hd590300_0
  - amqp=5.1.1=pyhd8ed1ab_0
  - annotated-types=0.5.0=pyhd8ed1ab_0
  - antlr-python-runtime=4.9.3=pyhd8ed1ab_1
  - anyio=3.7.1=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=23.1.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py310h2372a71_4
  - arrow=1.2.3=pyhd8ed1ab_0
  - asttokens=2.4.0=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-lru=2.0.4=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - asyncssh=2.13.2=pyhd8ed1ab_0
  - atk-1.0=2.38.0=hd4edc92_1
  - atpublic=3.0.1=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - attrs=23.1.0=pyh71513ae_1
  - autopep8=2.0.4=pyhd8ed1ab_0
  - aws-c-auth=0.7.3=he2921ad_3
  - aws-c-cal=0.6.2=hc309b26_1
  - aws-c-common=0.9.0=hd590300_0
  - aws-c-compression=0.2.17=h4d4d85c_2
  - aws-c-event-stream=0.3.2=h2e3709c_0
  - aws-c-http=0.7.12=hc865f51_1
  - aws-c-io=0.13.32=h1a03231_3
  - aws-c-mqtt=0.9.6=h3a0376c_0
  - aws-c-s3=0.3.17=h1678ad6_0
  - aws-c-sdkutils=0.1.12=h4d4d85c_1
  - aws-checksums=0.1.17=h4d4d85c_1
  - aws-crt-cpp=0.23.1=hf7d0843_2
  - aws-sdk-cpp=1.11.156=he6c2984_2
  - babel=2.12.1=pyhd8ed1ab_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backoff=2.2.1=pyhd8ed1ab_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.cached-property=1.0.2=pyhd8ed1ab_0
  - backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
  - backports.zoneinfo=0.2.1=py310hff52083_8
  - beautifulsoup4=4.12.2=pyha770c72_0
  - billiard=4.1.0=py310h2372a71_1
  - black=23.9.1=py310hff52083_0
  - bleach=6.0.0=pyhd8ed1ab_0
  - blessed=1.19.1=pyhe4f9e05_2
  - brotli=1.1.0=hd590300_0
  - brotli-bin=1.1.0=hd590300_0
  - brotlipy=0.7.0=py310h2372a71_1006
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.19.1=hd590300_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cachecontrol=0.12.14=pyhd8ed1ab_0
  - cachecontrol-with-filecache=0.12.14=pyhd8ed1ab_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.16.0=h0c91306_1017
  - celery=5.3.4=pyhd8ed1ab_1
  - certifi=2023.7.22=pyhd8ed1ab_0
  - cffi=1.15.1=py310h2fee648_5
  - cfgv=3.3.1=pyhd8ed1ab_0
  - charset-normalizer=3.2.0=pyhd8ed1ab_0
  - cleo=2.0.1=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - click-didyoumean=0.3.0=pyhd8ed1ab_0
  - click-plugins=1.1.1=py_0
  - click-repl=0.3.0=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - comm=0.1.4=pyhd8ed1ab_0
  - configobj=5.0.8=pyhd8ed1ab_0
  - contourpy=1.1.1=py310hd41b1e2_1
  - crashtest=0.4.1=pyhd8ed1ab_0
  - croniter=1.4.1=pyhd8ed1ab_0
  - cryptography=41.0.4=py310h75e40e8_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cuda-version=11.7=h67201e3_2
  - cudatoolkit=11.7.0=hd8887f6_10
  - cudnn=8.8.0.121=h838ba91_3
  - cycler=0.11.0=pyhd8ed1ab_0
  - dateutils=0.6.12=py_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.0=py310hc6cd4ac_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - deepdiff=6.5.0=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - dictdiffer=0.9.0=pyhd8ed1ab_0
  - diskcache=5.6.3=pyhd8ed1ab_0
  - distlib=0.3.7=pyhd8ed1ab_0
  - distro=1.8.0=pyhd8ed1ab_0
  - dpath=2.1.6=pyha770c72_0
  - dulwich=0.21.6=py310h2372a71_0
  - dvc=3.22.1=pyhd8ed1ab_0
  - dvc-data=2.16.3=pyhd8ed1ab_0
  - dvc-http=2.30.2=pyhd8ed1ab_2
  - dvc-objects=1.0.1=pyhd8ed1ab_0
  - dvc-render=0.6.0=pyhd8ed1ab_0
  - dvc-studio-client=0.15.0=pyhd8ed1ab_0
  - dvc-task=0.3.0=pyhd8ed1ab_0
  - dvclive=3.0.0=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - exceptiongroup=1.1.3=pyhd8ed1ab_0
  - execnb=0.1.5=py_0
  - executing=1.2.0=pyhd8ed1ab_0
  - expat=2.5.0=hcb278e6_1
  - fastapi=0.103.1=pyhd8ed1ab_0
  - fastcluster=1.2.6=py310h769672d_2
  - fastcore=1.5.29=py_0
  - filelock=3.12.4=pyhd8ed1ab_0
  - flatten-dict=0.4.2=pyhd8ed1ab_1
  - flufl.lock=7.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.42.1=py310h2372a71_0
  - fqdn=1.5.1=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.4.0=py310h2372a71_1
  - fsspec=2023.9.2=pyh1a96a4e_0
  - funcy=2.0=pyhd8ed1ab_0
  - future=0.18.3=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.10=h6c15284_3
  - gettext=0.21.1=h27087fc_0
  - gflags=2.2.2=he1b5a44_1004
  - ghapi=1.0.3=py_0
  - giflib=5.2.1=h0b41bf4_3
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.37=pyhd8ed1ab_0
  - glib=2.78.0=hfc55251_0
  - glib-tools=2.78.0=hfc55251_0
  - glog=0.6.0=h6f12383_0
  - gmp=6.2.1=h58526e2_0
  - gmpy2=2.1.2=py310h3ec546c_1
  - grandalf=0.7=pyhd8ed1ab_0
  - graphite2=1.3.13=h58526e2_1001
  - graphviz=8.1.0=h28d9a01_0
  - gst-plugins-base=1.22.6=h8e1006c_0
  - gstreamer=1.22.6=h98fc4e7_0
  - gtk2=2.24.33=h90689f9_2
  - gts=0.7.6=h977cf35_4
  - h11=0.14.0=pyhd8ed1ab_0
  - harfbuzz=8.2.1=h3d44ed6_0
  - html5lib=1.1=pyh9f0ad1d_0
  - hydra-core=1.3.2=pyhd8ed1ab_0
  - icu=73.2=h59595ed_0
  - identify=2.5.29=pyhd8ed1ab_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - importlib_metadata=6.8.0=hd8ed1ab_0
  - importlib_resources=6.1.0=pyhd8ed1ab_0
  - inquirer=3.1.3=pyhd8ed1ab_0
  - ipykernel=6.25.2=pyh2140261_0
  - ipython=8.15.0=pyh0d859eb_0
  - ipywidgets=8.1.1=pyhd8ed1ab_0
  - isoduration=20.11.0=pyhd8ed1ab_0
  - iterative-telemetry=0.0.8=pyhd8ed1ab_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jaraco.classes=3.3.0=pyhd8ed1ab_0
  - jedi=0.19.0=pyhd8ed1ab_0
  - jeepney=0.8.0=pyhd8ed1ab_0
  - jinja2=3.1.2=pyhd8ed1ab_1
  - joblib=1.3.2=pyhd8ed1ab_0
  - json5=0.9.14=pyhd8ed1ab_0
  - jsonpointer=2.4=py310hff52083_3
  - jsonschema=4.19.1=pyhd8ed1ab_0
  - jsonschema-specifications=2023.7.1=pyhd8ed1ab_0
  - jsonschema-with-format-nongpl=4.19.1=pyhd8ed1ab_0
  - jupyter-lsp=2.2.0=pyhd8ed1ab_0
  - jupyter_client=8.3.1=pyhd8ed1ab_0
  - jupyter_core=5.3.1=py310hff52083_0
  - jupyter_events=0.7.0=pyhd8ed1ab_2
  - jupyter_server=2.7.3=pyhd8ed1ab_0
  - jupyter_server_terminals=0.4.4=pyhd8ed1ab_1
  - jupyterlab=4.0.6=pyhd8ed1ab_0
  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
  - jupyterlab_server=2.25.0=pyhd8ed1ab_0
  - jupyterlab_widgets=3.0.9=pyhd8ed1ab_0
  - keyring=23.13.1=py310hff52083_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py310hd41b1e2_1
  - kombu=5.3.2=py310hff52083_1
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=h7f713cb_2
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20230802.1=cxx17_h59595ed_0
  - libarrow=13.0.0=h1935d02_4_cpu
  - libblas=3.9.0=18_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_0
  - libbrotlidec=1.1.0=hd590300_0
  - libbrotlienc=1.1.0=hd590300_0
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=18_linux64_openblas
  - libclang=15.0.7=default_h7634d5b_3
  - libclang13=15.0.7=default_h9986a30_3
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.7.2.10=0
  - libcups=2.3.3=h4637d8d_4
  - libcurand=10.3.3.141=0
  - libcurl=8.3.0=hca28451_0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.2.0=h807b86a_2
  - libgcrypt=1.10.1=h166bdaf_0
  - libgd=2.3.3=he9388d3_8
  - libgfortran-ng=13.2.0=h69a702a_2
  - libgfortran5=13.2.0=ha4646dd_2
  - libgit2=1.7.1=hca3a8ce_0
  - libglib=2.78.0=hebfc3b9_0
  - libgoogle-cloud=2.12.0=h8d7e28b_2
  - libgpg-error=1.47=h71f35ed_0
  - libgrpc=1.57.0=ha4d0f93_1
  - libhwloc=2.9.3=default_h554bfaf_1009
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.5.1=hd590300_1
  - liblapack=3.9.0=18_linux64_openblas
  - libllvm14=14.0.6=hcd5def8_4
  - libllvm15=15.0.7=h5cf9203_3
  - libmagma=2.7.1=h09159a4_4
  - libmagma_sparse=2.7.1=hc72dce7_4
  - libnghttp2=1.52.0=h61bc06f_0
  - libnpp=11.7.4.75=0
  - libnsl=2.0.0=h7f98852_0
  - libnuma=2.0.16=h0b41bf4_1
  - libnvjpeg=11.8.0.2=0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.24=pthreads_h413a1c8_0
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.39=h753d276_0
  - libpq=15.4=hfc447b1_1
  - libprotobuf=4.23.4=hf27288f_6
  - librsvg=2.56.3=h98fae49_0
  - libsndfile=1.2.2=hbc2eb40_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.43.0=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libsystemd0=254=h3516f8a_0
  - libthrift=0.19.0=h8fd135c_0
  - libtiff=4.6.0=h29866fb_1
  - libtool=2.4.7=h27087fc_0
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.46.0=hd590300_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.3.2=hdffd6e0_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxkbcommon=1.5.0=h5d7e998_3
  - libxml2=2.11.5=h232c23b_1
  - libzlib=1.2.13=hd590300_5
  - lightning=2.0.9=pyhd8ed1ab_0
  - lightning-cloud=0.5.38=pyhd8ed1ab_0
  - lightning-utilities=0.9.0=pyhd8ed1ab_0
  - llvm-openmp=16.0.6=h4dfa4b3_0
  - llvmlite=0.40.1=py310h1b8f574_0
  - lockfile=0.12.2=py_1
  - lz4-c=1.9.4=hcb278e6_0
  - magma=2.7.1=ha770c72_4
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py310h2372a71_1
  - matplotlib=3.8.0=py310hff52083_1
  - matplotlib-base=3.8.0=py310h62c0568_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - mistune=3.0.1=pyhd8ed1ab_0
  - mkl=2022.2.1=h84fe81f_16997
  - more-itertools=10.1.0=pyhd8ed1ab_0
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.0=hb012696_0
  - mpg123=1.31.3=hcb278e6_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - msgpack-python=1.0.6=py310hd41b1e2_0
  - multidict=6.0.4=py310h1fa729e_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - mysql-common=8.0.33=hf1915f5_4
  - mysql-libs=8.0.33=hca2cd23_4
  - nanotime=0.5.2=py_0
  - nb_conda_kernels=2.3.1=py310hff52083_2
  - nbclient=0.8.0=pyhd8ed1ab_0
  - nbconvert-core=7.8.0=pyhd8ed1ab_0
  - nbdev=2.3.12=py_0
  - nbformat=5.9.2=pyhd8ed1ab_0
  - nccl=2.18.5.1=h0800d71_1
  - ncurses=6.4=hcb278e6_0
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - networkx=3.1=pyhd8ed1ab_0
  - nodeenv=1.8.0=pyhd8ed1ab_0
  - notebook=7.0.4=pyhd8ed1ab_0
  - notebook-shim=0.2.3=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.92=h1d7d5a4_0
  - numba=0.57.1=py310h0f6aa51_0
  - numpy=1.24.4=py310ha4c1d20_0
  - omegaconf=2.3.0=pyhd8ed1ab_0
  - openjpeg=2.5.0=h488ebb8_3
  - openssl=3.1.3=hd590300_0
  - opentsne=1.0.0=py310hfb6f7a9_0
  - orc=1.9.0=h52d3b3c_2
  - ordered-set=4.1.0=pyhd8ed1ab_0
  - orjson=3.9.6=py310h1e2579a_0
  - overrides=7.4.0=pyhd8ed1ab_0
  - packaging=23.1=pyhd8ed1ab_0
  - pandas=2.1.1=py310hcc13569_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - pango=1.50.14=ha41ecd1_2
  - parso=0.8.3=pyhd8ed1ab_0
  - pathlib2=2.3.7.post1=py310hff52083_3
  - pathspec=0.11.2=pyhd8ed1ab_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pillow=10.0.1=py310h29da1c1_1
  - pip=23.2.1=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - pkginfo=1.9.6=pyhd8ed1ab_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - platformdirs=3.10.0=pyhd8ed1ab_0
  - ply=3.11=py_1
  - poetry=1.5.1=linux_pyhd8ed1ab_0
  - poetry-core=1.6.1=pyhd8ed1ab_0
  - poetry-plugin-export=1.5.0=pyhd8ed1ab_0
  - pre-commit=3.4.0=pyha770c72_1
  - prometheus_client=0.17.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.39=pyha770c72_0
  - prompt_toolkit=3.0.39=hd8ed1ab_0
  - psutil=5.9.5=py310h2372a71_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio-client=16.1=hb77b528_5
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyarrow=13.0.0=py310hf9e7431_4_cpu
  - pycodestyle=2.11.0=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pydantic=2.1.1=pyhd8ed1ab_0
  - pydantic-core=2.4.0=py310hcb5633a_0
  - pydot=1.4.2=py310hff52083_4
  - pygit2=1.13.1=py310h2372a71_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pygtrie=2.5.0=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_0
  - pyopenssl=23.2.0=pyhd8ed1ab_1
  - pyparsing=3.1.1=pyhd8ed1ab_0
  - pyproject_hooks=1.0.0=pyhd8ed1ab_0
  - pyqt=5.15.9=py310h04931ad_5
  - pyqt5-sip=12.12.2=py310hc6cd4ac_5
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.11=he550d4f_0_cpython
  - python-build=0.10.0=pyhd8ed1ab_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-editor=1.0.4=py_0
  - python-fastjsonschema=2.18.0=pyhd8ed1ab_0
  - python-gssapi=1.8.2=py310h98feede_3
  - python-installer=0.7.0=pyhd8ed1ab_0
  - python-json-logger=2.0.7=pyhd8ed1ab_0
  - python-multipart=0.0.6=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytorch=2.0.0=cuda112py310he0931da_302
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-lightning=2.0.9=pyhd8ed1ab_0
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0.1=py310h2372a71_1
  - pyzmq=25.1.1=py310h5bbb5d0_1
  - qt-main=5.15.8=hc47bfe8_16
  - rapidfuzz=2.15.1=py310heca2aa9_0
  - rdma-core=28.9=h59595ed_1
  - re2=2023.03.02=h8c504da_0
  - readchar=4.0.5=pyhd8ed1ab_0
  - readline=8.2=h8228510_1
  - referencing=0.30.2=pyhd8ed1ab_0
  - requests=2.31.0=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_0
  - rfc3339-validator=0.1.4=pyhd8ed1ab_0
  - rfc3986-validator=0.1.1=pyh9f0ad1d_0
  - rich=13.5.3=pyhd8ed1ab_0
  - rpds-py=0.10.3=py310hcb5633a_0
  - ruamel.yaml=0.17.32=py310h2372a71_0
  - ruamel.yaml.clib=0.2.7=py310h1fa729e_1
  - s2n=1.3.51=h06160fa_0
  - scikit-learn=1.3.1=py310h1fdf081_0
  - scipy=1.11.2=py310hb13e2d6_1
  - scmrepo=1.3.1=pyhd8ed1ab_1
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - secretstorage=3.3.3=py310hff52083_2
  - send2trash=1.8.2=pyh41d4057_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - shellingham=1.5.3=pyhd8ed1ab_0
  - shortuuid=1.0.11=pyhd8ed1ab_0
  - shtab=1.6.4=pyhd8ed1ab_1
  - sip=6.7.11=py310hc6cd4ac_1
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h9b69904_2
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.10=h9fff704_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqltrie=0.7.0=pyhd8ed1ab_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - starlette=0.27.0=pyhd8ed1ab_0
  - starsessions=1.3.0=pyhd8ed1ab_0
  - statsmodels=0.14.0=py310h278f3c1_1
  - sympy=1.12=pypyh9d50eac_103
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.10.0=h00ab1b0_1
  - terminado=0.17.1=pyh41d4057_0
  - threadpoolctl=3.2.0=pyha21a80b_0
  - tinycss2=1.2.1=pyhd8ed1ab_0
  - tk=8.6.13=h2797004_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tomlkit=0.12.1=pyha770c72_0
  - torchmetrics=1.1.2=pyhd8ed1ab_0
  - torchvision=0.15.2=cuda112py310h0801bf5_1
  - tornado=6.3.3=py310h2372a71_1
  - tqdm=4.66.1=pyhd8ed1ab_0
  - traitlets=5.10.0=pyhd8ed1ab_0
  - trove-classifiers=2023.9.19=pyhd8ed1ab_0
  - typing=3.10.0.0=pyhd8ed1ab_0
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - typing_utils=0.1.0=pyhd8ed1ab_0
  - tzdata=2023c=h71feb2d_0
  - ucx=1.14.1=h64cca9d_5
  - ukkonen=1.0.1=py310hd41b1e2_4
  - unicodedata2=15.0.0=py310h2372a71_1
  - uri-template=1.3.0=pyhd8ed1ab_0
  - urllib3=1.26.15=pyhd8ed1ab_0
  - uvicorn=0.23.2=py310hff52083_1
  - vine=5.0.0=pyhd8ed1ab_1
  - virtualenv=20.24.4=pyhd8ed1ab_0
  - voluptuous=0.13.1=pyhd8ed1ab_0
  - watchdog=3.0.0=py310hff52083_1
  - watermark=2.4.3=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - webcolors=1.13=pyhd8ed1ab_0
  - webencodings=0.5.1=pyhd8ed1ab_2
  - websocket-client=1.6.3=pyhd8ed1ab_0
  - websockets=11.0.3=py310h2372a71_1
  - wheel=0.41.2=pyhd8ed1ab_0
  - widgetsnbextension=4.0.9=pyhd8ed1ab_0
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.39=hd590300_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.6=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.2=py310h2372a71_0
  - zc.lockfile=3.0.post1=pyhd8ed1ab_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
variables:
  CUBLAS_WORKSPACE_CONFIG: :4096:8
  CUDA_LAUNCH_BLOCKING: 1
  PRE_COMMIT_USE_MAMBA: 1
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Traceback (most recent call last):
  File "<env>/bin/jupyter-notebook", line 10, in <module>
    sys.exit(main())
  File "<env>/lib/python3.10/site-packages/jupyter_server/extension/application.py", line 607, in launch_instance
    serverapp = cls.initialize_server(argv=args)
  File "<env>/lib/python3.10/site-packages/jupyter_server/extension/application.py", line 577, in initialize_server
    serverapp.initialize(
  File "<env>/lib/python3.10/site-packages/traitlets/config/application.py", line 113, in inner
    return method(app, *args, **kwargs)
  File "<env>/lib/python3.10/site-packages/jupyter_server/serverapp.py", line 2556, in initialize
    super().initialize(argv=argv)
  File "<env>/lib/python3.10/site-packages/traitlets/config/application.py", line 113, in inner
    return method(app, *args, **kwargs)
  File "<env>/lib/python3.10/site-packages/jupyter_core/application.py", line 256, in initialize
    self.parse_command_line(argv)
  File "<env>/lib/python3.10/site-packages/jupyter_server/serverapp.py", line 1856, in parse_command_line
    super().parse_command_line(argv)
  File "<env>/lib/python3.10/site-packages/traitlets/config/application.py", line 113, in inner
    return method(app, *args, **kwargs)
  File "<env>/lib/python3.10/site-packages/traitlets/config/application.py", line 883, in parse_command_line
    self.cli_config = deepcopy(loader.load_config())
  File "<env>/lib/python3.10/site-packages/traitlets/config/loader.py", line 882, in load_config
    self._argcomplete(self.classes, self.subcommands)
  File "<env>/lib/python3.10/site-packages/traitlets/config/loader.py", line 1126, in _argcomplete
    finder(self.parser, **getattr(self, "_argcomplete_kwargs", {}))
TypeError: 'ExtendedCompletionFinder' object is not callable

</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
na
</pre>
</details>

**Comment by thisiswhereitype** [comment]
This was caused by some inconsistent state in the conda environment's site-packages.
