### ISSUE TITLE
Test failure on OpenBSD (terminado)

### ISSUE THREAD

**Issue by vext01** [jupyter/notebook#716]
```
ERROR: Failure: ImportError (No module named terminado)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/local/lib/python2.7/site-packages/notebook/terminal/__init__.py", line 3, in <module>
    import terminado
ImportError: No module named terminado
```

As I understand it (from reading `setup.py`) terminado is optional. This should be a skipped test if the module is absent?

(I tried to figure the fix myself, but failed)

**Comment by vext01** [comment]
This is on 4.0.6.

**Comment by Carreau** [comment]
That's just nose walking through the module hierarchy to discover tests. 
When it try to import `notebook.terminal` it fails (cause terminado not installed). There is nothing we can do for that, except actually telling nose on the command line `--exclude=terminal`.

**Comment by minrk** [comment]
According to setup.py, terminado is requires on every platform other than Windows.

**Comment by vext01** [comment]
Ah i see. My mistake.
