### ISSUE TITLE
Big conflict of library versions that can't move user forward after update

### ISSUE THREAD

**Issue by ManPython** [jupyter/notebook#7177]
## Description

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
voila 0.4.0 requires jupyter-client<=7.4.1,>=6.1.3, but you have jupyter-client 8.6.0 which is incompatible.
voila 0.4.0 requires jupyter-server<2.0.0,>=1.18, but you have jupyter-server 2.12.0 which is incompatible.
jupyterlab-code-formatter 1.5.3 requires jupyterlab~=3.0, but you have jupyterlab 4.0.9 which is incompatible.

```

```
Successfully built tornado
Installing collected packages: tornado
  Attempting uninstall: tornado
    Found existing installation: tornado 6.2
    Uninstalling tornado-6.2:
      Successfully uninstalled tornado-6.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyterlab-code-formatter 1.5.3 requires jupyterlab~=3.0, but you have jupyterlab 4.0.9 which is incompatible.
Successfully installed tornado-6.4

```

## Reproduce

1.  After OS update on hosting sys requires rpds_py-0.13.2-cp311-cp311-freebsd_13_2_RELEASE_amd64 and was error ImportError: Shared object "libffi.so.7" not found, required by "_cffi_backend.cpython-311.so" 
2.  I decided update virtualenv and update 
pip install --upgrade cython
pip install --upgrade jupyter
pip install --upgrade notebook
pip install --upgrade tornado

```
Installing collected packages: voila
  Attempting uninstall: voila
    Found existing installation: voila 0.4.0
    Uninstalling voila-0.4.0:
      Successfully uninstalled voila-0.4.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
voila-gridstack 0.3.1 requires voila<0.5.0,>=0.2.0, but you have voila 0.5.5 which is incompatible.
Successfully installed voila-0.5.5
```

[log_jupyter.txt](https://github.com/jupyter/notebook/files/13590277/log_jupyter.txt)

## Expected behavior

I'm looking some option to update jupyter or other to this version where other **instaled libs** will be compatible or updated to optmial versions, eg. force re-instal to older main app and related libs. Soo I need some "indication" to right version betwen all version.
Soo.. when update.. then propbably pip should alert and inform possible conflicts and not install new version if older are incompatible in some iteration of update and ask that I'm sure that something can't work or list optimal version to update to minimize impact for some old libs, eg. list of sugested version to update where 75% libs are compatible as tools, etc. or 50%, 25% and of course.. 95% is most of desirable.
Right now I stuck..  fighting with pip to find some optimal version.. but how.. 

## Context

- Operating System and version: LNX freebsd_13_2
- Browser and version: 

- Jupyter Notebook version: 
```
- jupyter --version
Selected Jupyter core packages...
IPython          : 8.8.0
ipykernel        : 6.20.1
ipywidgets       : 8.0.4
jupyter_client   : 8.6.0
jupyter_core     : 5.1.3
jupyter_server   : 2.12.0
jupyterlab       : 4.0.9
nbclient         : 0.7.2
nbconvert        : 7.2.7
nbformat         : 5.7.1
notebook         : 7.0.6
qtconsole        : 5.4.0
traitlets        : 5.8.1
```

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter notebook` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

```[tasklist]
### Tasks
```

**Comment by ManPython** [comment]
In final case I reach some old compatibility around libs manualy... I think as:
```
IPython          : 8.8.0
ipykernel        : 6.20.1
ipywidgets       : 8.0.4
jupyter_client   : 7.4.1
jupyter_core     : 5.1.3
jupyter_server   : 1.23.5
jupyterlab       : 3.5.2
nbclient         : 0.7.2
nbconvert        : 7.2.7
nbformat         : 5.7.1
notebook         : 6.5.2
qtconsole        : 5.4.0
traitlets        : 5.8.1
```
but errors
```
[I 02:02:04.721 NotebookApp] Loading IPython parallel extension
[I 02:02:04.750 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.6.1
[W 2023-12-07 02:02:05.354 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-12-07 02:02:05.354 LabApp] 'allow_origin' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-12-07 02:02:05.354 LabApp] 'allow_remote_access' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-12-07 02:02:05.354 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-12-07 02:02:05.354 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-12-07 02:02:05.354 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2023-12-07 02:02:05.360 LabApp] JupyterLab extension loaded from /usr/home/ManPython/.virtualenvs/venvpython311/lib/python3.11/site-packages/jupyterlab
[I 2023-12-07 02:02:05.360 LabApp] JupyterLab application directory is /usr/home/ManPython/.virtualenvs/venvpython311/share/jupyter/lab
[W 02:02:05.646 NotebookApp] Error loading server extension voila_gridstack.server_extension
    Traceback (most recent call last):
      File "/usr/home/ManPython/.virtualenvs/venvpython311/lib/python3.11/site-packages/notebook/notebookapp.py", line 2026, in init_server_extensions
        mod = importlib.import_module(modulename)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/usr/home/ManPython/.virtualenvs/venvpython311/lib/python3.11/site-packages/voila_gridstack/__init__.py", line 18, in <module>
        with open(osp.join(HERE, 'labextension', 'package.json')) as fid:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: '/usr/home/ManPython/.virtualenvs/venvpython311/lib/python3.11/site-packages/voila_gridstack/labextension/package.json'
Traceback (most recent call last):
  File "/usr/home/ManPython/.virtualenvs/venvp311/bin/jupyter-notebook", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/jupyter_core/application.py", line 277, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/traitlets/config/application.py", line 1041, in launch_instance
    app.start()
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/notebook/notebookapp.py", line 2320, in start
    success = self._bind_http_server()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/notebook/notebookapp.py", line 1795, in _bind_http_server
    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/notebook/notebookapp.py", line 1821, in _bind_http_server_tcp
    self.http_server.listen(port, self.ip)
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/tornado/tcpserver.py", line 183, in listen
    sockets = bind_sockets(
              ^^^^^^^^^^^^^
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/tornado/netutil.py", line 105, in bind_sockets
    socket.getaddrinfo(address, port, family, socket.SOCK_STREAM, 0, flags),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] Name does not resolve
(venvp311) [ManPython@s24]:<~>$ jupyter notebook --ip=127.0.0.1:8890
[I 02:03:27.836 NotebookApp] Loading IPython parallel extension
[I 02:03:27.866 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.6.1
[W 2023-12-07 02:03:28.397 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-12-07 02:03:28.397 LabApp] 'allow_origin' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-12-07 02:03:28.398 LabApp] 'allow_remote_access' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-12-07 02:03:28.398 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-12-07 02:03:28.398 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-12-07 02:03:28.398 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2023-12-07 02:03:28.404 LabApp] JupyterLab extension loaded from /usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/jupyterlab
[I 2023-12-07 02:03:28.404 LabApp] JupyterLab application directory is /usr/home/ManPython/.virtualenvs/venvp311/share/jupyter/lab
[W 02:03:28.682 NotebookApp] Error loading server extension voila_gridstack.server_extension
    Traceback (most recent call last):
      File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/notebook/notebookapp.py", line 2026, in init_server_extensions
        mod = importlib.import_module(modulename)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/voila_gridstack/__init__.py", line 18, in <module>
        with open(osp.join(HERE, 'labextension', 'package.json')) as fid:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: '/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/voila_gridstack/labextension/package.json'
Traceback (most recent call last):
  File "/usr/home/ManPython/.virtualenvs/venvp311/bin/jupyter-notebook", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/jupyter_core/application.py", line 277, in launch_instance
    return super().launch_instance(argv=argv, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/traitlets/config/application.py", line 1041, in launch_instance
    app.start()
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/notebook/notebookapp.py", line 2320, in start
    success = self._bind_http_server()
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/notebook/notebookapp.py", line 1795, in _bind_http_server
    return self._bind_http_server_unix() if self.sock else self._bind_http_server_tcp()
                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/notebook/notebookapp.py", line 1821, in _bind_http_server_tcp
    self.http_server.listen(port, self.ip)
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/tornado/tcpserver.py", line 183, in listen
    sockets = bind_sockets(
              ^^^^^^^^^^^^^
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/tornado/netutil.py", line 105, in bind_sockets
    socket.getaddrinfo(address, port, family, socket.SOCK_STREAM, 0, flags),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno 8] Name does not resolve
```

**Comment by ManPython** [comment]
For next posts I uninstalled this due problems, but this what I meet.. dependency hell.

**Comment by ManPython** [comment]
Require tornado>=6.1.0 ([#9453](https://github.com/jupyterlab/jupyterlab/pull/9453)) - wrong info maybe
```
pip install tornado==6.1.0
Collecting tornado==6.1.0
  Downloading tornado-6.1.tar.gz (497 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 497.4/497.4 kB 2.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: tornado
  Building wheel for tornado (setup.py) ... done
  Created wheel for tornado: filename=tornado-6.1-cp311-cp311-freebsd_13_2_release_amd64.whl size=418074 sha256=542e45c71c27906e1f036c12c56939b6012f9901bfc8671d21090a19080f2610
  Stored in directory: /usr/home/eaforex/.cache/pip/wheels/f2/59/06/a9c85c7b17ec0fc9b1e2ae0c59e3d39255d5c0a38492e33fea
Successfully built tornado
Installing collected packages: tornado
  Attempting uninstall: tornado
    Found existing installation: tornado 6.4
    Uninstalling tornado-6.4:
      Successfully uninstalled tornado-6.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
jupyter-client 7.4.1 requires tornado>=6.2, but you have tornado 6.1 which is incompatible.
Successfully installed tornado-6.1
(venvpython311) [eaforex@s24]:<~>$ pip install tornado==6.2
Collecting tornado==6.2
  Using cached tornado-6.2-cp37-abi3-freebsd_13_2_release_amd64.whl
Installing collected packages: tornado
  Attempting uninstall: tornado
    Found existing installation: tornado 6.1
    Uninstalling tornado-6.1:
      Successfully uninstalled tornado-6.1
Successfully installed tornado-6.2
```
Then again 
**ImportError: Shared object "libffi.so.7" not found, required by "_cffi_backend.cpython-311.so"**
```
[I 20:11:20.941 NotebookApp] Loading IPython parallel extension
[I 20:11:20.971 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.6.1
[W 2023-12-11 20:11:21.592 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-12-11 20:11:21.592 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-12-11 20:11:21.593 LabApp] 'allow_origin' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-12-11 20:11:21.593 LabApp] 'allow_remote_access' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-12-11 20:11:21.593 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-12-11 20:11:21.593 LabApp] 'notebook_dir' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-12-11 20:11:21.593 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2023-12-11 20:11:21.600 LabApp] JupyterLab extension loaded from /usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/jupyterlab
[I 2023-12-11 20:11:21.600 LabApp] JupyterLab application directory is /usr/home/ManPython/.virtualenvs/venvp311/share/jupyter/lab
[I 20:11:21.879 NotebookApp] Serving notebooks from local directory: /usr/home/ManPython/domains/jupyter.ManPython.pl/public_html/jupyter-notebook
[I 20:11:21.879 NotebookApp] Jupyter Notebook 6.5.2 is running at:
[I 20:11:21.879 NotebookApp] http://127.0.0.1:9999/
[I 20:11:21.879 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
                                                                                                                                                                                                                    Opening Jupyter Notebook
   Refresh: [I 20:11:27.088 NotebookApp] 302 GET / (127.0.0.1) 1.160000ms
[I 20:11:27.145 NotebookApp] 302 GET /tree? (127.0.0.1) 1.280000ms
[E 20:11:29.314 NotebookApp] Uncaught exception POST /login?next=%2Ftree%3F (127.0.0.1)o Jupyter.
    HTTPServerRequest(protocol='http', host='manpython.com', method='POST', uri='/login?next=%2Ftree%3F', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/notebook/auth/login.py", line 87, in post
        if self.passwd_check(self.hashed_password, typed_password) and not new_password:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/notebook/auth/login.py", line 78, in passwd_check
        return passwd_check(a, b)
               ^^^^^^^^^^^^^^^^^^
      File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/notebook/auth/security.py", line 108, in passwd_check
        import argon2
      File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/argon2/__init__.py", line 7, in <module>
        from . import exceptions, low_level, profiles
      File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/argon2/low_level.py", line 15, in <module>
        from _argon2_cffi_bindings import ffi, lib
      File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/_argon2_cffi_bindings/__init__.py", line 3, in <module>
        from ._ffi import ffi, lib
    ImportError: Shared object "libffi.so.7" not found, required by "_cffi_backend.cpython-311.so"
[E 20:11:29.323 NotebookApp] {
      "Host": "manpython.com",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
      "Referer": "http://manpython.com/login?next=%2Ftree%3F",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0"
    }
[E 20:11:29.323 NotebookApp] 500 POST /login?next=%2Ftree%3F (127.0.0.1) 11.780000ms referer=http://manpython.com/login?next=%2Ftree%3F
```

**Comment by ManPython** [comment]
I deleted everything.. and installed lower version, then jupyter working but with some difficulties, eg.
1. Notebooks and tree working from last stored password
2. Nothing working in private mode browser where providing this same pass, as `500 : Internal Server Error`
- then "libffi.so.7" again.. strange.. coz exist "libffi.so.8" and working.. 
4. I missing the old style nbextensions manager

**Comment by ManPython** [comment]
I find problem where something still want  "libffi.so.7" again.. strange.. coz exist "libffi.so.8" and working.. 
Cached or static indication?

```
Uncaught exception POST /login?next=%2Ftree%3F (127.0.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1', method='POST', uri='/login?next=%2Ftree%3F', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/home/ManPython/.virtualenvs/venvpython311/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
        result = method(*self.path_args, **self.path_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/jupyter_server/auth/login.py", line 86, in post
        user = self.current_user = self.identity_provider.process_login_form(self)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/jupyter_server/auth/identity.py", line 645, in process_login_form
        if self.passwd_check(typed_password) and not new_password:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/jupyter_server/auth/identity.py", line 631, in passwd_check
        return passwd_check(self.hashed_password, password)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/jupyter_server/auth/security.py", line 108, in passwd_check
        import argon2
      File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/argon2/__init__.py", line 7, in <module>
        from . import exceptions, low_level, profiles
      File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/argon2/low_level.py", line 17, in <module>
        from _argon2_cffi_bindings import ffi, lib
      File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/_argon2_cffi_bindings/__init__.py", line 3, in <module>
        from ._ffi import ffi, lib
    ImportError: Shared object "libffi.so.7" not found, required by "_cffi_backend.cpython-311.so"
[E 2023-12-13 20:38:51.114 ServerApp] {
      "Host": "127.0.0.1",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
      "Referer": "http://127.0.0.1/login?next=%2Ftree%3F",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0"
    }
[E 2023-12-13 20:38:51.114 ServerApp] 500 POST /login?next=%2Ftree%3F (@127.0.0.1) 6.21ms referer=http://127.0.0.1/login?next=%2Ftree%3F

```

**Comment by ManPython** [comment]
Delete pyc etc. `__pycache__` not helping it's something around:

```
jupyter notebook password
Enter password:
Verify password:
Traceback (most recent call last):
  File "/usr/home/ManPython/.virtualenvs/venvp311/bin/jupyter-notebook", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/jupyter_server/extension/application.py", line 622, in launch_instance
    serverapp.start()
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/jupyter_server/serverapp.py", line 2967, in start
    self.start_app()
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/jupyter_server/serverapp.py", line 2836, in start_app
    super().start()
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/jupyter_core/application.py", line 269, in start
    self.subapp.start()
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/jupyter_server/serverapp.py", line 507, in start
    set_password(config_file=self.config_file)
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/jupyter_server/auth/security.py", line 172, in set_password
    hashed_password = passwd(password)
                      ^^^^^^^^^^^^^^^^
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/jupyter_server/auth/security.py", line 61, in passwd
    import argon2
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/argon2/__init__.py", line 7, in <module>
    from . import exceptions, low_level, profiles
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/argon2/low_level.py", line 17, in <module>
    from _argon2_cffi_bindings import ffi, lib
  File "/usr/home/ManPython/.virtualenvs/venvp311/lib/python3.11/site-packages/_argon2_cffi_bindings/__init__.py", line 3, in <module>
    from ._ffi import ffi, lib
ImportError: Shared object "libffi.so.7" not found, required by "_cffi_backend.cpython-311.so"
```

**Comment by ManPython** [comment]
You need refresh information here:
https://jupyterlab.readthedocs.io/en/stable/getting_started/changelog.html#v4-0
As other new version.. coz is not updated.
The problem was solved due relations around _cffi and related argon2
Issue can be closed, but need review docs and indicating the versions problems around whole libs.
What a hell.. around..
