### ISSUE TITLE
Cannot start notebook on Windows 7: WinError 10106

### ISSUE THREAD

**Issue by ricklupton** [jupyter/notebook#724]
Trying to get the notebook working on a colleague's computer, we installed Anaconda (Python 3.5) on Windows 7. IPython itself works but the notebook will not start. Unfortunately I don't have the full stack trace available right now, but in effect it was:

```
something in traitlets: no attribute 'ip'

During processing of this exception:

OSError: [WinError 10106] The requested service provider could not be loaded or initialized
```

Prompted by the missing 'ip' attribute, I tried various combinations of

```
jupyter notebook --ip=127.0.0.1
jupyter notebook --ip=machinel.ip.address
jupyter notebook --port=9000
```

and also tried to temporarily disable Windows Firewall and the virus scanner, with no success.

Sorry for the lack of detail, perhaps if you can suggest what more specific information would help then we can try again on his machine and report back.

Has anyone experienced this problem before?

**Comment by minrk** [comment]
Can you provide the complete traceback?

**Comment by ricklupton** [comment]
Here it is -- sorry for not giving it to start with:

```
>jupyter notebook
Traceback (most recent call last):
  File "C:\Users\Iain\Anaconda3\lib\site-packages\traitlets\traitlets.py",
 line 432, in __get__
    value = obj._trait_values[self.name]
KeyError: 'ip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Iain\Anaconda3\Scripts\jupyter-notebook-script.py", line
5, in <module>
    sys.exit(main())
  File "C:\Users\Iain\Anaconda3\lib\site-packages\jupyter_core\application
.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "C:\Users\Iain\Anaconda3\lib\site-packages\traitlets\config\applica
tion.py", line 591, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-115>", line 2, in initialize
  File "C:\Users\Iain\Anaconda3\lib\site-packages\traitlets\config\applica
tion.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\Iain\Anaconda3\lib\site-packages\notebook\notebookapp.py"
, line 1007, in initialize
    self.init_webapp()
  File "C:\Users\Iain\Anaconda3\lib\site-packages\notebook\notebookapp.py"
, line 866, in init_webapp
    self.login_handler_class.validate_security(self, ssl_options=ssl_options)
  File "C:\Users\Iain\Anaconda3\lib\site-packages\notebook\auth\login.py",
 line 88, in validate_security
    if not app.ip:
  File "C:\Users\Iain\Anaconda3\lib\site-packages\traitlets\traitlets.py",
 line 439, in __get__
    value = self._validate(obj, dynamic_default())
  File "C:\Users\Iain\Anaconda3\lib\site-packages\notebook\notebookapp.py"
, line 445, in _ip_default
    s = socket.socket()
  File "C:\Users\Iain\Anaconda3\lib\socket.py", line 134, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [WinError 10106] The requested service provider could not be loaded or
initialized
```

**Comment by minrk** [comment]
That seems to be the root issue - the process can't even create Socket objects. That seems to be a severe permission or configuration problem that's going to prevent the server from running.

**Comment by makmanalp** [comment]
Hit this also

**Comment by takluyver** [comment]
If you're seeing the same traceback, it looks like an error with your system that we have no way of avoiding. Searching for the error message online, I find some suggestions that you try running a command like:

```
netsh winsock reset catalog
```

([from here](http://texhex.blogspot.com/2009/01/dhcp-error-service-provider-could-not.html))

I haven't tried this, and I have no idea what it's doing, so I don't know whether it will work, or create further problems.
