### ISSUE TITLE
Something went wrong (v3 beta)

### ISSUE THREAD

**Issue by Gahwa-Gahwa** [jupyter/notebook#7254]
Hello the app shows an error at startup and does not open the notes.

I get a something went wrong message with the following error:
`TRPCClientError: net::ERR_INTERNET_DISCONNECTED
TRPCClientError: net::ERR_INTERNET_DISCONNECTED
    at Lo.from (https://app.notesnook.com/assets/index-1660b90b.js:821:11909)
    at Object.next (https://app.notesnook.com/assets/index-1660b90b.js:821:20246)
    at sL.xy (https://app.notesnook.com/assets/index-1660b90b.js:821:19870)
    at https://app.notesnook.com/assets/index-1660b90b.js:821:19391
    at EventEmitter.<anonymous> (C:\Users\danga\AppData\Local\Programs\@notesnookdesktop\resources\app\build\preload.js:1:9104)
    at EventEmitter.emit (node:events:517:28)
    at Object.onMessage (node:electron/js2c/renderer_init:2:8536)`

This is for version 3 beta.

**Comment by JasonWeill** [comment]
@Gahwa-Gahwa Thanks for opening this issue! What application are you using? Your issue mentions notesnook.com, whose website points to this GitHub repo: https://github.com/streetwriters/notesnook
