### ISSUE TITLE
JupyterLab not running 

### ISSUE THREAD

**Issue by rasnegus** [jupyter/notebook#7351]
Traceback (most recent call last):
File "C:\Users\wlady\Anaconda3\lib\site-packages\jupyterlab_server\server.py", line 14, in 
from notebook.base.handlers import (
File "C:\Users\wlady\Anaconda3\lib\site-packages\notebook\base\handlers.py", line 21, in 
from jinja2 import TemplateNotFound
File "C:\Users\wlady\Anaconda3\lib\site-packages\jinja2\__init__.py", line 12, in 
from .environment import Environment
File "C:\Users\wlady\Anaconda3\lib\site-packages\jinja2\environment.py", line 25, in 
from .defaults import BLOCK_END_STRING
File "C:\Users\wlady\Anaconda3\lib\site-packages\jinja2\defaults.py", line 3, in 
from .filters import FILTERS as DEFAULT_FILTERS # noqa: F401
File "C:\Users\wlady\Anaconda3\lib\site-packages\jinja2\filters.py", line 13, in 
from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (C:\Users\wlady\Anaconda3\lib\site-packages\markupsafe\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\wlady\Anaconda3\Scripts\jupyter-lab-script.py", line 5, in 
from jupyterlab.labapp import main
File "C:\Users\wlady\Anaconda3\lib\site-packages\jupyterlab\labapp.py", line 14, in 
from jupyterlab_server import slugify, WORKSPACE_EXTENSION
File "C:\Users\wlady\Anaconda3\lib\site-packages\jupyterlab_server\__init__.py", line 4, in 
from .app import LabServerApp
File "C:\Users\wlady\Anaconda3\lib\site-packages\jupyterlab_server\app.py", line 9, in 
from .server import ServerApp
File "C:\Users\wlady\Anaconda3\lib\site-packages\jupyterlab_server\server.py", line 26, in 
from jupyter_server.base.handlers import ( # noqa
ModuleNotFoundError: No module named 'jupyter_server'

**Comment by JasonWeill** [comment]
@rasnegus Thanks for opening this issue! Can you please share how you've installed JupyterLab and Jupyter Notebook? Which versions of these packages, and on which OS and version, are you trying to run?
