### ISSUE TITLE
using error

### ISSUE THREAD

**Issue by willamsc** [jupyter/notebook#7402]
when i use the jupyter notebook . i bit the buttern of launch the production return me.
Traceback (most recent call last):
File "D:\70\anaconda\envs\summer holiday ml\lib\site-packages\notebook\traittypes.py", line 235, in _resolve_classes
klass = self._resolve_string(klass)
File "D:\70\anaconda\envs\summer holiday ml\lib\site-packages\traitlets\traitlets.py", line 2015, in _resolve_string
return import_item(string)
File "D:\70\anaconda\envs\summer holiday ml\lib\site-packages\traitlets\utils\importstring.py", line 33, in import_item
module = import(package, fromlist=[obj])
ModuleNotFoundError: No module named 'jupyter_server.contents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "D:\70\anaconda\envs\summer holiday ml\Scripts\jupyter-notebook-script.py", line 10, in
sys.exit(main())
File "D:\70\anaconda\envs\summer holiday ml\lib\site-packages\jupyter_core\application.py", line 283, in launch_instance
super().launch_instance(argv=argv, **kwargs)
File "D:\70\anaconda\envs\summer holiday ml\lib\site-packages\traitlets\config\application.py", line 1073, in launch_instance
app = cls.instance(**kwargs)
File "D:\70\anaconda\envs\summer holiday ml\lib\site-packages\traitlets\config\configurable.py", line 583, in instance
inst = cls(*args, **kwargs)
File "D:\70\anaconda\envs\summer holiday ml\lib\site-packages\traitlets\traitlets.py", line 1292, in new
inst.setup_instance(*args, **kwargs)
File "D:\70\anaconda\envs\summer holiday ml\lib\site-packages\traitlets\traitlets.py", line 1335, in setup_instance
super(HasTraits, self).setup_instance(*args, **kwargs)
File "D:\70\anaconda\envs\summer holiday ml\lib\site-packages\traitlets\traitlets.py", line 1311, in setup_instance
init(self)
File "D:\70\anaconda\envs\summer holiday ml\lib\site-packages\notebook\traittypes.py", line 226, in instance_init
self._resolve_classes()
File "D:\70\anaconda\envs\summer holiday ml\lib\site-packages\notebook\traittypes.py", line 238, in _resolve_classes
warn(f"{klass} is not importable. Is it installed?", ImportWarning)
TypeError: warn() missing 1 required keyword-only argument: 'stacklevel'

**Comment by willamsc** [comment]
thank you for your reply.I reslove the problem now.The solution is pip uninstall traitlets
pip install traitlets==5.9.0






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jupyter/notebook"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月26日(星期三) 凌晨0:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jupyter/notebook] using error (Issue #7402)





 
Thank you @willamsc for opening this issue! Are you using the Anaconda prompt? Also could you share the versions you are using for: Jupyter Notebook, Windows and Python?
