### ISSUE TITLE
I can't Launch Jupyter Notebook 

### ISSUE THREAD

**Issue by CVG12** [jupyter/notebook#7426]
It will not let me launch Jupyter Notebook. This is the error it is giving me:
[I 2024-07-15 16:51:28.857 ServerApp] Extension package aext_assistant took 0.1632s to import
[I 2024-07-15 16:51:28.872 ServerApp] ****************** ENVIRONMENT Environment.PRODUCTION ******************
[I 2024-07-15 16:51:28.874 ServerApp] ****************** ENVIRONMENT Environment.PRODUCTION ******************
[W 2024-07-15 16:51:28.902 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[W 2024-07-15 16:51:28.974 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-07-15 16:51:29.630 ServerApp] Extension package panel.io.jupyter_server_extension took 0.6556s to import
[I 2024-07-15 16:51:29.630 ServerApp] aext_assistant | extension was successfully linked.
[I 2024-07-15 16:51:29.630 ServerApp] aext_core | extension was successfully linked.
[I 2024-07-15 16:51:29.630 ServerApp] aext_panels | extension was successfully linked.
[I 2024-07-15 16:51:29.632 ServerApp] aext_share_notebook | extension was successfully linked.
[I 2024-07-15 16:51:29.632 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-07-15 16:51:29.634 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-07-15 16:51:29.637 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-07-15 16:51:29.640 ServerApp] notebook | extension was successfully linked.
[I 2024-07-15 16:51:29.890 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-07-15 16:51:29.890 ServerApp] panel.io.jupyter_server_extension | extension was successfully linked.
[I 2024-07-15 16:51:29.957 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-07-15 16:51:29.957 ServerApp] Registered aext_assistant server extension
[I 2024-07-15 16:51:29.957 ServerApp] aext_assistant | extension was successfully loaded.
[I 2024-07-15 16:51:29.958 ServerApp] Registered aext_core server extension
[I 2024-07-15 16:51:29.958 ServerApp] aext_core | extension was successfully loaded.
[I 2024-07-15 16:51:29.959 ServerApp] Registered aext_panels server extension
[I 2024-07-15 16:51:29.959 ServerApp] aext_panels | extension was successfully loaded.
[I 2024-07-15 16:51:29.959 ServerApp] Registered aext_share_notebook_server server extension
[I 2024-07-15 16:51:29.959 ServerApp] aext_share_notebook | extension was successfully loaded.
[I 2024-07-15 16:51:29.960 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-07-15 16:51:29.960 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-07-15 16:51:29.964 LabApp] JupyterLab extension loaded from C:\Users\cal_v\anaconda3\Lib\site-packages\jupyterlab
[I 2024-07-15 16:51:29.964 LabApp] JupyterLab application directory is C:\Users\cal_v\anaconda3\share\jupyter\lab
[I 2024-07-15 16:51:29.965 LabApp] Extension Manager is 'pypi'.
[I 2024-07-15 16:51:29.966 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-07-15 16:51:29.970 ServerApp] notebook | extension was successfully loaded.
[I 2024-07-15 16:51:29.970 ServerApp] panel.io.jupyter_server_extension | extension was successfully loaded.
[I 2024-07-15 16:51:29.971 ServerApp] Serving notebooks from local directory: C:\Users\cal_v
[I 2024-07-15 16:51:29.971 ServerApp] Jupyter Server 2.14.1 is running at:
[I 2024-07-15 16:51:29.971 ServerApp] http://localhost:8888/tree?token=e6859425dfd1d02b4ab7e608d62527d2ee75fb6f6528fd05
[I 2024-07-15 16:51:29.971 ServerApp] http://127.0.0.1:8888/tree?token=e6859425dfd1d02b4ab7e608d62527d2ee75fb6f6528fd05
[I 2024-07-15 16:51:29.971 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[E 2024-07-15 16:51:29.971 ServerApp] Failed to write server-info to C:\Users\cal_v\AppData\Roaming\jupyter\runtime\jpserver-13596.json: PermissionError(13, 'Permission denied')
Traceback (most recent call last):
File "C:\Users\cal_v\anaconda3\Scripts\jupyter-notebook-script.py", line 10, in 
sys.exit(main())
^^^^^^
File "C:\Users\cal_v\anaconda3\Lib\site-packages\jupyter_server\extension\application.py", line 623, in launch_instance
serverapp.start()
File "C:\Users\cal_v\anaconda3\Lib\site-packages\jupyter_server\serverapp.py", line 3119, in start
self.start_app()
File "C:\Users\cal_v\anaconda3\Lib\site-packages\jupyter_server\serverapp.py", line 3023, in start_app
self.write_browser_open_files()
File "C:\Users\cal_v\anaconda3\Lib\site-packages\jupyter_server\serverapp.py", line 2890, in write_browser_open_files
self.write_browser_open_file()
File "C:\Users\cal_v\anaconda3\Lib\site-packages\jupyter_server\serverapp.py", line 2913, in write_browser_open_file
with open(self.browser_open_file, "w", encoding="utf-8") as f:
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\cal_v\\AppData\\Roaming\\jupyter\\runtime\\jpserver-13596-open.html'

**Comment by CVG12** [comment]
How do I update the runtime directory?

**Comment by CVG12** [comment]
I was not. Because my device is brand new and I have not owned a computer
before, I believe that is why the runtime directories and other components
needed for Jupyter are not properly installed. I decided to just use
different IDEs to run python. Thank you so much for your help

**Comment by JimeFioni** [comment]
So using another IDE have you solved the problem? @CVG12

**Comment by CVG12** [comment]
Yes, I did.

**Comment by Hashmatullah-Asady** [comment]
Hi @CVG12 I have the same issue with the Jupyter notebook, and I solved it by deleting the Jupyter folder from C:\Users\cal_v\AppData\Roaming\jupyter\runtime.

Please try if it works for you!!

**Comment by Aam120** [comment]
hi there, i just wanted to say that im someone whose not from IT and needed jupyter through anaconda for a finance ML course. i spent the last week clean installing windows onto my laptop, thinking i messed up and deleted an important file. thank you so much @RRosio for your help. i tried your steps but they didnt work or they did work once and then the runtime would again default back to the original one. What finally did the job was when i opened the folder manually myself in C:\Users\cal_v\AppData\Roaming\jupyter\runtime, and was asked admin permissions to continue. i clicked yes and it has been working ever since. I cant thank everyone here enough.

**Comment by GeochemicalScientific** [comment]
Aam120  Thank you for posting this.  You have saved me both a headache and heartache

I had the exact same problem and it was solved in 5mins because of this thread
