### ISSUE TITLE
OSError: [WinError 10038]  - jupyter notebook crashing

### ISSUE THREAD

**Issue by leobargigli** [jupyter/notebook#7432]
Hi, 
jupyter notebook 7.0.8 crashes on windows 11 pro with  the following log.
Can you help me please?
Thank you so much!

(base) C:\Users\leona>jupyter notebook
[W 2024-08-01 09:26:17.247 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[W 2024-08-01 09:26:17.523 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2024-08-01 09:26:19.233 ServerApp] Extension package panel.io.jupyter_server_extension took 1.7052s to import
[I 2024-08-01 09:26:19.236 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-08-01 09:26:19.241 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-08-01 09:26:19.251 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-08-01 09:26:19.258 ServerApp] notebook | extension was successfully linked.
[I 2024-08-01 09:26:20.025 ServerApp] notebook_shim | extension was successfully linked.
[I 2024-08-01 09:26:20.025 ServerApp] panel.io.jupyter_server_extension | extension was successfully linked.
[I 2024-08-01 09:26:20.079 ServerApp] notebook_shim | extension was successfully loaded.
[I 2024-08-01 09:26:20.079 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2024-08-01 09:26:20.079 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2024-08-01 09:26:20.092 LabApp] JupyterLab extension loaded from C:\Users\leona\anaconda3\Lib\site-packages\jupyterlab
[I 2024-08-01 09:26:20.092 LabApp] JupyterLab application directory is C:\Users\leona\anaconda3\share\jupyter\lab
[I 2024-08-01 09:26:20.092 LabApp] Extension Manager is 'pypi'.
[I 2024-08-01 09:26:20.092 ServerApp] jupyterlab | extension was successfully loaded.
[I 2024-08-01 09:26:20.092 ServerApp] notebook | extension was successfully loaded.
[I 2024-08-01 09:26:20.107 ServerApp] panel.io.jupyter_server_extension | extension was successfully loaded.
[I 2024-08-01 09:26:20.109 ServerApp] Serving notebooks from local directory: C:\Users\leona
[I 2024-08-01 09:26:20.109 ServerApp] Jupyter Server 2.14.1 is running at:
[I 2024-08-01 09:26:20.109 ServerApp] http://localhost:8888/tree?token=7f454b1e793d0913f8426fb16fcf1998661c2825ed41c983
[I 2024-08-01 09:26:20.109 ServerApp]     http://127.0.0.1:8888/tree?token=7f454b1e793d0913f8426fb16fcf1998661c2825ed41c983
[I 2024-08-01 09:26:20.109 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2024-08-01 09:26:20.145 ServerApp]

    To access the server, open this file in a browser:
        file:///C:/Users/leona/AppData/Roaming/jupyter/runtime/jpserver-12440-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/tree?token=7f454b1e793d0913f8426fb16fcf1998661c2825ed41c983
        http://127.0.0.1:8888/tree?token=7f454b1e793d0913f8426fb16fcf1998661c2825ed41c983
[I 2024-08-01 09:26:20.342 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[E 2024-08-01 09:26:22.402 ServerApp] Error unpacking user from cookie: Expecting value: line 1 column 1 (char 0)
[E 2024-08-01 09:26:22.404 ServerApp] Error unpacking user from cookie: Expecting value: line 1 column 1 (char 0)
0.01s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[W 2024-08-01 09:28:09.773 ServerApp] Notebook Dropbox/Insegnamento/evolutionary_game_theory/PyIntro_part1.ipynb is not trusted
[W 2024-08-01 09:28:12.686 ServerApp] Notebook Dropbox/Insegnamento/evolutionary_game_theory/PyIntro_part1.ipynb is not trusted
[I 2024-08-01 09:28:13.129 ServerApp] Kernel started: 0793fe43-4738-4b85-ba91-9a232c13a1d0
0.00s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
[I 2024-08-01 09:28:15.247 ServerApp] Connecting to kernel 0793fe43-4738-4b85-ba91-9a232c13a1d0.
Traceback (most recent call last):
  File "C:\Users\leona\anaconda3\Scripts\jupyter-notebook-script.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\leona\anaconda3\Lib\site-packages\jupyter_server\extension\application.py", line 623, in launch_instance
    serverapp.start()
  File "C:\Users\leona\anaconda3\Lib\site-packages\jupyter_server\serverapp.py", line 3120, in start
    self.start_ioloop()
  File "C:\Users\leona\anaconda3\Lib\site-packages\jupyter_server\serverapp.py", line 3106, in start_ioloop
    self.io_loop.start()
  File "C:\Users\leona\anaconda3\Lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\leona\anaconda3\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\leona\anaconda3\Lib\asyncio\base_events.py", line 1949, in _run_once
    event_list = self._selector.select(timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leona\anaconda3\Lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\leona\anaconda3\Lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 10038] Tentativo di operazione su un elemento diverso dal socket

**Comment by leobargigli** [comment]
I tried but with no result.
Finally I had to restore windows to make jupyter work.

Il giorno mar 6 ago 2024 alle ore 18:30 Rosio ***@***.***> ha
scritto:
