### ISSUE TITLE
Issue while installing Jupyter on Ubuntu 14.4 32 bit

### ISSUE THREAD

**Issue by AgazW** [jupyter/notebook#745]
I am trying to install Jupyter on my 32 bit machine. I use 

`pip3 install jupyter`

Getting some downloading, warning and finally the following error

Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/__pycache__'

Storing debug log for failure in /home/hussain/.pip/pip.log

**Comment by hosemn** [comment]
It looks like a permissions error, have you tried `sudo pip3 install 
jupyter`? Looking back at my notes from when I installed Jupyter a few 
months ago, I definitely used `sudo` (and I also installed from pip 
using Python 3).

**Comment by AgazW** [comment]
Thanks i got it. Why without `sudo` does not work.
