### ISSUE TITLE
No syntax highlighting in Chrome

### ISSUE THREAD

**Issue by soerenwolfers** [jupyter/notebook#7459]
## Description

No syntax highlighting in Chrome.

## Reproduce

Create notebook. Write Python.

## Expected behavior

Green import and print statements

## Context

- Operating System and version: Ubuntu 22.04
- Browser and version:  Chrome 128 
- Jupyter Notebook version: 7.2.2

<details><summary>Troubleshoot Output</summary>
<pre>
[notice] A new release of pip is available: 23.0.1 -> 24.2
[notice] To update, run: pip install --upgrade pip
$PATH:
	/home/sdf/fuck/bin
	/usr/local/src/anaconda3/bin
	/createsubmission
	/home/sdf/.local/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin

sys.path:
	/home/sdf/fuck/bin
	/usr/lib/python39.zip
	/usr/lib/python3.9
	/usr/lib/python3.9/lib-dynload
	/home/sdf/fuck/lib/python3.9/site-packages

sys.executable:
	/home/sdf/fuck/bin/python3.9

sys.version:
	3.9.20 (main, Sep  7 2024, 18:35:26) 
	[GCC 9.4.0]

platform.platform():
	Linux-5.15.0-117-generic-x86_64-with-glibc2.31

which -a jupyter:
	/home/sdf/fuck/bin/jupyter

pip list:
	Package                   Version
	------------------------- --------------
	anyio                     4.4.0
	argon2-cffi               23.1.0
	argon2-cffi-bindings      21.2.0
	arrow                     1.3.0
	asttokens                 2.4.1
	async-lru                 2.0.4
	attrs                     24.2.0
	babel                     2.16.0
	beautifulsoup4            4.12.3
	bleach                    6.1.0
	certifi                   2024.8.30
	cffi                      1.17.1
	charset-normalizer        3.3.2
	comm                      0.2.2
	debugpy                   1.8.5
	decorator                 5.1.1
	defusedxml                0.7.1
	exceptiongroup            1.2.2
	executing                 2.1.0
	fastjsonschema            2.20.0
	fqdn                      1.5.1
	h11                       0.14.0
	httpcore                  1.0.5
	httpx                     0.27.2
	idna                      3.8
	importlib_metadata        8.4.0
	ipykernel                 6.29.5
	ipython                   8.18.1
	isoduration               20.11.0
	jedi                      0.19.1
	Jinja2                    3.1.4
	json5                     0.9.25
	jsonpointer               3.0.0
	jsonschema                4.23.0
	jsonschema-specifications 2023.12.1
	jupyter_client            8.6.2
	jupyter_core              5.7.2
	jupyter-events            0.10.0
	jupyter-lsp               2.2.5
	jupyter_server            2.14.2
	jupyter_server_terminals  0.5.3
	jupyterlab                4.2.5
	jupyterlab_pygments       0.3.0
	jupyterlab_server         2.27.3
	MarkupSafe                2.1.5
	matplotlib-inline         0.1.7
	mistune                   3.0.2
	nbclient                  0.10.0
	nbconvert                 7.16.4
	nbformat                  5.10.4
	nest-asyncio              1.6.0
	notebook                  7.2.2
	notebook_shim             0.2.4
	overrides                 7.7.0
	packaging                 24.1
	pandocfilters             1.5.1
	parso                     0.8.4
	pexpect                   4.9.0
	pip                       23.0.1
	platformdirs              4.3.2
	prometheus_client         0.20.0
	prompt_toolkit            3.0.47
	psutil                    6.0.0
	ptyprocess                0.7.0
	pure_eval                 0.2.3
	pycparser                 2.22
	Pygments                  2.18.0
	python-dateutil           2.9.0.post0
	python-json-logger        2.0.7
	PyYAML                    6.0.2
	pyzmq                     26.2.0
	referencing               0.35.1
	requests                  2.32.3
	rfc3339-validator         0.1.4
	rfc3986-validator         0.1.1
	rpds-py                   0.20.0
	Send2Trash                1.8.3
	setuptools                58.1.0
	six                       1.16.0
	sniffio                   1.3.1
	soupsieve                 2.6
	stack-data                0.6.3
	terminado                 0.18.1
	tinycss2                  1.3.0
	tomli                     2.0.1
	tornado                   6.4.1
	traitlets                 5.14.3
	types-python-dateutil     2.9.0.20240906
	typing_extensions         4.12.2
	uri-template              1.3.0
	urllib3                   2.2.2
	wcwidth                   0.2.13
	webcolors                 24.8.0
	webencodings              0.5.1
	websocket-client          1.8.0
	zipp                      3.20.1
Click to add a cell.
</pre>
</details>

<details><summary>Browser Output</summary>
<pre>
content.js:1 [Deprecation] Listener added for a 'DOMNodeInserted' mutation event. Support for this event type has been removed, and this event will no longer be fired. See https://chromestatus.com/feature/5083947249172480 for more information.
(anonymous) @ content.js:1
Show 1 more frame
Show less
7819.bundle.js:1 Language pack 'en_GB' not installed!
fetch @ 7819.bundle.js:1
5649.bundle.js:1 Menu entry for command 'filemenu:close-and-cleanup' is duplicated.
(anonymous) @ 5649.bundle.js:1
5649.bundle.js:1 Menu entry for command 'application:close' is duplicated.
(anonymous) @ 5649.bundle.js:1
3676.bundle.js:1 Starting WebSocket: ws://localhost:8888/api/kernels/34037ee1-3259-4979-a8d0-b7a5523dd6df
3676.bundle.js:1 Starting WebSocket: ws://localhost:8888/api/kernels/6de37a6d-33dd-494e-8e00-f997cf4a3381
5263.bundle.js:1 Failed to load language for 'text/x-ipython'. TypeError: Cannot read properties of undefined (reading 'call')
    at v (bundle.js:1:516)
    at 12552 (2552.bundle.js:1:250)
    at Function.v (bundle.js:1:516)
    at async N.load [as loadFunc] (5263.bundle.js:1:105969)
    at async Ai.getLanguage (5263.bundle.js:1:100544)
5263.bundle.js:1 Failed to load language for 'text/x-ipython'. ReferenceError: Cannot access 'v' before initialization
    at Module.pythonLanguage (2552.bundle.js:1:229)
    at N.load [as loadFunc] (5263.bundle.js:1:106038)
    at async Ai.getLanguage (5263.bundle.js:1:100544)
5263.bundle.js:1 Failed to load language for 'text/x-ipython'. ReferenceError: Cannot access 'v' before initialization
    at Module.pythonLanguage (2552.bundle.js:1:229)
    at N.load [as loadFunc] (5263.bundle.js:1:106038)
    at async Ai.getLanguage (5263.bundle.js:1:100544)
5263.bundle.js:1 Failed to load language for 'text/x-ipython'. ReferenceError: Cannot access 'v' before initialization
    at Module.pythonLanguage (2552.bundle.js:1:229)
    at N.load [as loadFunc] (5263.bundle.js:1:106038)
    at async Ai.getLanguage (5263.bundle.js:1:100544)

</pre>
</details>

**Comment by krassowski** [comment]
Can you add a screenshot demonstrating the issue please?

**Comment by soerenwolfers** [comment]
@krassowski Sorry, had taken the screenshot but not pasted in. Edited the OP now to add it.

**Comment by krassowski** [comment]
Does it happen consistently? Does it also happen in 7.2.1?

**Comment by soerenwolfers** [comment]
Does happen across laptop restarts, complete browser refreshes, and in all notebooks.

Problem does**n't** exist on Firefox+Notebook7.2.2.
Problem does**n't** exist on Chrome+Notebook7.1.1. (and I can persistently obtain this fix by pip installing this notebook version)
Problem **does** exist on Chrome+(Notebook7.2.1 and Notebook7.2.2). (and I can persistently reproduce the problem by pip installing these notebook versions)

**Comment by Mohammad-MZ** [comment]
hi, i have the same problem on chromium   with Notebook7.2 & Notebook7.1
Firefox is fine,
i have python 3.9 as well.
