### ISSUE TITLE
UnicodeDecodeError: 'utf8' codec can't decode byte 0xfd in position 932: invalid start byte

### ISSUE THREAD

**Issue by muthu1086** [jupyter/notebook#780]
Not able to run anything from jupyter notebook. got following errors in terminal,

```
[I 14:49:51.180 NotebookApp] Creating new notebook in
[I 14:49:52.018 NotebookApp] Kernel started: d661309d-daf3-4daf-9589-bd826b29ad9e
[E 14:49:52.019 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/notebook/base/handlers.py", line 436, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/usr/local/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 56, in post
        model = sm.create_session(path=path, kernel_name=kernel_name)
      File "/usr/local/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 68, in create_session
        kernel_id=kernel_id)
      File "/usr/local/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 94, in save_session
        return self.get_session(session_id=session_id)
      File "/usr/local/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 125, in get_session
        self.cursor.execute(query, list(kwargs.values()))
    "OperationalError: Could not decode to UTF-8 column 'kernel_id' with text '\xfd\xa0\x81\xa4\xfc\x90\x80\xb6\xfc\x80\x80\xb3\xf9\x80\x80\xb9\xf9\x80\x80\xad\xf9\xa0\x81\xa1\xfb\x90\x80\xb3\xf9\x80\x80\xb4\xf9\xa0\x81\xa1\xfe\x90\x80\xad\xfe\x80\x80\xb5\xfb\x90\x80\xb9\xf9\x80\x81\xa2\xfc\xa0\x80\xb8\xf8\xa0\x80\xb6\xfe\x90\x80\xb2\xf9\x80\x81\xa1\xf9\x90\x80\xb9\xfc\xb0\x80\x80'"
[E 14:49:52.020 NotebookApp] Uncaught exception POST /api/sessions (10.10.25.62)
    HTTPServerRequest(protocol='http', host='10.10.10.25:8888', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='10.10.25.62', headers={'Origin': 'http://10.10.10.25:8888', 'Content-Length': '77', 'Accept-Language': 'en-GB,en-US;q=0.8,en;q=0.6', 'Accept-Encoding': 'gzip, deflate', 'Host': '10.10.10.25:8888', 'Accept': 'application/json, text/javascript, */*; q=0.01', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36', 'Connection': 'keep-alive', 'X-Requested-With': 'XMLHttpRequest', 'Referer': 'http://10.10.10.25:8888/notebooks/Untitled1.ipynb?kernel_name=python2', 'Content-Type': 'application/json'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1445, in _execute
        result = yield result
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1008, in run
        value = future.result()
      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 282, in wrapper
        yielded = next(result)
      File "/usr/local/lib/python2.7/site-packages/notebook/base/handlers.py", line 454, in wrapper
        self.finish(json.dumps(reply))
      File "/usr/local/lib/python2.7/json/__init__.py", line 243, in dumps
        return _default_encoder.encode(obj)
      File "/usr/local/lib/python2.7/json/encoder.py", line 207, in encode
        chunks = self.iterencode(o, _one_shot=True)
      File "/usr/local/lib/python2.7/json/encoder.py", line 270, in iterencode
        return _iterencode(o, 0)
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xfd in position 932: invalid start byte
[E 14:49:52.040 NotebookApp] Exception in exception handler
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1450, in _execute
        self._handle_request_exception(e)
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1504, in _handle_request_exception
        self.send_error(500, exc_info=sys.exc_info())
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 978, in send_error
        self.finish()
      File "/usr/local/lib/python2.7/site-packages/notebook/base/handlers.py", line 375, in finish
        return super(APIHandler, self).finish(*args, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 934, in finish
        self._log()
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1474, in _log
        self.application.log_request(self)
      File "/usr/local/lib/python2.7/site-packages/tornado/web.py", line 1936, in log_request
        self.settings["log_function"](handler)
      File "/usr/local/lib/python2.7/site-packages/notebook/log.py", line 46, in log_request
        log_method(json.dumps(request.headers, indent=2))
      File "/usr/local/lib/python2.7/json/__init__.py", line 250, in dumps
        sort_keys=sort_keys, **kw).encode(obj)
      File "/usr/local/lib/python2.7/json/encoder.py", line 209, in encode
        chunks = list(chunks)
      File "/usr/local/lib/python2.7/json/encoder.py", line 442, in _iterencode
        o = _default(o)
      File "/usr/local/lib/python2.7/json/encoder.py", line 184, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: <tornado.httputil.HTTPHeaders object at 0x7f5c968a8450> is not JSON serializable
^C[I 14:50:07.391 NotebookApp] interrupted
```

Kernels

```
[hadoop2@nn01 ipython]$ jupyter kernelspec list
Available kernels:
  python2    /usr/local/share/jupyter/kernels/python2
```

**Comment by takluyver** [comment]
It looks like some random bytes are getting into the in-memory sqlite database used to store the mappings of sessions, kernels and notebooks.

Can you find [this line](https://github.com/jupyter/notebook/blob/addc7eb5d91c0c21a9dfd0dda3e2f99884b6b7f4/notebook/services/sessions/sessionmanager.py#L91) in your installed copy of the notebook, and insert before it:

```python
print(repr(kernel_id))
```

Then try starting it again and look to see what output that's producing.

**Comment by methodds** [comment]
I seem to have a similar problem with Anacaonda for Python3.5 x64 on a Windows system. I think that I inserted the print statement before the line you mentioned in the sessionmanager, but didn't notice anything in the exception output:


`````
C:\Users\kasus>jupyter notebook
[I 21:35:07.491 NotebookApp] Serving notebooks from local directory: E:\Dropbox\
kasus\workspace\Python\iPython
[I 21:35:07.491 NotebookApp] 0 active kernels
[I 21:35:07.491 NotebookApp] The IPython Notebook is running at: http://localhos
t:8888/
[I 21:35:07.491 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip confirmation).
[W 21:35:12.162 NotebookApp] Notebook Crawler.ipynb is not trusted
[E 21:35:12.316 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "C:\Users\kasus\Anaconda3\lib\site-packages\notebook\base\handlers.py
", line 436, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "C:\Users\kasus\Anaconda3\lib\site-packages\notebook\services\session
s\handlers.py", line 56, in post
        model = sm.create_session(path=path, kernel_name=kernel_name)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\notebook\services\session
s\sessionmanager.py", line 66, in create_session
        kernel_name=kernel_name)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\notebook\services\kernels
\kernelmanager.py", line 84, in start_kernel
        **kwargs)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\jupyter_client\multikerne
lmanager.py", line 109, in start_kernel
        km.start_kernel(**kwargs)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\jupyter_client\manager.py
", line 244, in start_kernel
        **kw)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\jupyter_client\manager.py
", line 190, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\jupyter_client\launcher.p
y", line 108, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "C:\Users\kasus\Anaconda3\lib\subprocess.py", line 950, in __init__
        restore_signals, start_new_session)
      File "C:\Users\kasus\Anaconda3\lib\subprocess.py", line 1220, in _execute_
child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
[E 21:35:12.331 NotebookApp] Uncaught exception POST /api/sessions (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='POST', uri
='/api/sessions', version='HTTP/1.1', remote_ip='::1', headers={'Accept': 'appli
cation/json, text/javascript, */*; q=0.01', 'Origin': 'http://localhost:8888', '
Referer': 'http://localhost:8888/notebooks/Crawler.ipynb', 'Host': 'localhost:88
88', 'X-Requested-With': 'XMLHttpRequest', 'Content-Length': '75', 'Content-Type
': 'application/json', 'Connection': 'keep-alive', 'Accept-Encoding': 'gzip, def
late', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (K
HTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36', 'Accept-Language': 'en,en
-US;q=0.8,de-DE;q=0.6,de;q=0.4'})
    Traceback (most recent call last):
      File "C:\Users\kasus\Anaconda3\lib\site-packages\notebook\base\handlers.py
", line 436, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "C:\Users\kasus\Anaconda3\lib\site-packages\notebook\services\session
s\handlers.py", line 56, in post
        model = sm.create_session(path=path, kernel_name=kernel_name)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\notebook\services\session
s\sessionmanager.py", line 66, in create_session
        kernel_name=kernel_name)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\notebook\services\kernels
\kernelmanager.py", line 84, in start_kernel
        **kwargs)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\jupyter_client\multikerne
lmanager.py", line 109, in start_kernel
        km.start_kernel(**kwargs)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\jupyter_client\manager.py
", line 244, in start_kernel
        **kw)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\jupyter_client\manager.py
", line 190, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\jupyter_client\launcher.p
y", line 108, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "C:\Users\kasus\Anaconda3\lib\subprocess.py", line 950, in __init__
        restore_signals, start_new_session)
      File "C:\Users\kasus\Anaconda3\lib\subprocess.py", line 1220, in _execute_
child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\kasus\Anaconda3\lib\site-packages\tornado\web.py", line 144
5, in _execute
        result = yield result
      File "C:\Users\kasus\Anaconda3\lib\site-packages\tornado\gen.py", line 100
8, in run
        value = future.result()
      File "C:\Users\kasus\Anaconda3\lib\site-packages\tornado\concurrent.py", l
ine 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "C:\Users\kasus\Anaconda3\lib\site-packages\tornado\gen.py", line 282
, in wrapper
        yielded = next(result)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\notebook\base\handlers.py
", line 454, in wrapper
        self.finish(json.dumps(reply))
      File "C:\Users\kasus\Anaconda3\lib\site-packages\notebook\base\handlers.py
", line 375, in finish
        return super(APIHandler, self).finish(*args, **kwargs)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\tornado\web.py", line 934
, in finish
        self._log()
      File "C:\Users\kasus\Anaconda3\lib\site-packages\tornado\web.py", line 147
4, in _log
        self.application.log_request(self)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\tornado\web.py", line 193
6, in log_request
        self.settings["log_function"](handler)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\notebook\log.py", line 46
, in log_request
        log_method(json.dumps(request.headers, indent=2))
      File "C:\Users\kasus\Anaconda3\lib\json\__init__.py", line 237, in dumps
        **kw).encode(obj)
      File "C:\Users\kasus\Anaconda3\lib\json\encoder.py", line 201, in encode
        chunks = list(chunks)
      File "C:\Users\kasus\Anaconda3\lib\json\encoder.py", line 436, in _iterenc
ode
        o = _default(o)
      File "C:\Users\kasus\Anaconda3\lib\json\encoder.py", line 180, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: <tornado.httputil.HTTPHeaders object at 0x000000503193A940> is no
t JSON serializable
[E 21:35:12.341 NotebookApp] Cannot send error response after headers written
[E 21:35:12.341 NotebookApp] Failed to flush partial response
    Traceback (most recent call last):
      File "C:\Users\kasus\Anaconda3\lib\site-packages\notebook\base\handlers.py
", line 436, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "C:\Users\kasus\Anaconda3\lib\site-packages\notebook\services\session
s\handlers.py", line 56, in post
        model = sm.create_session(path=path, kernel_name=kernel_name)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\notebook\services\session
s\sessionmanager.py", line 66, in create_session
        kernel_name=kernel_name)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\notebook\services\kernels
\kernelmanager.py", line 84, in start_kernel
        **kwargs)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\jupyter_client\multikerne
lmanager.py", line 109, in start_kernel
        km.start_kernel(**kwargs)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\jupyter_client\manager.py
", line 244, in start_kernel
        **kw)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\jupyter_client\manager.py
", line 190, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\jupyter_client\launcher.p
y", line 108, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "C:\Users\kasus\Anaconda3\lib\subprocess.py", line 950, in __init__
        restore_signals, start_new_session)
      File "C:\Users\kasus\Anaconda3\lib\subprocess.py", line 1220, in _execute_
child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\kasus\Anaconda3\lib\site-packages\tornado\web.py", line 144
5, in _execute
        result = yield result
      File "C:\Users\kasus\Anaconda3\lib\site-packages\tornado\gen.py", line 100
8, in run
        value = future.result()
      File "C:\Users\kasus\Anaconda3\lib\site-packages\tornado\concurrent.py", l
ine 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "C:\Users\kasus\Anaconda3\lib\site-packages\tornado\gen.py", line 282
, in wrapper
        yielded = next(result)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\notebook\base\handlers.py
", line 454, in wrapper
        self.finish(json.dumps(reply))
      File "C:\Users\kasus\Anaconda3\lib\site-packages\notebook\base\handlers.py
", line 375, in finish
        return super(APIHandler, self).finish(*args, **kwargs)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\tornado\web.py", line 934
, in finish
        self._log()
      File "C:\Users\kasus\Anaconda3\lib\site-packages\tornado\web.py", line 147
4, in _log
        self.application.log_request(self)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\tornado\web.py", line 193
6, in log_request
        self.settings["log_function"](handler)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\notebook\log.py", line 46
, in log_request
        log_method(json.dumps(request.headers, indent=2))
      File "C:\Users\kasus\Anaconda3\lib\json\__init__.py", line 237, in dumps
        **kw).encode(obj)
      File "C:\Users\kasus\Anaconda3\lib\json\encoder.py", line 201, in encode
        chunks = list(chunks)
      File "C:\Users\kasus\Anaconda3\lib\json\encoder.py", line 436, in _iterenc
ode
        o = _default(o)
      File "C:\Users\kasus\Anaconda3\lib\json\encoder.py", line 180, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: <tornado.httputil.HTTPHeaders object at 0x000000503193A940> is no
t JSON serializable

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\kasus\Anaconda3\lib\site-packages\tornado\web.py", line 960
, in send_error
        self.finish()
      File "C:\Users\kasus\Anaconda3\lib\site-packages\notebook\base\handlers.py
", line 375, in finish
        return super(APIHandler, self).finish(*args, **kwargs)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\tornado\web.py", line 934
, in finish
        self._log()
      File "C:\Users\kasus\Anaconda3\lib\site-packages\tornado\web.py", line 147
4, in _log
        self.application.log_request(self)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\tornado\web.py", line 193
6, in log_request
        self.settings["log_function"](handler)
      File "C:\Users\kasus\Anaconda3\lib\site-packages\notebook\log.py", line 46
, in log_request
        log_method(json.dumps(request.headers, indent=2))
      File "C:\Users\kasus\Anaconda3\lib\json\__init__.py", line 237, in dumps
        **kw).encode(obj)
      File "C:\Users\kasus\Anaconda3\lib\json\encoder.py", line 201, in encode
        chunks = list(chunks)
      File "C:\Users\kasus\Anaconda3\lib\json\encoder.py", line 436, in _iterenc
ode
        o = _default(o)
      File "C:\Users\kasus\Anaconda3\lib\json\encoder.py", line 180, in default
        raise TypeError(repr(o) + " is not JSON serializable")
    TypeError: <tornado.httputil.HTTPHeaders object at 0x000000503193A940> is no
t JSON serializable
``````

Reinstalling my Anaconda environment did not fix the problem.

**Comment by minrk** [comment]
FileNotFound suggests that there may be a stale kernelspec. What do you get from:

    jupyter kernelspec list

**Comment by methodds** [comment]
The output looks like this:
````
Available kernels:
  stata      C:\Users\kasus\.ipython\kernels\stata
  python3    C:\ProgramData\jupyter\kernels\python3
````

**Comment by minrk** [comment]
Can you do `python3 -m ipykernel install` and see if it works again after that?

**Comment by methodds** [comment]
thank you very much! ```python -m ipykernel install``` fixed the problem :)

**Comment by LiZhenchong** [comment]
@muthu1086 I have just met the same issue in python 2.7. 
I solve it by reinstalling python with

```
--enable-loadable-sqlite-extensions
```
config.

The reason is that jupyter use sqlite for it's data storing. We have to add sqlite extensions for python 2.x.
We all know that python 2.x has a long story about Unicode. 

At last, don't forget to use
```

upyter kernelspec install-self
```
to reinstall your jupyter kernel.

Hope it's useful.

**Comment by Carreau** [comment]
Closing as this is likely fixed.

**Comment by henryon** [comment]
@LiZhenchong  I've just tried your ways. still get exception.
could you add more detail steps. reinstall python, what about other pkgs . reinstall or not? 

Exception as below:

I 09:58:23.079 NotebookApp] Kernel started: 5eb76e3c-ed0f-4b0d-ab29-a3d2c11695b0
[E 09:58:23.080 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/notebook/base/handlers.py", line 457, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
        yielded = self.gen.throw(*exc_info)
      File "/usr/local/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 62, in post
        kernel_id=kernel_id))
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
        value = future.result()
      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 1024, in run
        yielded = self.gen.send(value)
      File "/usr/local/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 81, in create_session
        self.save_session(session_id, path=path, kernel_id=kernel_id)
      File "/usr/local/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 121, in save_session
        return self.get_session(session_id=session_id)
      File "/usr/local/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 152, in get_session
        self.cursor.execute(query, list(kwargs.values()))
    "OperationalError: Could not decode to UTF-8 column 'kernel_id' with text '\xf9\x90\x80\xb5\xfd\xb0\x81\xa2\xf9\x90\x80\xb6\xf8\xb0\x80\xb3\xf9\x90\x80\xad\xfc\x80\x81\xa4\xfb\x90\x81\xa6\xf8\xa0\x80\xb4\xf9\x80\x80\xb0\xf8\x90\x80\xad\xfc\xa0\x81\xa2\xfb\x90\x80\xb9\xfc\xb0\x81\xa1\xfc\xa0\x81\xa4\xfc\x90\x81\xa3\xfd\xa0\x80\xb1\xfd\x90\x80\xb9\xfc\x80\x81\xa2'"
[E 09:58:23.081 NotebookApp] Uncaught exception POST /api/sessions

**Comment by pinkman61** [comment]
Please tell me how to resolve this. Above things are not working.

pinkman@pinkman:~$ anaconda-navigator
Traceback (most recent call last):
  File "/home/pinkman/anaconda2/bin/anaconda-navigator", line 11, in <module>
    sys.exit(main())
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/app/main.py", line 125, in main
    from anaconda_navigator.utils.logs import clean_logs
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/utils/logs.py", line 18, in <module>
    from anaconda_navigator.config import (LOG_FILENAME, LOG_FOLDER,
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/config/__init__.py", line 24, in <module>
    from anaconda_navigator.config.main import CONF
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/config/main.py", line 67, in <module>
    raw_mode=True,
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/config/user.py", line 221, in __init__
    self.load_from_ini()
  File "/home/pinkman/anaconda2/lib/python2.7/site-packages/anaconda_navigator/config/user.py", line 275, in load_from_ini
    self.readfp(conf_file)
  File "/home/pinkman/anaconda2/lib/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/home/pinkman/anaconda2/lib/python2.7/ConfigParser.py", line 479, in _read
    line = fp.readline()
  File "/home/pinkman/anaconda2/lib/python2.7/codecs.py", line 690, in readline
    return self.reader.readline(size)
  File "/home/pinkman/anaconda2/lib/python2.7/codecs.py", line 545, in readline
    data = self.read(readsize, firstline=True)
  File "/home/pinkman/anaconda2/lib/python2.7/codecs.py", line 492, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x88 in position 2: invalid start byte
