### ISSUE TITLE
Check for `jupyter_declarativewidgets`?

### ISSUE THREAD

**Issue by jackmaney** [jupyter/notebook#933]
OS X 10.9.5

Python `3.5.0`

`jupyter` version `1.0.0`

`notebook` version `4.0.6`

`ipython` version `4.0.1` (in case that's relevant).

Lately, whenever I've tried `jupyter notebook` or `ipython notebook`, I got the following stack trace, which is always spat out three times in the terminal:

```
[W 14:37:24.649 NotebookApp] Error loading server extension urth.widgets.ext.urth_import
    Traceback (most recent call last):
      File "/Users/[username]/.pyenv/versions/stochastic-order/lib/python3.5/site-packages/notebook/notebookapp.py", line 991, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/Users/[username]/.pyenv/versions/3.5.0/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
    ImportError: No module named 'urth'
```

Doing a bit of digging, I found `urth` to be part of [`jupyter_declarativewidgets`](https://github.com/jupyter-incubator/declarativewidgets). After doing a `pip install jupyter_declarativewidgets`, the stack traces went away.

I'm not going to pretend to understand exactly what's going on in that package or if it's absolutely necessary, but would it be worth considering the addition of `jupyter_declarativewidgets` as a prerequisite?

Thank you for your time.

**Comment by minrk** [comment]
That's definitely not a dependency. What appears to have happened is that jupyter_declarativewidgets was installed at some point on your system, and was registered as a notebook server extension. Subsequently, you have set up an env without it, or otherwise uninstalled it, but it's still registered as an extension in config. What's failing is the loading of the extension (that's the `init_server_extensions` part). You can look for `jupyter_declarativewidgets` in `~/.jupyter/jupyter_notebook_config.{py,json}` and see where it is added to your configuration, and remove it there.

**Comment by jackmaney** [comment]
Thanks for the quick reply, and my apologies for the misunderstanding.
