### ISSUE TITLE
Travis Build Error.

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#956]
Travis seem to be stuck reliably on Python 3.5 ( I restarted 5-6 times this morning, it stuck during coverage report)

I can't figure out why. 

can I get some help ?

**Comment by takluyver** [comment]
I've prodded it to retry just in case it's sulking at you for some reason.

I wonder if coverage has some minor issue on Python 3.5, maybe only 3.5.1?

**Comment by jdfreder** [comment]
Travis was borking up a few days ago.  Just because it's Travis.  All the tests in ipywidgets were failing.  Went to sleep, and the next day Travis was happy.  He probably got food poisoning or something.

**Comment by Carreau** [comment]
I locally have an thread error with sqlite exactly where the build breaks:

```
OK (SKIP=1)
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/history.py", line 755, in writeout_cache
    self._writeout_input_cache(conn)
  File "/Users/bussonniermatthias/dev/ipython/IPython/core/history.py", line 739, in _writeout_input_cache
    (self.session_number,)+line)
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 4377808896 and this is thread id 140735277753088
````

**Comment by takluyver** [comment]
I don't see an error locally. And I can't work out how the error you see makes sense - atexit functions should run on the main thread, which should also be where the history database connection was opened.

And if it's hanging producing the coverage report after the notebook tests, what's an IPython traceback doing there? :-S

**Comment by takluyver** [comment]
I've also seen this nasty looking traceback on Travis a couple of times. I think either there's an as-yet-unknown bug in Python itself, or there's something rotten in the state of Travis.

```
Fatal Python error: PyImport_GetModuleDict: no module dictionary!
Thread 0x00007f4693374700 (most recent call first):
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/ipykernel/parentpoller.py", line 37 in run
  File "/opt/python/3.5.0/lib/python3.5/threading.py", line 923 in _bootstrap_inner
  File "/opt/python/3.5.0/lib/python3.5/threading.py", line 891 in _bootstrap

Thread 0x00007f46a1826700 (most recent call first):
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/ipykernel/heartbeat.py", line 61 in run
  File "/opt/python/3.5.0/lib/python3.5/threading.py", line 923 in _bootstrap_inner
  File "/opt/python/3.5.0/lib/python3.5/threading.py", line 891 in _bootstrap

Current thread 0x00007f46aba39700 (most recent call first):
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/traitlets/traitlets.py", line 1076 in on_trait_change
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/IPython/core/extensions.py", line 64 in __del__

.Fatal Python error: PyImport_GetModuleDict: no module dictionary!

Thread 0x00007f01dbfff700 (most recent call first):
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/ipykernel/parentpoller.py", line 37 in run
  File "/opt/python/3.5.0/lib/python3.5/threading.py", line 923 in _bootstrap_inner
  File "/opt/python/3.5.0/lib/python3.5/threading.py", line 891 in _bootstrap

Thread 0x00007f01ea72a700 (most recent call first):
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/ipykernel/heartbeat.py", line 61 in run
  File "/opt/python/3.5.0/lib/python3.5/threading.py", line 923 in _bootstrap_inner
  File "/opt/python/3.5.0/lib/python3.5/threading.py", line 891 in _bootstrap

Current thread 0x00007f01f493d700 (most recent call first):
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/traitlets/traitlets.py", line 1076 in on_trait_change
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site-packages/IPython/core/extensions.py", line 64 in __del__

.Failed to import the site module

Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 1077, in _path_importer_cache
KeyError: '/home/travis/virtualenv/python3.5.0/lib/python3.5/lib-dynload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.0/lib/python3.5/site.py", line 69, in <module>
    import __builtin__ as builtins
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1136, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1107, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1079, in _path_importer_cache
  File "<frozen importlib._bootstrap_external>", line 1055, in _path_hooks
  File "<frozen importlib._bootstrap_external>", line 1300, in path_hook_for_FileFinder
  File "<frozen importlib._bootstrap_external>", line 96, in _path_isdir
  File "<frozen importlib._bootstrap_external>", line 81, in _path_is_mode_type
  File "<frozen importlib._bootstrap_external>", line 75, in _path_stat
KeyboardInterrupt
```

**Comment by takluyver** [comment]
(I just got that by re-running [this build](https://travis-ci.org/jupyter/notebook/jobs/102303145) - it somehow succeeded despite that error)

**Comment by jdfreder** [comment]
I'm telling you guys, just wait a day ;)

**Comment by Carreau** [comment]
> I'm telling you guys, just wait a day... ;)

We've already waited a day. It's ben broken for more than 24h.

**Comment by jdfreder** [comment]
> We've already waited a day. It's ben broken for more than 24h.

Aw okay, maybe he has a fatal injury.

**Comment by takluyver** [comment]
@Carreau did you work out where the SQLite error you saw locally was coming from? It's now happening on Jenkins: https://jenkins.jupyter.org/job/jack-of-none/128/console

**Comment by Carreau** [comment]
No haven't found.... :-(

**Comment by jdfreder** [comment]
The flu Travis had must have been contagious :trollface:

**Comment by takluyver** [comment]
I restarted Jenkins, and the error is gone... :confused:

**Comment by willingc** [comment]
@Carreau @takluyver I'm thinking this would be ok to close.

**Comment by Carreau** [comment]
Thanks @willingc !
